// AUTO-GENERATED. Course slug -> the units a teacher can target when assigning
// a unit test.
//
// Plain literals on purpose. Importing the configs in src/data/unit-tests/
// would pull all 35 question pools into a single module, which is enough to
// run the production build out of memory.
//
// sat-prep and mcat-prep are absent on purpose: they build their unit lists
// programmatically from domain data rather than declaring them, so there is
// nothing static to lift. Their unit picker falls back to "any unit in this
// course", which still assigns and still completes.
export interface UnitOption {
  id: string
  unitNumber: number
  name: string
}

const UNITS_BY_COURSE: Record<string, UnitOption[]> = {
  "act-prep": [{ id: "english", unitNumber: 1, name: "ACT English" }, { id: "math", unitNumber: 2, name: "ACT Math" }, { id: "reading", unitNumber: 3, name: "ACT Reading" }, { id: "science", unitNumber: 4, name: "ACT Science" }],
  "algebra-1": [{ id: "linear-equations", unitNumber: 1, name: "Unit 1: Solving Equations & Inequalities" }, { id: "linear-functions", unitNumber: 2, name: "Unit 2: Linear Functions & Graphing" }, { id: "systems", unitNumber: 3, name: "Unit 3: Systems of Equations" }, { id: "polynomials", unitNumber: 4, name: "Unit 4: Exponents & Polynomials" }, { id: "quadratics", unitNumber: 5, name: "Unit 5: Quadratic Equations" }, { id: "radicals-exponentials", unitNumber: 6, name: "Unit 6: Radicals & Exponential Functions" }, { id: "proportions", unitNumber: 7, name: "Unit 7: Ratios, Proportions & Percents" }, { id: "statistics", unitNumber: 8, name: "Unit 8: Data & Statistics" }],
  "algebra-2": [{ id: "equations-inequalities", unitNumber: 1, name: "Unit 1: Equations, Inequalities & Systems" }, { id: "quadratics", unitNumber: 2, name: "Unit 2: Quadratics & Complex Numbers" }, { id: "polynomials-rational", unitNumber: 3, name: "Unit 3: Polynomials & Rational Functions" }, { id: "exponential-log", unitNumber: 4, name: "Unit 4: Exponential & Logarithmic Functions" }, { id: "trigonometry-alg2", unitNumber: 5, name: "Unit 5: Trigonometry" }, { id: "sequences-probability", unitNumber: 6, name: "Unit 6: Sequences, Series & Probability" }],
  "ap-african-american-studies": [{ id: "origins-diaspora", unitNumber: 1, name: "Unit 1: Origins of the African Diaspora" }, { id: "freedom-enslavement", unitNumber: 2, name: "Unit 2: Freedom, Enslavement & Resistance" }, { id: "practice-freedom", unitNumber: 3, name: "Unit 3: The Practice of Freedom" }, { id: "movements-debates", unitNumber: 4, name: "Unit 4: Movements & Debates" }],
  "ap-biology": [{ id: "cell-structure", unitNumber: 1, name: "Unit 1\u20132: Chemistry of Life & Cell Structure" }, { id: "cell-communication", unitNumber: 2, name: "Unit 3\u20134: Cellular Energetics & Communication" }, { id: "heredity", unitNumber: 3, name: "Unit 5: Heredity" }, { id: "gene-expression", unitNumber: 4, name: "Unit 6: Gene Expression & Regulation" }, { id: "natural-selection", unitNumber: 5, name: "Unit 7: Natural Selection & Evolution" }, { id: "ecology", unitNumber: 6, name: "Unit 8: Ecology" }],
  "ap-calculus-ab": [{ id: "limits", unitNumber: 1, name: "Unit 1: Limits & Continuity" }, { id: "differentiation", unitNumber: 2, name: "Unit 2\u20133: Differentiation" }, { id: "applications-derivatives", unitNumber: 3, name: "Unit 4\u20135: Applications of Differentiation" }, { id: "integration", unitNumber: 4, name: "Unit 6: Integration & Accumulation" }, { id: "diffeq", unitNumber: 5, name: "Unit 7: Differential Equations" }, { id: "applications-integration", unitNumber: 6, name: "Unit 8: Applications of Integration" }],
  "ap-calculus-bc": [{ id: "limits", unitNumber: 1, name: "Unit 1: Limits & Continuity" }, { id: "differentiation", unitNumber: 2, name: "Unit 2\u20133: Differentiation" }, { id: "applications-derivatives", unitNumber: 3, name: "Unit 4\u20135: Applications of Differentiation" }, { id: "integration", unitNumber: 4, name: "Unit 6: Integration & Accumulation" }, { id: "diffeq", unitNumber: 5, name: "Unit 7: Differential Equations" }, { id: "applications-integration", unitNumber: 6, name: "Unit 8: Applications of Integration" }, { id: "parametric-polar-vector", unitNumber: 7, name: "Unit 9: Parametric, Polar & Vector Functions" }, { id: "sequences-series", unitNumber: 8, name: "Unit 10: Infinite Sequences & Series" }],
  "ap-chemistry": [{ id: "atomic-structure", unitNumber: 1, name: "Unit 1: Atomic Structure & Properties" }, { id: "bonding", unitNumber: 2, name: "Unit 2: Compound Structure & Bonding" }, { id: "imf", unitNumber: 3, name: "Unit 3: Properties of Substances & Mixtures" }, { id: "reactions", unitNumber: 4, name: "Unit 4: Chemical Reactions" }, { id: "kinetics", unitNumber: 5, name: "Unit 5: Kinetics" }, { id: "thermodynamics", unitNumber: 6, name: "Unit 6: Thermodynamics" }, { id: "equilibrium", unitNumber: 7, name: "Unit 7: Equilibrium" }, { id: "acids-bases", unitNumber: 8, name: "Unit 8: Acids & Bases" }, { id: "electrochemistry", unitNumber: 9, name: "Unit 9: Applications of Thermodynamics & Electrochemistry" }],
  "ap-computer-science-a": [{ id: "primitive-types", unitNumber: 1, name: "Unit 1: Primitive Types" }, { id: "using-objects", unitNumber: 2, name: "Unit 2: Using Objects" }, { id: "conditionals", unitNumber: 3, name: "Unit 3: Boolean Expressions & If Statements" }, { id: "iteration", unitNumber: 4, name: "Unit 4: Iteration" }, { id: "writing-classes", unitNumber: 5, name: "Unit 5: Writing Classes" }, { id: "arrays", unitNumber: 6, name: "Unit 6: Array" }, { id: "arraylist", unitNumber: 7, name: "Unit 7: ArrayList" }, { id: "2d-array", unitNumber: 8, name: "Unit 8: 2D Array" }, { id: "inheritance", unitNumber: 9, name: "Unit 9: Inheritance" }],
  "ap-cs-principles": [{ id: "creative-development", unitNumber: 1, name: "Big Idea 1: Creative Development" }, { id: "data", unitNumber: 2, name: "Big Idea 2: Data" }, { id: "algorithms", unitNumber: 3, name: "Big Idea 3: Algorithms & Programming" }, { id: "computing-systems", unitNumber: 4, name: "Big Idea 4: Computing Systems & Networks" }, { id: "impact", unitNumber: 5, name: "Big Idea 5: Impact of Computing" }],
  "ap-english-language": [{ id: "rhetorical-situation", unitNumber: 1, name: "Unit 1: The Rhetorical Situation" }, { id: "claims-evidence", unitNumber: 2, name: "Unit 2: Claims & Evidence" }, { id: "reasoning-organization", unitNumber: 3, name: "Unit 3: Reasoning & Organization" }, { id: "style", unitNumber: 4, name: "Unit 4: Style" }, { id: "rhetorical-devices", unitNumber: 5, name: "Unit 5\u20137: Rhetorical Devices & Strategies" }, { id: "synthesis-argument", unitNumber: 6, name: "Unit 8\u20139: Synthesis & Argument" }],
  "ap-english-literature": [{ id: "short-fiction", unitNumber: 1, name: "Unit 1: Short Fiction I" }, { id: "poetry", unitNumber: 2, name: "Unit 2 & 5: Poetry" }, { id: "longer-fiction", unitNumber: 3, name: "Unit 3 & 6: Longer Fiction & Drama" }, { id: "character-narrative", unitNumber: 4, name: "Unit 4 & 7: Character & Narrative Technique" }, { id: "figurative-language", unitNumber: 5, name: "Unit 8: Figurative Language" }, { id: "analysis-argument", unitNumber: 6, name: "Unit 9: Literary Analysis & Argument" }],
  "ap-environmental-science": [{ id: "earth-systems", unitNumber: 1, name: "Unit 1\u20132: Earth Systems & Biodiversity" }, { id: "biodiversity", unitNumber: 2, name: "Unit 2: Biodiversity" }, { id: "populations", unitNumber: 3, name: "Unit 3: Populations" }, { id: "land-water", unitNumber: 4, name: "Unit 4\u20135: Land & Water Use" }, { id: "energy", unitNumber: 5, name: "Unit 6: Energy Resources & Consumption" }, { id: "pollution", unitNumber: 6, name: "Unit 7\u20139: Pollution & Global Change" }],
  "ap-human-geography": [{ id: "thinking-geographically", unitNumber: 1, name: "Unit 1: Thinking Geographically" }, { id: "population-migration", unitNumber: 2, name: "Unit 2: Population & Migration" }, { id: "cultural-patterns", unitNumber: 3, name: "Unit 3: Cultural Patterns & Processes" }, { id: "political-patterns", unitNumber: 4, name: "Unit 4: Political Patterns & Processes" }, { id: "agriculture", unitNumber: 5, name: "Unit 5: Agriculture & Rural Land Use" }, { id: "cities-urban", unitNumber: 6, name: "Unit 6: Cities & Urban Land Use" }, { id: "industrialization-development", unitNumber: 7, name: "Unit 7: Industrialization & Economic Development" }],
  "ap-macroeconomics": [{ id: "basic-concepts", unitNumber: 1, name: "Unit 1: Basic Economic Concepts" }, { id: "measurement", unitNumber: 2, name: "Unit 2: Economic Indicators & Business Cycle" }, { id: "national-income", unitNumber: 3, name: "Unit 3: National Income & Price Determination" }, { id: "financial-sector", unitNumber: 4, name: "Unit 4: Financial Sector" }, { id: "stabilization", unitNumber: 5, name: "Unit 5: Long-Run & Stabilization Policies" }, { id: "international", unitNumber: 6, name: "Unit 6: Open Economy \u2014 International Trade & Finance" }],
  "ap-microeconomics": [{ id: "basic-concepts", unitNumber: 1, name: "Unit 1: Basic Economic Concepts" }, { id: "supply-demand", unitNumber: 2, name: "Unit 2: Supply & Demand" }, { id: "production-cost", unitNumber: 3, name: "Unit 3: Production, Cost & Perfect Competition" }, { id: "imperfect-competition", unitNumber: 4, name: "Unit 4: Imperfect Competition" }, { id: "factor-markets", unitNumber: 5, name: "Unit 5: Factor Markets" }, { id: "market-failure", unitNumber: 6, name: "Unit 6: Market Failure & Government" }],
  "ap-physics-1": [{ id: "kinematics", unitNumber: 1, name: "Unit 1: Kinematics" }, { id: "dynamics", unitNumber: 2, name: "Unit 2: Dynamics (Newton\\u2019s Laws)" }, { id: "circular-motion-gravity", unitNumber: 3, name: "Unit 3: Circular Motion & Gravitation" }, { id: "energy", unitNumber: 4, name: "Unit 4: Energy" }, { id: "momentum", unitNumber: 5, name: "Unit 5: Momentum" }, { id: "simple-harmonic-motion", unitNumber: 6, name: "Unit 6: Simple Harmonic Motion" }, { id: "torque-rotation", unitNumber: 7, name: "Unit 7: Torque & Rotational Motion" }, { id: "fluids", unitNumber: 8, name: "Unit 8: Fluids" }],
  "ap-physics-2": [{ id: "waves-sound", unitNumber: 1, name: "Unit 1: Waves, Sound & Physical Optics" }, { id: "thermodynamics", unitNumber: 2, name: "Unit 2: Thermodynamics" }, { id: "electricity", unitNumber: 3, name: "Unit 3\u20134: Electric Force, Field & Potential" }, { id: "circuits", unitNumber: 4, name: "Unit 5: Circuits" }, { id: "magnetism", unitNumber: 5, name: "Unit 6: Magnetism & EM Induction" }, { id: "optics", unitNumber: 6, name: "Unit 7: Geometric & Physical Optics" }, { id: "modern-physics", unitNumber: 7, name: "Unit 8: Modern Physics" }],
  "ap-physics-c-em": [{ id: "electrostatics", unitNumber: 1, name: "Unit 1: Electrostatics" }, { id: "electric-potential", unitNumber: 2, name: "Unit 2: Electric Potential" }, { id: "capacitors-dielectrics", unitNumber: 3, name: "Unit 3: Capacitors & Dielectrics" }, { id: "circuits", unitNumber: 4, name: "Unit 4: Electric Circuits" }, { id: "magnetism-em-induction", unitNumber: 5, name: "Unit 5: Magnetism & Electromagnetic Induction" }],
  "ap-physics-c-mechanics": [{ id: "kinematics", unitNumber: 1, name: "Unit 1: Kinematics" }, { id: "work-energy-power", unitNumber: 3, name: "Unit 3: Work, Energy & Power" }, { id: "momentum", unitNumber: 4, name: "Unit 4: Systems of Particles & Linear Momentum" }, { id: "rotation-oscillation", unitNumber: 5, name: "Unit 5: Rotation & Oscillation" }],
  "ap-precalculus": [{ id: "polynomial-rational", unitNumber: 1, name: "Unit 1: Polynomial & Rational Functions" }, { id: "exp-log", unitNumber: 2, name: "Unit 2: Exponential & Logarithmic Functions" }, { id: "trig-polar", unitNumber: 3, name: "Unit 3: Trigonometric & Polar Functions" }, { id: "params-vectors-matrices", unitNumber: 4, name: "Unit 4: Functions Involving Parameters, Vectors & Matrices" }],
  "ap-psychology": [{ id: "history-approaches", unitNumber: 1, name: "Unit 1: History & Approaches" }, { id: "biological-bases", unitNumber: 2, name: "Unit 2: Biological Bases of Behavior" }, { id: "sensation-perception", unitNumber: 3, name: "Unit 3: Sensation & Perception" }, { id: "learning", unitNumber: 4, name: "Unit 4: Learning" }, { id: "memory", unitNumber: 5, name: "Unit 5: Cognitive Psychology \u2014 Memory" }, { id: "thinking-language", unitNumber: 6, name: "Unit 6: Cognition \u2014 Thinking & Language" }, { id: "developmental", unitNumber: 7, name: "Unit 7: Developmental Psychology" }, { id: "motivation-emotion", unitNumber: 8, name: "Unit 8: Motivation, Emotion & Personality" }, { id: "personality", unitNumber: 9, name: "Unit 9: Personality" }, { id: "disorders-treatment", unitNumber: 10, name: "Unit 10: Psychological Disorders & Treatment" }, { id: "social", unitNumber: 11, name: "Unit 11: Social Psychology" }],
  "ap-statistics": [{ id: "exploring-data", unitNumber: 1, name: "Unit 1\u20132: Exploring Data" }, { id: "sampling-experimentation", unitNumber: 2, name: "Unit 3: Sampling & Experimentation" }, { id: "probability", unitNumber: 3, name: "Unit 4\u20135: Probability, Random Variables & Distributions" }, { id: "confidence-intervals", unitNumber: 4, name: "Unit 6\u20137: Confidence Intervals" }, { id: "hypothesis-testing", unitNumber: 5, name: "Unit 6\u20137: Hypothesis Testing" }, { id: "regression", unitNumber: 6, name: "Unit 9: Regression & Inference for Slopes" }],
  "ap-us-government": [{ id: "foundations", unitNumber: 1, name: "Unit 1: Foundations of American Democracy" }, { id: "branches", unitNumber: 2, name: "Unit 2: Interactions Among Branches of Government" }, { id: "civil-liberties-rights", unitNumber: 3, name: "Unit 3: Civil Liberties & Civil Rights" }, { id: "political-ideology", unitNumber: 4, name: "Unit 4: American Political Ideologies & Beliefs" }, { id: "political-participation", unitNumber: 5, name: "Unit 5: Political Participation" }],
  "ap-us-history": [{ id: "period-1-2", unitNumber: 1, name: "Period 1\u20132: 1491\u20131754" }, { id: "period-3", unitNumber: 2, name: "Period 3: 1754\u20131800" }, { id: "period-4", unitNumber: 3, name: "Period 4: 1800\u20131848" }, { id: "period-5", unitNumber: 4, name: "Period 5: 1844\u20131877" }, { id: "period-6", unitNumber: 5, name: "Period 6: 1865\u20131898" }, { id: "period-7", unitNumber: 6, name: "Period 7\u20139: 1890\u2013Present" }],
  "ap-world-history": [{ id: "global-tapestry", unitNumber: 1, name: "Unit 1: The Global Tapestry (c. 1200\u20131450)" }, { id: "networks-exchange", unitNumber: 2, name: "Unit 2: Networks of Exchange (c. 1200\u20131450)" }, { id: "land-based-empires", unitNumber: 3, name: "Unit 3: Land-Based Empires (c. 1450\u20131750)" }, { id: "transoceanic", unitNumber: 4, name: "Unit 4: Transoceanic Interconnections (c. 1450\u20131750)" }, { id: "revolutions", unitNumber: 5, name: "Unit 5: Revolutions (c. 1750\u20131900)" }, { id: "consequences", unitNumber: 6, name: "Unit 6\u20139: Global Conflicts, Cold War & Globalization" }],
  "geometry": [{ id: "angles-lines", unitNumber: 1, name: "Unit 1: Angles & Parallel Lines" }, { id: "triangles", unitNumber: 2, name: "Unit 2: Triangles & Similarity" }, { id: "right-triangles", unitNumber: 3, name: "Unit 3: Right Triangles & Trigonometry" }, { id: "polygons", unitNumber: 4, name: "Unit 4: Polygons & Quadrilaterals" }, { id: "circles", unitNumber: 5, name: "Unit 5: Circles" }],
  "grade-8-math": [{ id: "number-system", unitNumber: 1, name: "Unit 1: The Number System & Exponents" }, { id: "expressions-equations", unitNumber: 2, name: "Unit 2: Expressions, Equations & Systems" }, { id: "functions", unitNumber: 3, name: "Unit 3: Functions" }, { id: "geometry", unitNumber: 4, name: "Unit 4: Geometry & the Pythagorean Theorem" }, { id: "statistics", unitNumber: 5, name: "Unit 5: Statistics & Probability" }],
  "organic-chemistry-1": [{ id: "structure-bonding", unitNumber: 1, name: "Unit 1: Structure, Bonding & Acidity" }, { id: "stereochemistry", unitNumber: 2, name: "Unit 2: Stereochemistry" }, { id: "substitution-elimination", unitNumber: 3, name: "Unit 3: Substitution & Elimination" }, { id: "alkenes-alkynes", unitNumber: 4, name: "Unit 4: Alkenes, Alkynes & Radicals" }, { id: "alcohols-spectroscopy", unitNumber: 5, name: "Unit 5: Alcohols, Ethers & Spectroscopy" }],
  "organic-chemistry-2": [{ id: "aromatics", unitNumber: 1, name: "Unit 1: Aromatic Chemistry" }, { id: "aldehydes-ketones", unitNumber: 2, name: "Unit 2: Aldehydes & Ketones" }, { id: "acids-derivatives", unitNumber: 3, name: "Unit 3: Carboxylic Acids & Derivatives" }, { id: "enols-condensations", unitNumber: 4, name: "Unit 4: Enols, Enolates & Condensations" }, { id: "amines-biomolecules", unitNumber: 5, name: "Unit 5: Amines, Biomolecules & Spectroscopy" }],
  "pre-algebra": [{ id: "integers", unitNumber: 1, name: "Unit 1: Integers, Exponents & Order of Operations" }, { id: "fractions", unitNumber: 2, name: "Unit 2: Fractions & Decimals" }, { id: "ratios-percents", unitNumber: 3, name: "Unit 3: Ratios, Rates & Percents" }, { id: "expressions-equations", unitNumber: 4, name: "Unit 4: Expressions, Equations & Inequalities" }, { id: "geometry-measurement", unitNumber: 5, name: "Unit 5: Geometry & Measurement" }, { id: "data-probability", unitNumber: 6, name: "Unit 6: Data, Graphs & Probability" }],
  "precalculus": [{ id: "functions", unitNumber: 1, name: "Unit 1: Functions & Transformations" }, { id: "polynomial-rational", unitNumber: 2, name: "Unit 2: Polynomial & Rational Functions" }, { id: "exponential-log", unitNumber: 3, name: "Unit 3: Exponential & Logarithmic Functions" }, { id: "trigonometry", unitNumber: 4, name: "Unit 4: Trigonometry" }, { id: "vectors-matrices-polar", unitNumber: 5, name: "Unit 5: Vectors, Matrices, Parametric & Polar" }, { id: "sequences", unitNumber: 6, name: "Unit 6: Sequences & Series" }],
  "psat": [{ id: "information-ideas", unitNumber: 1, name: "Unit 1: Information and Ideas" }, { id: "craft-structure", unitNumber: 2, name: "Unit 2: Craft and Structure" }, { id: "expression-ideas", unitNumber: 3, name: "Unit 3: Expression of Ideas" }, { id: "standard-conventions", unitNumber: 4, name: "Unit 4: Standard English Conventions" }, { id: "algebra-psat", unitNumber: 5, name: "Unit 5: Algebra" }, { id: "advanced-math-psat", unitNumber: 6, name: "Unit 6: Advanced Math" }, { id: "problem-solving-data", unitNumber: 7, name: "Unit 7: Problem-Solving and Data Analysis" }, { id: "geometry-trig-psat", unitNumber: 8, name: "Unit 8: Geometry and Trigonometry" }],
}

/** Units available for a course's unit tests, or [] when the course has none. */
export function unitsForCourse(courseSlug: string): UnitOption[] {
  return UNITS_BY_COURSE[courseSlug] ?? []
}

/** Course slugs that actually have unit tests, for the assignment picker. */
export function coursesWithUnitTests(): string[] {
  return Object.keys(UNITS_BY_COURSE)
}
