/**
 * Entrance Quiz — Adolescence & Adulthood (AP Psychology)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-psych-entrance-quizzes-batch*.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "aa-ent-1a", question: "Puberty in girls is typically marked by MENARCHE around age:", options: ["6", "About 12 (range 9-16); average has dropped over the past century, partly due to nutrition", "20", "30"], correctIndex: 1, explanation: "Secular trend: average menarche fell from ~16 in 1840 to ~12 today in industrialized countries (better nutrition, lower infectious load).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "aa-ent-1b", question: "During adolescence, the PREFRONTAL cortex matures:", options: ["Earlier than the limbic system", "LATER than limbic/reward systems — creating a developmental gap that helps explain risk-taking and impulsivity", "At the same time", "Not at all"], correctIndex: 1, explanation: "Casey, Steinberg, and others document the limbic-prefrontal asymmetry of adolescence (~ages 12-25).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "aa-ent-2a", question: "Erik Erikson's adolescent stage is:", options: ["Trust vs Mistrust", "Identity vs Role Confusion — forming a coherent sense of self", "Generativity vs Stagnation", "Integrity vs Despair"], correctIndex: 1, explanation: "Erikson saw adolescence as a psychosocial moratorium for exploring values, vocation, and identity.", partNumber: 2, partTitle: "Key Processes" },
  { id: "aa-ent-2b", question: "James Marcia (1966) identified four IDENTITY STATUSES based on exploration × commitment:", options: ["Only 'achieved' and 'lost'", "Identity diffusion, foreclosure, moratorium, achievement", "Just two: child / adult", "Stages identical to Erikson"], correctIndex: 1, explanation: "Marcia operationalized Erikson's theory: foreclosure = commitment without exploration; achievement = both.", partNumber: 2, partTitle: "Key Processes" },
  { id: "aa-ent-3a", question: "Kohlberg's POSTCONVENTIONAL morality is characterized by:", options: ["Obedience to authority", "Reasoning from universal ethical PRINCIPLES that may override laws (e.g., civil disobedience)", "Self-interest only", "Blind rule-following"], correctIndex: 1, explanation: "Postconventional reasoning is uncommon and developed late, if at all. Kohlberg said many adults remain at conventional level.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "aa-ent-3b", question: "Carol Gilligan (1982) critiqued Kohlberg by arguing his stages:", options: ["Were too lenient", "Underemphasized a 'CARE' orientation (relationships, responsibility) more typical of how women describe moral dilemmas", "Were too strict for males", "Did not exist"], correctIndex: 1, explanation: "Gilligan's 'In a Different Voice' argued for a relational ethic of care alongside the justice orientation.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "aa-ent-4a", question: "ADOLESCENT egocentrism (Elkind 1967) includes the:", options: ["IMAGINARY AUDIENCE (teens feel constantly watched/judged) and PERSONAL FABLE (teens feel uniquely invulnerable or special)", "Sensory adaptation", "Object permanence", "Phi phenomenon"], correctIndex: 0, explanation: "These cognitive distortions help explain self-consciousness and risk taking in adolescence.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "aa-ent-4b", question: "Authoritative parenting (Baumrind 1967, 1971) combines:", options: ["Low warmth and high control", "HIGH warmth and HIGH control — generally associated with the most positive child outcomes in Western samples", "Low both", "High warmth, no rules"], correctIndex: 1, explanation: "Baumrind's other styles: authoritarian (low warmth/high control), permissive (high warmth/low control), neglectful (low both).", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "aa-ent-5a", question: "Levinson (1978) and others described EMERGING adulthood (Arnett 2000, ages ~18-25) as:", options: ["A return to childhood", "A distinct stage of identity exploration, instability, and feeling 'in-between' — increasingly delayed marriage, parenthood, financial independence", "Identity foreclosure", "Senescence"], correctIndex: 1, explanation: "Arnett's emerging adulthood concept reflects demographic changes since the 1970s in industrialized societies.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "aa-ent-5b", question: "Erikson's MIDDLE adulthood stage is:", options: ["Identity vs Role Confusion", "Generativity vs Stagnation — contributing to the next generation through work, parenting, mentorship", "Trust vs Mistrust", "Industry vs Inferiority"], correctIndex: 1, explanation: "Generativity researchers (McAdams) link generativity to higher well-being in midlife.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "aa-ent-6a", question: "Crystallized vs Fluid INTELLIGENCE across the lifespan:", options: ["Both decline rapidly after 30", "Crystallized (knowledge, vocabulary) tends to RISE or hold steady into older age; fluid (novel reasoning, processing speed) tends to DECLINE earlier", "Both rise indefinitely", "Both are unrelated to age"], correctIndex: 1, explanation: "Cattell-Horn-Carroll model. Fluid IQ peaks in 20s; crystallized IQ can rise into 60s-70s.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "aa-ent-6b", question: "Elisabeth Kübler-Ross (1969) proposed five stages of grief:", options: ["Bargaining only", "Denial, Anger, Bargaining, Depression, Acceptance — descriptive (not strictly sequential or universal)", "Three stages", "None"], correctIndex: 1, explanation: "Modern bereavement research (Bonanno) finds many trajectories (resilience common); the 'stages' are not a required sequence.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "aa-ent-7a", question: "On the AP Psych exam, a question about a midlife adult mentoring younger employees and finding meaning in shaping the next generation tests:", options: ["Identity vs role confusion", "Generativity vs Stagnation (Erikson, middle adulthood)", "Trust vs mistrust", "Integrity vs despair"], correctIndex: 1, explanation: "Generativity is the central task of middle adulthood in Erikson's framework.", partNumber: 7, partTitle: "AP Review" },
  { id: "aa-ent-7b", question: "Which AP-style claim is correct?", options: ["Cognitive decline in old age is universal and rapid", "Aging shows differential changes — speed-based cognition declines while knowledge and emotional regulation often improve; lifestyle and health buffer decline", "All older adults develop dementia", "Personality changes radically every decade"], correctIndex: 1, explanation: "Modern lifespan research (Carstensen, Salthouse) emphasizes both losses and gains in adult development.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
