/**
 * Entrance Quiz — Emotion & Stress (AP Psychology)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-psych-entrance-quizzes-batch*.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "es-ent-1a", question: "The James-Lange theory (1884-1885) proposes:", options: ["Emotion causes bodily arousal", "Bodily AROUSAL comes FIRST and the emotion is our perception of that arousal ('we feel afraid because we tremble')", "Emotion and arousal are simultaneous", "Cognition produces all emotion"], correctIndex: 1, explanation: "James-Lange: stimulus → physiological response → labeled emotion. Critiqued because many emotions share similar arousal patterns.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "es-ent-1b", question: "The Cannon-Bard theory (1927) proposes:", options: ["Sequential", "SIMULTANEOUS arousal and emotional experience — both result from thalamic processing", "Cognition first", "Behavior first"], correctIndex: 1, explanation: "Cannon-Bard rejected James-Lange because (a) similar arousal accompanies different emotions and (b) arousal is too slow.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "es-ent-2a", question: "Schachter-Singer TWO-FACTOR theory (1962) holds emotion = ", options: ["Arousal alone", "Physiological AROUSAL + cognitive LABEL (interpretation of context)", "Cognition alone", "Reflex"], correctIndex: 1, explanation: "Schachter-Singer epinephrine experiment: same arousal interpreted as anger or euphoria depending on confederate's behavior.", partNumber: 2, partTitle: "Key Processes" },
  { id: "es-ent-2b", question: "Lazarus's COGNITIVE-MEDIATIONAL theory (1984) holds:", options: ["Arousal precedes appraisal", "APPRAISAL of an event determines the emotion (primary appraisal: threat? secondary: can I cope?)", "Emotion has no cognition", "Reflex only"], correctIndex: 1, explanation: "Lazarus debated Zajonc on whether emotion can occur without cognitive appraisal; both positions partly correct.", partNumber: 2, partTitle: "Key Processes" },
  { id: "es-ent-3a", question: "Zajonc (1980) argued:", options: ["All emotion requires cognition", "Some emotional responses occur WITHOUT conscious cognitive appraisal — the 'mere exposure effect' increases liking even with subliminal exposure", "No emotions are automatic", "Lazarus is fully wrong"], correctIndex: 1, explanation: "Zajonc-Lazarus debate. LeDoux's amygdala 'low road' (subcortical fear path) supports rapid pre-cognitive emotional responses.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "es-ent-3b", question: "Paul Ekman's research identified UNIVERSAL facial expressions for at least:", options: ["1 emotion", "6-7 basic emotions (happiness, sadness, anger, fear, surprise, disgust, contempt) recognized across cultures", "100 emotions", "0 emotions"], correctIndex: 1, explanation: "Ekman's cross-cultural studies (e.g., Fore of Papua New Guinea, 1972) supported universality of basic emotions.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "es-ent-4a", question: "The FACIAL FEEDBACK hypothesis (Strack et al. 1988) proposes:", options: ["Facial expressions reflect but don't cause emotion", "Facial muscle activity FEEDS BACK to influence felt emotion (holding a pen in teeth → mild positive mood) — weak/inconsistent in recent replications", "Faces are unrelated to emotion", "Only voice matters"], correctIndex: 1, explanation: "The classic pen-in-teeth study failed to replicate in a 2016 multi-lab effort, illustrating the replication crisis.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "es-ent-4b", question: "Hans Selye (1936) described the General Adaptation Syndrome (GAS) with three stages:", options: ["Inflammation only", "Alarm → Resistance → Exhaustion", "Cognitive appraisal stages", "Sleep stages"], correctIndex: 1, explanation: "GAS describes the body's stereotyped stress response; chronic stress wears down resistance into exhaustion.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "es-ent-5a", question: "The HPA axis releases ____ in response to stress:", options: ["Insulin", "Cortisol (from adrenal cortex, via hypothalamic CRH and pituitary ACTH)", "Melatonin", "Estrogen"], correctIndex: 1, explanation: "Acute cortisol mobilizes energy; chronic elevation suppresses immunity and damages hippocampus.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "es-ent-5b", question: "Chronic stress is associated with INCREASED risk of:", options: ["Better sleep", "Cardiovascular disease, suppressed immunity, depression, and impaired memory (hippocampal effects)", "Faster healing", "Lower cortisol"], correctIndex: 1, explanation: "Psychoneuroimmunology (Ader, Cohen) documents stress-immune links; chronic stress raises infection risk.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "es-ent-6a", question: "PROBLEM-FOCUSED vs EMOTION-FOCUSED coping (Lazarus & Folkman 1984):", options: ["Both target the body", "Problem-focused tries to change the stressor; emotion-focused tries to change one's emotional response — best choice depends on controllability", "They are identical", "Only one works"], correctIndex: 1, explanation: "Controllable stressors → problem-focused coping. Uncontrollable losses → emotion-focused coping.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "es-ent-6b", question: "The Type A behavior pattern (Friedman & Rosenman 1959) was originally linked to coronary disease; modern refinement points specifically to:", options: ["Time urgency alone", "HOSTILITY/anger as the toxic component, more than competitive drive or time urgency", "Ambition only", "Talkativeness"], correctIndex: 1, explanation: "Decades of follow-up studies refined Type A: hostility is the strongest cardiovascular risk component.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "es-ent-7a", question: "On the AP Psych exam, a question describing a roller-coaster rider on a first date who interprets racing heart as romantic attraction tests:", options: ["James-Lange", "Schachter-Singer two-factor theory (misattribution of arousal — Dutton & Aron 1974 bridge study)", "Cannon-Bard", "Facial feedback"], correctIndex: 1, explanation: "The bridge-misattribution study showed arousal from height was misattributed to attraction, supporting two-factor theory.", partNumber: 7, partTitle: "AP Review" },
  { id: "es-ent-7b", question: "Which AP-style claim is correct?", options: ["Emotion is purely physiological", "Emotion involves an interaction of physiological arousal, cognitive appraisal, behavioral expression, and culture — captured by combining James-Lange, Cannon-Bard, two-factor, and appraisal theories", "Emotion is purely cognitive", "Cultures share no emotional features"], correctIndex: 1, explanation: "AP Psych emphasizes integrating multiple theories to explain emotional phenomena.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
