/**
 * Entrance Quiz — Origins & Diffusion of Agriculture (AP Human Geography)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-hg-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "hgao-ent-1a", question: "The AGRICULTURAL REVOLUTION (First, Neolithic) began approximately:", options: ["500 years ago", "~10,000-12,000 years ago at end of Pleistocene; multiple independent origins", "2,000 years ago", "100,000 years ago"], correctIndex: 1, explanation: "Neolithic Revolution ~10-12 kya. Multiple independent centers identified — not single origin.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hgao-ent-1b", question: "Carl Sauer (1952) identified key HEARTHS of domestication including:", options: ["Only one: Middle East", "Fertile Crescent (wheat, barley, sheep), China (rice, millet), Mesoamerica (maize, beans), Andes (potato), W. Africa (yams, sorghum), New Guinea (taro, banana)", "Only Europe", "Only Australia"], correctIndex: 1, explanation: "Sauer 'Agricultural Origins and Dispersals' (1952). Now confirmed: ~7-10 independent agricultural origins across Earth.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hgao-ent-2a", question: "Wheat, barley, sheep, and goats were domesticated in:", options: ["China", "Fertile Crescent (SW Asia, ~10,000 BCE) — Jarmo, Jericho, Çatalhöyük key sites", "Mesoamerica", "Europe"], correctIndex: 1, explanation: "Fertile Crescent: natural habitat of wild einkorn/emmer wheat and wild goat/sheep ancestors.", partNumber: 2, partTitle: "Key Processes" },
  { id: "hgao-ent-2b", question: "Maize was domesticated in:", options: ["China", "Mesoamerica (~9,000 years ago) from teosinte grass — Oaxaca/Balsas Valley, Mexico", "Middle East", "India"], correctIndex: 1, explanation: "Maize: domesticated from teosinte in Balsas Valley (Mexico) ~9 kya. Spread throughout Americas pre-Columbian.", partNumber: 2, partTitle: "Key Processes" },
  { id: "hgao-ent-3a", question: "The COLUMBIAN EXCHANGE (Crosby 1972) moved:", options: ["Only humans", "Plants, animals, diseases, people between Old World and New World after 1492 — reshaped global diets", "Only diseases", "Nothing"], correctIndex: 1, explanation: "Columbian Exchange: potato, maize, tomato, tobacco, chili → Old World; wheat, sugar, horses, smallpox → New World. Transformative.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hgao-ent-3b", question: "Potatoes (domesticated Andes) diffused to Europe ~1570 and by 1800:", options: ["Were rejected", "Became staple crop in Ireland, Germany, Russia; supported population explosion; Irish famine 1845-49 linked to potato blight killed ~1M", "Only grown in museums", "Eliminated wheat"], correctIndex: 1, explanation: "Potato caloric yield ~2x wheat; drove European population growth; Phytophthora infestans blight devastated Ireland 1845-49.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hgao-ent-4a", question: "Boserup's thesis (1965) about agricultural change:", options: ["Population collapse", "Population pressure induces agricultural intensification (shorter fallow, more labor, new tools)", "Population stagnation", "Technology is fixed"], correctIndex: 1, explanation: "Boserup: 'Conditions of Agricultural Growth' — agriculture intensifies in response to population pressure, reversing Malthusian logic.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hgao-ent-4b", question: "The SECOND AGRICULTURAL REVOLUTION (17th-19th c. Europe) involved:", options: ["Industrialization of food only", "Enclosure, crop rotation, new crops (turnips, clover), selective breeding — preceded and enabled Industrial Revolution (British Agricultural Revolution ~1600-1850)", "Return to subsistence", "Pure mechanization only"], correctIndex: 1, explanation: "British Ag Rev: 4-field rotation (Townshend), enclosure acts, improved breeds (Bakewell). Freed labor for factories.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hgao-ent-5a", question: "The GREEN REVOLUTION (1940s-80s) introduced:", options: ["Traditional seeds only", "High-yielding varieties (dwarf wheat Norman Borlaug 1944 Mexico; IR8 rice IRRI 1966), fertilizers, irrigation, pesticides — tripled grain yields", "Organic-only methods", "Only genetic modification"], correctIndex: 1, explanation: "Borlaug (1970 Nobel Peace) 'Father of Green Revolution'. India/Pakistan wheat self-sufficient by 1970s. Saved ~1B from famine.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hgao-ent-5b", question: "GMOs (genetically modified crops) became widespread after:", options: ["1900", "1996 (first commercial release: Monsanto's Roundup Ready soy); by 2024 ~80% of U.S. soy, corn, cotton is GM", "1800", "1945"], correctIndex: 1, explanation: "First commercial GMO 1996. U.S. ~92% GM corn, ~94% GM soy (USDA 2023). Controversial in EU (restrictive).", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hgao-ent-6a", question: "SUBSISTENCE agriculture is:", options: ["For export", "Production for the farmer's own family/village consumption; ~40% of world's farmers, common in sub-Saharan Africa, South Asia", "Industrial scale", "For mass market"], correctIndex: 1, explanation: "Subsistence: growing what you eat. Still ~2 billion people globally (FAO). Contrast with commercial agriculture.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hgao-ent-6b", question: "COMMERCIAL agriculture is:", options: ["For self-consumption", "Production for sale/market — dominant in HICs (U.S., EU, Canada, Australia, Argentina) with high mechanization and capital intensity", "Only for subsistence", "Only for trade"], correctIndex: 1, explanation: "Commercial ag: large-scale, mechanized, export-oriented. U.S. farms avg ~450 acres; < 2% of workforce feeds 330M.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hgao-ent-7a", question: "On the AP HG exam, 'explain Columbian Exchange impacts' tests:", options: ["Only plants", "Impacts on demographics (indigenous deaths from smallpox ~90%), diets (global cuisines transformed), economies, ecology", "Only Europe", "Only trade"], correctIndex: 1, explanation: "Columbian Exchange: ~90% indigenous American population died from disease 1492-1600; global diets transformed; African slavery expanded with American crops.", partNumber: 7, partTitle: "AP Review" },
  { id: "hgao-ent-7b", question: "Which AP-style claim is correct?", options: ["Agriculture arose in one place", "Agriculture arose INDEPENDENTLY in multiple hearths at different times — not a single diffusion event", "Humans are naturally farmers", "Agriculture was a single-origin event"], correctIndex: 1, explanation: "Independent origins: Fertile Crescent, China, Mesoamerica, Andes, W Africa, New Guinea. AP expects recognition of multiple hearths.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
