/**
 * Entrance Quiz — Ethnicity, Race & Identity (AP Human Geography)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-hg-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "hgei-ent-1a", question: "ETHNICITY refers to:", options: ["Biological difference", "Shared cultural identity based on ancestry, language, religion, or customs (socially constructed)", "Nationality only", "Race synonym"], correctIndex: 1, explanation: "Ethnicity = shared cultural identity. Constructed, not biological. Can be claimed, modified, lost across generations.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hgei-ent-1b", question: "RACE is best understood as:", options: ["A biological reality", "A SOCIAL CONSTRUCT with no coherent biological basis; categories vary by country and era", "Genetically fixed", "Climate-determined"], correctIndex: 1, explanation: "Race categories differ by country (U.S. vs Brazil vs South Africa) and era — strong evidence they're social, not biological.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hgei-ent-2a", question: "A NATION-STATE is:", options: ["A multicultural empire", "A political state whose population predominantly shares one national identity (Japan ~98% Japanese, Iceland, South Korea)", "A city only", "Any country"], correctIndex: 1, explanation: "Pure nation-states are rare; most countries are multinational. Japan, Iceland, S. Korea closest to the ideal type.", partNumber: 2, partTitle: "Key Processes" },
  { id: "hgei-ent-2b", question: "A MULTINATIONAL state contains:", options: ["One nation", "Multiple national/ethnic groups within one state (Canada: English/French/Indigenous; UK: English/Scottish/Welsh/Irish; Spain, Belgium)", "Only ethnic groups", "No citizens"], correctIndex: 1, explanation: "Canada, UK, Spain, Belgium have multiple recognized nations. Some formal devolution (Scotland, Catalonia, Flanders).", partNumber: 2, partTitle: "Key Processes" },
  { id: "hgei-ent-3a", question: "A STATELESS NATION is:", options: ["A state without people", "A nation without a state of its own (Kurds ~30M across Turkey/Iraq/Iran/Syria; Palestinians; Rohingya; Roma; Uyghurs; pre-1948 Jews)", "A tribe only", "A refugee group"], correctIndex: 1, explanation: "Kurds are the largest stateless nation globally. Persistent geopolitical issue (Kurdistan pursuits in Iraq 2017 referendum 93% yes, no recognition).", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hgei-ent-3b", question: "GHETTOIZATION (historical) refers to:", options: ["Voluntary clustering only", "Forced residential segregation (Venetian Ghetto 1516 first; Nazi ghettos Warsaw/Lodz 1939-44; apartheid South Africa)", "Wealthy neighborhoods", "Tourism zones"], correctIndex: 1, explanation: "Ghetto (term from Venice 1516) = forced segregated zone. Nazis revived term 1939-44 with lethal intent.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hgei-ent-4a", question: "Apartheid (South Africa 1948-1994) included:", options: ["Racial equality", "Racial classification, residential segregation (Group Areas Act 1950), and political disenfranchisement of Black majority", "Full integration", "Only language policy"], correctIndex: 1, explanation: "Apartheid: NP government 1948-1994. Pass laws, Group Areas Act 1950, Bantustans. Ended with Mandela's 1994 election.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hgei-ent-4b", question: "The U.S. CIVIL RIGHTS ACT (1964) and Voting Rights Act (1965) outlawed:", options: ["Segregation only in schools", "Racial discrimination in public accommodations and employment (CRA 1964); banned literacy tests and enabled federal oversight of voting (VRA 1965)", "All immigration", "Only housing discrimination"], correctIndex: 1, explanation: "LBJ signed CRA July 2, 1964 and VRA August 6, 1965 — dismantled Jim Crow legal framework.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hgei-ent-5a", question: "GENOCIDE (1948 UN Convention) is defined as:", options: ["Any war", "Acts intended to destroy, in whole or part, a national, ethnic, racial, or religious group (Holocaust, Rwanda 1994 ~800K Tutsis in 100 days, Bosnia 1995 Srebrenica)", "Economic policy", "Natural disaster"], correctIndex: 1, explanation: "UN Genocide Convention Dec 9, 1948. Rwanda 1994: ~800K Tutsis killed; Bosnia Srebrenica July 1995: ~8,000 Bosniak men/boys.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hgei-ent-5b", question: "ETHNIC CLEANSING differs from genocide:", options: ["Same thing", "Intent to forcibly remove a group from a territory (may or may not include mass killing); Yugoslav Wars 1991-2001; Myanmar Rohingya 2017 ~700K fled", "Only financial", "Only colonial"], correctIndex: 1, explanation: "Ethnic cleansing: territorial removal by force. Yugoslav Wars and Myanmar Rohingya (~700K fled to Bangladesh 2017) are key examples.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hgei-ent-6a", question: "CENSUS categories shape:", options: ["Nothing", "Political representation (apportionment), resource allocation, and identity itself (U.S. census race categories evolved: 'Mulatto' 1890-1920, 'Hispanic' 1980+, multi-race 2000)", "Only statistics", "Only academic research"], correctIndex: 1, explanation: "Censuses both measure and construct identity. U.S. census race categories have changed repeatedly, reflecting politics.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hgei-ent-6b", question: "Brazilian race categories include multiple:", options: ["Only Black/White", "Categories including pardo (mixed), preto (Black), branco (White), amarelo (Asian), indígena — differs from U.S. binary framing", "Same as U.S.", "None"], correctIndex: 1, explanation: "Brazil 2022 IBGE census: pardo 45.3%, branco 43.5%, preto 10.2% — fluid categorization vs. U.S. hypodescent tradition.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hgei-ent-7a", question: "On the AP HG exam, 'balkanization' refers to:", options: ["Unification", "Breakup of a region into hostile smaller units along ethnic lines (Yugoslavia 1991-2008 into 7 states; former USSR 1991 into 15)", "Economic integration", "Physical borders"], correctIndex: 1, explanation: "Term from Balkan wars of 1912-13. Revived 1991-2001 Yugoslav breakup: Slovenia, Croatia, Bosnia, Serbia, Montenegro, N. Macedonia, Kosovo.", partNumber: 7, partTitle: "AP Review" },
  { id: "hgei-ent-7b", question: "Which AP-style claim is correct?", options: ["Ethnicity is always biological", "Ethnicity and race are socially constructed, spatially variable, and politically contested — AP expects recognition of this", "Race is genetically fixed", "Nation = state always"], correctIndex: 1, explanation: "Both ethnicity and race are social constructs; they vary by country and era. AP rubrics expect students to treat them as contested concepts.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
