/**
 * Entrance Quiz — Language & Religion (AP Human Geography)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-hg-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "hglr-ent-1a", question: "About how many living languages exist today (Ethnologue 2024)?", options: ["50", "About 7,100 (with ~40% endangered; half spoken by fewer than 10,000 people)", "100,000", "50,000"], correctIndex: 1, explanation: "Ethnologue counts ~7,168 living languages (2024). Top 10 account for ~50% of speakers; long tail of endangered languages.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hglr-ent-1b", question: "The INDO-EUROPEAN language family includes:", options: ["Only English", "English, Spanish, Russian, Hindi, Persian — ~3.2 billion speakers (~42% of world)", "Only German", "Chinese"], correctIndex: 1, explanation: "Indo-European: largest family by speakers. Romance, Germanic, Slavic, Indo-Iranian, etc. Originated ~6,000 ya, likely Pontic-Caspian steppe.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hglr-ent-2a", question: "The SINO-TIBETAN family's largest language is:", options: ["Japanese", "Mandarin Chinese (~1.1 billion native speakers; world's most-spoken L1)", "Korean", "Hindi"], correctIndex: 1, explanation: "Mandarin ~1.1B native (2024). Sino-Tibetan also includes Cantonese, Tibetan, Burmese.", partNumber: 2, partTitle: "Key Processes" },
  { id: "hglr-ent-2b", question: "A DIALECT differs from a language:", options: ["By being completely separate", "By being a variant of a language (often mutually intelligible); 'a language is a dialect with an army and navy' (Max Weinreich)", "By age only", "By having no grammar"], correctIndex: 1, explanation: "Language-dialect boundary is political/social, not purely linguistic. Weinreich quote illustrates political nature.", partNumber: 2, partTitle: "Key Processes" },
  { id: "hglr-ent-3a", question: "LINGUA FRANCA examples include:", options: ["English only", "English globally, Swahili in E. Africa, Hindi-Urdu in S. Asia, Arabic in MENA", "Latin only", "None exist today"], correctIndex: 1, explanation: "Lingua francas enable cross-linguistic trade/communication. Each region has its own.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hglr-ent-3b", question: "PIDGIN vs CREOLE:", options: ["Same thing", "Pidgin = simplified contact language with no native speakers; Creole = pidgin that became a native language of a new generation (Haitian Kreyòl, Tok Pisin)", "Both dialects", "Creole is older"], correctIndex: 1, explanation: "Pidgin → Creole when children acquire it natively. Haitian Kreyòl, Tok Pisin (PNG), Jamaican Patois examples.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hglr-ent-4a", question: "UNIVERSALIZING religions seek converts; include:", options: ["Judaism", "Christianity (~2.4B), Islam (~1.9B), Buddhism (~500M) — all seek universal membership", "Hinduism only", "Shinto"], correctIndex: 1, explanation: "Universalizing religions spread by missionaries, conquest, trade. Christianity, Islam, Buddhism largest.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hglr-ent-4b", question: "ETHNIC religions are tied to a specific group/place; include:", options: ["Christianity", "Hinduism (~1.2B), Judaism (~15M), Sikhism, Shinto — generally don't seek converts", "Islam", "Buddhism"], correctIndex: 1, explanation: "Ethnic religions tied to culture/place of origin: Hinduism-India, Shinto-Japan, Judaism-Jewish people.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hglr-ent-5a", question: "Christianity originated in:", options: ["Europe", "1st-century Roman Judea (Jerusalem region); spread via Roman Empire, missionaries, colonialism", "Africa", "Asia"], correctIndex: 1, explanation: "Christianity: 1st century Judea → Rome (official 380 CE, Edict of Thessalonica) → global via empire/missionaries/colonialism.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hglr-ent-5b", question: "Islam originated in:", options: ["Egypt", "7th-century Arabian Peninsula (Mecca/Medina, 610-632 CE); spread via conquests, trade, missionaries", "Persia", "Spain"], correctIndex: 1, explanation: "Islam: Muhammad in Mecca 610 CE; Medina 622 (Hijra = Year 1 AH); rapid expansion 632-750 across MENA, Iberia.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hglr-ent-6a", question: "Buddhism spread primarily through:", options: ["Military conquest", "Missionary activity (Ashoka, 3rd c. BCE) and trade routes (Silk Road) — reaching China ~1st c. CE, Japan ~6th c. CE", "Isolation", "Pure relocation"], correctIndex: 1, explanation: "Ashoka (Mauryan, r. 268-232 BCE) sent missionaries throughout Asia. Silk Road carried Buddhism to China, Korea, Japan.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hglr-ent-6b", question: "A TOPONYM reveals cultural history, e.g.:", options: ["Nothing", "San Francisco (Spanish Catholic), New York (English colonial renaming of New Amsterdam), Saskatoon (Cree language)", "Only physical features", "Only natural names"], correctIndex: 1, explanation: "Toponyms record cultural layers: indigenous, colonial, religious. Renaming often signals political change (Mumbai ← Bombay 1995).", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hglr-ent-7a", question: "On the AP HG exam, 'explain language extinction' likely tests:", options: ["Only natural causes", "Causes (globalization, colonization, education-language policy, urbanization) and preservation efforts (UNESCO, revitalization like Hebrew, Welsh, Māori)", "Only policy", "Only technology"], correctIndex: 1, explanation: "Extinction causes: conquest, assimilation, economic pressure, urbanization. Revitalization examples: Hebrew (only successful complete revival), Welsh, Māori.", partNumber: 7, partTitle: "AP Review" },
  { id: "hglr-ent-7b", question: "Which AP-style claim is correct?", options: ["Religion has no spatial pattern", "Religions leave distinct cultural landscapes (churches, mosques, temples) and affect economic/political geography (Sabbath observance, halal economies, pilgrimage)", "Religion is purely private", "Religion only matters historically"], correctIndex: 1, explanation: "Religion shapes landscape (sacred sites, architecture) and daily geography (halal food, Sabbath, pilgrimage). Core AP topic.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
