/**
 * Entrance Quiz — Political Geography & Territoriality (AP Human Geography)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-hg-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "hgpt-ent-1a", question: "A STATE in political geography is:", options: ["A federal subunit", "A politically organized territory with defined borders, population, sovereignty, and recognition", "Any region", "A city"], correctIndex: 1, explanation: "State = country with sovereignty, territory, population, recognition. Confusingly, U.S. 'states' are subunits (should be called provinces).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hgpt-ent-1b", question: "The WESTPHALIAN SYSTEM (1648 Treaty of Westphalia) established:", options: ["Democracy", "State sovereignty within fixed territorial borders, non-interference principle — basis of modern state system", "Free trade", "Colonial empires"], correctIndex: 1, explanation: "Peace of Westphalia 1648 ended Thirty Years' War and established territorial sovereignty — foundation of modern international system.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hgpt-ent-2a", question: "A COMPACT state has borders that are roughly:", options: ["Long and narrow", "Circular/compact (Poland, Kenya, Uruguay) — efficient administration", "Fragmented islands", "Penetrated by another state"], correctIndex: 1, explanation: "Compact shapes: efficient governance. Examples: Poland, Kenya, Uruguay, Rwanda.", partNumber: 2, partTitle: "Key Processes" },
  { id: "hgpt-ent-2b", question: "An ELONGATED state is:", options: ["Circular", "Long and narrow (Chile ~4,300 km long, ~180 km wide; Vietnam; Italy) — challenges of internal communication", "Exclaves", "Compact"], correctIndex: 1, explanation: "Elongated: Chile ~4,300 km long, <180 km wide average. Vietnam, Norway, Italy similar. Integration challenges.", partNumber: 2, partTitle: "Key Processes" },
  { id: "hgpt-ent-3a", question: "A FRAGMENTED state has:", options: ["One territory", "Non-contiguous territory (Indonesia ~17,000 islands; Philippines; U.S. with Alaska/Hawaii; Russia with Kaliningrad)", "Compact shape", "Perforated shape"], correctIndex: 1, explanation: "Fragmented states: Indonesia, Philippines, Japan, U.S. (with Alaska, Hawaii), Russia (Kaliningrad exclave).", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hgpt-ent-3b", question: "A PERFORATED state:", options: ["Has no borders", "Completely SURROUNDS another state (South Africa surrounds Lesotho; Italy surrounds Vatican City and San Marino)", "Is fragmented", "Has no government"], correctIndex: 1, explanation: "Perforated: S. Africa around Lesotho; Italy around Vatican + San Marino.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hgpt-ent-4a", question: "An ENCLAVE is a territory that is:", options: ["A country", "Entirely surrounded by another state's territory (Lesotho, Vatican City, San Marino, Kaliningrad is an exclave not enclave)", "An island", "A state capital"], correctIndex: 1, explanation: "Enclave: enclosed by foreign territory. Exclave: separated from main territory (Alaska, Kaliningrad).", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hgpt-ent-4b", question: "COLONIALISM peaked in what period?", options: ["1200-1400", "1880-1914 (Scramble for Africa); by 1914 European powers controlled ~84% of Earth's land", "Post-1950", "Pre-1000"], correctIndex: 1, explanation: "By 1914 European empires ruled ~84% of world. Decolonization wave: India 1947, Ghana 1957, ~50 African states 1960s.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hgpt-ent-5a", question: "The BERLIN CONFERENCE (1884-85):", options: ["Ended colonialism", "Partitioned Africa among European powers with arbitrary borders, ignoring ethnic groups — cause of later conflicts", "Created UN", "Abolished slavery"], correctIndex: 1, explanation: "Berlin Conference Nov 1884-Feb 1885: 14 European states divided Africa. Arbitrary borders still generate conflicts (Biafra, S. Sudan, etc.).", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hgpt-ent-5b", question: "DECOLONIZATION accelerated after:", options: ["1800", "WWII (1945+); ~60 new UN member states 1945-1980 including India 1947, Ghana 1957, Algeria 1962, Angola 1975", "1600", "1700"], correctIndex: 1, explanation: "Post-WWII decolonization: India 1947, Ghana 1957, ~17 African states in 1960 alone, Angola 1975. Triggered by WWII exhaustion, Cold War, nationalism.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hgpt-ent-6a", question: "The IRON CURTAIN (1945-1991) was:", options: ["A real wall", "Churchill's 1946 metaphor for political boundary separating Soviet bloc from Western Europe — physical barriers (Berlin Wall 1961-89)", "Natural barrier", "Economic zone"], correctIndex: 1, explanation: "Churchill March 5, 1946 Fulton, MO speech. Berlin Wall Aug 13, 1961 - Nov 9, 1989. Eastern bloc collapse 1989-91.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hgpt-ent-6b", question: "A BOUNDARY DISPUTE can be:", options: ["Only definitional", "Definitional (where is the line?), locational (moving rivers), operational (crossings), allocational (resources like India-China Siachen Glacier)", "Only over water", "Always resolved"], correctIndex: 1, explanation: "Four types of boundary disputes: definitional, locational, operational, allocational. Kashmir, Western Sahara, Crimea current examples.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hgpt-ent-7a", question: "On the AP HG exam, 'centripetal vs centrifugal forces' tests:", options: ["Magnetism", "Unifying forces (shared language, economy, external threat, infrastructure) vs divisive forces (ethnic tension, religious difference, economic inequality)", "Only borders", "Physical geography"], correctIndex: 1, explanation: "Centripetal unify (nationalism, lingua franca, infrastructure). Centrifugal divide (regionalism, secession movements, ethnic divisions).", partNumber: 7, partTitle: "AP Review" },
  { id: "hgpt-ent-7b", question: "Which AP-style claim is correct?", options: ["All borders are natural", "Most boundaries are human constructs (often colonial legacy) that may not match underlying physical, linguistic, or ethnic geography — a key source of conflict", "Borders are fixed forever", "Borders don't matter"], correctIndex: 1, explanation: "Borders are political constructs, often arbitrary (Sykes-Picot 1916 Middle East, Berlin 1885 Africa). Mismatches create conflict.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
