/**
 * Entrance Quiz — Population Distribution & Composition (AP Human Geography)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-hg-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "hgpd-ent-1a", question: "About what percentage of the world's 8+ billion people live in the Northern Hemisphere?", options: ["20%", "About 90% (most land and major population clusters are north of equator)", "50%", "10%"], correctIndex: 1, explanation: "~90% of humans live in the Northern Hemisphere — most continents, including East Asia, South Asia, and Europe.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hgpd-ent-1b", question: "The four major population clusters historically are:", options: ["Greenland, Antarctica, Sahara, Gobi", "East Asia, South Asia, Europe, and Southeast Asia (~2/3 of humanity)", "Africa, Australia, Arctic, Middle East", "Americas only"], correctIndex: 1, explanation: "Four big clusters: E Asia (~1.7B), S Asia (~2B), SE Asia (~700M), Europe (~750M). Dictated by river valleys, fertile soils.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hgpd-ent-2a", question: "Areas with sparse population (ecumene's opposite, nonecumene) include:", options: ["Major river deltas", "Deserts (Sahara, Gobi), high mountains (Himalayas, Andes), polar regions (Antarctica, Greenland), dense rainforest", "Coastal plains", "Monsoon zones"], correctIndex: 1, explanation: "Nonecumene: ~10% of land is essentially uninhabited due to climate or terrain extremes.", partNumber: 2, partTitle: "Key Processes" },
  { id: "hgpd-ent-2b", question: "Population PYRAMIDS plot:", options: ["Income by age", "Population by age and sex cohorts, stacked into a bilateral pyramid", "GDP over time", "Migration flows"], correctIndex: 1, explanation: "Pyramid: horizontal bars by 5-year age group, males left and females right. Reveals growth pattern and dependency ratio.", partNumber: 2, partTitle: "Key Processes" },
  { id: "hgpd-ent-3a", question: "A WIDE BASE pyramid indicates:", options: ["Low fertility", "High fertility and rapid population growth (typical of Stage 2 DTM: Niger TFR ~6.7)", "Declining population", "Aging population"], correctIndex: 1, explanation: "Wide base = many young, high fertility. Niger, Uganda, Yemen show this. Predicts future momentum growth.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hgpd-ent-3b", question: "A CONSTRICTED (inverted) pyramid indicates:", options: ["Young growing population", "Low fertility and an aging population (Japan median age 49 in 2024; Italy 47; Germany 46)", "Baby boom", "High infant mortality"], correctIndex: 1, explanation: "Japan, Italy, Germany, S. Korea — all have constricted bases, wide middles/tops. Declining populations or imminent decline.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hgpd-ent-4a", question: "DEPENDENCY RATIO equals:", options: ["(0-14 + 65+) / (15-64) × 100", "Working age / total", "Birth rate / death rate", "Migrants / population"], correctIndex: 0, explanation: "DR = (youth + elderly dependents) / working-age × 100. High DR strains social safety nets.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hgpd-ent-4b", question: "SEX RATIO = (males / females × 100). Natural sex ratio at birth is about 105. China's sex ratio peaked at:", options: ["100 (balanced)", "About 120 males per 100 females at birth (2000s), linked to One-Child Policy and son preference", "80", "150"], correctIndex: 1, explanation: "China's SRB hit ~120 in 2005 (gender-selective abortion under One-Child Policy 1980-2015). Now ~111.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hgpd-ent-5a", question: "Kerala, India's sex ratio is unusual because:", options: ["It is extremely low (few females)", "It has MORE females than males (~1084 females per 1000 males), linked to high female literacy and status", "It matches China", "It is 100 exactly"], correctIndex: 1, explanation: "Kerala's gender ratio (>1000 F per 1000 M) reflects high female education (90%+ literacy) and lower discrimination.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hgpd-ent-5b", question: "Japan's population peaked in 2008 at ~128M and is projected to fall to:", options: ["200M by 2100", "Under 90M by 2065 (National Institute of Population and Social Security Research)", "150M by 2050", "Stable at 128M"], correctIndex: 1, explanation: "Japan: 128M (2008) → ~125M (2024) → projected ~87M (2065). Drastic aging + low TFR 1.26.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hgpd-ent-6a", question: "A country with TFR below 2.1 (replacement) experiences:", options: ["Rapid growth", "Natural decrease if no immigration (deaths > births long-term)", "Stable population", "Immediate population collapse"], correctIndex: 1, explanation: "TFR < 2.1 → natural decrease. Japan, S. Korea (0.72 in 2023, world's lowest), most EU.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hgpd-ent-6b", question: "Calculate Crude Birth Rate if 600 babies were born in a population of 50,000 last year:", options: ["6 per 1,000", "12 per 1,000 (= 600/50,000 × 1,000)", "60 per 1,000", "120 per 1,000"], correctIndex: 1, explanation: "CBR = (births/population) × 1,000 = (600/50,000) × 1,000 = 12 per 1,000.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hgpd-ent-7a", question: "On the AP HG exam, pyramids are used to:", options: ["Just look at shape", "Predict future population (demographic momentum), identify policy challenges (aging, dependency), compare developmental stages", "Replace census data", "Identify individual people"], correctIndex: 1, explanation: "Pyramids reveal momentum, dependency, policy needs (pensions vs schools), DTM stage — rich AP analysis tool.", partNumber: 7, partTitle: "AP Review" },
  { id: "hgpd-ent-7b", question: "Which AP-style claim is correct?", options: ["Population distribution is even globally", "Population is highly UNEVEN at every scale (global, national, regional), shaped by physical and human factors", "Density and distribution are the same", "Only physical factors matter"], correctIndex: 1, explanation: "Uneven distribution at all scales is a core AP HG concept — explained by physical (climate, terrain) and human (history, economics) factors.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
