/**
 * Entrance Quiz — Urbanization & Urban Models (AP Human Geography)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-hg-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "hgur-ent-1a", question: "As of 2024, about what share of humans live in urban areas?", options: ["10%", "~57% (UN 2024); projected ~68% by 2050. Urbanization accelerating in LICs", "100%", "20%"], correctIndex: 1, explanation: "UN DESA 2024: ~57% urban. Crossed 50% ~2007. Projected 68% by 2050. Growth mostly in Asia/Africa.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hgur-ent-1b", question: "A MEGACITY is typically defined as:", options: ["Any large city", "Urban agglomeration over 10 million; 33 megacities in 2024 (Tokyo ~37M, Delhi, Shanghai, São Paulo, Mexico City)", "Above 100K", "Above 1M"], correctIndex: 1, explanation: "Megacity threshold: 10M. 33 in 2024 (up from 10 in 1990). Most in Asia. Tokyo has been #1 for decades.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "hgur-ent-2a", question: "Burgess's CONCENTRIC ZONE model (1925) describes:", options: ["Linear cities", "Chicago-based: CBD → zone of transition → working-class → residential → commuter rings", "Polynuclear cities", "Galactic cities"], correctIndex: 1, explanation: "Burgess 1925: classic Chicago model. Critiqued as specific to 1920s Chicago but iconic.", partNumber: 2, partTitle: "Key Processes" },
  { id: "hgur-ent-2b", question: "Hoyt's SECTOR model (1939) emphasizes:", options: ["Rings only", "Wedge-shaped sectors radiating outward along transport corridors (high-rent residential extends as wedge)", "Multiple nuclei", "No pattern"], correctIndex: 1, explanation: "Hoyt 1939: sectors align with transport lines. Better captures industrial corridors and high-status residential extensions.", partNumber: 2, partTitle: "Key Processes" },
  { id: "hgur-ent-3a", question: "Harris-Ullman MULTIPLE NUCLEI model (1945) argues:", options: ["Single center", "Cities have MULTIPLE specialized nodes (CBD, industrial parks, airports, universities, suburbs)", "Concentric only", "Random"], correctIndex: 1, explanation: "Harris-Ullman 1945: post-war U.S. cities with automobiles — multiple specialized centers, not one CBD.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hgur-ent-3b", question: "The GALACTIC CITY (edge city) model (Joel Garreau 1991) describes:", options: ["Classical concentric", "Post-suburban U.S. cities with edge cities (office/retail nodes far from old CBD; e.g., Tysons Corner VA, Schaumburg IL)", "Only LICs", "Pre-industrial"], correctIndex: 1, explanation: "Garreau 'Edge City' 1991. Tysons Corner (VA), Schaumburg (IL) became major employment centers outside old CBDs.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "hgur-ent-4a", question: "LATIN AMERICAN city model (Griffin-Ford 1980) features:", options: ["No CBD", "CBD + commercial spine + wealthy sectors along spine; poor peripheral barrios/favelas (inverse of U.S. pattern)", "Identical to U.S.", "Only rural"], correctIndex: 1, explanation: "L.A. cities: wealthy near center along spine; poor at periphery. Inverse of U.S. suburbanization. Favelas in Rio, barrios in Caracas.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hgur-ent-4b", question: "AFRICAN CITY model has THREE CBDs reflecting:", options: ["Random", "Colonial CBD, traditional/market CBD, informal/transitional — legacy of colonialism + traditional + modern economies", "Single center", "Multiple nuclei only"], correctIndex: 1, explanation: "African city model: 3 CBDs reflect colonial imposition + pre-colonial market centers + informal post-colonial growth.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "hgur-ent-5a", question: "SE ASIAN city model (McGee 1967) centers on:", options: ["CBD only", "The PORT (zone of old colonial trade); no formal CBD; spoking commercial, governmental, and tourist zones", "Rural only", "Walled city"], correctIndex: 1, explanation: "McGee 1967: primate port city (Jakarta, Manila, Bangkok) organized around colonial-era port, not Western CBD.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hgur-ent-5b", question: "PRIMATE CITY (Jefferson 1939): a country's largest city is:", options: ["Average size", "MUCH larger than the 2nd city (e.g., London 9× Birmingham; Bangkok 12× Chiang Mai; Paris 7× Lyon)", "Smaller than 2nd", "Equal to 2nd"], correctIndex: 1, explanation: "Primate city: disproportionate dominance. Often colonial/administrative legacy. Contrasts with balanced hierarchy (U.S., Germany).", partNumber: 5, partTitle: "Change Over Time" },
  { id: "hgur-ent-6a", question: "The RANK-SIZE RULE (Zipf 1949) predicts:", options: ["All cities equal", "nth city ≈ 1/n of largest city's population (U.S. approximates; many LICs don't due to primacy)", "Only capital matters", "Random sizes"], correctIndex: 1, explanation: "Zipf 1949: frequency ∝ 1/rank. U.S.: NYC ~8M, LA ~4M, Chicago ~2.7M. Rough approximation, better in countries without primate bias.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hgur-ent-6b", question: "CHRISTALLER's CENTRAL PLACE THEORY (1933) predicts:", options: ["Random urban locations", "Hexagonal hinterland pattern based on threshold (minimum demand) + range (max distance consumers travel); higher-order services in larger places", "Only coastal", "No pattern"], correctIndex: 1, explanation: "Christaller 1933, rural southern Germany. Hexagons minimize overlap/unserved area. Higher-order goods → higher threshold → fewer, larger centers.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "hgur-ent-7a", question: "On the AP HG exam, applying a city model requires:", options: ["Memorization alone", "Identifying the model, its assumptions, fit/misfit with the specific city, and modifications needed", "Only naming", "Only U.S. cities"], correctIndex: 1, explanation: "AP rubric: apply models critically. Identify assumptions (time, place, economy) and explain deviations in specific cases.", partNumber: 7, partTitle: "AP Review" },
  { id: "hgur-ent-7b", question: "Which AP-style claim is correct?", options: ["All cities look the same", "Urban form varies by era, culture, economy, colonial history — multiple models capture different patterns", "Only U.S. cities matter", "One model fits all"], correctIndex: 1, explanation: "No single model fits all cities. Multiple models (Burgess, Hoyt, Harris-Ullman, Latin American, African, SE Asian) capture diversity.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
