/**
 * Entrance Quiz — Aggregate Demand & Aggregate Supply (AP Macroeconomics)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-macro-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "macr-ent-1a", question: "Aggregate Demand (AD) slopes downward because of:", options: ["Diminishing marginal utility", "The wealth, interest-rate, and exchange-rate effects", "Income effects on individual goods", "Substitution between goods"], correctIndex: 1, explanation: "AD slopes down due to three macro effects: real-balances (wealth), interest-rate, and exchange-rate.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "macr-ent-1b", question: "Short-run aggregate supply (SRAS) slopes upward because:", options: ["Resources are perfectly mobile", "Sticky wages and prices mean firms expand output as the price level rises", "Government sets all prices", "Money supply rises"], correctIndex: 1, explanation: "SRAS upward slope reflects sticky nominal wages: as P rises, real wages fall, firms hire more and produce more.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "macr-ent-2a", question: "Long-run aggregate supply (LRAS) is vertical because:", options: ["Wages are perfectly sticky", "In the long run, output is determined by real factors (capital, labor, technology) — not the price level", "Government sets output", "AD is also vertical"], correctIndex: 1, explanation: "LRAS is vertical at potential output; in the long run, all prices and wages adjust, leaving real output unaffected by P.", partNumber: 2, partTitle: "Key Processes" },
  { id: "macr-ent-2b", question: "A rightward shift in AD can result from:", options: ["A tax increase", "Lower interest rates (more I), higher consumer confidence (more C), or expansionary fiscal policy", "A negative supply shock", "Lower government spending"], correctIndex: 1, explanation: "AD shifts right with anything that increases C, I, G, or NX at every price level.", partNumber: 2, partTitle: "Key Processes" },
  { id: "macr-ent-3a", question: "A negative supply shock (e.g., oil price spike) causes:", options: ["AD to shift right", "SRAS to shift LEFT, raising P and lowering Y → stagflation", "LRAS to shift right", "AD to shift left only"], correctIndex: 1, explanation: "Adverse supply shocks shift SRAS leftward, producing higher P and lower Y simultaneously (stagflation).", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "macr-ent-3b", question: "The 1973-74 OPEC oil embargo is the classic example of:", options: ["A demand shock", "A negative supply shock causing stagflation", "Monetary expansion", "Tax-cut stimulus"], correctIndex: 1, explanation: "OPEC's 1973 embargo quadrupled crude prices, shifting U.S. SRAS left — inflation hit double digits while unemployment rose.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "macr-ent-4a", question: "In a recessionary gap, output is BELOW potential. Self-correction in the long run requires:", options: ["AD to shift right on its own", "Nominal wages to fall, shifting SRAS rightward back to LRAS", "Government intervention only", "LRAS to shift left"], correctIndex: 1, explanation: "Long-run self-correction: with persistent unemployment, nominal wages fall, SRAS shifts right until Y = Y_f.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "macr-ent-4b", question: "In an inflationary (expansionary) gap, the self-correcting mechanism is:", options: ["Nominal wages rise as labor markets tighten, shifting SRAS leftward", "AD shifts left automatically", "LRAS shifts right", "The price level falls automatically"], correctIndex: 0, explanation: "When Y > Y_f, tight labor markets push nominal wages up; SRAS shifts left until Y = Y_f at a higher P.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "macr-ent-5a", question: "LRAS shifts rightward over time due to:", options: ["Money supply growth", "Increases in capital stock, labor force, or productivity", "Lower price levels", "AD growth"], correctIndex: 1, explanation: "LRAS growth = real factors: capital deepening, labor force expansion, technological progress.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "macr-ent-5b", question: "During the 2008-09 Great Recession, U.S. AD shifted leftward primarily due to:", options: ["Higher oil prices", "Collapse in C and I from housing wealth losses, financial-system freeze, and credit contraction", "A surge in government spending", "Currency depreciation"], correctIndex: 1, explanation: "The financial crisis collapsed wealth (C↓), froze credit (I↓), and shifted AD sharply left, requiring TARP and ARRA stimulus.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "macr-ent-6a", question: "If AD shifts right with the economy already at LRAS, the SHORT-RUN result is:", options: ["Higher Y, lower P", "Higher Y AND higher P (inflationary gap)", "Lower Y, lower P", "No change"], correctIndex: 1, explanation: "AD right when at full employment: short-run equilibrium moves up SRAS to higher P and Y above Y_f (inflationary gap).", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "macr-ent-6b", question: "Compute the recessionary gap if Y = $\\$19$T, Y_f = $\\$20$T, MPC = 0.75. The required ΔG to close it:", options: ["$1T", "$\\$250$ billion (multiplier = 4; ΔG = $\\$1$T/4)", "$4T", "$750 billion"], correctIndex: 1, explanation: "Multiplier = 1/(1−0.75) = 4. ΔG = gap/multiplier = $\\$1$T/4 = $\\$250$B.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "macr-ent-7a", question: "On the AP exam, a question asking you to draw AD-AS for a recessionary gap requires:", options: ["AD intersecting SRAS to the LEFT of LRAS", "AD intersecting SRAS to the RIGHT of LRAS", "AD = LRAS only", "Vertical AD"], correctIndex: 0, explanation: "Recessionary gap = SR equilibrium output (where AD ∩ SRAS) is LESS than LRAS (Y_f).", partNumber: 7, partTitle: "AP Review" },
  { id: "macr-ent-7b", question: "Which AP-style policy response addresses an inflationary gap?", options: ["Cut taxes (expansionary fiscal)", "Sell bonds (contractionary monetary) or raise taxes (contractionary fiscal) to shift AD left", "Lower the federal funds rate", "Increase G"], correctIndex: 1, explanation: "Inflationary gap → contractionary policy: shift AD leftward via tax hikes, G cuts, or Fed bond sales.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
