/**
 * Entrance Quiz — International Trade & Finance (AP Macroeconomics)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-macro-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "macr-ent-1a", question: "The Balance of Payments (BOP) consists of the:", options: ["Trade balance only", "Current account, capital account, and financial account, summing to ≈ 0", "Government budget", "GDP and unemployment rate"], correctIndex: 1, explanation: "BOP: Current Account + Capital Account + Financial Account ≈ 0 (with statistical discrepancy).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "macr-ent-1b", question: "The CURRENT ACCOUNT primarily includes:", options: ["Stock purchases", "Exports/imports of goods and services, net investment income, net transfers", "Foreign direct investment", "Central bank reserves"], correctIndex: 1, explanation: "Current account = trade balance + primary income (investment income) + secondary income (transfers like remittances).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "macr-ent-2a", question: "The U.S. has run persistent CURRENT ACCOUNT deficits since the early 1980s, financed by:", options: ["Tariffs", "Net capital INFLOWS (foreigners buying U.S. assets) — financial account surplus", "Foreign aid", "Gold sales"], correctIndex: 1, explanation: "U.S. CA deficit since 1982 has been mirrored by financial account surplus — net foreign purchases of U.S. assets.", partNumber: 2, partTitle: "Key Processes" },
  { id: "macr-ent-2b", question: "Under flexible exchange rates, a country's currency APPRECIATES when:", options: ["Demand for its currency rises (e.g., higher domestic real interest rates, more exports)", "Inflation rises sharply", "It runs trade deficits", "Its central bank prints more money"], correctIndex: 0, explanation: "Higher demand for currency in FX market → appreciation. Drivers: higher r, more exports, capital inflows.", partNumber: 2, partTitle: "Key Processes" },
  { id: "macr-ent-3a", question: "If the Mexican peso depreciates against the U.S. dollar:", options: ["U.S. exports to Mexico become MORE competitive", "Mexican exports to U.S. become more competitive (cheaper in dollar terms)", "Trade volumes don't change", "Both currencies are unaffected"], correctIndex: 1, explanation: "Peso depreciation → Mexican goods cheaper in USD terms → U.S. imports from Mexico rise; U.S. exports to Mexico fall.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "macr-ent-3b", question: "Which historical episode involved coordinated currency intervention?", options: ["1985 Plaza Accord (G5: U.S., Japan, W. Germany, France, U.K. agree to depreciate USD)", "1944 Bretton Woods established floating rates", "1973 OPEC embargo", "1995 NAFTA signing"], correctIndex: 0, explanation: "September 1985 Plaza Accord coordinated FX intervention to weaken the over-strong dollar after Volcker disinflation.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "macr-ent-4a", question: "A tariff on imports primarily:", options: ["Raises domestic prices, reduces import quantity, generates government revenue, creates DWL", "Lowers domestic prices", "Has no domestic effects", "Always reduces unemployment"], correctIndex: 0, explanation: "Tariff effects: ↑P_domestic, ↓Q_imports, gov revenue rectangle, deadweight loss triangles.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "macr-ent-4b", question: "A QUOTA differs from a tariff in that:", options: ["Quotas raise government revenue; tariffs do not", "Quotas restrict QUANTITY directly; surplus revenue accrues to importers (or via auctioned licenses)", "Quotas have no effect on price", "Quotas always lower deadweight loss"], correctIndex: 1, explanation: "Quotas restrict quantity; the tariff-equivalent rent goes to import license holders rather than government.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "macr-ent-5a", question: "In 1973, the global system of fixed exchange rates collapsed when:", options: ["The U.S. left the gold standard (Nixon Shock 1971) and major currencies floated", "OPEC formed", "WTO was created", "Bretton Woods was signed"], correctIndex: 0, explanation: "Bretton Woods system (1944-71) ended Aug 15, 1971 (Nixon Shock); major currencies began floating by 1973.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "macr-ent-5b", question: "Under the gold standard (~1870-1914), exchange rates were:", options: ["Floating", "Fixed via gold convertibility — countries pegged currency to gold", "Set by central banks", "Determined by tariffs"], correctIndex: 1, explanation: "Classical gold standard: each country fixed its currency in terms of gold; cross-rates were derived from gold parities.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "macr-ent-6a", question: "If U.S. and Mexico both have inflation, and U.S. inflation is HIGHER, purchasing-power parity (PPP) predicts:", options: ["USD will appreciate vs peso", "USD will DEPRECIATE vs peso (currency of higher-inflation country depreciates)", "No effect", "Peso will collapse"], correctIndex: 1, explanation: "PPP: currency of higher-inflation country depreciates over time to maintain real exchange rates.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "macr-ent-6b", question: "If the dollar APPRECIATES 10% against the euro, U.S. exports to Europe will likely:", options: ["Rise (cheaper for Europeans)", "Fall (more expensive for Europeans, requiring more euros per dollar)", "Stay constant", "Be replaced by tariffs"], correctIndex: 1, explanation: "Stronger USD → U.S. goods more expensive abroad → exports fall (and imports rise).", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "macr-ent-7a", question: "On the AP exam, the FX market graph for USD has:", options: ["Quantity of USD on Y, exchange rate on X", "Exchange rate (foreign currency per USD) on Y, quantity of USD on X", "Price level on Y, real GDP on X", "Interest rate on Y, money on X"], correctIndex: 1, explanation: "Standard AP FX market: Y-axis = foreign currency per USD, X-axis = quantity of USD.", partNumber: 7, partTitle: "AP Review" },
  { id: "macr-ent-7b", question: "Which AP-style action causes USD demand to INCREASE?", options: ["U.S. inflation rises faster than abroad", "U.S. real interest rates rise above foreign rates (capital inflow)", "U.S. trade deficit grows", "U.S. exports fall"], correctIndex: 1, explanation: "Higher U.S. real rates attract foreign capital → demand for USD shifts right → USD appreciates.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
