/**
 * Entrance Quiz — The Open Economy & Loanable Funds (AP Macroeconomics)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-macro-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "macr-ent-1a", question: "The loanable funds market determines:", options: ["Nominal interest rate and quantity of money", "REAL interest rate and quantity of loanable funds", "Exchange rate", "Price level"], correctIndex: 1, explanation: "Loanable funds: Y-axis = real interest rate, X-axis = quantity of loanable funds. NOT the money market.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "macr-ent-1b", question: "Demand for loanable funds comes primarily from:", options: ["Households saving", "Firms wanting to invest in capital and the government issuing bonds to finance deficits", "The Federal Reserve", "Foreign exporters"], correctIndex: 1, explanation: "D_LF = private investment demand + government borrowing (deficits).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "macr-ent-2a", question: "Supply of loanable funds comes from:", options: ["Government spending", "Private and public saving (national saving), plus net capital inflows from abroad", "Federal Reserve only", "Tax revenue"], correctIndex: 1, explanation: "S_LF = national saving (private + public) + net capital inflows in an open economy.", partNumber: 2, partTitle: "Key Processes" },
  { id: "macr-ent-2b", question: "Crowding out occurs when:", options: ["Government cuts spending", "Government deficits shift D_LF right, raising real interest rates and reducing private I", "The Fed sells bonds", "Imports rise"], correctIndex: 1, explanation: "Crowding out: ↑deficit → D_LF right → r↑ → I↓ → less private capital formation.", partNumber: 2, partTitle: "Key Processes" },
  { id: "macr-ent-3a", question: "If a country runs a TRADE DEFICIT, in the loanable funds market this implies:", options: ["A capital outflow", "A capital INFLOW (foreigners lending to the country) → S_LF shifts right", "No connection", "Higher tax revenue"], correctIndex: 1, explanation: "BOP identity: trade deficit ↔ capital inflow → S_LF shifts right (e.g., U.S. since 1982: foreign saving funds U.S. CA deficit).", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "macr-ent-3b", question: "The Reagan-era 'twin deficits' of the 1980s involved:", options: ["Trade surplus + budget surplus", "Large U.S. budget deficits + growing trade deficits, with foreign capital financing both", "Two trade surpluses", "Inflation surplus + deflation deficit"], correctIndex: 1, explanation: "1980s: Reagan tax cuts + defense buildup → budget deficit; high real rates → USD appreciation → trade deficit (twin deficits).", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "macr-ent-4a", question: "In a small open economy, the world real interest rate (r_world) determines the domestic rate, and a budget deficit:", options: ["Raises r above r_world", "Cannot raise r above r_world; instead it draws in foreign capital, with no crowding out (closed-economy logic doesn't apply)", "Has no effect", "Raises exchange rates only"], correctIndex: 1, explanation: "Small open economy: domestic r = r_world; deficits → capital inflow rather than r↑ → less crowding out, more trade deficit.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "macr-ent-4b", question: "If the U.S. budget deficit rises and S_LF doesn't change, the result is:", options: ["Lower real interest rates", "Higher real interest rates and crowding out of private investment", "More private investment", "No effect on r"], correctIndex: 1, explanation: "D_LF rightward shift with fixed S_LF: r↑ → I↓ → crowding out.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "macr-ent-5a", question: "During 2020-21, U.S. national saving FELL because:", options: ["Higher tax revenue", "Massive fiscal deficits ($\\$3.1$T FY2020, $\\$2.8$T FY2021) reduced PUBLIC saving", "Households saved more", "Investment fell"], correctIndex: 1, explanation: "Public saving = T − G − Transfers; large 2020-21 deficits made public saving sharply negative, reducing national saving.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "macr-ent-5b", question: "If foreign saving floods the U.S. via capital inflows, S_LF shifts:", options: ["Left", "Right → real interest rate falls, equilibrium quantity of loanable funds rises", "Vertical", "Doesn't shift"], correctIndex: 1, explanation: "Capital inflows boost S_LF; r falls and quantity rises (mid-2000s 'global savings glut' explanation, Bernanke 2005).", partNumber: 5, partTitle: "Change Over Time" },
  { id: "macr-ent-6a", question: "If real interest rate rises by 2%, holding everything else constant, private investment will:", options: ["Increase", "Decrease (move up the I demand curve)", "Stay constant", "Become zero"], correctIndex: 1, explanation: "Higher r → fewer projects with NPV > 0 → I demand quantity falls (movement up D_I curve).", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "macr-ent-6b", question: "If domestic S_LF = $\\$5$T, private I demand = $\\$4$T at r = 3%, and government deficit = $\\$2$T at r = 3%, market clearing requires:", options: ["r = 3%", "r above 3% (excess demand) until S_LF = D_LF; or capital inflows close the gap", "r = 0", "G = T"], correctIndex: 1, explanation: "Total demand $\\$4$T+$\\$2$T = $\\$6$T > $\\$5$T supply → r must rise OR foreign capital must flow in.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "macr-ent-7a", question: "On the AP exam, the loanable funds graph and money market graph differ on the:", options: ["Y-axis: loanable funds = REAL interest rate; money market = NOMINAL interest rate", "Both use the same axis", "X-axis only", "There is no difference"], correctIndex: 0, explanation: "Loanable funds: real interest rate. Money market: nominal interest rate. Critical AP distinction.", partNumber: 7, partTitle: "AP Review" },
  { id: "macr-ent-7b", question: "Which AP-style scenario LOWERS the real interest rate in the loanable funds market?", options: ["Government deficit increases", "Increase in private saving (S_LF shifts right)", "Higher private investment demand", "Tariff increase"], correctIndex: 1, explanation: "Higher national saving shifts S_LF right → r falls and equilibrium quantity rises.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
