/**
 * Entrance Quiz — Supply & Demand (AP Microeconomics)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-micro-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "micr-ent-1a", question: "The law of demand states that, ceteris paribus:", options: ["Higher price → higher quantity demanded", "Higher price → lower quantity demanded (downward-sloping D)", "Demand always rises", "Price doesn't affect quantity"], correctIndex: 1, explanation: "Law of demand: P↑ → Q_d↓ (substitution + income effects), holding other factors constant.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "micr-ent-1b", question: "The law of supply states that, ceteris paribus:", options: ["Higher price → lower quantity supplied", "Higher price → higher quantity supplied (upward-sloping S)", "Supply is always vertical", "Price has no effect on Q_s"], correctIndex: 1, explanation: "Law of supply: P↑ → Q_s↑ (firms have higher MC at higher Q and need higher P to cover it).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "micr-ent-2a", question: "A movement ALONG the demand curve is caused by:", options: ["A change in income", "A change in the good's own price", "A change in price of a substitute", "A change in tastes"], correctIndex: 1, explanation: "Own-price change → movement along D (change in quantity demanded). Other factors → SHIFT of D.", partNumber: 2, partTitle: "Key Processes" },
  { id: "micr-ent-2b", question: "Which causes demand for coffee to SHIFT RIGHT?", options: ["A rise in coffee's price", "A study showing coffee improves health (taste/preference change)", "A decrease in income (if coffee is normal)", "A drop in coffee bean prices"], correctIndex: 1, explanation: "Demand shifters: tastes, income (for normal goods), prices of related goods, expectations, # of buyers.", partNumber: 2, partTitle: "Key Processes" },
  { id: "micr-ent-3a", question: "If income RISES and demand for ramen FALLS, ramen is:", options: ["A normal good", "An inferior good", "A complement", "A substitute"], correctIndex: 1, explanation: "Inferior good: demand falls as income rises. Examples: instant ramen, used cars, generic groceries.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "micr-ent-3b", question: "Coffee and tea are SUBSTITUTES. A rise in coffee's price will:", options: ["Decrease tea demand", "Increase tea demand (shift right)", "Have no effect on tea", "Lower tea price"], correctIndex: 1, explanation: "Substitutes: when one's P rises, demand for the other shifts right.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "micr-ent-4a", question: "Cars and gasoline are COMPLEMENTS. A fall in gasoline price will:", options: ["Decrease car demand", "Increase car demand (shift right)", "Have no effect", "Lower car price only"], correctIndex: 1, explanation: "Complements: when one's P falls, demand for the other shifts right.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "micr-ent-4b", question: "A new technology that lowers production cost causes:", options: ["Demand to shift right", "Supply to shift right (lower MC at every Q)", "Demand to shift left", "Movement along supply only"], correctIndex: 1, explanation: "Supply shifters: input prices, technology, # of sellers, expected future prices, taxes/subsidies.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "micr-ent-5a", question: "During the 2020 COVID toilet-paper shortage, equilibrium was disturbed by:", options: ["A leftward shift in supply only", "A sharp rightward shift in DEMAND (panic buying) overwhelming supply", "A leftward shift in demand", "Tariffs"], correctIndex: 1, explanation: "March 2020 saw demand surge from panic buying while supply chains had limited capacity → shortages and price spikes.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "micr-ent-5b", question: "In the 1970s, OPEC oil embargoes caused gasoline shortages because:", options: ["Demand shifted right", "Supply shifted LEFT and U.S. price controls created persistent shortages and queues", "Price ceilings increased Q", "There was no shortage"], correctIndex: 1, explanation: "1973-74 OPEC embargo shifted oil supply left; U.S. price controls (Nixon 1971+) prevented prices from clearing → gasoline lines.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "micr-ent-6a", question: "Equilibrium price is where:", options: ["Demand = Supply curves cross", "Quantity demanded = Quantity supplied (no shortage or surplus)", "Demand is highest", "MC = 0"], correctIndex: 1, explanation: "Equilibrium: Q_d = Q_s; market clears with no excess demand or supply.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "micr-ent-6b", question: "If P > equilibrium price, the result is:", options: ["A shortage", "A surplus that pushes price down", "Equilibrium", "An increase in demand"], correctIndex: 1, explanation: "Above equilibrium: Q_s > Q_d → surplus → competitive pressure pushes P down toward equilibrium.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "micr-ent-7a", question: "On the AP exam, a question asking the effect of two simultaneous shifts (e.g., D right and S right) tests:", options: ["Only the price effect (always rises)", "That one variable (P or Q) is determinate, the other indeterminate without magnitudes", "Both must rise", "Both must fall"], correctIndex: 1, explanation: "When D and S both shift right, Q definitely rises but P direction is indeterminate without knowing magnitudes.", partNumber: 7, partTitle: "AP Review" },
  { id: "micr-ent-7b", question: "Which AP-style claim is correct?", options: ["A change in the good's own price shifts the demand curve", "A change in the good's own price causes movement ALONG the demand curve", "Tastes shift only the supply curve", "Income shifts only the supply curve"], correctIndex: 1, explanation: "Own-price change → movement along D (Δquantity demanded). Other factors → shift of D (Δdemand).", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
