/**
 * Entrance Quiz — Government Intervention (AP Microeconomics)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-micro-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "micr-ent-1a", question: "A binding price CEILING (e.g., rent control) below equilibrium causes:", options: ["A surplus and falling rents", "A SHORTAGE, DWL, deteriorating quality, and possible black markets", "Equilibrium pricing", "No effect"], correctIndex: 1, explanation: "Binding ceiling: Q_d > Q_s → shortage. Long-run effects: reduced quality, less new construction, queues.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "micr-ent-1b", question: "A binding price FLOOR (e.g., minimum wage) above equilibrium causes:", options: ["A shortage of labor", "A SURPLUS of labor (unemployment) and DWL", "Equilibrium", "Lower wages"], correctIndex: 1, explanation: "Binding floor: Q_s > Q_d → surplus. Min wage above equilibrium → unemployment among low-skill workers (in textbook competitive model).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "micr-ent-2a", question: "Excise taxes on producers shift:", options: ["Demand left", "Supply LEFT (upward) by the per-unit tax — wedge between price paid and price received", "Both curves left", "Neither curve"], correctIndex: 1, explanation: "Per-unit tax on producers shifts S up by tax. New equilibrium: P_consumer > P_producer with wedge = tax.", partNumber: 2, partTitle: "Key Processes" },
  { id: "micr-ent-2b", question: "Tax incidence falls more heavily on the side with:", options: ["Higher elasticity", "Lower elasticity (more inelastic side absorbs more)", "Equal elasticity", "Government regulation"], correctIndex: 1, explanation: "Incidence ∝ inelasticity. Cigarette taxes mostly fall on smokers (inelastic D); luxury taxes mostly fall on producers (elastic D).", partNumber: 2, partTitle: "Key Processes" },
  { id: "micr-ent-3a", question: "U.S. federal tariffs on Chinese imports rose sharply during:", options: ["1930s only", "2018-19 (Section 301 tariffs on $370B+) and 2024-25", "1995-2001", "Never"], correctIndex: 1, explanation: "Trump 2018-19 Section 301 tariffs on ~$370B Chinese imports; further escalations 2024-25 raise effective tariff rates further.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "micr-ent-3b", question: "Smoot-Hawley Tariff Act (1930) raised tariffs on ~20,000 imports and:", options: ["Boosted U.S. exports", "Triggered retaliatory tariffs that contributed to the Great Depression's depth (international trade fell ~65%)", "Lowered domestic prices", "Eliminated unemployment"], correctIndex: 1, explanation: "Smoot-Hawley raised average tariffs to ~60%; world trade collapsed by ~65% by 1934, deepening the Depression (Eichengreen, Irwin).", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "micr-ent-4a", question: "A subsidy to producers shifts:", options: ["Supply LEFT", "Supply RIGHT, lowering P_consumer and raising P_producer with deadweight loss (overproduction)", "Demand right", "No curves"], correctIndex: 1, explanation: "Per-unit subsidy = anti-tax. S shifts down/right by subsidy amount. New equilibrium: more Q, lower P_consumer, higher P_producer; DWL from overproduction beyond efficient.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "micr-ent-4b", question: "U.S. agricultural price supports above market equilibrium typically lead to:", options: ["Shortage", "Surplus production that government must buy or store; commodity programs date to AAA 1933", "Higher consumer prices only", "No effect on Q"], correctIndex: 1, explanation: "Price floor above equilibrium → surplus. AAA 1933 (Agricultural Adjustment Act) created supply-management programs continuing in modified form today.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "micr-ent-5a", question: "DWL from a per-unit tax equals:", options: ["Tax revenue", "½ × tax wedge × ΔQ (the lost-trades triangle)", "Total revenue", "Tax × Q traded"], correctIndex: 1, explanation: "DWL = ½ × t × ΔQ; tax revenue = t × Q_after-tax (separate area).", partNumber: 5, partTitle: "Change Over Time" },
  { id: "micr-ent-5b", question: "U.S. NYC rent stabilization (post-1969) covers about how many apartments?", options: ["10 thousand", "About 1 million units (~50% of NYC rental stock)", "5 million", "Zero"], correctIndex: 1, explanation: "NYC has ~1 million rent-stabilized apartments (Census 2023, ~50% of rental stock); persistent shortages, deferred maintenance documented.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "micr-ent-6a", question: "Calculate DWL of a $3/unit tax that reduces Q from 200 to 150:", options: ["$0", "$\\$75$ (= ½ × $\\$3$ × 50)", "$450", "$600"], correctIndex: 1, explanation: "DWL = ½ × tax wedge × ΔQ = ½ × $\\$3$ × 50 = $\\$75$.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "micr-ent-6b", question: "Calculate tax revenue from the previous question:", options: ["$150", "$\\$450$ (= $\\$3$ × 150)", "$600", "$75"], correctIndex: 1, explanation: "Revenue = tax × Q_after-tax = $\\$3$ × 150 = $\\$450$.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "micr-ent-7a", question: "On the AP exam, a question on 'who bears the burden of a payroll tax' likely tests:", options: ["Workers always", "Employers always", "Statutory vs. economic incidence — true incidence depends on relative elasticities, not who legally pays", "Both 50/50 always"], correctIndex: 2, explanation: "Economic incidence (who actually bears the burden) is independent of statutory incidence; depends on labor demand/supply elasticities.", partNumber: 7, partTitle: "AP Review" },
  { id: "micr-ent-7b", question: "Which AP-style claim is correct?", options: ["Tariffs always benefit consumers", "Tariffs raise domestic prices, reduce consumer surplus, increase producer surplus, raise gov revenue, and create DWL", "Tariffs eliminate DWL", "Tariffs reduce producer surplus"], correctIndex: 1, explanation: "Standard tariff effects: ↑P_domestic, ↓CS, ↑PS, ↑Gov revenue, net DWL (CS loss > PS + Rev gains).", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
