/**
 * Entrance Quiz — Monopolistic Competition & Oligopoly (AP Microeconomics)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-micro-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "micr-ent-1a", question: "Monopolistic competition has:", options: ["One firm", "MANY firms with DIFFERENTIATED products and free entry/exit", "Two firms", "Identical products"], correctIndex: 1, explanation: "Mon comp: many firms (like PC) but differentiated products (each firm has slight market power).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "micr-ent-1b", question: "In the SHORT RUN, a monopolistically competitive firm:", options: ["Always earns zero profit", "Can earn positive economic profit (faces downward-sloping D, sets MR = MC)", "Always loses money", "Charges P = MC"], correctIndex: 1, explanation: "SR: like a monopoly, mon comp firm sets MR = MC and can earn positive economic profit.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "micr-ent-2a", question: "In the LONG RUN, monopolistic competition:", options: ["Earns positive profit", "Earns ZERO economic profit (entry causes D to shift left until tangent to ATC)", "Behaves like pure monopoly", "Has negative profit"], correctIndex: 1, explanation: "Free entry erodes profit: D for each firm shifts left until tangent to ATC → P = ATC > MC, zero economic profit.", partNumber: 2, partTitle: "Key Processes" },
  { id: "micr-ent-2b", question: "Monopolistic competition produces with:", options: ["Productive efficiency", "EXCESS capacity (P > MC and Q below min ATC) and product variety as a trade-off", "P = min ATC", "P = MC"], correctIndex: 1, explanation: "Mon comp LR: tangency on downward-sloping D means firm produces below min ATC (excess capacity); P > MC means allocative inefficiency.", partNumber: 2, partTitle: "Key Processes" },
  { id: "micr-ent-3a", question: "Real-world examples of monopolistic competition include:", options: ["Wheat farming", "Restaurants, clothing brands, hair salons (many sellers, differentiated products)", "Local water utility", "Diamond mining"], correctIndex: 1, explanation: "Mon comp: restaurants, fashion brands, books, salons — differentiated by location, style, brand, quality.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "micr-ent-3b", question: "Oligopoly is characterized by:", options: ["Many small firms", "A FEW large firms with mutual interdependence and significant barriers to entry", "One firm", "Identical products always"], correctIndex: 1, explanation: "Oligopoly: few firms (3-10), each firm's actions affect rivals → strategic interaction. Cars, airlines, oil refining.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "micr-ent-4a", question: "In a Prisoner's Dilemma payoff matrix, the NASH EQUILIBRIUM is:", options: ["The cooperative outcome", "Each player's BEST RESPONSE given the other's choice; often inferior to cooperation", "Random", "Zero payoff"], correctIndex: 1, explanation: "Nash: no player can improve by unilateral deviation. In PD, dominant strategies → mutual defection (worse than cooperation).", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "micr-ent-4b", question: "OPEC was founded in 1960 as a CARTEL to:", options: ["Eliminate oil production", "Coordinate output to raise prices and increase member revenue", "Privatize national oil companies", "Phase out fossil fuels"], correctIndex: 1, explanation: "OPEC (Organization of Petroleum Exporting Countries, 1960) coordinates production quotas to support oil prices — classic cartel.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "micr-ent-5a", question: "OPEC members frequently CHEAT on production quotas because:", options: ["Quotas are non-binding", "Each member individually gains by exceeding quota when others comply (dominant defect strategy in repeated game)", "OPEC enforces strictly", "Cheating reduces revenue"], correctIndex: 1, explanation: "Each member's individual incentive: produce extra to capture revenue, while collective quota holds prices up. Classic cartel instability.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "micr-ent-5b", question: "Repeated games can sustain cooperation through:", options: ["One-shot dominance", "Tit-for-tat strategies and credible punishment (Axelrod 1984)", "Random play", "Public announcements only"], correctIndex: 1, explanation: "In repeated games (Folk Theorem), credible punishment for defection (e.g., tit-for-tat) can sustain cooperation that fails in one-shot games.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "micr-ent-6a", question: "If two firms have payoffs (50, 50) for cooperate and (30, 30) for defect, but defect is dominant, they end up at:", options: ["Cooperate (better outcome)", "Defect (Nash equilibrium); Pareto inferior outcome — Prisoner's Dilemma", "Mixed strategy", "No equilibrium"], correctIndex: 1, explanation: "Dominant defect strategy → both defect → (30,30) Nash equilibrium, despite (50,50) being available — Prisoner's Dilemma.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "micr-ent-6b", question: "Compared to perfect competition, oligopoly typically has:", options: ["Lower prices", "Higher prices, lower output, and possible DWL (varies by market structure)", "Identical outcomes", "Zero profit always"], correctIndex: 1, explanation: "Oligopoly markup over MC creates DWL similar to monopoly, though magnitude varies with rivalry intensity.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "micr-ent-7a", question: "On the AP exam, a question asking 'identify the dominant strategy' requires you to:", options: ["Look at row sums", "Compare each player's payoffs across the OTHER player's strategies; choose the strategy that's best regardless", "Add all payoffs", "Choose the highest single number"], correctIndex: 1, explanation: "Dominant strategy: best response to EVERY action of the opponent. Compare payoffs in each opponent column.", partNumber: 7, partTitle: "AP Review" },
  { id: "micr-ent-7b", question: "Which AP-style claim about cartels is correct?", options: ["Cartels are illegal in the U.S. under antitrust law (Sherman Act 1890)", "Cartels always succeed", "Cartels increase consumer surplus", "Cartels lower prices"], correctIndex: 0, explanation: "Sherman Antitrust Act 1890 § 1 prohibits price-fixing and output restriction agreements — cartels are per se illegal in the U.S.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
