/**
 * Entrance Quiz — Production & Costs (AP Microeconomics)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-micro-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "micr-ent-1a", question: "In the SHORT RUN:", options: ["All inputs are variable", "At least one input (typically capital) is FIXED; others are variable", "All inputs are fixed", "Firms cannot produce"], correctIndex: 1, explanation: "Short run = at least one input fixed (usually plant size). Long run = all inputs variable.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "micr-ent-1b", question: "The law of DIMINISHING MARGINAL RETURNS states that, holding fixed inputs constant:", options: ["Adding more variable input always raises MP", "Beyond some point, additional variable input adds LESS extra output (MP_L falls)", "MP rises forever", "Output cannot increase"], correctIndex: 1, explanation: "Diminishing MP: with fixed capital, each extra unit of labor eventually adds less extra output.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "micr-ent-2a", question: "Marginal cost (MC) eventually RISES because of:", options: ["Diminishing marginal returns to the variable input", "Increasing returns to scale", "Falling input prices", "Government regulation"], correctIndex: 0, explanation: "Falling MP_L (diminishing returns) → rising MC: each extra unit of output requires more variable input.", partNumber: 2, partTitle: "Key Processes" },
  { id: "micr-ent-2b", question: "ATC = AFC + AVC. As Q rises:", options: ["AFC rises", "AFC falls (fixed cost spread over more units); AVC eventually rises; ATC is U-shaped", "Both AFC and AVC always fall", "ATC is constant"], correctIndex: 1, explanation: "AFC = FC/Q always falls. AVC and ATC are U-shaped due to diminishing returns and spreading effect.", partNumber: 2, partTitle: "Key Processes" },
  { id: "micr-ent-3a", question: "Marginal cost intersects ATC and AVC at:", options: ["Their maximums", "Their MINIMUMS (geometric property of marginal-average relationship)", "Q = 0", "Origin"], correctIndex: 1, explanation: "MC cuts ATC and AVC at their minimum points — when MC < AVG, AVG falls; when MC > AVG, AVG rises.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "micr-ent-3b", question: "In the LONG RUN, all inputs are variable, so the long-run ATC (LRATC) shows:", options: ["Constant returns to scale always", "Economies of scale (LRATC falls), constant returns, then diseconomies of scale (LRATC rises)", "Always rising costs", "Always falling costs"], correctIndex: 1, explanation: "U-shaped LRATC: economies (specialization), then constant returns, then diseconomies (coordination problems).", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "micr-ent-4a", question: "ECONOMIC profit differs from ACCOUNTING profit because:", options: ["Economic profit subtracts only explicit costs", "Economic profit subtracts both explicit AND implicit (opportunity) costs", "They are identical", "Accounting includes implicit costs only"], correctIndex: 1, explanation: "Accounting profit = Revenue − Explicit Costs. Economic profit = Revenue − Explicit − Implicit (opportunity) costs.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "micr-ent-4b", question: "If Total Cost = $1,000 at Q = 100, then ATC equals:", options: ["$1,000", "$\\$10$ ($\\$1{,}000$/100)", "$100", "$1"], correctIndex: 1, explanation: "ATC = TC/Q = $\\$1{,}000$/100 = $\\$10$.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "micr-ent-5a", question: "Henry Ford's 1913 moving assembly line at Highland Park reduced Model T production time per chassis from:", options: ["Days to weeks", "About 12.5 hours to 1.5 hours (achieving massive economies of scale)", "It had no effect", "Years to months"], correctIndex: 1, explanation: "Ford's assembly line cut chassis assembly from 12.5 hours (1913) to 1.5 hours, exemplifying economies of scale through specialization.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "micr-ent-5b", question: "Calculate marginal cost between Q=10 (TC=$\\$50$) and Q=11 (TC=$\\$58$):", options: ["$8 (ΔTC/ΔQ)", "$58", "$5", "$108"], correctIndex: 0, explanation: "MC = ΔTC/ΔQ = ($\\$58$ − $\\$50$)/(11 − 10) = $\\$8$.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "micr-ent-6a", question: "If MP_L is rising and the wage is constant, MC is:", options: ["Rising", "Falling (each extra worker adds more output for the same wage)", "Constant", "Zero"], correctIndex: 1, explanation: "MC = w/MP_L. Rising MP_L with constant w → MC falls (initial range before diminishing returns).", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "micr-ent-6b", question: "If MC = $\\$20$ and ATC = $\\$25$ at Q = 100, then producing one more unit will:", options: ["Raise ATC", "LOWER ATC (since MC < ATC pulls average down)", "Leave ATC unchanged", "Raise FC"], correctIndex: 1, explanation: "When MC < ATC, average falls (you're adding a below-average cost unit). When MC > ATC, average rises.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "micr-ent-7a", question: "On the AP exam, the SHUTDOWN price for a competitive firm is:", options: ["Minimum ATC", "Minimum AVC (below this, even VC isn't covered → firm shuts down in short run)", "Zero", "Maximum MC"], correctIndex: 1, explanation: "Short-run shutdown: P < min AVC → firm cannot cover variable costs → produce 0 (lose only FC).", partNumber: 7, partTitle: "AP Review" },
  { id: "micr-ent-7b", question: "Which AP-style claim is correct?", options: ["Implicit costs are not real costs", "Implicit costs (e.g., owner's forgone wages) are real opportunity costs and reduce economic profit", "Implicit costs apply only to corporations", "Implicit costs equal sunk costs"], correctIndex: 1, explanation: "Implicit costs (forgone wages, forgone interest on owner's capital) are real opportunity costs — central to economic profit.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
