/**
 * Entrance Quiz — Elasticity (AP Microeconomics)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-micro-entrance-quizzes.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "micr-ent-1a", question: "Price elasticity of demand (PED) measures:", options: ["Slope of the demand curve", "Percent change in Q_d divided by percent change in P (in absolute value)", "Total revenue", "Marginal cost"], correctIndex: 1, explanation: "PED = |%ΔQ_d / %ΔP|. Pure ratio of percentages — independent of units.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "micr-ent-1b", question: "If |PED| > 1, demand is:", options: ["Inelastic", "Elastic (Q changes proportionally MORE than P)", "Unit elastic", "Perfectly inelastic"], correctIndex: 1, explanation: "Elastic: |PED| > 1 → consumers very responsive to price changes.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "micr-ent-2a", question: "If |PED| < 1, raising price will:", options: ["Decrease total revenue", "Increase total revenue (TR)", "Have no effect on TR", "Always increase quantity sold"], correctIndex: 1, explanation: "Inelastic demand: price hike outweighs quantity loss → TR rises.", partNumber: 2, partTitle: "Key Processes" },
  { id: "micr-ent-2b", question: "If |PED| > 1, raising price will:", options: ["Increase TR", "Decrease TR (Q falls more than P rises in %)", "Have no effect", "Always increase profit"], correctIndex: 1, explanation: "Elastic demand: quantity loss outweighs price hike → TR falls when P rises.", partNumber: 2, partTitle: "Key Processes" },
  { id: "micr-ent-3a", question: "Determinants of demand elasticity include:", options: ["Income only", "Substitutes available, share of budget, time horizon, necessity vs luxury", "Cost of production", "Government regulation"], correctIndex: 1, explanation: "More substitutes, larger budget share, longer time horizon, and luxury status → MORE elastic demand.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "micr-ent-3b", question: "Insulin demand for diabetics is highly:", options: ["Elastic", "Inelastic (no substitutes, necessity)", "Perfectly elastic", "Unit elastic"], correctIndex: 1, explanation: "Insulin = life-saving necessity with no close substitutes → highly inelastic demand.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "micr-ent-4a", question: "Long-run gasoline demand is more ELASTIC than short-run because:", options: ["Cars become more important", "Consumers can switch vehicles, locations, or transit modes given enough time", "Government regulates more", "Prices fall"], correctIndex: 1, explanation: "Time allows substitution: hybrids, EVs, public transit, relocating closer to work → long-run E > short-run E.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "micr-ent-4b", question: "Income elasticity of demand for normal goods is:", options: ["Negative", "Positive", "Zero", "Always greater than 1"], correctIndex: 1, explanation: "Normal goods: income↑ → demand↑ → income elasticity > 0. Luxuries have YED > 1; necessities have 0 < YED < 1.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "micr-ent-5a", question: "Cross-price elasticity between two SUBSTITUTES is:", options: ["Negative", "Positive", "Zero", "Undefined"], correctIndex: 1, explanation: "Substitutes have positive cross-price elasticity (Coke price up → Pepsi demand up).", partNumber: 5, partTitle: "Change Over Time" },
  { id: "micr-ent-5b", question: "Cross-price elasticity between two COMPLEMENTS is:", options: ["Negative", "Positive", "Zero", "Undefined"], correctIndex: 0, explanation: "Complements have negative cross-price elasticity (cars and gasoline; coffee and cream).", partNumber: 5, partTitle: "Change Over Time" },
  { id: "micr-ent-6a", question: "Calculate PED using midpoint when P rises from $4 to $6 and Q falls from 100 to 80:", options: ["0.45", "0.56 (= |−22.2%/40%|)", "1.25", "2.00"], correctIndex: 1, explanation: "Midpoint: %ΔQ = (80−100)/90 = −22.2%; %ΔP = (6−4)/5 = 40%. PED = 22.2/40 = 0.555.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "micr-ent-6b", question: "If demand is perfectly INELASTIC, the demand curve is:", options: ["Horizontal", "Vertical (Q doesn't change with P)", "Upward sloping", "Downward sloping with slope = 1"], correctIndex: 1, explanation: "Perfectly inelastic: PED = 0 → vertical demand curve. Real-world close approximation: insulin, life-saving treatments.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "micr-ent-7a", question: "On the AP exam, the connection between elasticity and tax incidence is:", options: ["More elastic side bears more tax", "Less elastic (more inelastic) side bears more of the tax", "Tax falls equally regardless of elasticity", "Elasticity doesn't affect tax incidence"], correctIndex: 1, explanation: "Tax incidence: more inelastic side bears more burden (cigarette taxes mostly fall on consumers).", partNumber: 7, partTitle: "AP Review" },
  { id: "micr-ent-7b", question: "Which AP-style scenario implies elastic demand?", options: ["Insulin", "Premium dining options at one of many local restaurants (many close substitutes)", "Water", "A life-saving medication"], correctIndex: 1, explanation: "Many close substitutes → high elasticity. Necessities with few substitutes → inelastic.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
