/**
 * Entrance Quiz — Observational Learning & Cognition (AP Psychology)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-psych-entrance-quizzes-batch*.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "olc-ent-1a", question: "Observational (social) learning was systematized by:", options: ["B.F. Skinner", "Albert Bandura — Social Learning / Social Cognitive Theory (1960s-)", "Pavlov", "Tolman"], correctIndex: 1, explanation: "Bandura argued people learn by observing models, not just through direct reinforcement — extending behaviorism toward cognitive social learning.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "olc-ent-1b", question: "Bandura's Bobo doll study (1961) found that children who watched an aggressive adult model:", options: ["Were less aggressive", "Were MORE likely to imitate the specific aggressive acts toward the doll, even without reinforcement", "Showed no effect", "Became calmer"], correctIndex: 1, explanation: "Bobo doll experiments demonstrated imitation/modeling and influenced later concerns about media violence.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "olc-ent-2a", question: "Bandura's four key processes for observational learning are:", options: ["Eat, sleep, move, repeat", "Attention, retention, reproduction (motor), motivation", "Stimulus, response, reward, punishment", "Id, ego, superego, drive"], correctIndex: 1, explanation: "Each step can fail: didn't pay attention, didn't remember, can't physically reproduce, or no motivation to perform.", partNumber: 2, partTitle: "Key Processes" },
  { id: "olc-ent-2b", question: "Vicarious reinforcement / vicarious punishment occurs when:", options: ["You receive reinforcement", "Observing a model BEING reinforced or punished changes the observer's likelihood of performing the behavior", "Behaviors decrease randomly", "Only humans use it"], correctIndex: 1, explanation: "Bobo follow-ups: children imitated MORE when the model was rewarded and LESS when punished, even though the children themselves received nothing.", partNumber: 2, partTitle: "Key Processes" },
  { id: "olc-ent-3a", question: "Mirror neurons (di Pellegrino, Rizzolatti et al. 1992) fire both when an animal:", options: ["Sleeps and wakes", "Performs an action AND when it observes another performing the same action", "Eats and digests", "Sees and hears"], correctIndex: 1, explanation: "Macaque mirror neurons (premotor F5) suggested a neural basis for imitation, though their role in human social cognition is debated.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "olc-ent-3b", question: "Observational learning is especially powerful when the model is:", options: ["Strange and unrelated", "Similar to the observer, high-status, attractive, warm, or successful", "Punished severely", "Unknown"], correctIndex: 1, explanation: "Bandura: model characteristics (status, similarity, warmth) increase attention and motivation to imitate.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "olc-ent-4a", question: "Insight learning (Wolfgang Köhler's chimps, ~1925) is:", options: ["Slow trial-and-error", "Sudden 'aha' solution after restructuring the problem (Sultan stacking boxes to reach bananas)", "Reinforcement-driven", "Imitation"], correctIndex: 1, explanation: "Köhler's Mentality of Apes argued some learning is sudden/cognitive, not just incremental — challenging strict behaviorism.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "olc-ent-4b", question: "Latent learning (Tolman & Honzik 1930) showed:", options: ["Learning requires immediate reinforcement", "Learning can occur WITHOUT reinforcement and remain hidden until reward provides MOTIVATION to perform", "Animals cannot learn mazes", "Only classical conditioning works"], correctIndex: 1, explanation: "Rats with no reward formed cognitive maps; once rewarded, they performed as well as continuously-rewarded rats.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "olc-ent-5a", question: "The overjustification effect (Lepper, Greene, & Nisbett 1973) found that:", options: ["External rewards always boost interest", "Excessive EXTERNAL rewards for an already-intrinsically-rewarding activity can REDUCE intrinsic motivation", "Rewards do nothing", "Punishment increases interest"], correctIndex: 1, explanation: "Children who liked drawing lost interest after being rewarded for it — implications for classroom and parenting practice.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "olc-ent-5b", question: "Carol Dweck's (1988-) growth vs fixed mindset research found that students taught a:", options: ["Fixed mindset achieve more", "GROWTH mindset (intelligence is malleable with effort) tend to show greater resilience and improvement than those with a fixed mindset", "Mindsets don't matter", "Reward mindset is best"], correctIndex: 1, explanation: "Dweck's mindset interventions are influential, though effect sizes are debated and replication results are mixed.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "olc-ent-6a", question: "Prosocial modeling (e.g., children who see helpful models help more) and antisocial modeling (e.g., bullying spread by peer models) both demonstrate:", options: ["Operant conditioning only", "The power of OBSERVATIONAL learning to spread both helpful and harmful behaviors across social networks", "Classical conditioning", "Innate reflexes"], correctIndex: 1, explanation: "Bandura emphasized that modeling is a major mechanism for cultural transmission of values and behavior.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "olc-ent-6b", question: "Bandura's concept of self-efficacy refers to:", options: ["Self-esteem in general", "A person's BELIEF in their capability to perform a specific task — predicts persistence and achievement", "IQ", "Locus of control"], correctIndex: 1, explanation: "Self-efficacy beliefs influence task choice, effort, persistence, and resilience — distinct from global self-esteem.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "olc-ent-7a", question: "On the AP Psych exam, a question about teens copying risky stunts after watching a viral video describes:", options: ["Operant conditioning", "Observational learning / modeling (Bandura)", "Classical conditioning", "Habituation"], correctIndex: 1, explanation: "Imitation of media models is the modern extension of Bandura's Bobo work.", partNumber: 7, partTitle: "AP Review" },
  { id: "olc-ent-7b", question: "Which AP-style claim is correct?", options: ["Only direct reinforcement teaches new behavior", "Humans learn extensively by observing others, allowing cultural transmission of skills, language, and values that direct reinforcement could not efficiently teach", "Cognition plays no role in learning", "Mirror neurons fully explain imitation"], correctIndex: 1, explanation: "Bandura's social cognitive theory expanded learning theory to include attention, expectation, and self-regulation.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
