/**
 * Entrance Quiz — Operant Conditioning (AP Psychology)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-psych-entrance-quizzes-batch*.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "oc-ent-1a", question: "Operant conditioning was systematized by:", options: ["Pavlov", "B.F. Skinner (building on Thorndike's Law of Effect, 1898) using operant chambers ('Skinner boxes')", "Wundt", "Freud"], correctIndex: 1, explanation: "Thorndike (1898) Law of Effect: behaviors followed by satisfying consequences are more likely to recur. Skinner extended this systematically.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "oc-ent-1b", question: "Thorndike's Law of Effect states behaviors followed by:", options: ["Punishment are repeated", "Satisfying consequences are STRENGTHENED; behaviors followed by aversive consequences are weakened", "Nothing change", "Time delays vanish"], correctIndex: 1, explanation: "Thorndike's puzzle-box cats learned to escape faster after each successful trial — basis of all instrumental learning research.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "oc-ent-2a", question: "POSITIVE reinforcement:", options: ["Removes a stimulus", "ADDS a desirable stimulus to increase a behavior (e.g., praise after homework)", "Removes a chore", "Decreases behavior"], correctIndex: 1, explanation: "'Positive' = added; 'reinforcement' = increases behavior. Both reinforcement types INCREASE behavior.", partNumber: 2, partTitle: "Key Processes" },
  { id: "oc-ent-2b", question: "NEGATIVE reinforcement:", options: ["Adds a punisher", "REMOVES an aversive stimulus to increase a behavior (buckling a seatbelt to stop the beeping)", "Decreases behavior", "Is the same as punishment"], correctIndex: 1, explanation: "Negative reinforcement is NOT punishment — it removes something unpleasant, INCREASING the behavior that ended the aversive state.", partNumber: 2, partTitle: "Key Processes" },
  { id: "oc-ent-3a", question: "POSITIVE punishment:", options: ["Removes a desired item", "ADDS an aversive stimulus to DECREASE behavior (a speeding ticket)", "Increases behavior", "Removes a chore"], correctIndex: 1, explanation: "Both punishments DECREASE behavior. 'Positive' = added stimulus; 'negative' = removed stimulus.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "oc-ent-3b", question: "NEGATIVE punishment (response cost):", options: ["Adds a chore", "REMOVES a desirable stimulus to DECREASE behavior (taking away phone privileges)", "Adds praise", "Increases behavior"], correctIndex: 1, explanation: "Time-out and loss of privileges are negative punishment. Skinner generally favored reinforcement over punishment as more effective.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "oc-ent-4a", question: "A primary reinforcer is:", options: ["A learned reinforcer", "Innately reinforcing — satisfies a biological need (food, water, warmth)", "Money", "A grade"], correctIndex: 1, explanation: "Primary reinforcers are biologically wired. Secondary (conditioned) reinforcers (money, grades) acquire value through pairing.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "oc-ent-4b", question: "Shaping is:", options: ["One-trial learning", "Reinforcing successive APPROXIMATIONS toward a target behavior (used to train animals and shape complex skills)", "Removing reinforcement", "Punishment"], correctIndex: 1, explanation: "Skinner shaped pigeons to peck disks, play ping-pong, etc. — by reinforcing closer-and-closer behaviors.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "oc-ent-5a", question: "A FIXED-RATIO (FR) schedule reinforces:", options: ["After variable time", "After every Nth response (e.g., FR-10) — produces high response rates with brief post-reinforcement pauses", "Random", "Continuous"], correctIndex: 1, explanation: "FR (e.g., piecework pay) → fast steady responding with a pause right after each reinforcer.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "oc-ent-5b", question: "A VARIABLE-RATIO (VR) schedule (e.g., slot machines) produces:", options: ["The lowest response rate", "The HIGHEST and most extinction-resistant response rates — reinforcement after an unpredictable number of responses", "Slow responding", "No learning"], correctIndex: 1, explanation: "VR schedules drive gambling and many addictive behaviors. Hard to extinguish because every response could be 'the one.'", partNumber: 5, partTitle: "Change Over Time" },
  { id: "oc-ent-6a", question: "FIXED-INTERVAL (FI) schedules produce:", options: ["Steady responding throughout", "A SCALLOPED pattern — slow responding after reinforcement, accelerating just before the next reinforcer (e.g., studying right before a weekly quiz)", "Random bursts", "No responding"], correctIndex: 1, explanation: "FI: only the first response after a fixed time period is reinforced. Cumulative records show characteristic scallop.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "oc-ent-6b", question: "Cognitive map / latent learning was demonstrated by:", options: ["Watson", "Edward Tolman (1948) — rats that explored a maze without reinforcement showed sudden mastery once reward was introduced, implying mental maps", "Skinner", "Thorndike"], correctIndex: 1, explanation: "Tolman's rats challenged strict behaviorism: learning can occur WITHOUT immediate reinforcement (latent learning) and includes cognitive representations.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "oc-ent-7a", question: "On the AP Psych exam, a question about a child whining until a parent gives candy describes:", options: ["Positive punishment for the child", "Negative reinforcement FOR THE PARENT (whining stops when candy is given) and positive reinforcement FOR THE CHILD (candy)", "Extinction", "Shaping"], correctIndex: 1, explanation: "Many parent-child cycles involve mutual reinforcement: each party's behavior strengthens the other's.", partNumber: 7, partTitle: "AP Review" },
  { id: "oc-ent-7b", question: "Which AP-style claim is correct?", options: ["Punishment is generally the most effective behavior change", "Reinforcement (especially positive) tends to be more effective than punishment for shaping new behavior; punishment can suppress behavior temporarily but has side effects (fear, aggression, modeling)", "Schedules don't matter", "Operant and classical conditioning are identical"], correctIndex: 1, explanation: "Modern behavior analysis emphasizes positive reinforcement, with punishment used cautiously due to documented side effects.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
