/**
 * Entrance Quiz — Perception & Attention (AP Psychology)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-psych-entrance-quizzes-batch*.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "pa-ent-1a", question: "Perception involves:", options: ["Receptor activity only", "Top-down organization and INTERPRETATION of sensory data, shaped by prior knowledge and expectations", "Reflex actions", "Storage in memory"], correctIndex: 1, explanation: "Perception adds meaning to raw sensation, combining bottom-up data with top-down expectations (schemas, context).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "pa-ent-1b", question: "Bottom-up processing is driven by:", options: ["Expectations", "The sensory input itself — building from features upward", "Memories", "Schemas"], correctIndex: 1, explanation: "Bottom-up = data-driven. Top-down = concept-driven (using context, prior knowledge).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "pa-ent-2a", question: "Gestalt psychologists (Wertheimer ~1912) argued:", options: ["Perception is the sum of sensations", "'The whole is OTHER than the sum of its parts' — we organize stimuli using grouping principles", "Sensation requires no organization", "Only structuralism is correct"], correctIndex: 1, explanation: "Gestalt principles (proximity, similarity, continuity, closure, figure-ground) describe automatic perceptual organization.", partNumber: 2, partTitle: "Key Processes" },
  { id: "pa-ent-2b", question: "The figure-ground principle holds that we automatically:", options: ["See everything as one shape", "Separate a scene into a FIGURE (object) standing out against a BACKGROUND (e.g., Rubin's vase-faces)", "Cannot organize visual scenes", "Use only color cues"], correctIndex: 1, explanation: "Figure-ground (Rubin, 1915): even ambiguous figures force a perceptual choice between competing organizations.", partNumber: 2, partTitle: "Key Processes" },
  { id: "pa-ent-3a", question: "Binocular depth cues include:", options: ["Linear perspective", "Retinal disparity and convergence — requiring two eyes", "Texture gradient", "Interposition"], correctIndex: 1, explanation: "Binocular = two eyes (disparity = different image in each eye; convergence = eye angle for near objects). Monocular cues = perspective, interposition, texture, etc.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "pa-ent-3b", question: "Linear perspective (parallel lines converging in the distance) is a:", options: ["Binocular cue", "Monocular depth cue", "Vestibular cue", "Auditory cue"], correctIndex: 1, explanation: "Monocular cues (one eye sufficient): linear perspective, relative size, interposition, texture gradient, light/shadow, motion parallax.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "pa-ent-4a", question: "Phi phenomenon (Wertheimer 1912) — the illusion of motion from rapidly flashing stationary lights — demonstrates:", options: ["Perceptual constancy", "That perception ADDS information not present in the raw sensation (basis of motion pictures)", "Sensation = perception", "Color blindness"], correctIndex: 1, explanation: "Phi (and stroboscopic) movement underlies film/TV. Brain constructs continuous motion from discrete frames.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "pa-ent-4b", question: "Perceptual constancy means we perceive objects as:", options: ["Always changing", "Stable in size, shape, color, and brightness despite changes in retinal image (e.g., a door looks rectangular at any angle)", "Two-dimensional", "Random"], correctIndex: 1, explanation: "Without size/shape/color constancy, the world would seem chaotic as our viewpoint shifted.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "pa-ent-5a", question: "Selective attention is dramatically illustrated by Simons & Chabris (1999) 'invisible gorilla' study, in which:", options: ["All viewers noticed the gorilla", "About 50% of viewers counting basketball passes failed to notice a gorilla walking through — INATTENTIONAL BLINDNESS", "No gorilla was used", "Only children noticed"], correctIndex: 1, explanation: "Inattentional blindness: focused attention on one task makes unexpected stimuli invisible despite being in plain view.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "pa-ent-5b", question: "Cherry's (1953) cocktail-party effect demonstrates that:", options: ["We process all conversations equally", "We can selectively attend to ONE conversation among many but our name in the unattended channel still grabs attention", "We hear nothing in unattended channels", "Attention is unlimited"], correctIndex: 1, explanation: "Dichotic listening shows attention filters most unattended content but personally relevant signals (your name) break through.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "pa-ent-6a", question: "Change blindness (Rensink, Simons) refers to:", options: ["Inability to see motion", "Failure to notice large changes between two scenes when changes occur during a brief disruption", "Color blindness", "Permanent blindness"], correctIndex: 1, explanation: "Change blindness shows our visual world is far less detailed than it feels — we hold limited information across saccades.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "pa-ent-6b", question: "Top-down processing is illustrated by:", options: ["A reflex", "The McGurk effect (visual lip-reading alters what you HEAR) or context-driven word recognition", "Pure photoreceptor activity", "Pupil dilation"], correctIndex: 1, explanation: "Top-down example: hearing 'ba' but seeing lips say 'ga' produces the perception 'da' (McGurk & MacDonald, 1976).", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "pa-ent-7a", question: "On the AP Psych exam, a question describing a person not noticing a change to a computer-screen image during a flicker expects:", options: ["Inattentional blindness", "Change blindness", "Sensory adaptation", "Phi phenomenon"], correctIndex: 1, explanation: "Change blindness specifically refers to missing differences between two states separated by a disruption.", partNumber: 7, partTitle: "AP Review" },
  { id: "pa-ent-7b", question: "Which AP-style claim is correct?", options: ["Perception is purely bottom-up", "Perception combines bottom-up sensory data with top-down expectations, organized by Gestalt principles and limited by attention", "Attention is unlimited", "Sensation and perception are identical"], correctIndex: 1, explanation: "Modern view integrates Gestalt organization, top-down schemas, and selective attention as joint contributors to perception.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
