/**
 * Entrance Quiz — Prenatal & Childhood Development (AP Psychology)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-psych-entrance-quizzes-batch*.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "pcd-ent-1a", question: "The three prenatal stages, in order, are:", options: ["Fetal, embryonic, germinal", "Germinal (0-2 wk), embryonic (3-8 wk), fetal (9 wk-birth)", "Embryonic, germinal, fetal", "Fetal, germinal, embryonic"], correctIndex: 1, explanation: "Germinal: zygote to implantation. Embryonic: organ formation (most teratogen-vulnerable). Fetal: growth and refinement.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "pcd-ent-1b", question: "Teratogens are agents that:", options: ["Promote prenatal growth", "Cross the placenta and harm prenatal development (e.g., alcohol, certain drugs, viruses)", "Are always genetic", "Affect only adults"], correctIndex: 1, explanation: "Maternal alcohol use can cause Fetal Alcohol Syndrome (FAS): facial abnormalities, growth deficits, intellectual disability.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "pcd-ent-2a", question: "Newborn reflexes include:", options: ["Driving and reading", "Rooting (turning head toward cheek touch), sucking, grasping, Moro (startle) — present at birth, fade by ~6 months", "Walking and talking", "Algebra"], correctIndex: 1, explanation: "Reflexes provide adaptive value (rooting helps feeding) and assess neurological development. Persistence past expected age may signal problems.", partNumber: 2, partTitle: "Key Processes" },
  { id: "pcd-ent-2b", question: "Habituation studies show infants:", options: ["Cannot perceive at all", "Look LESS at familiar stimuli and MORE at novel ones — used to infer perceptual and cognitive abilities", "Are blind for 6 months", "Cannot distinguish faces"], correctIndex: 1, explanation: "Habituation paradigms reveal that even young infants discriminate phonemes, faces, and quantities.", partNumber: 2, partTitle: "Key Processes" },
  { id: "pcd-ent-3a", question: "Piaget's SENSORIMOTOR stage (birth - ~2 yr) is characterized by:", options: ["Abstract thinking", "Learning through senses and actions; achieving OBJECT PERMANENCE around 8 months", "Conservation", "Hypothetical reasoning"], correctIndex: 1, explanation: "Sensorimotor: infants build mental representations through action. Object permanence = knowing things exist when out of sight.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "pcd-ent-3b", question: "Piaget's PREOPERATIONAL stage (~2-7 yr) features:", options: ["Conservation mastery", "Egocentrism (3-Mountains Task), centration, lack of conservation; rapid language and pretend play", "Abstract reasoning", "Object permanence emerging"], correctIndex: 1, explanation: "Preoperational kids often fail conservation (taller glass = more water) and show egocentrism (assuming others see what they see).", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "pcd-ent-4a", question: "Vygotsky's 'Zone of Proximal Development' (ZPD) refers to:", options: ["What a child cannot do at all", "The gap between what a child can do alone and what they can do with SCAFFOLDING from a more capable partner", "Adult performance", "IQ score"], correctIndex: 1, explanation: "Vygotsky (1896-1934) emphasized social/cultural context: learning happens through guided participation in the ZPD.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "pcd-ent-4b", question: "Theory of Mind (typically achieved ~age 4-5) is the:", options: ["Ability to read", "Understanding that others have beliefs, desires, and perspectives DIFFERENT from one's own (false-belief / Sally-Anne tasks)", "IQ", "Memory span"], correctIndex: 1, explanation: "Wimmer & Perner (1983) Sally-Anne task. Delayed ToM is characteristic of autism (Baron-Cohen 1985).", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "pcd-ent-5a", question: "Harlow's monkey studies (1958) showed infant monkeys preferred:", options: ["Wire 'mothers' that fed them", "CLOTH 'mothers' even when wire mothers provided food — demonstrating contact comfort over feeding for attachment", "Neither mother", "Always real mothers"], correctIndex: 1, explanation: "Harlow's surrogate-mother experiments overturned 'cupboard love' theory; attachment is about comfort, not just feeding.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "pcd-ent-5b", question: "Mary Ainsworth's Strange Situation (1970) classifies infant attachment as:", options: ["Only one type", "Secure, insecure-avoidant, insecure-anxious/ambivalent (and later disorganized) — based on responses to mother's separation/return", "IQ-based", "Random"], correctIndex: 1, explanation: "About 60-70% of U.S. infants classified as securely attached; predicts later social-emotional outcomes.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "pcd-ent-6a", question: "Erik Erikson's first psychosocial stage (infancy) is:", options: ["Autonomy vs shame", "Trust vs Mistrust — caregiver responsiveness builds basic trust in the world", "Industry vs inferiority", "Identity vs role confusion"], correctIndex: 1, explanation: "Erikson's 8 stages span the lifespan; each stage has a developmental crisis whose resolution shapes later development.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "pcd-ent-6b", question: "Lawrence Kohlberg's moral development uses dilemmas (e.g., Heinz) to identify levels:", options: ["Pre-moral, moral, post-moral", "Preconventional (consequences), Conventional (rules/social order), Postconventional (universal principles)", "Only one level", "Ethics is innate"], correctIndex: 1, explanation: "Kohlberg's levels (built on Piaget) classify moral REASONING. Critiqued by Carol Gilligan (1982) for under-representing care/relational ethics.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "pcd-ent-7a", question: "On the AP Psych exam, a question describing a 4-year-old who insists pouring juice into a tall glass means 'more juice' tests:", options: ["Conservation failure (preoperational stage)", "Object permanence", "Abstract reasoning", "Theory of mind"], correctIndex: 0, explanation: "Conservation = understanding quantity stays the same despite shape changes. Mastered ~age 7 (concrete operational).", partNumber: 7, partTitle: "AP Review" },
  { id: "pcd-ent-7b", question: "Which AP-style claim is correct?", options: ["Development is purely genetic", "Development reflects continuous interaction of biological maturation with experience; modern critics see Piaget's stages as more gradual and culturally variable than originally proposed", "Vygotsky rejected social influence", "Attachment quality has no later effects"], correctIndex: 1, explanation: "Modern developmental psychology integrates Piaget, Vygotsky, attachment theory, and biopsychosocial influences.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
