/**
 * Entrance Quiz — Social Influence & Conformity (AP Psychology)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-psych-entrance-quizzes-batch*.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "sic-ent-1a", question: "Solomon Asch's line-judgment experiments (1951) found that participants conformed to the wrong group answer about:", options: ["1% of trials", "About 37% of trials on average; ~75% conformed at least once", "100% always", "Never"], correctIndex: 1, explanation: "Asch demonstrated normative social influence even on perceptually obvious tasks. Conformity dropped sharply with one dissenting ally.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "sic-ent-1b", question: "Asch showed conformity DECREASED when:", options: ["The group was unanimous", "Any single ally also dissented from the majority", "Group size grew past 30", "Participants were anonymous to themselves"], correctIndex: 1, explanation: "Even one ally dramatically reduced conformity, suggesting social support breaks the unanimity pressure.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "sic-ent-2a", question: "Sherif's autokinetic effect study (1935) demonstrated:", options: ["Normative conformity", "INFORMATIONAL social influence — in an ambiguous situation, individuals' estimates converged on a group norm", "Obedience", "Bystander effect"], correctIndex: 1, explanation: "Sherif used a stationary point of light in darkness (apparent motion). Norms persisted when participants were retested alone, even a year later.", partNumber: 2, partTitle: "Key Processes" },
  { id: "sic-ent-2b", question: "Stanley Milgram's obedience studies (1961-63) found that approximately ____ of participants delivered the maximum 450-volt shock:", options: ["1%", "About 65% in the baseline condition", "100%", "10%"], correctIndex: 1, explanation: "Milgram's findings shocked psychology by showing ordinary adults would obey legitimate authority to apparently lethal levels.", partNumber: 2, partTitle: "Key Processes" },
  { id: "sic-ent-3a", question: "Milgram's obedience DECREASED when:", options: ["Authority wore a lab coat", "The experimenter was distant, the authority's legitimacy was undermined, OR the participant saw a peer disobey", "The victim was unseen", "The shock was real"], correctIndex: 1, explanation: "Proximity to victim, distance from authority, location prestige, and presence of disobedient models all reduced obedience.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "sic-ent-3b", question: "Zimbardo's Stanford Prison Experiment (1971) is now:", options: ["Considered a model study", "Heavily critiqued for methodology, demand characteristics, and ethics — Zimbardo coached guards; recent reanalyses (Le Texier 2019; Texier-Reicher) challenge the 'situational power' interpretation", "Required reading uncritically", "Replicated successfully"], correctIndex: 1, explanation: "Modern reappraisal: SPE is more demonstration than experiment; AP Psych still teaches it but with important caveats.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "sic-ent-4a", question: "INFORMATIONAL social influence (vs normative) is conforming because we believe the group:", options: ["Will reward us", "Has accurate information when we are uncertain", "Is the same as us", "Will punish us"], correctIndex: 1, explanation: "Informational influence drives genuine attitude change; normative influence drives public compliance to gain acceptance.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "sic-ent-4b", question: "FOOT-IN-THE-DOOR (Freedman & Fraser 1966) is a compliance technique that:", options: ["Asks the big request first", "Asks a small request first; once granted, larger requests are more likely to be granted", "Uses force", "Uses authority"], correctIndex: 1, explanation: "Foot-in-the-door exploits commitment/consistency. Door-in-the-face does the opposite (large then reasonable).", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "sic-ent-5a", question: "The BYSTANDER effect (Latané & Darley 1968) refers to:", options: ["Faster help with more bystanders", "REDUCED helping when more bystanders are present, due to diffusion of responsibility and pluralistic ignorance", "Random helping", "Helping only strangers"], correctIndex: 1, explanation: "Triggered by 1964 Kitty Genovese case (later journalism revised many details). The lab effect itself is robust.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "sic-ent-5b", question: "Latané & Darley's smoke-filled-room study found participants reported the smoke:", options: ["Faster when alone vs in a group", "More slowly when other (passive) bystanders were present — pluralistic ignorance", "At the same rate", "Only with female confederates"], correctIndex: 1, explanation: "When others remained calm, participants suppressed their own concern, illustrating pluralistic ignorance.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "sic-ent-6a", question: "Social FACILITATION (Triplett 1898; Zajonc 1965) refers to:", options: ["Worse performance under arousal", "Improved performance on WELL-LEARNED/simple tasks but IMPAIRED performance on novel/complex tasks when others are present (arousal × dominant response)", "Identical performance", "No effect of audience"], correctIndex: 1, explanation: "Zajonc explained mixed early results by tying audience effects to dominant-response strength.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "sic-ent-6b", question: "Social LOAFING (Latané, Williams, Harkins 1979) is the tendency to:", options: ["Work harder in groups", "Exert LESS effort in groups when individual contributions are not identifiable", "Work alone always", "Avoid groups"], correctIndex: 1, explanation: "Social loafing is reduced when individual performance is monitored, the task is engaging, or group identification is high.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "sic-ent-7a", question: "On the AP Psych exam, a question about an employee going along with a coworker majority on an obviously incorrect answer to avoid awkwardness tests:", options: ["Informational social influence", "Normative social influence (Asch-style conformity)", "Obedience", "Bystander effect"], correctIndex: 1, explanation: "Going along to avoid disapproval, knowing the answer is wrong, is normative influence.", partNumber: 7, partTitle: "AP Review" },
  { id: "sic-ent-7b", question: "Which AP-style claim is correct?", options: ["Social influence is rare and weak", "Classic social psychology (Asch, Milgram, Latané/Darley) shows that ordinary situational forces — conformity, obedience, diffusion of responsibility — powerfully shape behavior, often more than personality traits", "Personality alone explains behavior", "Bystander effect was disconfirmed"], correctIndex: 1, explanation: "AP Psych emphasizes the 'power of the situation' demonstrated by classic social-psychological research.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
