/**
 * Entrance Quiz — Thinking & Problem Solving (AP Psychology)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-psych-entrance-quizzes-batch*.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "tps-ent-1a", question: "A CONCEPT is:", options: ["A specific event", "A mental grouping of similar objects, events, or ideas (e.g., 'furniture')", "An emotion", "A neuron"], correctIndex: 1, explanation: "Concepts let us treat new instances by their category. Hierarchies (basic, superordinate, subordinate) organize them (Rosch).", partNumber: 1, partTitle: "Core Concepts" },
  { id: "tps-ent-1b", question: "Eleanor Rosch's PROTOTYPE theory holds we judge category membership by:", options: ["Strict definitions", "Similarity to a 'best example' or PROTOTYPE (a robin is a more typical bird than a penguin)", "Random sampling", "Alphabetical order"], correctIndex: 1, explanation: "Rosch (1975) showed graded category membership and prototypicality effects in reaction times and ratings.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "tps-ent-2a", question: "An ALGORITHM is:", options: ["A guess", "A step-by-step procedure that GUARANTEES a solution (e.g., long division)", "A bias", "A heuristic"], correctIndex: 1, explanation: "Algorithms are systematic but can be slow. Heuristics trade certainty for speed.", partNumber: 2, partTitle: "Key Processes" },
  { id: "tps-ent-2b", question: "A HEURISTIC is:", options: ["A guaranteed solution", "A mental SHORTCUT (rule of thumb) that often works but can fail", "A random guess", "A reflex"], correctIndex: 1, explanation: "Heuristics enable fast judgments under uncertainty. Tversky & Kahneman documented systematic biases that arise from them.", partNumber: 2, partTitle: "Key Processes" },
  { id: "tps-ent-3a", question: "The AVAILABILITY heuristic (Tversky & Kahneman 1973) is judging probability by:", options: ["Statistics", "How EASILY examples come to mind (vivid plane crashes inflate fear of flying vs driving)", "Logical analysis", "Survey data"], correctIndex: 1, explanation: "Availability explains many risk perception errors: rare-but-vivid events feel more probable than they are.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "tps-ent-3b", question: "The REPRESENTATIVENESS heuristic is judging probability by:", options: ["Available examples", "Similarity to a STEREOTYPE/prototype (Linda problem: more people judge 'feminist bank teller' more probable than 'bank teller')", "Base rates", "Probability theory"], correctIndex: 1, explanation: "Tversky & Kahneman 'Linda problem' demonstrates conjunction fallacy — overlooking that P(A∩B) ≤ P(A).", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "tps-ent-4a", question: "CONFIRMATION bias is the tendency to:", options: ["Seek disconfirming evidence", "SEEK and remember information that CONFIRMS one's existing beliefs while underweighting disconfirming evidence", "Be perfectly objective", "Reverse beliefs"], correctIndex: 1, explanation: "Confirmation bias affects political reasoning, scientific theorizing, and everyday judgment. Identified by Wason (1960) selection task.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "tps-ent-4b", question: "MENTAL SET (Luchins water-jar problem, 1942) is:", options: ["Random thinking", "Tendency to use a previously SUCCESSFUL approach even when a simpler one is available", "Always optimal", "A bias-free strategy"], correctIndex: 1, explanation: "Luchins showed people kept using a complex 3-jar formula even when a simple one-step solution was available.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "tps-ent-5a", question: "FUNCTIONAL FIXEDNESS is the tendency to:", options: ["Be flexible", "See objects only in their USUAL function (failing to use a pliers as a pendulum weight in Maier's two-string problem, 1931)", "Use objects creatively", "Solve novel problems quickly"], correctIndex: 1, explanation: "Functional fixedness blocks creative problem solving when familiar uses dominate. Reduced by reframing the object generically.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "tps-ent-5b", question: "FRAMING effects (Tversky & Kahneman 1981) show choices change when options are described as:", options: ["Identical numbers", "GAINS vs LOSSES (e.g., '90% survival rate' vs '10% mortality') — even though equivalent, framing alters preferences", "Equally desirable", "Random"], correctIndex: 1, explanation: "Prospect theory: people are loss-averse, so loss-framed options are weighted differently than mathematically equivalent gain-framed options.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "tps-ent-6a", question: "The ANCHORING effect is:", options: ["Ignoring reference points", "RELYING too heavily on the first piece of information ('anchor') when making estimates (used in negotiations, sale prices)", "Random estimates", "Pure logic"], correctIndex: 1, explanation: "Even arbitrary anchors (random numbers spun on a wheel) influence subsequent quantitative estimates.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "tps-ent-6b", question: "Belief PERSEVERANCE refers to:", options: ["Updating beliefs rationally", "Clinging to initial beliefs even after evidence supporting them is discredited", "Always changing beliefs", "Bayesian reasoning"], correctIndex: 1, explanation: "Ross, Lepper, & Hubbard (1975): beliefs persist even when their original evidentiary basis is removed.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "tps-ent-7a", question: "On the AP Psych exam, a question about overestimating shark attack risk after seeing news coverage tests:", options: ["Confirmation bias", "Availability heuristic", "Anchoring", "Functional fixedness"], correctIndex: 1, explanation: "Vivid, recent, emotional examples come easily to mind, distorting perceived probability — the availability heuristic.", partNumber: 7, partTitle: "AP Review" },
  { id: "tps-ent-7b", question: "Which AP-style claim is correct?", options: ["Human reasoning is fully rational", "Human reasoning relies on heuristics that are usually adaptive but produce systematic biases (Tversky-Kahneman, Nobel 2002 to Kahneman)", "Heuristics are always wrong", "Algorithms are always slower"], correctIndex: 1, explanation: "Dual-process accounts (Kahneman 'Thinking Fast and Slow', 2011) integrate fast/heuristic and slow/deliberative thinking.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
