/**
 * Entrance Quiz — Treatment & Therapy (AP Psychology)
 * 14 questions · 7 parts (2 per part)
 * AUTO-GENERATED by scripts/write-psych-entrance-quizzes-batch*.py
 */

import type { EntranceQuizQuestion } from './moles-molar-mass'

const questions: EntranceQuizQuestion[] = [
  { id: "tt-ent-1a", question: "Psychoanalysis (Freud) uses techniques such as:", options: ["Token economies", "FREE ASSOCIATION, dream analysis, interpretation of resistance and TRANSFERENCE", "Cognitive restructuring", "Exposure therapy"], correctIndex: 1, explanation: "Modern psychodynamic therapy is briefer but retains attention to unconscious processes and the therapeutic relationship.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "tt-ent-1b", question: "Carl Rogers's CLIENT-CENTERED therapy emphasizes:", options: ["Confrontation", "Genuineness, empathic understanding, and UNCONDITIONAL POSITIVE REGARD — letting the client direct the work", "Operant conditioning", "Brain stimulation"], correctIndex: 1, explanation: "Rogers (1951) reframed the relationship as 'client' (not patient) and 'therapist as facilitator' — foundational for humanistic therapy.", partNumber: 1, partTitle: "Core Concepts" },
  { id: "tt-ent-2a", question: "BEHAVIOR therapies apply learning principles. SYSTEMATIC DESENSITIZATION (Wolpe 1958) treats phobias by:", options: ["Random reinforcement", "Pairing graduated exposure to the feared CS with relaxation (counter-conditioning)", "Free association", "Hypnosis"], correctIndex: 1, explanation: "Systematic desensitization is highly effective for specific phobias; modern variants use in-vivo and virtual-reality exposure.", partNumber: 2, partTitle: "Key Processes" },
  { id: "tt-ent-2b", question: "EXPOSURE-and-Response Prevention (ERP) is the gold standard for:", options: ["Schizophrenia", "Obsessive-Compulsive Disorder — exposing client to triggers WHILE preventing the compulsion until anxiety subsides", "Bipolar disorder", "Dementia"], correctIndex: 1, explanation: "Foa's ERP shows large effect sizes for OCD, often equaling or exceeding SSRIs.", partNumber: 2, partTitle: "Key Processes" },
  { id: "tt-ent-3a", question: "AVERSION therapy pairs an unwanted behavior with:", options: ["A reward", "An UNPLEASANT stimulus (e.g., disulfiram for alcohol → nausea when drinking) — modest evidence base", "Free association", "ECT"], correctIndex: 1, explanation: "Aversion therapy has been controversial; effect often does not generalize beyond the conditioning context.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "tt-ent-3b", question: "Cognitive-Behavioral Therapy (CBT) combines:", options: ["Drugs and surgery", "Cognitive restructuring (changing distorted thoughts) AND behavioral techniques (exposure, behavioral activation)", "Hypnosis only", "Free association"], correctIndex: 1, explanation: "CBT (Beck, Ellis, Meichenbaum) is the most empirically supported psychotherapy across depression, anxiety, PTSD, OCD, and many other disorders.", partNumber: 3, partTitle: "Patterns & Examples" },
  { id: "tt-ent-4a", question: "Albert Ellis's RATIONAL EMOTIVE Behavior Therapy (REBT) targets:", options: ["Reflexes", "Irrational BELIEFS (the 'B' in his ABC model: Activating event → Belief → Consequence) — directly disputing them", "Hormones", "Memories only"], correctIndex: 1, explanation: "Ellis (1955) developed REBT before Beck's cognitive therapy. Both emphasize cognition's role in emotional disorder.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "tt-ent-4b", question: "DIALECTICAL Behavior Therapy (DBT, Linehan 1993) was developed for:", options: ["Schizophrenia", "Borderline Personality Disorder; combines CBT with mindfulness, emotion regulation, distress tolerance, and interpersonal skills", "Dementia", "Specific phobia"], correctIndex: 1, explanation: "DBT has the strongest evidence base for BPD and is also used for self-harm and chronic suicidality.", partNumber: 4, partTitle: "Connections & Interactions" },
  { id: "tt-ent-5a", question: "SSRIs (e.g., fluoxetine/Prozac, FDA-approved 1987) work by:", options: ["Blocking dopamine receptors", "Selectively inhibiting reuptake of SEROTONIN, increasing synaptic 5-HT", "Increasing GABA", "Stimulating ACh release"], correctIndex: 1, explanation: "SSRIs are first-line for MDD, anxiety, OCD; effect typically takes 2-6 weeks despite immediate biochemical change.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "tt-ent-5b", question: "Antipsychotic medications work primarily by:", options: ["Blocking serotonin only", "Blocking dopamine D2 receptors (typicals); atypicals also affect serotonin (5-HT2A)", "Releasing dopamine", "Suppressing acetylcholine"], correctIndex: 1, explanation: "Typical antipsychotics (chlorpromazine 1952, haloperidol) cause more extrapyramidal side effects; atypicals (clozapine, risperidone) reduce these but increase metabolic risk.", partNumber: 5, partTitle: "Change Over Time" },
  { id: "tt-ent-6a", question: "Electroconvulsive therapy (ECT) is most clearly effective for:", options: ["Mild anxiety", "SEVERE, treatment-resistant depression — rapid response, especially when suicide risk or psychotic features present; main side effect = transient memory loss", "Specific phobia", "Schizophrenia in remission"], correctIndex: 1, explanation: "Modern ECT (unilateral, brief-pulse, with anesthesia) is far safer than mid-20th-century practice and remains an important option.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "tt-ent-6b", question: "Lobotomy (Moniz 1936; popularized in U.S. by Freeman 1940s) is now:", options: ["Standard practice", "Largely abandoned as crude and harmful — replaced by medications and far more targeted neurosurgical procedures (deep brain stimulation, anterior cingulotomy in rare cases)", "Used routinely for depression", "Mandatory for schizophrenia"], correctIndex: 1, explanation: "Moniz received the 1949 Nobel Prize for prefrontal leucotomy — now seen as one of the most regrettable medical Nobels.", partNumber: 6, partTitle: "Problem-Solving Workshop" },
  { id: "tt-ent-7a", question: "On the AP Psych exam, a question about a clinician disputing a client's belief that 'one bad grade means I am a complete failure' tests:", options: ["Free association", "Cognitive therapy / cognitive restructuring (Beck, Ellis)", "Token economy", "Aversion therapy"], correctIndex: 1, explanation: "Identifying and challenging cognitive distortions (overgeneralization, all-or-nothing) is core to cognitive therapy.", partNumber: 7, partTitle: "AP Review" },
  { id: "tt-ent-7b", question: "Which AP-style claim is correct?", options: ["Therapy effectiveness depends only on technique", "Outcome research finds therapy is generally effective; common factors (therapeutic alliance, client expectations) account for substantial variance, with specific techniques (e.g., CBT for anxiety, DBT for BPD) showing additional disorder-specific benefits", "All therapies are equally effective for everything", "Therapy doesn't work"], correctIndex: 1, explanation: "Wampold's Common Factors model + evidence-based practice both supported. AP Psych emphasizes evidence-based treatment.", partNumber: 7, partTitle: "AP Review" }
]

export function generateEntranceQuiz(): EntranceQuizQuestion[] {
  return [...questions].sort(() => Math.random() - 0.5)
}

export function getEntranceQuizParts(): { partNumber: number; partTitle: string }[] {
  return [
    { partNumber: 1, partTitle: 'Core Concepts' },
    { partNumber: 2, partTitle: 'Key Processes' },
    { partNumber: 3, partTitle: 'Patterns & Examples' },
    { partNumber: 4, partTitle: 'Connections & Interactions' },
    { partNumber: 5, partTitle: 'Change Over Time' },
    { partNumber: 6, partTitle: 'Problem-Solving Workshop' },
    { partNumber: 7, partTitle: 'AP Review' }
  ]
}
