/**
 * AP African American Studies — FRQ Practice Question Pool
 * AUTO-GENERATED by scripts/write-aas-frqs.py
 *
 * Format mirrors College Board AP AAS exam: long source-based prompts (~25 min, 7 pts)
 * and shorter source/data prompts (~12 min, 4 pts), each with 4 parts (a)–(d).
 */

export interface FRQRubricItem {
  points: number
  description: string
  keywords: string[]
}

export interface FRQPart {
  label: string
  prompt: string
  maxPoints: number
  rubric: FRQRubricItem[]
  sampleAnswer: string
}

export interface AASFRQ {
  id: string
  type: 'long' | 'short'
  unit: number
  title: string
  prompt: string
  parts: FRQPart[]
  totalPoints: number
  timeRecommendation: string
  calculatorAllowed: boolean
}

const longFRQs: AASFRQ[] = [
  {
    id: "aas-long-1",
    type: 'long' as const,
    unit: 1,
    title: "African Kingdoms & the Origins of the Diaspora",
    prompt: "Use the historical context of West and Central African societies before 1500 to address the prompt below. Reference specific figures, places, and primary sources.",
    parts: [
      {
        label: "(a)",
        prompt: "Identify ONE specific feature of the Mali Empire under Mansa Musa (r. 1312–1337) that demonstrates the wealth, scholarship, or political organization of West African states before European contact.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Identifies a concrete, attested feature (e.g., 1324 hajj, Sankore Madrasa, Djinguereber Mosque, gold–salt trade)", keywords: ["Mansa Musa", "1324", "hajj", "Mali", "Timbuktu", "Sankore", "Djinguereber", "gold", "salt", "Catalan Atlas"] },
          { points: 1, description: "Explains why this feature signals state capacity, scholarship, or commercial integration", keywords: ["because", "demonstrates", "shows", "evidence", "trans-Saharan", "Islamic", "scholarship", "centralized"] }
        ],
        sampleAnswer: "Mansa Musa's 1324 hajj distributed so much gold that, according to al-Umari, prices in Cairo were depressed for over a decade. This demonstrates both Mali's centralized control over the trans-Saharan gold-salt trade and its integration into the wider Islamic world, as confirmed by Mansa Musa's appearance on the 1375 Catalan Atlas.",
      },
      {
        label: "(b)",
        prompt: "Using ONE specific primary source from the unit (e.g., Ibn Battuta's Rihla, the Epic of Sundiata, or Afonso I's 1526 letter), explain what it reveals about African political or religious life before the height of the Atlantic slave trade.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Names a specific primary source by author/title and dates it to within the period", keywords: ["Ibn Battuta", "Rihla", "1352", "1354", "Sundiata", "Afonso", "Kongo", "1526", "al-Sa'di", "Tarikh"] },
          { points: 1, description: "Uses the source to support a claim about African society (sourcing point: HAPP)", keywords: ["audience", "purpose", "perspective", "according to", "argues", "demonstrates", "reveals"] }
        ],
        sampleAnswer: "Ibn Battuta's Rihla (1352–1354) describes Mansa Suleyman's court protocol, mandatory mosque attendance on Fridays, and the safety of trans-Saharan trade routes. Because Ibn Battuta was a Maliki jurist writing for an Islamic audience, his praise of Mali's adherence to Islamic law is especially credible as evidence that Mali was deeply integrated into the Dar al-Islam.",
      },
      {
        label: "(c)",
        prompt: "Explain ONE way the political and economic structures of African kingdoms shaped — or were reshaped by — the early transatlantic slave trade between roughly 1450 and 1600.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Identifies a specific causal link (e.g., Kongolese diplomacy, intensification of warfare, Portuguese factor system at Elmina)", keywords: ["Kongo", "Afonso", "Portugal", "Elmina", "Luanda", "warfare", "captives", "asiento", "factor"] },
          { points: 1, description: "Explains the mechanism (continuity OR change) using historical reasoning", keywords: ["because", "led to", "destabilized", "intensified", "transformed", "feedback", "consequence"] }
        ],
        sampleAnswer: "King Afonso I of Kongo's 1526 letter to João III of Portugal protested that Portuguese slavers were depopulating his kingdom by bypassing royal monopolies and seizing Kongolese subjects. This shows that Atlantic demand restructured the political authority of even powerful African states, turning regulated trade into political destabilization within a single generation.",
      },
      {
        label: "(d)",
        prompt: "Evaluate the long-term significance of pre-1500 African civilizations for understanding the African diaspora in the Americas.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Provides a defensible evaluative claim tied to evidence (cultural retention, religion, kinship, language, political memory)", keywords: ["diaspora", "retention", "creolization", "Yoruba", "Vodou", "Candomble", "Santeria", "kinship", "memory", "long-term"] }
        ],
        sampleAnswer: "Pre-1500 African societies remain significant because their religious, linguistic, and political traditions traveled with enslaved Africans to the Americas. Yoruba religion structured Santeria, Candomble, and Lucumi, while political memory of Kongo and Akan polities shaped maroon resistance from Palmares to Jamaica — meaning the diaspora is incomprehensible without African history before 1500.",
      }
    ],
    totalPoints: 7,
    timeRecommendation: "~25 minutes",
    calculatorAllowed: false,
  },
  {
    id: "aas-long-2",
    type: 'long' as const,
    unit: 2,
    title: "From Reconstruction to Jim Crow: Continuity and Change",
    prompt: "Analyze how African Americans pursued political and economic freedom between 1865 and 1900, and how white supremacist responses reshaped that pursuit. Use specific figures, legislation, and primary sources.",
    parts: [
      {
        label: "(a)",
        prompt: "Identify ONE specific provision of the Reconstruction Amendments (13th, 14th, 15th) and explain its significance for Black political life.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Names a specific clause/provision and dates it (1865, 1868, 1870)", keywords: ["13th", "14th", "15th", "1865", "1868", "1870", "abolition", "citizenship", "equal protection", "due process", "suffrage"] },
          { points: 1, description: "Explains the significance for Black voters, officeholders, or schools", keywords: ["birthright", "Black voters", "officeholders", "Hiram Revels", "Robert Smalls", "Freedmen's Bureau", "schools"] }
        ],
        sampleAnswer: "The 14th Amendment (1868) defined birthright citizenship and required equal protection of the laws — overturning Dred Scott (1857) and providing the constitutional basis on which Black voters elected Hiram Revels (1870) and Robert Smalls (1875) to Congress during Reconstruction.",
      },
      {
        label: "(b)",
        prompt: "Use ONE primary source from the period (e.g., Ida B. Wells's *Southern Horrors* (1892), Booker T. Washington's 1895 Atlanta Compromise speech, or W. E. B. Du Bois's *Souls of Black Folk* (1903)) to support a claim about Black strategy after 1877.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Names a specific primary source and dates it", keywords: ["Wells", "Southern Horrors", "1892", "Red Record", "1895", "Atlanta Compromise", "Du Bois", "Souls of Black Folk", "1903"] },
          { points: 1, description: "Uses HAPP (historical situation, audience, purpose, point of view) to support a claim", keywords: ["audience", "purpose", "perspective", "northern readers", "Black uplift", "double-consciousness", "color line"] }
        ],
        sampleAnswer: "Ida B. Wells's *Southern Horrors* (1892) was written for a northern white audience whose silence enabled lynching. Wells's statistical method — naming victims, dates, and accusations — was designed to refute the southern claim that lynchings were responses to rape, demonstrating that lynching was instead an instrument of political and economic terror.",
      },
      {
        label: "(c)",
        prompt: "Explain ONE specific mechanism by which white-supremacist regimes dismantled Black political and economic gains between 1877 and 1900.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Names a specific mechanism (poll tax, literacy test, grandfather clause, white primary, convict leasing, Wilmington 1898, *Plessy* 1896, Mississippi Plan 1890)", keywords: ["poll tax", "literacy test", "grandfather clause", "white primary", "convict leasing", "Wilmington", "1898", "Plessy", "1896", "Mississippi Plan", "1890"] },
          { points: 1, description: "Explains how the mechanism operated and its quantitative or political effect", keywords: ["disfranchisement", "registered voters", "fell from", "labor", "removed from office", "coup"] }
        ],
        sampleAnswer: "Mississippi's 1890 constitutional convention introduced poll taxes and literacy tests that, combined with white-only Democratic primaries, reduced Black voter registration in the state from over 130,000 in 1890 to fewer than 9,000 by 1892 — a model copied by every former Confederate state by 1908.",
      },
      {
        label: "(d)",
        prompt: "Evaluate which had the larger long-term effect on Black life by 1900: the gains of Reconstruction or the rise of Jim Crow. Defend your position with evidence.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Takes a defensible position supported with two specific pieces of evidence", keywords: ["because", "Plessy", "1896", "AME", "HBCUs", "NAACP", "1909", "Wells", "Du Bois", "long-term"] }
        ],
        sampleAnswer: "Although *Plessy* (1896) and disfranchisement reversed most political gains, Reconstruction's institutional legacies — the 14th Amendment, HBCUs founded between 1865 and 1881, and the AME Church's expansion — provided the legal and organizational platform that NAACP litigation (founded 1909) eventually used to dismantle Jim Crow, so Reconstruction's long-term effect was the greater of the two.",
      }
    ],
    totalPoints: 7,
    timeRecommendation: "~25 minutes",
    calculatorAllowed: false,
  },
  {
    id: "aas-long-3",
    type: 'long' as const,
    unit: 3,
    title: "The Civil Rights Movement and the Turn to Black Power",
    prompt: "Compare the strategies, demands, and outcomes of the civil rights movement (1954–1965) and the Black Power movement (1965–1975). Use specific figures, organizations, events, and primary sources.",
    parts: [
      {
        label: "(a)",
        prompt: "Identify TWO specific civil rights organizations or campaigns between 1954 and 1965 and briefly describe what each demanded.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Names a first organization or campaign (NAACP LDF, SCLC, SNCC, CORE, MFDP, Montgomery Bus Boycott, Birmingham 1963, Selma 1965)", keywords: ["NAACP", "SCLC", "SNCC", "CORE", "MFDP", "Montgomery", "1955", "Birmingham", "1963", "Selma", "1965"] },
          { points: 1, description: "Names a second and explains its specific demand (desegregation, voting rights, federal enforcement)", keywords: ["voting rights", "desegregation", "Civil Rights Act", "1964", "Voting Rights Act", "Fannie Lou Hamer", "MLK", "Bayard Rustin"] }
        ],
        sampleAnswer: "The NAACP Legal Defense Fund litigated *Brown v. Board* (1954) to demand desegregation of public schools, while SNCC's 1964 Mississippi Freedom Summer mobilized 1,000 volunteers to register Black voters and seat the Mississippi Freedom Democratic Party at the Democratic National Convention.",
      },
      {
        label: "(b)",
        prompt: "Use ONE primary source — e.g., King's 'Letter from Birmingham Jail' (1963), Fannie Lou Hamer's 1964 DNC testimony, or the Black Panther Party Ten-Point Program (1966) — to support an interpretation of movement strategy.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Names the source, dates it, and identifies the author's purpose", keywords: ["Letter from Birmingham Jail", "1963", "Hamer", "1964", "DNC", "Ten-Point Program", "1966", "Carmichael"] },
          { points: 1, description: "Uses HAPP to support a claim about strategy or audience", keywords: ["audience", "white moderate", "national television", "self-defense", "community control", "purpose"] }
        ],
        sampleAnswer: "King's 'Letter from Birmingham Jail' (1963) was addressed to white clergy who had urged him to wait, but its real audience was the national press. By citing Aquinas, Niebuhr, and the prophets, King reframed direct action as conservative — a defense of moral law against unjust statutes — to win over moderate northern opinion.",
      },
      {
        label: "(c)",
        prompt: "Explain ONE specific reason that some activists turned from integrationist civil rights toward Black Power between 1965 and 1968.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Identifies a specific cause (Watts 1965, Selma backlash, frustration with northern de facto segregation, Carmichael's 1966 Greenwood speech, assassinations of Malcolm X and MLK)", keywords: ["Watts", "1965", "Carmichael", "Greenwood", "1966", "Malcolm X", "1965", "MLK", "1968", "northern", "de facto"] },
          { points: 1, description: "Explains the mechanism — why this cause produced a strategic shift", keywords: ["because", "frustration", "limits of", "self-determination", "community control", "self-defense"] }
        ],
        sampleAnswer: "After the August 1965 Watts uprising and the murder of Jonathan Daniels in Alabama, Stokely Carmichael's June 1966 Greenwood, MS rally rejected nonviolent integrationism. Carmichael argued that without economic power and self-defense, federal voting rights legislation alone could not address the de facto segregation, police violence, and unemployment that defined northern Black life.",
      },
      {
        label: "(d)",
        prompt: "Evaluate ONE specific continuity OR change between the civil rights and Black Power movements that historians should emphasize.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Takes a defensible position with two specific pieces of evidence", keywords: ["continuity", "change", "Free Breakfast", "Ten-Point Program", "Ella Baker", "Diane Nash", "Combahee", "intersectionality", "abolition"] }
        ],
        sampleAnswer: "An important continuity is the role of Black women organizers: Ella Baker's bottom-up philosophy in SNCC carried directly into the Combahee River Collective Statement (1977) and the Movement for Black Lives (2013), suggesting that intersectional Black feminist organizing — not the King–Carmichael split — provides the through-line of late-20th-century Black politics.",
      }
    ],
    totalPoints: 7,
    timeRecommendation: "~25 minutes",
    calculatorAllowed: false,
  },
  {
    id: "aas-long-4",
    type: 'long' as const,
    unit: 4,
    title: "Mass Incarceration, Movement for Black Lives, and the Long 21st Century",
    prompt: "Analyze how late-20th-century policies and 21st-century movements have continued — or transformed — earlier struggles for Black freedom in the United States. Use specific evidence.",
    parts: [
      {
        label: "(a)",
        prompt: "Identify ONE specific late-20th-century policy that contributed to the rise of mass incarceration after 1980 and describe its racially disparate effect.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Names a specific policy (1986 Anti-Drug Abuse Act, 1994 Crime Bill, mandatory minimums, three-strikes laws)", keywords: ["1986", "Anti-Drug Abuse", "100:1", "crack", "powder", "1994", "Crime Bill", "three strikes", "mandatory minimum"] },
          { points: 1, description: "Cites a quantitative or proportional disparity", keywords: ["5 to 6 times", "incarceration rate", "Black men", "rose from 300,000", "2.3 million", "Michelle Alexander", "New Jim Crow"] }
        ],
        sampleAnswer: "The 1986 Anti-Drug Abuse Act's 100:1 sentencing disparity between crack and powder cocaine helped raise the U.S. prison population from about 300,000 in 1972 to roughly 2.3 million by 2008, with Black men incarcerated at five to six times the rate of white men — what Michelle Alexander calls *The New Jim Crow*.",
      },
      {
        label: "(b)",
        prompt: "Use ONE primary source from the contemporary period (e.g., Ta-Nehisi Coates's 'The Case for Reparations' (2014), the 2013 BLM founding statement, or Hannah-Jones's *1619 Project* (2019)) to support an interpretation of contemporary Black political thought.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Names the source, author, and date", keywords: ["Coates", "Case for Reparations", "2014", "BLM", "2013", "Cullors", "Garza", "Tometi", "Hannah-Jones", "1619 Project", "2019"] },
          { points: 1, description: "Uses HAPP to support a claim", keywords: ["redlining", "HOLC", "intersectionality", "queer", "founding", "audience", "policy"] }
        ],
        sampleAnswer: "Coates's 'The Case for Reparations' (Atlantic, 2014) was written for a national, largely white liberal audience and grounded its argument not in slavery alone but in 1930s-era HOLC redlining maps and FHA discrimination. By documenting 20th-century federal complicity, Coates moved reparations from a moral abstraction to a legal claim about specific, recoverable theft.",
      },
      {
        label: "(c)",
        prompt: "Explain ONE specific way the Movement for Black Lives (founded 2013) extends OR departs from the civil rights and Black Power traditions.",
        maxPoints: 2,
        rubric: [
          { points: 1, description: "Names a specific extension or departure (decentralization, intersectionality, abolitionism, queer leadership)", keywords: ["decentralized", "intersectionality", "Crenshaw", "Combahee", "abolition", "police violence", "queer", "Black women"] },
          { points: 1, description: "Explains the mechanism with reference to earlier movements", keywords: ["unlike", "extends", "echoes", "Ella Baker", "Davis", "King", "SCLC", "Panthers"] }
        ],
        sampleAnswer: "M4BL extends Ella Baker's SNCC tradition of decentralized, group-centered leadership while explicitly centering Black queer and women's experience — a structural departure from the male, clerical leadership of SCLC. Founders Cullors, Garza, and Tometi drew directly on the Combahee River Collective Statement (1977) to make intersectional analysis foundational rather than ancillary.",
      },
      {
        label: "(d)",
        prompt: "Evaluate the claim that the period 2008–2020 represents EITHER a culmination of earlier civil rights gains OR the start of a distinctly new phase in Black political history. Defend your position.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Takes a defensible position with two specific pieces of evidence", keywords: ["Obama", "2008", "Shelby County", "2013", "Ferguson", "2014", "Floyd", "2020", "BLM", "long-term"] }
        ],
        sampleAnswer: "The period is best read as a new phase: although Obama's 2008 election fulfilled a long civil-rights aspiration, *Shelby County v. Holder* (2013) gutted Voting Rights Act preclearance the same year BLM was founded, and the 2020 George Floyd protests — perhaps the largest in U.S. history — addressed police violence and abolition rather than legal segregation, framing a distinctly post-civil-rights agenda.",
      }
    ],
    totalPoints: 7,
    timeRecommendation: "~25 minutes",
    calculatorAllowed: false,
  }
]

const shortFRQs: AASFRQ[] = [
  {
    id: "aas-short-1",
    type: 'short' as const,
    unit: 1,
    title: "Source: Olaudah Equiano's Narrative",
    prompt: "The following passage is from Olaudah Equiano's *The Interesting Narrative of the Life of Olaudah Equiano* (1789), describing the Middle Passage.\n\n> 'The closeness of the place, and the heat of the climate, added to the number in the ship, which was so crowded that each had scarcely room to turn himself, almost suffocated us. … The shrieks of the women, and the groans of the dying, rendered the whole a scene of horror almost inconceivable.'",
    parts: [
      {
        label: "(a)",
        prompt: "Identify ONE specific historical context (1450–1808) that helps explain the conditions Equiano describes.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Names a specific context (Middle Passage, ~12.5M embarked, ~15% mortality, tight-pack stowage, asiento system, Royal African Company)", keywords: ["Middle Passage", "12.5 million", "15%", "mortality", "tight pack", "asiento", "Royal African Company", "Bight of Biafra"] }
        ],
        sampleAnswer: "Equiano was captured in the Bight of Biafra around 1756, during the peak decades of an Atlantic slave trade that embarked roughly 12.5 million Africans, with average shipboard mortality of about 15%.",
      },
      {
        label: "(b)",
        prompt: "Identify the audience and purpose of Equiano's *Narrative* (HAPP).",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Identifies British abolitionist audience and persuasive/political purpose", keywords: ["British", "abolition", "1789", "Parliament", "Sons of Africa", "audience", "purpose", "persuade"] }
        ],
        sampleAnswer: "Equiano wrote for a British reading public during the parliamentary abolition campaign of the late 1780s, aiming to persuade Christian readers — including MPs voting on the trade — that the Atlantic system was both un-Christian and unsustainable.",
      },
      {
        label: "(c)",
        prompt: "Explain ONE specific way Equiano's account influenced abolitionist politics in Britain.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Identifies a specific influence (best-seller; cited by Wilberforce/Clarkson; informed 1807 Abolition Act)", keywords: ["Wilberforce", "Clarkson", "1807", "Abolition Act", "Sons of Africa", "best seller", "nine editions"] }
        ],
        sampleAnswer: "The *Narrative* went through nine editions in five years, was cited by Thomas Clarkson in evidence to the Privy Council, and helped build the public pressure that produced the 1807 British Abolition of the Slave Trade Act.",
      },
      {
        label: "(d)",
        prompt: "Identify ONE limitation of using Equiano's *Narrative* as evidence about the Middle Passage.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Identifies a valid limitation (single perspective; written 30+ years after events; recent scholarship questioning birthplace)", keywords: ["single", "perspective", "memory", "decades later", "Carretta", "South Carolina", "birthplace", "limit"] }
        ],
        sampleAnswer: "Recent scholarship (notably by Vincent Carretta) has raised questions about whether Equiano was actually born in Africa or in colonial South Carolina, which complicates — though does not negate — the use of his narrative as direct testimony of the Middle Passage.",
      }
    ],
    totalPoints: 4,
    timeRecommendation: "~12 minutes",
    calculatorAllowed: false,
  },
  {
    id: "aas-short-2",
    type: 'short' as const,
    unit: 2,
    title: "Source: Frederick Douglass, 'What to the Slave is the Fourth of July?' (1852)",
    prompt: "The following passage is from Frederick Douglass's July 5, 1852 address in Rochester, New York.\n\n> 'What, to the American slave, is your 4th of July? I answer; a day that reveals to him, more than all other days in the year, the gross injustice and cruelty to which he is the constant victim. To him, your celebration is a sham; your boasted liberty, an unholy license …'",
    parts: [
      {
        label: "(a)",
        prompt: "Identify the historical context for Douglass's speech in 1852.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Names a relevant context (Compromise of 1850, Fugitive Slave Act, *Uncle Tom's Cabin*, slave power expansion)", keywords: ["Fugitive Slave", "1850", "Compromise", "Uncle Tom's Cabin", "1852", "Stowe", "expansion"] }
        ],
        sampleAnswer: "The speech came two years after the 1850 Fugitive Slave Act required northern citizens to assist in returning escaped enslaved people, and the same year as the publication of Stowe's *Uncle Tom's Cabin* — a moment of intensifying sectional crisis.",
      },
      {
        label: "(b)",
        prompt: "Identify the audience Douglass was addressing and one rhetorical strategy he used.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Identifies northern white abolitionist audience and a rhetorical strategy (jeremiad, biblical cadence, irony)", keywords: ["Rochester", "Ladies' Anti-Slavery Society", "white", "northern", "jeremiad", "irony", "biblical", "Isaiah", "Jefferson"] }
        ],
        sampleAnswer: "Douglass spoke to the Rochester Ladies' Anti-Slavery Society — a northern white audience — and used the jeremiad form, citing Isaiah and Jefferson against his listeners, to indict the gap between national ideals and the lived reality of enslavement.",
      },
      {
        label: "(c)",
        prompt: "Explain ONE way Douglass's argument here departs from his earlier Garrisonian position.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Identifies the break with Garrison's view that the Constitution was proslavery", keywords: ["Garrison", "Constitution", "proslavery", "antislavery", "1851", "North Star", "political action"] }
        ],
        sampleAnswer: "By 1852 Douglass had broken with Garrison's view that the Constitution was a proslavery document; he now argued it could be read as antislavery, opening the door to political action through the Liberty and Free Soil parties — a shift signaled in his founding of *The North Star* (1847).",
      },
      {
        label: "(d)",
        prompt: "Identify ONE limitation of using a single Douglass speech as evidence about Black political thought in 1852.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Identifies a valid limitation (Black women's perspectives, free Black opinion in the South, AME Church)", keywords: ["women", "Sojourner Truth", "Maria Stewart", "AME", "free Black", "South", "perspective", "single voice"] }
        ],
        sampleAnswer: "Douglass's voice does not represent all Black political thought of 1852: Sojourner Truth's 'Ain't I a Woman?' (1851) addressed gender directly, and the AME Church and free Black communities in the South had different practical priorities under harsher state laws.",
      }
    ],
    totalPoints: 4,
    timeRecommendation: "~12 minutes",
    calculatorAllowed: false,
  },
  {
    id: "aas-short-3",
    type: 'short' as const,
    unit: 3,
    title: "Source: Combahee River Collective Statement (1977)",
    prompt: "The following is an excerpt from the *Combahee River Collective Statement* (1977).\n\n> 'The most general statement of our politics at the present time would be that we are actively committed to struggling against racial, sexual, heterosexual, and class oppression, and see as our particular task the development of integrated analysis and practice based upon the fact that the major systems of oppression are interlocking.'",
    parts: [
      {
        label: "(a)",
        prompt: "Identify the immediate political context out of which the Combahee River Collective emerged.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Names a relevant context (NBFO 1973, post-civil rights and Black Power, second-wave feminism's racial blind spots)", keywords: ["NBFO", "1973", "Black feminist", "second wave", "white feminism", "Black Power", "lesbian"] }
        ],
        sampleAnswer: "The Collective formed in Boston in 1974 after splitting from the National Black Feminist Organization (1973), in response to the racial blind spots of mainstream second-wave feminism and the marginalization of Black women's leadership in the male-led Black Power movement.",
      },
      {
        label: "(b)",
        prompt: "Explain how the concept of 'interlocking' systems of oppression in the Statement anticipates Kimberlé Crenshaw's later concept of 'intersectionality' (1989).",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Connects 'interlocking' to intersectionality (multiple, mutually constitutive systems)", keywords: ["intersectionality", "Crenshaw", "1989", "interlocking", "race", "gender", "class", "sexuality", "mutually", "constitutive"] }
        ],
        sampleAnswer: "The Statement's claim that race, sex, sexuality, and class are 'interlocking' rather than additive directly anticipates Crenshaw's 1989 argument that single-axis analysis (race OR gender) erases Black women's experience — making the 1977 Statement a foundational text for intersectional theory.",
      },
      {
        label: "(c)",
        prompt: "Identify ONE specific way Combahee influenced later Black political organizing.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Identifies a specific influence (M4BL/BLM founding, intersectional policy platform, queer Black leadership)", keywords: ["M4BL", "BLM", "Cullors", "Garza", "Tometi", "queer", "intersectional", "Movement for Black Lives", "Vision for Black Lives"] }
        ],
        sampleAnswer: "Movement for Black Lives co-founders Patrisse Cullors, Alicia Garza, and Opal Tometi cite the Combahee Statement as a direct influence; the 2016 'Vision for Black Lives' platform's intersectional, abolitionist framework reflects Combahee's analytical structure.",
      },
      {
        label: "(d)",
        prompt: "Identify ONE limitation of using the Statement as evidence about Black women's politics in the 1970s.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Identifies a valid limitation (small group; Northeastern; lesbian/socialist focus may not represent Black women broadly)", keywords: ["small group", "Boston", "lesbian", "socialist", "broad", "AME", "rural", "limit", "perspective"] }
        ],
        sampleAnswer: "Combahee was a small Boston-based group of Black lesbian socialists; its analysis does not necessarily speak for Black church-based, southern, or working-class women's political organizing in the same period, which often used different idioms and strategies.",
      }
    ],
    totalPoints: 4,
    timeRecommendation: "~12 minutes",
    calculatorAllowed: false,
  },
  {
    id: "aas-short-4",
    type: 'short' as const,
    unit: 4,
    title: "Data: Great Migration Population Shifts",
    prompt: "Use the following data to address the prompt.\n\nBetween 1910 and 1970, approximately 6 million African Americans moved from the rural South to the urban North, Midwest, and West. By 1970:\n\n- Detroit: Black population rose from ~6,000 (1910) to ~660,000 (1970) — about 44% of the city.\n- Chicago: from ~44,000 (1910) to ~1.1 million (1970) — about 33% of the city.\n- Harlem: by 1930, more than 200,000 African Americans lived in a 50-block district that had been majority-white in 1900.",
    parts: [
      {
        label: "(a)",
        prompt: "Identify ONE specific 'push' factor that drove the Great Migration out of the South.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Names a specific push factor (lynching, sharecropping debt, boll weevil, disfranchisement, Jim Crow violence)", keywords: ["lynching", "sharecropping", "boll weevil", "1916", "1921", "Tulsa", "Jim Crow", "disfranchisement", "Wells"] }
        ],
        sampleAnswer: "Lynching — documented by Ida B. Wells's 1892 *Southern Horrors* and continuing through the 1921 Tulsa Race Massacre — combined with the boll weevil's destruction of cotton crops after 1915, made daily life and economic survival in the rural South untenable for many Black families.",
      },
      {
        label: "(b)",
        prompt: "Identify ONE specific 'pull' factor that drew migrants north, and name a specific institution or actor that amplified it.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Names a pull factor (WWI labor demand, higher wages, voting rights) and a specific actor (*Chicago Defender*, Pullman porters, Robert Abbott)", keywords: ["WWI", "1917", "labor", "Chicago Defender", "Abbott", "Pullman", "porters", "wages", "voting"] }
        ],
        sampleAnswer: "Wartime industrial labor demand after 1917 — combined with Robert Abbott's *Chicago Defender*, distributed throughout the South by Pullman porters — actively recruited Black workers north with promises of higher wages and political rights.",
      },
      {
        label: "(c)",
        prompt: "Explain ONE way the Great Migration reshaped Black political and cultural life in northern cities.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Identifies a specific cultural/political consequence (Harlem Renaissance 1925, UNIA, Black mayors, blues/jazz, Black press)", keywords: ["Harlem Renaissance", "1925", "Locke", "Hughes", "UNIA", "Garvey", "Ellington", "Black mayors", "Defender", "Courier"] }
        ],
        sampleAnswer: "Concentrated Black populations sustained Alain Locke's *New Negro* (1925) and Marcus Garvey's UNIA, while later producing the political bases for Black mayors (Carl Stokes, Cleveland 1967; Coleman Young, Detroit 1973) — institutional and electoral power that the rural South had violently denied.",
      },
      {
        label: "(d)",
        prompt: "Identify ONE specific way northern cities reproduced racial inequality despite the absence of legal Jim Crow.",
        maxPoints: 1,
        rubric: [
          { points: 1, description: "Identifies de facto mechanisms (HOLC redlining 1933–35, FHA loan discrimination, restrictive covenants, school segregation, Detroit and Chicago race riots)", keywords: ["redlining", "HOLC", "1935", "FHA", "restrictive covenants", "Shelley", "Kraemer", "1948", "1919", "1943", "Detroit"] }
        ],
        sampleAnswer: "Federal HOLC maps (1935) and FHA underwriting standards systematically denied mortgages to Black neighborhoods, while restrictive covenants — only struck down in *Shelley v. Kraemer* (1948) — and the 1919 Chicago and 1943 Detroit race riots showed that northern de facto segregation could be enforced as violently as southern de jure segregation.",
      }
    ],
    totalPoints: 4,
    timeRecommendation: "~12 minutes",
    calculatorAllowed: false,
  }
]


export const apAASFRQs: AASFRQ[] = [...longFRQs, ...shortFRQs]

export function getApAASFRQs(): AASFRQ[] {
  return apAASFRQs
}

export function getLongFRQs(): AASFRQ[] {
  return longFRQs
}

export function getShortFRQs(): AASFRQ[] {
  return shortFRQs
}

export function generateFullExamFRQs(): {
  long: AASFRQ[]
  short: AASFRQ[]
  totalPoints: number
  totalTime: string
} {
  const shuffle = <T>(arr: T[]): T[] => {
    const copy = [...arr]
    for (let i = copy.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1))
      ;[copy[i], copy[j]] = [copy[j], copy[i]]
    }
    return copy
  }

  const selectedLong = shuffle(longFRQs).slice(0, 2)
  const selectedShort = shuffle(shortFRQs).slice(0, 2)
  const totalPoints = [...selectedLong, ...selectedShort].reduce((s, f) => s + f.totalPoints, 0)

  return {
    long: selectedLong,
    short: selectedShort,
    totalPoints,
    totalTime: '90 min',
  }
}
