/**
 * MCAT Full-Length Form 5 — Chemical & Physical Foundations, file A
 * (passages 1–5, 22 questions, plus 8 discrete items).
 *
 * Built to the 2026-09 AAMC-representativeness brief: 400–600-word passages,
 * a mix of experiment and information passages, keys that require using the
 * passage rather than matching its wording, and position/length-balanced
 * options. Explanations reference options by CONTENT, never by letter.
 *
 * LaTeX renders through KaTeX; backslashes are double-escaped in these strings.
 */
import type { MCATPassage, MCATDiscreteQuestion } from '../types'

export const FL5_CHEM_PHYS_A_PASSAGES: MCATPassage[] = [
  // ────────────────────────────────────────────────────────────────────────
  // 1. PHYSICS (experiment, chart) — Hydrostatic pressure in the circulation
  // ────────────────────────────────────────────────────────────────────────
  {
    id: 'fl5-cp-a-01',
    section: 'chem-phys',
    discipline: 'physics',
    title: 'Hydrostatic Pressure Gradients in the Standing Body',
    passageText:
      'The pressure in a fluid at rest increases with depth. For two points separated by a vertical distance $h$ in a fluid of density $\\rho$, the lower point is at the higher pressure, and the difference between them is $\\rho g h$. Blood is a fluid, and although the circulation is never at rest, this hydrostatic contribution is superimposed on the pressure generated by the heart at every point in the vascular tree. Clinically, blood pressures are reported as gauge pressures, the amount by which the pressure exceeds the surrounding atmospheric pressure, and they are expressed in millimeters of mercury (mmHg), the height of a column of mercury that the pressure can support. One standard atmosphere supports a mercury column 760 mm high; mercury is used for this purpose because it is far denser than water or blood, so the column stays conveniently short.\n\nA sphygmomanometer measures arterial pressure indirectly. An inflatable cuff is wrapped around the upper arm and inflated until it squeezes the brachial artery shut. As the cuff is slowly deflated, the cuff pressure at which blood first spurts through with each heartbeat is recorded as the systolic pressure, and the cuff pressure at which flow becomes continuous and silent is recorded as the diastolic pressure. At each of these moments the pressure inside the cuff equals the pressure inside the artery beneath it, so the cuff gauge reports the arterial pressure at the position of the cuff. By convention the measurement is made with the cuff at the level of the heart.\n\nTo examine how posture affects pressure in different parts of the arterial tree, investigators recorded mean arterial pressure in eight healthy adults using miniature pressure transducers mounted on the tips of catheters threaded into the arterial system. Readings were taken at eight vertical levels, from 100 cm below the heart (at the ankle) to 40 cm above it (at the level of the head), first with each subject lying supine on a horizontal table and then after the subject had stood quietly for five minutes. Each transducer was calibrated against a water manometer before use. The results are shown in Figure 1, in which the vertical position of each site is given relative to the heart, with positive values above it. Mean pressure at heart level happened to be nearly identical in the two postures.\n\nThe investigators compared their findings with two extreme cases. The giraffe carries its brain about 2.0 m above its heart, and its mean arterial pressure at heart level, roughly 250 mmHg, is about two and a half times the human value; the carotid arteries run almost vertically from heart to head. In orbiting astronauts, by contrast, blood has no weight, and the hydrostatic component of pressure vanishes throughout the body. Within hours of reaching orbit, astronauts develop puffy faces and thin legs as fluid redistributes toward the head, and many report nasal congestion like that of a head cold.\n\nVenous pressures are subject to the same hydrostatic gradient, but the veins of the lower limb contain one-way valves, and contraction of the surrounding skeletal muscle during walking drives blood toward the heart one segment at a time, so that venous pressure in the foot during walking is far lower than the full hydrostatic value reached during motionless standing.',
    chart: {
      title: 'Figure 1. Mean arterial pressure at eight vertical levels relative to the heart, supine and standing (n = 8)',
      kind: 'line',
      xLabel: 'Vertical position relative to heart',
      xUnit: 'cm',
      yLabel: 'Mean arterial pressure',
      yUnit: 'mmHg',
      xValues: [-100, -80, -60, -40, -20, 0, 20, 40],
      yValues: [172, 157, 141, 126, 110, 95, 80, 64],
      seriesLabel: 'Standing',
      comparisonSeries: [{ label: 'Supine', yValues: [94, 94, 95, 95, 95, 95, 94, 94] }],
    },
    questions: [
      {
        question: 'Based on Figure 1, the hydrostatic pressure gradient along the arterial tree of a standing subject is closest to:',
        options: ['0.077 mmHg per cm', '0.77 mmHg per cm', '1.3 mmHg per cm', '7.7 mmHg per cm'],
        correctAnswer: 1,
        explanation:
          'On the standing curve the pressure rises from 64 mmHg at 40 cm above the heart to 172 mmHg at 100 cm below it, a change of 108 mmHg over 140 cm, or about 0.77 mmHg per cm. This agrees with the density of blood: $\\rho g h$ for 1 cm of blood is about $(1060)(9.8)(0.01) \\approx 104$ Pa, and 1 mmHg is about 133 Pa, giving 0.78 mmHg per cm. The value 1.3 is the reciprocal of the gradient, in cm per mmHg. The values 7.7 and 0.077 each slip a factor of ten.',
        skill: '4B hydrostatic pressure gradient from a figure (Skill 4)',
      },
      {
        question: 'A standing subject’s blood pressure is measured with the cuff on an arm held so that the cuff is 26 cm above the level of the heart. Compared with a reading taken at heart level, the systolic reading will be about:',
        options: [
          'unchanged, because the gauge reads the pressure generated by the heart, not by gravity',
          '20 mmHg higher, because the veins of the elevated arm drain more freely toward the heart',
          '26 mmHg lower, because each centimeter of elevation removes one millimeter of mercury',
          '20 mmHg lower, because the artery under the cuff lies above the level of the heart',
        ],
        correctAnswer: 3,
        explanation:
          'The cuff reports the arterial pressure at its own position, and Figure 1 shows that arterial pressure in a standing subject falls by about 0.77 mmHg for every centimeter above the heart, so a cuff 26 cm above the heart reads about $26 \\times 0.77 \\approx 20$ mmHg lower. The reading is not immune to gravity, because the artery beneath the cuff carries the hydrostatic term just as the sites in Figure 1 do. Raising the arm lowers, rather than raises, the pressure in the artery, and venous drainage does not set arterial pressure. A drop of 26 mmHg would require a gradient of 1 mmHg per cm, which the figure rules out.',
        skill: '4B hydrostatic pressure applied to cuff measurement (Skill 2)',
      },
      {
        question: 'According to Figure 1, the absolute pressure in an artery at the ankle of a standing subject is closest to:',
        options: ['172 mmHg', '588 mmHg', '760 mmHg', '932 mmHg'],
        correctAnswer: 3,
        explanation:
          'The figure reports gauge pressure, the excess over atmospheric pressure, and the standing value at 100 cm below the heart is 172 mmHg. Absolute pressure adds the atmosphere: $172 + 760 = 932$ mmHg. The value 172 mmHg is the gauge pressure alone. The value 760 mmHg is atmospheric pressure alone, which would correspond to a gauge pressure of zero. The value 588 mmHg subtracts the arterial pressure from atmospheric pressure, which would describe a pressure below atmospheric.',
        skill: '4B gauge versus absolute pressure (Skill 4)',
      },
      {
        question: 'Using the gradient measured in Figure 1 and the information in the passage, the mean arterial pressure in the giraffe’s brain is closest to:',
        options: ['95 mmHg', '155 mmHg', '250 mmHg', '405 mmHg'],
        correctAnswer: 0,
        explanation:
          'The brain is 2.0 m, or 200 cm, above the heart, and at about 0.77 mmHg per cm the hydrostatic drop over that height is about 154 mmHg, so the brain pressure is roughly $250 - 154 \\approx 96$ mmHg, close to the human value at heart level. The value 155 mmHg is the hydrostatic drop by itself, not the pressure that remains. The value 250 mmHg ignores the height of the brain above the heart. The value 405 mmHg adds the hydrostatic term instead of subtracting it, which would be appropriate only for a point below the heart.',
        skill: '4B hydrostatic pressure in a vertical column (Skill 2)',
      },
      {
        question: 'The investigators recorded pressure with transducers mounted on the catheter tips rather than with fluid-filled catheters connected to a transducer outside the body. The most likely reason is that with a fluid-filled catheter:',
        options: [
          'the reading would include the weight of the fluid between the tip and the transducer',
          'the fluid would transmit the pulsatile component of pressure but not the mean pressure',
          'the fluid column would convert the gauge pressure at the tip into an absolute pressure',
          'the fluid would clot during five minutes of quiet standing and block the pressure signal',
        ],
        correctAnswer: 0,
        explanation:
          'A fluid-filled catheter transmits pressure to wherever the transducer sits, and the fluid inside it is itself a column with weight, so the transducer registers the tip pressure plus or minus $\\rho g h$ for the height difference between tip and transducer. In a study whose entire purpose is to measure pressures at sites spread over 140 cm of height, an external transducer would have to be re-leveled for every site, so a tip-mounted transducer removes the problem. A continuous fluid column transmits both the mean and the pulsatile components of pressure. A fluid column adds or subtracts a hydrostatic offset; it does not change a gauge reading into an absolute one. Clotting is a practical concern for any catheter, but it is not a reason specific to this measurement.',
        skill: '4B measurement design in a hydrostatic study (Skill 3)',
      },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────
  // 2. GENERAL CHEMISTRY (information) — Essential metals, chelation, Lewis acid–base
  // ────────────────────────────────────────────────────────────────────────
  {
    id: 'fl5-cp-a-02',
    section: 'chem-phys',
    discipline: 'general chemistry',
    title: 'Transition Metals, Chelation, and the Control of Free Metal Ions',
    passageText:
      'Iron, copper, and zinc are required in milligram quantities by every human cell, yet none of them is allowed to circulate as a free aqueous ion. Each cation is a Lewis acid: it has empty valence orbitals and accepts electron pairs from ligands, which are Lewis bases, to form coordination complexes. In water a bare metal ion is immediately surrounded by water molecules, and the biological chemistry of the metal consists largely of exchanging these water ligands for the nitrogen, oxygen, and sulfur donor atoms of proteins and small molecules. Iron(III) prefers six ligands in an octahedral arrangement, copper(II) is commonly found with four to six, and zinc(II) in enzymes is most often four-coordinate and tetrahedral.\n\nThe three metals differ sharply in their redox behavior. Iron cycles between the +2 and +3 states, and copper between +1 and +2, under conditions found in cells; this is why both serve as electron carriers in the respiratory chain and in oxidases. Zinc(II), with a completely filled 3d subshell, has no second oxidation state that is accessible in biology. It is therefore used where a Lewis acid is needed without any possibility of electron transfer, as in carbonic anhydrase and in the zinc-finger domains of transcription factors.\n\nThe same ability to transfer electrons makes free iron and copper dangerous. In the Fenton reaction, Fe²⁺ + H₂O₂ → Fe³⁺ + OH⁻ + •OH, a trace of reduced iron converts hydrogen peroxide, a routine product of metabolism, into the hydroxyl radical, the most reactive oxygen species encountered in biology; Cu⁺ does the same. For this reason iron in plasma is carried by transferrin, two Fe³⁺ ions per protein molecule, and stored inside ferritin, while copper is carried by ceruloplasmin. In healthy plasma the concentration of free, exchangeable iron is below $10^{-18}$ M.\n\nA ligand that offers two or more donor atoms to the same metal ion is a chelating agent, and the ring that it closes with the metal is a chelate ring. Ethylenediaminetetraacetate, EDTA⁴⁻, is hexadentate: its two amine nitrogens and four carboxylate oxygens occupy all six positions around an octahedral ion. The formation constant $K_f$ for a 1:1 metal–EDTA complex ranges over many orders of magnitude depending on the metal. Representative values of $\\log K_f$ are: Mg²⁺, 8.7; Ca²⁺, 10.7; Zn²⁺, 16.5; Pb²⁺, 18.0; Cu²⁺, 18.8; Fe³⁺, 25.1. In every case the chelate is far more stable than the complex the same metal forms with six separate ligands that each supply one comparable donor atom, even though the individual metal–donor bonds are of similar strength.\n\nChelating agents are the drugs of choice when a metal accumulates to toxic levels. Deferoxamine, a bacterial product bearing three hydroxamic acid groups, binds Fe³⁺ with $\\log K_f$ of about 31 and is given for iron overload. Penicillamine, which carries a thiol, an amine, and a carboxylate, is used for copper overload. For lead poisoning, EDTA is administered not as the disodium salt but as the calcium disodium salt, CaNa₂EDTA, in which the chelator is already occupied by Ca²⁺ when it enters the bloodstream; the disodium salt itself can precipitate a dangerous fall in plasma calcium. Because every one of these drugs binds several essential metals in addition to the one targeted, chelation therapy is monitored with serial measurements of plasma metal concentrations, and mineral supplements may be required during a long course of treatment.',
    questions: [
      {
        question: 'Which of the following metal ions would be expected to behave most like Zn²⁺ with respect to the radical-generating chemistry described in the passage?',
        options: ['Cu⁺', 'Fe²⁺', 'Mg²⁺', 'Mn²⁺'],
        correctAnswer: 2,
        explanation:
          'Fenton-type chemistry requires a metal that can give up an electron to H₂O₂, so an ion that is safe in the way Zn²⁺ is safe must have no accessible higher oxidation state. Mg²⁺ is a group 2 ion with a noble-gas electron configuration; like Zn²⁺ it exists in cells in a single oxidation state and cannot donate an electron. Cu⁺ and Fe²⁺ are the reduced members of the two redox couples the passage identifies as hazardous. Manganese is a transition metal with several accessible oxidation states (+2, +3, +4, and higher), so Mn²⁺ can be oxidized and does not resemble zinc in this respect.',
        skill: '4E oxidation states and electron configuration of metal ions (Skill 1)',
      },
      {
        question: 'The complex of Fe³⁺ with one EDTA⁴⁻ ion is far more stable than its complex with six separate monodentate ligands of similar donor strength. The main thermodynamic reason is that forming the EDTA complex from the aqueous ion:',
        options: [
          'releases six water molecules while consuming only one ligand, so the entropy change is more favorable',
          'forms six metal–ligand bonds that are each much stronger than a bond to a monodentate ligand',
          'produces a complex with a lower net charge, which is more strongly stabilized by solvation in water',
          'requires that the iron first be reduced to Fe²⁺, which binds carboxylate and amine donors more tightly',
        ],
        correctAnswer: 0,
        explanation:
          'When EDTA⁴⁻ replaces the six water ligands of the aqueous ion, one particle binds and six are set free, so the number of independent particles in solution rises by five and $\\Delta S$ is strongly positive; replacing six waters with six monodentate ligands leaves the particle count unchanged and gives no such entropic gain. The passage specifies that the individual metal–donor bonds are of similar strength, so the enthalpy of bonding cannot be the main difference. The Fe(EDTA)⁻ complex does carry a lower charge than the +3 aquo ion, but the question compares EDTA with six monodentate ligands of comparable donor type, and solvation of the product is not the dominant effect. No reduction of iron is involved, and the formation constants show that Fe³⁺ binds EDTA far more strongly than divalent ions do.',
        skill: '5B/5E the chelate effect and entropy (Skill 2)',
      },
      {
        question: 'Based on the formation constants in the passage, which essential ion is most likely to be depleted during a prolonged course of CaNa₂EDTA?',
        options: ['Mg²⁺', 'Ca²⁺', 'Na⁺', 'Zn²⁺'],
        correctAnswer: 3,
        explanation:
          'The administered chelator arrives already bound to Ca²⁺, so another metal can be captured only if it displaces calcium, which requires a more stable complex than Ca–EDTA ($\\log K_f = 10.7$). Zn²⁺ ($\\log K_f = 16.5$) forms a complex nearly a million-fold more stable and will be taken up and excreted, which is why zinc depletion is a recognized consequence of EDTA therapy. Mg²⁺ ($\\log K_f = 8.7$) binds more weakly than Ca²⁺ and cannot displace it. Ca²⁺ is not depleted because the chelator is already saturated with calcium; this is exactly why the calcium salt is used. Na⁺ forms no significant complex with EDTA and is present simply as a counterion.',
        skill: '5E formation constants and ligand exchange (Skill 2)',
      },
      {
        question: 'In the Fenton reaction shown in the passage, hydrogen peroxide acts as:',
        options: [
          'an oxidizing agent, and the oxidation state of each of its oxygen atoms changes from −2 to −1',
          'an oxidizing agent, and the oxidation state of one of its oxygen atoms changes from −1 to −2',
          'a reducing agent, and the oxidation state of one of its oxygen atoms changes from −1 to 0',
          'a reducing agent, and the oxidation state of each of its oxygen atoms changes from −1 to −2',
        ],
        correctAnswer: 1,
        explanation:
          'Iron goes from +2 to +3, so it is oxidized, and hydrogen peroxide, which accepts the electron, is the oxidizing agent. In H₂O₂ each oxygen is in the −1 state; the oxygen that ends up in OH⁻ is reduced to −2, while the oxygen in the neutral radical •OH remains at −1. Peroxide oxygen starts at −1, not −2, so no oxygen is taken from −2 to −1. Peroxide is not the reducing agent in this reaction, and no oxygen is oxidized to the zero state, which would require O₂ formation. Only one of the two oxygens changes oxidation state, so it is incorrect to say that both are reduced.',
        skill: '4C oxidation states and redox roles in the Fenton reaction (Skill 1)',
      },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────
  // 3. BIOCHEMISTRY (experiment, table) — Reducing sugars, hydrolysis, anomeric carbon
  // ────────────────────────────────────────────────────────────────────────
  {
    id: 'fl5-cp-a-03',
    section: 'chem-phys',
    discipline: 'biochemistry',
    title: 'Identifying Unknown Sugars by Reducing Power and Hydrolysis',
    passageText:
      'Monosaccharides are polyhydroxy aldehydes or ketones. In solution a hexose such as glucose exists almost entirely as a six-membered ring, formed when the hydroxyl group on C-5 adds to the carbonyl carbon, C-1, and converts the aldehyde into a cyclic hemiacetal. The former carbonyl carbon, now bonded to two oxygen atoms, is the anomeric carbon, and the hydroxyl group attached to it can lie on either face of the ring, giving the α and β anomers. Because the ring opens and closes continuously, the two anomers and a small amount of the open-chain form coexist at equilibrium.\n\nWhen the anomeric hydroxyl of one sugar condenses with a hydroxyl group of a second molecule, the product is a glycosidic bond. The anomeric carbon involved is now an acetal and is locked: it can no longer open to the free carbonyl. A disaccharide in which only one anomeric carbon takes part in the bond retains a hemiacetal at its other end; a disaccharide in which both anomeric carbons form the bond has none.\n\nBenedict’s reagent, an alkaline solution of Cu²⁺ complexed with citrate, is reduced by sugars that can present a free aldehyde group, with formation of a red-brown precipitate of Cu₂O; sugars that respond are called reducing sugars. The acetal linkage of a glycoside is stable in base but is cleaved by hot dilute acid, which hydrolyzes glycosidic bonds without regard to their configuration. Glycosidase enzymes, in contrast, hydrolyze only bonds of one specific configuration: maltase (an α-glucosidase) cleaves the α(1→4) bond between two glucose units, lactase (a β-galactosidase) cleaves the β(1→4) bond that joins galactose to glucose, and sucrase cleaves the bond in sucrose, which joins the anomeric carbon of glucose to the anomeric carbon of fructose.\n\nFive carbohydrate samples, labeled V through Z, were each supplied as a pure compound at a concentration of 10.0 mM. Students were told that each sample was either a single hexose or a disaccharide made of two hexose units, and that no two samples were the same compound. Five 1.00-mL portions of each sample were prepared. One portion was tested directly with Benedict’s reagent. A second was heated with 1 M HCl for 30 min, neutralized, and then tested. Each of the remaining three was incubated with one of the three glycosidases at 37 °C and pH 7 for 1 h and then tested. In every test the Cu₂O precipitate was collected, dried, and weighed, and its mass was expressed as a reducing value relative to the mass produced by a 1.00-mL portion of 10.0 mM glucose, which was assigned the value 1.00. Under these conditions a given mass of precipitate was found to be proportional to the number of moles of reducing sugar present. The results are given in Table 1.\n\nIn a separate experiment, the open-chain form of Sample W was shown to contain a ketone group rather than an aldehyde group.',
    figure:
      '**Table 1. Reducing values of the five samples (glucose, 10.0 mM = 1.00)**\n\n| Sample | Untreated | After acid hydrolysis | After maltase | After lactase | After sucrase |\n|--------|-----------|----------------------|---------------|---------------|---------------|\n| V | 0.00 | 2.00 | 0.00 | 0.00 | 0.00 |\n| W | 1.00 | 1.00 | 1.00 | 1.00 | 1.00 |\n| X | 0.00 | 2.00 | 0.00 | 0.00 | 2.00 |\n| Y | 1.00 | 2.00 | 2.00 | 1.00 | 1.00 |\n| Z | 1.00 | 2.00 | 1.00 | 2.00 | 1.00 |',
    questions: [
      {
        question: 'Based on Table 1, which samples are disaccharides in which only one of the two anomeric carbons takes part in the glycosidic bond?',
        options: ['V and X', 'W only', 'V, X, Y, and Z', 'Y and Z'],
        correctAnswer: 3,
        explanation:
          'A disaccharide doubles its reducing value when acid cleaves it into two monosaccharides, and Y and Z do so (1.00 to 2.00); because each already reduces the reagent before hydrolysis, each retains one free hemiacetal, so only one anomeric carbon is in the bond. V and X are also disaccharides, since acid raises their values from 0.00 to 2.00, but their lack of reducing power before hydrolysis shows that both anomeric carbons are tied up in the bond. W is unchanged by acid and by every enzyme, so it is a single hexose, not a disaccharide. Grouping all four disaccharides together ignores the untreated column, which separates the two kinds of linkage.',
        skill: '5D interpreting reducing-sugar data (Skill 4)',
      },
      {
        question: 'Sample V is best described as a disaccharide that:',
        options: [
          'is joined by a β(1→4) bond between two glucose units',
          'is joined through the anomeric carbons of both of its monosaccharide units',
          'contains a fructose unit joined through its anomeric carbon to a glucose hydroxyl',
          'contains a free hemiacetal that the ring structure shields from Benedict’s reagent',
        ],
        correctAnswer: 1,
        explanation:
          'V gives no reducing value until acid hydrolysis releases two reducing units, so neither monosaccharide retains a free hemiacetal: both anomeric carbons must be part of the glycosidic bond. A β(1→4) glucose–glucose bond uses only one anomeric carbon and would leave V reducing before any treatment. A fructose unit linked through its anomeric carbon to a non-anomeric hydroxyl of glucose would leave the glucose hemiacetal free, again making V reducing; and if the glucose anomeric carbon were also used, as in sucrose, sucrase would have cleaved it, which it did not. A free hemiacetal is in equilibrium with the open-chain aldehyde and is never shielded from the reagent.',
        skill: '5D glycosidic bonds and the anomeric carbon (Skill 2)',
      },
      {
        question: 'Methyl α-D-glucopyranoside is glucose in which the anomeric hydroxyl group has been converted to an –OCH₃ group. An untreated 10.0 mM solution of this compound would be expected to give a reducing value of:',
        options: [
          '0.00, because the anomeric carbon has become an acetal that cannot open to an aldehyde',
          '0.50, because only the β anomer of glucose can be converted to the methyl derivative',
          '1.00, because the methyl group leaves the oxidation state of the anomeric carbon unchanged',
          '2.00, because the methoxy group is itself oxidized by alkaline Cu²⁺ in the reagent',
        ],
        correctAnswer: 0,
        explanation:
          'Replacing the anomeric –OH with –OCH₃ converts the hemiacetal into an acetal, the same functional group that locks the anomeric carbon in a glycoside, so the ring can no longer open to expose an aldehyde and no Cu₂O forms. The compound is a single, pure α anomer, and a value of 0.50 would require a mixture in which half the molecules still had a free hemiacetal. The oxidation state of the anomeric carbon is indeed unchanged by methylation, but reducing power depends on the ability to generate a free aldehyde, not on oxidation state alone. An ether-type methoxy group is not oxidized by Benedict’s reagent.',
        skill: '5D hemiacetal versus acetal at the anomeric carbon (Skill 1)',
      },
      {
        question: 'A student notes that Sample V gave a value of 0.00 after each enzyme treatment and concludes that V contains none of the three bonds those enzymes recognize. Which feature of the results in Table 1 is needed to justify this conclusion?',
        options: [
          'Each enzyme raised the reducing value of one other sample under the same incubation conditions',
          'Sample V reached a reducing value of 2.00 after it was heated with dilute acid',
          'Sample V gave a reducing value of 0.00 before any treatment was applied',
          'No enzyme treatment gave a higher reducing value than acid hydrolysis gave',
        ],
        correctAnswer: 0,
        explanation:
          'A negative result after enzyme treatment is informative only if the enzyme was active: a denatured or mis-stored preparation would leave every substrate uncleaved. Table 1 supplies the positive controls: sucrase doubled the value of X, maltase that of Y, and lactase that of Z under the same conditions, so each preparation was active and its failure to act on V can be attributed to the structure of V. The acid result shows that V is a disaccharide of two reducing hexoses but says nothing about whether the enzymes worked. The untreated value of 0.00 shows that V has no free hemiacetal and likewise does not bear on enzyme activity. That no enzyme exceeded the acid value is expected for any disaccharide and would hold even if every enzyme were inactive.',
        skill: '5D positive controls in an enzyme-specificity experiment (Skill 3)',
      },
      {
        question: 'Which of the following best explains the result obtained for untreated Sample W?',
        options: [
          'Ketones are oxidized by alkaline Cu²⁺ to carboxylic acids as readily as aldehydes are',
          'The citrate in the reagent reduces the ketone to an alcohol, releasing Cu₂O in the process',
          'Ring opening of a ketohexose exposes a hemiketal hydroxyl group that is itself a reducing group',
          'The alkaline reagent isomerizes the ketose to an aldose through an enediol intermediate',
        ],
        correctAnswer: 3,
        explanation:
          'W reduces the reagent fully (1.00) despite having a ketone rather than an aldehyde in its open-chain form. In base, the α-hydroxy ketone of a ketose undergoes keto–enol tautomerization to an enediol, which can re-ketonize with the carbonyl at C-1, giving an aldose that then reduces Cu²⁺; this is why ketoses such as fructose are classified as reducing sugars. Simple ketones are not oxidized to carboxylic acids under these conditions, because that would require breaking a carbon–carbon bond. Citrate serves only to keep Cu²⁺ in solution in base and is not a reducing agent for ketones. A hemiketal hydroxyl is a hydroxyl group, not a reducing group; it is the carbonyl that is oxidized.',
        skill: '5D ketoses as reducing sugars via keto–enol tautomerization (Skill 1)',
      },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────
  // 4. ORGANIC CHEMISTRY (experiment, table) — Amine basicity and ion trapping
  // ────────────────────────────────────────────────────────────────────────
  {
    id: 'fl5-cp-a-04',
    section: 'chem-phys',
    discipline: 'organic chemistry',
    title: 'Basicity of Amine Drugs and pH-Dependent Partitioning',
    passageText:
      'Most drugs that act on the nervous system are amines. An amine is a derivative of ammonia in which one, two, or three hydrogens are replaced by carbon groups; it is classified as primary, secondary, or tertiary according to the number of carbon atoms bonded to the nitrogen, not according to the substitution of those carbons. When a fourth carbon group is attached, the nitrogen carries a permanent positive charge and the compound is a quaternary ammonium salt. The lone pair on the nitrogen of a primary, secondary, or tertiary amine makes it a base: it is protonated by acid to give an ammonium ion. Basicity is conventionally expressed as the $\\text{p}K_a$ of the conjugate ammonium ion, so that a higher $\\text{p}K_a$ corresponds to a stronger base. For a base B and its conjugate acid BH⁺,\n\n$\\text{pH} = \\text{p}K_a + \\log\\frac{[\\text{B}]}{[\\text{BH}^+]}$\n\nThe ammonium ions of simple alkylamines have $\\text{p}K_a$ values near 10, whereas those of aromatic amines, in which the nitrogen is bonded directly to a benzene ring, have $\\text{p}K_a$ values near 4 to 5. Amides are not appreciably basic under physiological conditions.\n\nThe charge state of an amine controls its movement through the body. A lipid bilayer is readily crossed by the small neutral molecule but is essentially impermeable to the charged ammonium ion. When a membrane separates two aqueous compartments of different pH, the neutral form equilibrates across the membrane until its concentration is the same on both sides, but the concentration of the ionized form on each side is set by that side’s pH. The total concentration of drug, neutral plus ionized, therefore differs between the compartments, a phenomenon called ion trapping. For a weak base, the ratio of total concentrations at equilibrium is\n\n$\\frac{C_B}{C_A} = \\frac{1 + 10^{(\\text{p}K_a - \\text{pH}_B)}}{1 + 10^{(\\text{p}K_a - \\text{pH}_A)}}$\n\nwhere $C_A$ and $C_B$ are the total concentrations in compartments A and B. For a weak acid, the sign of each exponent is reversed.\n\nTo measure ion trapping directly, investigators used a cell with two 10-mL compartments separated by a synthetic lipid membrane. Compartment A was buffered at pH 7.4 to represent plasma, and compartment B at pH 6.4 to represent mildly acidic urine. Each of four test compounds was added to compartment A at an initial concentration of 100 μM, the cell was gently stirred for 24 h at 37 °C, and the total concentration of the compound in each compartment was then measured. Compound 1 is a tertiary alkylamine bearing two N-methyl groups; Compound 2 is a primary aromatic amine; Compound 3 is the N-methyl quaternary ammonium derivative of Compound 1; and Compound 4 is a carboxylic acid. The $\\text{p}K_a$ values and the equilibrium concentration ratios are listed in Table 1. The investigators confirmed that none of the compounds bound measurably to the membrane itself and that the pH of each compartment did not drift during the experiment.',
    figure:
      '**Table 1. Properties and equilibrium distribution of the four test compounds**\n\n| Compound | Class | pKa of conjugate acid | $C_B / C_A$ at equilibrium |\n|----------|-------|----------------------|----------------------------|\n| 1 | Tertiary alkylamine | 9.4 | 9.9 |\n| 2 | Primary aromatic amine | 4.6 | 1.0 |\n| 3 | Quaternary ammonium salt | — | < 0.01 |\n| 4 | Carboxylic acid | 3.5 | 0.10 |',
    questions: [
      {
        question: 'If compartment B had instead been buffered at pH 5.4, the equilibrium ratio $C_B/C_A$ for Compound 1 would have been closest to:',
        options: ['1.0', '9.9', '99', '990'],
        correctAnswer: 2,
        explanation:
          'With $\\text{p}K_a = 9.4$, the exponent on side A (pH 7.4) is 2.0, giving $1 + 10^{2} = 101$, and on side B (pH 5.4) it is 4.0, giving $1 + 10^{4} \\approx 10{,}001$; the ratio is about 99. Each additional pH unit of acidity on side B traps about ten times more of the protonated form, so the ratio climbs from about 10 at pH 6.4 to about 100 at pH 5.4. A ratio of 1.0 would require equal pH on both sides. The value 9.9 is the ratio measured at pH 6.4, before the change. The value 990 corresponds to a side-B pH of 4.4, one unit more acidic than specified.',
        skill: '5A/5D ion trapping and the Henderson–Hasselbalch relation (Skill 2)',
      },
      {
        question: 'Compound 2 is a much weaker base than Compound 1 primarily because in Compound 2:',
        options: [
          'the nitrogen lone pair is delocalized into the π system of the aromatic ring',
          'the nitrogen is bonded to fewer carbon atoms and so receives less electron donation',
          'the aromatic ring sterically prevents a proton from approaching the nitrogen',
          'the N–H bonds of a primary amine are acidic, so the compound acts as an acid instead',
        ],
        correctAnswer: 0,
        explanation:
          'In an aromatic amine the nitrogen lone pair is conjugated with the ring and is shared with the π system by resonance, so it is less available to accept a proton, and protonation also destroys that resonance stabilization; both effects lower the $\\text{p}K_a$ of the conjugate acid by about five units. The difference between a primary and a tertiary alkylamine is small (both have $\\text{p}K_a$ near 10), so the number of carbon groups cannot account for a gap of this size. A flat benzene ring presents no meaningful steric barrier to a proton, the smallest possible electrophile. The N–H bonds of amines are not acidic in water; amines are bases, and the compound is still protonated at low pH.',
        skill: '5D resonance and the basicity of aromatic versus alkyl amines (Skill 1)',
      },
      {
        question: 'Which of the following compounds would be expected to behave like Compound 3 in this experiment?',
        options: ['(CH₃)₃C–NH₂', 'CH₃CH₂–N(CH₃)₂', 'CH₃–CO–N(CH₃)₂', '[(CH₃)₃N–CH₂CH₃]⁺ Br⁻'],
        correctAnswer: 3,
        explanation:
          'Compound 3 is a quaternary ammonium salt: its nitrogen bears four carbon groups and a positive charge that no change in pH can remove, so it has no neutral form that can cross the membrane and essentially none reaches compartment B. The ethyltrimethylammonium bromide salt has the same structure and would behave the same way. tert-Butylamine, despite its heavily substituted carbon, is a primary amine, and N,N-dimethylethylamine is a tertiary amine; both have neutral forms and would partition like Compound 1. N,N-Dimethylacetamide is an amide, which is neutral at every pH and would cross freely, giving a ratio near 1.0.',
        skill: '5D classification of amines and quaternary ammonium salts (Skill 1)',
      },
      {
        question: 'Which additional experiment would most directly test whether the accumulation of Compound 1 in compartment B depends on the pH difference between the compartments?',
        options: [
          'Repeat the experiment with Compound 3 added to compartment B rather than to compartment A',
          'Repeat the experiment with both compartments buffered at pH 7.4',
          'Repeat the experiment with the initial concentration of Compound 1 doubled',
          'Repeat the experiment with the membrane replaced by one twice as thick',
        ],
        correctAnswer: 1,
        explanation:
          'Ion trapping predicts that with no pH difference the neutral form equilibrates and every ionized fraction matches, so the ratio should fall to 1.0; observing that directly isolates the pH difference as the cause. Moving Compound 3 to the other side tests a different, permanently charged compound and says nothing about Compound 1. Doubling the starting concentration tests whether the ratio is concentration-independent, which is expected for a dilute solute, but does not test the role of pH. A thicker membrane would slow the approach to equilibrium without changing the equilibrium ratio, so it does not address the question either.',
        skill: '5A experimental design for testing an ion-trapping mechanism (Skill 3)',
      },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────
  // 5. PHYSICS (information) — X-ray production, attenuation, contrast
  // ────────────────────────────────────────────────────────────────────────
  {
    id: 'fl5-cp-a-05',
    section: 'chem-phys',
    discipline: 'physics',
    title: 'Production and Attenuation of Diagnostic X-rays',
    passageText:
      'A radiograph is a shadow. X-ray photons leave a small source, pass through the patient, and strike a detector. Where the body has absorbed or scattered more of them, the conventional image is brighter, so bone appears white, and where more photons pass through, the image is darker. Interpreting such an image, and choosing the exposure that produces it, depends on how the photons are generated and how they are removed from the beam.\n\nIn an x-ray tube, electrons released from a heated filament are accelerated through a potential difference of 50 to 150 kV toward a tungsten target. An electron accelerated through a potential difference $V$ acquires kinetic energy $eV$; at 100 kV this is 100 keV. When the electrons are abruptly decelerated by the nuclei of the target they radiate a continuous spectrum of photons, called bremsstrahlung, whose energies run from near zero up to a maximum equal to the full kinetic energy of the electrons. Superimposed on this continuum are a few characteristic lines, emitted when an incident electron ejects an inner-shell electron from a tungsten atom and an outer electron drops into the vacancy. More than 99% of the electrons’ energy ends up as heat in the target, so the anode is rotated and cooled. The tube current, typically 100 to 500 mA, sets the number of photons produced per second, while the tube voltage sets the maximum, and roughly the average, photon energy.\n\nA narrow beam of photons of a single energy passing through matter is attenuated exponentially: $I = I_0 e^{-\\mu x}$, where $x$ is the thickness traversed and $\\mu$, the linear attenuation coefficient, depends on the material and on the photon energy. The thickness that reduces the intensity by half is the half-value layer, $\\text{HVL} = \\ln 2/\\mu \\approx 0.693/\\mu$. At 60 keV the HVL of soft tissue is about 3.5 cm, that of cortical bone about 1.0 cm, and that of lead about 0.1 mm.\n\nTwo processes dominate attenuation at diagnostic energies. In the photoelectric effect a photon is absorbed outright by an atom, which ejects a bound electron; the probability of this process per atom rises steeply with atomic number, approximately as $Z^3$, and falls steeply with photon energy, approximately as $1/E^3$. In Compton scattering a photon transfers part of its energy to a loosely bound electron and continues in a new direction; its probability depends on the number of electrons per unit volume, which is nearly the same for all soft tissues and less than twice as high for bone, and it declines only slowly as photon energy rises. Contrast between tissues in a radiograph therefore arises mainly from differences in photoelectric absorption. Soft tissue has an effective atomic number of about 7.4; bone, because of its calcium (Z = 20) and phosphorus, about 13; and the elements used in contrast agents, iodine (Z = 53) and barium (Z = 56), are higher still. Iodinated compounds injected into blood vessels and barium sulfate suspensions swallowed or introduced into the bowel render those structures opaque.\n\nPhotoelectric absorption also shows a sharp jump when the photon energy just exceeds the binding energy of an inner-shell electron, a feature called the K-edge: for iodine it lies at 33 keV and for barium at 37 keV. Photons slightly above the K-edge are absorbed far more strongly than photons slightly below it, and the tube voltage for a contrast study is chosen with this in mind.',
    questions: [
      {
        question: 'A radiographer finds that 10.5 cm of soft tissue transmits the same fraction of a 60-keV beam as a slab of cortical bone. Based on the passage, the thickness of the bone slab is closest to:',
        options: ['1.0 cm', '3.0 cm', '3.5 cm', '10.5 cm'],
        correctAnswer: 1,
        explanation:
          'A thickness of 10.5 cm is three half-value layers of soft tissue (3 × 3.5 cm), which transmits $(1/2)^3 = 1/8$ of the beam. To transmit the same fraction, bone must also present three of its own half-value layers, 3 × 1.0 cm = 3.0 cm. A 1.0-cm slab is a single HVL of bone and would transmit half the beam. The value 3.5 cm is the HVL of soft tissue, not a thickness of bone. The value 10.5 cm assumes equal thickness gives equal transmission, which ignores the difference in attenuation coefficients.',
        skill: '4D exponential attenuation and half-value layers (Skill 2)',
      },
      {
        question: 'The linear attenuation coefficient of soft tissue at 60 keV is closest to:',
        options: ['0.10 cm⁻¹', '0.14 cm⁻¹', '0.20 cm⁻¹', '0.29 cm⁻¹'],
        correctAnswer: 2,
        explanation:
          'From $\\text{HVL} = 0.693/\\mu$, $\\mu = 0.693/\\text{HVL} = 0.693/3.5\\ \\text{cm} \\approx 0.20\\ \\text{cm}^{-1}$. The value 0.29 cm⁻¹ is simply $1/3.5$, which omits the factor $\\ln 2$ that relates the HVL to the exponential constant. The value 0.14 cm⁻¹ uses 0.5 in place of 0.693. The value 0.10 cm⁻¹ divides by twice the HVL, as if two HVLs were needed to halve the beam.',
        skill: '4D relating the half-value layer to the attenuation coefficient (Skill 2)',
      },
      {
        question: 'Iodinated contrast agents make blood vessels visible on a radiograph primarily because iodine:',
        options: [
          'has a high atomic number, so it absorbs photons by the photoelectric effect far more strongly than tissue does',
          'has a high density of loosely bound electrons, so it scatters photons by the Compton process',
          'emits characteristic x-rays of its own that expose the detector lying beneath the vessel',
          'is far denser than tissue, so it reflects incoming photons back toward the x-ray source',
        ],
        correctAnswer: 0,
        explanation:
          'Photoelectric absorption scales roughly as $Z^3$, and iodine’s atomic number of 53 compared with tissue’s effective value of about 7.4 gives a per-atom probability hundreds of times greater; vessels filled with iodinated agent therefore remove far more photons than the surrounding tissue. Compton scattering depends on electron density, which differs far less among materials, and the passage attributes contrast mainly to the photoelectric process. Any characteristic x-rays iodine emits after absorption are low in energy and emitted in all directions; they do not create the shadow, and a vessel that exposed the detector more would appear darker, not opaque. Diagnostic photons are absorbed or scattered, not reflected like light from a mirror.',
        skill: '4D photoelectric absorption and atomic number (Skill 1)',
      },
      {
        question: 'Raising the tube voltage from 60 kV to 120 kV would be expected to reduce the contrast between bone and soft tissue because:',
        options: [
          'fewer photons are produced per second at the higher voltage, so the detector receives a weaker signal',
          'the tungsten characteristic lines shift to energies that bone and soft tissue absorb equally',
          'the half-value layer of soft tissue decreases with energy while that of bone is unchanged',
          'photoelectric absorption falls steeply with energy, leaving a process that varies little between tissues',
        ],
        correctAnswer: 3,
        explanation:
          'Doubling the voltage roughly doubles the typical photon energy, and the photoelectric probability falls as $1/E^3$, so the process that depends strongly on atomic number, and that distinguishes bone from soft tissue, contributes much less; Compton scattering, which depends on electron density and is similar for both, becomes dominant, and the two materials attenuate the beam more nearly alike. The number of photons is set by tube current, not voltage, and a weaker signal would affect brightness rather than the relative contrast. Characteristic lines are fixed by tungsten’s electron energy levels and do not shift with tube voltage. Half-value layers of both materials increase at higher energy; soft tissue does not become more absorbing.',
        skill: '4D energy dependence of photoelectric and Compton interactions (Skill 2)',
      },
    ],
  },
]

export const FL5_CHEM_PHYS_A_DISCRETES: MCATDiscreteQuestion[] = [
  {
    id: 'fl5-cp-a-d01',
    section: 'chem-phys',
    discipline: 'general chemistry',
    question: 'An enzyme accelerates the interconversion A ⇌ B by a factor of 10⁶ at 37 °C. Compared with the uncatalyzed reaction at the same temperature, the enzyme-catalyzed reaction has:',
    options: [
      'a lower activation energy and an unchanged equilibrium constant',
      'a lower activation energy and a larger equilibrium constant',
      'a more negative free-energy change and an unchanged activation energy',
      'an unchanged activation energy and a larger collision frequency',
    ],
    correctAnswer: 0,
    explanation:
      'A catalyst provides a pathway with a lower activation energy, which raises the rate constants of the forward and reverse reactions by the same factor; because the equilibrium constant is their ratio, it is unchanged, as is $\\Delta G$, which depends only on the states of reactants and products. A larger equilibrium constant would require the catalyst to change the free energies of A or B, which it cannot do. A more negative free-energy change is likewise impossible for a catalyst, which is not consumed and does not alter the thermodynamics. Collision frequency is set by concentration and temperature, and a catalyst acts by lowering the barrier, not by making molecules collide more often.',
    skill: '5E effect of a catalyst on rate and equilibrium (Skill 1)',
  },
  {
    id: 'fl5-cp-a-d02',
    section: 'chem-phys',
    discipline: 'general chemistry',
    question: 'At the same temperature and pressure, an unknown gas effuses through a small opening at half the rate of helium (molar mass 4.0 g/mol). The molar mass of the unknown gas is:',
    options: ['2.0 g/mol', '8.0 g/mol', '16 g/mol', '32 g/mol'],
    correctAnswer: 2,
    explanation:
      'By Graham’s law the rate of effusion is inversely proportional to the square root of molar mass, so $\\frac{r_{\\text{unknown}}}{r_{\\text{He}}} = \\sqrt{\\frac{M_{\\text{He}}}{M_{\\text{unknown}}}}$; a ratio of 1/2 requires $M_{\\text{unknown}} = 4 \\times 4.0 = 16$ g/mol, consistent with methane. A value of 8.0 g/mol treats the rate ratio as inversely proportional to molar mass itself, without the square root. A value of 32 g/mol squares the factor of four a second time. A value of 2.0 g/mol would effuse faster than helium, not slower.',
    skill: '4B Graham’s law of effusion (Skill 2)',
  },
  {
    id: 'fl5-cp-a-d03',
    section: 'chem-phys',
    discipline: 'general chemistry',
    question: 'A 25.0-mL sample of 0.120 M HCl is titrated with 0.150 M NaOH. What volume of the base is required to reach the equivalence point?',
    options: ['12.5 mL', '20.0 mL', '25.0 mL', '31.3 mL'],
    correctAnswer: 1,
    explanation:
      'At the equivalence point the moles of OH⁻ added equal the moles of H⁺ present: $(0.0250\\ \\text{L})(0.120\\ \\text{M}) = 3.00 \\times 10^{-3}$ mol, and $3.00 \\times 10^{-3}\\ \\text{mol}/0.150\\ \\text{M} = 0.0200$ L = 20.0 mL. The value 25.0 mL assumes equal volumes are always needed, which holds only when the concentrations are equal. The value 31.3 mL inverts the concentration ratio, multiplying 25.0 mL by 0.150/0.120. The value 12.5 mL halves the sample volume for no chemical reason.',
    skill: '5A strong acid–strong base titration stoichiometry (Skill 2)',
  },
  {
    id: 'fl5-cp-a-d04',
    section: 'chem-phys',
    discipline: 'physics',
    question: 'A 60-kg runner rounds a curve of radius 20 m at a constant speed of 5.0 m/s. The net horizontal force acting on the runner is:',
    options: [
      '15 N, directed toward the center of the curve',
      '75 N, directed toward the center of the curve',
      '75 N, directed away from the center of the curve',
      '300 N, directed toward the center of the curve',
    ],
    correctAnswer: 1,
    explanation:
      'An object moving in a circle at constant speed accelerates toward the center with $a = v^2/r = (5.0)^2/20 = 1.25\\ \\text{m/s}^2$, so the net horizontal force is $ma = (60)(1.25) = 75$ N, directed toward the center; it is supplied by friction between the shoes and the ground. A force directed outward is the fictitious centrifugal effect felt in the runner’s frame, not a real net force in the ground frame. The value 15 N uses $mv/r$ instead of $mv^2/r$. The value 300 N divides $mv^2$ by the speed rather than by the radius.',
    skill: '4A centripetal force in uniform circular motion (Skill 2)',
  },
  {
    id: 'fl5-cp-a-d05',
    section: 'chem-phys',
    discipline: 'physics',
    question: 'A pendulum bob is pulled aside until it is 0.20 m above its lowest point and released from rest. Ignoring air resistance, at what height above the lowest point is the bob’s speed equal to half of its maximum speed?',
    options: ['0.05 m', '0.10 m', '0.15 m', '0.20 m'],
    correctAnswer: 2,
    explanation:
      'Kinetic energy is proportional to the square of speed, so at half the maximum speed the bob has one quarter of its maximum kinetic energy; the other three quarters of the total mechanical energy is still potential, placing the bob at $0.75 \\times 0.20 = 0.15$ m above the lowest point. A height of 0.10 m is where half the energy is kinetic, which corresponds to a speed of $1/\\sqrt{2}$ of the maximum, not one half. A height of 0.05 m would mean three quarters of the energy is kinetic, giving a speed about 0.87 of the maximum. At 0.20 m the bob is at its release height and momentarily at rest.',
    skill: '4A energy conservation in a pendulum (Skill 2)',
  },
  {
    id: 'fl5-cp-a-d06',
    section: 'chem-phys',
    discipline: 'organic chemistry',
    question: 'In trans-1,4-dimethylcyclohexane:',
    options: [
      'the two chair conformations are equal in energy, each having one axial and one equatorial methyl',
      'the more stable chair places both methyls axial, where they lie anti to each other',
      'a ring flip interconverts the trans isomer and the cis isomer',
      'the more stable chair places both methyls equatorial, avoiding 1,3-diaxial strain',
    ],
    correctAnswer: 3,
    explanation:
      'In a 1,4-disubstituted cyclohexane the trans isomer has its two substituents either both axial or both equatorial, and a ring flip interconverts these two chairs; the diequatorial chair is more stable because axial methyl groups suffer 1,3-diaxial interactions with the axial hydrogens on the same face. A chair with one axial and one equatorial methyl is the cis-1,4 isomer, whose two chairs are indeed equal in energy, but that is not the trans isomer. Placing both methyls axial maximizes, rather than avoids, steric strain. A ring flip changes conformation only; converting cis to trans would require breaking a bond to invert a stereocenter.',
    skill: '5D chair conformations and 1,3-diaxial interactions (Skill 1)',
  },
  {
    id: 'fl5-cp-a-d07',
    section: 'chem-phys',
    discipline: 'biochemistry',
    question: 'A glutamine residue on the solvent-exposed surface of a protein is to be replaced by site-directed mutagenesis. Which substitution would best preserve the polarity and charge of the side chain at pH 7?',
    options: ['Glutamate', 'Leucine', 'Asparagine', 'Lysine'],
    correctAnswer: 2,
    explanation:
      'Glutamine has a polar, uncharged amide side chain, and asparagine is its closest relative, an amide side chain one methylene shorter, so it belongs to the same polar-uncharged class. Glutamate, despite the similar name, carries a carboxylate that is negatively charged at pH 7 and would introduce a charge where none existed. Leucine has a nonpolar hydrocarbon side chain and would be poorly tolerated at a solvent-exposed site. Lysine is positively charged at pH 7 and, like glutamate, changes the charge of the surface.',
    skill: '5D classification of amino acids by side chain (Skill 1)',
  },
  {
    id: 'fl5-cp-a-d08',
    section: 'chem-phys',
    discipline: 'biochemistry',
    question: 'Which of the following correctly describes how cytidine differs from cytosine?',
    options: [
      'Cytidine carries a phosphate group esterified to the 5′ carbon of a sugar',
      'Cytidine is the purine that pairs with guanine, whereas cytosine is a pyrimidine',
      'Cytidine contains a ribose joined to the base through an N-glycosidic bond',
      'Cytidine contains a deoxyribose but no phosphate, whereas cytosine contains ribose',
    ],
    correctAnswer: 2,
    explanation:
      'Cytosine is the free pyrimidine base; cytidine is the corresponding nucleoside, in which N-1 of the base is linked to C-1′ of ribose by an N-glycosidic bond. A phosphate esterified to the 5′ carbon would make the molecule a nucleotide, cytidine monophosphate, not the nucleoside. Both cytosine and cytidine contain the same pyrimidine base; neither is a purine. The nucleoside with deoxyribose is deoxycytidine, and the free base contains no sugar at all.',
    skill: '5D base versus nucleoside versus nucleotide (Skill 1)',
  },
]
