/**
 * Content patches for Algebra 2 topics:
 * - algebra2-exponential-functions (7 parts)
 * - algebra2-polynomial-operations (7 parts)
 * - algebra2-rational-expressions (7 parts)
 */
module.exports = {

'algebra2-exponential-functions': [
  { introContent: `\n# 📐 Exponential Growth\n\n**Part 1 of 7 — Exponential Growth**\n\n$$y = a \\cdot b^x \\quad (b > 1)$$\n\n- $a$ = initial value\n- $b$ = growth factor\n- Growth rate $r$: $b = 1 + r$\n\nExponential growth: each step multiplies by $b$.\n    `, workedContent: `\n## Worked Example\n\n**Population: 500, grows 10% per year. After 3 years?**\n\n$y = 500(1.10)^3 = 500(1.331) = 665.5$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Initial | Rate | Years | Formula |\n|---|---------|------|-------|---------|\n| 1 | 100 | 20% | 2 | 100(1.2)² |\n| 2 | 200 | 5% | 3 | 200(1.05)³ |\n| 3 | 1000 | 50% | 1 | 1000(1.5)¹ |\n    `,
    mcq1: { questions: [{ question: 'Growth factor for 20% growth rate?', options: ['1.2','0.2','20','1.02'], correctAnswer: 0, explanation: 'b = 1 + 0.20 = 1.2.' }] },
    mcq2: { questions: [{ question: 'In $y = a \\cdot b^x$, $a$ represents:', options: ['Initial value','Growth rate','Time','Final value'], correctAnswer: 0, explanation: 'a = starting amount.' }] },
    input: { boxes: 3, correctAnswers: ['144','1500','8'], content: `\n**Exponential Growth** 🧮\n\n1) $100(1.2)^2 = ?$\n\n2) $1000(1.5)^1 = ?$\n\n3) $y = 2^x$. When $x = 3$, $y = ?$\n    `, hint1: '100 × 1.44.', hint2: '1000 × 1.5.', hint3: '2³.', explanation: '1) 144. 2) 1500. 3) 8.' },
    dropdown: { dropdowns: [{ label: 'Exponential growth has b', options: ['Greater than 1','Less than 1','Equal to 1','Equal to 0'] }, { label: 'The growth factor includes', options: ['1 plus the rate','Just the rate','1 minus the rate','The rate squared'] }], correctAnswers: ['Greater than 1','1 plus the rate'], hint1: 'b > 1 for growth.', hint2: 'b = 1 + r.', explanation: 'Growth: b > 1. Growth factor = 1 + rate.' }
  },
  { introContent: `\n# 📊 Exponential Decay\n\n**Part 2 of 7 — Exponential Decay**\n\n$$y = a \\cdot b^x \\quad (0 < b < 1)$$\n\nDecay factor: $b = 1 - r$ (where $r$ is the decay rate)\n\n**Half-life**: time for the quantity to halve.\n    `, workedContent: `\n## Worked Example\n\n**Car: \\$20,000, depreciates 15%/year. Value after 2 years?**\n\n$y = 20000(0.85)^2 = 20000(0.7225) = 14450$ → **\\$14,450** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Initial | Rate | Years | Formula |\n|---|---------|------|-------|---------|\n| 1 | 1000 | 10% | 2 | 1000(0.9)² |\n| 2 | 500 | 50% | 1 | 500(0.5)¹ |\n| 3 | 800 | 25% | 2 | 800(0.75)² |\n    `,
    mcq1: { questions: [{ question: 'Decay factor for 10% decay rate?', options: ['0.9','1.1','0.1','10'], correctAnswer: 0, explanation: 'b = 1 − 0.10 = 0.9.' }] },
    mcq2: { questions: [{ question: 'After one half-life, ½ remains. After two?', options: ['1/4','0','1/3','1/2'], correctAnswer: 0, explanation: '½ × ½ = ¼.' }] },
    input: { boxes: 3, correctAnswers: ['810','250','450'], content: `\n**Exponential Decay** 🧮\n\n1) $1000(0.9)^2 = ?$\n\n2) $500(0.5)^1 = ?$\n\n3) $800(0.75)^2 = ?$\n    `, hint1: '1000 × 0.81.', hint2: '500 × 0.5.', hint3: '800 × 0.5625.', explanation: '1) 810. 2) 250. 3) 450.' },
    dropdown: { dropdowns: [{ label: 'Exponential decay has b', options: ['Between 0 and 1','Greater than 1','Equal to 1','Negative'] }, { label: 'Decay factor = 1 minus the', options: ['Rate','Initial value','Time','Exponent'] }], correctAnswers: ['Between 0 and 1','Rate'], hint1: '0 < b < 1.', hint2: 'b = 1 − r.', explanation: 'Decay: 0 < b < 1. Decay factor = 1 − rate.' }
  },
  { introContent: `\n# 🔢 Compound Interest\n\n**Part 3 of 7 — Compound Interest**\n\n$$A = P\\left(1 + \\frac{r}{n}\\right)^{nt}$$\n\n- $P$ = principal, $r$ = annual rate, $n$ = compounding frequency, $t$ = years\n\n**Continuous compounding**: $A = Pe^{rt}$\n    `, workedContent: `\n## Worked Example\n\n**\\$1000 at 6% compounded annually for 2 years.**\n\n$A = 1000(1.06)^2 = 1000(1.1236) = 1123.6$ → **\\$1,123.60** ✅\n    `, practiceContent: `\n## Practice\n\n| # | P | r | n | t | A |\n|---|---|---|---|---|---|\n| 1 | \\$1000 | 5% | 1 | 2 | \\$1102.50 |\n| 2 | \\$500 | 10% | 1 | 1 | \\$550 |\n| 3 | \\$2000 | 4% | 1 | 3 | \\$2249.73 |\n    `,
    mcq1: { questions: [{ question: '$500 at 10% compounded annually for 1 year:', options: ['$550','$510','$600','$5000'], correctAnswer: 0, explanation: '500(1.10) = 550.' }] },
    mcq2: { questions: [{ question: 'In $A = P(1+r/n)^{nt}$, $n$ represents:', options: ['Number of times compounded per year','Principal','Years','Rate'], correctAnswer: 0, explanation: 'n = compounding frequency.' }] },
    input: { boxes: 3, correctAnswers: ['550','1102.5','1060'], content: `\n**Compound Interest** 🧮\n\n1) $500 at 10%, 1 year, annual. A = ?\n\n2) $1000 at 5%, 2 years, annual. A = ?\n\n3) $1000 at 6%, 1 year, annual. A = ?\n    `, hint1: '500(1.10)¹.', hint2: '1000(1.05)².', hint3: '1000(1.06)¹.', explanation: '1) 550. 2) 1102.5. 3) 1060.' },
    dropdown: { dropdowns: [{ label: 'Compound interest means interest is earned on', options: ['Principal plus previously earned interest','Principal only','Interest only','Nothing'] }, { label: 'More frequent compounding gives', options: ['Slightly more money','Less money','The same amount','Much less money'] }], correctAnswers: ['Principal plus previously earned interest','Slightly more money'], hint1: 'Interest on interest.', hint2: 'More compounding = more growth.', explanation: 'Compound: interest on interest. More compounding → more return.' }
  },
  { introContent: `\n# 📈 Logarithms Introduction\n\n**Part 4 of 7 — Logarithms Introduction**\n\nA **logarithm** is the inverse of an exponential.\n\n$$\\log_b(x) = y \\iff b^y = x$$\n\n$\\log_2(8) = 3$ because $2^3 = 8$\n\n**Common log**: $\\log(x) = \\log_{10}(x)$\n**Natural log**: $\\ln(x) = \\log_e(x)$\n    `, workedContent: `\n## Worked Example\n\n$\\log_3(81) = ?$\n\n$3^? = 81$. Since $3^4 = 81$, $\\log_3(81) = 4$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Log | Value |\n|---|-----|-------|\n| 1 | $\\log_2(16)$ | 4 |\n| 2 | $\\log_5(25)$ | 2 |\n| 3 | $\\log_{10}(1000)$ | 3 |\n    `,
    mcq1: { questions: [{ question: '$\\log_2(16) = ?$', options: ['4','8','2','16'], correctAnswer: 0, explanation: '2⁴ = 16, so log₂(16) = 4.' }] },
    mcq2: { questions: [{ question: '$\\log_b(x) = y$ means:', options: ['$b^y = x$','$x^y = b$','$y^b = x$','$b^x = y$'], correctAnswer: 0, explanation: 'Log definition: b^y = x.' }] },
    input: { boxes: 3, correctAnswers: ['4','2','3'], content: `\n**Evaluate Logs** 🧮\n\n1) $\\log_2(16) = ?$\n\n2) $\\log_5(25) = ?$\n\n3) $\\log_{10}(1000) = ?$\n    `, hint1: '2 to what power = 16?', hint2: '5 to what power = 25?', hint3: '10 to what power = 1000?', explanation: '1) 2⁴=16→4. 2) 5²=25→2. 3) 10³=1000→3.' },
    dropdown: { dropdowns: [{ label: 'A logarithm is the inverse of', options: ['An exponential','Addition','Multiplication','A polynomial'] }, { label: '$\\log_b(1) =$', options: ['0','1','b','Undefined'] }], correctAnswers: ['An exponential','0'], hint1: 'Logs undo exponentials.', hint2: 'b⁰ = 1 for any b.', explanation: 'Logs are inverse of exponentials. log_b(1) = 0.' }
  },
  { introContent: `\n# 🧮 Log Properties\n\n**Part 5 of 7 — Log Properties**\n\n### Key Properties\n1. **Product**: $\\log_b(MN) = \\log_b(M) + \\log_b(N)$\n2. **Quotient**: $\\log_b\\left(\\frac{M}{N}\\right) = \\log_b(M) - \\log_b(N)$\n3. **Power**: $\\log_b(M^p) = p \\cdot \\log_b(M)$\n    `, workedContent: `\n## Worked Example\n\n$\\log_2(4 \\cdot 8) = \\log_2(4) + \\log_2(8) = 2 + 3 = 5$ ✅\n\nCheck: $4 \\times 8 = 32 = 2^5$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Property | Example |\n|---|---------|--------|\n| 1 | Product | $\\log(2)+\\log(5) = \\log(10) = 1$ |\n| 2 | Quotient | $\\log(100)-\\log(10) = \\log(10) = 1$ |\n| 3 | Power | $\\log(10^3) = 3$ |\n    `,
    mcq1: { questions: [{ question: '$\\log_2(4) + \\log_2(8) = ?$', options: ['5','6','24','32'], correctAnswer: 0, explanation: '2+3=5. Or log₂(32)=5.' }] },
    mcq2: { questions: [{ question: '$\\log_b(M^3)$ equals:', options: ['$3\\log_b(M)$','$\\log_b(3M)$','$M^3$','$3M$'], correctAnswer: 0, explanation: 'Power rule: exponent becomes coefficient.' }] },
    input: { boxes: 3, correctAnswers: ['5','1','3'], content: `\n**Log Properties** 🧮\n\n1) $\\log_2(4) + \\log_2(8) = ?$\n\n2) $\\log_{10}(100) - \\log_{10}(10) = ?$\n\n3) $\\log_{10}(10^3) = ?$\n    `, hint1: '2 + 3.', hint2: '2 − 1.', hint3: 'Power rule: bring down 3.', explanation: '1) 5. 2) 1. 3) 3.' },
    dropdown: { dropdowns: [{ label: '$\\log(MN) =$', options: ['$\\log(M) + \\log(N)$','$\\log(M) \\times \\log(N)$','$\\log(M) - \\log(N)$','$\\log(M^N)$'] }, { label: '$\\log(M/N) =$', options: ['$\\log(M) - \\log(N)$','$\\log(M) + \\log(N)$','$\\log(M) / \\log(N)$','$\\log(M \\cdot N)$'] }], correctAnswers: ['$\\log(M) + \\log(N)$','$\\log(M) - \\log(N)$'], hint1: 'Product rule.', hint2: 'Quotient rule.', explanation: 'Product: add logs. Quotient: subtract logs.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nApply exponential and logarithmic skills:\n- Doubling time problems\n- Real-world decay (depreciation, radioactive)\n- Solving exponential equations with logs\n    `, workedContent: `\n## Worked Example\n\n**\\$2000 at 8% annual. When does it double? (Rule of 72)**\n\n$72 \\div 8 = 9$ years (approximately) ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Answer |\n|---|---------|--------|\n| 1 | Doubling at 6%? | ~12 years |\n| 2 | $1000 ×(1.05)² | 1102.5 |\n| 3 | log₂(64) | 6 |\n    `,
    mcq1: { questions: [{ question: 'Rule of 72: doubling time at 6%?', options: ['12 years','6 years','72 years','7.2 years'], correctAnswer: 0, explanation: '72 ÷ 6 = 12 years.' }] },
    mcq2: { questions: [{ question: '$\\log_2(64) = ?$', options: ['6','8','32','4'], correctAnswer: 0, explanation: '2⁶ = 64.' }] },
    input: { boxes: 3, correctAnswers: ['12','1102.5','6'], content: `\n**Applications** 🧮\n\n1) Rule of 72: doubling at 6%. Years?\n\n2) $1000(1.05)^2 = ?$\n\n3) $\\log_2(64) = ?$\n    `, hint1: '72 ÷ 6.', hint2: '1000 × 1.1025.', hint3: '2 to what power equals 64?', explanation: '1) 12. 2) 1102.5. 3) 6.' },
    dropdown: { dropdowns: [{ label: 'The Rule of 72 estimates', options: ['Doubling time','Half-life','Interest rate','Principal'] }, { label: 'To solve $2^x = 64$, use', options: ['Logarithms','Addition','Multiplication','Square roots'] }], correctAnswers: ['Doubling time','Logarithms'], hint1: '72/rate.', hint2: 'Logs undo exponentials.', explanation: 'Rule of 72: doubling time. Solve exponential equations with logs.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Formulas\n- Growth: $y = a(1+r)^t$, Decay: $y = a(1-r)^t$\n- Compound interest: $A = P(1+r/n)^{nt}$\n- $\\log_b(x) = y \\iff b^y = x$\n- Product/Quotient/Power rules for logs\n    `, workedContent: `\n## Worked Example\n\n$\\log_3(27) + \\log_3(9) = 3 + 2 = 5 = \\log_3(243)$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Growth | 500(1.1)² |\n| 2 | Decay | 1000(0.5)³ |\n| 3 | Log | log₃(27) |\n    `,
    mcq1: { questions: [{ question: '$500(1.1)^2 = ?$', options: ['605','600','550','510'], correctAnswer: 0, explanation: '500 × 1.21 = 605.' }] },
    mcq2: { questions: [{ question: '$1000(0.5)^3 = ?$', options: ['125','500','250','62.5'], correctAnswer: 0, explanation: '1000 × 0.125 = 125.' }] },
    input: { boxes: 3, correctAnswers: ['605','125','3'], content: `\n**Review** 🧮\n\n1) $500(1.1)^2 = ?$\n\n2) $1000(0.5)^3 = ?$\n\n3) $\\log_3(27) = ?$\n    `, hint1: '500 × 1.21.', hint2: '1000 × 0.125.', hint3: '3³ = 27.', explanation: '1) 605. 2) 125. 3) 3.' },
    dropdown: { dropdowns: [{ label: '$b > 1$ in $y = ab^x$ means', options: ['Exponential growth','Exponential decay','Linear growth','No change'] }, { label: '$\\log_b(b) =$', options: ['1','0','b','Undefined'] }], correctAnswers: ['Exponential growth','1'], hint1: 'b > 1 → growing.', hint2: 'b¹ = b.', explanation: 'b>1 → growth. log_b(b) = 1.' }
  }
],

'algebra2-polynomial-operations': [
  { introContent: `\n# 📐 Adding & Subtracting Polynomials\n\n**Part 1 of 7 — Adding & Subtracting Polynomials**\n\nCombine **like terms** (same variable and exponent).\n\n$(3x^2 + 2x) + (5x^2 - x) = 8x^2 + x$\n\nFor subtraction: distribute the negative sign first.\n    `, workedContent: `\n## Worked Example\n\n$(4x^2 + 3x - 1) - (2x^2 - x + 5)$\n$= 4x^2 + 3x - 1 - 2x^2 + x - 5$\n$= 2x^2 + 4x - 6$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Operation | Result |\n|---|----------|--------|\n| 1 | $(3x+2)+(5x+1)$ | $8x+3$ |\n| 2 | $(x^2+4x)-(3x-2)$ | $x^2+x+2$ |\n| 3 | $(2x^2-1)+(x^2+3)$ | $3x^2+2$ |\n    `,
    mcq1: { questions: [{ question: '$(3x+2)+(5x+1) = ?$', options: ['$8x+3$','$15x+3$','$8x+2$','$15x+2$'], correctAnswer: 0, explanation: '3x+5x=8x. 2+1=3.' }] },
    mcq2: { questions: [{ question: 'When subtracting polynomials, first:', options: ['Distribute the negative sign','Add all terms','Multiply','Factor'], correctAnswer: 0, explanation: 'Distribute −1 to each term in the second polynomial.' }] },
    input: { boxes: 3, correctAnswers: ['8','3','2'], content: `\n**Add/Subtract Polynomials** 🧮\n\n$(3x + 2) + (5x + 1)$\n\n1) Coefficient of x?\n\n2) Constant term?\n\n$(2x^2 - 1) + (x^2 + 3)$\n\n3) Constant term?\n    `, hint1: '3 + 5.', hint2: '2 + 1.', hint3: '−1 + 3.', explanation: '1) 8. 2) 3. 3) 2.' },
    dropdown: { dropdowns: [{ label: 'Like terms have the same', options: ['Variable and exponent','Coefficient','Sign','Value'] }, { label: 'To subtract polynomials', options: ['Distribute the negative then combine like terms','Just subtract coefficients randomly','Multiply all terms','Ignore the second polynomial'] }], correctAnswers: ['Variable and exponent','Distribute the negative then combine like terms'], hint1: 'Same variable, same power.', hint2: 'Flip signs then add.', explanation: 'Like terms: same variable and power. Subtract: distribute −1.' }
  },
  { introContent: `\n# 📊 Multiplying Polynomials\n\n**Part 2 of 7 — Multiplying Polynomials**\n\nUse **FOIL** for binomials or **distribute** each term.\n\n$(a+b)(c+d) = ac + ad + bc + bd$\n\n**Special products:**\n- $(a+b)^2 = a^2 + 2ab + b^2$\n- $(a-b)(a+b) = a^2 - b^2$\n    `, workedContent: `\n## Worked Example\n\n$(2x + 3)(x - 4)$\n$= 2x^2 - 8x + 3x - 12$\n$= 2x^2 - 5x - 12$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Product | Result |\n|---|---------|--------|\n| 1 | $(x+2)(x+5)$ | $x^2+7x+10$ |\n| 2 | $(x+3)^2$ | $x^2+6x+9$ |\n| 3 | $(x-4)(x+4)$ | $x^2-16$ |\n    `,
    mcq1: { questions: [{ question: '$(x+2)(x+5) = ?$', options: ['$x^2+7x+10$','$x^2+10x+7$','$2x+7$','$x^2+10$'], correctAnswer: 0, explanation: 'FOIL: x²+5x+2x+10 = x²+7x+10.' }] },
    mcq2: { questions: [{ question: '$(x-4)(x+4) = ?$', options: ['$x^2-16$','$x^2-8$','$x^2+16$','$2x$'], correctAnswer: 0, explanation: 'Difference of squares: a²−b² = x²−16.' }] },
    input: { boxes: 3, correctAnswers: ['7','10','9'], content: `\n**Multiply** 🧮\n\n$(x+2)(x+5) = x^2 + ?x + ?$\n\n1) Coefficient of x?\n\n2) Constant term?\n\n$(x+3)^2 = x^2 + 6x + ?$\n\n3) Constant term?\n    `, hint1: '5+2.', hint2: '5×2.', hint3: '3².', explanation: '1) 7. 2) 10. 3) 9.' },
    dropdown: { dropdowns: [{ label: 'FOIL stands for', options: ['First, Outer, Inner, Last','Factor, Order, Identify, List','Find, Observe, Insert, Learn','None of these'] }, { label: '$(a+b)(a-b) =$', options: ['$a^2-b^2$','$a^2+b^2$','$2a$','$a^2-2ab+b^2$'] }], correctAnswers: ['First, Outer, Inner, Last','$a^2-b^2$'], hint1: 'Method for multiplying binomials.', hint2: 'Difference of squares.', explanation: 'FOIL: First/Outer/Inner/Last. (a+b)(a−b)=a²−b².' }
  },
  { introContent: `\n# 🔢 Factoring Review\n\n**Part 3 of 7 — Factoring Review**\n\n### Methods\n1. **GCF**: Factor out the greatest common factor\n2. **Trinomial**: $x^2 + bx + c = (x+m)(x+n)$ where $m+n=b$, $mn=c$\n3. **Difference of squares**: $a^2-b^2=(a+b)(a-b)$\n    `, workedContent: `\n## Worked Example\n\n$x^2 + 7x + 12 = ?$\n\nFind $m, n$: $m + n = 7$, $mn = 12$ → $m = 3, n = 4$\n\n$(x+3)(x+4)$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Factored |\n|---|-----------|----------|\n| 1 | $x^2+5x+6$ | $(x+2)(x+3)$ |\n| 2 | $x^2-9$ | $(x+3)(x-3)$ |\n| 3 | $2x^2+4x$ | $2x(x+2)$ |\n    `,
    mcq1: { questions: [{ question: '$x^2+5x+6 = ?$', options: ['$(x+2)(x+3)$','$(x+1)(x+6)$','$(x+5)(x+1)$','$(x-2)(x-3)$'], correctAnswer: 0, explanation: '2+3=5, 2×3=6.' }] },
    mcq2: { questions: [{ question: '$x^2-9 = ?$', options: ['$(x+3)(x-3)$','$(x-9)(x+1)$','$(x-3)^2$','Cannot be factored'], correctAnswer: 0, explanation: 'Difference of squares: x²−3².' }] },
    input: { boxes: 3, correctAnswers: ['2','3','3'], content: `\n**Factor** 🧮\n\n$x^2 + 5x + 6 = (x+?)(x+?)$\n\n1) Smaller number?\n\n2) Larger number?\n\n$x^2 - 9 = (x+?)(x-?)$\n\n3) The number?\n    `, hint1: 'Two numbers that add to 5 and multiply to 6.', hint2: 'The other of those two numbers.', hint3: '√9.', explanation: '1) 2. 2) 3. 3) 3.' },
    dropdown: { dropdowns: [{ label: '$a^2 - b^2$ factors as', options: ['$(a+b)(a-b)$','$(a-b)^2$','$(a+b)^2$','Cannot be factored'] }, { label: 'For $x^2+bx+c$, find two numbers that', options: ['Add to b and multiply to c','Add to c and multiply to b','Both equal b','Both equal c'] }], correctAnswers: ['$(a+b)(a-b)$','Add to b and multiply to c'], hint1: 'Difference of squares.', hint2: 'm+n=b, mn=c.', explanation: 'a²−b²=(a+b)(a−b). Trinomial: m+n=b, mn=c.' }
  },
  { introContent: `\n# 📈 Polynomial Division\n\n**Part 4 of 7 — Polynomial Division**\n\n**Long division** or **synthetic division** (for divisor $x - c$).\n\n$\\frac{x^2 + 3x + 2}{x + 1} = x + 2$\n    `, workedContent: `\n## Worked Example\n\n$(x^2 + 5x + 6) \\div (x + 2)$\n\n$= x + 3$ (since $(x+2)(x+3) = x^2+5x+6$) ✅\n    `, practiceContent: `\n## Practice\n\n| # | Division | Quotient |\n|---|---------|----------|\n| 1 | $(x^2+3x+2)÷(x+1)$ | $x+2$ |\n| 2 | $(x^2+5x+6)÷(x+2)$ | $x+3$ |\n| 3 | $(2x^2+6x)÷(2x)$ | $x+3$ |\n    `,
    mcq1: { questions: [{ question: '$(x^2+3x+2) \\div (x+1) = ?$', options: ['$x+2$','$x+3$','$x+1$','$x^2+2$'], correctAnswer: 0, explanation: '(x+1)(x+2) = x²+3x+2.' }] },
    mcq2: { questions: [{ question: 'Synthetic division can be used when dividing by:', options: ['$x - c$ (linear)','Any polynomial','Quadratics only','Constants only'], correctAnswer: 0, explanation: 'Synthetic division works with linear divisors.' }] },
    input: { boxes: 3, correctAnswers: ['2','3','3'], content: `\n**Polynomial Division** 🧮\n\n1) $(x^2+3x+2)÷(x+1) = x + ?$\n\n2) $(x^2+5x+6)÷(x+2) = x + ?$\n\n3) $(2x^2+6x)÷(2x) = x + ?$\n    `, hint1: 'Factor x²+3x+2.', hint2: 'Factor x²+5x+6.', hint3: 'Factor out 2x.', explanation: '1) x+2. 2) x+3. 3) x+3.' },
    dropdown: { dropdowns: [{ label: 'If $(x+a)$ divides $p(x)$ evenly, then', options: ['$p(-a) = 0$','$p(a) = 0$','$a = 0$','The degree decreases by 2'] }, { label: 'Polynomial long division is similar to', options: ['Long division with numbers','Addition','Factoring','Graphing'] }], correctAnswers: ['$p(-a) = 0$','Long division with numbers'], hint1: 'Factor theorem.', hint2: 'Same algorithm.', explanation: '(x+a)|p(x) → p(−a)=0. Same process as numerical long division.' }
  },
  { introContent: `\n# 🧮 Remainder Theorem\n\n**Part 5 of 7 — Remainder Theorem**\n\nWhen dividing $p(x)$ by $(x - c)$, the remainder equals $p(c)$.\n\nIf $p(c) = 0$, then $(x - c)$ is a **factor** of $p(x)$.\n    `, workedContent: `\n## Worked Example\n\n$p(x) = x^2 - 4x + 3$. Find $p(1)$.\n\n$p(1) = 1 - 4 + 3 = 0$ → $(x-1)$ is a factor! ✅\n    `, practiceContent: `\n## Practice\n\n| # | p(x) | c | p(c) |\n|---|------|---|------|\n| 1 | $x^2-4x+3$ | 1 | 0 |\n| 2 | $x^2+x-6$ | 2 | 0 |\n| 3 | $x^2+1$ | 1 | 2 |\n    `,
    mcq1: { questions: [{ question: '$p(x)=x^2+x-6$. $p(2)=?$', options: ['0','−4','8','2'], correctAnswer: 0, explanation: '4+2−6=0. So (x−2) is a factor.' }] },
    mcq2: { questions: [{ question: 'If $p(c) = 0$, then $(x-c)$ is:', options: ['A factor of p(x)','The remainder','Not related','The quotient'], correctAnswer: 0, explanation: 'Zero remainder → factor.' }] },
    input: { boxes: 3, correctAnswers: ['0','0','2'], content: `\n**Remainder Theorem** 🧮\n\n1) $p(x) = x^2 - 4x + 3$. $p(1) = ?$\n\n2) $p(x) = x^2 + x - 6$. $p(2) = ?$\n\n3) $p(x) = x^2 + 1$. $p(1) = ?$\n    `, hint1: '1 − 4 + 3.', hint2: '4 + 2 − 6.', hint3: '1 + 1.', explanation: '1) 0. 2) 0. 3) 2.' },
    dropdown: { dropdowns: [{ label: 'The remainder when dividing p(x) by (x−c) is', options: ['p(c)','p(0)','c','x'] }, { label: 'If the remainder is 0, (x−c) is a', options: ['Factor','Root','Quotient','Constant'] }], correctAnswers: ['p(c)','Factor'], hint1: 'Plug in c.', hint2: 'Divides evenly.', explanation: 'Remainder = p(c). If 0, (x−c) is a factor.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nSolve polynomial problems:\n- Model with polynomial expressions\n- Factor to find zeros\n- Use the remainder theorem to test factors\n    `, workedContent: `\n## Worked Example\n\n**Rectangle: length $(x+5)$, width $(x+2)$. Area?**\n\n$A = (x+5)(x+2) = x^2 + 7x + 10$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Expression |\n|---|---------|--------|\n| 1 | Area: $(x+3)(x+4)$ | $x^2+7x+12$ |\n| 2 | Volume: $x(x+1)(x+2)$ | $x^3+3x^2+2x$ |\n| 3 | Factor $x^2-1$ | $(x+1)(x-1)$ |\n    `,
    mcq1: { questions: [{ question: 'Area of rectangle $(x+3)$ by $(x+4)$?', options: ['$x^2+7x+12$','$2x+7$','$x^2+12$','$4x+12$'], correctAnswer: 0, explanation: 'FOIL: x²+4x+3x+12.' }] },
    mcq2: { questions: [{ question: '$x^2-1$ factors as:', options: ['$(x+1)(x-1)$','$(x-1)^2$','$(x+1)^2$','Cannot factor'], correctAnswer: 0, explanation: 'Difference of squares.' }] },
    input: { boxes: 3, correctAnswers: ['7','12','1'], content: `\n**Applications** 🧮\n\n$(x+3)(x+4) = x^2 + ?x + ?$\n\n1) Coefficient of x?\n\n2) Constant?\n\n$x^2 - 1 = (x+1)(x-?)$\n\n3) The number?\n    `, hint1: '3+4.', hint2: '3×4.', hint3: 'Difference of squares: 1²=1.', explanation: '1) 7. 2) 12. 3) 1.' },
    dropdown: { dropdowns: [{ label: 'The zeros of a polynomial are where', options: ['$p(x) = 0$','$p(x)$ is maximum','x = 0','The graph is steep'] }, { label: 'Area of a rectangle is', options: ['Length × Width','Length + Width','2(L+W)','L²'] }], correctAnswers: ['$p(x) = 0$','Length × Width'], hint1: 'x-intercepts.', hint2: 'Area = LW.', explanation: 'Zeros: p(x)=0. Area = L×W.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Concepts\n- Add/subtract: combine like terms\n- Multiply: FOIL or distribute\n- Factor: GCF, trinomial, difference of squares\n- Divide: long or synthetic division\n- Remainder theorem: $p(c)$ = remainder when $\\div (x-c)$\n    `, workedContent: `\n## Worked Example\n\n$x^2 - 5x + 6 = (x-2)(x-3)$\nZeros: $x = 2, 3$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | FOIL | $(x+1)(x+6)$ |\n| 2 | Factor | $x^2-5x+6$ |\n| 3 | Evaluate | $p(x)=x^2-1$, $p(3)$ |\n    `,
    mcq1: { questions: [{ question: '$(x+1)(x+6) = ?$', options: ['$x^2+7x+6$','$x^2+6x+1$','$2x+7$','$x^2+6$'], correctAnswer: 0, explanation: '1+6=7, 1×6=6.' }] },
    mcq2: { questions: [{ question: '$p(x)=x^2-1$. $p(3)=?$', options: ['8','10','2','0'], correctAnswer: 0, explanation: '9−1=8.' }] },
    input: { boxes: 3, correctAnswers: ['7','6','8'], content: `\n**Review** 🧮\n\n$(x+1)(x+6) = x^2 + ?x + ?$\n\n1) Coefficient of x?\n\n2) Constant?\n\n3) $p(x)=x^2-1$. $p(3) = ?$\n    `, hint1: '1+6.', hint2: '1×6.', hint3: '9−1.', explanation: '1) 7. 2) 6. 3) 8.' },
    dropdown: { dropdowns: [{ label: 'FOIL is used to multiply', options: ['Two binomials','Any polynomials','Monomials','Constants'] }, { label: 'The Factor Theorem says if $p(c)=0$ then', options: ['$(x-c)$ is a factor','c is the degree','$(x+c)$ is the quotient','p has no real zeros'] }], correctAnswers: ['Two binomials','$(x-c)$ is a factor'], hint1: 'Two terms × two terms.', hint2: 'Zero remainder.', explanation: 'FOIL: binomial × binomial. p(c)=0 → (x−c) is factor.' }
  }
],

'algebra2-rational-expressions': [
  { introContent: `\n# 📐 Simplifying Rational Expressions\n\n**Part 1 of 7 — Simplifying Rational Expressions**\n\nA rational expression is a fraction with polynomials:\n$\\frac{p(x)}{q(x)}$, $q(x) \\neq 0$\n\nSimplify by **factoring** and canceling common factors.\n\n$\\frac{x^2-4}{x+2} = \\frac{(x+2)(x-2)}{x+2} = x-2$\n    `, workedContent: `\n## Worked Example\n\n$\\frac{x^2-9}{x+3} = \\frac{(x+3)(x-3)}{x+3} = x-3$ ✅ (when $x \\neq -3$)\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Simplified |\n|---|-----------|------------|\n| 1 | $\\frac{x^2-4}{x+2}$ | $x-2$ |\n| 2 | $\\frac{2x}{4x^2}$ | $\\frac{1}{2x}$ |\n| 3 | $\\frac{x^2-1}{x-1}$ | $x+1$ |\n    `,
    mcq1: { questions: [{ question: '$\\frac{x^2-4}{x+2}$ simplifies to:', options: ['$x-2$','$x+2$','$x^2-2$','$x-4$'], correctAnswer: 0, explanation: 'Factor: (x+2)(x−2)/(x+2) = x−2.' }] },
    mcq2: { questions: [{ question: 'We cannot cancel terms that are:', options: ['Added (only factors cancel)','Multiplied','In the numerator','In parentheses'], correctAnswer: 0, explanation: 'Only factors (multiplication) can cancel.' }] },
    input: { boxes: 3, correctAnswers: ['-2','-3','1'], content: `\n**Simplify** 🧮\n\n$\\frac{x^2-4}{x+2} = x + ?$\n\n1) The constant?\n\n$\\frac{x^2-9}{x+3} = x + ?$\n\n2) The constant?\n\n$\\frac{x^2-1}{x-1} = x + ?$\n\n3) The constant?\n    `, hint1: '(x+2)(x−2)/(x+2).', hint2: '(x+3)(x−3)/(x+3).', hint3: '(x+1)(x−1)/(x−1).', explanation: '1) x−2. 2) x−3. 3) x+1.' },
    dropdown: { dropdowns: [{ label: 'To simplify a rational expression', options: ['Factor and cancel common factors','Cross multiply','Add numerators','Flip the fraction'] }, { label: 'A rational expression is undefined when the', options: ['Denominator equals zero','Numerator equals zero','Expression is negative','Variable is large'] }], correctAnswers: ['Factor and cancel common factors','Denominator equals zero'], hint1: 'Factor first.', hint2: 'Division by zero.', explanation: 'Factor then cancel. Undefined when denominator = 0.' }
  },
  { introContent: `\n# 📊 Multiplying & Dividing\n\n**Part 2 of 7 — Multiplying & Dividing**\n\n**Multiply**: $\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{ac}{bd}$ (factor and cancel first)\n\n**Divide**: multiply by the reciprocal\n$\\frac{a}{b} \\div \\frac{c}{d} = \\frac{a}{b} \\cdot \\frac{d}{c}$\n    `, workedContent: `\n## Worked Example\n\n$\\frac{x}{x+2} \\cdot \\frac{x+2}{x^2} = \\frac{x(x+2)}{x^2(x+2)} = \\frac{1}{x}$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Result |\n|---|---------|--------|\n| 1 | $\\frac{3}{x} \\cdot \\frac{x}{6}$ | $\\frac{1}{2}$ |\n| 2 | $\\frac{x}{3} \\div \\frac{x}{9}$ | $3$ |\n| 3 | $\\frac{x+1}{2} \\cdot \\frac{4}{x+1}$ | $2$ |\n    `,
    mcq1: { questions: [{ question: '$\\frac{3}{x} \\cdot \\frac{x}{6} = ?$', options: ['$\\frac{1}{2}$','$\\frac{3x}{6}$','$\\frac{18}{x^2}$','$3x$'], correctAnswer: 0, explanation: '3x/(6x) = 1/2.' }] },
    mcq2: { questions: [{ question: 'To divide fractions:', options: ['Multiply by the reciprocal','Multiply straight across','Add the denominators','Subtract the numerators'], correctAnswer: 0, explanation: 'Flip the second fraction and multiply.' }] },
    input: { boxes: 3, correctAnswers: ['0.5','3','2'], content: `\n**Multiply & Divide** 🧮\n\n1) $\\frac{3}{x} \\cdot \\frac{x}{6} = ?$ (decimal)\n\n2) $\\frac{x}{3} \\div \\frac{x}{9} = ?$\n\n3) $\\frac{x+1}{2} \\cdot \\frac{4}{x+1} = ?$\n    `, hint1: '3x/6x. Cancel x.', hint2: 'Flip: (x/3)(9/x). Cancel x.', hint3: 'Cancel (x+1). 4/2.', explanation: '1) 1/2=0.5. 2) 9/3=3. 3) 4/2=2.' },
    dropdown: { dropdowns: [{ label: 'Dividing by a fraction is the same as', options: ['Multiplying by its reciprocal','Dividing by its reciprocal','Adding it','Subtracting it'] }, { label: 'The reciprocal of $\\frac{a}{b}$ is', options: ['$\\frac{b}{a}$','$\\frac{a}{b}$','$-\\frac{a}{b}$','$ab$'] }], correctAnswers: ['Multiplying by its reciprocal','$\\frac{b}{a}$'], hint1: 'Flip and multiply.', hint2: 'Flip numerator and denominator.', explanation: 'Divide → multiply by reciprocal. Reciprocal: flip.' }
  },
  { introContent: `\n# 🔢 Adding & Subtracting\n\n**Part 3 of 7 — Adding & Subtracting**\n\nNeed a **common denominator**.\n\n$\\frac{a}{b} + \\frac{c}{d} = \\frac{ad + bc}{bd}$\n\n**LCD** (Least Common Denominator): smallest expression that both denominators divide into.\n    `, workedContent: `\n## Worked Example\n\n$\\frac{2}{x} + \\frac{3}{x} = \\frac{5}{x}$ ✅ (same denominator)\n\n$\\frac{1}{x} + \\frac{1}{x+1} = \\frac{(x+1) + x}{x(x+1)} = \\frac{2x+1}{x(x+1)}$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | LCD |\n|---|---------|-----|\n| 1 | $\\frac{3}{x}+\\frac{2}{x}$ | $x$ |\n| 2 | $\\frac{1}{2}+\\frac{1}{3}$ | $6$ |\n| 3 | $\\frac{1}{x}+\\frac{1}{2x}$ | $2x$ |\n    `,
    mcq1: { questions: [{ question: '$\\frac{3}{x} + \\frac{2}{x} = ?$', options: ['$\\frac{5}{x}$','$\\frac{5}{2x}$','$\\frac{6}{x^2}$','$5$'], correctAnswer: 0, explanation: 'Same denominator: 3/x + 2/x = 5/x.' }] },
    mcq2: { questions: [{ question: 'LCD of $\\frac{1}{x}$ and $\\frac{1}{2x}$ is:', options: ['$2x$','$x$','$2x^2$','$x^2$'], correctAnswer: 0, explanation: '2x is the smallest common denominator.' }] },
    input: { boxes: 3, correctAnswers: ['5','5','3'], content: `\n**Add/Subtract** 🧮\n\n1) $\\frac{3}{x} + \\frac{2}{x} = \\frac{?}{x}$ (numerator)\n\n2) $\\frac{1}{2} + \\frac{1}{3} = \\frac{?}{6}$ (numerator)\n\n3) $\\frac{1}{x} + \\frac{1}{2x} = \\frac{?}{2x}$ (numerator)\n    `, hint1: '3 + 2.', hint2: '3/6 + 2/6.', hint3: '2/2x + 1/2x.', explanation: '1) 5. 2) 3+2=5. 3) 2+1=3.' },
    dropdown: { dropdowns: [{ label: 'To add fractions with different denominators', options: ['Find a common denominator first','Just add the denominators','Multiply them','Skip the denominators'] }, { label: 'LCD stands for', options: ['Least Common Denominator','Last Common Divisor','Largest Common Denominator','Linear Common Degree'] }], correctAnswers: ['Find a common denominator first','Least Common Denominator'], hint1: 'Need matching bottoms.', hint2: 'Least = smallest.', explanation: 'Common denominator first. LCD = Least Common Denominator.' }
  },
  { introContent: `\n# 📈 Complex Fractions\n\n**Part 4 of 7 — Complex Fractions**\n\nA **complex fraction** has fractions in the numerator, denominator, or both.\n\n$$\\frac{\\frac{a}{b}}{\\frac{c}{d}} = \\frac{a}{b} \\cdot \\frac{d}{c} = \\frac{ad}{bc}$$\n\nAlternatively: multiply top and bottom by the LCD.\n    `, workedContent: `\n## Worked Example\n\n$\\frac{\\frac{1}{2}}{\\frac{3}{4}} = \\frac{1}{2} \\times \\frac{4}{3} = \\frac{4}{6} = \\frac{2}{3}$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Complex Fraction | Simplified |\n|---|-----------------|----------|\n| 1 | $\\frac{\\frac{2}{3}}{\\frac{4}{9}}$ | $\\frac{3}{2}$ |\n| 2 | $\\frac{\\frac{1}{x}}{\\frac{2}{x}}$ | $\\frac{1}{2}$ |\n| 3 | $\\frac{3}{\\frac{6}{5}}$ | $\\frac{5}{2}$ |\n    `,
    mcq1: { questions: [{ question: '$\\frac{\\frac{2}{3}}{\\frac{4}{9}} = ?$', options: ['$\\frac{3}{2}$','$\\frac{8}{27}$','$\\frac{2}{3}$','$6$'], correctAnswer: 0, explanation: '(2/3)(9/4) = 18/12 = 3/2.' }] },
    mcq2: { questions: [{ question: 'To simplify a complex fraction:', options: ['Multiply by the reciprocal of the denominator fraction','Add top and bottom','Subtract','Square both parts'], correctAnswer: 0, explanation: 'Main fraction ÷ bottom = multiply by reciprocal.' }] },
    input: { boxes: 3, correctAnswers: ['1.5','0.5','2.5'], content: `\n**Simplify Complex Fractions** 🧮 (decimal answers)\n\n1) $\\frac{\\frac{2}{3}}{\\frac{4}{9}} = ?$\n\n2) $\\frac{\\frac{1}{x}}{\\frac{2}{x}} = ?$\n\n3) $\\frac{3}{\\frac{6}{5}} = ?$\n    `, hint1: '(2/3) × (9/4).', hint2: '(1/x) × (x/2).', hint3: '3 × (5/6).', explanation: '1) 18/12=1.5. 2) 1/2=0.5. 3) 15/6=2.5.' },
    dropdown: { dropdowns: [{ label: 'A complex fraction has', options: ['Fractions within fractions','Only whole numbers','No denominator','Imaginary numbers'] }, { label: 'The key strategy for complex fractions is', options: ['Multiply by the reciprocal','Cross multiply','Add numerators','Ignore the inner fractions'] }], correctAnswers: ['Fractions within fractions','Multiply by the reciprocal'], hint1: 'Fractions in the numerator or denominator.', hint2: 'Flip and multiply.', explanation: 'Complex: fractions within fractions. Multiply by reciprocal.' }
  },
  { introContent: `\n# 🧮 Rational Equations\n\n**Part 5 of 7 — Rational Equations**\n\nTo solve: multiply both sides by the **LCD** to clear fractions.\n\n**Always check for extraneous solutions** (values making denominator = 0).\n    `, workedContent: `\n## Worked Example\n\n$\\frac{x}{3} = 4$\n\nMultiply by 3: $x = 12$ ✅\n\nCheck: $\\frac{12}{3} = 4$ ✓\n    `, practiceContent: `\n## Practice\n\n| # | Equation | Solution |\n|---|---------|----------|\n| 1 | $\\frac{x}{5} = 3$ | $x = 15$ |\n| 2 | $\\frac{2}{x} = 1$ | $x = 2$ |\n| 3 | $\\frac{x+1}{2} = 4$ | $x = 7$ |\n    `,
    mcq1: { questions: [{ question: '$\\frac{x}{5} = 3$. $x = ?$', options: ['15','3/5','8','5/3'], correctAnswer: 0, explanation: 'x = 3 × 5 = 15.' }] },
    mcq2: { questions: [{ question: 'Extraneous solutions are:', options: ['Solutions that make the denominator zero','Extra correct answers','The best answers','Never possible'], correctAnswer: 0, explanation: 'They appear as solutions but create division by zero.' }] },
    input: { boxes: 3, correctAnswers: ['15','2','7'], content: `\n**Solve Rational Equations** 🧮\n\n1) $\\frac{x}{5} = 3$. $x = ?$\n\n2) $\\frac{2}{x} = 1$. $x = ?$\n\n3) $\\frac{x+1}{2} = 4$. $x = ?$\n    `, hint1: 'Multiply both sides by 5.', hint2: 'Multiply both sides by x.', hint3: 'Multiply by 2: x+1=8.', explanation: '1) 15. 2) 2. 3) 7.' },
    dropdown: { dropdowns: [{ label: 'To solve a rational equation', options: ['Multiply both sides by the LCD','Cross out fractions','Add all denominators','Set everything equal to 1'] }, { label: 'After solving, always check for', options: ['Extraneous solutions','Extra variables','Perfect answers','Round numbers'] }], correctAnswers: ['Multiply both sides by the LCD','Extraneous solutions'], hint1: 'Clear fractions with LCD.', hint2: 'Values that make denominator 0.', explanation: 'Clear fractions with LCD. Check for extraneous solutions.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nApply rational expression skills:\n- Rate problems (work/time)\n- Mixture problems\n- Proportion problems\n    `, workedContent: `\n## Worked Example\n\n**Worker A: 6 hours alone. Worker B: 3 hours alone. Together?**\n\n$\\frac{1}{6} + \\frac{1}{3} = \\frac{1}{6} + \\frac{2}{6} = \\frac{3}{6} = \\frac{1}{2}$\n\nTogether: 2 hours ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Answer |\n|---|---------|--------|\n| 1 | A: 4h, B: 4h. Together? | 2h |\n| 2 | $\\frac{x}{2} = 6$. x = ? | 12 |\n| 3 | $\\frac{3}{x} = \\frac{1}{2}$. x = ? | 6 |\n    `,
    mcq1: { questions: [{ question: 'Worker A: 4h, Worker B: 4h. Together?', options: ['2 hours','8 hours','4 hours','1 hour'], correctAnswer: 0, explanation: '1/4 + 1/4 = 1/2. Time = 2h.' }] },
    mcq2: { questions: [{ question: '$\\frac{3}{x} = \\frac{1}{2}$. $x = ?$', options: ['6','3/2','2/3','1'], correctAnswer: 0, explanation: 'Cross multiply: 6 = x.' }] },
    input: { boxes: 3, correctAnswers: ['2','12','6'], content: `\n**Applications** 🧮\n\n1) Rate: A does job in 4h, B in 4h. Together in ? hours.\n\n2) $\\frac{x}{2} = 6$. $x = ?$\n\n3) $\\frac{3}{x} = \\frac{1}{2}$. $x = ?$\n    `, hint1: '1/4 + 1/4 = 1/2. Reciprocal?', hint2: '2 × 6.', hint3: 'Cross multiply: 3(2)=x(1).', explanation: '1) 2. 2) 12. 3) 6.' },
    dropdown: { dropdowns: [{ label: 'In work problems, rates are expressed as', options: ['1/(time to complete)','Time × jobs','Distance/speed','Jobs × workers'] }, { label: 'Combined rate = sum of individual rates when working', options: ['Together','Separately','In shifts','Neither'] }], correctAnswers: ['1/(time to complete)','Together'], hint1: 'Rate = 1/time.', hint2: 'Rates add when collaborating.', explanation: 'Rate = 1/t. Combined rate: add when working together.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Concepts\n- Simplify: factor and cancel\n- Multiply: across, after factoring\n- Divide: multiply by reciprocal\n- Add/subtract: find LCD\n- Complex fractions: multiply by reciprocal or LCD\n- Equations: clear fractions, check for extraneous solutions\n    `, workedContent: `\n## Worked Example\n\n$\\frac{x^2-1}{x+1} = \\frac{(x+1)(x-1)}{x+1} = x - 1$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Simplify | $\\frac{x^2-4}{x-2}$ |\n| 2 | Solve | $\\frac{x}{4} = 5$ |\n| 3 | Add | $\\frac{1}{3}+\\frac{1}{6}$ |\n    `,
    mcq1: { questions: [{ question: '$\\frac{x^2-4}{x-2} = ?$', options: ['$x+2$','$x-2$','$x^2-2$','$x+4$'], correctAnswer: 0, explanation: '(x+2)(x−2)/(x−2) = x+2.' }] },
    mcq2: { questions: [{ question: '$\\frac{x}{4} = 5$. $x = ?$', options: ['20','5/4','4/5','9'], correctAnswer: 0, explanation: 'x = 4 × 5 = 20.' }] },
    input: { boxes: 3, correctAnswers: ['2','20','0.5'], content: `\n**Review** 🧮\n\n$\\frac{x^2-4}{x-2} = x + ?$\n\n1) The constant?\n\n2) $\\frac{x}{4} = 5$. $x = ?$\n\n3) $\\frac{1}{3} + \\frac{1}{6} = ?$ (decimal)\n    `, hint1: '(x+2)(x−2)/(x−2).', hint2: '4 × 5.', hint3: '2/6 + 1/6.', explanation: '1) 2. 2) 20. 3) 3/6=0.5.' },
    dropdown: { dropdowns: [{ label: 'Only ______ can be canceled in fractions', options: ['Common factors','Common terms','Added terms','Constants'] }, { label: 'Extraneous solutions must be', options: ['Rejected','Accepted','Added','Doubled'] }], correctAnswers: ['Common factors','Rejected'], hint1: 'Factors, not terms.', hint2: 'They make denominator = 0.', explanation: 'Cancel factors only. Reject extraneous solutions.' }
  }
]

};
