/**
 * Content patches for AP Precalculus topics:
 * - apprecalc-polynomial-end-behavior (7 parts)
 * - apprecalc-rational-functions (7 parts)
 * - apprecalc-trig-modeling (7 parts)
 */
module.exports = {

'apprecalc-polynomial-end-behavior': [
  { introContent: `\n# 📐 Degree & Leading Coefficient\n\n**Part 1 of 7 — Degree & Leading Coefficient**\n\n- **Degree**: highest power of $x$\n- **Leading coefficient**: coefficient of the highest-degree term\n- These two values determine end behavior\n\nExample: $f(x) = -3x^4 + 2x^2 - 1$ → degree 4, leading coefficient $-3$\n    `, workedContent: `\n## Worked Example\n\n**$g(x) = 5x^3 - x + 7$**\n\nDegree = 3, Leading coefficient = 5 ✅\n    `, practiceContent: `\n## Practice\n\n| # | Polynomial | Degree | Leading Coeff |\n|---|-----------|--------|---------------|\n| 1 | $2x^5 - x$ | 5 | 2 |\n| 2 | $-x^2 + 3x + 1$ | 2 | −1 |\n| 3 | $4x^3 + x^2$ | 3 | 4 |\n    `,
    mcq1: { questions: [{ question: 'Degree of 7x⁴ − 3x + 2?', options: ['4','7','3','1'], correctAnswer: 0, explanation: 'Highest power is 4.' }] },
    mcq2: { questions: [{ question: 'Leading coefficient of −2x³ + 5x?', options: ['−2','5','3','−3'], correctAnswer: 0, explanation: 'Coefficient of x³ term.' }] },
    input: { boxes: 3, correctAnswers: ['5','2','4'], content: `\n**Identify Degree** 🧮\n\n1) $2x^5 - x$. Degree?\n\n2) $-x^2 + 3x$. Degree?\n\n3) $4x^3 + x^2 - 1$. Leading coefficient?\n    `, hint1: 'Highest exponent.', hint2: 'Highest power is x².', hint3: 'Coefficient of the x³ term.', explanation: '1) 5. 2) 2. 3) 4.' },
    dropdown: { dropdowns: [{ label: 'The degree is determined by the', options: ['Highest power of x','Number of terms','Leading coefficient','Constant term'] }, { label: 'The leading coefficient is the coefficient of', options: ['The highest-degree term','The first term written','The constant','The x term'] }], correctAnswers: ['Highest power of x','The highest-degree term'], hint1: 'Biggest exponent.', hint2: 'Attached to the highest power.', explanation: 'Degree = highest power. Leading coeff = coeff of that term.' }
  },
  { introContent: `\n# 📊 End Behavior Rules\n\n**Part 2 of 7 — End Behavior Rules**\n\n| Degree | Leading Coeff | Left | Right |\n|--------|--------------|------|-------|\n| Even | + | ↑ | ↑ |\n| Even | − | ↓ | ↓ |\n| Odd | + | ↓ | ↑ |\n| Odd | − | ↑ | ↓ |\n\nAs $x \\to \\pm\\infty$, only the leading term matters.\n    `, workedContent: `\n## Worked Example\n\n**$f(x) = -2x^3 + x$. End behavior?**\n\nOdd degree, negative leading coeff → Left ↑, Right ↓ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Polynomial | Left | Right |\n|---|-----------|------|-------|\n| 1 | $x^2$ | ↑ | ↑ |\n| 2 | $-x^3$ | ↑ | ↓ |\n| 3 | $x^4$ | ↑ | ↑ |\n    `,
    mcq1: { questions: [{ question: 'Even degree, positive leading coeff. End behavior?', options: ['Both ends up','Both ends down','Left down, right up','Left up, right down'], correctAnswer: 0, explanation: 'Even + positive → ↑↑.' }] },
    mcq2: { questions: [{ question: 'Odd degree, negative leading coeff. As x→∞?', options: ['f(x) → −∞','f(x) → +∞','f(x) → 0','Cannot tell'], correctAnswer: 0, explanation: 'Odd negative → right side goes down.' }] },
    input: { boxes: 3, correctAnswers: ['4','2','3'], content: `\n**End Behavior** 🧮\n\n1) $3x^4$: Degree?\n\n2) $-x^2 + 1$: Degree?\n\n3) $5x^3 - 2x$: Degree?\n    `, hint1: 'Highest exponent.', hint2: 'Highest power.', hint3: 'Highest power.', explanation: '1) 4 (even→both same). 2) 2 (even). 3) 3 (odd→opposite).' },
    dropdown: { dropdowns: [{ label: 'For x⁴, both ends go', options: ['Up','Down','Opposite directions','To zero'] }, { label: 'For −x³, the right end goes', options: ['Down','Up','To zero','Stays constant'] }], correctAnswers: ['Up','Down'], hint1: 'Even + positive.', hint2: 'Odd + negative → right ↓.', explanation: 'x⁴: even+positive→both up. −x³: odd+neg→right down.' }
  },
  { introContent: `\n# 🔢 Zeros & Multiplicity\n\n**Part 3 of 7 — Zeros & Multiplicity**\n\n- A **zero** (root) is where $f(x) = 0$\n- **Multiplicity**: how many times a factor repeats\n  - Odd multiplicity → graph **crosses** x-axis\n  - Even multiplicity → graph **bounces** off x-axis\n\n$f(x) = (x-2)^3(x+1)^2$ → zero at $x=2$ (mult. 3, cross), zero at $x=-1$ (mult. 2, bounce)\n    `, workedContent: `\n## Worked Example\n\n**$f(x) = (x-1)^2(x+3)$. Zeros?**\n\n$x = 1$ (multiplicity 2, bounces), $x = -3$ (multiplicity 1, crosses) ✅\n    `, practiceContent: `\n## Practice\n\n| # | Function | Zeros | Behavior |\n|---|---------|-------|----------|\n| 1 | $(x-4)^2$ | 4 | Bounce |\n| 2 | $(x+2)^3$ | −2 | Cross |\n| 3 | $(x-1)(x+1)^2$ | 1, −1 | Cross, Bounce |\n    `,
    mcq1: { questions: [{ question: 'Even multiplicity means the graph:', options: ['Bounces off the x-axis','Crosses the x-axis','Has no zero','Goes to infinity'], correctAnswer: 0, explanation: 'Even mult → tangent to axis → bounce.' }] },
    mcq2: { questions: [{ question: 'Zero of (x+5)³ is at x =', options: ['−5','5','3','−3'], correctAnswer: 0, explanation: 'Set x+5=0 → x=−5.' }] },
    input: { boxes: 3, correctAnswers: ['4','-2','1'], content: `\n**Find the Zeros** 🧮\n\n1) $(x-4)^2 = 0$. $x = $ ?\n\n2) $(x+2)^3 = 0$. $x = $ ?\n\n3) $(x-1)(x+1)^2 = 0$. One zero is $x = $ ?\n    `, hint1: 'x−4 = 0.', hint2: 'x+2 = 0.', hint3: 'x−1 = 0.', explanation: '1) x=4. 2) x=−2. 3) x=1 (or −1).' },
    dropdown: { dropdowns: [{ label: 'Multiplicity 2 means the factor appears', options: ['Twice','Once','Three times','Zero times'] }, { label: 'At a zero with odd multiplicity, the graph', options: ['Crosses the x-axis','Bounces','Has a hole','Is undefined'] }], correctAnswers: ['Twice','Crosses the x-axis'], hint1: 'Squared.', hint2: 'Odd → passes through.', explanation: 'Mult 2 = factor squared. Odd mult → crosses.' }
  },
  { introContent: `\n# 📈 Turning Points\n\n**Part 4 of 7 — Turning Points**\n\nA degree-$n$ polynomial has **at most** $n-1$ turning points.\n\n- **Local max**: graph goes from increasing to decreasing\n- **Local min**: graph goes from decreasing to increasing\n\nThe number of turning points is always $\\leq n - 1$.\n    `, workedContent: `\n## Worked Example\n\n**Degree 4 polynomial. Max turning points?**\n\n$4 - 1 = 3$ turning points max ✅\n    `, practiceContent: `\n## Practice\n\n| # | Degree | Max Turning Points |\n|---|--------|-------------------|\n| 1 | 3 | 2 |\n| 2 | 5 | 4 |\n| 3 | 2 | 1 |\n    `,
    mcq1: { questions: [{ question: 'Max turning points for degree 6?', options: ['5','6','7','4'], correctAnswer: 0, explanation: '6−1 = 5.' }] },
    mcq2: { questions: [{ question: 'A quadratic (degree 2) has at most ____ turning point(s):', options: ['1','2','0','3'], correctAnswer: 0, explanation: '2−1 = 1 (the vertex).' }] },
    input: { boxes: 3, correctAnswers: ['2','4','1'], content: `\n**Max Turning Points** 🧮\n\n1) Degree 3 → max turning points?\n\n2) Degree 5 → max turning points?\n\n3) Degree 2 → max turning points?\n    `, hint1: '3−1.', hint2: '5−1.', hint3: '2−1.', explanation: '1) 2. 2) 4. 3) 1.' },
    dropdown: { dropdowns: [{ label: 'A degree-n polynomial has at most ____ turning points', options: ['n−1','n','n+1','2n'] }, { label: 'A turning point is where the graph changes from', options: ['Increasing to decreasing or vice versa','Positive to negative','Linear to curved','One equation to another'] }], correctAnswers: ['n−1','Increasing to decreasing or vice versa'], hint1: 'One less than degree.', hint2: 'Direction change.', explanation: 'Max turning points = n−1. Turning = direction change.' }
  },
  { introContent: `\n# 🧮 Sketching Polynomials\n\n**Part 5 of 7 — Sketching Polynomials**\n\nSteps to sketch:\n1. Find the **degree** and **leading coefficient** → end behavior\n2. Find **zeros** and their multiplicities\n3. Find the **y-intercept** ($f(0)$)\n4. Plot key points and connect smoothly\n    `, workedContent: `\n## Worked Example\n\n**$f(x) = x^2 - 4 = (x-2)(x+2)$**\n\n- Degree 2, LC = 1 → both ends up\n- Zeros: $x = 2, -2$ (mult 1 each → cross)\n- y-int: $f(0) = -4$\n- Parabola opening up ✅\n    `, practiceContent: `\n## Practice\n\n| # | Function | y-intercept |\n|---|---------|-------------|\n| 1 | $x^2 - 9$ | −9 |\n| 2 | $x^3 - x$ | 0 |\n| 3 | $2x^2 + 1$ | 1 |\n    `,
    mcq1: { questions: [{ question: 'y-intercept of f(x) = x² − 9?', options: ['−9','9','0','3'], correctAnswer: 0, explanation: 'f(0) = 0 − 9 = −9.' }] },
    mcq2: { questions: [{ question: 'Zeros of x² − 4?', options: ['x = 2 and x = −2','x = 4','x = 0','No real zeros'], correctAnswer: 0, explanation: '(x−2)(x+2) = 0.' }] },
    input: { boxes: 3, correctAnswers: ['-9','0','1'], content: `\n**y-Intercepts** 🧮\n\nFind $f(0)$:\n\n1) $f(x) = x^2 - 9$\n\n2) $f(x) = x^3 - x$\n\n3) $f(x) = 2x^2 + 1$\n    `, hint1: '0² − 9.', hint2: '0³ − 0.', hint3: '2(0)² + 1.', explanation: '1) −9. 2) 0. 3) 1.' },
    dropdown: { dropdowns: [{ label: 'The y-intercept is found by setting', options: ['x = 0','y = 0','f(x) = 0','x = 1'] }, { label: 'Zeros are found by setting', options: ['f(x) = 0','x = 0','f(x) = 1','x = y'] }], correctAnswers: ['x = 0','f(x) = 0'], hint1: 'Evaluate at x=0.', hint2: 'Where the function equals zero.', explanation: 'y-intercept: x = 0. Zeros: f(x) = 0.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nCombine all concepts:\n- Identify degree, LC, end behavior\n- Find zeros and y-intercept\n- Determine turning points\n- Sketch the graph\n    `, workedContent: `\n## Worked Example\n\n**$f(x) = -x^3 + 4x$**\n\n- Degree 3, LC = −1 → left ↑, right ↓\n- $f(x) = -x(x^2-4) = -x(x-2)(x+2)$ → zeros: 0, 2, −2\n- Max turning points: 2\n- y-int: f(0) = 0 ✅\n    `, practiceContent: `\n## Practice\n\n| # | Concept | Problem |\n|---|---------|------|\n| 1 | End behavior | −2x⁴ |\n| 2 | Zeros | x²−1 |\n| 3 | Turning points | degree 4 |\n    `,
    mcq1: { questions: [{ question: 'End behavior of −2x⁴?', options: ['Both ends down','Both ends up','Left up, right down','Left down, right up'], correctAnswer: 0, explanation: 'Even degree + negative LC → ↓↓.' }] },
    mcq2: { questions: [{ question: 'Zeros of x²−1?', options: ['x=1 and x=−1','x=1 only','x=0','No real zeros'], correctAnswer: 0, explanation: '(x−1)(x+1)=0.' }] },
    input: { boxes: 3, correctAnswers: ['1','-1','3'], content: `\n**Combined Practice** 🧮\n\n1) One zero of $x^2 - 1$?\n\n2) The other zero of $x^2 - 1$?\n\n3) Max turning points for degree 4?\n    `, hint1: 'x−1=0.', hint2: 'x+1=0.', hint3: '4−1.', explanation: '1) 1. 2) −1. 3) 3.' },
    dropdown: { dropdowns: [{ label: '−2x⁴ has what end behavior?', options: ['Both ends down','Both ends up','Opposite ends','Cannot tell'] }, { label: 'x² − 1 factors as', options: ['(x−1)(x+1)','(x−1)²','x(x−1)','Cannot factor'] }], correctAnswers: ['Both ends down','(x−1)(x+1)'], hint1: 'Even + negative.', hint2: 'Difference of squares.', explanation: 'Even neg → both down. x²−1 = (x−1)(x+1).' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Concepts\n- Degree & LC → end behavior\n- Even mult → bounce; Odd mult → cross\n- Max turning points = degree − 1\n- y-intercept = f(0)\n    `, workedContent: `\n## Worked Example\n\n**$f(x) = 2x^3 - 6x$. Degree? LC? y-int?**\n\nDegree 3, LC = 2 (odd+pos → left↓ right↑), $f(0)=0$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Concept | Answer |\n|---|---------|--------|\n| 1 | Degree of 4x⁵ | 5 |\n| 2 | Max turning points for degree 5 | 4 |\n| 3 | y-int of 3x²−7 | −7 |\n    `,
    mcq1: { questions: [{ question: 'Max turning points for degree 5?', options: ['4','5','6','3'], correctAnswer: 0, explanation: '5−1=4.' }] },
    mcq2: { questions: [{ question: 'y-intercept of 3x²−7?', options: ['−7','3','7','0'], correctAnswer: 0, explanation: 'f(0)=0−7=−7.' }] },
    input: { boxes: 3, correctAnswers: ['5','4','-7'], content: `\n**Review** 🧮\n\n1) Degree of $4x^5 + x$?\n\n2) Max turning points for degree 5?\n\n3) y-intercept of $3x^2 - 7$?\n    `, hint1: 'Highest exponent.', hint2: '5−1.', hint3: 'f(0).', explanation: '1) 5. 2) 4. 3) −7.' },
    dropdown: { dropdowns: [{ label: 'End behavior depends on', options: ['Degree and leading coefficient','Number of terms','y-intercept','Zeros only'] }, { label: 'Odd multiplicity means the graph ____ the x-axis', options: ['Crosses','Bounces off','Does not touch','Is parallel to'] }], correctAnswers: ['Degree and leading coefficient','Crosses'], hint1: 'Two key properties.', hint2: 'Passes through.', explanation: 'End behavior: degree + LC. Odd mult → crosses.' }
  }
],

'apprecalc-rational-functions': [
  { introContent: `\n# 📐 Domain Restrictions\n\n**Part 1 of 7 — Domain Restrictions**\n\nA rational function is $f(x) = \\frac{p(x)}{q(x)}$ where $q(x) \\neq 0$.\n\n**Domain**: all real numbers except where the denominator = 0.\n\nSet $q(x) = 0$ and solve to find restrictions.\n    `, workedContent: `\n## Worked Example\n\n**$f(x) = \\frac{x+1}{x-3}$. Domain?**\n\n$x - 3 = 0 \\Rightarrow x = 3$\n\nDomain: all reals except $x = 3$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Function | Restriction |\n|---|---------|----------|\n| 1 | $\\frac{1}{x-5}$ | x ≠ 5 |\n| 2 | $\\frac{x}{x+2}$ | x ≠ −2 |\n| 3 | $\\frac{1}{x^2-4}$ | x ≠ ±2 |\n    `,
    mcq1: { questions: [{ question: 'Domain restriction for 1/(x−5)?', options: ['x ≠ 5','x ≠ −5','x ≠ 0','No restriction'], correctAnswer: 0, explanation: 'x−5=0 → x=5.' }] },
    mcq2: { questions: [{ question: 'How many restrictions for 1/(x²−4)?', options: ['2','1','0','4'], correctAnswer: 0, explanation: 'x²−4=0 → x=±2.' }] },
    input: { boxes: 3, correctAnswers: ['5','-2','2'], content: `\n**Domain Restrictions** 🧮\n\nFind where denominator = 0:\n\n1) $\\frac{1}{x-5}$. Restricted at $x = $ ?\n\n2) $\\frac{x}{x+2}$. Restricted at $x = $ ?\n\n3) $\\frac{1}{x^2-4}$. One restriction at $x = $ ?\n    `, hint1: 'x−5=0.', hint2: 'x+2=0.', hint3: 'x²−4=(x−2)(x+2)=0.', explanation: '1) 5. 2) −2. 3) 2 (also −2).' },
    dropdown: { dropdowns: [{ label: 'The domain of a rational function excludes values where', options: ['The denominator equals zero','The numerator equals zero','The function equals zero','x is negative'] }, { label: 'Division by zero is', options: ['Undefined','Zero','Infinity','One'] }], correctAnswers: ['The denominator equals zero','Undefined'], hint1: 'Cannot divide by zero.', hint2: 'Not a number.', explanation: 'Exclude denominator zeros. Division by zero is undefined.' }
  },
  { introContent: `\n# 📊 Vertical Asymptotes\n\n**Part 2 of 7 — Vertical Asymptotes**\n\nA **vertical asymptote** occurs at $x = a$ when:\n- The denominator equals zero at $x = a$\n- The factor does NOT cancel with the numerator\n\nThe graph approaches $\\pm\\infty$ near a vertical asymptote.\n    `, workedContent: `\n## Worked Example\n\n**$f(x) = \\frac{2}{x-4}$. Vertical asymptote?**\n\n$x - 4 = 0 \\Rightarrow x = 4$\n\nVertical asymptote at $x = 4$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Function | VA |\n|---|---------|----|\n| 1 | $\\frac{1}{x-3}$ | x = 3 |\n| 2 | $\\frac{x}{x+1}$ | x = −1 |\n| 3 | $\\frac{1}{(x-2)(x+5)}$ | x = 2, x = −5 |\n    `,
    mcq1: { questions: [{ question: 'VA of 1/(x−3)?', options: ['x = 3','x = −3','x = 0','No VA'], correctAnswer: 0, explanation: 'Denominator zero at x=3.' }] },
    mcq2: { questions: [{ question: 'Near a vertical asymptote, the graph:', options: ['Approaches ±∞','Crosses the axis','Becomes zero','Stays constant'], correctAnswer: 0, explanation: 'The function value grows without bound.' }] },
    input: { boxes: 3, correctAnswers: ['3','-1','2'], content: `\n**Vertical Asymptotes** 🧮\n\n1) $\\frac{1}{x-3}$. VA at $x = $ ?\n\n2) $\\frac{x}{x+1}$. VA at $x = $ ?\n\n3) $\\frac{1}{(x-2)(x+5)}$. One VA at $x = $ ?\n    `, hint1: 'x−3=0.', hint2: 'x+1=0.', hint3: 'x−2=0.', explanation: '1) 3. 2) −1. 3) 2 (also −5).' },
    dropdown: { dropdowns: [{ label: 'A vertical asymptote is a ____ line the graph approaches', options: ['Vertical','Horizontal','Diagonal','Curved'] }, { label: 'VAs occur where the denominator is zero and the factor', options: ['Does not cancel','Cancels','Is positive','Is negative'] }], correctAnswers: ['Vertical','Does not cancel'], hint1: 'x = constant.', hint2: 'Non-canceling zero.', explanation: 'VA = vertical line. Only if factor does not cancel.' }
  },
  { introContent: `\n# 🔢 Horizontal Asymptotes\n\n**Part 3 of 7 — Horizontal Asymptotes**\n\nCompare degrees of numerator ($n$) and denominator ($d$):\n\n| Condition | HA |\n|-----------|----|\n| $n < d$ | $y = 0$ |\n| $n = d$ | $y = \\frac{\\text{leading coefficients}}{\\text{ratio}}$ |\n| $n > d$ | No HA (oblique asymptote) |\n    `, workedContent: `\n## Worked Example\n\n**$f(x) = \\frac{3x^2}{x^2 + 1}$. HA?**\n\nDegrees equal (both 2). HA: $y = \\frac{3}{1} = 3$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Function | HA |\n|---|---------|----|\n| 1 | $\\frac{1}{x+1}$ | y = 0 |\n| 2 | $\\frac{2x}{x-3}$ | y = 2 |\n| 3 | $\\frac{4x^2}{2x^2+1}$ | y = 2 |\n    `,
    mcq1: { questions: [{ question: 'HA of 1/(x+1)?', options: ['y = 0','y = 1','y = −1','No HA'], correctAnswer: 0, explanation: 'Degree num (0) < degree den (1) → y=0.' }] },
    mcq2: { questions: [{ question: 'HA of 2x/(x−3)?', options: ['y = 2','y = 0','y = −3','No HA'], correctAnswer: 0, explanation: 'Equal degrees → ratio of LCs: 2/1=2.' }] },
    input: { boxes: 3, correctAnswers: ['0','2','2'], content: `\n**Horizontal Asymptotes** 🧮\n\n1) $\\frac{1}{x+1}$. HA: $y = $ ?\n\n2) $\\frac{2x}{x-3}$. HA: $y = $ ?\n\n3) $\\frac{4x^2}{2x^2+1}$. HA: $y = $ ?\n    `, hint1: 'Num degree < den degree.', hint2: 'Equal degrees: LC ratio.', hint3: '4/2.', explanation: '1) 0. 2) 2/1=2. 3) 4/2=2.' },
    dropdown: { dropdowns: [{ label: 'When numerator degree < denominator degree, HA is', options: ['y = 0','y = 1','No HA','y = leading coeff'] }, { label: 'When degrees are equal, HA equals', options: ['Ratio of leading coefficients','0','1','No HA'] }], correctAnswers: ['y = 0','Ratio of leading coefficients'], hint1: 'Smaller on top → approaches 0.', hint2: 'Compare the leading terms.', explanation: 'n<d → y=0. n=d → ratio of LCs.' }
  },
  { introContent: `\n# 📈 Holes in Graphs\n\n**Part 4 of 7 — Holes in Graphs**\n\nA **hole** occurs when a factor cancels from both numerator and denominator.\n\n$$f(x) = \\frac{(x-2)(x+1)}{(x-2)(x+3)}$$\n\nThe $(x-2)$ cancels → hole at $x = 2$.\n\nTo find the y-value of the hole, substitute into the simplified function.\n    `, workedContent: `\n## Worked Example\n\n**$f(x) = \\frac{(x-2)(x+1)}{(x-2)(x+3)}$. Hole?**\n\nCancel $(x-2)$: simplified = $\\frac{x+1}{x+3}$\n\nHole at $x=2$: $y = \\frac{2+1}{2+3} = \\frac{3}{5} = 0.6$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Function | Hole at |\n|---|---------|--------|\n| 1 | $\\frac{(x-3)(x+1)}{(x-3)(x-1)}$ | x = 3 |\n| 2 | $\\frac{x(x-5)}{x(x+2)}$ | x = 0 |\n    `,
    mcq1: { questions: [{ question: 'Hole in (x−3)(x+1)/[(x−3)(x−1)]?', options: ['x = 3','x = 1','x = −1','No hole'], correctAnswer: 0, explanation: '(x−3) cancels → hole at x=3.' }] },
    mcq2: { questions: [{ question: 'A hole occurs when a factor:', options: ['Cancels from both num and den','Only appears in the denominator','Only appears in the numerator','Equals 1'], correctAnswer: 0, explanation: 'Common factor cancels → hole.' }] },
    input: { boxes: 3, correctAnswers: ['3','0','0.6'], content: `\n**Holes** 🧮\n\n1) $\\frac{(x-3)(x+1)}{(x-3)(x-1)}$. Hole at $x = $ ?\n\n2) $\\frac{x(x-5)}{x(x+2)}$. Hole at $x = $ ?\n\n3) $\\frac{(x-2)(x+1)}{(x-2)(x+3)}$. y-value of hole?\n    `, hint1: 'Common factor x−3.', hint2: 'Common factor x.', hint3: 'Plug x=2 into simplified form.', explanation: '1) 3. 2) 0. 3) 3/5=0.6.' },
    dropdown: { dropdowns: [{ label: 'A hole appears as', options: ['An open circle on the graph','A vertical line','A horizontal line','A solid dot'] }, { label: 'To find the y-coordinate of a hole, use', options: ['The simplified function','The original function','The denominator only','x = 0'] }], correctAnswers: ['An open circle on the graph','The simplified function'], hint1: 'Point is missing.', hint2: 'After canceling.', explanation: 'Hole = open circle. Find y using simplified function.' }
  },
  { introContent: `\n# 🧮 Graphing Rational Functions\n\n**Part 5 of 7 — Graphing Rational Functions**\n\nSteps:\n1. Find **domain restrictions** (den = 0)\n2. Identify **holes** (cancel common factors)\n3. Find **VAs** (remaining den zeros)\n4. Find **HA** (compare degrees)\n5. Find **x-intercepts** (num = 0) and **y-intercept** ($f(0)$)\n6. Plot and connect\n    `, workedContent: `\n## Worked Example\n\n**$f(x) = \\frac{x+2}{x-1}$**\n\n- No common factors → no holes\n- VA: $x = 1$\n- HA: $y = 1$ (equal degrees, 1/1)\n- x-int: $x = -2$\n- y-int: $f(0) = \\frac{2}{-1} = -2$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Function | VA | HA | x-int |\n|---|---------|----|----|-------|\n| 1 | $\\frac{x}{x-2}$ | 2 | 1 | 0 |\n| 2 | $\\frac{3}{x+1}$ | −1 | 0 | none |\n    `,
    mcq1: { questions: [{ question: 'x-intercept of x/(x−2)?', options: ['x = 0','x = 2','x = −2','No x-int'], correctAnswer: 0, explanation: 'Numerator = 0 → x = 0.' }] },
    mcq2: { questions: [{ question: 'y-intercept of (x+2)/(x−1)?', options: ['−2','2','1','−1'], correctAnswer: 0, explanation: 'f(0) = 2/(−1) = −2.' }] },
    input: { boxes: 3, correctAnswers: ['2','1','0'], content: `\n**Graph $\\frac{x}{x-2}$** 🧮\n\n1) VA at $x = $ ?\n\n2) HA at $y = $ ?\n\n3) x-intercept at $x = $ ?\n    `, hint1: 'x−2=0.', hint2: 'Equal degrees: 1/1.', hint3: 'Numerator = 0.', explanation: '1) VA: x=2. 2) HA: y=1. 3) x-int: x=0.' },
    dropdown: { dropdowns: [{ label: 'x-intercepts are found by setting the ____ equal to zero', options: ['Numerator','Denominator','Entire function','Leading coefficient'] }, { label: 'The first step in graphing a rational function is to find', options: ['Domain restrictions','The y-intercept','The end behavior','The turning points'] }], correctAnswers: ['Numerator','Domain restrictions'], hint1: 'Top of the fraction.', hint2: 'Where is it undefined?', explanation: 'x-int: numerator=0. Start with domain restrictions.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nCombine all concepts for rational functions:\n- Domain, VAs, HAs, holes\n- Intercepts\n- Sketch the graph\n    `, workedContent: `\n## Worked Example\n\n**$f(x) = \\frac{2x}{x^2-1} = \\frac{2x}{(x-1)(x+1)}$**\n\n- VAs: $x = 1, x = -1$\n- HA: $y = 0$ (degree 1 < degree 2)\n- x-int: $x = 0$, y-int: $f(0) = 0$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Function | Analysis |\n|---|---------|----------|\n| 1 | $\\frac{x-3}{x+2}$ | VA: −2, HA: 1 |\n| 2 | $\\frac{4}{x^2}$ | VA: 0, HA: 0 |\n    `,
    mcq1: { questions: [{ question: 'VA of (x−3)/(x+2)?', options: ['x = −2','x = 3','x = 2','x = −3'], correctAnswer: 0, explanation: 'x+2=0 → x=−2.' }] },
    mcq2: { questions: [{ question: 'HA of (x−3)/(x+2)?', options: ['y = 1','y = 0','y = −3','No HA'], correctAnswer: 0, explanation: 'Equal degrees → 1/1=1.' }] },
    input: { boxes: 3, correctAnswers: ['-2','1','3'], content: `\n**Analyze $\\frac{x-3}{x+2}$** 🧮\n\n1) VA at $x = $ ?\n\n2) HA at $y = $ ?\n\n3) x-intercept at $x = $ ?\n    `, hint1: 'x+2=0.', hint2: 'LC ratio: 1/1.', hint3: 'x−3=0.', explanation: '1) −2. 2) 1. 3) 3.' },
    dropdown: { dropdowns: [{ label: 'When numerator degree > denominator degree, there is', options: ['No horizontal asymptote','HA at y=0','HA at y=1','Two HAs'] }, { label: 'A rational function with no common factors has ____ holes', options: ['Zero','One','Two','Infinite'] }], correctAnswers: ['No horizontal asymptote','Zero'], hint1: 'n>d → oblique instead.', hint2: 'No cancellation → no holes.', explanation: 'n>d → no HA (oblique). No common factors → no holes.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Concepts\n- Domain: exclude den = 0\n- VA: non-canceled den zeros\n- HA: compare degrees ($n<d$: y=0; $n=d$: LC ratio; $n>d$: none)\n- Holes: canceled common factors\n- x-int: num = 0; y-int: f(0)\n    `, workedContent: `\n## Worked Example\n\n**$\\frac{3x+6}{x+2} = \\frac{3(x+2)}{x+2}$**\n\nCommon factor → hole at $x=-2$, simplified: $y = 3$\n(Horizontal line with a hole) ✅\n    `, practiceContent: `\n## Practice\n\n| # | Topic | Problem |\n|---|-------|---------|\n| 1 | VA | $\\frac{5}{x-4}$ |\n| 2 | HA | $\\frac{2x}{3x+1}$ |\n| 3 | Hole | $\\frac{x(x-1)}{x(x+3)}$ |\n    `,
    mcq1: { questions: [{ question: 'HA of 2x/(3x+1)?', options: ['y = 2/3','y = 2','y = 3','y = 0'], correctAnswer: 0, explanation: 'Equal degrees → 2/3.' }] },
    mcq2: { questions: [{ question: 'Hole in x(x−1)/[x(x+3)]?', options: ['x = 0','x = 1','x = −3','No hole'], correctAnswer: 0, explanation: 'Factor x cancels → hole at x=0.' }] },
    input: { boxes: 3, correctAnswers: ['4','0.67','0'], content: `\n**Review** 🧮\n\n1) VA of $\\frac{5}{x-4}$ at $x = $ ?\n\n2) HA of $\\frac{2x}{3x+1}$ at $y = $ ? (round to hundredths)\n\n3) Hole of $\\frac{x(x-1)}{x(x+3)}$ at $x = $ ?\n    `, hint1: 'x−4=0.', hint2: '2/3.', hint3: 'Common factor x.', explanation: '1) 4. 2) 0.67. 3) 0.' },
    dropdown: { dropdowns: [{ label: 'A rational function is a ratio of', options: ['Polynomials','Integers','Constants','Exponents'] }, { label: 'The graph of a rational function never ____ a vertical asymptote', options: ['Crosses','Approaches','Is near','Is defined near'] }], correctAnswers: ['Polynomials','Crosses'], hint1: 'p(x)/q(x).', hint2: 'Undefined there.', explanation: 'Rational = polynomial/polynomial. Cannot cross a VA.' }
  }
],

'apprecalc-trig-modeling': [
  { introContent: `\n# 📐 Sine & Cosine Graphs\n\n**Part 1 of 7 — Sine & Cosine Graphs**\n\n$$y = A\\sin(Bx + C) + D$$\n\n- **A**: amplitude (vertical stretch)\n- **B**: affects period ($T = \\frac{2\\pi}{|B|}$)\n- **C**: phase shift\n- **D**: vertical shift (midline)\n\nSine starts at midline; cosine starts at maximum.\n    `, workedContent: `\n## Worked Example\n\n**$y = \\sin(x)$. Key features?**\n\nAmplitude = 1, Period = 2π, Midline: y = 0 ✅\n    `, practiceContent: `\n## Practice\n\n| # | Function | Amplitude | Period |\n|---|---------|-----------|--------|\n| 1 | sin(x) | 1 | 2π |\n| 2 | cos(x) | 1 | 2π |\n| 3 | 2sin(x) | 2 | 2π |\n    `,
    mcq1: { questions: [{ question: 'sin(0) = ?', options: ['0','1','−1','π'], correctAnswer: 0, explanation: 'Sine of 0 is 0.' }] },
    mcq2: { questions: [{ question: 'cos(0) = ?', options: ['1','0','−1','π'], correctAnswer: 0, explanation: 'Cosine of 0 is 1.' }] },
    input: { boxes: 3, correctAnswers: ['1','1','2'], content: `\n**Amplitude** 🧮\n\n1) Amplitude of $\\sin(x)$?\n\n2) Amplitude of $\\cos(x)$?\n\n3) Amplitude of $2\\sin(x)$?\n    `, hint1: 'Coefficient of sin.', hint2: 'Coefficient of cos.', hint3: 'Coefficient of sin.', explanation: '1) 1. 2) 1. 3) 2.' },
    dropdown: { dropdowns: [{ label: 'Sine starts at the', options: ['Midline going up','Maximum','Minimum','Origin only'] }, { label: 'Cosine starts at the', options: ['Maximum','Midline','Minimum','Zero'] }], correctAnswers: ['Midline going up','Maximum'], hint1: 'sin(0) = 0.', hint2: 'cos(0) = 1.', explanation: 'Sine: midline → up. Cosine: starts at max.' }
  },
  { introContent: `\n# 📊 Amplitude & Period\n\n**Part 2 of 7 — Amplitude & Period**\n\n- **Amplitude** = $|A|$ (distance from midline to max/min)\n- **Period** = $\\frac{2\\pi}{|B|}$ (one full cycle length)\n\nFor $y = 3\\sin(2x)$: amplitude = 3, period = $\\frac{2\\pi}{2} = \\pi$\n    `, workedContent: `\n## Worked Example\n\n**$y = 4\\cos(3x)$. Amplitude? Period?**\n\nAmplitude = 4, Period = $\\frac{2\\pi}{3} \\approx 2.09$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Function | Amplitude | Period |\n|---|---------|-----------|--------|\n| 1 | $3\\sin(2x)$ | 3 | π |\n| 2 | $5\\cos(x)$ | 5 | 2π |\n| 3 | $\\sin(4x)$ | 1 | π/2 |\n    `,
    mcq1: { questions: [{ question: 'Amplitude of 3sin(2x)?', options: ['3','2','6','1'], correctAnswer: 0, explanation: '|A| = 3.' }] },
    mcq2: { questions: [{ question: 'Period of sin(4x)?', options: ['π/2','4π','2π','π/4'], correctAnswer: 0, explanation: '2π/4 = π/2.' }] },
    input: { boxes: 3, correctAnswers: ['3','5','1'], content: `\n**Find Amplitude** 🧮\n\n1) $3\\sin(2x)$: Amplitude?\n\n2) $5\\cos(x)$: Amplitude?\n\n3) $\\sin(4x)$: Amplitude?\n    `, hint1: '|A| from y=A·sin(Bx).', hint2: 'Coefficient of cos.', hint3: 'No coefficient means 1.', explanation: '1) 3. 2) 5. 3) 1.' },
    dropdown: { dropdowns: [{ label: 'Period = 2π divided by', options: ['|B|','A','C','D'] }, { label: 'If B increases, the period', options: ['Decreases','Increases','Stays the same','Becomes zero'] }], correctAnswers: ['|B|','Decreases'], hint1: 'T = 2π/|B|.', hint2: 'Bigger B → smaller fraction.', explanation: 'Period = 2π/|B|. Larger B → shorter period.' }
  },
  { introContent: `\n# 🔢 Phase Shift\n\n**Part 3 of 7 — Phase Shift**\n\n$$y = A\\sin(B(x - h)) + D$$\n\n**Phase shift** = $h = -\\frac{C}{B}$ (horizontal shift)\n\n- Shift **right** when $h > 0$\n- Shift **left** when $h < 0$\n\n**Vertical shift** = $D$ (moves the midline)\n    `, workedContent: `\n## Worked Example\n\n**$y = \\sin(x - \\frac{\\pi}{4})$. Phase shift?**\n\nShift right by $\\frac{\\pi}{4}$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Function | Phase Shift |\n|---|---------|----------|\n| 1 | $\\sin(x - \\pi)$ | Right π |\n| 2 | $\\cos(x + \\frac{\\pi}{2})$ | Left π/2 |\n| 3 | $\\sin(x) + 3$ | No phase shift, up 3 |\n    `,
    mcq1: { questions: [{ question: 'Phase shift of sin(x − π)?', options: ['Right by π','Left by π','Up by π','Down by π'], correctAnswer: 0, explanation: 'x − π → shift right π.' }] },
    mcq2: { questions: [{ question: 'Vertical shift of sin(x) + 3?', options: ['Up 3','Down 3','Right 3','Left 3'], correctAnswer: 0, explanation: '+D shifts the midline up.' }] },
    input: { boxes: 3, correctAnswers: ['3','0','2'], content: `\n**Shifts** 🧮\n\n1) $\\sin(x) + 3$. Midline at $y = $ ?\n\n2) $\\sin(x - \\pi)$. Midline at $y = $ ?\n\n3) $\\cos(x) + 2$. Midline at $y = $ ?\n    `, hint1: 'D = 3.', hint2: 'No vertical shift.', hint3: 'D = 2.', explanation: '1) 3. 2) 0. 3) 2.' },
    dropdown: { dropdowns: [{ label: 'A phase shift moves the graph', options: ['Horizontally','Vertically','Both','Neither'] }, { label: 'sin(x − π/2) equals', options: ['−cos(x)','cos(x)','sin(x)','tan(x)'] }], correctAnswers: ['Horizontally','−cos(x)'], hint1: 'Left or right.', hint2: 'Sine shifted right by π/2.', explanation: 'Phase = horizontal shift. sin(x−π/2) = −cos(x).' }
  },
  { introContent: `\n# 📈 Modeling with Sinusoids\n\n**Part 4 of 7 — Modeling with Sinusoids**\n\nMany real-world phenomena are periodic:\n- Temperature over a year\n- Tides, daylight hours\n- Sound waves, pendulums\n\nTo model: find **amplitude** (half of max−min), **midline** (average of max and min), and **period** (time for one cycle).\n    `, workedContent: `\n## Worked Example\n\n**Temperature: max 90°F, min 30°F, period 12 months.**\n\n$A = \\frac{90-30}{2} = 30$, $D = \\frac{90+30}{2} = 60$\n$B = \\frac{2\\pi}{12} = \\frac{\\pi}{6}$\n\n$T(t) = 30\\sin\\left(\\frac{\\pi}{6}t\\right) + 60$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Max | Min | Amplitude | Midline |\n|---|-----|-----|-----------|--------|\n| 1 | 80 | 40 | 20 | 60 |\n| 2 | 100 | 20 | 40 | 60 |\n| 3 | 50 | 10 | 20 | 30 |\n    `,
    mcq1: { questions: [{ question: 'Max 80, min 40. Amplitude?', options: ['20','60','40','120'], correctAnswer: 0, explanation: '(80−40)/2 = 20.' }] },
    mcq2: { questions: [{ question: 'Max 80, min 40. Midline?', options: ['60','20','80','40'], correctAnswer: 0, explanation: '(80+40)/2 = 60.' }] },
    input: { boxes: 3, correctAnswers: ['20','40','20'], content: `\n**Find Amplitude** 🧮\n\nAmplitude = (max − min) / 2\n\n1) Max=80, min=40. Amplitude?\n\n2) Max=100, min=20. Amplitude?\n\n3) Max=50, min=10. Amplitude?\n    `, hint1: '(80−40)/2.', hint2: '(100−20)/2.', hint3: '(50−10)/2.', explanation: '1) 20. 2) 40. 3) 20.' },
    dropdown: { dropdowns: [{ label: 'The midline is the ____ of max and min', options: ['Average','Difference','Product','Sum'] }, { label: 'A sinusoidal model requires the data to be', options: ['Periodic','Linear','Exponential','Random'] }], correctAnswers: ['Average','Periodic'], hint1: '(max+min)/2.', hint2: 'Repeating pattern.', explanation: 'Midline = average. Data must be periodic for sinusoidal models.' }
  },
  { introContent: `\n# 🧮 Inverse Trig Functions\n\n**Part 5 of 7 — Inverse Trig Functions**\n\n- $\\sin^{-1}(x)$ or $\\arcsin(x)$: returns angle whose sine is $x$; range $[-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$\n- $\\cos^{-1}(x)$ or $\\arccos(x)$: range $[0, \\pi]$\n- $\\tan^{-1}(x)$ or $\\arctan(x)$: range $(-\\frac{\\pi}{2}, \\frac{\\pi}{2})$\n    `, workedContent: `\n## Worked Example\n\n**$\\sin^{-1}(1) = $ ?**\n\n$\\sin(\\frac{\\pi}{2}) = 1$ → $\\sin^{-1}(1) = \\frac{\\pi}{2} = 90°$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Value |\n|---|-----------|-------|\n| 1 | $\\sin^{-1}(0)$ | 0° |\n| 2 | $\\cos^{-1}(1)$ | 0° |\n| 3 | $\\tan^{-1}(1)$ | 45° |\n    `,
    mcq1: { questions: [{ question: 'sin⁻¹(0) = ?', options: ['0°','90°','180°','45°'], correctAnswer: 0, explanation: 'sin(0) = 0.' }] },
    mcq2: { questions: [{ question: 'cos⁻¹(0) = ?', options: ['90°','0°','180°','45°'], correctAnswer: 0, explanation: 'cos(90°) = 0.' }] },
    input: { boxes: 3, correctAnswers: ['0','0','45'], content: `\n**Inverse Trig** 🧮 (answer in degrees)\n\n1) $\\sin^{-1}(0) = $ ?\n\n2) $\\cos^{-1}(1) = $ ?\n\n3) $\\tan^{-1}(1) = $ ?\n    `, hint1: 'What angle has sin = 0?', hint2: 'What angle has cos = 1?', hint3: 'What angle has tan = 1?', explanation: '1) 0°. 2) 0°. 3) 45°.' },
    dropdown: { dropdowns: [{ label: 'The range of arcsin is', options: ['[−90°, 90°]','[0°, 180°]','[0°, 360°]','All reals'] }, { label: 'The range of arccos is', options: ['[0°, 180°]','[−90°, 90°]','[0°, 360°]','All reals'] }], correctAnswers: ['[−90°, 90°]','[0°, 180°]'], hint1: 'Restricted range for unique outputs.', hint2: 'Quadrants I and II.', explanation: 'arcsin: [−90°,90°]. arccos: [0°,180°].' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nApply all trig modeling concepts:\n- Read amplitude, period, shifts from a graph or description\n- Write a sinusoidal model\n- Evaluate inverse trig expressions\n    `, workedContent: `\n## Worked Example\n\n**Ferris wheel: radius 20 ft, center 25 ft high, period 60 sec.**\n\n$h(t) = -20\\cos\\left(\\frac{2\\pi}{60}t\\right) + 25 = -20\\cos\\left(\\frac{\\pi}{30}t\\right) + 25$ ✅\n\n(Negative cosine starts at the bottom)\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Type |\n|---|---------|------|\n| 1 | Max 70, min 30, period 12 | Model |\n| 2 | arctan(0) | Inverse trig |\n| 3 | Amplitude of 5sin(πx)+2 | Read graph |\n    `,
    mcq1: { questions: [{ question: 'Max 70, min 30. Midline?', options: ['50','40','20','100'], correctAnswer: 0, explanation: '(70+30)/2 = 50.' }] },
    mcq2: { questions: [{ question: 'arctan(0) = ?', options: ['0°','45°','90°','180°'], correctAnswer: 0, explanation: 'tan(0) = 0.' }] },
    input: { boxes: 3, correctAnswers: ['50','20','5'], content: `\n**Applications** 🧮\n\nMax = 70, min = 30:\n\n1) Midline?\n\n2) Amplitude?\n\n3) Amplitude of $5\\sin(\\pi x) + 2$?\n    `, hint1: '(70+30)/2.', hint2: '(70−30)/2.', hint3: 'Coefficient of sin.', explanation: '1) 50. 2) 20. 3) 5.' },
    dropdown: { dropdowns: [{ label: 'A Ferris wheel is modeled with ____ because it is periodic', options: ['A sinusoidal function','A linear function','A polynomial','An exponential'] }, { label: '−cos starts at the', options: ['Minimum','Maximum','Midline','Zero'] }], correctAnswers: ['A sinusoidal function','Minimum'], hint1: 'Repeating circular motion.', hint2: '−cos(0) = −1.', explanation: 'Ferris wheel → sinusoidal. −cos starts at minimum.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Formulas\n- $y = A\\sin(B(x-h)) + D$\n- Amplitude = $|A|$\n- Period = $2\\pi / |B|$\n- Phase shift = $h$\n- Midline = $D$\n- Amplitude = (max−min)/2\n- Midline = (max+min)/2\n    `, workedContent: `\n## Worked Example\n\n**$y = 3\\sin(2x) + 1$**\n\nA=3, B=2, D=1. Amplitude=3, Period=π, Midline: y=1 ✅\n    `, practiceContent: `\n## Practice\n\n| # | Topic | Problem |\n|---|-------|---------|\n| 1 | Amplitude | $y = 4\\cos(x)$ |\n| 2 | Period of $\\sin(3x)$ | 2π/3 |\n| 3 | arcsin(1) | 90° |\n    `,
    mcq1: { questions: [{ question: 'Amplitude of 4cos(x)?', options: ['4','1','8','0'], correctAnswer: 0, explanation: '|A| = 4.' }] },
    mcq2: { questions: [{ question: 'Period of sin(3x)?', options: ['2π/3','3π','6π','π/3'], correctAnswer: 0, explanation: '2π/3.' }] },
    input: { boxes: 3, correctAnswers: ['4','90','1'], content: `\n**Review** 🧮\n\n1) Amplitude of $4\\cos(x)$?\n\n2) $\\sin^{-1}(1)$ in degrees?\n\n3) Midline of $\\sin(x) + 1$?\n    `, hint1: '|A|.', hint2: 'sin(90°)=1.', hint3: 'D=1.', explanation: '1) 4. 2) 90. 3) 1.' },
    dropdown: { dropdowns: [{ label: 'The period formula is', options: ['2π/|B|','2π·B','A/B','B/2π'] }, { label: 'Increasing |A| makes the graph', options: ['Taller (vertically stretched)','Wider','Shorter','Narrower'] }], correctAnswers: ['2π/|B|','Taller (vertically stretched)'], hint1: 'Divide 2π by |B|.', hint2: 'Amplitude = height.', explanation: 'Period = 2π/|B|. Larger |A| → taller graph.' }
  }
]

};
