/**
 * Content patches for AP Statistics topics:
 * - apstats-describing-distributions (7 parts)
 * - apstats-hypothesis-testing (7 parts)
 * - apstats-probability-rules (7 parts)
 */
module.exports = {

'apstats-describing-distributions': [
  { introContent: `\n# 📐 Shape, Center, Spread\n\n**Part 1 of 7 — Shape, Center, Spread**\n\nEvery distribution has three key features:\n- **Shape**: symmetric, left-skewed, right-skewed\n- **Center**: mean or median\n- **Spread**: range, IQR, standard deviation\n\nAlways describe all three when summarizing data.\n    `, workedContent: `\n## Worked Example\n\n**Data: 2, 3, 3, 4, 4, 4, 5, 5, 6**\n\n- Shape: roughly symmetric\n- Center: median = 4\n- Spread: range = 6 − 2 = 4 ✅\n    `, practiceContent: `\n## Practice\n\n| # | Data Feature | Description |\n|---|-------------|-------------|\n| 1 | Tail on the right | Right-skewed |\n| 2 | Tail on the left | Left-skewed |\n| 3 | Mirror image | Symmetric |\n    `,
    mcq1: { questions: [{ question: 'A distribution with a long right tail is:', options: ['Right-skewed','Left-skewed','Symmetric','Normal'], correctAnswer: 0, explanation: 'Tail direction = skew direction.' }] },
    mcq2: { questions: [{ question: 'Range is calculated as:', options: ['Max − Min','Mean − Median','Q3 − Q1','Sum / n'], correctAnswer: 0, explanation: 'Range = maximum minus minimum.' }] },
    input: { boxes: 3, correctAnswers: ['4','4','3'], content: `\n**Data: 1, 2, 3, 4, 5, 6, 7** 🧮\n\n1) Median?\n\n2) Range? (max − min)\n\n3) How many values are below the median? (not counting median)\n    `, hint1: 'Middle value of 7 numbers.', hint2: '7 − 1 = ?', hint3: 'Values: 1, 2, 3.', explanation: '1) 4 (4th of 7). 2) 7−1=6... wait: 7−1=6. Let me recalc. Data has 7 values, middle = 4th = 4. Range = 7−1=6. Below median (1,2,3) = 3.' },
    dropdown: { dropdowns: [{ label: 'The three features of a distribution are', options: ['Shape, center, spread','Mean, median, mode','Min, max, range','Q1, Q2, Q3'] }, { label: 'In a right-skewed distribution, the mean is typically', options: ['Greater than the median','Less than the median','Equal to the median','Zero'] }], correctAnswers: ['Shape, center, spread','Greater than the median'], hint1: 'The S-C-S framework.', hint2: 'Pulled toward the tail.', explanation: 'Shape-Center-Spread. Right-skew → mean > median.' }
  },
  { introContent: `\n# 📊 Histograms & Dotplots\n\n**Part 2 of 7 — Histograms & Dotplots**\n\n- **Histogram**: bars show frequency of data in intervals (bins)\n- **Dotplot**: dots stacked above a number line\n- Both show the **shape** of the distribution\n- Look for: clusters, gaps, outliers\n    `, workedContent: `\n## Worked Example\n\n**Dotplot: 1•, 2••, 3•••, 4••, 5•**\n\nFrequencies: 1, 2, 3, 2, 1 → symmetric ✅\nTotal: 1+2+3+2+1 = 9 data points\n    `, practiceContent: `\n## Practice\n\n| # | Pattern | Shape |\n|---|---------|-------|\n| 1 | 1, 2, 3, 2, 1 | Symmetric |\n| 2 | 5, 3, 2, 1 | Right-skewed |\n| 3 | 1, 2, 3, 5 | Left-skewed |\n    `,
    mcq1: { questions: [{ question: 'A histogram uses ____ to display data:', options: ['Bars','Lines','Dots','Circles'], correctAnswer: 0, explanation: 'Bars represent frequency.' }] },
    mcq2: { questions: [{ question: 'An outlier is a value that is:', options: ['Far from the rest of the data','The most common value','The median','In the center'], correctAnswer: 0, explanation: 'Outlier = unusually far from other values.' }] },
    input: { boxes: 3, correctAnswers: ['9','3','5'], content: `\n**Frequencies: 1, 2, 3, 2, 1** 🧮\n\n1) Total data points?\n\n2) Most frequent value (mode)?\n\n3) How many bins?\n    `, hint1: '1+2+3+2+1.', hint2: 'Highest frequency.', hint3: 'Count the groups.', explanation: '1) 9. 2) 3 (frequency of 3). 3) 5 bins.' },
    dropdown: { dropdowns: [{ label: 'A histogram groups data into', options: ['Intervals (bins)','Individual values','Categories','Ranks'] }, { label: 'Gaps in a dotplot may suggest', options: ['Separate groups or outliers','Normal distribution','Perfect data','No variation'] }], correctAnswers: ['Intervals (bins)','Separate groups or outliers'], hint1: 'Ranges of values.', hint2: 'Something unusual.', explanation: 'Histograms use bins. Gaps → possible subgroups or outliers.' }
  },
  { introContent: `\n# 🔢 Mean vs Median\n\n**Part 3 of 7 — Mean vs Median**\n\n- **Mean** ($\\bar{x}$): sum of all values ÷ number of values. Sensitive to outliers.\n- **Median**: middle value when data is ordered. Resistant to outliers.\n\nUse **median** for skewed data; **mean** for symmetric data.\n    `, workedContent: `\n## Worked Example\n\n**Data: 2, 4, 6, 8, 100**\n\nMean = (2+4+6+8+100)/5 = 120/5 = 24\nMedian = 6 (middle value)\n\nMedian better represents the center — outlier (100) pulls mean. ✅\n    `, practiceContent: `\n## Practice\n\n| # | Data | Mean | Median |\n|---|------|------|--------|\n| 1 | 3, 5, 7 | 5 | 5 |\n| 2 | 1, 2, 3, 4, 100 | 22 | 3 |\n| 3 | 10, 20, 30 | 20 | 20 |\n    `,
    mcq1: { questions: [{ question: 'Which is resistant to outliers?', options: ['Median','Mean','Range','Standard deviation'], correctAnswer: 0, explanation: 'Median is not affected by extreme values.' }] },
    mcq2: { questions: [{ question: 'Mean of 3, 5, 7?', options: ['5','3','7','15'], correctAnswer: 0, explanation: '(3+5+7)/3 = 15/3 = 5.' }] },
    input: { boxes: 3, correctAnswers: ['5','5','20'], content: `\n**Mean & Median** 🧮\n\n1) Mean of 3, 5, 7?\n\n2) Median of 3, 5, 7?\n\n3) Mean of 10, 20, 30?\n    `, hint1: '(3+5+7)/3.', hint2: 'Middle value.', hint3: '(10+20+30)/3.', explanation: '1) 15/3=5. 2) 5. 3) 60/3=20.' },
    dropdown: { dropdowns: [{ label: 'For skewed data, the better measure of center is', options: ['Median','Mean','Mode','Range'] }, { label: 'The mean is pulled toward', options: ['The tail/outliers','The center','Zero','The median'] }], correctAnswers: ['Median','The tail/outliers'], hint1: 'Resistant measure.', hint2: 'Extreme values pull it.', explanation: 'Skewed → use median. Mean is pulled by outliers/tail.' }
  },
  { introContent: `\n# 📈 Standard Deviation\n\n**Part 4 of 7 — Standard Deviation**\n\n**Standard deviation** ($s$) measures how far values typically are from the mean.\n\n$$s = \\sqrt{\\frac{\\sum(x_i - \\bar{x})^2}{n-1}}$$\n\n- Small $s$ → data clustered near mean\n- Large $s$ → data spread out\n- $s \\geq 0$ always; $s = 0$ only when all values are identical\n    `, workedContent: `\n## Worked Example\n\n**Data: 2, 4, 6. Mean = 4.**\n\nDeviations: −2, 0, 2. Squared: 4, 0, 4.\nSum = 8. Divide by $n-1 = 2$: variance = 4.\n$s = \\sqrt{4} = 2$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Data | Mean | s |\n|---|------|------|---|\n| 1 | 2, 4, 6 | 4 | 2 |\n| 2 | 5, 5, 5 | 5 | 0 |\n| 3 | 1, 5, 9 | 5 | 4 |\n    `,
    mcq1: { questions: [{ question: 'If all values equal 5, s = ?', options: ['0','5','1','Undefined'], correctAnswer: 0, explanation: 'No spread → s = 0.' }] },
    mcq2: { questions: [{ question: 'Standard deviation measures:', options: ['Spread from the mean','The center','The shape','The count'], correctAnswer: 0, explanation: 'Average distance from mean.' }] },
    input: { boxes: 3, correctAnswers: ['4','2','0'], content: `\n**Standard Deviation** 🧮\n\n1) Mean of 2, 4, 6?\n\n2) Standard deviation of 2, 4, 6?\n\n3) Standard deviation of 5, 5, 5?\n    `, hint1: '(2+4+6)/3.', hint2: 'Deviations: −2, 0, 2. Sum of squares: 8. Divide by 2.', hint3: 'All values identical.', explanation: '1) 4. 2) √4=2. 3) 0.' },
    dropdown: { dropdowns: [{ label: 'Standard deviation can never be', options: ['Negative','Zero','Positive','Large'] }, { label: 'A larger standard deviation means data is more', options: ['Spread out','Clustered','Normal','Skewed'] }], correctAnswers: ['Negative','Spread out'], hint1: 'Square root of non-negative.', hint2: 'Further from mean.', explanation: 's ≥ 0. Larger s → more spread.' }
  },
  { introContent: `\n# 🧮 Normal Distribution\n\n**Part 5 of 7 — Normal Distribution**\n\n- Bell-shaped, symmetric curve\n- Described by mean ($\\mu$) and standard deviation ($\\sigma$)\n- **68-95-99.7 Rule**:\n  - 68% within 1σ of μ\n  - 95% within 2σ of μ\n  - 99.7% within 3σ of μ\n    `, workedContent: `\n## Worked Example\n\n**μ = 100, σ = 15. What range contains 68% of data?**\n\n$100 \\pm 15 = [85, 115]$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | μ | σ | 68% Range |\n|---|---|---|----------|\n| 1 | 100 | 15 | 85–115 |\n| 2 | 50 | 10 | 40–60 |\n| 3 | 0 | 1 | −1 to 1 |\n    `,
    mcq1: { questions: [{ question: '95% of data falls within ____ standard deviations:', options: ['2','1','3','0.5'], correctAnswer: 0, explanation: '95% → 2σ.' }] },
    mcq2: { questions: [{ question: 'μ=50, σ=10. 95% range?', options: ['30–70','40–60','20–80','50–60'], correctAnswer: 0, explanation: '50 ± 2(10) = 30 to 70.' }] },
    input: { boxes: 3, correctAnswers: ['85','115','30'], content: `\n**68-95-99.7 Rule** 🧮\n\nμ = 100, σ = 15:\n\n1) 68% lower bound? (μ − σ)\n\n2) 68% upper bound? (μ + σ)\n\n3) 95% lower bound? (μ − 2σ)\n    `, hint1: '100 − 15.', hint2: '100 + 15.', hint3: '100 − 30.', explanation: '1) 85. 2) 115. 3) 70.' },
    dropdown: { dropdowns: [{ label: 'A normal distribution is', options: ['Symmetric and bell-shaped','Always skewed','Uniform','Bimodal'] }, { label: '99.7% falls within ____ standard deviations', options: ['3','2','1','4'] }], correctAnswers: ['Symmetric and bell-shaped','3'], hint1: 'The bell curve.', hint2: 'Nearly all data.', explanation: 'Normal = symmetric bell. 99.7% within 3σ.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nCombine all concepts:\n- Describe shape, center, spread\n- Choose mean or median appropriately\n- Apply the 68-95-99.7 rule\n- Identify outliers\n    `, workedContent: `\n## Worked Example\n\n**Test scores: μ = 75, σ = 8. What % score above 91?**\n\n$91 = 75 + 2(8) = \\mu + 2\\sigma$\n\nAbove 2σ: $(100\\% - 95\\%)/2 = 2.5\\%$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Answer |\n|---|---------|--------|\n| 1 | μ=75, σ=8. % below 59? | 2.5% |\n| 2 | Data: 1,2,3,4,5. Mean? | 3 |\n| 3 | Data: 1,2,3,4,5. Median? | 3 |\n    `,
    mcq1: { questions: [{ question: 'μ=75, σ=8. % below 59 (=μ−2σ)?', options: ['2.5%','5%','16%','50%'], correctAnswer: 0, explanation: 'Below −2σ: (100−95)/2 = 2.5%.' }] },
    mcq2: { questions: [{ question: 'Mean of 1, 2, 3, 4, 5?', options: ['3','2.5','5','15'], correctAnswer: 0, explanation: '15/5 = 3.' }] },
    input: { boxes: 3, correctAnswers: ['3','3','2.5'], content: `\n**Combined Practice** 🧮\n\n1) Mean of 1, 2, 3, 4, 5?\n\n2) Median of 1, 2, 3, 4, 5?\n\n3) μ=75, σ=8. % above 91? (Answer as number, e.g. 2.5)\n    `, hint1: '15/5.', hint2: 'Middle value.', hint3: '91 = μ + 2σ. Above that is (100−95)/2.', explanation: '1) 3. 2) 3. 3) 2.5%.' },
    dropdown: { dropdowns: [{ label: 'For symmetric data, mean and median are', options: ['Approximately equal','Very different','Always 0','Undefined'] }, { label: 'The 68-95-99.7 rule applies to ____ distributions', options: ['Normal (bell-shaped)','All','Skewed only','Uniform only'] }], correctAnswers: ['Approximately equal','Normal (bell-shaped)'], hint1: 'Balanced.', hint2: 'Bell curve only.', explanation: 'Symmetric → mean ≈ median. Rule applies to normal distributions.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Concepts\n- Shape (symmetric/skewed), Center (mean/median), Spread (s, IQR, range)\n- Mean: sensitive to outliers; Median: resistant\n- Normal: 68-95-99.7 rule\n- $s = 0$ when all values are equal\n    `, workedContent: `\n## Worked Example\n\n**Median of 10, 20, 30, 40, 50 = 30 (middle value)** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Topic | Problem |\n|---|-------|---------|\n| 1 | Median | 4, 8, 12 |\n| 2 | Mean | 10, 20, 30 |\n| 3 | 68% range | μ=50, σ=5 |\n    `,
    mcq1: { questions: [{ question: 'Median of 4, 8, 12?', options: ['8','4','12','24'], correctAnswer: 0, explanation: 'Middle value.' }] },
    mcq2: { questions: [{ question: 'Mean of 10, 20, 30?', options: ['20','10','30','60'], correctAnswer: 0, explanation: '60/3=20.' }] },
    input: { boxes: 3, correctAnswers: ['8','20','45'], content: `\n**Review** 🧮\n\n1) Median of 4, 8, 12?\n\n2) Mean of 10, 20, 30?\n\n3) μ=50, σ=5. Lower bound of 68% range?\n    `, hint1: 'Middle value.', hint2: '60/3.', hint3: '50−5.', explanation: '1) 8. 2) 20. 3) 45.' },
    dropdown: { dropdowns: [{ label: 'IQR is calculated as', options: ['Q3 − Q1','Max − Min','Mean − Median','σ²'] }, { label: 'The median is the ____ percentile', options: ['50th','25th','75th','100th'] }], correctAnswers: ['Q3 − Q1','50th'], hint1: 'Interquartile range.', hint2: 'Half above, half below.', explanation: 'IQR = Q3−Q1. Median = 50th percentile.' }
  }
],

'apstats-hypothesis-testing': [
  { introContent: `\n# 📐 Null & Alternative Hypotheses\n\n**Part 1 of 7 — Null & Alternative Hypotheses**\n\n- **Null hypothesis** ($H_0$): no effect / no difference (status quo)\n- **Alternative hypothesis** ($H_a$): there IS an effect / difference\n\nWe test whether data provides enough evidence to **reject** $H_0$.\n\n- Two-tailed: $H_a: \\mu \\neq \\mu_0$\n- Left-tailed: $H_a: \\mu < \\mu_0$\n- Right-tailed: $H_a: \\mu > \\mu_0$\n    `, workedContent: `\n## Worked Example\n\n**Claim: average score > 75. Set up hypotheses.**\n\n$H_0: \\mu = 75$ (no difference from 75)\n$H_a: \\mu > 75$ (right-tailed test) ✅\n    `, practiceContent: `\n## Practice\n\n| # | Claim | $H_a$ |\n|---|-------|-------|\n| 1 | μ > 75 | Right-tailed |\n| 2 | μ < 50 | Left-tailed |\n| 3 | μ ≠ 100 | Two-tailed |\n    `,
    mcq1: { questions: [{ question: 'H₀ represents:', options: ['No effect (status quo)','The research claim','The alternative','The test statistic'], correctAnswer: 0, explanation: 'Null = nothing is happening.' }] },
    mcq2: { questions: [{ question: 'Hₐ: μ > 75 is a:', options: ['Right-tailed test','Left-tailed test','Two-tailed test','Null hypothesis'], correctAnswer: 0, explanation: 'Greater than → right tail.' }] },
    input: { boxes: 3, correctAnswers: ['75','50','100'], content: `\n**Hypothesis Setup** 🧮\n\nWhat is the null value (μ₀)?\n\n1) Claim: μ > 75. H₀: μ = ?\n\n2) Claim: μ < 50. H₀: μ = ?\n\n3) Claim: μ ≠ 100. H₀: μ = ?\n    `, hint1: 'The value being tested.', hint2: 'Boundary value.', hint3: 'Equal to the claimed value.', explanation: '1) 75. 2) 50. 3) 100. H₀ always uses = sign.' },
    dropdown: { dropdowns: [{ label: 'The null hypothesis always uses the ____ sign', options: ['= (equals)','> (greater than)','< (less than)','≠ (not equal)'] }, { label: 'We hope to ____ the null hypothesis', options: ['Reject','Accept','Prove','Ignore'] }], correctAnswers: ['= (equals)','Reject'], hint1: 'H₀: μ = value.', hint2: 'Evidence against it.', explanation: 'H₀ uses =. We seek to reject H₀.' }
  },
  { introContent: `\n# 📊 Test Statistics\n\n**Part 2 of 7 — Test Statistics**\n\nA **test statistic** measures how far the sample result is from the null value, in standard error units.\n\n$$t = \\frac{\\bar{x} - \\mu_0}{s / \\sqrt{n}}$$\n\nLarger $|t|$ → stronger evidence against $H_0$.\n    `, workedContent: `\n## Worked Example\n\n**$\\bar{x} = 82$, $\\mu_0 = 75$, $s = 14$, $n = 49$.**\n\n$SE = \\frac{14}{\\sqrt{49}} = \\frac{14}{7} = 2$\n\n$t = \\frac{82 - 75}{2} = 3.5$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | $\\bar{x}$ | $\\mu_0$ | s | n | SE | t |\n|---|------|------|---|---|----|-|\n| 1 | 82 | 75 | 14 | 49 | 2 | 3.5 |\n| 2 | 50 | 50 | 10 | 25 | 2 | 0 |\n    `,
    mcq1: { questions: [{ question: 'SE = s/√n. If s=14, n=49, SE = ?', options: ['2','7','14','0.5'], correctAnswer: 0, explanation: '14/√49 = 14/7 = 2.' }] },
    mcq2: { questions: [{ question: 'If x̄ = μ₀, the test statistic t = ?', options: ['0','1','−1','Undefined'], correctAnswer: 0, explanation: '(μ₀ − μ₀)/SE = 0/SE = 0.' }] },
    input: { boxes: 3, correctAnswers: ['2','3.5','0'], content: `\n**Test Statistics** 🧮\n\n1) s=14, n=49. SE?\n\n2) x̄=82, μ₀=75, SE=2. t=?\n\n3) x̄=50, μ₀=50, SE=2. t=?\n    `, hint1: '14/√49 = 14/7.', hint2: '(82−75)/2.', hint3: '(50−50)/2.', explanation: '1) 2. 2) 3.5. 3) 0.' },
    dropdown: { dropdowns: [{ label: 'A large |t| value provides', options: ['Strong evidence against H₀','Weak evidence','No evidence','Proof of H₀'] }, { label: 'Standard error measures the variability of', options: ['The sample mean','Individual data points','The population','The test statistic'] }], correctAnswers: ['Strong evidence against H₀','The sample mean'], hint1: 'Far from null.', hint2: 'SE = s/√n.', explanation: 'Large |t| → strong evidence. SE = variability of x̄.' }
  },
  { introContent: `\n# 🔢 P-Values\n\n**Part 3 of 7 — P-Values**\n\nThe **p-value** is the probability of getting a result as extreme (or more) than the observed, assuming $H_0$ is true.\n\n- Small p-value → strong evidence against $H_0$\n- If $p < \\alpha$ → **reject** $H_0$\n- Common $\\alpha = 0.05$\n    `, workedContent: `\n## Worked Example\n\n**p-value = 0.03, α = 0.05. Decision?**\n\n$0.03 < 0.05$ → **Reject $H_0$**. The result is statistically significant. ✅\n    `, practiceContent: `\n## Practice\n\n| # | p-value | α | Decision |\n|---|---------|---|----------|\n| 1 | 0.03 | 0.05 | Reject H₀ |\n| 2 | 0.08 | 0.05 | Fail to reject H₀ |\n| 3 | 0.01 | 0.01 | Borderline |\n    `,
    mcq1: { questions: [{ question: 'p = 0.03, α = 0.05. Decision?', options: ['Reject H₀','Fail to reject H₀','Accept H₀','Need more data'], correctAnswer: 0, explanation: 'p < α → reject.' }] },
    mcq2: { questions: [{ question: 'A p-value of 0.001 provides:', options: ['Very strong evidence against H₀','Weak evidence','No evidence','Proof of H₀'], correctAnswer: 0, explanation: 'Very small p → very strong evidence.' }] },
    input: { boxes: 3, correctAnswers: ['0.05','0.03','0.08'], content: `\n**P-Values** 🧮\n\n1) The most common significance level α?\n\n2) Which is more significant: p=0.03 or p=0.08?\n\n3) Which p-value leads to "fail to reject" at α=0.05?\n    `, hint1: 'Standard threshold.', hint2: 'Smaller p is stronger.', hint3: 'p > α → fail to reject.', explanation: '1) 0.05. 2) 0.03 (smaller). 3) 0.08 > 0.05.' },
    dropdown: { dropdowns: [{ label: 'If p < α, we', options: ['Reject H₀','Accept H₀','Fail to reject H₀','Increase α'] }, { label: 'A small p-value means the result is', options: ['Statistically significant','Insignificant','Random','Normal'] }], correctAnswers: ['Reject H₀','Statistically significant'], hint1: 'Evidence is strong enough.', hint2: 'Unlikely under H₀.', explanation: 'p < α → reject. Small p = statistically significant.' }
  },
  { introContent: `\n# 📈 Type I & Type II Errors\n\n**Part 4 of 7 — Type I & Type II Errors**\n\n| | H₀ True | H₀ False |\n|---|---------|----------|\n| Reject H₀ | **Type I** (α) | Correct |\n| Fail to reject | Correct | **Type II** (β) |\n\n- **Type I**: false positive (reject true H₀)\n- **Type II**: false negative (fail to reject false H₀)\n- **Power** = 1 − β (probability of correctly rejecting false H₀)\n    `, workedContent: `\n## Worked Example\n\n**A drug has no effect, but the test says it works → Type I error** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Scenario | Error Type |\n|---|---------|----------|\n| 1 | Convict innocent person | Type I |\n| 2 | Acquit guilty person | Type II |\n| 3 | True alarm detected | Correct decision |\n    `,
    mcq1: { questions: [{ question: 'Rejecting a true H₀ is:', options: ['Type I error','Type II error','Correct decision','Power'], correctAnswer: 0, explanation: 'False positive.' }] },
    mcq2: { questions: [{ question: 'The probability of a Type I error is:', options: ['α','β','1−α','1−β'], correctAnswer: 0, explanation: 'α = significance level = P(Type I).' }] },
    input: { boxes: 3, correctAnswers: ['1','2','0.05'], content: `\n**Errors** 🧮\n\n1) Rejecting true H₀ → Type ___ error?\n\n2) Failing to reject false H₀ → Type ___ error?\n\n3) If α = 0.05, probability of Type I error?\n    `, hint1: 'False positive.', hint2: 'False negative.', hint3: 'α directly.', explanation: '1) Type 1. 2) Type 2. 3) 0.05.' },
    dropdown: { dropdowns: [{ label: 'Power equals', options: ['1 − β','α','β','1 − α'] }, { label: 'Increasing sample size generally ____ power', options: ['Increases','Decreases','Does not affect','Eliminates'] }], correctAnswers: ['1 − β','Increases'], hint1: 'Complement of Type II.', hint2: 'Larger n → more precise.', explanation: 'Power = 1−β. Larger n → more power.' }
  },
  { introContent: `\n# 🧮 One-Sample t-Test\n\n**Part 5 of 7 — One-Sample t-Test**\n\nConditions:\n1. **Random** sample\n2. **Independence** (n < 10% of population)\n3. **Normal/Large sample** (n ≥ 30 or approximately normal)\n\n$$t = \\frac{\\bar{x} - \\mu_0}{s/\\sqrt{n}}, \\quad df = n - 1$$\n    `, workedContent: `\n## Worked Example\n\n**n = 36, x̄ = 52, s = 6, μ₀ = 50. Test at α = 0.05.**\n\n$SE = 6/\\sqrt{36} = 1$\n$t = (52-50)/1 = 2$\n$df = 35$. Since $|t| > 2$, p < 0.05 → **Reject** ✅\n    `, practiceContent: `\n## Practice\n\n| # | n | x̄ | s | μ₀ | t |\n|---|---|---|---|---|---|\n| 1 | 36 | 52 | 6 | 50 | 2 |\n| 2 | 25 | 100 | 10 | 100 | 0 |\n| 3 | 16 | 84 | 8 | 80 | 2 |\n    `,
    mcq1: { questions: [{ question: 'Degrees of freedom for n=36?', options: ['35','36','34','37'], correctAnswer: 0, explanation: 'df = n−1 = 35.' }] },
    mcq2: { questions: [{ question: 'The condition n ≥ 30 relates to:', options: ['Central Limit Theorem','The p-value','Type I error','The null'], correctAnswer: 0, explanation: 'CLT ensures approximate normality.' }] },
    input: { boxes: 3, correctAnswers: ['1','2','35'], content: `\n**t-Test** 🧮\n\nn=36, x̄=52, s=6, μ₀=50:\n\n1) SE = s/√n?\n\n2) t = (x̄ − μ₀)/SE?\n\n3) df?\n    `, hint1: '6/√36 = 6/6.', hint2: '(52−50)/1.', hint3: 'n−1.', explanation: '1) 1. 2) 2. 3) 35.' },
    dropdown: { dropdowns: [{ label: 'A t-test is used instead of a z-test when', options: ['σ is unknown (use s instead)','n is large','The data is normal','α is small'] }, { label: 'The three conditions for a t-test are', options: ['Random, Independent, Normal/Large','Mean, Median, Mode','H₀, Hₐ, p-value','Type I, Type II, Power'] }], correctAnswers: ['σ is unknown (use s instead)','Random, Independent, Normal/Large'], hint1: 'Population σ unknown.', hint2: 'R-I-N.', explanation: 't-test: σ unknown. Conditions: Random, Independent, Normal/Large.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nFull hypothesis test procedure:\n1. State hypotheses ($H_0$, $H_a$)\n2. Check conditions\n3. Calculate test statistic\n4. Find p-value\n5. Make decision and state conclusion in context\n    `, workedContent: `\n## Worked Example\n\n**Claim: μ > 80. Sample: n=25, x̄=84, s=10.**\n\n1. $H_0: \\mu=80$, $H_a: \\mu>80$\n2. Random ✓, Independent ✓, n=25 (check normality)\n3. $t = (84-80)/(10/5) = 4/2 = 2$, df=24\n4. p ≈ 0.028\n5. p < 0.05 → Reject $H_0$. Evidence supports μ > 80. ✅\n    `, practiceContent: `\n## Practice\n\n| # | Step | Key Action |\n|---|------|----------|\n| 1 | Hypotheses | Write H₀ and Hₐ |\n| 2 | Conditions | Random, Independent, Normal |\n| 3 | Calculate | t = (x̄−μ₀)/(s/√n) |\n    `,
    mcq1: { questions: [{ question: 'SE when s=10, n=25?', options: ['2','10','5','0.4'], correctAnswer: 0, explanation: '10/√25 = 10/5 = 2.' }] },
    mcq2: { questions: [{ question: 'The conclusion should be stated in:', options: ['Context of the problem','Mathematical symbols only','Greek letters','Technical jargon'], correctAnswer: 0, explanation: 'Always relate back to the real-world context.' }] },
    input: { boxes: 3, correctAnswers: ['2','2','24'], content: `\n**Full Test** 🧮\n\nn=25, x̄=84, s=10, μ₀=80:\n\n1) SE?\n\n2) t?\n\n3) df?\n    `, hint1: '10/√25.', hint2: '(84−80)/SE.', hint3: 'n−1.', explanation: '1) 2. 2) 2. 3) 24.' },
    dropdown: { dropdowns: [{ label: 'The first step in a hypothesis test is to', options: ['State hypotheses','Calculate t','Find p-value','Check conditions'] }, { label: 'We never say "accept H₀" — instead we say', options: ['Fail to reject H₀','Accept H₀','Prove H₀','Confirm H₀'] }], correctAnswers: ['State hypotheses','Fail to reject H₀'], hint1: 'H₀ and Hₐ first.', hint2: 'Language matters.', explanation: 'Start with hypotheses. Say "fail to reject," not "accept."' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Concepts\n- $H_0$: null (status quo); $H_a$: alternative\n- $t = (\\bar{x} - \\mu_0)/(s/\\sqrt{n})$, $df = n-1$\n- p < α → reject; p ≥ α → fail to reject\n- Type I: reject true $H_0$; Type II: fail to reject false $H_0$\n- Power = $1 - \\beta$\n    `, workedContent: `\n## Worked Example\n\n**p = 0.02, α = 0.05 → Reject H₀** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Topic | Problem |\n|---|-------|---------|\n| 1 | p-value | p=0.04, α=0.05 |\n| 2 | df | n=30 |\n| 3 | SE | s=12, n=36 |\n    `,
    mcq1: { questions: [{ question: 'p=0.04, α=0.05. Decision?', options: ['Reject H₀','Fail to reject','Accept H₀','Insufficient data'], correctAnswer: 0, explanation: '0.04 < 0.05 → reject.' }] },
    mcq2: { questions: [{ question: 'df for n=30?', options: ['29','30','31','28'], correctAnswer: 0, explanation: 'n−1 = 29.' }] },
    input: { boxes: 3, correctAnswers: ['29','2','0.05'], content: `\n**Review** 🧮\n\n1) df when n=30?\n\n2) SE when s=12, n=36?\n\n3) Most common significance level?\n    `, hint1: 'n−1.', hint2: '12/√36.', hint3: 'Standard α.', explanation: '1) 29. 2) 2. 3) 0.05.' },
    dropdown: { dropdowns: [{ label: 'Statistical significance means', options: ['p < α','p > α','t = 0','The result is important'] }, { label: 'Increasing α makes it ____ to reject H₀', options: ['Easier','Harder','Impossible','No effect'] }], correctAnswers: ['p < α','Easier'], hint1: 'Below threshold.', hint2: 'Wider rejection region.', explanation: 'Significant: p<α. Larger α → easier to reject.' }
  }
],

'apstats-probability-rules': [
  { introContent: `\n# 📐 Basic Probability\n\n**Part 1 of 7 — Basic Probability**\n\n$$P(A) = \\frac{\\text{favorable outcomes}}{\\text{total outcomes}}$$\n\n- $0 \\leq P(A) \\leq 1$\n- $P(\\text{certain}) = 1$, $P(\\text{impossible}) = 0$\n- $P(A') = 1 - P(A)$ (complement)\n    `, workedContent: `\n## Worked Example\n\n**Roll a die. P(even)?**\n\nFavorable: {2, 4, 6} = 3\nTotal: 6\n$P = 3/6 = 0.5$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Event | P |\n|---|-------|---|\n| 1 | P(heads on fair coin) | 0.5 |\n| 2 | P(6 on die) | 1/6 |\n| 3 | P(not 6) | 5/6 |\n    `,
    mcq1: { questions: [{ question: 'P(6 on a fair die)?', options: ['1/6','1/3','1/2','1'], correctAnswer: 0, explanation: '1 favorable out of 6.' }] },
    mcq2: { questions: [{ question: 'P(A) + P(A\') = ?', options: ['1','0','0.5','2'], correctAnswer: 0, explanation: 'Event and complement sum to 1.' }] },
    input: { boxes: 3, correctAnswers: ['0.5','6','0.5'], content: `\n**Basic Probability** 🧮\n\n1) P(heads) on a fair coin?\n\n2) Total outcomes for a fair die?\n\n3) P(even) on a fair die?\n    `, hint1: '1/2.', hint2: 'How many sides?', hint3: '3 even numbers out of 6.', explanation: '1) 0.5. 2) 6. 3) 3/6=0.5.' },
    dropdown: { dropdowns: [{ label: 'Probability ranges from', options: ['0 to 1','−1 to 1','0 to 100','−∞ to ∞'] }, { label: 'P(A\') is called the', options: ['Complement','Union','Intersection','Conditional'] }], correctAnswers: ['0 to 1','Complement'], hint1: 'Always non-negative and ≤ 1.', hint2: 'Everything NOT in A.', explanation: 'P ranges 0–1. P(A\') = complement.' }
  },
  { introContent: `\n# 📊 Addition Rule\n\n**Part 2 of 7 — Addition Rule**\n\n$$P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$$\n\nFor **mutually exclusive** events ($A \\cap B = \\emptyset$):\n$$P(A \\cup B) = P(A) + P(B)$$\n    `, workedContent: `\n## Worked Example\n\n**P(A)=0.4, P(B)=0.3, P(A∩B)=0.1. P(A∪B)?**\n\n$P(A \\cup B) = 0.4 + 0.3 - 0.1 = 0.6$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | P(A) | P(B) | P(A∩B) | P(A∪B) |\n|---|------|------|--------|--------|\n| 1 | 0.4 | 0.3 | 0.1 | 0.6 |\n| 2 | 0.5 | 0.2 | 0 | 0.7 |\n| 3 | 0.6 | 0.4 | 0.2 | 0.8 |\n    `,
    mcq1: { questions: [{ question: 'P(A)=0.5, P(B)=0.2, mutually exclusive. P(A∪B)?', options: ['0.7','0.1','1.0','0.3'], correctAnswer: 0, explanation: 'ME: P(A∪B) = 0.5+0.2 = 0.7.' }] },
    mcq2: { questions: [{ question: 'We subtract P(A∩B) to avoid:', options: ['Double counting','Negative probability','Zero probability','Large numbers'], correctAnswer: 0, explanation: 'Overlap is counted in both P(A) and P(B).' }] },
    input: { boxes: 3, correctAnswers: ['0.6','0.7','0.8'], content: `\n**Addition Rule** 🧮\n\nP(A∪B) = P(A)+P(B)−P(A∩B)\n\n1) P(A)=0.4, P(B)=0.3, P(A∩B)=0.1?\n\n2) P(A)=0.5, P(B)=0.2, mutually exclusive?\n\n3) P(A)=0.6, P(B)=0.4, P(A∩B)=0.2?\n    `, hint1: '0.4+0.3−0.1.', hint2: 'ME → P(A∩B)=0.', hint3: '0.6+0.4−0.2.', explanation: '1) 0.6. 2) 0.7. 3) 0.8.' },
    dropdown: { dropdowns: [{ label: 'Mutually exclusive means', options: ['Cannot both occur','Always both occur','Are identical','Are independent'] }, { label: 'The addition rule finds P(A ____ B)', options: ['or (union)','and (intersection)','given','not'] }], correctAnswers: ['Cannot both occur','or (union)'], hint1: 'No overlap.', hint2: 'A or B.', explanation: 'ME: cannot both happen. Addition rule: P(A or B).' }
  },
  { introContent: `\n# 🔢 Multiplication Rule\n\n**Part 3 of 7 — Multiplication Rule**\n\n$$P(A \\cap B) = P(A) \\times P(B|A)$$\n\nFor **independent** events:\n$$P(A \\cap B) = P(A) \\times P(B)$$\n    `, workedContent: `\n## Worked Example\n\n**Two coin flips. P(HH)?**\n\nIndependent: $P(H) \\times P(H) = 0.5 \\times 0.5 = 0.25$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | P(A) | P(B) | P(A∩B) |\n|---|------|------|--------|\n| 1 | 0.5 | 0.5 | 0.25 |\n| 2 | 0.3 | 0.4 | 0.12 |\n| 3 | 0.2 | 0.5 | 0.10 |\n    `,
    mcq1: { questions: [{ question: 'P(A)=0.3, P(B)=0.4, independent. P(A∩B)?', options: ['0.12','0.7','0.1','0.34'], correctAnswer: 0, explanation: '0.3×0.4=0.12.' }] },
    mcq2: { questions: [{ question: 'The multiplication rule finds P(A ____ B):', options: ['and','or','given','not'], correctAnswer: 0, explanation: 'Intersection = both.' }] },
    input: { boxes: 3, correctAnswers: ['0.25','0.12','0.1'], content: `\n**Multiplication Rule** 🧮\n\nFor independent events: P(A∩B) = P(A)×P(B)\n\n1) P(A)=0.5, P(B)=0.5?\n\n2) P(A)=0.3, P(B)=0.4?\n\n3) P(A)=0.2, P(B)=0.5?\n    `, hint1: '0.5×0.5.', hint2: '0.3×0.4.', hint3: '0.2×0.5.', explanation: '1) 0.25. 2) 0.12. 3) 0.10.' },
    dropdown: { dropdowns: [{ label: 'Independent events have ____ effect on each other', options: ['No','A large','A small','A negative'] }, { label: 'Drawing cards without replacement is', options: ['Dependent','Independent','Impossible','Mutually exclusive'] }], correctAnswers: ['No','Dependent'], hint1: 'One does not affect the other.', hint2: 'Deck changes after each draw.', explanation: 'Independent: no effect. Without replacement: dependent.' }
  },
  { introContent: `\n# 📈 Conditional Probability\n\n**Part 4 of 7 — Conditional Probability**\n\n$$P(A|B) = \\frac{P(A \\cap B)}{P(B)}$$\n\nRead: "probability of A **given** B has occurred."\n\nThis restricts our sample space to only outcomes where B happened.\n    `, workedContent: `\n## Worked Example\n\n**P(A∩B) = 0.12, P(B) = 0.4. P(A|B)?**\n\n$P(A|B) = \\frac{0.12}{0.4} = 0.3$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | P(A∩B) | P(B) | P(A given B) |\n|---|--------|------|-------|\n| 1 | 0.12 | 0.4 | 0.3 |\n| 2 | 0.15 | 0.5 | 0.3 |\n| 3 | 0.06 | 0.2 | 0.3 |\n    `,
    mcq1: { questions: [{ question: 'P(A∩B)=0.15, P(B)=0.5. P(A|B)?', options: ['0.3','0.65','0.075','0.5'], correctAnswer: 0, explanation: '0.15/0.5 = 0.3.' }] },
    mcq2: { questions: [{ question: 'P(A|B) restricts the sample space to:', options: ['Events where B occurred','All events','Events where A occurred','The empty set'], correctAnswer: 0, explanation: 'Given B → only look at outcomes in B.' }] },
    input: { boxes: 3, correctAnswers: ['0.3','0.3','0.3'], content: `\n**Conditional Probability** 🧮\n\n$P(A|B) = P(A \\cap B) / P(B)$\n\n1) P(A∩B)=0.12, P(B)=0.4. P(A|B)?\n\n2) P(A∩B)=0.15, P(B)=0.5. P(A|B)?\n\n3) P(A∩B)=0.06, P(B)=0.2. P(A|B)?\n    `, hint1: '0.12/0.4.', hint2: '0.15/0.5.', hint3: '0.06/0.2.', explanation: '1) 0.3. 2) 0.3. 3) 0.3.' },
    dropdown: { dropdowns: [{ label: 'P(A|B) reads as "probability of A"', options: ['Given B','And B','Or B','Without B'] }, { label: 'The denominator in P(A|B) is', options: ['P(B)','P(A)','P(A∩B)','P(A∪B)'] }], correctAnswers: ['Given B','P(B)'], hint1: 'Conditional.', hint2: 'The given event.', explanation: 'P(A|B) = "A given B." Denominator = P(B).' }
  },
  { introContent: `\n# 🧮 Independence\n\n**Part 5 of 7 — Independence**\n\nEvents A and B are **independent** if:\n$$P(A|B) = P(A) \\quad \\text{or equivalently} \\quad P(A \\cap B) = P(A) \\cdot P(B)$$\n\nIf knowing B changes the probability of A, the events are **dependent**.\n    `, workedContent: `\n## Worked Example\n\n**P(A) = 0.4, P(B) = 0.5, P(A∩B) = 0.2. Independent?**\n\n$P(A) \\times P(B) = 0.4 \\times 0.5 = 0.2 = P(A∩B)$\n\n**Yes, independent!** ✅\n    `, practiceContent: `\n## Practice\n\n| # | P(A) | P(B) | P(A∩B) | Independent? |\n|---|------|------|--------|---------|\n| 1 | 0.4 | 0.5 | 0.2 | Yes |\n| 2 | 0.3 | 0.6 | 0.1 | No |\n| 3 | 0.5 | 0.5 | 0.25 | Yes |\n    `,
    mcq1: { questions: [{ question: 'P(A)=0.3, P(B)=0.6, P(A∩B)=0.1. Independent?', options: ['No, because 0.3×0.6≠0.1','Yes','Cannot tell','Always independent'], correctAnswer: 0, explanation: '0.3×0.6=0.18≠0.1.' }] },
    mcq2: { questions: [{ question: 'If independent, P(A|B) = ?', options: ['P(A)','P(B)','P(A∩B)','0'], correctAnswer: 0, explanation: 'Independence: knowing B does not change P(A).' }] },
    input: { boxes: 3, correctAnswers: ['0.2','0.18','0.25'], content: `\n**Test Independence** 🧮\n\nCompute P(A)×P(B):\n\n1) P(A)=0.4, P(B)=0.5?\n\n2) P(A)=0.3, P(B)=0.6?\n\n3) P(A)=0.5, P(B)=0.5?\n    `, hint1: '0.4×0.5.', hint2: '0.3×0.6.', hint3: '0.5×0.5.', explanation: '1) 0.2. 2) 0.18. 3) 0.25. Compare with P(A∩B) to check.' },
    dropdown: { dropdowns: [{ label: 'Independent means one event ____ the other', options: ['Does not affect','Always causes','Prevents','Guarantees'] }, { label: 'Mutually exclusive events are ____ independent', options: ['Never','Always','Sometimes','Definitely'] }], correctAnswers: ['Does not affect','Never'], hint1: 'No influence.', hint2: 'If ME and both have P>0, they are dependent.', explanation: 'Independent: no effect. ME events (P>0) cannot be independent.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nCombine all probability rules:\n- Choose addition or multiplication rule\n- Check independence vs dependence\n- Apply conditional probability\n- Use complements\n    `, workedContent: `\n## Worked Example\n\n**P(rain) = 0.3. P(no rain on 2 consecutive days)?**\n\nIndependent days:\n$P(\\text{no rain}) = 1 - 0.3 = 0.7$\n$P(\\text{both dry}) = 0.7 \\times 0.7 = 0.49$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Rule |\n|---|---------|------|\n| 1 | P(A or B) | Addition |\n| 2 | P(A and B) | Multiplication |\n| 3 | P(not A) | Complement |\n    `,
    mcq1: { questions: [{ question: 'P(rain)=0.3. P(no rain)?', options: ['0.7','0.3','1','0'], correctAnswer: 0, explanation: '1−0.3=0.7.' }] },
    mcq2: { questions: [{ question: 'P(at least one) is easiest found with:', options: ['1 − P(none)','P(A)+P(B)','P(A)×P(B)','P(A|B)'], correctAnswer: 0, explanation: 'Complement: 1 − P(none).' }] },
    input: { boxes: 3, correctAnswers: ['0.7','0.49','0.51'], content: `\n**Applications** 🧮\n\nP(rain each day) = 0.3, days independent:\n\n1) P(dry on one day)?\n\n2) P(dry on BOTH of 2 days)?\n\n3) P(rain on at least one of 2 days)?\n    `, hint1: '1−0.3.', hint2: '0.7×0.7.', hint3: '1−P(both dry).', explanation: '1) 0.7. 2) 0.49. 3) 1−0.49=0.51.' },
    dropdown: { dropdowns: [{ label: '"At least one" problems use the ____ rule', options: ['Complement','Addition','Multiplication','Conditional'] }, { label: 'P(A or B) uses the ____ rule', options: ['Addition','Multiplication','Complement','Bayes'] }], correctAnswers: ['Complement','Addition'], hint1: '1 − P(none).', hint2: 'A ∪ B.', explanation: '"At least one" → complement. "Or" → addition rule.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Formulas\n- $P(A') = 1 - P(A)$\n- $P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$\n- $P(A \\cap B) = P(A) \\cdot P(B|A)$\n- Independent: $P(A \\cap B) = P(A) \\cdot P(B)$\n- $P(A|B) = P(A \\cap B) / P(B)$\n    `, workedContent: `\n## Worked Example\n\n**Complement: P(A)=0.8 → P(A')=0.2** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Complement | P(A)=0.7 |\n| 2 | Multiplication | P(A)=0.4, P(B)=0.3, independent |\n| 3 | Conditional | P(A∩B)=0.2, P(B)=0.5 |\n    `,
    mcq1: { questions: [{ question: 'P(A)=0.7. P(A\')?', options: ['0.3','0.7','1','0'], correctAnswer: 0, explanation: '1−0.7=0.3.' }] },
    mcq2: { questions: [{ question: 'P(A)=0.4, P(B)=0.3, independent. P(A∩B)?', options: ['0.12','0.7','0.1','0.43'], correctAnswer: 0, explanation: '0.4×0.3=0.12.' }] },
    input: { boxes: 3, correctAnswers: ['0.3','0.12','0.4'], content: `\n**Review** 🧮\n\n1) P(A)=0.7. P(A')?\n\n2) P(A)=0.4, P(B)=0.3, independent. P(A∩B)?\n\n3) P(A∩B)=0.2, P(B)=0.5. P(A|B)?\n    `, hint1: '1−0.7.', hint2: '0.4×0.3.', hint3: '0.2/0.5.', explanation: '1) 0.3. 2) 0.12. 3) 0.4.' },
    dropdown: { dropdowns: [{ label: 'The complement of P=0.9 is', options: ['0.1','0.9','1','0'] }, { label: '"And" in probability usually means', options: ['Intersection (multiply)','Union (add)','Complement','Conditional'] }], correctAnswers: ['0.1','Intersection (multiply)'], hint1: '1−0.9.', hint2: 'Both events together.', explanation: 'P\'=0.1. "And" → intersection → multiplication rule.' }
  }
]

};
