/**
 * Content patches for Geometry topics:
 * - geometry-circles (7 parts)
 * - geometry-coordinate-proofs (7 parts)
 * - geometry-triangle-congruence (7 parts)
 */
module.exports = {

'geometry-circles': [
  { introContent: `\n# 📐 Parts of a Circle\n\n**Part 1 of 7 — Parts of a Circle**\n\n- **Radius** ($r$): center to edge\n- **Diameter** ($d = 2r$): edge to edge through center\n- **Chord**: segment with both endpoints on the circle\n- **Secant**: line that intersects a circle at two points\n- **Tangent**: line that touches the circle at one point\n    `, workedContent: `\n## Worked Example\n\n**Circle with radius 7. What is the diameter?**\n\n$d = 2r = 2(7) = 14$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Given | Find |\n|---|-------|------|\n| 1 | r = 5 | d |\n| 2 | d = 18 | r |\n| 3 | r = 3.5 | d |\n    `,
    mcq1: { questions: [{ question: 'The diameter is:', options: ['Twice the radius','Half the radius','Equal to the radius','The circumference'], correctAnswer: 0, explanation: 'd = 2r.' }] },
    mcq2: { questions: [{ question: 'A tangent line touches a circle at:', options: ['Exactly one point','Two points','Zero points','Infinite points'], correctAnswer: 0, explanation: 'Tangent = one point of tangency.' }] },
    input: { boxes: 3, correctAnswers: ['10','9','7'], content: `\n**Circle Parts** 🧮\n\n1) r = 5. Diameter?\n\n2) d = 18. Radius?\n\n3) r = 3.5. Diameter?\n    `, hint1: 'd = 2r.', hint2: 'r = d/2.', hint3: 'd = 2(3.5).', explanation: '1) 10. 2) 9. 3) 7.' },
    dropdown: { dropdowns: [{ label: 'A chord that passes through the center is called', options: ['A diameter','A radius','A tangent','A secant'] }, { label: 'All radii of a circle are', options: ['Equal in length','Different lengths','Chords','Tangent lines'] }], correctAnswers: ['A diameter','Equal in length'], hint1: 'Longest chord.', hint2: 'Same distance from center.', explanation: 'Diameter is a chord through center. All radii are equal.' }
  },
  { introContent: `\n# 📊 Central & Inscribed Angles\n\n**Part 2 of 7 — Central & Inscribed Angles**\n\n- **Central angle**: vertex at center; equals the intercepted arc\n- **Inscribed angle**: vertex on the circle; equals **half** the intercepted arc\n\n$$\\text{Inscribed angle} = \\frac{1}{2} \\times \\text{intercepted arc}$$\n    `, workedContent: `\n## Worked Example\n\n**Arc = 80°. Inscribed angle?**\n\n$\\frac{80}{2} = 40°$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Arc | Inscribed Angle |\n|---|-----|----------------|\n| 1 | 100° | 50° |\n| 2 | 60° | 30° |\n| 3 | 140° | 70° |\n    `,
    mcq1: { questions: [{ question: 'Central angle equals:', options: ['Its intercepted arc','Half its arc','Twice its arc','90°'], correctAnswer: 0, explanation: 'Central angle = arc.' }] },
    mcq2: { questions: [{ question: 'An inscribed angle in a semicircle is:', options: ['90°','180°','45°','60°'], correctAnswer: 0, explanation: 'Arc of semicircle = 180°. Half = 90°.' }] },
    input: { boxes: 3, correctAnswers: ['50','30','70'], content: `\n**Inscribed Angles** 🧮\n\n1) Arc = 100°. Inscribed angle?\n\n2) Arc = 60°. Inscribed angle?\n\n3) Arc = 140°. Inscribed angle?\n    `, hint1: '100 ÷ 2.', hint2: '60 ÷ 2.', hint3: '140 ÷ 2.', explanation: '1) 50. 2) 30. 3) 70.' },
    dropdown: { dropdowns: [{ label: 'An inscribed angle is ____ its intercepted arc', options: ['Half','Equal to','Double','Unrelated to'] }, { label: 'A central angle has its vertex at the', options: ['Center','Circle edge','Outside','On a chord'] }], correctAnswers: ['Half','Center'], hint1: 'Inscribed = ½ arc.', hint2: 'Central → center.', explanation: 'Inscribed = ½ arc. Central angle: vertex at center.' }
  },
  { introContent: `\n# 🔢 Arc Length & Sector Area\n\n**Part 3 of 7 — Arc Length & Sector Area**\n\n$$\\text{Arc length} = \\frac{\\theta}{360} \\times 2\\pi r$$\n\n$$\\text{Sector area} = \\frac{\\theta}{360} \\times \\pi r^2$$\n\nwhere $\\theta$ is the central angle in degrees.\n    `, workedContent: `\n## Worked Example\n\n**r = 10, θ = 90°. Arc length?**\n\n$\\frac{90}{360} \\times 2\\pi(10) = \\frac{1}{4}(20\\pi) = 5\\pi \\approx 15.7$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | r | θ | Find |\n|---|---|---|------|\n| 1 | 6 | 60° | Arc length |\n| 2 | 10 | 90° | Sector area |\n| 3 | 4 | 180° | Arc length |\n    `,
    mcq1: { questions: [{ question: 'Arc length formula uses what fraction of the circumference?', options: ['θ/360','θ/180','θ/2π','r/θ'], correctAnswer: 0, explanation: 'Fraction = central angle / 360°.' }] },
    mcq2: { questions: [{ question: 'Sector area for r=10, θ=90° (use π≈3.14)?', options: ['78.5','314','157','31.4'], correctAnswer: 0, explanation: '(90/360)π(100) = 25π ≈ 78.5.' }] },
    input: { boxes: 3, correctAnswers: ['6.28','78.5','12.56'], content: `\n**Arc & Sector** 🧮 (Use π ≈ 3.14)\n\n1) r=6, θ=60°. Arc length?\n\n2) r=10, θ=90°. Sector area?\n\n3) r=4, θ=180°. Arc length?\n    `, hint1: '(60/360)(2)(3.14)(6).', hint2: '(90/360)(3.14)(100).', hint3: '(180/360)(2)(3.14)(4).', explanation: '1) (1/6)(37.68)=6.28. 2) 78.5. 3) (1/2)(25.12)=12.56.' },
    dropdown: { dropdowns: [{ label: 'Arc length is a portion of the', options: ['Circumference','Area','Diameter','Radius'] }, { label: 'Sector area is a portion of the', options: ['Circle area','Circumference','Diameter','Perimeter'] }], correctAnswers: ['Circumference','Circle area'], hint1: 'Arc = part of distance around.', hint2: 'Sector = pizza slice of area.', explanation: 'Arc length: part of circumference. Sector: part of area.' }
  },
  { introContent: `\n# 📈 Tangent Lines\n\n**Part 4 of 7 — Tangent Lines**\n\nA tangent is **perpendicular** to the radius at the point of tangency.\n\nIf tangent meets radius at point P: angle = 90°.\n\n**Two tangent segments** from an external point are **equal** in length.\n    `, workedContent: `\n## Worked Example\n\n**Radius = 5, tangent segment = 12. Distance from center to external point?**\n\nForms a right triangle: $d = \\sqrt{5^2 + 12^2} = \\sqrt{25+144} = \\sqrt{169} = 13$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Radius | Tangent | Distance |\n|---|--------|---------|----------|\n| 1 | 3 | 4 | 5 |\n| 2 | 5 | 12 | 13 |\n| 3 | 8 | 6 | 10 |\n    `,
    mcq1: { questions: [{ question: 'A tangent is ____ to the radius at the point of tangency:', options: ['Perpendicular','Parallel','Equal','Bisecting'], correctAnswer: 0, explanation: 'Tangent ⊥ radius.' }] },
    mcq2: { questions: [{ question: 'r=3, tangent=4. Distance to center from external point?', options: ['5','7','12','25'], correctAnswer: 0, explanation: '√(9+16)=√25=5.' }] },
    input: { boxes: 3, correctAnswers: ['5','13','10'], content: `\n**Tangent Problems** 🧮\n\n1) r=3, tangent=4. Distance from center?\n\n2) r=5, tangent=12. Distance from center?\n\n3) r=8, tangent=6. Distance from center?\n    `, hint1: '√(9+16).', hint2: '√(25+144).', hint3: '√(64+36).', explanation: '1) √25=5. 2) √169=13. 3) √100=10.' },
    dropdown: { dropdowns: [{ label: 'The angle between a tangent and radius is', options: ['90°','180°','45°','60°'] }, { label: 'Two tangents from the same external point are', options: ['Equal in length','Perpendicular','Parallel','Different lengths'] }], correctAnswers: ['90°','Equal in length'], hint1: 'Tangent ⊥ radius.', hint2: 'Tangent segments from same point.', explanation: 'Tangent ⊥ radius (90°). Equal tangent segments from external point.' }
  },
  { introContent: `\n# 🧮 Chords & Secants\n\n**Part 5 of 7 — Chords & Secants**\n\n### Key Theorems\n- **Intersecting chords**: $a \\cdot b = c \\cdot d$ (pieces of each chord)\n- **Equal chords** are equidistant from center\n- **Perpendicular from center** bisects a chord\n    `, workedContent: `\n## Worked Example\n\n**Two chords cross: segments 3, 8 and 4, ?.**\n\n$3 \\times 8 = 4 \\times x \\Rightarrow 24 = 4x \\Rightarrow x = 6$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Chord 1 | Chord 2 | Missing |\n|---|---------|---------|--------|\n| 1 | 3 × 8 | 4 × ? | 6 |\n| 2 | 2 × 9 | 3 × ? | 6 |\n| 3 | 5 × 4 | 10 × ? | 2 |\n    `,
    mcq1: { questions: [{ question: 'Intersecting chords: 2×9 = 3×?', options: ['6','18','11','5'], correctAnswer: 0, explanation: '18 = 3x → x = 6.' }] },
    mcq2: { questions: [{ question: 'A perpendicular from the center to a chord:', options: ['Bisects the chord','Doubles the chord','Is parallel','Creates a tangent'], correctAnswer: 0, explanation: 'Perpendicular from center bisects chord.' }] },
    input: { boxes: 3, correctAnswers: ['6','6','2'], content: `\n**Intersecting Chords** 🧮\n\n$a \\cdot b = c \\cdot d$\n\n1) 3 × 8 = 4 × ?\n\n2) 2 × 9 = 3 × ?\n\n3) 5 × 4 = 10 × ?\n    `, hint1: '24 ÷ 4.', hint2: '18 ÷ 3.', hint3: '20 ÷ 10.', explanation: '1) 6. 2) 6. 3) 2.' },
    dropdown: { dropdowns: [{ label: 'For intersecting chords, the products of segments are', options: ['Equal','Different','Added','Subtracted'] }, { label: 'The longest chord of a circle is the', options: ['Diameter','Radius','Tangent','Secant'] }], correctAnswers: ['Equal','Diameter'], hint1: 'ab = cd.', hint2: 'Through the center.', explanation: 'Chord segments: ab=cd. Longest chord = diameter.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nApply circle theorems:\n- Identify the given information\n- Choose the right theorem\n- Draw a diagram\n    `, workedContent: `\n## Worked Example\n\n**Pizza slice: r=10, θ=45°. Area of slice? (π≈3.14)**\n\n$\\frac{45}{360} \\times 3.14(100) = \\frac{1}{8}(314) = 39.25$ sq units ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Type |\n|---|---------|------|\n| 1 | Wheel r=14, rotation angle 180° | Arc length |\n| 2 | Clock face, 90° sector, r=6 | Sector area |\n| 3 | Tangent=8, r=6 | Distance |\n    `,
    mcq1: { questions: [{ question: 'Arc length: r=14, θ=180° (π≈3.14)?', options: ['43.96','87.92','21.98','14'], correctAnswer: 0, explanation: '(180/360)(2)(3.14)(14) = 43.96.' }] },
    mcq2: { questions: [{ question: 'r=6, tangent=8. Distance from center?', options: ['10','14','48','2'], correctAnswer: 0, explanation: '√(36+64)=√100=10.' }] },
    input: { boxes: 3, correctAnswers: ['43.96','28.26','10'], content: `\n**Circle Applications** 🧮 (π≈3.14)\n\n1) Arc: r=14, θ=180°. Length?\n\n2) Sector: r=6, θ=90°. Area?\n\n3) r=6, tangent=8. Distance from center?\n    `, hint1: '(1/2)(2)(3.14)(14).', hint2: '(1/4)(3.14)(36).', hint3: '√(36+64).', explanation: '1) 43.96. 2) 28.26. 3) 10.' },
    dropdown: { dropdowns: [{ label: 'A pizza slice is shaped like a', options: ['Sector','Segment','Chord','Tangent'] }, { label: 'The arc of a half-circle is', options: ['A semicircle','A quarter circle','A full circle','A chord'] }], correctAnswers: ['Sector','A semicircle'], hint1: 'Wedge from center.', hint2: '180° arc.', explanation: 'Pizza slice = sector. Half-circle arc = semicircle.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Formulas\n- $d = 2r$\n- Inscribed angle = ½ arc\n- Arc length = $(\\theta/360)(2\\pi r)$\n- Sector area = $(\\theta/360)(\\pi r^2)$\n- Tangent ⊥ radius\n- Intersecting chords: $ab = cd$\n    `, workedContent: `\n## Worked Example\n\n**Inscribed angle for a 120° arc = $\\frac{120}{2} = 60°$ ✅**\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Inscribed angle | Arc = 160° |\n| 2 | Diameter | r = 11 |\n| 3 | Chord | 4×? = 6×2 |\n    `,
    mcq1: { questions: [{ question: 'Inscribed angle for 160° arc?', options: ['80°','160°','320°','40°'], correctAnswer: 0, explanation: '160/2 = 80°.' }] },
    mcq2: { questions: [{ question: '4 × ? = 6 × 2:', options: ['3','4','12','6'], correctAnswer: 0, explanation: '12 = 4x → x = 3.' }] },
    input: { boxes: 3, correctAnswers: ['80','22','3'], content: `\n**Review** 🧮\n\n1) Inscribed angle for 160° arc?\n\n2) r = 11. Diameter?\n\n3) 4 × ? = 6 × 2. Missing value?\n    `, hint1: '160 ÷ 2.', hint2: '2 × 11.', hint3: '12 ÷ 4.', explanation: '1) 80. 2) 22. 3) 3.' },
    dropdown: { dropdowns: [{ label: 'C = 2πr is the formula for', options: ['Circumference','Area','Diameter','Sector area'] }, { label: 'A = πr² is the formula for', options: ['Area of a circle','Circumference','Arc length','Tangent length'] }], correctAnswers: ['Circumference','Area of a circle'], hint1: 'Distance around.', hint2: 'Space inside.', explanation: '2πr = circumference. πr² = area.' }
  }
],

'geometry-coordinate-proofs': [
  { introContent: `\n# 📐 Distance & Midpoint\n\n**Part 1 of 7 — Distance & Midpoint**\n\n$$d = \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}$$\n\n$$M = \\left(\\frac{x_1+x_2}{2}, \\frac{y_1+y_2}{2}\\right)$$\n    `, workedContent: `\n## Worked Example\n\n**(2, 3) and (8, 11).**\n\n$d = \\sqrt{36+64} = \\sqrt{100} = 10$\n$M = (5, 7)$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Points | Distance | Midpoint |\n|---|--------|----------|----------|\n| 1 | (0,0), (3,4) | 5 | (1.5, 2) |\n| 2 | (1,2), (5,5) | 5 | (3, 3.5) |\n| 3 | (−2,1), (4,9) | 10 | (1, 5) |\n    `,
    mcq1: { questions: [{ question: 'Distance from (0,0) to (3,4)?', options: ['5','7','12','25'], correctAnswer: 0, explanation: '√(9+16) = √25 = 5.' }] },
    mcq2: { questions: [{ question: 'Midpoint of (2,6) and (8,10)?', options: ['(5,8)','(10,16)','(6,4)','(3,2)'], correctAnswer: 0, explanation: '((2+8)/2, (6+10)/2) = (5,8).' }] },
    input: { boxes: 3, correctAnswers: ['5','5','10'], content: `\n**Distance** 🧮\n\n1) (0,0) to (3,4). Distance?\n\n2) (1,2) to (5,5). Distance?\n\n3) (−2,1) to (4,9). Distance?\n    `, hint1: '√(9+16).', hint2: '√(16+9).', hint3: '√(36+64).', explanation: '1) √25=5. 2) √25=5. 3) √100=10.' },
    dropdown: { dropdowns: [{ label: 'The midpoint formula averages the', options: ['Coordinates','Distances','Slopes','Areas'] }, { label: 'The distance formula comes from the', options: ['Pythagorean theorem','Midpoint formula','Slope formula','Area formula'] }], correctAnswers: ['Coordinates','Pythagorean theorem'], hint1: 'Average x and y separately.', hint2: 'a²+b²=c².', explanation: 'Midpoint: average coordinates. Distance: Pythagorean theorem.' }
  },
  { introContent: `\n# 📊 Slope in Proofs\n\n**Part 2 of 7 — Slope in Proofs**\n\n$$m = \\frac{y_2-y_1}{x_2-x_1}$$\n\n- **Parallel lines**: same slope ($m_1 = m_2$)\n- **Perpendicular lines**: negative reciprocal slopes ($m_1 \\cdot m_2 = -1$)\n    `, workedContent: `\n## Worked Example\n\n**Lines with slopes 2 and −1/2. Perpendicular?**\n\n$2 \\times (-\\frac{1}{2}) = -1$ → **Yes!** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Slopes | Relationship |\n|---|----|---|\n| 1 | 3, 3 | Parallel |\n| 2 | 2, −1/2 | Perpendicular |\n| 3 | 4, −1/4 | Perpendicular |\n    `,
    mcq1: { questions: [{ question: 'Lines with slopes 3 and 3 are:', options: ['Parallel','Perpendicular','Neither','Identical'], correctAnswer: 0, explanation: 'Same slope = parallel.' }] },
    mcq2: { questions: [{ question: 'Perpendicular to slope 4 has slope:', options: ['−1/4','1/4','−4','4'], correctAnswer: 0, explanation: '4 × (−1/4) = −1.' }] },
    input: { boxes: 3, correctAnswers: ['2','-0.5','-0.25'], content: `\n**Slopes** 🧮\n\n1) Slope of (1,3) and (3,7)?\n\n2) Perpendicular to slope 2?\n\n3) Perpendicular to slope 4?\n    `, hint1: '(7−3)/(3−1).', hint2: 'Negative reciprocal of 2.', hint3: 'Negative reciprocal of 4.', explanation: '1) 4/2=2. 2) −1/2=−0.5. 3) −1/4=−0.25.' },
    dropdown: { dropdowns: [{ label: 'Parallel lines have', options: ['Equal slopes','Perpendicular slopes','No slope','Zero slope'] }, { label: 'Perpendicular slopes multiply to', options: ['−1','0','1','Undefined'] }], correctAnswers: ['Equal slopes','−1'], hint1: 'Same steepness.', hint2: 'm₁ × m₂ = −1.', explanation: 'Parallel: m₁=m₂. Perpendicular: m₁·m₂=−1.' }
  },
  { introContent: `\n# 🔢 Proving Parallel & Perpendicular\n\n**Part 3 of 7 — Proving Parallel & Perpendicular**\n\nTo prove lines are **parallel**: show slopes are equal.\nTo prove lines are **perpendicular**: show slopes multiply to −1.\n\nCalculate slopes from given coordinates, then compare.\n    `, workedContent: `\n## Worked Example\n\n**Are AB and CD parallel? A(1,2), B(3,6), C(0,1), D(2,5).**\n\n$m_{AB} = \\frac{6-2}{3-1} = 2$, $m_{CD} = \\frac{5-1}{2-0} = 2$\n\nEqual slopes → **parallel** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Lines | Slopes | Relation |\n|---|-------|--------|----------|\n| 1 | (0,0)→(1,3) and (2,1)→(3,4) | 3,3 | Parallel |\n| 2 | (0,0)→(1,2) and (0,0)→(2,−1) | 2,−0.5 | Perpendicular |\n    `,
    mcq1: { questions: [{ question: 'To prove two sides are parallel, show:', options: ['Equal slopes','Product of slopes = −1','Equal lengths','Equal areas'], correctAnswer: 0, explanation: 'Parallel = same slope.' }] },
    mcq2: { questions: [{ question: 'Lines (0,0)→(1,2) and (0,0)→(2,−1). Relationship?', options: ['Perpendicular','Parallel','Neither','Identical'], correctAnswer: 0, explanation: '2×(−0.5)=−1.' }] },
    input: { boxes: 3, correctAnswers: ['3','3','2'], content: `\n**Prove Parallel/Perpendicular** 🧮\n\n1) Slope of (0,0) to (1,3)?\n\n2) Slope of (2,1) to (3,4)?\n\n3) Slope of (0,0) to (1,2)?\n    `, hint1: '3/1.', hint2: '(4−1)/(3−2).', hint3: '2/1.', explanation: '1) 3. 2) 3 (parallel to line 1). 3) 2.' },
    dropdown: { dropdowns: [{ label: 'Coordinate proofs use ____ to prove geometric properties', options: ['Algebra and coordinates','Rulers and protractors','Guessing','Theorems only'] }, { label: 'Perpendicular lines form ____ angles', options: ['Right (90°)','Acute','Obtuse','Straight'] }], correctAnswers: ['Algebra and coordinates','Right (90°)'], hint1: 'Analytic geometry.', hint2: '⊥ = 90°.', explanation: 'Coordinate proofs use algebra. Perpendicular = 90°.' }
  },
  { introContent: `\n# 📈 Classifying Quadrilaterals\n\n**Part 4 of 7 — Classifying Quadrilaterals**\n\nUse slopes and distances to classify:\n- **Parallelogram**: 2 pairs of parallel sides\n- **Rectangle**: parallelogram + right angles\n- **Rhombus**: parallelogram + all sides equal\n- **Square**: rectangle + rhombus\n    `, workedContent: `\n## Worked Example\n\n**ABCD: A(0,0), B(4,0), C(4,3), D(0,3). Classify.**\n\nAB = CD = 4 (horizontal), AD = BC = 3 (vertical).\nAll angles 90° → **Rectangle** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Property | Shape |\n|---|---------|-------|\n| 1 | 2 pairs parallel, all sides equal, no right angles | Rhombus |\n| 2 | 2 pairs parallel, right angles, unequal sides | Rectangle |\n| 3 | All sides equal and right angles | Square |\n    `,
    mcq1: { questions: [{ question: 'A square is always a:', options: ['Rectangle','Trapezoid','Triangle','Pentagon'], correctAnswer: 0, explanation: 'Square = special rectangle (all sides equal).' }] },
    mcq2: { questions: [{ question: 'A parallelogram has:', options: ['2 pairs of parallel sides','1 pair of parallel sides','No parallel sides','3 parallel sides'], correctAnswer: 0, explanation: 'Both pairs of opposite sides are parallel.' }] },
    input: { boxes: 3, correctAnswers: ['4','3','5'], content: `\n**Classify ABCD: A(0,0), B(4,0), C(4,3), D(0,3)** 🧮\n\n1) Length AB?\n\n2) Length BC?\n\n3) Length AC (diagonal)?\n    `, hint1: '|4−0|.', hint2: '|3−0|.', hint3: '√(16+9).', explanation: '1) 4. 2) 3. 3) √25=5.' },
    dropdown: { dropdowns: [{ label: 'To prove a quadrilateral is a parallelogram, show', options: ['Both pairs of opposite sides are parallel','One pair parallel','All angles equal','All sides equal'] }, { label: 'A rectangle has ____ right angles', options: ['4','2','1','0'] }], correctAnswers: ['Both pairs of opposite sides are parallel','4'], hint1: 'Two pairs of parallel sides.', hint2: 'All corners are 90°.', explanation: 'Parallelogram: 2 pairs parallel. Rectangle: 4 right angles.' }
  },
  { introContent: `\n# 🧮 Proving Triangle Properties\n\n**Part 5 of 7 — Proving Triangle Properties**\n\nUse coordinates to prove:\n- **Isosceles**: two sides equal (distance formula)\n- **Right triangle**: perpendicular sides (slope product = −1)\n- **Equilateral**: all three sides equal\n    `, workedContent: `\n## Worked Example\n\n**A(0,0), B(4,0), C(2,3). Isosceles?**\n\n$AB = 4$, $AC = \\sqrt{4+9} = \\sqrt{13}$, $BC = \\sqrt{4+9} = \\sqrt{13}$\n\nAC = BC → **Isosceles** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Vertices | Type |\n|---|---------|------|\n| 1 | (0,0),(4,0),(2,3) | Isosceles |\n| 2 | (0,0),(3,0),(0,4) | Right |\n| 3 | (0,0),(6,0),(3,3) | Isosceles |\n    `,
    mcq1: { questions: [{ question: 'To prove a triangle is isosceles, show:', options: ['Two sides are equal','All sides equal','No sides equal','Right angle exists'], correctAnswer: 0, explanation: 'Isosceles = at least 2 equal sides.' }] },
    mcq2: { questions: [{ question: 'For right triangle, two sides must be:', options: ['Perpendicular','Parallel','Equal','Opposite'], correctAnswer: 0, explanation: 'Right angle between two sides → perpendicular.' }] },
    input: { boxes: 3, correctAnswers: ['4','3','5'], content: `\n**Triangle (0,0), (3,0), (0,4)** 🧮\n\n1) Side from (0,0) to (0,4). Length?\n\n2) Side from (0,0) to (3,0). Length?\n\n3) Side from (3,0) to (0,4). Length?\n    `, hint1: '|4−0|.', hint2: '|3−0|.', hint3: '√(9+16).', explanation: '1) 4. 2) 3. 3) √25=5. This is a 3-4-5 right triangle!' },
    dropdown: { dropdowns: [{ label: 'An isosceles triangle has at least', options: ['2 equal sides','3 equal sides','0 equal sides','1 right angle'] }, { label: 'A 3-4-5 right triangle has a hypotenuse of', options: ['5','4','3','12'] }], correctAnswers: ['2 equal sides','5'], hint1: 'At least two sides match.', hint2: 'Longest side.', explanation: 'Isosceles: ≥2 equal sides. 3-4-5: hypotenuse=5.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nCoordinate proof strategy:\n1. Place the figure on a coordinate plane\n2. Assign coordinates to vertices\n3. Use formulas (distance, slope, midpoint)\n4. Draw conclusions\n    `, workedContent: `\n## Worked Example\n\n**Prove the diagonals of rectangle (0,0),(6,0),(6,4),(0,4) are equal.**\n\n$d_1 = \\sqrt{6^2+4^2} = \\sqrt{52}$\n$d_2 = \\sqrt{(-6)^2+4^2} = \\sqrt{52}$\n\nEqual! ✅\n    `, practiceContent: `\n## Practice\n\n| # | Task | Method |\n|---|------|--------|\n| 1 | Midpoint of (0,0)→(6,4) | Midpoint formula |\n| 2 | Is (1,1),(3,5),(5,1) isosceles? | Distance formula |\n| 3 | Diagonal of 3×4 rectangle | Pythagorean theorem |\n    `,
    mcq1: { questions: [{ question: 'Midpoint of (0,0) and (6,4)?', options: ['(3,2)','(6,4)','(3,4)','(0,2)'], correctAnswer: 0, explanation: '((0+6)/2, (0+4)/2) = (3,2).' }] },
    mcq2: { questions: [{ question: 'Diagonal of 3×4 rectangle?', options: ['5','7','12','3.5'], correctAnswer: 0, explanation: '√(9+16) = √25 = 5.' }] },
    input: { boxes: 3, correctAnswers: ['3','2','5'], content: `\n**Coordinate Proofs** 🧮\n\nMidpoint of (0,0) and (6,4):\n\n1) Midpoint x = ?\n\n2) Midpoint y = ?\n\n3) Diagonal of 3×4 rectangle?\n    `, hint1: '(0+6)/2.', hint2: '(0+4)/2.', hint3: '√(9+16).', explanation: '1) 3. 2) 2. 3) 5.' },
    dropdown: { dropdowns: [{ label: 'A good first step in coordinate proofs is to', options: ['Place a vertex at the origin','Guess the answer','Skip the coordinates','Use only one axis'] }, { label: 'The diagonals of a rectangle are', options: ['Equal','Perpendicular','Different','Parallel'] }], correctAnswers: ['Place a vertex at the origin','Equal'], hint1: 'Origin simplifies math.', hint2: 'Rectangle property.', explanation: 'Start at origin. Rectangle diagonals are equal.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Formulas\n- Distance: $\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}$\n- Midpoint: $\\left(\\frac{x_1+x_2}{2}, \\frac{y_1+y_2}{2}\\right)$\n- Slope: $\\frac{y_2-y_1}{x_2-x_1}$\n- Parallel: $m_1 = m_2$; Perpendicular: $m_1 \\cdot m_2 = -1$\n    `, workedContent: `\n## Worked Example\n\n**Distance (1,1) to (4,5):**\n$d = \\sqrt{9+16} = 5$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Distance | (0,0) to (5,12) |\n| 2 | Midpoint | (2,8) and (6,4) |\n| 3 | Slope | (1,3) to (4,9) |\n    `,
    mcq1: { questions: [{ question: 'Distance (0,0) to (5,12)?', options: ['13','17','7','60'], correctAnswer: 0, explanation: '√(25+144)=√169=13.' }] },
    mcq2: { questions: [{ question: 'Slope of (1,3) to (4,9)?', options: ['2','3','6','1/2'], correctAnswer: 0, explanation: '(9−3)/(4−1)=6/3=2.' }] },
    input: { boxes: 3, correctAnswers: ['13','4','2'], content: `\n**Review** 🧮\n\n1) Distance (0,0) to (5,12)?\n\n2) Midpoint x of (2,8) and (6,4)?\n\n3) Slope of (1,3) to (4,9)?\n    `, hint1: '√(25+144).', hint2: '(2+6)/2.', hint3: '6/3.', explanation: '1) 13. 2) 4. 3) 2.' },
    dropdown: { dropdowns: [{ label: 'The distance formula is derived from', options: ['The Pythagorean theorem','The midpoint formula','The slope formula','The quadratic formula'] }, { label: 'Two lines with slopes 3 and 3 are', options: ['Parallel','Perpendicular','Neither','Intersecting at 45°'] }], correctAnswers: ['The Pythagorean theorem','Parallel'], hint1: 'Right triangle on coordinate plane.', hint2: 'Equal slopes.', explanation: 'Distance → Pythagorean theorem. Equal slopes → parallel.' }
  }
],

'geometry-triangle-congruence': [
  { introContent: `\n# 📐 Classifying Triangles\n\n**Part 1 of 7 — Classifying Triangles**\n\n**By sides:**\n- **Scalene**: no equal sides\n- **Isosceles**: 2 equal sides\n- **Equilateral**: 3 equal sides\n\n**By angles:**\n- **Acute**: all angles < 90°\n- **Right**: one 90° angle\n- **Obtuse**: one angle > 90°\n    `, workedContent: `\n## Worked Example\n\n**Sides: 5, 5, 8. Classify.**\n\nTwo equal sides → **Isosceles** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Sides | Classification |\n|---|-------|---------------|\n| 1 | 3, 4, 5 | Scalene right |\n| 2 | 6, 6, 6 | Equilateral |\n| 3 | 7, 7, 10 | Isosceles |\n    `,
    mcq1: { questions: [{ question: 'Sides 6, 6, 6. Classification?', options: ['Equilateral','Isosceles','Scalene','Right'], correctAnswer: 0, explanation: 'All three sides equal.' }] },
    mcq2: { questions: [{ question: 'An equilateral triangle has all angles equal to:', options: ['60°','90°','45°','120°'], correctAnswer: 0, explanation: '180°/3 = 60° each.' }] },
    input: { boxes: 3, correctAnswers: ['60','60','60'], content: `\n**Equilateral Triangle Angles** 🧮\n\n1) Angle A = ?\n\n2) Angle B = ?\n\n3) Angle C = ?\n    `, hint1: '180° ÷ 3.', hint2: 'All angles equal.', hint3: 'All three are the same.', explanation: '1) 60°. 2) 60°. 3) 60°. Total = 180°.' },
    dropdown: { dropdowns: [{ label: 'A triangle with no equal sides is', options: ['Scalene','Isosceles','Equilateral','Right'] }, { label: 'The sum of angles in any triangle is', options: ['180°','360°','90°','270°'] }], correctAnswers: ['Scalene','180°'], hint1: 'No matching sides.', hint2: 'Triangle angle sum.', explanation: 'No equal sides = scalene. Angle sum = 180°.' }
  },
  { introContent: `\n# 📊 Triangle Sum Theorem\n\n**Part 2 of 7 — Triangle Sum Theorem**\n\n$$\\angle A + \\angle B + \\angle C = 180°$$\n\nThe **exterior angle theorem**: an exterior angle equals the sum of the two remote interior angles.\n    `, workedContent: `\n## Worked Example\n\n**Angles: 40° and 75°. Find the third.**\n\n$180 - 40 - 75 = 65°$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Known Angles | Third Angle |\n|---|-------------|----------|\n| 1 | 50°, 60° | 70° |\n| 2 | 90°, 45° | 45° |\n| 3 | 30°, 30° | 120° |\n    `,
    mcq1: { questions: [{ question: 'Angles 50° and 60°. Third angle?', options: ['70°','110°','10°','180°'], correctAnswer: 0, explanation: '180−50−60 = 70°.' }] },
    mcq2: { questions: [{ question: 'Exterior angle = sum of the two ____ interior angles:', options: ['Remote (non-adjacent)','Adjacent','Largest','Smallest'], correctAnswer: 0, explanation: 'The two non-adjacent interior angles.' }] },
    input: { boxes: 3, correctAnswers: ['70','45','120'], content: `\n**Find the Missing Angle** 🧮\n\n1) Angles 50° and 60°. Third?\n\n2) Angles 90° and 45°. Third?\n\n3) Angles 30° and 30°. Third?\n    `, hint1: '180−50−60.', hint2: '180−90−45.', hint3: '180−30−30.', explanation: '1) 70. 2) 45. 3) 120.' },
    dropdown: { dropdowns: [{ label: 'The sum of interior angles in a triangle is always', options: ['180°','360°','90°','Depends on the triangle'] }, { label: 'An exterior angle of a triangle is ____ than either remote interior angle', options: ['Greater','Less','Equal','Unrelated'] }], correctAnswers: ['180°','Greater'], hint1: 'Constant for all triangles.', hint2: 'Sum of two positive numbers.', explanation: 'Always 180°. Exterior angle > either remote angle.' }
  },
  { introContent: `\n# 🔢 SSS & SAS Congruence\n\n**Part 3 of 7 — SSS & SAS Congruence**\n\n**SSS** (Side-Side-Side): all three pairs of sides are equal → congruent.\n\n**SAS** (Side-Angle-Side): two pairs of sides and the **included angle** are equal → congruent.\n\nThe angle must be **between** the two sides (included).\n    `, workedContent: `\n## Worked Example\n\n**△ABC: AB=5, BC=7, ∠B=40°. △DEF: DE=5, EF=7, ∠E=40°.**\n\nSAS: two sides and included angle match → **Congruent** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Given | Postulate |\n|---|-------|----------|\n| 1 | All 3 sides match | SSS |\n| 2 | 2 sides + included angle | SAS |\n| 3 | 2 sides + non-included angle | Not sufficient |\n    `,
    mcq1: { questions: [{ question: 'All three sides match. Which postulate?', options: ['SSS','SAS','ASA','AAS'], correctAnswer: 0, explanation: 'Three sides → SSS.' }] },
    mcq2: { questions: [{ question: 'In SAS, the angle must be:', options: ['Included (between the two sides)','Any angle','The largest angle','Opposite the longest side'], correctAnswer: 0, explanation: 'The angle is between the two known sides.' }] },
    input: { boxes: 3, correctAnswers: ['180','7','40'], content: `\n**Triangle Facts** 🧮\n\nTriangle with sides 5, 7 and ∠ = 40° between them.\n\n1) Sum of all angles?\n\n2) The side opposite angle B if BC = 7?\n\n3) The included angle in the SAS proof?\n    `, hint1: 'Angle sum theorem.', hint2: 'BC = 7.', hint3: 'The angle between the two given sides.', explanation: '1) 180°. 2) 7. 3) 40°.' },
    dropdown: { dropdowns: [{ label: 'SSS requires matching of', options: ['All 3 sides','2 sides and 1 angle','2 angles and 1 side','1 side and 1 angle'] }, { label: 'SAS requires two sides and the ____ angle', options: ['Included','Opposite','Excluded','Any'] }], correctAnswers: ['All 3 sides','Included'], hint1: 'Side-Side-Side.', hint2: 'Between the two sides.', explanation: 'SSS: all 3 sides. SAS: included angle.' }
  },
  { introContent: `\n# 📈 ASA & AAS Congruence\n\n**Part 4 of 7 — ASA & AAS Congruence**\n\n**ASA** (Angle-Side-Angle): two angles and the **included side** → congruent.\n\n**AAS** (Angle-Angle-Side): two angles and a **non-included side** → congruent.\n\nNote: **AAA** proves similarity, not congruence!\n    `, workedContent: `\n## Worked Example\n\n**△PQR: ∠P=50°, PQ=6, ∠Q=70°. △XYZ: ∠X=50°, XY=6, ∠Y=70°.**\n\nASA: two angles with included side → **Congruent** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Given | Postulate |\n|---|-------|----------|\n| 1 | ∠A, AB, ∠B | ASA |\n| 2 | ∠A, ∠B, BC | AAS |\n| 3 | ∠A, ∠B, ∠C | Not sufficient (AAA) |\n    `,
    mcq1: { questions: [{ question: 'Two angles and the included side. Postulate?', options: ['ASA','SSS','SAS','AAS'], correctAnswer: 0, explanation: 'Angle-Side-Angle.' }] },
    mcq2: { questions: [{ question: 'AAA proves:', options: ['Similarity, not congruence','Congruence','Nothing','Both'], correctAnswer: 0, explanation: 'AAA means same shape but possibly different size.' }] },
    input: { boxes: 3, correctAnswers: ['70','60','180'], content: `\n**Angles** 🧮\n\n1) ∠A=50°, ∠B=60°. ∠C=?\n\n2) If △ABC ≅ △DEF and ∠D=50°, ∠F=70°, then ∠E=?\n\n3) Sum of angles in any triangle?\n    `, hint1: '180−50−60.', hint2: '180−50−70.', hint3: 'Angle sum theorem.', explanation: '1) 70. 2) 60. 3) 180.' },
    dropdown: { dropdowns: [{ label: 'ASA stands for', options: ['Angle-Side-Angle','Angle-Side-Any','All-Sides-Angles','Area-Side-Area'] }, { label: 'AAA is NOT sufficient for congruence because', options: ['Triangles can be similar but different sizes','All triangles are congruent','Angles do not matter','Sides are always equal'] }], correctAnswers: ['Angle-Side-Angle','Triangles can be similar but different sizes'], hint1: 'A-S-A.', hint2: 'Same angles, different scale.', explanation: 'ASA: Angle-Side-Angle. AAA → similar, not necessarily congruent.' }
  },
  { introContent: `\n# 🧮 CPCTC Proofs\n\n**Part 5 of 7 — CPCTC Proofs**\n\n**CPCTC**: Corresponding Parts of Congruent Triangles are Congruent.\n\nSteps:\n1. Prove triangles are congruent (SSS, SAS, ASA, AAS)\n2. Conclude that corresponding parts are equal (CPCTC)\n    `, workedContent: `\n## Worked Example\n\n**If △ABC ≅ △DEF by SAS, then AB = DE, BC = EF, AC = DF, ∠A = ∠D, ∠B = ∠E, ∠C = ∠F.** ✅\n    `, practiceContent: `\n## Practice\n\n| # | If △ABC ≅ △DEF | Then |\n|---|----------------|------|\n| 1 | AB corresponds to | DE |\n| 2 | ∠A corresponds to | ∠D |\n| 3 | BC corresponds to | EF |\n    `,
    mcq1: { questions: [{ question: 'CPCTC can be used AFTER:', options: ['Proving triangles are congruent','Finding the area','Measuring angles','Graphing'], correctAnswer: 0, explanation: 'Must prove congruence first.' }] },
    mcq2: { questions: [{ question: 'If △ABC ≅ △DEF, then ∠B = :', options: ['∠E','∠D','∠F','Cannot tell'], correctAnswer: 0, explanation: 'B is the second letter → corresponds to E.' }] },
    input: { boxes: 3, correctAnswers: ['5','7','60'], content: `\n**CPCTC** 🧮\n\n△ABC ≅ △DEF where AB=5, BC=7, ∠C=60°.\n\n1) DE = ?\n\n2) EF = ?\n\n3) ∠F = ?\n    `, hint1: 'AB corresponds to DE.', hint2: 'BC corresponds to EF.', hint3: '∠C corresponds to ∠F.', explanation: '1) DE=AB=5. 2) EF=BC=7. 3) ∠F=∠C=60°.' },
    dropdown: { dropdowns: [{ label: 'CPCTC stands for', options: ['Corresponding Parts of Congruent Triangles are Congruent','Congruent Parts Create Two Congruences','Common Properties of Congruent Triangles','Congruent Parts need Two Conditions'] }, { label: 'CPCTC is used as a ____ in a proof', options: ['Reason (after establishing congruence)','First step','Hypothesis','Definition'] }], correctAnswers: ['Corresponding Parts of Congruent Triangles are Congruent','Reason (after establishing congruence)'], hint1: 'Full name.', hint2: 'Comes after proving ≅.', explanation: 'CPCTC: Corresponding Parts of Congruent Triangles are Congruent. Used as reason after proving congruence.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nApply congruence:\n- Identify given information\n- Choose the right postulate (SSS, SAS, ASA, AAS)\n- Write the proof\n- Use CPCTC as needed\n    `, workedContent: `\n## Worked Example\n\n**Given: AB=CD, BC=DA, AC is shared. Prove △ABC ≅ △CDA.**\n\nAB=CD, BC=DA, AC=AC (reflexive) → SSS → **Congruent** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Given | Postulate |\n|---|-------|----------|\n| 1 | 3 pairs of sides equal | SSS |\n| 2 | 2 sides + included angle | SAS |\n| 3 | Shared side + 2 angles | ASA |\n    `,
    mcq1: { questions: [{ question: 'A shared side in two triangles uses the ____ property:', options: ['Reflexive','Symmetric','Transitive','Commutative'], correctAnswer: 0, explanation: 'A segment is congruent to itself.' }] },
    mcq2: { questions: [{ question: 'Which is NOT a valid congruence postulate?', options: ['SSA','SSS','SAS','ASA'], correctAnswer: 0, explanation: 'SSA (or ASS) is ambiguous and not valid.' }] },
    input: { boxes: 3, correctAnswers: ['180','5','3'], content: `\n**Apply Congruence** 🧮\n\n1) Sum of angles in any triangle?\n\n2) △ABC ≅ △DEF, AB=5. What is DE?\n\n3) How many postulates prove congruence? (SSS, SAS, ASA)\n    `, hint1: 'Angle sum.', hint2: 'Corresponding parts.', hint3: 'Count: SSS, SAS, ASA (also AAS).', explanation: '1) 180°. 2) 5 (CPCTC). 3) 3 basic (plus AAS = 4).' },
    dropdown: { dropdowns: [{ label: 'The reflexive property states', options: ['A segment equals itself','Two segments are equal','Segments can be added','Segments are parallel'] }, { label: 'SSA is ____ for proving congruence', options: ['Not sufficient','Sufficient','The best method','Required'] }], correctAnswers: ['A segment equals itself','Not sufficient'], hint1: 'Self-equality.', hint2: 'Ambiguous case.', explanation: 'Reflexive: AB=AB. SSA is not sufficient.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Congruence Postulates\n| Postulate | Requires |\n|-----------|----------|\n| SSS | 3 pairs of sides |\n| SAS | 2 sides + included angle |\n| ASA | 2 angles + included side |\n| AAS | 2 angles + non-included side |\n\n**CPCTC**: use after proving congruence.\n    `, workedContent: `\n## Worked Example\n\n**△ABC: ∠A=40°, ∠B=80°. ∠C?**\n$180 - 40 - 80 = 60°$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Angle sum | 55°, 65°, ? |\n| 2 | Postulate | 3 sides → ? |\n| 3 | CPCTC | ≅ triangles, AB=8, DE=? |\n    `,
    mcq1: { questions: [{ question: 'Angles 55° and 65°. Third?', options: ['60°','120°','10°','180°'], correctAnswer: 0, explanation: '180−55−65=60°.' }] },
    mcq2: { questions: [{ question: '3 pairs of equal sides → which postulate?', options: ['SSS','SAS','ASA','AAS'], correctAnswer: 0, explanation: 'Side-Side-Side.' }] },
    input: { boxes: 3, correctAnswers: ['60','8','4'], content: `\n**Review** 🧮\n\n1) Angles 55°, 65°. Third?\n\n2) △ABC ≅ △DEF, AB=8. DE=?\n\n3) How many congruence postulates (SSS, SAS, ASA, AAS)?\n    `, hint1: '180−55−65.', hint2: 'Corresponding parts.', hint3: 'Count them.', explanation: '1) 60. 2) 8. 3) 4.' },
    dropdown: { dropdowns: [{ label: 'Congruent triangles have identical', options: ['Shape and size','Shape only','Size only','Angles only'] }, { label: 'The postulate that does NOT work is', options: ['SSA','SSS','SAS','ASA'] }], correctAnswers: ['Shape and size','SSA'], hint1: 'Same everything.', hint2: 'The ambiguous one.', explanation: 'Congruent: same shape and size. SSA is not valid.' }
  }
]

};
