/**
 * Content patches for Grade 8 topics:
 * - grade8-linear-functions (7 parts)
 * - grade8-pythagorean-theorem (7 parts)
 * - grade8-transformations (7 parts)
 */
module.exports = {

'grade8-linear-functions': [
  { introContent: `\n# 📐 Functions & Relations\n\n**Part 1 of 7 — Functions & Relations**\n\nA **function** assigns each input exactly **one** output.\n\nRepresentations: mapping, table, graph, equation.\n\n**Vertical Line Test**: if any vertical line crosses the graph more than once, it is **not** a function.\n    `, workedContent: `\n## Worked Example\n\n**Is {(1,3), (2,5), (3,7), (1,4)} a function?**\n\nInput 1 maps to 3 and 4 — two outputs. **Not a function.** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Set | Function? |\n|---|-----|----------|\n| 1 | (1,2),(2,4),(3,6) | Yes |\n| 2 | (1,3),(1,5),(2,4) | No |\n| 3 | (0,0),(1,1),(2,4) | Yes |\n    `,
    mcq1: { questions: [{ question: 'Which is NOT a function?', options: ['{(1,2),(1,3),(2,4)}','{(1,2),(2,3),(3,4)}','{(0,0),(1,1),(2,2)}','{(−1,1),(0,0),(1,1)}'], correctAnswer: 0, explanation: 'Input 1 has two outputs (2 and 3).' }] },
    mcq2: { questions: [{ question: 'The vertical line test tells us:', options: ['If a graph is a function','If a graph is linear','The slope','The y-intercept'], correctAnswer: 0, explanation: 'Vertical line test checks for functions.' }] },
    input: { boxes: 3, correctAnswers: ['5','7','9'], content: `\n**Functions** 🧮\n\n$f(x) = 2x + 1$\n\n1) $f(2) = ?$\n\n2) $f(3) = ?$\n\n3) $f(4) = ?$\n    `, hint1: '2(2) + 1.', hint2: '2(3) + 1.', hint3: '2(4) + 1.', explanation: '1) 5. 2) 7. 3) 9.' },
    dropdown: { dropdowns: [{ label: 'A function gives each input', options: ['Exactly one output','Two outputs','No output','Multiple outputs'] }, { label: 'The vertical line test checks if a graph is a', options: ['Function','Line','Parabola','Circle'] }], correctAnswers: ['Exactly one output','Function'], hint1: 'One input → one output.', hint2: 'VLT → function test.', explanation: 'Function: one output per input. VLT checks this on graphs.' }
  },
  { introContent: `\n# 📊 Slope from Tables & Graphs\n\n**Part 2 of 7 — Slope from Tables & Graphs**\n\n$$\\text{slope} = m = \\frac{\\Delta y}{\\Delta x} = \\frac{y_2 - y_1}{x_2 - x_1}$$\n\n- Positive slope: rises left to right\n- Negative slope: falls left to right\n- Zero slope: horizontal\n- Undefined slope: vertical\n    `, workedContent: `\n## Worked Example\n\n**Points (1, 3) and (4, 9).**\n\n$m = \\frac{9 - 3}{4 - 1} = \\frac{6}{3} = 2$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Points | Slope |\n|---|--------|-------|\n| 1 | (0,1) and (2,5) | 2 |\n| 2 | (1,6) and (3,2) | −2 |\n| 3 | (0,0) and (4,12) | 3 |\n    `,
    mcq1: { questions: [{ question: 'Slope of (0,1) and (2,5)?', options: ['2','3','1/2','4'], correctAnswer: 0, explanation: '(5−1)/(2−0) = 4/2 = 2.' }] },
    mcq2: { questions: [{ question: 'A horizontal line has slope:', options: ['0','Undefined','1','−1'], correctAnswer: 0, explanation: 'Horizontal → no rise → slope = 0.' }] },
    input: { boxes: 3, correctAnswers: ['2','-2','3'], content: `\n**Find the Slope** 🧮\n\n1) (0,1) and (2,5). m = ?\n\n2) (1,6) and (3,2). m = ?\n\n3) (0,0) and (4,12). m = ?\n    `, hint1: '(5−1)/(2−0).', hint2: '(2−6)/(3−1).', hint3: '(12−0)/(4−0).', explanation: '1) 4/2=2. 2) −4/2=−2. 3) 12/4=3.' },
    dropdown: { dropdowns: [{ label: 'Positive slope means the line', options: ['Rises left to right','Falls left to right','Is horizontal','Is vertical'] }, { label: 'Undefined slope means the line is', options: ['Vertical','Horizontal','Diagonal','Curved'] }], correctAnswers: ['Rises left to right','Vertical'], hint1: 'Positive = uphill.', hint2: 'Divide by zero = undefined.', explanation: 'Positive slope → rises. Undefined → vertical.' }
  },
  { introContent: `\n# 🔢 Writing Linear Equations\n\n**Part 3 of 7 — Writing Linear Equations**\n\n**Slope-intercept form**: $y = mx + b$\n- $m$ = slope\n- $b$ = y-intercept\n\nGiven slope and a point, plug in to find $b$.\n    `, workedContent: `\n## Worked Example\n\n**Slope 3, passes through (2, 10).**\n\n$10 = 3(2) + b \\Rightarrow 10 = 6 + b \\Rightarrow b = 4$\n\n$y = 3x + 4$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Given | Equation |\n|---|-------|----------|\n| 1 | m=2, (1,5) | y = 2x + 3 |\n| 2 | m=−1, (0,4) | y = −x + 4 |\n| 3 | (0,2) and (3,8) | y = 2x + 2 |\n    `,
    mcq1: { questions: [{ question: 'In $y = 3x + 4$, the y-intercept is:', options: ['4','3','7','−4'], correctAnswer: 0, explanation: 'b = 4 in y = mx + b.' }] },
    mcq2: { questions: [{ question: 'Line with m=2 through (1,5). What is b?', options: ['3','5','2','7'], correctAnswer: 0, explanation: '5 = 2(1) + b → b = 3.' }] },
    input: { boxes: 3, correctAnswers: ['3','4','2'], content: `\n**Find b** 🧮\n\n1) $m = 2$, point $(1, 5)$. $b = ?$\n\n2) $m = -1$, point $(0, 4)$. $b = ?$\n\n3) Points $(0, 2)$ and $(3, 8)$. $b = ?$\n    `, hint1: '5 = 2(1) + b.', hint2: 'Point (0,4) means b = 4.', hint3: '(0,2) → b = 2.', explanation: '1) 5−2=3. 2) 4. 3) 2.' },
    dropdown: { dropdowns: [{ label: 'In y = mx + b, m is the', options: ['Slope','Y-intercept','X-intercept','Constant'] }, { label: 'The y-intercept is the point where the line crosses the', options: ['Y-axis','X-axis','Origin','Diagonal'] }], correctAnswers: ['Slope','Y-axis'], hint1: 'm = rate of change.', hint2: 'When x = 0.', explanation: 'm = slope. Y-intercept: where line hits the y-axis.' }
  },
  { introContent: `\n# 📈 Comparing Functions\n\n**Part 4 of 7 — Comparing Functions**\n\nCompare functions using:\n- **Rate of change** (slope)\n- **Initial value** (y-intercept)\n- **Tables, graphs, and equations**\n\nThe function with a greater slope grows faster.\n    `, workedContent: `\n## Worked Example\n\n**Function A: $y = 3x + 1$. Function B: table (0,2),(1,4),(2,6).**\n\nA: slope = 3, intercept = 1.\nB: slope = (4−2)/(1−0) = 2, intercept = 2.\n\nA grows faster (slope 3 > 2). B starts higher (intercept 2 > 1). ✅\n    `, practiceContent: `\n## Practice\n\n| # | Comparison | Greater slope |\n|---|-----------|---------------|\n| 1 | y=4x vs y=2x+5 | y = 4x |\n| 2 | y=x+10 vs y=3x | y = 3x |\n| 3 | y=5x−1 vs y=5x+3 | Same slope |\n    `,
    mcq1: { questions: [{ question: 'Which grows faster: $y=4x$ or $y=2x+5$?', options: ['y = 4x','y = 2x + 5','They grow equally','Cannot tell'], correctAnswer: 0, explanation: 'Slope 4 > slope 2.' }] },
    mcq2: { questions: [{ question: '$y=5x−1$ and $y=5x+3$ have:', options: ['Same slope, different intercepts','Same intercept, different slopes','Nothing in common','Same everything'], correctAnswer: 0, explanation: 'Both have slope 5, different b values.' }] },
    input: { boxes: 3, correctAnswers: ['4','3','5'], content: `\n**Compare Slopes** 🧮\n\n1) $y = 4x + 1$. Slope = ?\n\n2) Table: (0,0), (1,3), (2,6). Slope = ?\n\n3) $y = 5x - 2$. Slope = ?\n    `, hint1: 'Coefficient of x.', hint2: '(3−0)/(1−0).', hint3: 'Coefficient of x.', explanation: '1) 4. 2) 3. 3) 5.' },
    dropdown: { dropdowns: [{ label: 'The function with GREATER slope', options: ['Increases faster','Starts higher','Is always larger','Has more points'] }, { label: 'Two lines with the same slope are', options: ['Parallel','Perpendicular','Identical','Intersecting'] }], correctAnswers: ['Increases faster','Parallel'], hint1: 'Steeper = grows faster.', hint2: 'Same slope = never intersect.', explanation: 'Greater slope → faster increase. Same slope → parallel.' }
  },
  { introContent: `\n# 🧮 Systems Introduction\n\n**Part 5 of 7 — Systems Introduction**\n\nA **system of equations** is two equations with two variables.\n\nThe **solution** is the point where both lines intersect.\n\nSolving: graphing, substitution, or elimination.\n    `, workedContent: `\n## Worked Example\n\n**$y = x + 1$ and $y = 2x - 1$.**\n\nSet equal: $x + 1 = 2x - 1 \\Rightarrow 2 = x$. Then $y = 2 + 1 = 3$.\n\nSolution: $(2, 3)$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | System | Solution |\n|---|--------|---------|\n| 1 | y=x, y=2x−3 | (3,3) |\n| 2 | y=3x+1, y=x+5 | (2,7) |\n| 3 | y=2x, y=x+4 | (4,8) |\n    `,
    mcq1: { questions: [{ question: 'Solution to $y=x$ and $y=2x−3$?', options: ['(3,3)','(1,1)','(0,0)','(−3,−3)'], correctAnswer: 0, explanation: 'x = 2x−3 → x = 3, y = 3.' }] },
    mcq2: { questions: [{ question: 'A system with no solution means the lines are:', options: ['Parallel','Perpendicular','Identical','Intersecting'], correctAnswer: 0, explanation: 'No intersection = parallel lines.' }] },
    input: { boxes: 3, correctAnswers: ['3','2','4'], content: `\n**Find X** 🧮\n\n1) $y = x$ and $y = 2x - 3$. $x = ?$\n\n2) $y = 3x + 1$ and $y = x + 5$. $x = ?$\n\n3) $y = 2x$ and $y = x + 4$. $x = ?$\n    `, hint1: 'x = 2x − 3.', hint2: '3x+1 = x+5.', hint3: '2x = x+4.', explanation: '1) x=3. 2) 2x=4→x=2. 3) x=4.' },
    dropdown: { dropdowns: [{ label: 'The solution to a system is where lines', options: ['Intersect','Are parallel','Touch the x-axis','Have the same slope'] }, { label: 'If two lines have different slopes, they have', options: ['Exactly one solution','No solution','Infinite solutions','Two solutions'] }], correctAnswers: ['Intersect','Exactly one solution'], hint1: 'Lines cross at the solution.', hint2: 'Different slopes → one crossing.', explanation: 'Solution = intersection point. Different slopes → one solution.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nApply linear function skills:\n- Model with equations\n- Interpret slope as rate and intercept as starting value\n- Solve real-world problems\n    `, workedContent: `\n## Worked Example\n\n**Taxi: \\$3 base + \\$2/mile. Equation? Cost for 7 miles?**\n\n$C = 2m + 3$. For 7 miles: $C = 2(7) + 3 = 17$ → **\\$17** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Equation |\n|---|---------|----------|\n| 1 | Gym: \\$50 join + \\$30/mo | C = 30m + 50 |\n| 2 | Phone: \\$40/mo + \\$0.10/text | C = 0.10t + 40 |\n| 3 | Savings: \\$100 + \\$25/week | S = 25w + 100 |\n    `,
    mcq1: { questions: [{ question: 'Gym: $50 join + $30/mo. Cost after 6 months?', options: ['$230','$180','$80','$480'], correctAnswer: 0, explanation: '30(6) + 50 = 180 + 50 = 230.' }] },
    mcq2: { questions: [{ question: 'In C = 2m + 3, the slope 2 represents:', options: ['Cost per mile','Starting cost','Total miles','Total cost'], correctAnswer: 0, explanation: 'Slope = rate = cost per mile.' }] },
    input: { boxes: 3, correctAnswers: ['230','90','250'], content: `\n**Word Problems** 🧮\n\n1) Gym: \\$50 + \\$30/month. Cost after 6 months?\n\n2) Phone: \\$40 + \\$0.10/text. Cost for 500 texts?\n\n3) Savings: \\$100 + \\$25/week. Total after 6 weeks?\n    `, hint1: '30(6) + 50.', hint2: '0.10(500) + 40.', hint3: '25(6) + 100.', explanation: '1) 180+50=230. 2) 50+40=90. 3) 150+100=250.' },
    dropdown: { dropdowns: [{ label: 'In C = mx + b, the slope m represents the', options: ['Rate of change','Starting value','Total','Maximum'] }, { label: 'The y-intercept b represents the', options: ['Starting value','Rate','Slope','End value'] }], correctAnswers: ['Rate of change','Starting value'], hint1: 'Slope = unit rate.', hint2: 'At x=0.', explanation: 'm = rate of change. b = starting value (initial amount).' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Concepts\n- Function: one output per input\n- Slope: $m = \\frac{y_2-y_1}{x_2-x_1}$\n- Slope-intercept: $y = mx + b$\n- System solution: intersection point\n    `, workedContent: `\n## Worked Example\n\n**Line through (1,4) and (3,10). Equation?**\n\n$m = \\frac{10-4}{3-1} = 3$. Then $4 = 3(1) + b \\Rightarrow b = 1$.\n$y = 3x + 1$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Slope | (2,3) and (5,9) |\n| 2 | Evaluate | f(x)=4x−1, f(3) |\n| 3 | System | y=x+1, y=3x−5 |\n    `,
    mcq1: { questions: [{ question: 'Slope of (2,3) and (5,9)?', options: ['2','3','6','1/2'], correctAnswer: 0, explanation: '(9−3)/(5−2) = 6/3 = 2.' }] },
    mcq2: { questions: [{ question: '$f(x)=4x−1$. $f(3)=?$', options: ['11','12','13','7'], correctAnswer: 0, explanation: '4(3)−1 = 12−1 = 11.' }] },
    input: { boxes: 3, correctAnswers: ['2','11','3'], content: `\n**Review** 🧮\n\n1) Slope of (2,3) and (5,9)?\n\n2) $f(x) = 4x - 1$. $f(3) = ?$\n\n3) $y = x+1$ and $y = 3x-5$. $x = ?$\n    `, hint1: '(9−3)/(5−2).', hint2: '4(3) − 1.', hint3: 'x+1 = 3x−5 → 6=2x.', explanation: '1) 6/3=2. 2) 11. 3) x=3.' },
    dropdown: { dropdowns: [{ label: 'y = mx + b is called', options: ['Slope-intercept form','Standard form','Point-slope form','Vertex form'] }, { label: 'Two parallel lines have', options: ['Same slope','Same intercept','Different slopes','Same everything'] }], correctAnswers: ['Slope-intercept form','Same slope'], hint1: 'Slope + intercept.', hint2: 'Parallel = same steepness.', explanation: 'y=mx+b is slope-intercept form. Parallel lines share slope.' }
  }
],

'grade8-pythagorean-theorem': [
  { introContent: `\n# 📐 Understanding the Theorem\n\n**Part 1 of 7 — Understanding the Theorem**\n\nIn a right triangle with legs $a$ and $b$ and hypotenuse $c$:\n\n$$a^2 + b^2 = c^2$$\n\nThe **hypotenuse** is always the longest side, opposite the right angle.\n    `, workedContent: `\n## Worked Example\n\n**Legs: 3 and 4. Find hypotenuse.**\n\n$3^2 + 4^2 = 9 + 16 = 25$\n$c = \\sqrt{25} = 5$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Legs | Hypotenuse |\n|---|------|------------|\n| 1 | 3, 4 | 5 |\n| 2 | 5, 12 | 13 |\n| 3 | 6, 8 | 10 |\n    `,
    mcq1: { questions: [{ question: 'In a right triangle, the hypotenuse is:', options: ['The longest side','The shortest side','Any side','A leg'], correctAnswer: 0, explanation: 'Hypotenuse = longest, opposite right angle.' }] },
    mcq2: { questions: [{ question: 'Legs 5 and 12. Hypotenuse?', options: ['13','17','7','60'], correctAnswer: 0, explanation: '25 + 144 = 169. √169 = 13.' }] },
    input: { boxes: 3, correctAnswers: ['5','13','10'], content: `\n**Find the Hypotenuse** 🧮\n\n1) Legs 3, 4. c = ?\n\n2) Legs 5, 12. c = ?\n\n3) Legs 6, 8. c = ?\n    `, hint1: '9 + 16 = 25. √25.', hint2: '25 + 144 = 169. √169.', hint3: '36 + 64 = 100. √100.', explanation: '1) 5. 2) 13. 3) 10.' },
    dropdown: { dropdowns: [{ label: 'The Pythagorean theorem applies to', options: ['Right triangles only','All triangles','Rectangles','Circles'] }, { label: '$a^2 + b^2 = c^2$ — c is the', options: ['Hypotenuse','Shorter leg','Longer leg','Any side'] }], correctAnswers: ['Right triangles only','Hypotenuse'], hint1: 'Must have a 90° angle.', hint2: 'c = longest side.', explanation: 'Only right triangles. c = hypotenuse.' }
  },
  { introContent: `\n# 📊 Finding Missing Sides\n\n**Part 2 of 7 — Finding Missing Sides**\n\nTo find a **leg**: $a = \\sqrt{c^2 - b^2}$\n\nAlways identify: which side is the hypotenuse?\n    `, workedContent: `\n## Worked Example\n\n**Hypotenuse 10, one leg 6. Find the other leg.**\n\n$a = \\sqrt{10^2 - 6^2} = \\sqrt{100 - 36} = \\sqrt{64} = 8$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Known | Find |\n|---|-------|------|\n| 1 | c=13, a=5 | b=12 |\n| 2 | c=15, a=9 | b=12 |\n| 3 | c=17, a=8 | b=15 |\n    `,
    mcq1: { questions: [{ question: 'c=13, a=5. b=?', options: ['12','8','18','14'], correctAnswer: 0, explanation: '169−25=144. √144=12.' }] },
    mcq2: { questions: [{ question: 'c=15, a=9. b=?', options: ['12','6','24','18'], correctAnswer: 0, explanation: '225−81=144. √144=12.' }] },
    input: { boxes: 3, correctAnswers: ['12','12','15'], content: `\n**Find the Missing Leg** 🧮\n\n1) c=13, a=5. b = ?\n\n2) c=15, a=9. b = ?\n\n3) c=17, a=8. b = ?\n    `, hint1: '169 − 25.', hint2: '225 − 81.', hint3: '289 − 64.', explanation: '1) √144=12. 2) √144=12. 3) √225=15.' },
    dropdown: { dropdowns: [{ label: 'To find a missing leg, use', options: ['$a = \\sqrt{c^2 - b^2}$','$a = c + b$','$a = c \\times b$','$a = c - b$'] }, { label: 'The hypotenuse is always the ____ value', options: ['Largest','Smallest','Middle','Unknown'] }], correctAnswers: ['$a = \\sqrt{c^2 - b^2}$','Largest'], hint1: 'Rearrange a²+b²=c².', hint2: 'Opposite the largest angle.', explanation: 'Leg = √(c²−b²). Hypotenuse is the largest side.' }
  },
  { introContent: `\n# 🔢 Distance Between Points\n\n**Part 3 of 7 — Distance Between Points**\n\nThe **distance formula** comes from the Pythagorean theorem:\n\n$$d = \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}$$\n\nThe horizontal and vertical differences form the legs of a right triangle.\n    `, workedContent: `\n## Worked Example\n\n**Distance between (1, 2) and (4, 6).**\n\n$d = \\sqrt{(4-1)^2 + (6-2)^2} = \\sqrt{9+16} = \\sqrt{25} = 5$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Points | Distance |\n|---|--------|----------|\n| 1 | (0,0) and (3,4) | 5 |\n| 2 | (1,2) and (4,6) | 5 |\n| 3 | (0,0) and (5,12) | 13 |\n    `,
    mcq1: { questions: [{ question: 'Distance from (0,0) to (3,4)?', options: ['5','7','12','25'], correctAnswer: 0, explanation: '√(9+16) = √25 = 5.' }] },
    mcq2: { questions: [{ question: 'The distance formula is derived from:', options: ['The Pythagorean theorem','Area formula','Slope formula','Midpoint formula'], correctAnswer: 0, explanation: 'Distance formula = Pythagorean theorem on coordinate plane.' }] },
    input: { boxes: 3, correctAnswers: ['5','5','13'], content: `\n**Find the Distance** 🧮\n\n1) (0,0) to (3,4). d = ?\n\n2) (1,2) to (4,6). d = ?\n\n3) (0,0) to (5,12). d = ?\n    `, hint1: '√(9+16).', hint2: '√(9+16).', hint3: '√(25+144).', explanation: '1) √25=5. 2) √25=5. 3) √169=13.' },
    dropdown: { dropdowns: [{ label: 'The distance formula uses a', options: ['Square root','Cube root','Fourth root','No root'] }, { label: 'The differences (x₂−x₁) and (y₂−y₁) represent', options: ['Legs of a right triangle','The hypotenuse','The slope','The area'] }], correctAnswers: ['Square root','Legs of a right triangle'], hint1: 'Final step: take the square root.', hint2: 'Horizontal and vertical legs.', explanation: 'Distance uses square root. Differences = triangle legs.' }
  },
  { introContent: `\n# 📈 Converse of Pythagorean Theorem\n\n**Part 4 of 7 — Converse of Pythagorean Theorem**\n\nIf $a^2 + b^2 = c^2$, the triangle is a **right triangle**.\n\nIf $a^2 + b^2 > c^2$, it's **acute**.\nIf $a^2 + b^2 < c^2$, it's **obtuse**.\n    `, workedContent: `\n## Worked Example\n\n**Sides 7, 24, 25. Right triangle?**\n\n$7^2 + 24^2 = 49 + 576 = 625 = 25^2$ → **Yes, right triangle!** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Sides | Type |\n|---|-------|------|\n| 1 | 3, 4, 5 | Right |\n| 2 | 5, 6, 8 | Obtuse |\n| 3 | 4, 5, 6 | Acute |\n    `,
    mcq1: { questions: [{ question: 'Sides 5, 12, 13. Right triangle?', options: ['Yes, 25+144=169','No','Acute','Obtuse'], correctAnswer: 0, explanation: '25+144=169=13². Right triangle.' }] },
    mcq2: { questions: [{ question: 'If $a^2 + b^2 < c^2$, the triangle is:', options: ['Obtuse','Acute','Right','Equilateral'], correctAnswer: 0, explanation: 'Sum less than c² → obtuse.' }] },
    input: { boxes: 3, correctAnswers: ['625','169','100'], content: `\n**Check: $a^2 + b^2 = ?$** 🧮\n\n1) a=7, b=24. $a^2 + b^2 = ?$\n\n2) a=5, b=12. $a^2 + b^2 = ?$\n\n3) a=6, b=8. $a^2 + b^2 = ?$\n    `, hint1: '49 + 576.', hint2: '25 + 144.', hint3: '36 + 64.', explanation: '1) 625. 2) 169. 3) 100. All equal c², so all right triangles.' },
    dropdown: { dropdowns: [{ label: '$a^2 + b^2 = c^2$ means the triangle is', options: ['Right','Acute','Obtuse','Equilateral'] }, { label: '$a^2 + b^2 > c^2$ means the triangle is', options: ['Acute','Right','Obtuse','Impossible'] }], correctAnswers: ['Right','Acute'], hint1: 'Equals → right angle.', hint2: 'Greater → all angles < 90°.', explanation: '= c²: right. > c²: acute. < c²: obtuse.' }
  },
  { introContent: `\n# 🧮 3D Applications\n\n**Part 5 of 7 — 3D Applications**\n\nThe Pythagorean theorem extends to 3D:\n\n$$d = \\sqrt{l^2 + w^2 + h^2}$$\n\n**Space diagonal of a box**: finds the longest line from corner to opposite corner.\n    `, workedContent: `\n## Worked Example\n\n**Box 3×4×12. Space diagonal?**\n\n$d = \\sqrt{3^2+4^2+12^2} = \\sqrt{9+16+144} = \\sqrt{169} = 13$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Dimensions | Diagonal |\n|---|-----------|----------|\n| 1 | 3×4×12 | 13 |\n| 2 | 1×2×2 | 3 |\n| 3 | 2×6×9 | 11 |\n    `,
    mcq1: { questions: [{ question: '3D diagonal of 1×2×2 box?', options: ['3','5','√5','1'], correctAnswer: 0, explanation: '√(1+4+4) = √9 = 3.' }] },
    mcq2: { questions: [{ question: 'The space diagonal of a box is ____ than any edge.', options: ['Longer','Shorter','Equal','Unrelated'], correctAnswer: 0, explanation: 'The diagonal spans all three dimensions.' }] },
    input: { boxes: 3, correctAnswers: ['13','3','11'], content: `\n**Space Diagonals** 🧮\n\n1) Box 3×4×12. Diagonal?\n\n2) Box 1×2×2. Diagonal?\n\n3) Box 2×6×9. Diagonal?\n    `, hint1: '√(9+16+144).', hint2: '√(1+4+4).', hint3: '√(4+36+81).', explanation: '1) √169=13. 2) √9=3. 3) √121=11.' },
    dropdown: { dropdowns: [{ label: '3D distance uses ____ dimensions', options: ['Three','Two','One','Four'] }, { label: 'The formula for 3D diagonal is', options: ['$\\sqrt{l^2+w^2+h^2}$','$l+w+h$','$lwh$','$2(l+w+h)$'] }], correctAnswers: ['Three','$\\sqrt{l^2+w^2+h^2}$'], hint1: 'Length, width, height.', hint2: 'Square, add, square root.', explanation: '3D uses three dimensions. d = √(l²+w²+h²).' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nReal-world Pythagorean theorem:\n- Ladder against a wall\n- Television screen size (diagonal)\n- Walking shortest path\n    `, workedContent: `\n## Worked Example\n\n**Ladder: 10 ft long, base 6 ft from wall. How high does it reach?**\n\n$h = \\sqrt{10^2 - 6^2} = \\sqrt{100-36} = \\sqrt{64} = 8$ ft ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Answer |\n|---|---------|--------|\n| 1 | Ladder 13 ft, 5 ft from wall | 12 ft |\n| 2 | TV: 16×12 screen | 20 in |\n| 3 | Walk: 9 blocks E, 12 blocks N | 15 blocks |\n    `,
    mcq1: { questions: [{ question: 'Ladder 13 ft, 5 ft from wall. Height?', options: ['12 ft','8 ft','18 ft','14 ft'], correctAnswer: 0, explanation: '√(169−25) = √144 = 12.' }] },
    mcq2: { questions: [{ question: 'TV screen 16×12. Diagonal?', options: ['20 in','28 in','14 in','192 in'], correctAnswer: 0, explanation: '√(256+144) = √400 = 20.' }] },
    input: { boxes: 3, correctAnswers: ['12','20','15'], content: `\n**Word Problems** 🧮\n\n1) Ladder 13 ft, base 5 ft from wall. Height?\n\n2) TV screen 16 × 12. Diagonal?\n\n3) Walk 9 blocks east, 12 blocks north. Direct distance?\n    `, hint1: '√(169−25).', hint2: '√(256+144).', hint3: '√(81+144).', explanation: '1) √144=12. 2) √400=20. 3) √225=15.' },
    dropdown: { dropdowns: [{ label: 'A TV screen size refers to its', options: ['Diagonal','Width','Height','Area'] }, { label: 'A ladder, wall, and ground form a', options: ['Right triangle','Square','Circle','Cube'] }], correctAnswers: ['Diagonal','Right triangle'], hint1: 'Measured corner to corner.', hint2: 'Wall is perpendicular to ground.', explanation: 'TV size = diagonal. Ladder/wall/ground = right triangle.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Formulas\n- $a^2 + b^2 = c^2$\n- Leg: $a = \\sqrt{c^2 - b^2}$\n- Distance: $d = \\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}$\n- 3D diagonal: $d = \\sqrt{l^2+w^2+h^2}$\n- Converse: classify triangle by comparing $a^2+b^2$ to $c^2$\n    `, workedContent: `\n## Worked Example\n\n**Legs 8 and 15. Hypotenuse?**\n$c = \\sqrt{64+225} = \\sqrt{289} = 17$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Hypotenuse | Legs 8, 15 |\n| 2 | Leg | c=25, a=7 |\n| 3 | Distance | (0,0) to (6,8) |\n    `,
    mcq1: { questions: [{ question: 'Legs 8 and 15. Hypotenuse?', options: ['17','23','√23','289'], correctAnswer: 0, explanation: '64+225=289. √289=17.' }] },
    mcq2: { questions: [{ question: 'c=25, a=7. b=?', options: ['24','18','32','625'], correctAnswer: 0, explanation: '625−49=576. √576=24.' }] },
    input: { boxes: 3, correctAnswers: ['17','24','10'], content: `\n**Review** 🧮\n\n1) Legs 8, 15. c = ?\n\n2) c=25, a=7. b = ?\n\n3) Distance: (0,0) to (6,8). d = ?\n    `, hint1: '64+225.', hint2: '625−49.', hint3: '36+64.', explanation: '1) √289=17. 2) √576=24. 3) √100=10.' },
    dropdown: { dropdowns: [{ label: 'The Pythagorean theorem is for', options: ['Right triangles','All triangles','Circles','Squares'] }, { label: '$a^2+b^2 > c^2$ classifies as', options: ['Acute','Obtuse','Right','Equilateral'] }], correctAnswers: ['Right triangles','Acute'], hint1: 'Need a 90° angle.', hint2: 'Greater → all acute angles.', explanation: 'Right triangles only. a²+b² > c² → acute.' }
  }
],

'grade8-transformations': [
  { introContent: `\n# 📐 Translations\n\n**Part 1 of 7 — Translations**\n\nA **translation** slides every point the same distance and direction.\n\nRule: $(x, y) \\to (x + a, y + b)$\n\nTranslations preserve **size** and **shape** (rigid motion). The image is congruent to the pre-image.\n    `, workedContent: `\n## Worked Example\n\n**Translate (3, 5) right 4, down 2.**\n\n$(3+4, 5-2) = (7, 3)$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Point | Translation | Image |\n|---|-------|------------|-------|\n| 1 | (2,3) | Right 5, Up 1 | (7,4) |\n| 2 | (0,0) | Left 3, Down 4 | (−3,−4) |\n| 3 | (−1,4) | Right 6, Down 3 | (5,1) |\n    `,
    mcq1: { questions: [{ question: 'Translate (2,3) right 5, up 1:', options: ['(7,4)','(7,2)','(−3,4)','(3,8)'], correctAnswer: 0, explanation: '(2+5, 3+1) = (7, 4).' }] },
    mcq2: { questions: [{ question: 'Translations preserve:', options: ['Size and shape','Size only','Shape only','Neither'], correctAnswer: 0, explanation: 'Translations are rigid motions.' }] },
    input: { boxes: 3, correctAnswers: ['7','4','5'], content: `\n**Translations** 🧮\n\nTranslate (2, 3) right 5, up 1.\n\n1) New x-coordinate?\n\n2) New y-coordinate?\n\nTranslate (−1, 4) right 6, down 3. \n3) New x-coordinate?\n    `, hint1: '2 + 5.', hint2: '3 + 1.', hint3: '−1 + 6.', explanation: '1) 7. 2) 4. 3) 5.' },
    dropdown: { dropdowns: [{ label: 'A translation is a', options: ['Slide','Flip','Turn','Stretch'] }, { label: 'After a translation, the figure is', options: ['Congruent to the original','Larger','Smaller','Different shape'] }], correctAnswers: ['Slide','Congruent to the original'], hint1: 'Every point moves same way.', hint2: 'Rigid motion.', explanation: 'Translation = slide. Image is congruent.' }
  },
  { introContent: `\n# 📊 Reflections\n\n**Part 2 of 7 — Reflections**\n\nA **reflection** flips a figure over a line.\n\n- Over **x-axis**: $(x, y) \\to (x, -y)$\n- Over **y-axis**: $(x, y) \\to (-x, y)$\n- Over $y = x$: $(x, y) \\to (y, x)$\n    `, workedContent: `\n## Worked Example\n\n**Reflect (3, 5) over the x-axis.**\n\n$(3, 5) \\to (3, -5)$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Point | Line | Image |\n|---|-------|------|-------|\n| 1 | (4,2) | x-axis | (4,−2) |\n| 2 | (4,2) | y-axis | (−4,2) |\n| 3 | (3,5) | y=x | (5,3) |\n    `,
    mcq1: { questions: [{ question: 'Reflect (4,2) over x-axis:', options: ['(4,−2)','(−4,2)','(−4,−2)','(2,4)'], correctAnswer: 0, explanation: 'Over x-axis: y becomes −y.' }] },
    mcq2: { questions: [{ question: 'Reflect (4,2) over y-axis:', options: ['(−4,2)','(4,−2)','(−4,−2)','(2,4)'], correctAnswer: 0, explanation: 'Over y-axis: x becomes −x.' }] },
    input: { boxes: 3, correctAnswers: ['-2','2','-4'], content: `\n**Reflections** 🧮\n\n1) Reflect (4, 2) over x-axis. New y = ?\n\n2) Reflect (4, 2) over y-axis. New y = ?\n\n3) Reflect (4, 2) over y-axis. New x = ?\n    `, hint1: 'x-axis reflection: flip y sign.', hint2: 'y-axis reflection: y stays.', hint3: 'y-axis reflection: flip x sign.', explanation: '1) −2. 2) 2 (y unchanged). 3) −4.' },
    dropdown: { dropdowns: [{ label: 'Reflection over x-axis changes', options: ['The y-coordinate sign','The x-coordinate sign','Both signs','Neither sign'] }, { label: 'A reflection is a', options: ['Flip','Slide','Turn','Stretch'] }], correctAnswers: ['The y-coordinate sign','Flip'], hint1: '(x,y)→(x,−y).', hint2: 'Mirror image.', explanation: 'x-axis: y flips. Reflection = flip.' }
  },
  { introContent: `\n# 🔢 Rotations\n\n**Part 3 of 7 — Rotations**\n\nA **rotation** turns a figure around a center point.\n\n**Rotations about the origin (counterclockwise):**\n- 90°: $(x,y) \\to (-y,x)$\n- 180°: $(x,y) \\to (-x,-y)$\n- 270°: $(x,y) \\to (y,-x)$\n    `, workedContent: `\n## Worked Example\n\n**Rotate (3, 2) 90° CCW about origin.**\n\n$(3, 2) \\to (-2, 3)$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Point | Rotation | Image |\n|---|-------|----------|-------|\n| 1 | (4,1) | 90° CCW | (−1,4) |\n| 2 | (4,1) | 180° | (−4,−1) |\n| 3 | (4,1) | 270° CCW | (1,−4) |\n    `,
    mcq1: { questions: [{ question: 'Rotate (4,1) 90° CCW:', options: ['(−1,4)','(1,−4)','(−4,−1)','(4,−1)'], correctAnswer: 0, explanation: '(x,y)→(−y,x): (−1,4).' }] },
    mcq2: { questions: [{ question: 'Rotate (4,1) 180°:', options: ['(−4,−1)','(4,1)','(−1,4)','(1,−4)'], correctAnswer: 0, explanation: '(x,y)→(−x,−y): (−4,−1).' }] },
    input: { boxes: 3, correctAnswers: ['-1','-4','1'], content: `\n**Rotations** 🧮\n\nPoint (4, 1):\n\n1) 90° CCW. New x = ?\n\n2) 180°. New x = ?\n\n3) 270° CCW. New x = ?\n    `, hint1: '(x,y)→(−y,x). New x = −y = −1.', hint2: '(x,y)→(−x,−y). New x = −4.', hint3: '(x,y)→(y,−x). New x = y = 1.', explanation: '1) −1. 2) −4. 3) 1.' },
    dropdown: { dropdowns: [{ label: '180° rotation changes (x,y) to', options: ['(−x,−y)','(−y,x)','(y,−x)','(x,y)'] }, { label: 'Rotations preserve', options: ['Size and shape','Size only','Shape only','Nothing'] }], correctAnswers: ['(−x,−y)','Size and shape'], hint1: 'Both coordinates negate.', hint2: 'Rigid motion.', explanation: '180°: (−x,−y). Rotations are rigid motions.' }
  },
  { introContent: `\n# 📈 Dilations\n\n**Part 4 of 7 — Dilations**\n\nA **dilation** resizes a figure by a **scale factor** $k$.\n\n$(x, y) \\to (kx, ky)$\n\n- $k > 1$: enlargement\n- $0 < k < 1$: reduction\n\nDilations produce **similar** figures (same shape, different size).\n    `, workedContent: `\n## Worked Example\n\n**Dilate (4, 6) by scale factor 2.**\n\n$(2·4, 2·6) = (8, 12)$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Point | Scale Factor | Image |\n|---|-------|-------------|-------|\n| 1 | (3,5) | 2 | (6,10) |\n| 2 | (8,4) | 0.5 | (4,2) |\n| 3 | (6,9) | 1/3 | (2,3) |\n    `,
    mcq1: { questions: [{ question: 'Dilate (3,5) by k=2:', options: ['(6,10)','(5,7)','(1.5,2.5)','(6,5)'], correctAnswer: 0, explanation: '(2·3, 2·5) = (6,10).' }] },
    mcq2: { questions: [{ question: 'Scale factor 0.5 means:', options: ['Figure shrinks to half','Figure doubles','No change','Figure disappears'], correctAnswer: 0, explanation: 'k < 1 → reduction.' }] },
    input: { boxes: 3, correctAnswers: ['6','4','2'], content: `\n**Dilations** 🧮\n\n1) (3, 5) × k=2. New x = ?\n\n2) (8, 4) × k=0.5. New x = ?\n\n3) (6, 9) × k=1/3. New x = ?\n    `, hint1: '3 × 2.', hint2: '8 × 0.5.', hint3: '6 × (1/3).', explanation: '1) 6. 2) 4. 3) 2.' },
    dropdown: { dropdowns: [{ label: 'A dilation with k > 1 is an', options: ['Enlargement','Reduction','Translation','Rotation'] }, { label: 'Dilations produce figures that are', options: ['Similar','Congruent','Different shapes','Perpendicular'] }], correctAnswers: ['Enlargement','Similar'], hint1: 'Gets bigger.', hint2: 'Same shape, different size.', explanation: 'k>1 → enlargement. Dilation → similar.' }
  },
  { introContent: `\n# 🧮 Sequences of Transformations\n\n**Part 5 of 7 — Sequences of Transformations**\n\nMultiple transformations can be combined:\n1. Apply the first transformation\n2. Apply the second to the **result**\n\nOrder matters! Different orders can give different results.\n    `, workedContent: `\n## Worked Example\n\n**Translate (2,3) right 3 then reflect over x-axis.**\n\nStep 1: $(2+3, 3) = (5, 3)$\nStep 2: $(5, -3)$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Steps | Final Image |\n|---|-------|------------|\n| 1 | (1,2): right 4, reflect x-axis | (5,−2) |\n| 2 | (3,1): reflect y-axis, up 5 | (−3,6) |\n| 3 | (2,4): dilate k=2, left 1 | (3,8) |\n    `,
    mcq1: { questions: [{ question: '(1,2): translate right 4, reflect over x-axis:', options: ['(5,−2)','(5,2)','(−1,−2)','(1,−2)'], correctAnswer: 0, explanation: '(1+4,2)=(5,2) then (5,−2).' }] },
    mcq2: { questions: [{ question: 'In a sequence of transformations, order:', options: ['Usually matters','Never matters','Always gives same result','Is irrelevant'], correctAnswer: 0, explanation: 'Different order → often different result.' }] },
    input: { boxes: 3, correctAnswers: ['5','-2','-3'], content: `\n**Sequences** 🧮\n\n(1, 2): Translate right 4, then reflect over x-axis.\n\n1) After translation, x = ?\n\n2) After reflection, y = ?\n\n(3, 1): Reflect over y-axis.\n3) New x = ?\n    `, hint1: '1 + 4.', hint2: 'Reflect (5,2): y flips.', hint3: 'y-axis: x → −x.', explanation: '1) 5. 2) −2. 3) −3.' },
    dropdown: { dropdowns: [{ label: 'A sequence of rigid motions produces', options: ['A congruent figure','A similar figure','A different shape','Nothing'] }, { label: 'The order of transformations', options: ['Usually matters','Never matters','Is always the same','Can be skipped'] }], correctAnswers: ['A congruent figure','Usually matters'], hint1: 'Translations, reflections, rotations are rigid.', hint2: 'Try switching order — different result.', explanation: 'Rigid motions → congruent. Order matters.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nApply transformations to real-world problems:\n- Identify the type of transformation\n- Write coordinate rules\n- Describe the transformation in words\n    `, workedContent: `\n## Worked Example\n\n**Triangle at (1,1), (3,1), (2,4). Reflect over y-axis.**\n\n$(1,1)→(-1,1)$, $(3,1)→(-3,1)$, $(2,4)→(-2,4)$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Type |\n|---|---------|------|\n| 1 | (x,y)→(x+3,y−1) | Translation |\n| 2 | (x,y)→(−x,y) | Reflection y-axis |\n| 3 | (x,y)→(2x,2y) | Dilation k=2 |\n    `,
    mcq1: { questions: [{ question: '$(x,y)→(x+3,y−1)$ describes a:', options: ['Translation','Reflection','Rotation','Dilation'], correctAnswer: 0, explanation: 'Adding to coordinates = slide.' }] },
    mcq2: { questions: [{ question: '$(x,y)→(−x,y)$ describes a:', options: ['Reflection over y-axis','Reflection over x-axis','Rotation 90°','Translation'], correctAnswer: 0, explanation: 'x flips → y-axis reflection.' }] },
    input: { boxes: 3, correctAnswers: ['-1','-3','-2'], content: `\n**Identify & Apply** 🧮\n\nReflect over y-axis: triangle at (1,1), (3,1), (2,4).\n\n1) (1,1) → new x = ?\n\n2) (3,1) → new x = ?\n\n3) (2,4) → new x = ?\n    `, hint1: 'Negate x.', hint2: 'Negate x.', hint3: 'Negate x.', explanation: '1) −1. 2) −3. 3) −2.' },
    dropdown: { dropdowns: [{ label: '(x,y)→(−y,x) is a', options: ['90° CCW rotation','Reflection','Translation','Dilation'] }, { label: 'Which transformation changes size?', options: ['Dilation','Translation','Reflection','Rotation'] }], correctAnswers: ['90° CCW rotation','Dilation'], hint1: 'Coordinates swap and one negates.', hint2: 'Scale factor changes size.', explanation: '(−y,x) = 90° CCW. Dilation changes size.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Transformation Summary\n| Transformation | Rule | Type |\n|---------------|------|------|\n| Translation | $(x+a, y+b)$ | Rigid |\n| Reflection x-axis | $(x, -y)$ | Rigid |\n| Reflection y-axis | $(-x, y)$ | Rigid |\n| Rotation 90° CCW | $(-y, x)$ | Rigid |\n| Rotation 180° | $(-x, -y)$ | Rigid |\n| Dilation | $(kx, ky)$ | Not rigid |\n    `, workedContent: `\n## Worked Example\n\n**Rotate (5, 2) 90° CCW then dilate by 3.**\n\nStep 1: $(5,2) \\to (-2,5)$\nStep 2: $(-6,15)$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Translation | (3,7) right 2 up 4 |\n| 2 | Reflection | (5,−3) over x-axis |\n| 3 | Rotation | (4,1) 180° |\n    `,
    mcq1: { questions: [{ question: 'Translate (3,7) right 2, up 4:', options: ['(5,11)','(1,3)','(5,3)','(1,11)'], correctAnswer: 0, explanation: '(3+2, 7+4) = (5,11).' }] },
    mcq2: { questions: [{ question: 'Rotate (4,1) 180°:', options: ['(−4,−1)','(−1,4)','(4,−1)','(1,−4)'], correctAnswer: 0, explanation: '(x,y)→(−x,−y) = (−4,−1).' }] },
    input: { boxes: 3, correctAnswers: ['5','3','-4'], content: `\n**Review** 🧮\n\n1) Translate (3,7) right 2. New x = ?\n\n2) Reflect (5,−3) over x-axis. New y = ?\n\n3) Rotate (4,1) 180°. New x = ?\n    `, hint1: '3 + 2.', hint2: '−(−3) = 3.', hint3: '−4.', explanation: '1) 5. 2) 3. 3) −4.' },
    dropdown: { dropdowns: [{ label: 'Rigid motions preserve', options: ['Size and shape','Size only','Shape only','Color'] }, { label: 'The only transformation that changes size is', options: ['Dilation','Translation','Reflection','Rotation'] }], correctAnswers: ['Size and shape','Dilation'], hint1: 'Congruent images.', hint2: 'Scale factor ≠ 1.', explanation: 'Rigid motions → congruent. Dilation changes size.' }
  }
]

};
