/**
 * Content patches for Grade 7 topics:
 * - grade7-geometry (7 parts)
 * - grade7-operations-rational (7 parts)
 * - grade7-proportional-relationships (7 parts)
 */
module.exports = {

'grade7-geometry': [
  { introContent: `\n# 📐 Angle Relationships\n\n**Part 1 of 7 — Angle Relationships**\n\n- **Complementary**: sum to 90°\n- **Supplementary**: sum to 180°\n- **Vertical angles**: equal\n- **Adjacent angles**: share a side\n    `, workedContent: `\n## Worked Example\n\nTwo supplementary angles: one is 65°. Other = $180° - 65° = 115°$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Concept | Example |\n|---|---------|--------|\n| 1 | Complementary | 40° + ? = 90° |\n| 2 | Supplementary | 110° + ? = 180° |\n| 3 | Vertical angles | Equal to each other |\n    `,
    mcq1: { questions: [{ question: 'Complement of 35°?', options: ['55°','145°','35°','90°'], correctAnswer: 0, explanation: '90° − 35° = 55°.' }] },
    mcq2: { questions: [{ question: 'Vertical angles are always:', options: ['Equal','Supplementary','Complementary','Adjacent'], correctAnswer: 0, explanation: 'Vertical angles are congruent.' }] },
    input: { boxes: 3, correctAnswers: ['50','70','115'], content: `\n**Angle Relationships** 🧮\n\n1) Complement of 40°?\n\n2) Complement of 20°?\n\n3) Supplement of 65°?\n    `, hint1: '90° − 40°.', hint2: '90° − 20°.', hint3: '180° − 65°.', explanation: '1) 50. 2) 70. 3) 115.' },
    dropdown: { dropdowns: [{ label: 'Complementary angles sum to', options: ['90°','180°','360°','45°'] }, { label: 'Supplementary angles sum to', options: ['180°','90°','360°','270°'] }], correctAnswers: ['90°','180°'], hint1: 'Complementary = right angle.', hint2: 'Supplementary = straight line.', explanation: 'Complementary: 90°. Supplementary: 180°.' }
  },
  { introContent: `\n# 📐 Area of Composite Shapes\n\n**Part 2 of 7 — Area of Composite Shapes**\n\nBreak complex shapes into simple ones:\n- Rectangles: $A = lw$\n- Triangles: $A = \\frac{1}{2}bh$\n- Trapezoids: $A = \\frac{1}{2}(b_1 + b_2)h$\n    `, workedContent: `\n## Worked Example\n\n**L-shape: 8×3 rectangle plus 4×3 rectangle.**\n\n$A = 8(3) + 4(3) = 24 + 12 = 36$ sq units ✅\n    `, practiceContent: `\n## Practice\n\n| # | Shape | Method |\n|---|-------|--------|\n| 1 | T-shape | Two rectangles |\n| 2 | Arrow | Rectangle + triangle |\n| 3 | House | Rectangle + triangle |\n    `,
    mcq1: { questions: [{ question: 'Area of triangle: base 10, height 6?', options: ['30','60','16','36'], correctAnswer: 0, explanation: '½(10)(6) = 30.' }] },
    mcq2: { questions: [{ question: 'Trapezoid: bases 5 and 9, height 4. Area?', options: ['28','56','14','36'], correctAnswer: 0, explanation: '½(5+9)(4) = ½(14)(4) = 28.' }] },
    input: { boxes: 3, correctAnswers: ['30','28','36'], content: `\n**Composite Areas** 🧮\n\n1) Triangle: base 10, height 6. Area?\n\n2) Trapezoid: bases 5 and 9, height 4. Area?\n\n3) L-shape: 8×3 + 4×3. Total area?\n    `, hint1: 'A = ½bh.', hint2: 'A = ½(b₁+b₂)h.', hint3: 'Add two rectangle areas.', explanation: '1) ½(10)(6)=30. 2) ½(14)(4)=28. 3) 24+12=36.' },
    dropdown: { dropdowns: [{ label: 'Triangle area formula', options: ['A = ½bh','A = bh','A = 2bh','A = b+h'] }, { label: 'To find area of a composite shape', options: ['Break into simpler shapes and add','Use one formula','Multiply all sides','Cannot be found'] }], correctAnswers: ['A = ½bh','Break into simpler shapes and add'], hint1: 'Half of base times height.', hint2: 'Decompose then combine.', explanation: 'Triangle: ½bh. Composite: split and add.' }
  },
  { introContent: `\n# 📐 Circumference & Area of Circles\n\n**Part 3 of 7 — Circumference & Area of Circles**\n\n- **Circumference**: $C = 2\\pi r = \\pi d$\n- **Area**: $A = \\pi r^2$\n\n$\\pi \\approx 3.14$\n    `, workedContent: `\n## Worked Example\n\n**Circle with radius 5 cm.**\n\n$C = 2\\pi(5) = 10\\pi \\approx 31.4$ cm\n$A = \\pi(5)^2 = 25\\pi \\approx 78.5$ cm² ✅\n    `, practiceContent: `\n## Practice\n\n| # | Given | Find |\n|---|-------|------|\n| 1 | r = 7 | C |\n| 2 | d = 10 | C |\n| 3 | r = 4 | A |\n    `,
    mcq1: { questions: [{ question: 'Circumference of circle with d = 10 cm? (Use π ≈ 3.14)', options: ['31.4 cm','62.8 cm','78.5 cm','15.7 cm'], correctAnswer: 0, explanation: 'C = πd = 3.14(10) = 31.4 cm.' }] },
    mcq2: { questions: [{ question: 'Area of circle with r = 3? (Use π ≈ 3.14)', options: ['28.26','18.84','9.42','6.28'], correctAnswer: 0, explanation: 'A = π(3)² = 9π ≈ 28.26.' }] },
    input: { boxes: 3, correctAnswers: ['43.96','31.4','50.24'], content: `\n**Circles** 🧮 (Use π ≈ 3.14)\n\n1) r = 7. Circumference?\n\n2) d = 10. Circumference?\n\n3) r = 4. Area?\n    `, hint1: 'C = 2πr = 2(3.14)(7).', hint2: 'C = πd = 3.14(10).', hint3: 'A = πr² = 3.14(16).', explanation: '1) 2(3.14)(7)=43.96. 2) 3.14(10)=31.4. 3) 3.14(16)=50.24.' },
    dropdown: { dropdowns: [{ label: 'Circumference formula', options: ['C = 2πr','C = πr²','C = 2r','C = πr'] }, { label: 'Area of a circle formula', options: ['A = πr²','A = 2πr','A = πd','A = r²'] }], correctAnswers: ['C = 2πr','A = πr²'], hint1: 'Distance around.', hint2: 'Space inside.', explanation: 'C = 2πr (circumference). A = πr² (area).' }
  },
  { introContent: `\n# 📐 Surface Area\n\n**Part 4 of 7 — Surface Area**\n\nSurface area = total area of all faces.\n\n**Rectangular prism**: $SA = 2(lw + lh + wh)$\n\n**Cube**: $SA = 6s^2$\n    `, workedContent: `\n## Worked Example\n\n**Box: 5 × 3 × 4 cm.**\n\n$SA = 2(5·3 + 5·4 + 3·4) = 2(15 + 20 + 12) = 2(47) = 94$ cm² ✅\n    `, practiceContent: `\n## Practice\n\n| # | Shape | Dimensions |\n|---|-------|------------|\n| 1 | Cube | s = 3 |\n| 2 | Prism | 6×4×2 |\n| 3 | Prism | 8×5×3 |\n    `,
    mcq1: { questions: [{ question: 'SA of cube, side 3 cm?', options: ['54 cm²','27 cm²','36 cm²','18 cm²'], correctAnswer: 0, explanation: '6(3²) = 6(9) = 54.' }] },
    mcq2: { questions: [{ question: 'A rectangular prism has how many faces?', options: ['6','4','8','12'], correctAnswer: 0, explanation: 'Top, bottom, front, back, left, right = 6.' }] },
    input: { boxes: 3, correctAnswers: ['54','88','158'], content: `\n**Surface Area** 🧮\n\n1) Cube, side 3. SA?\n\n2) Prism 6×4×2. SA?\n\n3) Prism 8×5×3. SA?\n    `, hint1: 'SA = 6s².', hint2: '2(6·4 + 6·2 + 4·2).', hint3: '2(8·5 + 8·3 + 5·3).', explanation: '1) 54. 2) 2(24+12+8)=88. 3) 2(40+24+15)=158.' },
    dropdown: { dropdowns: [{ label: 'Surface area is measured in', options: ['Square units','Cubic units','Linear units','No units'] }, { label: 'A cube has how many identical faces?', options: ['6','4','8','12'] }], correctAnswers: ['Square units','6'], hint1: 'SA is a 2D measurement.', hint2: 'A cube has all faces equal.', explanation: 'SA → square units. Cube has 6 identical faces.' }
  },
  { introContent: `\n# 📐 Volume of Prisms & Cylinders\n\n**Part 5 of 7 — Volume of Prisms & Cylinders**\n\n- **Prism**: $V = Bh$ (B = base area)\n- **Rectangular prism**: $V = lwh$\n- **Cylinder**: $V = \\pi r^2 h$\n    `, workedContent: `\n## Worked Example\n\n**Cylinder: r = 3 cm, h = 10 cm.**\n\n$V = \\pi(3)^2(10) = 90\\pi \\approx 282.6$ cm³ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Shape | Dimensions |\n|---|-------|------------|\n| 1 | Rect. prism | 8×5×4 |\n| 2 | Cylinder | r=2, h=7 |\n| 3 | Triangular prism | B=12, h=5 |\n    `,
    mcq1: { questions: [{ question: 'Volume of 8×5×4 rectangular prism?', options: ['160','80','17','320'], correctAnswer: 0, explanation: '8 × 5 × 4 = 160.' }] },
    mcq2: { questions: [{ question: 'Cylinder volume formula?', options: ['V = πr²h','V = 2πrh','V = πrh','V = πd²h'], correctAnswer: 0, explanation: 'V = πr²h.' }] },
    input: { boxes: 3, correctAnswers: ['160','87.92','60'], content: `\n**Volume** 🧮 (Use π ≈ 3.14)\n\n1) Rectangular prism 8×5×4. Volume?\n\n2) Cylinder r=2, h=7. Volume?\n\n3) Triangular prism: base area 12, height 5. Volume?\n    `, hint1: '8 × 5 × 4.', hint2: 'π(2²)(7) = 3.14(4)(7).', hint3: 'V = Bh = 12(5).', explanation: '1) 160. 2) 3.14(4)(7)=87.92. 3) 12(5)=60.' },
    dropdown: { dropdowns: [{ label: 'Volume of a prism = base area ×', options: ['Height','Perimeter','Surface area','Width'] }, { label: 'Volume is measured in', options: ['Cubic units','Square units','Linear units','Liters only'] }], correctAnswers: ['Height','Cubic units'], hint1: 'V = Bh.', hint2: '3D measurement.', explanation: 'V = B × h. Volume → cubic units.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nApply geometry skills:\n- Choose the right formula\n- Draw pictures\n- Include correct units\n    `, workedContent: `\n## Worked Example\n\n**Paint a wall 12 ft × 8 ft with a 3 ft × 4 ft window. Paint needed?**\n\nWall area: $12(8) = 96$ ft²\nWindow: $3(4) = 12$ ft²\nPaint: $96 - 12 = 84$ ft² ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Formula |\n|---|---------|--------|\n| 1 | Fencing for circular garden, r=5 | C = 2πr |\n| 2 | Wrapping a 4×3×2 box | SA |\n| 3 | Water in cylindrical tank | V = πr²h |\n    `,
    mcq1: { questions: [{ question: 'Fencing for circular garden, r=5 m? (π≈3.14)', options: ['31.4 m','78.5 m','15.7 m','25 m'], correctAnswer: 0, explanation: 'C = 2π(5) = 31.4 m.' }] },
    mcq2: { questions: [{ question: 'To wrap a box, you need to find its:', options: ['Surface area','Volume','Perimeter','Weight'], correctAnswer: 0, explanation: 'Wrapping covers the surface.' }] },
    input: { boxes: 3, correctAnswers: ['31.4','52','84'], content: `\n**Word Problems** 🧮\n\n1) Fence circular garden, r=5. How many meters? (π≈3.14)\n\n2) Gift wrap a 4×3×2 box. SA?\n\n3) Paint a 12×8 wall minus a 3×4 window. Area to paint?\n    `, hint1: 'C = 2πr.', hint2: 'SA = 2(lw+lh+wh).', hint3: 'Wall − window.', explanation: '1) 2(3.14)(5)=31.4. 2) 2(12+8+6)=52. 3) 96−12=84.' },
    dropdown: { dropdowns: [{ label: 'Fencing goes around → need', options: ['Perimeter/Circumference','Area','Volume','Diameter'] }, { label: 'Filling a pool → need', options: ['Volume','Surface area','Perimeter','Length'] }], correctAnswers: ['Perimeter/Circumference','Volume'], hint1: 'Around = distance around.', hint2: 'Filling = 3D space.', explanation: 'Fencing → circumference. Filling → volume.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Formulas\n- Complement: $90° - x$, Supplement: $180° - x$\n- Triangle: $A = \\frac{1}{2}bh$\n- Circle: $C = 2\\pi r$, $A = \\pi r^2$\n- SA prism: $2(lw+lh+wh)$\n- V prism: $lwh$, V cylinder: $\\pi r^2 h$\n    `, workedContent: `\n## Worked Example\n\n**Cylinder: r = 4, h = 10. Volume?**\n$V = \\pi(16)(10) = 160\\pi \\approx 502.4$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Angle | Supplement of 72° |\n| 2 | Area | Triangle: b=8, h=5 |\n| 3 | Volume | Cube side 6 |\n    `,
    mcq1: { questions: [{ question: 'Supplement of 72°?', options: ['108°','18°','72°','288°'], correctAnswer: 0, explanation: '180° − 72° = 108°.' }] },
    mcq2: { questions: [{ question: 'Volume of cube side 6?', options: ['216','36','72','108'], correctAnswer: 0, explanation: '6³ = 216.' }] },
    input: { boxes: 3, correctAnswers: ['108','20','216'], content: `\n**Review** 🧮\n\n1) Supplement of 72°?\n\n2) Triangle: b=8, h=5. Area?\n\n3) Cube side 6. Volume?\n    `, hint1: '180 − 72.', hint2: '½(8)(5).', hint3: '6³.', explanation: '1) 108. 2) 20. 3) 216.' },
    dropdown: { dropdowns: [{ label: 'V = πr²h is the formula for a', options: ['Cylinder','Cube','Sphere','Cone'] }, { label: 'SA of a cube with side s', options: ['6s²','s³','4s²','s²'] }], correctAnswers: ['Cylinder','6s²'], hint1: 'Circular base × height.', hint2: '6 faces, each s².', explanation: 'πr²h = cylinder. SA cube = 6s².' }
  }
],

'grade7-operations-rational': [
  { introContent: `\n# 🔢 Adding Rational Numbers\n\n**Part 1 of 7 — Adding Rational Numbers**\n\nRational numbers include fractions, decimals, and integers.\n\n### Adding Same Signs\nAdd absolute values, keep sign: $(-2.5) + (-1.3) = -3.8$\n\n### Adding Different Signs\nSubtract, keep sign of larger absolute value: $(-4) + 7 = 3$\n    `, workedContent: `\n## Worked Example\n\n$-3.5 + 2.1 = ?$\n\n$3.5 - 2.1 = 1.4$. Negative is larger: $-1.4$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Rule |\n|---|---------|------|\n| 1 | $-2.4 + 5.1$ | Different signs |\n| 2 | $-3.7 + (-1.2)$ | Same signs |\n| 3 | $\\frac{1}{4} + (-\\frac{3}{4})$ | Different signs |\n    `,
    mcq1: { questions: [{ question: '$-2.4 + 5.1 = ?$', options: ['2.7','−7.5','7.5','−2.7'], correctAnswer: 0, explanation: '5.1 − 2.4 = 2.7, positive wins.' }] },
    mcq2: { questions: [{ question: '$-\\\\frac{3}{4} + \\\\frac{1}{4} = ?$', options: ['$-\\\\frac{1}{2}$','$\\\\frac{1}{2}$','$-1$','$1$'], correctAnswer: 0, explanation: '−3/4 + 1/4 = −2/4 = −1/2.' }] },
    input: { boxes: 3, correctAnswers: ['2.7','-4.9','-0.5'], content: `\n**Add Rationals** 🧮\n\n1) $-2.4 + 5.1 = ?$\n\n2) $-3.7 + (-1.2) = ?$\n\n3) $\\frac{1}{4} + (-\\frac{3}{4}) = ?$ (decimal)\n    `, hint1: '5.1 − 2.4.', hint2: '−(3.7 + 1.2).', hint3: '1/4 − 3/4 = −2/4.', explanation: '1) 2.7. 2) −4.9. 3) −0.5.' },
    dropdown: { dropdowns: [{ label: 'Adding two negative numbers gives', options: ['A negative','A positive','Zero','Cannot tell'] }, { label: '$-5 + 5 =$', options: ['0','10','−10','5'] }], correctAnswers: ['A negative','0'], hint1: 'Same signs: keep sign.', hint2: 'Opposites cancel.', explanation: 'Neg + neg = neg. Opposites sum to 0.' }
  },
  { introContent: `\n# 🔢 Subtracting Rational Numbers\n\n**Part 2 of 7 — Subtracting Rational Numbers**\n\nRule: **Add the opposite.**\n\n$a - b = a + (-b)$\n\n$3.5 - 7.2 = 3.5 + (-7.2) = -3.7$\n    `, workedContent: `\n## Worked Example\n\n$-2.4 - (-5.1) = -2.4 + 5.1 = 2.7$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Rewrite |\n|---|---------|--------|\n| 1 | $4.3 - 6.8$ | $4.3 + (-6.8)$ |\n| 2 | $-1.5 - 3.2$ | $-1.5 + (-3.2)$ |\n| 3 | $-7 - (-4)$ | $-7 + 4$ |\n    `,
    mcq1: { questions: [{ question: '$4.3 - 6.8 = ?$', options: ['$-2.5$','$2.5$','$11.1$','$-11.1$'], correctAnswer: 0, explanation: '4.3 + (−6.8) = −2.5.' }] },
    mcq2: { questions: [{ question: '$-7 - (-4) = ?$', options: ['$-3$','$-11$','$3$','$11$'], correctAnswer: 0, explanation: '−7 + 4 = −3.' }] },
    input: { boxes: 3, correctAnswers: ['-2.5','-4.7','-3'], content: `\n**Subtract Rationals** 🧮\n\n1) $4.3 - 6.8 = ?$\n\n2) $-1.5 - 3.2 = ?$\n\n3) $-7 - (-4) = ?$\n    `, hint1: 'Add the opposite: 4.3 + (−6.8).', hint2: '−1.5 + (−3.2).', hint3: '−7 + 4.', explanation: '1) −2.5. 2) −4.7. 3) −3.' },
    dropdown: { dropdowns: [{ label: 'Subtracting is the same as', options: ['Adding the opposite','Multiplying','Dividing','Squaring'] }, { label: '$0 - (-3.5) =$', options: ['3.5','−3.5','0','7'] }], correctAnswers: ['Adding the opposite','3.5'], hint1: 'Add the opposite.', hint2: '0 + 3.5.', explanation: 'Subtract = add opposite. 0−(−3.5)=3.5.' }
  },
  { introContent: `\n# 🔢 Multiplying Rational Numbers\n\n**Part 3 of 7 — Multiplying Rational Numbers**\n\nSign rules:\n- Same signs → **positive**\n- Different signs → **negative**\n\n$(-0.3)(0.5) = -0.15$\n$(-\\frac{2}{3})(-\\frac{3}{4}) = \\frac{1}{2}$\n    `, workedContent: `\n## Worked Example\n\n$(-2.5)(4) = -10$ (different signs → negative) ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Sign |\n|---|---------|------|\n| 1 | $(-3)(5)$ | Negative |\n| 2 | $(-4)(-7)$ | Positive |\n| 3 | $(0.5)(-0.8)$ | Negative |\n    `,
    mcq1: { questions: [{ question: '$(-4)(-7) = ?$', options: ['28','−28','−11','11'], correctAnswer: 0, explanation: 'Same signs → positive: 28.' }] },
    mcq2: { questions: [{ question: '$(-\\\\frac{1}{2})(\\\\frac{4}{5}) = ?$', options: ['$-\\\\frac{2}{5}$','$\\\\frac{2}{5}$','$-\\\\frac{5}{2}$','$\\\\frac{4}{10}$'], correctAnswer: 0, explanation: 'Different signs: −(1×4)/(2×5) = −2/5.' }] },
    input: { boxes: 3, correctAnswers: ['-15','28','-0.4'], content: `\n**Multiply Rationals** 🧮\n\n1) $(-3)(5) = ?$\n\n2) $(-4)(-7) = ?$\n\n3) $(0.5)(-0.8) = ?$\n    `, hint1: 'Different signs → negative.', hint2: 'Same signs → positive.', hint3: 'Different signs → negative. 5×8=40.', explanation: '1) −15. 2) 28. 3) −0.4.' },
    dropdown: { dropdowns: [{ label: 'Two negatives multiplied give', options: ['Positive','Negative','Zero','Undefined'] }, { label: '$(−1)(−1)(−1) =$', options: ['−1','1','0','3'] }], correctAnswers: ['Positive','−1'], hint1: 'Same sign rule.', hint2: 'Odd number of negatives.', explanation: '(−)(−)=(+). Three negatives: (−1)(−1)=1, (1)(−1)=−1.' }
  },
  { introContent: `\n# 🔢 Dividing Rational Numbers\n\n**Part 4 of 7 — Dividing Rational Numbers**\n\nSame sign rules as multiplication:\n- Same signs → **positive**\n- Different signs → **negative**\n\n$(-12) \\div 4 = -3$\n$(-15) \\div (-3) = 5$\n    `, workedContent: `\n## Worked Example\n\n$(-8.4) \\div (-2.1) = 4$ (same signs → positive) ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Sign |\n|---|---------|------|\n| 1 | $(-24) \\div 6$ | Negative |\n| 2 | $(-36) \\div (-9)$ | Positive |\n| 3 | $4.5 \\div (-1.5)$ | Negative |\n    `,
    mcq1: { questions: [{ question: '$(-24) \\\\div 6 = ?$', options: ['−4','4','−18','18'], correctAnswer: 0, explanation: 'Different signs → negative: −4.' }] },
    mcq2: { questions: [{ question: '$(-36) \\\\div (-9) = ?$', options: ['4','−4','45','−27'], correctAnswer: 0, explanation: 'Same signs → positive: 4.' }] },
    input: { boxes: 3, correctAnswers: ['-4','4','-3'], content: `\n**Divide Rationals** 🧮\n\n1) $(-24) \\div 6 = ?$\n\n2) $(-36) \\div (-9) = ?$\n\n3) $4.5 \\div (-1.5) = ?$\n    `, hint1: 'Different signs.', hint2: 'Same signs.', hint3: 'Different signs. 4.5/1.5 = 3.', explanation: '1) −4. 2) 4. 3) −3.' },
    dropdown: { dropdowns: [{ label: 'Division by zero is', options: ['Undefined','Zero','One','Infinity'] }, { label: '$(-1) \\\\div (-1) =$', options: ['1','−1','0','−2'] }], correctAnswers: ['Undefined','1'], hint1: 'You cannot divide by zero.', hint2: 'Same signs.', explanation: 'Division by 0 is undefined. (−1)÷(−1)=1.' }
  },
  { introContent: `\n# 🔢 Order of Operations Review\n\n**Part 5 of 7 — Order of Operations Review**\n\n**PEMDAS** with rational numbers:\n1. **P**arentheses\n2. **E**xponents\n3. **M**ultiplication / **D**ivision (left to right)\n4. **A**ddition / **S**ubtraction (left to right)\n    `, workedContent: `\n## Worked Example\n\n$-3 + 4(-2)^2 = ?$\n\n$(-2)^2 = 4$. Then $4(4) = 16$. Then $-3 + 16 = 13$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Value |\n|---|-----------|-------|\n| 1 | $2 + 3 \\times 4$ | 14 |\n| 2 | $(2 + 3) \\times 4$ | 20 |\n| 3 | $-5 + 3^2$ | 4 |\n    `,
    mcq1: { questions: [{ question: '$2 + 3 \\\\times 4 = ?$', options: ['14','20','24','9'], correctAnswer: 0, explanation: 'Multiply first: 2 + 12 = 14.' }] },
    mcq2: { questions: [{ question: '$-5 + 3^2 = ?$', options: ['4','−14','14','22'], correctAnswer: 0, explanation: '3² = 9. −5 + 9 = 4.' }] },
    input: { boxes: 3, correctAnswers: ['14','20','4'], content: `\n**Order of Operations** 🧮\n\n1) $2 + 3 \\times 4 = ?$\n\n2) $(2 + 3) \\times 4 = ?$\n\n3) $-5 + 3^2 = ?$\n    `, hint1: 'Multiply before adding.', hint2: 'Parentheses first.', hint3: 'Exponent first: 3² = 9.', explanation: '1) 2+12=14. 2) 5×4=20. 3) −5+9=4.' },
    dropdown: { dropdowns: [{ label: 'In PEMDAS, what comes first?', options: ['Parentheses','Exponents','Multiplication','Addition'] }, { label: 'Multiplication and division are done', options: ['Left to right','Right to left','Multiplication first','Division first'] }], correctAnswers: ['Parentheses','Left to right'], hint1: 'P-E-M-D-A-S.', hint2: 'Same precedence → left to right.', explanation: 'Parentheses first. M/D left to right.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nApply rational number operations:\n- Temperature changes\n- Financial transactions\n- Scientific measurements\n    `, workedContent: `\n## Worked Example\n\n**Temperature: -4.5°, rises 3.2°, drops 1.8°. Final temp?**\n\n$-4.5 + 3.2 - 1.8 = -1.3 - 1.8 = -3.1$° ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Expression |\n|---|---------|------------|\n| 1 | Stock: up 2.5, down 4.3 | $2.5 + (-4.3)$ |\n| 2 | Temp: −8, rises 12 | $-8 + 12$ |\n| 3 | Debt: owe 50, pay 32 | $-50 + 32$ |\n    `,
    mcq1: { questions: [{ question: 'Stock: +2.5 then −4.3. Net change?', options: ['−1.8','6.8','1.8','−6.8'], correctAnswer: 0, explanation: '2.5 + (−4.3) = −1.8.' }] },
    mcq2: { questions: [{ question: 'Owe $50, pay $32. Remaining debt?', options: ['$18','$82','$50','$32'], correctAnswer: 0, explanation: '$50 − $32 = $18 remaining.' }] },
    input: { boxes: 3, correctAnswers: ['-1.8','4','-18'], content: `\n**Word Problems** 🧮\n\n1) Stock: up 2.5, down 4.3. Net change?\n\n2) Temp: −8°F, rises 12°. New temp?\n\n3) Owe \\$50, pay \\$32. Balance? (negative = debt)\n    `, hint1: '2.5 − 4.3.', hint2: '−8 + 12.', hint3: '−50 + 32.', explanation: '1) −1.8. 2) 4. 3) −18.' },
    dropdown: { dropdowns: [{ label: 'A gain in stock price is', options: ['Positive','Negative','Zero','Neither'] }, { label: 'When temperature drops, we', options: ['Subtract','Add','Multiply','Divide'] }], correctAnswers: ['Positive','Subtract'], hint1: 'Gain → positive change.', hint2: 'Drops mean decreasing.', explanation: 'Gain → positive. Drop → subtract.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Rules\n- Add same signs: add, keep sign\n- Add different signs: subtract, keep larger\n- Subtract: add the opposite\n- Multiply/Divide: same signs = +, different = −\n- PEMDAS applies to all rational numbers\n    `, workedContent: `\n## Worked Example\n\n$(-3)(4) + 8 \\div (-2) = -12 + (-4) = -16$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Value |\n|---|-----------|-------|\n| 1 | $(-5)(3) + 2$ | −13 |\n| 2 | $12 \\div (-4) - 1$ | −4 |\n| 3 | $-2.5 + 3.7$ | 1.2 |\n    `,
    mcq1: { questions: [{ question: '$(-5)(3) + 2 = ?$', options: ['−13','−17','13','−7'], correctAnswer: 0, explanation: '−15 + 2 = −13.' }] },
    mcq2: { questions: [{ question: '$12 \\\\div (-4) - 1 = ?$', options: ['−4','−2','2','4'], correctAnswer: 0, explanation: '−3 − 1 = −4.' }] },
    input: { boxes: 3, correctAnswers: ['-13','-4','1.2'], content: `\n**Review** 🧮\n\n1) $(-5)(3) + 2 = ?$\n\n2) $12 \\div (-4) - 1 = ?$\n\n3) $-2.5 + 3.7 = ?$\n    `, hint1: 'Multiply first, then add.', hint2: 'Divide first, then subtract.', hint3: 'Different signs: 3.7 − 2.5.', explanation: '1) −15+2=−13. 2) −3−1=−4. 3) 1.2.' },
    dropdown: { dropdowns: [{ label: 'When doing $(-3)(2) + 5$, calculate the ____ first', options: ['Multiplication','Addition','Subtraction','Nothing — go left to right'] }, { label: '$(-1)^4 =$', options: ['1','−1','4','−4'] }], correctAnswers: ['Multiplication','1'], hint1: 'PEMDAS: M before A.', hint2: 'Even exponent of −1.', explanation: 'Multiply first. (−1)⁴ = 1.' }
  }
],

'grade7-proportional-relationships': [
  { introContent: `\n# 📊 Identifying Proportions\n\n**Part 1 of 7 — Identifying Proportions**\n\nA proportional relationship has a **constant ratio** $\\frac{y}{x} = k$.\n\nIn a table, check if all $\\frac{y}{x}$ values are equal.\n    `, workedContent: `\n## Worked Example\n\n| x | 2 | 4 | 6 |\n|---|---|---|---|\n| y | 6 | 12 | 18 |\n\n$\\frac{6}{2} = 3$, $\\frac{12}{4} = 3$, $\\frac{18}{6} = 3$ → **proportional** ($k = 3$) ✅\n    `, practiceContent: `\n## Practice\n\n| # | Data | Proportional? |\n|---|------|--------|\n| 1 | (1,3), (2,6), (3,9) | Yes, k=3 |\n| 2 | (1,2), (2,5), (3,8) | No |\n| 3 | (2,10), (4,20), (6,30) | Yes, k=5 |\n    `,
    mcq1: { questions: [{ question: 'Which table shows a proportional relationship?', options: ['(1,4), (2,8), (3,12)','(1,3), (2,5), (3,7)','(1,1), (2,3), (3,6)','(1,2), (2,6), (3,8)'], correctAnswer: 0, explanation: 'All ratios = 4: proportional.' }] },
    mcq2: { questions: [{ question: 'In $y = kx$, k is called the:', options: ['Constant of proportionality','Slope only','Y-intercept','Coefficient'], correctAnswer: 0, explanation: 'k = constant of proportionality.' }] },
    input: { boxes: 3, correctAnswers: ['3','5','4'], content: `\n**Find k** 🧮\n\n1) (2, 6): k = y/x = ?\n\n2) (4, 20): k = ?\n\n3) (3, 12): k = ?\n    `, hint1: '6 ÷ 2.', hint2: '20 ÷ 4.', hint3: '12 ÷ 3.', explanation: '1) 3. 2) 5. 3) 4.' },
    dropdown: { dropdowns: [{ label: 'A proportional relationship always passes through', options: ['The origin (0,0)','(1,1)','(0,1)','No specific point'] }, { label: 'If y/x varies, the relationship is', options: ['Not proportional','Proportional','Linear','Exponential'] }], correctAnswers: ['The origin (0,0)','Not proportional'], hint1: 'When x=0, y must be 0.', hint2: 'Constant ratio is required.', explanation: 'Proportional → through (0,0). Varying ratio → not proportional.' }
  },
  { introContent: `\n# 📊 Constant of Proportionality\n\n**Part 2 of 7 — Constant of Proportionality**\n\nThe **constant of proportionality** $k = \\frac{y}{x}$.\n\nEquation form: $y = kx$\n\nExample: If $k = 3$, then $y = 3x$.\n    `, workedContent: `\n## Worked Example\n\n**Bananas cost \\$0.50 each. Write the equation.**\n\n$\\text{Cost} = 0.50 \\times n$ → $C = 0.50n$, so $k = 0.50$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Scenario | k |\n|---|---------|---|\n| 1 | \\$3 per lb | 3 |\n| 2 | 60 mph | 60 |\n| 3 | 5 pages/min | 5 |\n    `,
    mcq1: { questions: [{ question: '$y = 7x$. What is k?', options: ['7','x','y','1/7'], correctAnswer: 0, explanation: 'In y = kx, k = 7.' }] },
    mcq2: { questions: [{ question: 'If 3 items cost $12, the constant of proportionality is:', options: ['4','3','12','36'], correctAnswer: 0, explanation: 'k = 12/3 = 4 (dollars per item).' }] },
    input: { boxes: 3, correctAnswers: ['3','60','0.5'], content: `\n**Find k** 🧮\n\n1) \\$3 per pound. k = ?\n\n2) 60 miles per hour. k = ?\n\n3) Cost = \\$0.50 per banana. k = ?\n    `, hint1: 'Price per pound.', hint2: 'Miles per hour.', hint3: 'Cost per banana.', explanation: '1) k=3. 2) k=60. 3) k=0.5.' },
    dropdown: { dropdowns: [{ label: 'In y = kx, k represents the', options: ['Rate or unit rate','Y-intercept','X-intercept','Exponent'] }, { label: 'If y = 2x, when x = 5, y =', options: ['10','7','25','2.5'] }], correctAnswers: ['Rate or unit rate','10'], hint1: 'k = rate of change.', hint2: 'y = 2(5).', explanation: 'k = unit rate. y = 2(5) = 10.' }
  },
  { introContent: `\n# 📊 Graphing Proportions\n\n**Part 3 of 7 — Graphing Proportions**\n\nA proportional relationship graphs as a **straight line through the origin**.\n\nThe **slope** of the line = **k** (constant of proportionality).\n    `, workedContent: `\n## Worked Example\n\n**Graph y = 2x.**\n\nPlot (0,0), (1,2), (2,4), (3,6). Connect → straight line through origin. ✅\n    `, practiceContent: `\n## Practice\n\n| # | Equation | Points |\n|---|---------|--------|\n| 1 | y = 3x | (0,0), (1,3), (2,6) |\n| 2 | y = 0.5x | (0,0), (2,1), (4,2) |\n| 3 | y = 4x | (0,0), (1,4), (2,8) |\n    `,
    mcq1: { questions: [{ question: 'A proportional graph always passes through:', options: ['(0, 0)','(1, 0)','(0, 1)','(1, 1)'], correctAnswer: 0, explanation: 'Proportional → through the origin.' }] },
    mcq2: { questions: [{ question: 'If a line through origin has slope 5, the equation is:', options: ['y = 5x','y = x + 5','y = 5','x = 5y'], correctAnswer: 0, explanation: 'Through origin with slope k: y = kx.' }] },
    input: { boxes: 3, correctAnswers: ['6','2','12'], content: `\n**Graph Values** 🧮\n\n1) $y = 3x$. When $x = 2$, $y = ?$\n\n2) $y = 0.5x$. When $x = 4$, $y = ?$\n\n3) $y = 4x$. When $x = 3$, $y = ?$\n    `, hint1: '3 × 2.', hint2: '0.5 × 4.', hint3: '4 × 3.', explanation: '1) 6. 2) 2. 3) 12.' },
    dropdown: { dropdowns: [{ label: 'The graph of y = kx is a', options: ['Line through the origin','Curve','Horizontal line','Vertical line'] }, { label: 'Slope of y = 3x is', options: ['3','0','1/3','x'] }], correctAnswers: ['Line through the origin','3'], hint1: 'y = kx → linear, through (0,0).', hint2: 'Coefficient of x.', explanation: 'y = kx → straight line through origin. Slope = k = 3.' }
  },
  { introContent: `\n# 📊 Scale Drawings\n\n**Part 4 of 7 — Scale Drawings**\n\nA **scale drawing** uses a ratio to represent real sizes.\n\nScale: $1\\text{ in} = 8\\text{ ft}$ means every inch represents 8 feet.\n\nActual = drawing measurement × scale factor\n    `, workedContent: `\n## Worked Example\n\n**Scale: 1 in = 5 ft. A room is 3 in wide on the drawing. Actual width?**\n\n$3 \\times 5 = 15$ ft ✅\n    `, practiceContent: `\n## Practice\n\n| # | Scale | Drawing | Actual |\n|---|-------|---------|--------|\n| 1 | 1:50 | 4 cm | 200 cm |\n| 2 | 1 in = 10 mi | 3.5 in | 35 mi |\n| 3 | 1:100 | 8 cm | 800 cm |\n    `,
    mcq1: { questions: [{ question: 'Scale 1 in = 10 mi. 3.5 in on map = ?', options: ['35 mi','3.5 mi','13.5 mi','350 mi'], correctAnswer: 0, explanation: '3.5 × 10 = 35 miles.' }] },
    mcq2: { questions: [{ question: 'Scale 1:50. 6 cm on drawing = ?', options: ['300 cm','56 cm','50 cm','6 cm'], correctAnswer: 0, explanation: '6 × 50 = 300 cm.' }] },
    input: { boxes: 3, correctAnswers: ['200','35','800'], content: `\n**Scale Drawings** 🧮\n\n1) Scale 1:50. Drawing: 4 cm. Actual (cm)?\n\n2) Scale 1 in = 10 mi. Drawing: 3.5 in. Actual?\n\n3) Scale 1:100. Drawing: 8 cm. Actual (cm)?\n    `, hint1: '4 × 50.', hint2: '3.5 × 10.', hint3: '8 × 100.', explanation: '1) 200. 2) 35. 3) 800.' },
    dropdown: { dropdowns: [{ label: 'To find actual size from a scale drawing', options: ['Multiply drawing size by scale factor','Divide drawing size by scale factor','Add the scale to drawing size','Subtract'] }, { label: 'Scale 1:25 means 1 unit on paper equals', options: ['25 units in reality','1/25 of a unit','25 papers','Nothing specific'] }], correctAnswers: ['Multiply drawing size by scale factor','25 units in reality'], hint1: 'Scale up from drawing.', hint2: '1:25 is a ratio.', explanation: 'Multiply by scale factor. 1:25 means 1 unit = 25 real units.' }
  },
  { introContent: `\n# 📊 Percent Applications\n\n**Part 5 of 7 — Percent Applications**\n\n### Common Applications\n- **Tax**: Price × tax rate\n- **Tip**: Bill × tip rate\n- **Discount**: Price × discount rate\n- **Markup**: Cost × markup rate\n- **Percent change**: $\\frac{\\text{new} - \\text{old}}{\\text{old}} \\times 100$\n    `, workedContent: `\n## Worked Example\n\n**Meal: \\$45. Tip: 20%. Total?**\n\nTip: $0.20 \\times 45 = 9$. Total: $45 + 9 = 54$ → **\\$54** ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Type |\n|---|---------|------|\n| 1 | \\$80, 10% tax | Tax |\n| 2 | \\$60, 25% off | Discount |\n| 3 | Was \\$40, now \\$50 | % increase |\n    `,
    mcq1: { questions: [{ question: '$80 item + 10% tax. Total?', options: ['$88','$80','$8','$90'], correctAnswer: 0, explanation: 'Tax: 0.10 × 80 = 8. Total: 80 + 8 = 88.' }] },
    mcq2: { questions: [{ question: 'Price went from $40 to $50. Percent increase?', options: ['25%','10%','20%','50%'], correctAnswer: 0, explanation: '(50−40)/40 × 100 = 25%.' }] },
    input: { boxes: 3, correctAnswers: ['88','45','25'], content: `\n**Percent Applications** 🧮\n\n1) \\$80 + 10% tax. Total?\n\n2) \\$60 with 25% off. Sale price?\n\n3) Was \\$40, now \\$50. Percent increase?\n    `, hint1: '80 + 0.10(80).', hint2: '60 − 0.25(60).', hint3: '(50−40)/40 × 100.', explanation: '1) 80+8=88. 2) 60−15=45. 3) 10/40×100=25%.' },
    dropdown: { dropdowns: [{ label: 'To find tax on an item, multiply price by', options: ['Tax rate as a decimal','Tax rate as a whole number','100','The price again'] }, { label: 'A 20% discount on $100 saves you', options: ['$20','$80','$120','$2'] }], correctAnswers: ['Tax rate as a decimal','$20'], hint1: 'Convert percent to decimal.', hint2: '0.20 × 100.', explanation: 'Tax = price × rate. 0.20 × 100 = $20 saved.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nApply proportional reasoning:\n- Unit rates and comparison shopping\n- Scale models\n- Percent change problems\n    `, workedContent: `\n## Worked Example\n\n**Store A: 5 for \\$12. Store B: 8 for \\$20. Which is cheaper?**\n\nA: $12/5 = \\$2.40. B: $20/8 = \\$2.50$. **Store A** is cheaper. ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Method |\n|---|---------|--------|\n| 1 | 3 lb for \\$6 vs 5 lb for \\$9 | Unit rate |\n| 2 | Map: 2 in = 30 mi, distance is 5 in | Scale |\n| 3 | Population: 200→250. % change? | Formula |\n    `,
    mcq1: { questions: [{ question: '3 lb for $6 vs 5 lb for $9. Better deal?', options: ['5 lb for $9','3 lb for $6','Same price','Cannot tell'], correctAnswer: 0, explanation: '$6/3=$2/lb vs $9/5=$1.80/lb. 5 lb is cheaper.' }] },
    mcq2: { questions: [{ question: 'Map: 2 in = 30 mi. 5 in = ?', options: ['75 mi','150 mi','30 mi','60 mi'], correctAnswer: 0, explanation: '2:30 = 5:x → x = 75.' }] },
    input: { boxes: 3, correctAnswers: ['1.8','75','25'], content: `\n**Problem Solving** 🧮\n\n1) 5 lb for \\$9. Price per pound? (decimal)\n\n2) Map: 2 in = 30 mi. 5 in = ? mi\n\n3) Population: 200 → 250. Percent increase?\n    `, hint1: '9 ÷ 5.', hint2: 'Proportion: 2/30 = 5/x.', hint3: '(250−200)/200 × 100.', explanation: '1) 9÷5=1.8. 2) 5×15=75. 3) 50/200=25%.' },
    dropdown: { dropdowns: [{ label: 'To compare prices, use', options: ['Unit rate','Total cost only','Number of items only','Weight only'] }, { label: 'Percent change formula', options: ['(new−old)/old × 100','(old−new)/new × 100','new/old × 100','old − new'] }], correctAnswers: ['Unit rate','(new−old)/old × 100'], hint1: 'Price per unit.', hint2: 'Change divided by original.', explanation: 'Unit rate for comparison. % change = (new−old)/old × 100.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Concepts\n- Proportional: constant y/x = k, through origin\n- Equation: y = kx\n- Graph: straight line through (0,0)\n- Scale: multiply by scale factor\n- Percent: part = rate × whole\n    `, workedContent: `\n## Worked Example\n\n**y = 4x. Find y when x = 7.**\n$y = 4(7) = 28$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | k | (5, 15): k = ? |\n| 2 | Equation | y when x=8, k=3 |\n| 3 | Percent | 15% of 200 |\n    `,
    mcq1: { questions: [{ question: '(5, 15): k = ?', options: ['3','5','15','75'], correctAnswer: 0, explanation: 'k = 15/5 = 3.' }] },
    mcq2: { questions: [{ question: '15% of 200 = ?', options: ['30','15','300','3'], correctAnswer: 0, explanation: '0.15 × 200 = 30.' }] },
    input: { boxes: 3, correctAnswers: ['3','24','30'], content: `\n**Review** 🧮\n\n1) (5, 15): k = ?\n\n2) y = 3x. When x = 8, y = ?\n\n3) 15% of 200 = ?\n    `, hint1: '15 ÷ 5.', hint2: '3 × 8.', hint3: '0.15 × 200.', explanation: '1) 3. 2) 24. 3) 30.' },
    dropdown: { dropdowns: [{ label: 'y = kx represents a', options: ['Proportional relationship','Quadratic','Exponential','Inverse variation'] }, { label: 'A proportional graph is a straight line that passes through', options: ['(0, 0)','(1, 1)','(0, k)','(k, 0)'] }], correctAnswers: ['Proportional relationship','(0, 0)'], hint1: 'Direct variation.', hint2: 'Proportional → origin.', explanation: 'y = kx → proportional. Always through the origin.' }
  }
]

};
