/**
 * Content patches for Pre-Algebra topics:
 * - prealgebra-fractions-decimals (7 parts)
 * - prealgebra-intro-variables (7 parts)
 * - prealgebra-order-of-operations (7 parts)
 */
module.exports = {

'prealgebra-fractions-decimals': [
  { introContent: `\n# 📐 Converting Fractions & Decimals\n\n**Part 1 of 7 — Converting Fractions & Decimals**\n\n### Fraction → Decimal\nDivide numerator by denominator: $\\frac{3}{4} = 3 \\div 4 = 0.75$\n\n### Decimal → Fraction\nUse place value: $0.6 = \\frac{6}{10} = \\frac{3}{5}$\n    `, workedContent: `\n## Worked Example\n\n$\\frac{7}{8} = 7 \\div 8 = 0.875$ ✅\n\n$0.35 = \\frac{35}{100} = \\frac{7}{20}$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Conversion | Answer |\n|---|-----------|--------|\n| 1 | 1/4 → decimal | 0.25 |\n| 2 | 3/5 → decimal | 0.6 |\n| 3 | 0.75 → fraction | 3/4 |\n    `,
    mcq1: { questions: [{ question: '$\\frac{3}{4}$ as a decimal?', options: ['0.75','0.34','0.43','7.5'], correctAnswer: 0, explanation: '3 ÷ 4 = 0.75.' }] },
    mcq2: { questions: [{ question: '$0.6$ as a fraction in lowest terms?', options: ['3/5','6/10','6/100','1/6'], correctAnswer: 0, explanation: '6/10 = 3/5.' }] },
    input: { boxes: 3, correctAnswers: ['0.25','0.6','0.875'], content: `\n**Convert to Decimals** 🧮\n\n1) $\\frac{1}{4} = ?$\n\n2) $\\frac{3}{5} = ?$\n\n3) $\\frac{7}{8} = ?$\n    `, hint1: '1 ÷ 4.', hint2: '3 ÷ 5.', hint3: '7 ÷ 8.', explanation: '1) 0.25. 2) 0.6. 3) 0.875.' },
    dropdown: { dropdowns: [{ label: 'To convert a fraction to a decimal', options: ['Divide numerator by denominator','Multiply top and bottom','Add them together','Flip the fraction'] }, { label: '0.5 as a fraction is', options: ['1/2','5/10','1/5','5/100'] }], correctAnswers: ['Divide numerator by denominator','1/2'], hint1: 'Numerator ÷ denominator.', hint2: '5/10 simplified.', explanation: 'Fraction→decimal: divide. 0.5 = 1/2.' }
  },
  { introContent: `\n# 📊 Converting to Percents\n\n**Part 2 of 7 — Converting to Percents**\n\n### Decimal → Percent\nMultiply by 100: $0.45 = 45\\%$\n\n### Fraction → Percent\nConvert to decimal first, then multiply by 100: $\\frac{3}{4} = 0.75 = 75\\%$\n\n### Percent → Decimal\nDivide by 100: $60\\% = 0.60$\n    `, workedContent: `\n## Worked Example\n\n$\\frac{2}{5} = 0.4 = 40\\%$ ✅\n\n$85\\% = 0.85$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Convert | Answer |\n|---|---------|--------|\n| 1 | 0.3 → % | 30% |\n| 2 | 1/4 → % | 25% |\n| 3 | 75% → decimal | 0.75 |\n    `,
    mcq1: { questions: [{ question: '$0.3$ as a percent?', options: ['30%','3%','0.3%','300%'], correctAnswer: 0, explanation: '0.3 × 100 = 30%.' }] },
    mcq2: { questions: [{ question: '$\\frac{1}{4}$ as a percent?', options: ['25%','14%','4%','75%'], correctAnswer: 0, explanation: '1/4 = 0.25 = 25%.' }] },
    input: { boxes: 3, correctAnswers: ['30','25','0.75'], content: `\n**Convert** 🧮\n\n1) 0.3 = ? % (number only)\n\n2) 1/4 = ? % (number only)\n\n3) 75% = ? (decimal)\n    `, hint1: '0.3 × 100.', hint2: '0.25 × 100.', hint3: '75 ÷ 100.', explanation: '1) 30. 2) 25. 3) 0.75.' },
    dropdown: { dropdowns: [{ label: 'To convert a decimal to a percent', options: ['Multiply by 100','Divide by 100','Add 100','Subtract 100'] }, { label: '50% as a fraction is', options: ['1/2','5/10','50/10','1/50'] }], correctAnswers: ['Multiply by 100','1/2'], hint1: 'Move decimal point right 2.', hint2: '50/100 simplified.', explanation: 'Decimal→%: ×100. 50% = 1/2.' }
  },
  { introContent: `\n# 🔢 Comparing Values\n\n**Part 3 of 7 — Comparing Values**\n\nTo compare fractions, decimals, and percents: **convert to the same form**.\n\nEasiest: convert everything to decimals.\n\n$\\frac{3}{8}$ vs $0.4$: $3÷8 = 0.375 < 0.4$ ✅\n    `, workedContent: `\n## Worked Example\n\n**Order from least to greatest: $\\frac{1}{3}$, 0.3, 35%**\n\n$\\frac{1}{3} \\approx 0.333$, $0.3$, $35\\% = 0.35$\n\nOrder: $0.3 < 0.333 < 0.35$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Values | Smallest |\n|---|--------|----------|\n| 1 | 0.5, 3/8, 45% | 3/8 |\n| 2 | 1/4, 0.3, 20% | 20% |\n| 3 | 0.7, 3/4, 72% | 0.7 |\n    `,
    mcq1: { questions: [{ question: 'Which is smallest: 0.5, 3/8, 45%?', options: ['3/8','0.5','45%','All equal'], correctAnswer: 0, explanation: '3/8=0.375, 45%=0.45, 0.5. Smallest is 0.375.' }] },
    mcq2: { questions: [{ question: 'To compare fractions and decimals, convert to:', options: ['The same form','Different forms','Whole numbers','Percents only'], correctAnswer: 0, explanation: 'Same form allows direct comparison.' }] },
    input: { boxes: 3, correctAnswers: ['0.375','0.45','0.75'], content: `\n**Convert to Decimals to Compare** 🧮\n\n1) $\\frac{3}{8} = ?$\n\n2) $45\\% = ?$\n\n3) $\\frac{3}{4} = ?$\n    `, hint1: '3 ÷ 8.', hint2: '45 ÷ 100.', hint3: '3 ÷ 4.', explanation: '1) 0.375. 2) 0.45. 3) 0.75.' },
    dropdown: { dropdowns: [{ label: 'The best way to compare fractions and decimals is to', options: ['Convert to the same form','Leave them as is','Guess','Multiply them together'] }, { label: 'Which is greater: 2/5 or 0.35?', options: ['2/5','0.35','They are equal','Cannot compare'] }], correctAnswers: ['Convert to the same form','2/5'], hint1: 'Common ground.', hint2: '2/5 = 0.4 > 0.35.', explanation: 'Convert to same form. 2/5=0.4 > 0.35.' }
  },
  { introContent: `\n# 📈 Operations with Mixed Forms\n\n**Part 4 of 7 — Operations with Mixed Forms**\n\nWhen adding/subtracting fractions and decimals:\n1. Convert everything to the **same form**\n2. Then perform the operation\n\n$\\frac{1}{2} + 0.3 = 0.5 + 0.3 = 0.8$\n    `, workedContent: `\n## Worked Example\n\n$\\frac{3}{4} + 0.5 = 0.75 + 0.5 = 1.25$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Answer |\n|---|---------|--------|\n| 1 | $\\frac{1}{2} + 0.3$ | 0.8 |\n| 2 | $0.75 - \\frac{1}{4}$ | 0.5 |\n| 3 | $\\frac{1}{5} + 0.6$ | 0.8 |\n    `,
    mcq1: { questions: [{ question: '$\\frac{1}{2} + 0.3 = ?$', options: ['0.8','1.3','0.13','0.53'], correctAnswer: 0, explanation: '0.5 + 0.3 = 0.8.' }] },
    mcq2: { questions: [{ question: '$0.75 - \\frac{1}{4} = ?$', options: ['0.5','1.0','0.25','0.74'], correctAnswer: 0, explanation: '0.75 − 0.25 = 0.5.' }] },
    input: { boxes: 3, correctAnswers: ['0.8','0.5','0.8'], content: `\n**Mixed Operations** 🧮\n\n1) $\\frac{1}{2} + 0.3 = ?$\n\n2) $0.75 - \\frac{1}{4} = ?$\n\n3) $\\frac{1}{5} + 0.6 = ?$\n    `, hint1: '0.5 + 0.3.', hint2: '0.75 − 0.25.', hint3: '0.2 + 0.6.', explanation: '1) 0.8. 2) 0.5. 3) 0.8.' },
    dropdown: { dropdowns: [{ label: 'To add a fraction and a decimal', options: ['Convert to the same form first','Just add numbers','Ignore the fraction','Use cross multiplication'] }, { label: '$\\frac{1}{4} + 0.25 =$', options: ['0.5','0.5025','0.125','0.75'] }], correctAnswers: ['Convert to the same form first','0.5'], hint1: 'Must be same type.', hint2: '0.25 + 0.25.', explanation: 'Convert first, then operate. 0.25+0.25=0.5.' }
  },
  { introContent: `\n# 🧮 Real-World Applications\n\n**Part 5 of 7 — Real-World Applications**\n\nFractions, decimals, and percents appear everywhere:\n- **Shopping**: discounts, sales tax\n- **Cooking**: recipe measurements\n- **Grades**: test scores\n- **Sports**: batting averages\n    `, workedContent: `\n## Worked Example\n\n**Test: 18 out of 20. What percent?**\n\n$\\frac{18}{20} = 0.9 = 90\\%$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Answer |\n|---|---------|--------|\n| 1 | 15/20 as % | 75% |\n| 2 | 30% of 50 | 15 |\n| 3 | Recipe: half of 3/4 cup | 3/8 cup |\n    `,
    mcq1: { questions: [{ question: '15 out of 20 as a percent?', options: ['75%','15%','20%','80%'], correctAnswer: 0, explanation: '15/20 = 0.75 = 75%.' }] },
    mcq2: { questions: [{ question: '30% of 50?', options: ['15','30','50','1500'], correctAnswer: 0, explanation: '0.30 × 50 = 15.' }] },
    input: { boxes: 3, correctAnswers: ['75','15','90'], content: `\n**Applications** 🧮\n\n1) 15/20 as a percent?\n\n2) 30% of 50?\n\n3) 18/20 as a percent?\n    `, hint1: '15 ÷ 20 × 100.', hint2: '0.30 × 50.', hint3: '18 ÷ 20 × 100.', explanation: '1) 75. 2) 15. 3) 90.' },
    dropdown: { dropdowns: [{ label: 'To find a percent of a number', options: ['Convert % to decimal and multiply','Just subtract the percent','Add the percent','Divide by the percent'] }, { label: 'A batting average of .300 means', options: ['30%','3%','300%','0.3%'] }], correctAnswers: ['Convert % to decimal and multiply','30%'], hint1: 'Percent → decimal → multiply.', hint2: '0.300 = 30%.', explanation: '% of a number: convert and multiply. 0.300 = 30%.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nSolve problems involving fractions, decimals, and percents:\n- Identify what form the answer should be in\n- Choose the most efficient conversion\n    `, workedContent: `\n## Worked Example\n\n**Shirt: \\$40, 25% off. Sale price?**\n\nDiscount: $0.25 \\times 40 = 10$. Sale price: $40 - 10 = \\$30$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Answer |\n|---|---------|--------|\n| 1 | \\$60, 20% off | \\$48 |\n| 2 | Tip: 15% of \\$80 | \\$12 |\n| 3 | Score: 42/50 as % | 84% |\n    `,
    mcq1: { questions: [{ question: '$60 shirt, 20% off. Sale price?', options: ['$48','$40','$12','$80'], correctAnswer: 0, explanation: '0.20 × 60 = 12. 60 − 12 = $48.' }] },
    mcq2: { questions: [{ question: '15% tip on $80?', options: ['$12','$15','$80','$95'], correctAnswer: 0, explanation: '0.15 × 80 = $12.' }] },
    input: { boxes: 3, correctAnswers: ['48','12','84'], content: `\n**Word Problems** 🧮\n\n1) \\$60 shirt, 20% off. Sale price?\n\n2) 15% tip on \\$80?\n\n3) 42 out of 50. Percent?\n    `, hint1: '60 − 0.20(60).', hint2: '0.15 × 80.', hint3: '42÷50 × 100.', explanation: '1) 60−12=48. 2) 12. 3) 84.' },
    dropdown: { dropdowns: [{ label: 'A 25% discount means you pay', options: ['75% of the price','25% of the price','The full price','125% of the price'] }, { label: 'To find the sale price after a discount', options: ['Subtract the discount from original price','Add the discount','Multiply by the discount','Divide by the discount'] }], correctAnswers: ['75% of the price','Subtract the discount from original price'], hint1: '100% − 25% = 75%.', hint2: 'Original − discount amount.', explanation: '25% off → pay 75%. Sale = original − discount.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Conversion Cheat Sheet\n| From | To | Method |\n|------|-----|--------|\n| Fraction → Decimal | Divide | ÷ |\n| Decimal → Percent | × 100 | Move decimal right 2 |\n| Percent → Decimal | ÷ 100 | Move decimal left 2 |\n| Fraction → Percent | Convert to decimal first | Then × 100 |\n    `, workedContent: `\n## Worked Example\n\n$\\frac{5}{8} = 0.625 = 62.5\\%$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Fraction→Decimal | 2/5 |\n| 2 | Decimal→Percent | 0.85 |\n| 3 | Percent of | 40% of 200 |\n    `,
    mcq1: { questions: [{ question: '$\\frac{2}{5}$ as a decimal?', options: ['0.4','0.25','2.5','0.2'], correctAnswer: 0, explanation: '2 ÷ 5 = 0.4.' }] },
    mcq2: { questions: [{ question: '40% of 200?', options: ['80','40','200','8'], correctAnswer: 0, explanation: '0.40 × 200 = 80.' }] },
    input: { boxes: 3, correctAnswers: ['0.4','85','80'], content: `\n**Review** 🧮\n\n1) $\\frac{2}{5}$ as a decimal?\n\n2) 0.85 as a percent? (number only)\n\n3) 40% of 200?\n    `, hint1: '2 ÷ 5.', hint2: '0.85 × 100.', hint3: '0.40 × 200.', explanation: '1) 0.4. 2) 85. 3) 80.' },
    dropdown: { dropdowns: [{ label: 'Fraction to decimal: ___', options: ['Divide numerator by denominator','Multiply by 100','Add them','Flip the fraction'] }, { label: '100% equals', options: ['1 whole','100 pieces','10 tenths','Nothing'] }], correctAnswers: ['Divide numerator by denominator','1 whole'], hint1: 'Top ÷ bottom.', hint2: '100% = 1.00.', explanation: 'Fraction→decimal: divide. 100% = 1 whole.' }
  }
],

'prealgebra-intro-variables': [
  { introContent: `\n# 📐 What is a Variable?\n\n**Part 1 of 7 — What is a Variable?**\n\nA **variable** is a letter that represents an unknown number.\n\n- $x + 5 = 12$ (x is unknown)\n- Variables can represent any value\n- Common letters: $x, y, n, a$\n    `, workedContent: `\n## Worked Example\n\n**If a box of crayons has $n$ crayons, and you buy 3 boxes, total = $3n$.**\n\nWhen $n = 24$: $3(24) = 72$ crayons ✅\n    `, practiceContent: `\n## Practice\n\n| # | Phrase | Expression |\n|---|--------|------------|\n| 1 | 5 more than x | x + 5 |\n| 2 | 3 times n | 3n |\n| 3 | y decreased by 7 | y − 7 |\n    `,
    mcq1: { questions: [{ question: '"5 more than x" as an expression?', options: ['x + 5','5x','x − 5','5 − x'], correctAnswer: 0, explanation: '"More than" means addition.' }] },
    mcq2: { questions: [{ question: 'A variable is:', options: ['A letter representing an unknown number','Always equal to x','A fixed number','An operation'], correctAnswer: 0, explanation: 'Variables represent unknowns.' }] },
    input: { boxes: 3, correctAnswers: ['8','15','3'], content: `\n**Evaluate** 🧮\n\nLet $x = 3$.\n\n1) $x + 5 = ?$\n\n2) $5x = ?$\n\n3) $x$ itself = ?\n    `, hint1: '3 + 5.', hint2: '5 × 3.', hint3: 'x = 3.', explanation: '1) 8. 2) 15. 3) 3.' },
    dropdown: { dropdowns: [{ label: 'A variable is a letter that represents', options: ['An unknown number','A specific number always','An operation','Nothing'] }, { label: 'In 3x, the 3 is called the', options: ['Coefficient','Variable','Constant','Exponent'] }], correctAnswers: ['An unknown number','Coefficient'], hint1: 'Letters for unknowns.', hint2: 'Number multiplied by the variable.', explanation: 'Variable = unknown. Coefficient = number in front.' }
  },
  { introContent: `\n# 📊 Writing Expressions\n\n**Part 2 of 7 — Writing Expressions**\n\nTranslate words to algebra:\n\n| Word | Operation |\n|------|-----------|\n| sum, plus, more than | + |\n| difference, minus, less than | − |\n| product, times, of | × |\n| quotient, divided by | ÷ |\n    `, workedContent: `\n## Worked Example\n\n**"The product of 4 and a number decreased by 7."**\n\n$4n - 7$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Phrase | Expression |\n|---|--------|--------|\n| 1 | Twice a number plus 3 | 2n + 3 |\n| 2 | 10 less than x | x − 10 |\n| 3 | A number divided by 5 | n/5 |\n    `,
    mcq1: { questions: [{ question: '"Twice a number plus 3":', options: ['2n + 3','2 + 3n','n + 6','2(n+3)'], correctAnswer: 0, explanation: 'Twice = 2n, plus 3.' }] },
    mcq2: { questions: [{ question: '"10 less than x":', options: ['x − 10','10 − x','x + 10','10x'], correctAnswer: 0, explanation: '"Less than" subtracts from x.' }] },
    input: { boxes: 3, correctAnswers: ['13','2','6'], content: `\n**Evaluate Expressions** 🧮\n\nLet $n = 5$.\n\n1) $2n + 3 = ?$\n\n2) $n \\div 5 + 1 = ?$\n\n3) $4n - 14 = ?$\n    `, hint1: '2(5) + 3.', hint2: '5/5 + 1.', hint3: '4(5) − 14.', explanation: '1) 10+3=13. 2) 1+1=2. 3) 20−14=6.' },
    dropdown: { dropdowns: [{ label: '"The sum of a number and 8" is', options: ['n + 8','n − 8','8n','n/8'] }, { label: '"Less than" means to', options: ['Subtract','Add','Multiply','Divide'] }], correctAnswers: ['n + 8','Subtract'], hint1: 'Sum = addition.', hint2: 'Less = take away.', explanation: 'Sum → addition. Less than → subtraction.' }
  },
  { introContent: `\n# 🔢 Evaluating Expressions\n\n**Part 3 of 7 — Evaluating Expressions**\n\nTo **evaluate** an expression:\n1. Substitute the given value for the variable\n2. Follow order of operations (PEMDAS)\n\n$3x + 2$ when $x = 4$: $3(4) + 2 = 14$\n    `, workedContent: `\n## Worked Example\n\n$2x^2 - 5$ when $x = 3$:\n\n$2(3)^2 - 5 = 2(9) - 5 = 18 - 5 = 13$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | x | Value |\n|---|-----------|---|-------|\n| 1 | 4x + 1 | 3 | 13 |\n| 2 | x² + 2 | 5 | 27 |\n| 3 | 3x − 7 | 4 | 5 |\n    `,
    mcq1: { questions: [{ question: '$4x + 1$ when $x = 3$?', options: ['13','12','43','15'], correctAnswer: 0, explanation: '4(3) + 1 = 12 + 1 = 13.' }] },
    mcq2: { questions: [{ question: '$x^2 + 2$ when $x = 5$?', options: ['27','12','52','7'], correctAnswer: 0, explanation: '25 + 2 = 27.' }] },
    input: { boxes: 3, correctAnswers: ['13','27','5'], content: `\n**Evaluate** 🧮\n\n1) $4x + 1$ when $x = 3$?\n\n2) $x^2 + 2$ when $x = 5$?\n\n3) $3x - 7$ when $x = 4$?\n    `, hint1: '4(3) + 1.', hint2: '5² + 2.', hint3: '3(4) − 7.', explanation: '1) 13. 2) 27. 3) 5.' },
    dropdown: { dropdowns: [{ label: 'To evaluate means to', options: ['Find the value by substituting','Simplify without values','Guess the answer','Skip the variable'] }, { label: 'When x=2, x² means', options: ['2² = 4','2×2 = 4','2+2 = 4','All of these are equivalent'] }], correctAnswers: ['Find the value by substituting','All of these are equivalent'], hint1: 'Substitute and calculate.', hint2: 'x²=x×x.', explanation: 'Evaluate: plug in and compute. x²=x×x.' }
  },
  { introContent: `\n# 📈 Combining Like Terms\n\n**Part 4 of 7 — Combining Like Terms**\n\n**Like terms** have the same variable raised to the same power.\n\n$3x + 5x = 8x$ ✅ (like terms)\n$3x + 5y$ → cannot combine (different variables)\n$2x^2 + 3x$ → cannot combine (different powers)\n    `, workedContent: `\n## Worked Example\n\n$4x + 3 + 2x + 7 = (4x + 2x) + (3 + 7) = 6x + 10$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Simplified |\n|---|-----------|------------|\n| 1 | 5x + 3x | 8x |\n| 2 | 2y + 4 + 3y + 1 | 5y + 5 |\n| 3 | 7a − 2a + 6 | 5a + 6 |\n    `,
    mcq1: { questions: [{ question: '$5x + 3x = ?$', options: ['8x','15x','53x','8x²'], correctAnswer: 0, explanation: 'Add coefficients: 5+3 = 8.' }] },
    mcq2: { questions: [{ question: 'Which are like terms?', options: ['3x and 7x','3x and 7y','3x and 3x²','3 and 3x'], correctAnswer: 0, explanation: 'Same variable, same power.' }] },
    input: { boxes: 3, correctAnswers: ['8','5','5'], content: `\n**Combine Like Terms** 🧮\n\n1) $5x + 3x = ?x$\n\n2) $2y + 3y = ?y$\n\n3) $7a - 2a = ?a$\n    `, hint1: '5 + 3.', hint2: '2 + 3.', hint3: '7 − 2.', explanation: '1) 8x. 2) 5y. 3) 5a.' },
    dropdown: { dropdowns: [{ label: 'Like terms have the same', options: ['Variable and exponent','Coefficient','Value','Number'] }, { label: '$3x + 5$ has how many terms?', options: ['2','1','3','8'] }], correctAnswers: ['Variable and exponent','2'], hint1: 'Match variable and power.', hint2: '3x is one term, 5 is another.', explanation: 'Like terms: same variable and power. 3x+5 has 2 terms.' }
  },
  { introContent: `\n# 🧮 Solving Simple Equations\n\n**Part 5 of 7 — Solving Simple Equations**\n\nGoal: get the variable **alone** on one side.\n\n### Inverse Operations\n- Addition ↔ Subtraction\n- Multiplication ↔ Division\n\n$x + 5 = 12 \\Rightarrow x = 12 - 5 = 7$\n    `, workedContent: `\n## Worked Example\n\n$3x + 4 = 19$\n\nStep 1: $3x = 19 - 4 = 15$\nStep 2: $x = 15 \\div 3 = 5$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Equation | Solution |\n|---|---------|----------|\n| 1 | x + 7 = 15 | x = 8 |\n| 2 | 2x = 14 | x = 7 |\n| 3 | 3x + 1 = 10 | x = 3 |\n    `,
    mcq1: { questions: [{ question: '$x + 7 = 15$. $x = ?$', options: ['8','22','7','15'], correctAnswer: 0, explanation: 'x = 15 − 7 = 8.' }] },
    mcq2: { questions: [{ question: '$2x = 14$. $x = ?$', options: ['7','28','12','2'], correctAnswer: 0, explanation: 'x = 14 ÷ 2 = 7.' }] },
    input: { boxes: 3, correctAnswers: ['8','7','3'], content: `\n**Solve** 🧮\n\n1) $x + 7 = 15$. $x = ?$\n\n2) $2x = 14$. $x = ?$\n\n3) $3x + 1 = 10$. $x = ?$\n    `, hint1: '15 − 7.', hint2: '14 ÷ 2.', hint3: '3x = 9, then 9 ÷ 3.', explanation: '1) 8. 2) 7. 3) 3.' },
    dropdown: { dropdowns: [{ label: 'To undo addition, use', options: ['Subtraction','Addition','Multiplication','Division'] }, { label: 'To undo multiplication, use', options: ['Division','Multiplication','Addition','Subtraction'] }], correctAnswers: ['Subtraction','Division'], hint1: 'Inverse operations.', hint2: 'Inverse of multiply.', explanation: 'Add↔subtract. Multiply↔divide.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nTranslate word problems to equations:\n1. Identify the unknown → variable\n2. Translate relationships → equation\n3. Solve\n    `, workedContent: `\n## Worked Example\n\n**"A number plus 8 equals 20. What is the number?"**\n\n$n + 8 = 20$\n$n = 12$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Equation | Answer |\n|---|---------|----------|--------|\n| 1 | 5 more than x is 17 | x+5=17 | x=12 |\n| 2 | Triple a number is 24 | 3n=24 | n=8 |\n| 3 | x minus 9 = 6 | x−9=6 | x=15 |\n    `,
    mcq1: { questions: [{ question: '"5 more than x is 17." x = ?', options: ['12','22','85','3'], correctAnswer: 0, explanation: 'x + 5 = 17 → x = 12.' }] },
    mcq2: { questions: [{ question: '"Triple a number is 24." The number?', options: ['8','72','21','3'], correctAnswer: 0, explanation: '3n = 24 → n = 8.' }] },
    input: { boxes: 3, correctAnswers: ['12','8','15'], content: `\n**Word Problems** 🧮\n\n1) 5 more than x is 17. x = ?\n\n2) Triple a number is 24. n = ?\n\n3) x minus 9 equals 6. x = ?\n    `, hint1: 'x + 5 = 17.', hint2: '3n = 24.', hint3: 'x − 9 = 6.', explanation: '1) 12. 2) 8. 3) 15.' },
    dropdown: { dropdowns: [{ label: '"Is" or "equals" translates to', options: ['=','+ ','×','≠'] }, { label: '"Triple" means multiply by', options: ['3','2','4','1/3'] }], correctAnswers: ['=','3'], hint1: 'Is/equals → equal sign.', hint2: 'Triple = three times.', explanation: '"Is" → =. Triple → ×3.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### Key Concepts\n- Variables represent unknowns\n- Translate words → expressions/equations\n- Evaluate by substituting\n- Like terms: same variable & power\n- Solve: use inverse operations\n    `, workedContent: `\n## Worked Example\n\n$4x - 3 = 21$\n$4x = 24$\n$x = 6$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Type | Problem |\n|---|------|---------|\n| 1 | Evaluate | 3x+2, x=4 |\n| 2 | Combine | 6y+2y |\n| 3 | Solve | 5x=35 |\n    `,
    mcq1: { questions: [{ question: '$3x + 2$ when $x=4$?', options: ['14','34','12','9'], correctAnswer: 0, explanation: '3(4)+2 = 14.' }] },
    mcq2: { questions: [{ question: '$5x = 35$. $x = ?$', options: ['7','30','175','40'], correctAnswer: 0, explanation: '35 ÷ 5 = 7.' }] },
    input: { boxes: 3, correctAnswers: ['14','8','7'], content: `\n**Review** 🧮\n\n1) $3x + 2$ when $x = 4$?\n\n2) $6y + 2y = ?y$ (coefficient)\n\n3) $5x = 35$. $x = ?$\n    `, hint1: '3(4) + 2.', hint2: '6 + 2.', hint3: '35 ÷ 5.', explanation: '1) 14. 2) 8. 3) 7.' },
    dropdown: { dropdowns: [{ label: 'An expression does NOT have', options: ['An equal sign','Variables','Numbers','Operations'] }, { label: 'An equation HAS', options: ['An equal sign','Only one term','No variables','No numbers'] }], correctAnswers: ['An equal sign','An equal sign'], hint1: 'Expressions vs equations.', hint2: 'Equals sign is the key.', explanation: 'Expressions: no =. Equations: have =.' }
  }
],

'prealgebra-order-of-operations': [
  { introContent: `\n# 📐 PEMDAS Basics\n\n**Part 1 of 7 — PEMDAS Basics**\n\n**P**arentheses → **E**xponents → **M**ultiplication/**D**ivision → **A**ddition/**S**ubtraction\n\nM/D and A/S are done **left to right** (equal priority within each pair).\n    `, workedContent: `\n## Worked Example\n\n$3 + 4 \\times 2 = ?$\n\nMultiplication first: $4 \\times 2 = 8$. Then $3 + 8 = 11$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Value |\n|---|-----------|-------|\n| 1 | 5 + 2 × 3 | 11 |\n| 2 | 8 − 4 ÷ 2 | 6 |\n| 3 | 6 × 3 + 1 | 19 |\n    `,
    mcq1: { questions: [{ question: '$5 + 2 \\times 3 = ?$', options: ['11','21','10','9'], correctAnswer: 0, explanation: '2×3=6. 5+6=11.' }] },
    mcq2: { questions: [{ question: 'In PEMDAS, what comes first?', options: ['Parentheses','Exponents','Multiplication','Addition'], correctAnswer: 0, explanation: 'P is first: Parentheses.' }] },
    input: { boxes: 3, correctAnswers: ['11','6','19'], content: `\n**PEMDAS Basics** 🧮\n\n1) $5 + 2 \\times 3 = ?$\n\n2) $8 - 4 \\div 2 = ?$\n\n3) $6 \\times 3 + 1 = ?$\n    `, hint1: 'Multiply first.', hint2: 'Divide first.', hint3: 'Multiply first.', explanation: '1) 5+6=11. 2) 8−2=6. 3) 18+1=19.' },
    dropdown: { dropdowns: [{ label: 'PEMDAS stands for', options: ['Parentheses, Exponents, Multiplication, Division, Addition, Subtraction','Please Excuse My Dear Aunt Sally','Both of these','Neither'] }, { label: 'Multiplication and division have', options: ['Equal priority','Multiplication first','Division first','No priority'] }], correctAnswers: ['Both of these','Equal priority'], hint1: 'Both are mnemonics for the same thing.', hint2: 'Left to right for tied operations.', explanation: 'PEMDAS = Please Excuse My Dear Aunt Sally. M and D have equal priority.' }
  },
  { introContent: `\n# 📊 Parentheses & Exponents\n\n**Part 2 of 7 — Parentheses & Exponents**\n\n**Parentheses** first: work inside out.\n**Exponents** second: evaluate powers.\n\n$(3 + 2)^2 = 5^2 = 25$ (parentheses first, then exponent)\n    `, workedContent: `\n## Worked Example\n\n$(4 + 1)^2 - 3 = 5^2 - 3 = 25 - 3 = 22$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Value |\n|---|-----------|-------|\n| 1 | (2+3)² | 25 |\n| 2 | 2(6−2) | 8 |\n| 3 | 4² + 1 | 17 |\n    `,
    mcq1: { questions: [{ question: '$(2 + 3)^2 = ?$', options: ['25','10','13','7'], correctAnswer: 0, explanation: '(5)² = 25.' }] },
    mcq2: { questions: [{ question: '$2(6 - 2) = ?$', options: ['8','10','16','4'], correctAnswer: 0, explanation: '2(4) = 8.' }] },
    input: { boxes: 3, correctAnswers: ['25','8','17'], content: `\n**Parentheses & Exponents** 🧮\n\n1) $(2 + 3)^2 = ?$\n\n2) $2(6 - 2) = ?$\n\n3) $4^2 + 1 = ?$\n    `, hint1: 'Inside first: 2+3=5.', hint2: 'Inside first: 6−2=4.', hint3: 'Exponent first: 4²=16.', explanation: '1) 25. 2) 8. 3) 17.' },
    dropdown: { dropdowns: [{ label: 'Parentheses are evaluated', options: ['First (innermost out)','Last','After exponents','After multiplication'] }, { label: '$3^2$ means', options: ['3 × 3','3 × 2','3 + 2','2 × 2 × 2'] }], correctAnswers: ['First (innermost out)','3 × 3'], hint1: 'P comes first in PEMDAS.', hint2: 'Base × base.', explanation: 'Parentheses first. 3² = 3×3 = 9.' }
  },
  { introContent: `\n# 🔢 Multiplication & Division\n\n**Part 3 of 7 — Multiplication & Division**\n\nAfter parentheses and exponents: **multiply and divide left to right**.\n\n$24 \\div 6 \\times 2 = 4 \\times 2 = 8$ (left to right, NOT $24 \\div 12$)\n    `, workedContent: `\n## Worked Example\n\n$12 \\div 3 \\times 4 = 4 \\times 4 = 16$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Value |\n|---|-----------|-------|\n| 1 | 20 ÷ 4 × 3 | 15 |\n| 2 | 2 × 6 ÷ 3 | 4 |\n| 3 | 18 ÷ 2 ÷ 3 | 3 |\n    `,
    mcq1: { questions: [{ question: '$20 \\div 4 \\times 3 = ?$', options: ['15','5/3','60/4','20/12'], correctAnswer: 0, explanation: 'Left to right: 5 × 3 = 15.' }] },
    mcq2: { questions: [{ question: '$18 \\div 2 \\div 3 = ?$', options: ['3','27','9','1'], correctAnswer: 0, explanation: 'Left to right: 9 ÷ 3 = 3.' }] },
    input: { boxes: 3, correctAnswers: ['15','4','3'], content: `\n**Multiply & Divide Left to Right** 🧮\n\n1) $20 \\div 4 \\times 3 = ?$\n\n2) $2 \\times 6 \\div 3 = ?$\n\n3) $18 \\div 2 \\div 3 = ?$\n    `, hint1: '20÷4=5, then 5×3.', hint2: '2×6=12, then 12÷3.', hint3: '18÷2=9, then 9÷3.', explanation: '1) 15. 2) 4. 3) 3.' },
    dropdown: { dropdowns: [{ label: 'When you see × and ÷ together, go', options: ['Left to right','Right to left','× first','÷ first'] }, { label: '$8 ÷ 2 × 4 =$', options: ['16','1','8','32'] }], correctAnswers: ['Left to right','16'], hint1: 'Same priority.', hint2: '4 × 4.', explanation: 'Left to right for ×/÷. 8÷2=4, 4×4=16.' }
  },
  { introContent: `\n# 📈 Addition & Subtraction\n\n**Part 4 of 7 — Addition & Subtraction**\n\nLast step: **add and subtract left to right**.\n\n$10 - 3 + 5 = 7 + 5 = 12$ (left to right)\n    `, workedContent: `\n## Worked Example\n\n$8 + 2 \\times 3 - 4 = 8 + 6 - 4 = 14 - 4 = 10$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Value |\n|---|-----------|-------|\n| 1 | 15 − 3 + 2 | 14 |\n| 2 | 4 + 5 × 2 − 3 | 11 |\n| 3 | 20 − 6 ÷ 2 + 1 | 18 |\n    `,
    mcq1: { questions: [{ question: '$4 + 5 \\times 2 - 3 = ?$', options: ['11','15','9','21'], correctAnswer: 0, explanation: '5×2=10. 4+10−3=11.' }] },
    mcq2: { questions: [{ question: '$20 - 6 \\div 2 + 1 = ?$', options: ['18','8','7.5','22'], correctAnswer: 0, explanation: '6÷2=3. 20−3+1=18.' }] },
    input: { boxes: 3, correctAnswers: ['14','11','18'], content: `\n**Full PEMDAS** 🧮\n\n1) $15 - 3 + 2 = ?$\n\n2) $4 + 5 \\times 2 - 3 = ?$\n\n3) $20 - 6 \\div 2 + 1 = ?$\n    `, hint1: 'Left to right: 12+2.', hint2: 'Multiply first: 4+10−3.', hint3: 'Divide first: 20−3+1.', explanation: '1) 14. 2) 11. 3) 18.' },
    dropdown: { dropdowns: [{ label: 'Addition and subtraction have', options: ['Equal priority','Addition first','Subtraction first','No order'] }, { label: 'In PEMDAS, A and S are done', options: ['Last (left to right)','First','Before multiplication','After parentheses'] }], correctAnswers: ['Equal priority','Last (left to right)'], hint1: 'Same level.', hint2: 'Final step.', explanation: '+ and − have equal priority, done last, left to right.' }
  },
  { introContent: `\n# 🧮 Nested Expressions\n\n**Part 5 of 7 — Nested Expressions**\n\n**Nested parentheses** (brackets inside brackets): work from innermost out.\n\n$2[3 + (4 - 1)] = 2[3 + 3] = 2[6] = 12$\n    `, workedContent: `\n## Worked Example\n\n$5 + 2[3(2+1)] = 5 + 2[3(3)] = 5 + 2[9] = 5 + 18 = 23$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Value |\n|---|-----------|-------|\n| 1 | 3(2+1)² | 27 |\n| 2 | 2[5−(3−1)] | 6 |\n| 3 | (1+2)²+4 | 13 |\n    `,
    mcq1: { questions: [{ question: '$3(2+1)^2 = ?$', options: ['27','81','12','21'], correctAnswer: 0, explanation: '(3)²=9. 3(9)=27.' }] },
    mcq2: { questions: [{ question: '$2[5 - (3-1)] = ?$', options: ['6','4','8','10'], correctAnswer: 0, explanation: 'Inner: 3−1=2. Outer: 5−2=3. 2(3)=6.' }] },
    input: { boxes: 3, correctAnswers: ['27','6','13'], content: `\n**Nested Expressions** 🧮\n\n1) $3(2 + 1)^2 = ?$\n\n2) $2[5 - (3 - 1)] = ?$\n\n3) $(1 + 2)^2 + 4 = ?$\n    `, hint1: 'Parentheses: 2+1=3. Then 3²=9. Then 3(9).', hint2: 'Inner first: 3−1=2. Then 5−2=3. Then 2(3).', hint3: '3² + 4.', explanation: '1) 27. 2) 6. 3) 13.' },
    dropdown: { dropdowns: [{ label: 'With nested parentheses, start from', options: ['Innermost','Outermost','Left to right','Right to left'] }, { label: 'Brackets [ ] and parentheses ( ) are', options: ['Both grouping symbols','Different operations','Brackets first','Parentheses only'] }], correctAnswers: ['Innermost','Both grouping symbols'], hint1: 'Inside out.', hint2: 'Both mean "do this first."', explanation: 'Innermost first. Brackets and parentheses both group.' }
  },
  { introContent: `\n# 🛠️ Problem-Solving Workshop\n\n**Part 6 of 7 — Problem-Solving Workshop**\n\nApply order of operations to multi-step problems:\n- Write the expression carefully\n- Identify which operations to do first\n- Show each step\n    `, workedContent: `\n## Worked Example\n\n**"3 squared plus the product of 2 and 5."**\n\n$3^2 + 2 \\times 5 = 9 + 10 = 19$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Problem | Expression | Value |\n|---|---------|-----------|-------|\n| 1 | Double the sum of 4 and 3 | 2(4+3) | 14 |\n| 2 | 5 squared minus 10 | 5²−10 | 15 |\n| 3 | Sum of 8 and 6 divided by 2 | (8+6)÷2 | 7 |\n    `,
    mcq1: { questions: [{ question: '"Double the sum of 4 and 3" = ?', options: ['14','11','23','10'], correctAnswer: 0, explanation: '2(4+3) = 2(7) = 14.' }] },
    mcq2: { questions: [{ question: '"Sum of 8 and 6 divided by 2" = ?', options: ['7','11','4','17'], correctAnswer: 0, explanation: '(8+6)÷2 = 14÷2 = 7.' }] },
    input: { boxes: 3, correctAnswers: ['14','15','7'], content: `\n**Translate & Compute** 🧮\n\n1) Double the sum of 4 and 3?\n\n2) 5 squared minus 10?\n\n3) Sum of 8 and 6, divided by 2?\n    `, hint1: '2(4+3).', hint2: '25 − 10.', hint3: '(8+6)÷2 = 14÷2.', explanation: '1) 14. 2) 15. 3) 7.' },
    dropdown: { dropdowns: [{ label: '"The sum of 4 and 3" requires', options: ['Parentheses to group the addition','No grouping','Multiplication first','Subtraction'] }, { label: '"5 squared" means', options: ['5² = 25','5 × 2 = 10','√5','5 + 5'] }], correctAnswers: ['Parentheses to group the addition','5² = 25'], hint1: 'Sum means add → group it.', hint2: 'Squared = power of 2.', explanation: 'Group the sum in parentheses. 5²=25.' }
  },
  { introContent: `\n# 🏆 Review & Applications\n\n**Part 7 of 7 — Review & Applications**\n\n### PEMDAS Order\n1. **P**arentheses (innermost first)\n2. **E**xponents\n3. **M**ultiplication & **D**ivision (left to right)\n4. **A**ddition & **S**ubtraction (left to right)\n    `, workedContent: `\n## Worked Example\n\n$2(3 + 1)^2 - 5 \\times 2 = 2(4)^2 - 10 = 2(16) - 10 = 32 - 10 = 22$ ✅\n    `, practiceContent: `\n## Practice\n\n| # | Expression | Value |\n|---|-----------|-------|\n| 1 | 3+4×2 | 11 |\n| 2 | (3+4)×2 | 14 |\n| 3 | 2³−1 | 7 |\n    `,
    mcq1: { questions: [{ question: '$3 + 4 \\times 2 = ?$', options: ['11','14','24','10'], correctAnswer: 0, explanation: '4×2=8. 3+8=11.' }] },
    mcq2: { questions: [{ question: '$(3 + 4) \\times 2 = ?$', options: ['14','11','24','10'], correctAnswer: 0, explanation: '(7)×2 = 14.' }] },
    input: { boxes: 3, correctAnswers: ['11','14','7'], content: `\n**Review** 🧮\n\n1) $3 + 4 \\times 2 = ?$\n\n2) $(3 + 4) \\times 2 = ?$\n\n3) $2^3 - 1 = ?$\n    `, hint1: 'Multiply first.', hint2: 'Parentheses first.', hint3: 'Exponent first: 2³=8.', explanation: '1) 11. 2) 14. 3) 7.' },
    dropdown: { dropdowns: [{ label: 'Parentheses change the answer because they', options: ['Override the default order','Are decorative','Come last','Do nothing'] }, { label: 'PEMDAS is used to', options: ['Determine the order of operations','Solve equations only','Factor polynomials','Find variables'] }], correctAnswers: ['Override the default order','Determine the order of operations'], hint1: 'Grouping overrides priority.', hint2: 'Order of operations.', explanation: 'Parentheses override order. PEMDAS determines operation order.' }
  }
]

};
