// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasReconstructionJimCrowPart1Data = {
  topicSlug: "aas-reconstruction-jim-crow",
  sections: [
    {
      id: "aasrjc1-intro",
      type: 'text' as const,
      content: "# ⚖️ Reconstruction & Jim Crow (1865–1900)\n\n**Part 1 of 7 — Foundations & Key Concepts**\n\n---\n\n### Why this unit matters\n\nAfter emancipation, the Reconstruction Amendments (13th, 14th, 15th) and Freedmen's Bureau promised citizenship, education, and political participation. The withdrawal of federal troops in 1877 enabled white-supremacist violence and a regime of legal segregation, disfranchisement, and convict-lease labor sustained by *Plessy v. Ferguson* (1896).\n\n### Core concepts\n\n| Core concept | What it refers to |\n|---|---|\n| **Reconstruction Amendments** | 13th (1865) abolition; 14th (1868) citizenship/equal protection; 15th (1870) Black male suffrage. |\n| **Freedmen's Bureau** | 1865–1872 federal agency providing schools, contracts, and legal aid. |\n| **Disfranchisement** | Poll taxes, literacy tests, grandfather clauses, white primaries strip Black voting rights. |\n\n> 🔑 **Key Concept:** AP African American History rewards arguments that combine specific evidence (named figures, dates, primary sources) with claims about causation, continuity, and change.\n"
    },
    {
      id: "aasrjc1-figures",
      type: 'text' as const,
      content: "## 📖 Key Figures of Reconstruction & Jim Crow\n\n| Figure | Dates | Why they matter |\n|---|---|---|\n| **Hiram Revels** | 1827–1901 | First Black U.S. Senator (MS, 1870); filled Jefferson Davis's former seat. |\n| **Robert Smalls** | 1839–1915 | Commandeered the *Planter* (1862); five-term U.S. congressman from SC. |\n| **Frederick Douglass** | c. 1818–1895 | Shifts focus to civil-rights enforcement; U.S. Marshal for D.C., minister to Haiti. |\n| **Ida B. Wells** | 1862–1931 | *Southern Horrors* (1892) and *A Red Record* (1895) document lynchings and convict leasing. |\n| **Booker T. Washington** | 1856–1915 | Tuskegee (1881); 1895 Atlanta Compromise advocates vocational training and accommodation. |\n\n> ⚠️ **AP Alert:** Strong responses cite specific figures by name and date — e.g., 'Hiram Revels (1827–1901)' rather than 'a famous leader.'"
    },
    {
      id: "aasrjc1-quiz1",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which statement BEST captures why Reconstruction & Jim Crow is foundational to AP African American History?",
            "options": [
              "After emancipation, the Reconstruction Amendments (13th, 14th, 15th) and Freedmen's Bureau promised citizenship, education, and political participation. The withdrawal of federal troops in 1877 enabled white-supremacist violence and a regime of legal segregation, disfranchisement, and convict-lease labor sustained by *Plessy v. Ferguson* (1896).",
              "Reconstruction & Jim Crow is primarily a literary movement with no political implications.",
              "Reconstruction & Jim Crow only matters to one decade and rarely appears on the AP exam.",
              "Reconstruction & Jim Crow is studied to memorize dates without analyzing causes."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards students who can articulate why Reconstruction & Jim Crow matters in the broader course narrative, not just describe it."
          },
          {
            "question": "Hiram Revels (1827–1901) is significant in this unit primarily because:",
            "options": [
              "First Black U.S. Senator (MS, 1870); filled Jefferson Davis's former seat.",
              "Hiram Revels opposed every form of African American institution building.",
              "Hiram Revels lived after the events of Reconstruction & Jim Crow ended.",
              "Hiram Revels is mentioned only in passing on the AP exam."
            ],
            "correctAnswer": 0,
            "explanation": "Hiram Revels is one of the central named figures the AP exam expects students to deploy when writing about Reconstruction & Jim Crow."
          }
        ]
      }
    },
    {
      id: "aasrjc1-context",
      type: 'text' as const,
      content: "## Historical Context\n\n| Event | Significance |\n|---|---|\n| **1865 Special Field Order 15** | Sherman promises freedmen '40 acres and a mule'; Andrew Johnson rescinds. |\n| **1866 Civil Rights Act / 1868 14th Amendment** | Codify birthright citizenship and equal protection. |\n| **1870 15th Amendment** | Bars race-based denial of male suffrage. |\n\n### Primary sources to know\n\n- **Wells-Barnett, *Southern Horrors* (1892)** — Statistical and journalistic indictment of lynching.\n- **Du Bois, *Souls of Black Folk* (1903)** — Coins 'double-consciousness' and the 'color line.'\n- **Washington, Atlanta Compromise speech (1895)** — Argues for economic uplift over immediate political confrontation.\n"
    },
    {
      id: "aasrjc1-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\nUse the exact historical term:\n\n1) Tenant farming arrangement that often produced perpetual debt\n\n2) 1865–66 southern laws restricting Black labor and movement\n\n3) States leased prisoners — overwhelmingly Black — to private employers\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Sharecropping",
          "Black Codes",
          "Convict leasing"
        ],
        "hint1": "Concept 1: S…",
        "hint2": "Concept 2: B…",
        "hint3": "Concept 3: C…",
        "explanation": "Sharecropping, Black Codes, and Convict leasing are core vocabulary for Reconstruction & Jim Crow."
      }
    },
    {
      id: "aasrjc1-dropdown",
      type: 'dropdown-select' as const,
      content: "**Match the Concepts** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "Reconstruction Amendments is best described as ___",
            "options": [
              "13th (1865) abolition; 14th (1868) citizenship/equal protection; 15th (1870) Black male suffrage.",
              "1865–1872 federal agency providing schools, contracts, and legal aid.",
              "Poll taxes, literacy tests, grandfather clauses, white primaries strip Black voting rights.",
              "An unrelated modern policy debate"
            ]
          },
          {
            "label": "Freedmen's Bureau is best described as ___",
            "options": [
              "1865–1872 federal agency providing schools, contracts, and legal aid.",
              "13th (1865) abolition; 14th (1868) citizenship/equal protection; 15th (1870) Black male suffrage.",
              "Poll taxes, literacy tests, grandfather clauses, white primaries strip Black voting rights.",
              "A 21st-century technology trend"
            ]
          },
          {
            "label": "Disfranchisement is best described as ___",
            "options": [
              "Poll taxes, literacy tests, grandfather clauses, white primaries strip Black voting rights.",
              "13th (1865) abolition; 14th (1868) citizenship/equal protection; 15th (1870) Black male suffrage.",
              "1865–1872 federal agency providing schools, contracts, and legal aid.",
              "An economic theory unrelated to this period"
            ]
          }
        ],
        "correctAnswers": [
          "13th (1865) abolition; 14th (1868) citizenship/equal protection; 15th (1870) Black male suffrage.",
          "1865–1872 federal agency providing schools, contracts, and legal aid.",
          "Poll taxes, literacy tests, grandfather clauses, white primaries strip Black voting rights."
        ],
        "hint1": "Definition tracks the concept name closely.",
        "hint2": "Match the language used in primary sources.",
        "hint3": "Use the historical, not the modern, definition.",
        "explanation": "All three are foundational concepts the AP exam expects you to define and apply within Reconstruction & Jim Crow."
      }
    },
    {
      id: "aasrjc1-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A historian argues that Reconstruction & Jim Crow is essential for understanding African American history. Which evidence BEST supports the claim?",
            "options": [
              "Hiram Revels (1827–1901) — First Black U.S. Senator (MS, 1870); filled Jefferson Davis's former seat.",
              "A 21st-century pop song references Reconstruction & Jim Crow without historical context.",
              "Reconstruction & Jim Crow is unrelated to broader trends in U.S. or Atlantic history.",
              "There are no primary sources for this period."
            ],
            "correctAnswer": 0,
            "explanation": "Strong AP arguments cite specific historical actors and dates, not anachronistic or vague references."
          },
          {
            "question": "Which statement most accurately describes the historical context of Reconstruction & Jim Crow?",
            "options": [
              "After emancipation, the Reconstruction Amendments (13th, 14th, 15th) and Freedmen's Bureau promised citizenship, education, and political participation. The withdrawal of federal troops in 1877 enabled white-supremacist violence and a regime of legal segregation, disfranchisement, and convict-lease labor sustained by *Plessy v. Ferguson* (1896).",
              "Reconstruction & Jim Crow occurred entirely outside any global or transregional context.",
              "Reconstruction & Jim Crow produced no documentary evidence and is impossible to study.",
              "Reconstruction & Jim Crow only appears on AP optional questions."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards contextualization — placing the topic within larger historical processes."
          }
        ]
      }
    }
  ]
}
