// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasBlackPowerBeyondPart2Data = {
  topicSlug: "aas-black-power-beyond",
  sections: [
    {
      id: "aasbpb2-intro",
      type: 'text' as const,
      content: "# ✊🏿 Black Power & Beyond\n\n**Part 2 of 7 — Key Processes & Mechanisms**\n\n---\n\n## What drove Black Power & Beyond?\n\nThis part focuses on the *mechanisms* — the systematic processes that produced the patterns historians describe.\n\n| Core concept | What it refers to |\n|---|---|\n| **Black Power** | Stokely Carmichael's June 1966 Greenwood, MS rally — slogan reframes the movement. |\n| **Community survival programs** | Black Panther Free Breakfast, free clinics, sickle-cell screening. |\n| **Black Arts Movement** | Cultural arm of Black Power — Amiri Baraka, Sonia Sanchez, Larry Neal. |\n"
    },
    {
      id: "aasbpb2-process",
      type: 'text' as const,
      content: "## Mechanisms in action\n\n| Event | Significance |\n|---|---|\n| **1965 Watts uprising** | 34 deaths; signals northern urban unrest. |\n| **1966 Black Panther Party founded** | Ten-Point Program demands housing, employment, justice. |\n| **1968 Olympic Project for Human Rights** | Smith and Carlos raise gloved fists in Mexico City. |\n| **1969 Free Breakfast Program** | BPP feeds tens of thousands of children before Federal School Breakfast Program expanded. |\n\n### Causal chains\n\nAP responses on Black Power & Beyond should make causation explicit. A strong sentence might be:\n\n> Because black power intensified, communities responded by black arts movement, which in turn produced community survival programs.\n"
    },
    {
      id: "aasbpb2-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which BEST describes a primary mechanism shaping Black Power & Beyond?",
            "options": [
              "Stokely Carmichael's June 1966 Greenwood, MS rally — slogan reframes the movement.",
              "An unrelated technological invention from a different century.",
              "Pure coincidence with no identifiable cause.",
              "A modern political slogan with no historical content."
            ],
            "correctAnswer": 0,
            "explanation": "Black Power is the central mechanism the AP exam expects students to explain."
          },
          {
            "question": "Stokely Carmichael / Kwame Ture's career illustrates which historical mechanism?",
            "options": [
              "SNCC chair; coined 'Black Power' (1966); All-African People's Revolutionary Party.",
              "Stokely Carmichael / Kwame Ture had no impact on Black Power & Beyond.",
              "An entirely modern policy debate.",
              "A purely literary aesthetic."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards specific causal claims tied to named figures."
          }
        ]
      }
    },
    {
      id: "aasbpb2-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Which figure (1925–1965) is associated with Black Power & Beyond?\n\n2) Which figure (1941–1998) shaped this mechanism?\n\n3) Which figure (1942–1989) extended it?\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Malcolm X",
          "Stokely Carmichael / Kwame Ture",
          "Huey P. Newton"
        ],
        "hint1": "Hint: 1925–1965",
        "hint2": "Hint: 1941–1998",
        "hint3": "Hint: 1942–1989",
        "explanation": "Naming specific figures is essential for high-scoring AP responses."
      }
    },
    {
      id: "aasbpb2-dropdown",
      type: 'dropdown-select' as const,
      content: "**Trace the Mechanism** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "The mechanism most strongly associated with Malcolm X is ___",
            "options": [
              "Nation of Islam minister; founded OAAU (1964); pilgrimage to Mecca shifts toward internationalism; assassinated Feb. 21, 1965.",
              "SNCC chair; coined 'Black Power' (1966); All-African People's Revolutionary Party.",
              "Co-founded Black Panther Party with Bobby Seale (Oakland, Oct. 1966).",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "The mechanism most strongly associated with Stokely Carmichael / Kwame Ture is ___",
            "options": [
              "SNCC chair; coined 'Black Power' (1966); All-African People's Revolutionary Party.",
              "Nation of Islam minister; founded OAAU (1964); pilgrimage to Mecca shifts toward internationalism; assassinated Feb. 21, 1965.",
              "Co-founded Black Panther Party with Bobby Seale (Oakland, Oct. 1966).",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "The mechanism most strongly associated with Huey P. Newton is ___",
            "options": [
              "Co-founded Black Panther Party with Bobby Seale (Oakland, Oct. 1966).",
              "Nation of Islam minister; founded OAAU (1964); pilgrimage to Mecca shifts toward internationalism; assassinated Feb. 21, 1965.",
              "SNCC chair; coined 'Black Power' (1966); All-African People's Revolutionary Party.",
              "Unrelated to this unit"
            ]
          }
        ],
        "correctAnswers": [
          "Nation of Islam minister; founded OAAU (1964); pilgrimage to Mecca shifts toward internationalism; assassinated Feb. 21, 1965.",
          "SNCC chair; coined 'Black Power' (1966); All-African People's Revolutionary Party.",
          "Co-founded Black Panther Party with Bobby Seale (Oakland, Oct. 1966)."
        ],
        "hint1": "Match the figure's actual contribution.",
        "hint2": "Use the dates as a guide.",
        "hint3": "Stay within the historical period.",
        "explanation": "Each figure is associated with a distinct mechanism within the unit."
      }
    },
    {
      id: "aasbpb2-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A student argues that Black Power & Beyond happened spontaneously. The strongest counter-argument is:",
            "options": [
              "Identifying specific actors and processes — e.g., Malcolm X (1925–1965) — that drove the change.",
              "Insisting that historians cannot know causes.",
              "Citing only events from outside this period.",
              "Memorizing dates without analyzing them."
            ],
            "correctAnswer": 0,
            "explanation": "Historical causation requires named actors, dated events, and articulated mechanisms."
          },
          {
            "question": "Which mechanism is MOST closely linked to Community survival programs?",
            "options": [
              "Black Panther Free Breakfast, free clinics, sickle-cell screening.",
              "Stokely Carmichael's June 1966 Greenwood, MS rally — slogan reframes the movement.",
              "Cultural arm of Black Power — Amiri Baraka, Sonia Sanchez, Larry Neal.",
              "A cause from a different historical era."
            ],
            "correctAnswer": 0,
            "explanation": "Community survival programs has its own historical mechanism distinct from related concepts."
          }
        ]
      }
    }
  ]
}
