// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasMovementsDebatesPart2Data = {
  topicSlug: "aas-movements-debates",
  sections: [
    {
      id: "aasmd2-intro",
      type: 'text' as const,
      content: "# 💬 Movements & Debates\n\n**Part 2 of 7 — Key Processes & Mechanisms**\n\n---\n\n## What drove Movements & Debates?\n\nThis part focuses on the *mechanisms* — the systematic processes that produced the patterns historians describe.\n\n| Core concept | What it refers to |\n|---|---|\n| **Integration vs. separatism** | Douglass vs. Delany; King vs. Malcolm X; NAACP vs. Nation of Islam. |\n| **Intersectionality** | Crenshaw (1989) — overlapping race, gender, and class generate distinct experiences of inequality. |\n| **Pan-Africanism** | Du Bois congresses (1900–1945); Garvey UNIA; Kwame Nkrumah; Black Power's African turn. |\n"
    },
    {
      id: "aasmd2-process",
      type: 'text' as const,
      content: "## Mechanisms in action\n\n| Event | Significance |\n|---|---|\n| **1895 Atlanta Compromise vs. 1903 *Souls of Black Folk*** | Public Washington–Du Bois split. |\n| **1919 Pan-African Congress (Paris)** | Du Bois petitions Versailles. |\n| **1955 Bandung Conference** | Asian–African solidarity reframes civil rights as anti-colonial. |\n| **1977 Combahee River Collective Statement** | Foundational Black feminist manifesto. |\n\n### Causal chains\n\nAP responses on Movements & Debates should make causation explicit. A strong sentence might be:\n\n> Because integration vs. separatism intensified, communities responded by pan-africanism, which in turn produced intersectionality.\n"
    },
    {
      id: "aasmd2-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which BEST describes a primary mechanism shaping Movements & Debates?",
            "options": [
              "Douglass vs. Delany; King vs. Malcolm X; NAACP vs. Nation of Islam.",
              "An unrelated technological invention from a different century.",
              "Pure coincidence with no identifiable cause.",
              "A modern political slogan with no historical content."
            ],
            "correctAnswer": 0,
            "explanation": "Integration vs. separatism is the central mechanism the AP exam expects students to explain."
          },
          {
            "question": "Booker T. Washington vs. W. E. B. Du Bois's career illustrates which historical mechanism?",
            "options": [
              "Vocational uplift vs. liberal arts and political agitation.",
              "Booker T. Washington vs. W. E. B. Du Bois had no impact on Movements & Debates.",
              "An entirely modern policy debate.",
              "A purely literary aesthetic."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards specific causal claims tied to named figures."
          }
        ]
      }
    },
    {
      id: "aasmd2-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Which figure (19th c.) is associated with Movements & Debates?\n\n2) Which figure (1895–1915) shaped this mechanism?\n\n3) Which figure (founded 1974) extended it?\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Frederick Douglass vs. Martin Delany",
          "Booker T. Washington vs. W. E. B. Du Bois",
          "Combahee River Collective"
        ],
        "hint1": "Hint: 19th c.",
        "hint2": "Hint: 1895–1915",
        "hint3": "Hint: founded 1974",
        "explanation": "Naming specific figures is essential for high-scoring AP responses."
      }
    },
    {
      id: "aasmd2-dropdown",
      type: 'dropdown-select' as const,
      content: "**Trace the Mechanism** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "The mechanism most strongly associated with Frederick Douglass vs. Martin Delany is ___",
            "options": [
              "Moral suasion / integration vs. emigration / Black nationalism.",
              "Vocational uplift vs. liberal arts and political agitation.",
              "Black lesbian feminist statement (1977) defines identity politics.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "The mechanism most strongly associated with Booker T. Washington vs. W. E. B. Du Bois is ___",
            "options": [
              "Vocational uplift vs. liberal arts and political agitation.",
              "Moral suasion / integration vs. emigration / Black nationalism.",
              "Black lesbian feminist statement (1977) defines identity politics.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "The mechanism most strongly associated with Combahee River Collective is ___",
            "options": [
              "Black lesbian feminist statement (1977) defines identity politics.",
              "Moral suasion / integration vs. emigration / Black nationalism.",
              "Vocational uplift vs. liberal arts and political agitation.",
              "Unrelated to this unit"
            ]
          }
        ],
        "correctAnswers": [
          "Moral suasion / integration vs. emigration / Black nationalism.",
          "Vocational uplift vs. liberal arts and political agitation.",
          "Black lesbian feminist statement (1977) defines identity politics."
        ],
        "hint1": "Match the figure's actual contribution.",
        "hint2": "Use the dates as a guide.",
        "hint3": "Stay within the historical period.",
        "explanation": "Each figure is associated with a distinct mechanism within the unit."
      }
    },
    {
      id: "aasmd2-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A student argues that Movements & Debates happened spontaneously. The strongest counter-argument is:",
            "options": [
              "Identifying specific actors and processes — e.g., Frederick Douglass vs. Martin Delany (19th c.) — that drove the change.",
              "Insisting that historians cannot know causes.",
              "Citing only events from outside this period.",
              "Memorizing dates without analyzing them."
            ],
            "correctAnswer": 0,
            "explanation": "Historical causation requires named actors, dated events, and articulated mechanisms."
          },
          {
            "question": "Which mechanism is MOST closely linked to Intersectionality?",
            "options": [
              "Crenshaw (1989) — overlapping race, gender, and class generate distinct experiences of inequality.",
              "Douglass vs. Delany; King vs. Malcolm X; NAACP vs. Nation of Islam.",
              "Du Bois congresses (1900–1945); Garvey UNIA; Kwame Nkrumah; Black Power's African turn.",
              "A cause from a different historical era."
            ],
            "correctAnswer": 0,
            "explanation": "Intersectionality has its own historical mechanism distinct from related concepts."
          }
        ]
      }
    }
  ]
}
