// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasContemporaryIssuesPart2Data = {
  topicSlug: "aas-contemporary-issues",
  sections: [
    {
      id: "aasci2-intro",
      type: 'text' as const,
      content: "# ⚡ Contemporary Issues & Debates\n\n**Part 2 of 7 — Key Processes & Mechanisms**\n\n---\n\n## What drove Contemporary Issues?\n\nThis part focuses on the *mechanisms* — the systematic processes that produced the patterns historians describe.\n\n| Core concept | What it refers to |\n|---|---|\n| **Mass incarceration** | U.S. prison population rose from ~300,000 (1972) to ~2.3 million (2008); Black men incarcerated at 5–6× white rate. |\n| **Color-blind racism** | Post-Civil Rights ideology that ignores structural inequality (Eduardo Bonilla-Silva). |\n| **Movement for Black Lives** | Decentralized network founded 2013; broadens civil-rights agenda to police violence, abolition, intersectionality. |\n"
    },
    {
      id: "aasci2-process",
      type: 'text' as const,
      content: "## Mechanisms in action\n\n| Event | Significance |\n|---|---|\n| **1986 Anti-Drug Abuse Act** | 100:1 crack/powder cocaine sentencing disparity. |\n| **1992 LA Uprising** | After Rodney King verdict; ~63 deaths. |\n| **1994 Crime Bill** | Three-strikes mandatory minimums; truth-in-sentencing grants. |\n| **2008 Obama elected** | First Black U.S. president. |\n\n### Causal chains\n\nAP responses on Contemporary Issues should make causation explicit. A strong sentence might be:\n\n> Because mass incarceration intensified, communities responded by movement for black lives, which in turn produced color-blind racism.\n"
    },
    {
      id: "aasci2-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which BEST describes a primary mechanism shaping Contemporary Issues?",
            "options": [
              "U.S. prison population rose from ~300,000 (1972) to ~2.3 million (2008); Black men incarcerated at 5–6× white rate.",
              "An unrelated technological invention from a different century.",
              "Pure coincidence with no identifiable cause.",
              "A modern political slogan with no historical content."
            ],
            "correctAnswer": 0,
            "explanation": "Mass incarceration is the central mechanism the AP exam expects students to explain."
          },
          {
            "question": "Toni Morrison's career illustrates which historical mechanism?",
            "options": [
              "Nobel Prize 1993; *Beloved* (1987) reframes American memory of slavery.",
              "Toni Morrison had no impact on Contemporary Issues.",
              "An entirely modern policy debate.",
              "A purely literary aesthetic."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards specific causal claims tied to named figures."
          }
        ]
      }
    },
    {
      id: "aasci2-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Which figure (b. 1941) is associated with Contemporary Issues?\n\n2) Which figure (1931–2019) shaped this mechanism?\n\n3) Which figure (b. 1953) extended it?\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Jesse Jackson",
          "Toni Morrison",
          "Cornel West"
        ],
        "hint1": "Hint: b. 1941",
        "hint2": "Hint: 1931–2019",
        "hint3": "Hint: b. 1953",
        "explanation": "Naming specific figures is essential for high-scoring AP responses."
      }
    },
    {
      id: "aasci2-dropdown",
      type: 'dropdown-select' as const,
      content: "**Trace the Mechanism** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "The mechanism most strongly associated with Jesse Jackson is ___",
            "options": [
              "1984 and 1988 Democratic presidential campaigns; Rainbow Coalition.",
              "Nobel Prize 1993; *Beloved* (1987) reframes American memory of slavery.",
              "*Race Matters* (1993); Black prophetic Christian intellectual.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "The mechanism most strongly associated with Toni Morrison is ___",
            "options": [
              "Nobel Prize 1993; *Beloved* (1987) reframes American memory of slavery.",
              "1984 and 1988 Democratic presidential campaigns; Rainbow Coalition.",
              "*Race Matters* (1993); Black prophetic Christian intellectual.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "The mechanism most strongly associated with Cornel West is ___",
            "options": [
              "*Race Matters* (1993); Black prophetic Christian intellectual.",
              "1984 and 1988 Democratic presidential campaigns; Rainbow Coalition.",
              "Nobel Prize 1993; *Beloved* (1987) reframes American memory of slavery.",
              "Unrelated to this unit"
            ]
          }
        ],
        "correctAnswers": [
          "1984 and 1988 Democratic presidential campaigns; Rainbow Coalition.",
          "Nobel Prize 1993; *Beloved* (1987) reframes American memory of slavery.",
          "*Race Matters* (1993); Black prophetic Christian intellectual."
        ],
        "hint1": "Match the figure's actual contribution.",
        "hint2": "Use the dates as a guide.",
        "hint3": "Stay within the historical period.",
        "explanation": "Each figure is associated with a distinct mechanism within the unit."
      }
    },
    {
      id: "aasci2-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A student argues that Contemporary Issues happened spontaneously. The strongest counter-argument is:",
            "options": [
              "Identifying specific actors and processes — e.g., Jesse Jackson (b. 1941) — that drove the change.",
              "Insisting that historians cannot know causes.",
              "Citing only events from outside this period.",
              "Memorizing dates without analyzing them."
            ],
            "correctAnswer": 0,
            "explanation": "Historical causation requires named actors, dated events, and articulated mechanisms."
          },
          {
            "question": "Which mechanism is MOST closely linked to Color-blind racism?",
            "options": [
              "Post-Civil Rights ideology that ignores structural inequality (Eduardo Bonilla-Silva).",
              "U.S. prison population rose from ~300,000 (1972) to ~2.3 million (2008); Black men incarcerated at 5–6× white rate.",
              "Decentralized network founded 2013; broadens civil-rights agenda to police violence, abolition, intersectionality.",
              "A cause from a different historical era."
            ],
            "correctAnswer": 0,
            "explanation": "Color-blind racism has its own historical mechanism distinct from related concepts."
          }
        ]
      }
    }
  ]
}
