// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasCivilRightsMovementPart5Data = {
  topicSlug: "aas-civil-rights-movement",
  sections: [
    {
      id: "aascrm5-intro",
      type: 'text' as const,
      content: "# 🗽 The Civil Rights Movement\n\n**Part 5 of 7 — Continuity & Change Over Time**\n\n---\n\n## Tracing Civil Rights Movement through 1954–1968\n\nAP CCOT (Continuity and Change Over Time) prompts ask: *what changed, what stayed the same, and what drove the change?*\n\n| Period | What changed | What persisted |\n|---|---|---|\n| Early period | New institutions emerge | African cultural retentions persist |\n| Middle period | Mechanisms of legal strategy expand | Federal enforcement continues |\n| Late period | Outcomes shift due to external pressure | Structural features endure |\n"
    },
    {
      id: "aascrm5-change",
      type: 'text' as const,
      content: "## Specific moments of change\n\n| Event | Significance |\n|---|---|\n| **Aug. 1963 March on Washington** | ~250,000 attend; King's 'I Have a Dream' speech. |\n| **1964 Civil Rights Act** | Bans discrimination in public accommodations and employment; Title VII. |\n| **1965 Selma–Montgomery marches → Voting Rights Act** | VRA Section 5 preclearance protects southern Black voting until *Shelby County v. Holder* (2013). |\n\n### Strong CCOT sentence\n\n> Although legal strategy continued throughout 1954–1968, the events of 1965 Selma–Montgomery marches → Voting Rights Act marked a decisive shift in how Black communities engaged with it."
    },
    {
      id: "aascrm5-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which best describes continuity within Civil Rights Movement?",
            "options": [
              "Aspects such as federal enforcement persisted even as other features changed.",
              "Nothing about this topic ever changed.",
              "Continuity is irrelevant to AP scoring.",
              "Only the most recent decade matters."
            ],
            "correctAnswer": 0,
            "explanation": "Continuity = elements that persist across change — a key AP analytical category."
          },
          {
            "question": "Which event marks a decisive change within Civil Rights Movement?",
            "options": [
              "1965 Selma–Montgomery marches → Voting Rights Act — VRA Section 5 preclearance protects southern Black voting until *Shelby County v. Holder* (2013).",
              "An anecdote with no historical impact.",
              "A 21st-century news headline unrelated to the period.",
              "A purely literary aesthetic with no political effect."
            ],
            "correctAnswer": 0,
            "explanation": "Specific dated events anchor change-over-time arguments."
          }
        ]
      }
    },
    {
      id: "aascrm5-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) An aspect of Civil Rights Movement that persisted: ___\n\n2) An event that marked decisive change: ___\n\n3) The AP analytical category for tracking these together: ___\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Federal enforcement",
          "1965 Selma–Montgomery marches → Voting Rights Act",
          "continuity and change"
        ],
        "hint1": "Hint: 1957 and 1964 Civil Rights Acts; 1965 Voting Right…",
        "hint2": "Hint: VRA Section 5 preclearance protects southern Black…",
        "hint3": "Hint: AP CCOT",
        "explanation": "AP CCOT prompts demand both continuity and change with specific evidence."
      }
    },
    {
      id: "aascrm5-dropdown",
      type: 'dropdown-select' as const,
      content: "**Continuity vs Change** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "Continuity in this unit is best illustrated by ___",
            "options": [
              "Federal enforcement",
              "1965 Selma–Montgomery marches → Voting Rights Act",
              "An unrelated modern slogan",
              "A topic from a different course"
            ]
          },
          {
            "label": "Change in this unit is best illustrated by ___",
            "options": [
              "1965 Selma–Montgomery marches → Voting Rights Act",
              "Federal enforcement",
              "An anecdote with no date",
              "An unrelated personal opinion"
            ]
          },
          {
            "label": "An AP CCOT response should ___",
            "options": [
              "Identify both continuities and changes with specific evidence",
              "Pick only one without analysis",
              "Avoid using dates",
              "Replace evidence with opinion"
            ]
          }
        ],
        "correctAnswers": [
          "Federal enforcement",
          "1965 Selma–Montgomery marches → Voting Rights Act",
          "Identify both continuities and changes with specific evidence"
        ],
        "hint1": "Continuity = persistence.",
        "hint2": "Change = decisive shift, named event.",
        "hint3": "CCOT requires both halves.",
        "explanation": "AP CCOT prompts always require both continuity and change with explicit evidence."
      }
    },
    {
      id: "aascrm5-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which CCOT thesis is strongest?",
            "options": [
              "Although federal enforcement continued, 1965 Selma–Montgomery marches → Voting Rights Act marked a decisive change in Civil Rights Movement.",
              "Nothing changed and nothing stayed the same.",
              "Change is impossible to identify in history.",
              "AP rubrics do not reward CCOT analysis."
            ],
            "correctAnswer": 0,
            "explanation": "Strong CCOT theses pair specific continuities with specific changes."
          },
          {
            "question": "Which evidence move is most valuable in a CCOT response?",
            "options": [
              "Naming a specific dated event AND a continuity within the same paragraph.",
              "Listing dates without analysis.",
              "Replacing evidence with a moral judgment.",
              "Citing only post-2010 news stories."
            ],
            "correctAnswer": 0,
            "explanation": "AP CCOT scoring rewards paired specificity."
          }
        ]
      }
    }
  ]
}
