// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasResistanceAbolitionPart3Data = {
  topicSlug: "aas-resistance-abolition",
  sections: [
    {
      id: "aasra3-intro",
      type: 'text' as const,
      content: "# ✊ Resistance & Abolition\n\n**Part 3 of 7 — Patterns, Regions & Case Studies**\n\n---\n\n## Specific cases — not abstractions\n\n| Event | Significance |\n|---|---|\n| **1739 Stono Rebellion (SC)** | ~20 white deaths; led to the Negro Act of 1740 restricting movement and literacy. |\n| **1791–1804 Haitian Revolution** | Defeats French, Spanish, and British forces; abolishes slavery and founds Haiti. |\n| **1816 AME Church founded** | Richard Allen leads first independent Black denomination in the U.S. |\n| **1831 Nat Turner Rebellion** | Triggers gag rules and harsher slave codes across the South. |\n| **1850 Fugitive Slave Act** | Forces northern compliance; radicalizes northern opinion. |\n| **1859 John Brown's raid on Harpers Ferry** | Brown plans a guerrilla war against slavery; executed but valorized by abolitionists. |\n| **1863 Emancipation Proclamation** | Frees enslaved people in Confederate-held areas; permits Black enlistment. |\n"
    },
    {
      id: "aasra3-cases",
      type: 'text' as const,
      content: "## Comparing cases\n\nAP comparison prompts ask you to identify a specific similarity AND difference between cases. For Resistance & Abolition, useful comparisons include:\n\n- 1739 Stono Rebellion (SC) vs. 1791–1804 Haitian Revolution\n- 1791–1804 Haitian Revolution vs. 1816 AME Church founded\n- 1816 AME Church founded vs. 1863 Emancipation Proclamation\n\n### Strong comparison sentence\n\n> Both 1739 Stono Rebellion (SC) and 1791–1804 Haitian Revolution involved everyday resistance, but they differed in the specific actors and consequences involved.\n"
    },
    {
      id: "aasra3-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which case BEST illustrates a pattern central to Resistance & Abolition?",
            "options": [
              "1739 Stono Rebellion (SC) — ~20 white deaths; led to the Negro Act of 1740 restricting movement and literacy.",
              "An unrelated event from another century.",
              "A purely fictional event.",
              "An anecdote with no documentary support."
            ],
            "correctAnswer": 0,
            "explanation": "Use historically attested events to illustrate patterns."
          },
          {
            "question": "A comparison of 1739 Stono Rebellion (SC) and 1791–1804 Haitian Revolution is most useful because:",
            "options": [
              "Both cases let students see common patterns and unique local differences in concrete historical detail.",
              "Both events occurred in identical contexts and produced identical outcomes.",
              "Comparison is irrelevant to AP scoring.",
              "Neither event left primary sources for historians."
            ],
            "correctAnswer": 0,
            "explanation": "AP comparison rewards specific similarities and differences with named cases."
          }
        ]
      }
    },
    {
      id: "aasra3-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Name the event: ~20 white deaths; led to the Negro Act of 1740 restricting movement and literacy…\n\n2) Name the event: Defeats French, Spanish, and British forces; abolishes slavery and founds Haiti.…\n\n3) Name the event: Richard Allen leads first independent Black denomination in the U.S.…\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "1739 Stono Rebellion (SC)",
          "1791–1804 Haitian Revolution",
          "1816 AME Church founded"
        ],
        "hint1": "Hint: 1739",
        "hint2": "Hint: 1791–1804",
        "hint3": "Hint: 1816",
        "explanation": "Naming specific events anchors AP arguments in evidence."
      }
    },
    {
      id: "aasra3-dropdown",
      type: 'dropdown-select' as const,
      content: "**Match Cases to Patterns** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "The case most central to Everyday resistance is ___",
            "options": [
              "1739 Stono Rebellion (SC)",
              "1791–1804 Haitian Revolution",
              "1816 AME Church founded",
              "An unrelated 21st-century news story"
            ]
          },
          {
            "label": "The case most central to Armed revolt is ___",
            "options": [
              "1791–1804 Haitian Revolution",
              "1739 Stono Rebellion (SC)",
              "1816 AME Church founded",
              "An unrelated 21st-century news story"
            ]
          },
          {
            "label": "The case most central to Moral suasion vs political action is ___",
            "options": [
              "1816 AME Church founded",
              "1739 Stono Rebellion (SC)",
              "1791–1804 Haitian Revolution",
              "An unrelated 21st-century news story"
            ]
          }
        ],
        "correctAnswers": [
          "1739 Stono Rebellion (SC)",
          "1791–1804 Haitian Revolution",
          "1816 AME Church founded"
        ],
        "hint1": "Use chronology to disambiguate.",
        "hint2": "Match the event to the concept it best illustrates.",
        "hint3": "Stay inside the unit's date range.",
        "explanation": "Each event is paired with the concept it most directly illustrates."
      }
    },
    {
      id: "aasra3-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Using one specific case from Resistance & Abolition, which sentence is the BEST AP comparison move?",
            "options": [
              "Both 1739 Stono Rebellion (SC) and 1791–1804 Haitian Revolution reveal everyday resistance, but they differ in actors and outcomes.",
              "Both events were fictional and produced no consequences.",
              "These events are too old to compare meaningfully.",
              "Comparison is unimportant in AP rubrics."
            ],
            "correctAnswer": 0,
            "explanation": "AP comparison combines a specific shared pattern with a specific difference."
          },
          {
            "question": "Toussaint L'Ouverture's role in Resistance & Abolition is best illustrated by which event?",
            "options": [
              "1739 Stono Rebellion (SC) — ~20 white deaths; led to the Negro Act of 1740 restricting movement and literacy.",
              "An unrelated event in a different century.",
              "A purely literary publication unconnected to politics.",
              "An event before the figure was born."
            ],
            "correctAnswer": 0,
            "explanation": "Tie figures to dated events for high-scoring AP arguments."
          }
        ]
      }
    }
  ]
}
