// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasAfricanKingdomsPart4Data = {
  topicSlug: "aas-african-kingdoms",
  sections: [
    {
      id: "aasak4-intro",
      type: 'text' as const,
      content: "# 👑 African Kingdoms & Civilizations\n\n**Part 4 of 7 — Connections Across the Diaspora**\n\n---\n\n## How African Kingdoms connects to other units\n\nAfrican Kingdoms does not stand alone. Strong AP responses connect it to **Origins of the African Diaspora**, because later forced migrations dispersed people from these very societies.\n\n### Connection table\n\n| Linked unit | Type of connection | Example |\n|---|---|---|\n| Origins of the African Diaspora | Causal / continuity | Later forced migrations dispersed people from these very societies. |\n| Atlantic / global context | Comparison | Parallel processes elsewhere in the African diaspora. |\n| U.S. political history | Synthesis | Federal law (e.g., constitutional amendments) shapes outcomes. |\n"
    },
    {
      id: "aasak4-links",
      type: 'text' as const,
      content: "## Specific cross-unit connections\n\n| Event | Significance |\n|---|---|\n| **c. 300–1076 Ghana Empire** | Controlled the gold–salt trade; sacked by the Almoravids in 1076. |\n| **1235 Battle of Kirina** | Sundiata defeats Sumanguru of Sosso; foundation of Mali. |\n| **1324 Mansa Musa's hajj** | Caravan of ~60,000 attendants and ~12 tons of gold; placed Mali on European maps. |\n\nEach event above interacts with **Origins of the African Diaspora** — either as cause, consequence, or parallel."
    },
    {
      id: "aasak4-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "How does African Kingdoms BEST connect to Origins of the African Diaspora?",
            "options": [
              "Later forced migrations dispersed people from these very societies.",
              "African Kingdoms and Origins of the African Diaspora are completely unrelated topics.",
              "Connections between units are not tested on the AP exam.",
              "AP rubrics reward isolated facts over connections."
            ],
            "correctAnswer": 0,
            "explanation": "AP synthesis prompts ask students to articulate how units interact."
          },
          {
            "question": "A 'feedback loop' across units means:",
            "options": [
              "Outcomes of one process reinforce or modify the conditions that produced it.",
              "Two unrelated facts placed next to each other.",
              "A modern policy with no historical relevance.",
              "Memorizing additional vocabulary words."
            ],
            "correctAnswer": 0,
            "explanation": "Feedback loops are a recurring AP analytical move."
          }
        ]
      }
    },
    {
      id: "aasak4-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Which figure connects African Kingdoms most directly to Origins of the African Diaspora?\n\n2) What is the analytical term for outcomes reinforcing their own causes?\n\n3) What is the AP term for combining evidence from multiple units?\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Sundiata Keita",
          "feedback loop",
          "synthesis"
        ],
        "hint1": "Hint: r. c. 1235–1255",
        "hint2": "Hint: a 'loop' of cause and effect",
        "hint3": "Hint: 'synth___'",
        "explanation": "Naming a connecting figure, identifying feedback, and synthesizing units are all explicit AP scoring moves."
      }
    },
    {
      id: "aasak4-dropdown",
      type: 'dropdown-select' as const,
      content: "**Map the Connections** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "African Kingdoms most directly causes ___",
            "options": [
              "Origins of the African Diaspora",
              "An unrelated 21st-century event",
              "A pre-modern European war",
              "A purely cultural festival"
            ]
          },
          {
            "label": "A 'feedback loop' is ___",
            "options": [
              "Outcomes that reinforce their own causes",
              "A failed argument",
              "An anachronism",
              "A primary source"
            ]
          },
          {
            "label": "AP 'synthesis' refers to ___",
            "options": [
              "Combining evidence across units to support a claim",
              "Memorizing dates only",
              "Avoiding all comparison",
              "Citing one example without analysis"
            ]
          }
        ],
        "correctAnswers": [
          "Origins of the African Diaspora",
          "Outcomes that reinforce their own causes",
          "Combining evidence across units to support a claim"
        ],
        "hint1": "Map cause to consequence.",
        "hint2": "'Loop' implies feedback.",
        "hint3": "Synthesis = bringing units together.",
        "explanation": "Connecting units is a high-leverage AP skill rewarded across MCQ, SAQ, and LEQ."
      }
    },
    {
      id: "aasak4-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A student writes: 'African Kingdoms had no effect on Origins of the African Diaspora.' The best AP correction is:",
            "options": [
              "Show specific connections — later forced migrations dispersed people from these very societies — to demonstrate causal interaction.",
              "Insist there are no connections in U.S. history.",
              "Cite only events outside the unit.",
              "Replace the claim with a personal opinion."
            ],
            "correctAnswer": 0,
            "explanation": "AP synthesis demands explicit, specific connections backed by evidence."
          },
          {
            "question": "The strongest AP synthesis move uses:",
            "options": [
              "Specific evidence from at least two units to support a single, defensible claim.",
              "One vague generalization across centuries.",
              "Multiple unrelated personal opinions.",
              "A list of names without explanation."
            ],
            "correctAnswer": 0,
            "explanation": "AP rubrics consistently reward specificity + cross-unit synthesis."
          }
        ]
      }
    }
  ]
}
