// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasTransatlanticSlaveTradePart1Data = {
  topicSlug: "aas-transatlantic-slave-trade",
  sections: [
    {
      id: "aasts1-intro",
      type: 'text' as const,
      content: "# ⛓️ The Transatlantic Slave Trade (c. 1500–1888)\n\n**Part 1 of 7 — Foundations & Key Concepts**\n\n---\n\n### Why this unit matters\n\nBetween 1501 and 1866, an estimated 12.5 million Africans were forcibly embarked on European ships across the Atlantic. About 10.7 million survived the Middle Passage; only ~388,000 (~3.6%) disembarked in mainland North America. The trade integrated four continents into a coercive economic system.\n\n### Core concepts\n\n| Core concept | What it refers to |\n|---|---|\n| **Triangular trade** | European manufactures → African captives → American plantation goods → Europe. |\n| **Middle Passage** | The Atlantic crossing; mortality averaged ~15%, sometimes much higher. |\n| **Asiento** | Spanish license granting European powers the monopoly to supply enslaved Africans to Spanish colonies. |\n\n> 🔑 **Key Concept:** AP African American History rewards arguments that combine specific evidence (named figures, dates, primary sources) with claims about causation, continuity, and change.\n"
    },
    {
      id: "aasts1-figures",
      type: 'text' as const,
      content: "## 📖 Key Figures of Transatlantic Slave Trade\n\n| Figure | Dates | Why they matter |\n|---|---|---|\n| **John Hawkins** | 1532–1595 | First English slaver; raids West Africa 1562 with backing of Elizabeth I. |\n| **Royal African Company** | chartered 1672 | English monopoly under James, Duke of York; branded the initials 'DY' on captives. |\n| **Olaudah Equiano** | captured c. 1756 | Describes Bight of Biafra capture, holding pens at Bonny, and the Middle Passage. |\n| **Captain John Newton** | 1725–1807 | Slave-ship captain turned abolitionist; wrote 'Amazing Grace' (1772) and *Thoughts upon the Slave Trade* (1788). |\n| **Thomas Clarkson** | 1760–1846 | British abolitionist whose evidence on conditions aboard ships catalyzed the 1807 Abolition Act. |\n\n> ⚠️ **AP Alert:** Strong responses cite specific figures by name and date — e.g., 'John Hawkins (1532–1595)' rather than 'a famous leader.'"
    },
    {
      id: "aasts1-quiz1",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which statement BEST captures why Transatlantic Slave Trade is foundational to AP African American History?",
            "options": [
              "Between 1501 and 1866, an estimated 12.5 million Africans were forcibly embarked on European ships across the Atlantic. About 10.7 million survived the Middle Passage; only ~388,000 (~3.6%) disembarked in mainland North America. The trade integrated four continents into a coercive economic system.",
              "Transatlantic Slave Trade is primarily a literary movement with no political implications.",
              "Transatlantic Slave Trade only matters to one decade and rarely appears on the AP exam.",
              "Transatlantic Slave Trade is studied to memorize dates without analyzing causes."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards students who can articulate why Transatlantic Slave Trade matters in the broader course narrative, not just describe it."
          },
          {
            "question": "John Hawkins (1532–1595) is significant in this unit primarily because:",
            "options": [
              "First English slaver; raids West Africa 1562 with backing of Elizabeth I.",
              "John Hawkins opposed every form of African American institution building.",
              "John Hawkins lived after the events of Transatlantic Slave Trade ended.",
              "John Hawkins is mentioned only in passing on the AP exam."
            ],
            "correctAnswer": 0,
            "explanation": "John Hawkins is one of the central named figures the AP exam expects students to deploy when writing about Transatlantic Slave Trade."
          }
        ]
      }
    },
    {
      id: "aasts1-context",
      type: 'text' as const,
      content: "## Historical Context\n\n| Event | Significance |\n|---|---|\n| **1444 first major Portuguese auction at Lagos** | Codifies European commercial trafficking of Africans. |\n| **1518 Spanish asiento authorizes direct African shipments to the Americas** | Bypasses Iberian re-export. |\n| **1619 *White Lion* arrives at Point Comfort, Virginia** | First documented enslaved Africans in English North America. |\n\n### Primary sources to know\n\n- **Equiano, *Narrative* ch. 2 (1789)** — Most-cited Middle Passage testimony in 18th-century abolition debates.\n- **Brookes slave-ship diagram (1788)** — Showed 482 Africans packed below decks; mass-printed by Clarkson.\n- **Trans-Atlantic Slave Trade Database (Voyages.org)** — Modern database of ~36,000 documented voyages used by historians.\n"
    },
    {
      id: "aasts1-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\nUse the exact historical term:\n\n1) Coastal holding pen where captives waited for slave ships\n\n2) European agent stationed at African coastal forts (e.g., Elmina, Cape Coast)\n\n3) Loading method maximizing captives per voyage at the cost of higher mortality\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Barracoon",
          "Factor",
          "Tight pack"
        ],
        "hint1": "Concept 1: B…",
        "hint2": "Concept 2: F…",
        "hint3": "Concept 3: T…",
        "explanation": "Barracoon, Factor, and Tight pack are core vocabulary for Transatlantic Slave Trade."
      }
    },
    {
      id: "aasts1-dropdown",
      type: 'dropdown-select' as const,
      content: "**Match the Concepts** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "Triangular trade is best described as ___",
            "options": [
              "European manufactures → African captives → American plantation goods → Europe.",
              "The Atlantic crossing; mortality averaged ~15%, sometimes much higher.",
              "Spanish license granting European powers the monopoly to supply enslaved Africans to Spanish colonies.",
              "An unrelated modern policy debate"
            ]
          },
          {
            "label": "Middle Passage is best described as ___",
            "options": [
              "The Atlantic crossing; mortality averaged ~15%, sometimes much higher.",
              "European manufactures → African captives → American plantation goods → Europe.",
              "Spanish license granting European powers the monopoly to supply enslaved Africans to Spanish colonies.",
              "A 21st-century technology trend"
            ]
          },
          {
            "label": "Asiento is best described as ___",
            "options": [
              "Spanish license granting European powers the monopoly to supply enslaved Africans to Spanish colonies.",
              "European manufactures → African captives → American plantation goods → Europe.",
              "The Atlantic crossing; mortality averaged ~15%, sometimes much higher.",
              "An economic theory unrelated to this period"
            ]
          }
        ],
        "correctAnswers": [
          "European manufactures → African captives → American plantation goods → Europe.",
          "The Atlantic crossing; mortality averaged ~15%, sometimes much higher.",
          "Spanish license granting European powers the monopoly to supply enslaved Africans to Spanish colonies."
        ],
        "hint1": "Definition tracks the concept name closely.",
        "hint2": "Match the language used in primary sources.",
        "hint3": "Use the historical, not the modern, definition.",
        "explanation": "All three are foundational concepts the AP exam expects you to define and apply within Transatlantic Slave Trade."
      }
    },
    {
      id: "aasts1-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A historian argues that Transatlantic Slave Trade is essential for understanding African American history. Which evidence BEST supports the claim?",
            "options": [
              "John Hawkins (1532–1595) — First English slaver; raids West Africa 1562 with backing of Elizabeth I.",
              "A 21st-century pop song references Transatlantic Slave Trade without historical context.",
              "Transatlantic Slave Trade is unrelated to broader trends in U.S. or Atlantic history.",
              "There are no primary sources for this period."
            ],
            "correctAnswer": 0,
            "explanation": "Strong AP arguments cite specific historical actors and dates, not anachronistic or vague references."
          },
          {
            "question": "Which statement most accurately describes the historical context of Transatlantic Slave Trade?",
            "options": [
              "Between 1501 and 1866, an estimated 12.5 million Africans were forcibly embarked on European ships across the Atlantic. About 10.7 million survived the Middle Passage; only ~388,000 (~3.6%) disembarked in mainland North America. The trade integrated four continents into a coercive economic system.",
              "Transatlantic Slave Trade occurred entirely outside any global or transregional context.",
              "Transatlantic Slave Trade produced no documentary evidence and is impossible to study.",
              "Transatlantic Slave Trade only appears on AP optional questions."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards contextualization — placing the topic within larger historical processes."
          }
        ]
      }
    }
  ]
}
