// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasOriginsDiasporaPart6Data = {
  topicSlug: "aas-origins-diaspora",
  sections: [
    {
      id: "aasod6-intro",
      type: 'text' as const,
      content: "# 🌍 Origins of the African Diaspora\n\n**Part 6 of 7 — Source & Evidence Workshop**\n\n---\n\n## Working with primary sources for Origins of the Diaspora\n\nAP DBQ-style work expects students to identify a source's *purpose, audience, point of view, and historical situation* — and to use that analysis to support a claim.\n\n### Primary sources for this unit\n\n- **Equiano, *The Interesting Narrative* (1789)** — Eyewitness account of Igbo society, capture, and Middle Passage.\n- **Wheatley, *Poems on Various Subjects* (1773)** — Demonstrates literacy and classical education to challenge proslavery claims.\n- **Cugoano, *Thoughts and Sentiments* (1787)** — Direct demand for total abolition by an enslaved survivor.\n"
    },
    {
      id: "aasod6-workshop",
      type: 'text' as const,
      content: "## Source-analysis workshop\n\nFor each source, ask:\n1. **Who** is the author? What is their position relative to events?\n2. **When** was it produced? Before, during, or after the events described?\n3. **For whom** was it written? Audience shapes argument.\n4. **What** does it claim? What does it leave out?\n\n### Worked example\n\n> *Equiano, *The Interesting Narrative* (1789)* — Eyewitness account of Igbo society, capture, and Middle Passage. A strong AP citation reads: 'According to Equiano, *The Interesting Narrative* (1789), …' followed by an inference about authorial purpose."
    },
    {
      id: "aasod6-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "What makes Equiano, *The Interesting Narrative* (1789) a strong source for studying Origins of the Diaspora?",
            "options": [
              "Eyewitness account of Igbo society, capture, and Middle Passage.",
              "It was published in 2024 with no link to the period.",
              "It is fictional and includes no historical content.",
              "It is unsigned and undated."
            ],
            "correctAnswer": 0,
            "explanation": "Provenance, date, and authorial position determine source value."
          },
          {
            "question": "When using a primary source on the AP exam, you should:",
            "options": [
              "Identify author/date/audience and tie the source to a specific claim.",
              "Quote the source verbatim without analysis.",
              "Ignore the author's position.",
              "Treat the source as neutral and unbiased."
            ],
            "correctAnswer": 0,
            "explanation": "AP source-use rewards explicit attribution and analytical framing."
          }
        ]
      }
    },
    {
      id: "aasod6-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Name the source: Eyewitness account of Igbo society, capture, and Middle Pass…\n\n2) Name the source: Demonstrates literacy and classical education to challenge p…\n\n3) Name the source: Direct demand for total abolition by an enslaved survivor.…\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Equiano, The Interesting Narrative (1789)",
          "Wheatley, Poems on Various Subjects (1773)",
          "Cugoano, Thoughts and Sentiments (1787)"
        ],
        "hint1": "Hint: Equiano, *The Interesting Narrative* (1789)",
        "hint2": "Hint: Wheatley, *Poems on Various Subjects* (1773)",
        "hint3": "Hint: Cugoano, *Thoughts and Sentiments* (1787)",
        "explanation": "Naming primary sources by author/title is essential for AP DBQ scoring."
      }
    },
    {
      id: "aasod6-dropdown",
      type: 'dropdown-select' as const,
      content: "**Match Sources to Their Function** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "Equiano, *The Interesting Narrative* (1789) — purpose ___",
            "options": [
              "Eyewitness account of Igbo society, capture, and Middle Passage.",
              "Demonstrates literacy and classical education to challenge proslavery claims.",
              "Direct demand for total abolition by an enslaved survivor.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "Wheatley, *Poems on Various Subjects* (1773) — purpose ___",
            "options": [
              "Demonstrates literacy and classical education to challenge proslavery claims.",
              "Eyewitness account of Igbo society, capture, and Middle Passage.",
              "Direct demand for total abolition by an enslaved survivor.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "Cugoano, *Thoughts and Sentiments* (1787) — purpose ___",
            "options": [
              "Direct demand for total abolition by an enslaved survivor.",
              "Eyewitness account of Igbo society, capture, and Middle Passage.",
              "Demonstrates literacy and classical education to challenge proslavery claims.",
              "Unrelated to this unit"
            ]
          }
        ],
        "correctAnswers": [
          "Eyewitness account of Igbo society, capture, and Middle Passage.",
          "Demonstrates literacy and classical education to challenge proslavery claims.",
          "Direct demand for total abolition by an enslaved survivor."
        ],
        "hint1": "Match the source to its actual function.",
        "hint2": "Date and audience matter.",
        "hint3": "Pick the description matching the title.",
        "explanation": "Each source plays a distinct evidentiary role within the unit."
      }
    },
    {
      id: "aasod6-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A strong AP citation of Equiano, *The Interesting Narrative* (1789) reads:",
            "options": [
              "'According to Equiano, *The Interesting Narrative* (1789), …' followed by inference about purpose and historical situation.",
              "A direct quote with no attribution.",
              "A loose paraphrase that hides the source's identity.",
              "An anachronistic reading that ignores the date."
            ],
            "correctAnswer": 0,
            "explanation": "Attribution + sourcing analysis is the AP scoring standard."
          },
          {
            "question": "Which source-analysis move earns the AP 'sourcing' point?",
            "options": [
              "Identifying author, audience, purpose, OR historical situation — and using it to support a claim.",
              "Quoting verbatim with no analysis.",
              "Ignoring the source's date.",
              "Citing only 21st-century opinion pieces."
            ],
            "correctAnswer": 0,
            "explanation": "AP DBQ rubrics explicitly reward sourcing analysis tied to claims."
          }
        ]
      }
    }
  ]
}
