// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasFreedomEnslavementPart6Data = {
  topicSlug: "aas-freedom-enslavement",
  sections: [
    {
      id: "aasfe6-intro",
      type: 'text' as const,
      content: "# 🕊️ Freedom & Enslavement\n\n**Part 6 of 7 — Source & Evidence Workshop**\n\n---\n\n## Working with primary sources for Freedom & Enslavement\n\nAP DBQ-style work expects students to identify a source's *purpose, audience, point of view, and historical situation* — and to use that analysis to support a claim.\n\n### Primary sources for this unit\n\n- **Walker, *Appeal* (1829)** — Articulates citizenship and rights claims for free Black Americans.\n- **Stewart speeches (1832)** — Earliest published political addresses by an American-born woman.\n- **AME Church *Discipline* (1817)** — Institutional charter of independent Black religious life.\n"
    },
    {
      id: "aasfe6-workshop",
      type: 'text' as const,
      content: "## Source-analysis workshop\n\nFor each source, ask:\n1. **Who** is the author? What is their position relative to events?\n2. **When** was it produced? Before, during, or after the events described?\n3. **For whom** was it written? Audience shapes argument.\n4. **What** does it claim? What does it leave out?\n\n### Worked example\n\n> *Walker, *Appeal* (1829)* — Articulates citizenship and rights claims for free Black Americans. A strong AP citation reads: 'According to Walker, *Appeal* (1829), …' followed by an inference about authorial purpose."
    },
    {
      id: "aasfe6-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "What makes Walker, *Appeal* (1829) a strong source for studying Freedom & Enslavement?",
            "options": [
              "Articulates citizenship and rights claims for free Black Americans.",
              "It was published in 2024 with no link to the period.",
              "It is fictional and includes no historical content.",
              "It is unsigned and undated."
            ],
            "correctAnswer": 0,
            "explanation": "Provenance, date, and authorial position determine source value."
          },
          {
            "question": "When using a primary source on the AP exam, you should:",
            "options": [
              "Identify author/date/audience and tie the source to a specific claim.",
              "Quote the source verbatim without analysis.",
              "Ignore the author's position.",
              "Treat the source as neutral and unbiased."
            ],
            "correctAnswer": 0,
            "explanation": "AP source-use rewards explicit attribution and analytical framing."
          }
        ]
      }
    },
    {
      id: "aasfe6-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Name the source: Articulates citizenship and rights claims for free Black Ame…\n\n2) Name the source: Earliest published political addresses by an American-born w…\n\n3) Name the source: Institutional charter of independent Black religious life.…\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Walker, Appeal (1829)",
          "Stewart speeches (1832)",
          "AME Church Discipline (1817)"
        ],
        "hint1": "Hint: Walker, *Appeal* (1829)",
        "hint2": "Hint: Stewart speeches (1832)",
        "hint3": "Hint: AME Church *Discipline* (1817)",
        "explanation": "Naming primary sources by author/title is essential for AP DBQ scoring."
      }
    },
    {
      id: "aasfe6-dropdown",
      type: 'dropdown-select' as const,
      content: "**Match Sources to Their Function** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "Walker, *Appeal* (1829) — purpose ___",
            "options": [
              "Articulates citizenship and rights claims for free Black Americans.",
              "Earliest published political addresses by an American-born woman.",
              "Institutional charter of independent Black religious life.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "Stewart speeches (1832) — purpose ___",
            "options": [
              "Earliest published political addresses by an American-born woman.",
              "Articulates citizenship and rights claims for free Black Americans.",
              "Institutional charter of independent Black religious life.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "AME Church *Discipline* (1817) — purpose ___",
            "options": [
              "Institutional charter of independent Black religious life.",
              "Articulates citizenship and rights claims for free Black Americans.",
              "Earliest published political addresses by an American-born woman.",
              "Unrelated to this unit"
            ]
          }
        ],
        "correctAnswers": [
          "Articulates citizenship and rights claims for free Black Americans.",
          "Earliest published political addresses by an American-born woman.",
          "Institutional charter of independent Black religious life."
        ],
        "hint1": "Match the source to its actual function.",
        "hint2": "Date and audience matter.",
        "hint3": "Pick the description matching the title.",
        "explanation": "Each source plays a distinct evidentiary role within the unit."
      }
    },
    {
      id: "aasfe6-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A strong AP citation of Walker, *Appeal* (1829) reads:",
            "options": [
              "'According to Walker, *Appeal* (1829), …' followed by inference about purpose and historical situation.",
              "A direct quote with no attribution.",
              "A loose paraphrase that hides the source's identity.",
              "An anachronistic reading that ignores the date."
            ],
            "correctAnswer": 0,
            "explanation": "Attribution + sourcing analysis is the AP scoring standard."
          },
          {
            "question": "Which source-analysis move earns the AP 'sourcing' point?",
            "options": [
              "Identifying author, audience, purpose, OR historical situation — and using it to support a claim.",
              "Quoting verbatim with no analysis.",
              "Ignoring the source's date.",
              "Citing only 21st-century opinion pieces."
            ],
            "correctAnswer": 0,
            "explanation": "AP DBQ rubrics explicitly reward sourcing analysis tied to claims."
          }
        ]
      }
    }
  ]
}
