// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasAfricanKingdomsPart3Data = {
  topicSlug: "aas-african-kingdoms",
  sections: [
    {
      id: "aasak3-intro",
      type: 'text' as const,
      content: "# 👑 African Kingdoms & Civilizations\n\n**Part 3 of 7 — Patterns, Regions & Case Studies**\n\n---\n\n## Specific cases — not abstractions\n\n| Event | Significance |\n|---|---|\n| **c. 300–1076 Ghana Empire** | Controlled the gold–salt trade; sacked by the Almoravids in 1076. |\n| **1235 Battle of Kirina** | Sundiata defeats Sumanguru of Sosso; foundation of Mali. |\n| **1324 Mansa Musa's hajj** | Caravan of ~60,000 attendants and ~12 tons of gold; placed Mali on European maps. |\n| **1464–1492 Sunni Ali** | Built Songhai's military and seized Timbuktu (1468) and Djenné (1473). |\n| **1591 Battle of Tondibi** | Moroccan musketeers crush Songhai cavalry, ending the empire. |\n| **11th–15th c. Great Zimbabwe** | Stone capital of ~18,000 controlling gold–ivory routes to Sofala. |\n| **c. 800–1500 Swahili city-states** | Kilwa, Mombasa, Mogadishu integrate the East African coast into Indian Ocean trade; Swahili language emerges. |\n"
    },
    {
      id: "aasak3-cases",
      type: 'text' as const,
      content: "## Comparing cases\n\nAP comparison prompts ask you to identify a specific similarity AND difference between cases. For African Kingdoms, useful comparisons include:\n\n- c. 300–1076 Ghana Empire vs. 1235 Battle of Kirina\n- 1235 Battle of Kirina vs. 1324 Mansa Musa's hajj\n- 1324 Mansa Musa's hajj vs. c. 800–1500 Swahili city-states\n\n### Strong comparison sentence\n\n> Both c. 300–1076 Ghana Empire and 1235 Battle of Kirina involved trans-saharan trade, but they differed in the specific actors and consequences involved.\n"
    },
    {
      id: "aasak3-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which case BEST illustrates a pattern central to African Kingdoms?",
            "options": [
              "c. 300–1076 Ghana Empire — Controlled the gold–salt trade; sacked by the Almoravids in 1076.",
              "An unrelated event from another century.",
              "A purely fictional event.",
              "An anecdote with no documentary support."
            ],
            "correctAnswer": 0,
            "explanation": "Use historically attested events to illustrate patterns."
          },
          {
            "question": "A comparison of c. 300–1076 Ghana Empire and 1235 Battle of Kirina is most useful because:",
            "options": [
              "Both cases let students see common patterns and unique local differences in concrete historical detail.",
              "Both events occurred in identical contexts and produced identical outcomes.",
              "Comparison is irrelevant to AP scoring.",
              "Neither event left primary sources for historians."
            ],
            "correctAnswer": 0,
            "explanation": "AP comparison rewards specific similarities and differences with named cases."
          }
        ]
      }
    },
    {
      id: "aasak3-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Name the event: Controlled the gold–salt trade; sacked by the Almoravids in 1076.…\n\n2) Name the event: Sundiata defeats Sumanguru of Sosso; foundation of Mali.…\n\n3) Name the event: Caravan of ~60,000 attendants and ~12 tons of gold; placed Mali on European maps…\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "c. 300–1076 Ghana Empire",
          "1235 Battle of Kirina",
          "1324 Mansa Musa's hajj"
        ],
        "hint1": "Hint: c.",
        "hint2": "Hint: 1235",
        "hint3": "Hint: 1324",
        "explanation": "Naming specific events anchors AP arguments in evidence."
      }
    },
    {
      id: "aasak3-dropdown",
      type: 'dropdown-select' as const,
      content: "**Match Cases to Patterns** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "The case most central to Trans-Saharan trade is ___",
            "options": [
              "c. 300–1076 Ghana Empire",
              "1235 Battle of Kirina",
              "1324 Mansa Musa's hajj",
              "An unrelated 21st-century news story"
            ]
          },
          {
            "label": "The case most central to Islamic scholarship is ___",
            "options": [
              "1235 Battle of Kirina",
              "c. 300–1076 Ghana Empire",
              "1324 Mansa Musa's hajj",
              "An unrelated 21st-century news story"
            ]
          },
          {
            "label": "The case most central to Centralized empires is ___",
            "options": [
              "1324 Mansa Musa's hajj",
              "c. 300–1076 Ghana Empire",
              "1235 Battle of Kirina",
              "An unrelated 21st-century news story"
            ]
          }
        ],
        "correctAnswers": [
          "c. 300–1076 Ghana Empire",
          "1235 Battle of Kirina",
          "1324 Mansa Musa's hajj"
        ],
        "hint1": "Use chronology to disambiguate.",
        "hint2": "Match the event to the concept it best illustrates.",
        "hint3": "Stay inside the unit's date range.",
        "explanation": "Each event is paired with the concept it most directly illustrates."
      }
    },
    {
      id: "aasak3-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Using one specific case from African Kingdoms, which sentence is the BEST AP comparison move?",
            "options": [
              "Both c. 300–1076 Ghana Empire and 1235 Battle of Kirina reveal trans-saharan trade, but they differ in actors and outcomes.",
              "Both events were fictional and produced no consequences.",
              "These events are too old to compare meaningfully.",
              "Comparison is unimportant in AP rubrics."
            ],
            "correctAnswer": 0,
            "explanation": "AP comparison combines a specific shared pattern with a specific difference."
          },
          {
            "question": "Sundiata Keita's role in African Kingdoms is best illustrated by which event?",
            "options": [
              "c. 300–1076 Ghana Empire — Controlled the gold–salt trade; sacked by the Almoravids in 1076.",
              "An unrelated event in a different century.",
              "A purely literary publication unconnected to politics.",
              "An event before the figure was born."
            ],
            "correctAnswer": 0,
            "explanation": "Tie figures to dated events for high-scoring AP arguments."
          }
        ]
      }
    }
  ]
}
