// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasAfricanKingdomsPart2Data = {
  topicSlug: "aas-african-kingdoms",
  sections: [
    {
      id: "aasak2-intro",
      type: 'text' as const,
      content: "# 👑 African Kingdoms & Civilizations\n\n**Part 2 of 7 — Key Processes & Mechanisms**\n\n---\n\n## What drove African Kingdoms?\n\nThis part focuses on the *mechanisms* — the systematic processes that produced the patterns historians describe.\n\n| Core concept | What it refers to |\n|---|---|\n| **Trans-Saharan trade** | Camel caravans linked West Africa with North Africa, exchanging gold, salt, copper, kola nuts, and enslaved people. |\n| **Islamic scholarship** | Cities like Timbuktu and Djenné became centers of Quranic learning and law (Maliki school). |\n| **Centralized empires** | Mali and Songhai built tax systems, standing armies, and provincial governors over millions of subjects. |\n"
    },
    {
      id: "aasak2-process",
      type: 'text' as const,
      content: "## Mechanisms in action\n\n| Event | Significance |\n|---|---|\n| **c. 300–1076 Ghana Empire** | Controlled the gold–salt trade; sacked by the Almoravids in 1076. |\n| **1235 Battle of Kirina** | Sundiata defeats Sumanguru of Sosso; foundation of Mali. |\n| **1324 Mansa Musa's hajj** | Caravan of ~60,000 attendants and ~12 tons of gold; placed Mali on European maps. |\n| **1464–1492 Sunni Ali** | Built Songhai's military and seized Timbuktu (1468) and Djenné (1473). |\n\n### Causal chains\n\nAP responses on African Kingdoms should make causation explicit. A strong sentence might be:\n\n> Because trans-saharan trade intensified, communities responded by centralized empires, which in turn produced islamic scholarship.\n"
    },
    {
      id: "aasak2-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which BEST describes a primary mechanism shaping African Kingdoms?",
            "options": [
              "Camel caravans linked West Africa with North Africa, exchanging gold, salt, copper, kola nuts, and enslaved people.",
              "An unrelated technological invention from a different century.",
              "Pure coincidence with no identifiable cause.",
              "A modern political slogan with no historical content."
            ],
            "correctAnswer": 0,
            "explanation": "Trans-Saharan trade is the central mechanism the AP exam expects students to explain."
          },
          {
            "question": "Mansa Musa's career illustrates which historical mechanism?",
            "options": [
              "Mali emperor whose 1324 hajj distributed so much gold it depressed Cairo's currency for a decade; commissioned Djinguereber Mosque at Timbuktu.",
              "Mansa Musa had no impact on African Kingdoms.",
              "An entirely modern policy debate.",
              "A purely literary aesthetic."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards specific causal claims tied to named figures."
          }
        ]
      }
    },
    {
      id: "aasak2-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Which figure (r. c. 1235–1255) is associated with African Kingdoms?\n\n2) Which figure (r. 1312–1337) shaped this mechanism?\n\n3) Which figure (r. 1493–1528) extended it?\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Sundiata Keita",
          "Mansa Musa",
          "Askia Muhammad I"
        ],
        "hint1": "Hint: r. c. 1235–1255",
        "hint2": "Hint: r. 1312–1337",
        "hint3": "Hint: r. 1493–1528",
        "explanation": "Naming specific figures is essential for high-scoring AP responses."
      }
    },
    {
      id: "aasak2-dropdown",
      type: 'dropdown-select' as const,
      content: "**Trace the Mechanism** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "The mechanism most strongly associated with Sundiata Keita is ___",
            "options": [
              "Founder of the Mali Empire; defeated the Sosso at the Battle of Kirina (1235); preserved in the *Epic of Sundiata*.",
              "Mali emperor whose 1324 hajj distributed so much gold it depressed Cairo's currency for a decade; commissioned Djinguereber Mosque at Timbuktu.",
              "Songhai ruler who centralized administration, performed his own hajj, and elevated Timbuktu's Sankore Madrasa.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "The mechanism most strongly associated with Mansa Musa is ___",
            "options": [
              "Mali emperor whose 1324 hajj distributed so much gold it depressed Cairo's currency for a decade; commissioned Djinguereber Mosque at Timbuktu.",
              "Founder of the Mali Empire; defeated the Sosso at the Battle of Kirina (1235); preserved in the *Epic of Sundiata*.",
              "Songhai ruler who centralized administration, performed his own hajj, and elevated Timbuktu's Sankore Madrasa.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "The mechanism most strongly associated with Askia Muhammad I is ___",
            "options": [
              "Songhai ruler who centralized administration, performed his own hajj, and elevated Timbuktu's Sankore Madrasa.",
              "Founder of the Mali Empire; defeated the Sosso at the Battle of Kirina (1235); preserved in the *Epic of Sundiata*.",
              "Mali emperor whose 1324 hajj distributed so much gold it depressed Cairo's currency for a decade; commissioned Djinguereber Mosque at Timbuktu.",
              "Unrelated to this unit"
            ]
          }
        ],
        "correctAnswers": [
          "Founder of the Mali Empire; defeated the Sosso at the Battle of Kirina (1235); preserved in the *Epic of Sundiata*.",
          "Mali emperor whose 1324 hajj distributed so much gold it depressed Cairo's currency for a decade; commissioned Djinguereber Mosque at Timbuktu.",
          "Songhai ruler who centralized administration, performed his own hajj, and elevated Timbuktu's Sankore Madrasa."
        ],
        "hint1": "Match the figure's actual contribution.",
        "hint2": "Use the dates as a guide.",
        "hint3": "Stay within the historical period.",
        "explanation": "Each figure is associated with a distinct mechanism within the unit."
      }
    },
    {
      id: "aasak2-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A student argues that African Kingdoms happened spontaneously. The strongest counter-argument is:",
            "options": [
              "Identifying specific actors and processes — e.g., Sundiata Keita (r. c. 1235–1255) — that drove the change.",
              "Insisting that historians cannot know causes.",
              "Citing only events from outside this period.",
              "Memorizing dates without analyzing them."
            ],
            "correctAnswer": 0,
            "explanation": "Historical causation requires named actors, dated events, and articulated mechanisms."
          },
          {
            "question": "Which mechanism is MOST closely linked to Islamic scholarship?",
            "options": [
              "Cities like Timbuktu and Djenné became centers of Quranic learning and law (Maliki school).",
              "Camel caravans linked West Africa with North Africa, exchanging gold, salt, copper, kola nuts, and enslaved people.",
              "Mali and Songhai built tax systems, standing armies, and provincial governors over millions of subjects.",
              "A cause from a different historical era."
            ],
            "correctAnswer": 0,
            "explanation": "Islamic scholarship has its own historical mechanism distinct from related concepts."
          }
        ]
      }
    }
  ]
}
