// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasWwiWwiiEraPart1Data = {
  topicSlug: "aas-wwi-wwii-era",
  sections: [
    {
      id: "aasww1-intro",
      type: 'text' as const,
      content: "# 🪖 African Americans in the World Wars (1914–1945)\n\n**Part 1 of 7 — Foundations & Key Concepts**\n\n---\n\n### Why this unit matters\n\nAfrican Americans served in segregated units in both world wars while facing Jim Crow at home. The contradiction between fighting fascism abroad and racism at home — captured by the *Pittsburgh Courier*'s 'Double V' campaign — accelerated postwar civil-rights mobilization.\n\n### Core concepts\n\n| Core concept | What it refers to |\n|---|---|\n| **Segregated military service** | U.S. armed forces remained legally segregated until Truman's Executive Order 9981 (1948). |\n| **Double V** | Victory abroad over fascism, victory at home over racism. |\n| **Federal employment opening** | EO 8802 (1941) banned defense-industry discrimination — the first such order since Reconstruction. |\n\n> 🔑 **Key Concept:** AP African American History rewards arguments that combine specific evidence (named figures, dates, primary sources) with claims about causation, continuity, and change.\n"
    },
    {
      id: "aasww1-figures",
      type: 'text' as const,
      content: "## 📖 Key Figures of WWI & WWII Era\n\n| Figure | Dates | Why they matter |\n|---|---|---|\n| **369th 'Harlem Hellfighters'** | 1917–1919 | Spent 191 days in combat with French Army; awarded the Croix de Guerre. |\n| **A. Philip Randolph** | 1889–1979 | Brotherhood of Sleeping Car Porters (1925); 1941 March on Washington Movement pressured FDR into EO 8802. |\n| **James G. Thompson** | 1942 letter to *Pittsburgh Courier* | Coined the 'Double V' campaign. |\n| **Tuskegee Airmen (332nd Fighter Group)** | 1941–1946 | Black combat pilots; ~1,500 missions, exemplary bomber-escort record. |\n| **Charles Hamilton Houston** | 1895–1950 | WWI veteran, Howard Law dean; architect of NAACP legal strategy against segregation. |\n\n> ⚠️ **AP Alert:** Strong responses cite specific figures by name and date — e.g., '369th 'Harlem Hellfighters' (1917–1919)' rather than 'a famous leader.'"
    },
    {
      id: "aasww1-quiz1",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which statement BEST captures why WWI & WWII Era is foundational to AP African American History?",
            "options": [
              "African Americans served in segregated units in both world wars while facing Jim Crow at home. The contradiction between fighting fascism abroad and racism at home — captured by the *Pittsburgh Courier*'s 'Double V' campaign — accelerated postwar civil-rights mobilization.",
              "WWI & WWII Era is primarily a literary movement with no political implications.",
              "WWI & WWII Era only matters to one decade and rarely appears on the AP exam.",
              "WWI & WWII Era is studied to memorize dates without analyzing causes."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards students who can articulate why WWI & WWII Era matters in the broader course narrative, not just describe it."
          },
          {
            "question": "369th 'Harlem Hellfighters' (1917–1919) is significant in this unit primarily because:",
            "options": [
              "Spent 191 days in combat with French Army; awarded the Croix de Guerre.",
              "369th 'Harlem Hellfighters' opposed every form of African American institution building.",
              "369th 'Harlem Hellfighters' lived after the events of WWI & WWII Era ended.",
              "369th 'Harlem Hellfighters' is mentioned only in passing on the AP exam."
            ],
            "correctAnswer": 0,
            "explanation": "369th 'Harlem Hellfighters' is one of the central named figures the AP exam expects students to deploy when writing about WWI & WWII Era."
          }
        ]
      }
    },
    {
      id: "aasww1-context",
      type: 'text' as const,
      content: "## Historical Context\n\n| Event | Significance |\n|---|---|\n| **1917 East St. Louis riot** | Anti-Black violence during WWI labor migration. |\n| **1925 Brotherhood of Sleeping Car Porters founded** | First Black-led union recognized by AFL. |\n| **1941 EO 8802 / FEPC created** | Bans defense-industry discrimination. |\n\n### Primary sources to know\n\n- ***Pittsburgh Courier* Double V campaign (1942–43)** — Black press leadership of wartime civil-rights agitation.\n- **Randolph March on Washington Movement memos (1941)** — Threatened mass march pressures FDR.\n- **Tuskegee Airmen Air Corps records** — Operational data refuting claims about Black combat capacity.\n"
    },
    {
      id: "aasww1-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\nUse the exact historical term:\n\n1) Fair Employment Practices Committee — created by EO 8802\n\n2) March on Washington Movement (1941)\n\n3) Pittsburgh Courier slogan linking domestic and global anti-fascism\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "FEPC",
          "MOWM",
          "Double V"
        ],
        "hint1": "Concept 1: F…",
        "hint2": "Concept 2: M…",
        "hint3": "Concept 3: D…",
        "explanation": "FEPC, MOWM, and Double V are core vocabulary for WWI & WWII Era."
      }
    },
    {
      id: "aasww1-dropdown",
      type: 'dropdown-select' as const,
      content: "**Match the Concepts** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "Segregated military service is best described as ___",
            "options": [
              "U.S. armed forces remained legally segregated until Truman's Executive Order 9981 (1948).",
              "Victory abroad over fascism, victory at home over racism.",
              "EO 8802 (1941) banned defense-industry discrimination — the first such order since Reconstruction.",
              "An unrelated modern policy debate"
            ]
          },
          {
            "label": "Double V is best described as ___",
            "options": [
              "Victory abroad over fascism, victory at home over racism.",
              "U.S. armed forces remained legally segregated until Truman's Executive Order 9981 (1948).",
              "EO 8802 (1941) banned defense-industry discrimination — the first such order since Reconstruction.",
              "A 21st-century technology trend"
            ]
          },
          {
            "label": "Federal employment opening is best described as ___",
            "options": [
              "EO 8802 (1941) banned defense-industry discrimination — the first such order since Reconstruction.",
              "U.S. armed forces remained legally segregated until Truman's Executive Order 9981 (1948).",
              "Victory abroad over fascism, victory at home over racism.",
              "An economic theory unrelated to this period"
            ]
          }
        ],
        "correctAnswers": [
          "U.S. armed forces remained legally segregated until Truman's Executive Order 9981 (1948).",
          "Victory abroad over fascism, victory at home over racism.",
          "EO 8802 (1941) banned defense-industry discrimination — the first such order since Reconstruction."
        ],
        "hint1": "Definition tracks the concept name closely.",
        "hint2": "Match the language used in primary sources.",
        "hint3": "Use the historical, not the modern, definition.",
        "explanation": "All three are foundational concepts the AP exam expects you to define and apply within WWI & WWII Era."
      }
    },
    {
      id: "aasww1-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A historian argues that WWI & WWII Era is essential for understanding African American history. Which evidence BEST supports the claim?",
            "options": [
              "369th 'Harlem Hellfighters' (1917–1919) — Spent 191 days in combat with French Army; awarded the Croix de Guerre.",
              "A 21st-century pop song references WWI & WWII Era without historical context.",
              "WWI & WWII Era is unrelated to broader trends in U.S. or Atlantic history.",
              "There are no primary sources for this period."
            ],
            "correctAnswer": 0,
            "explanation": "Strong AP arguments cite specific historical actors and dates, not anachronistic or vague references."
          },
          {
            "question": "Which statement most accurately describes the historical context of WWI & WWII Era?",
            "options": [
              "African Americans served in segregated units in both world wars while facing Jim Crow at home. The contradiction between fighting fascism abroad and racism at home — captured by the *Pittsburgh Courier*'s 'Double V' campaign — accelerated postwar civil-rights mobilization.",
              "WWI & WWII Era occurred entirely outside any global or transregional context.",
              "WWI & WWII Era produced no documentary evidence and is impossible to study.",
              "WWI & WWII Era only appears on AP optional questions."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards contextualization — placing the topic within larger historical processes."
          }
        ]
      }
    }
  ]
}
