// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasContemporaryIssuesPart6Data = {
  topicSlug: "aas-contemporary-issues",
  sections: [
    {
      id: "aasci6-intro",
      type: 'text' as const,
      content: "# ⚡ Contemporary Issues & Debates\n\n**Part 6 of 7 — Source & Evidence Workshop**\n\n---\n\n## Working with primary sources for Contemporary Issues\n\nAP DBQ-style work expects students to identify a source's *purpose, audience, point of view, and historical situation* — and to use that analysis to support a claim.\n\n### Primary sources for this unit\n\n- **Alexander, *The New Jim Crow* (2010)** — Argues mass incarceration is a racial caste system.\n- **Coates, 'The Case for Reparations' (2014)** — Frames housing discrimination and HOLC redlining as theft.\n- **BLM founding statement (2013)** — Centers Black queer and women's lives within the movement.\n"
    },
    {
      id: "aasci6-workshop",
      type: 'text' as const,
      content: "## Source-analysis workshop\n\nFor each source, ask:\n1. **Who** is the author? What is their position relative to events?\n2. **When** was it produced? Before, during, or after the events described?\n3. **For whom** was it written? Audience shapes argument.\n4. **What** does it claim? What does it leave out?\n\n### Worked example\n\n> *Alexander, *The New Jim Crow* (2010)* — Argues mass incarceration is a racial caste system. A strong AP citation reads: 'According to Alexander, *The New Jim Crow* (2010), …' followed by an inference about authorial purpose."
    },
    {
      id: "aasci6-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "What makes Alexander, *The New Jim Crow* (2010) a strong source for studying Contemporary Issues?",
            "options": [
              "Argues mass incarceration is a racial caste system.",
              "It was published in 2024 with no link to the period.",
              "It is fictional and includes no historical content.",
              "It is unsigned and undated."
            ],
            "correctAnswer": 0,
            "explanation": "Provenance, date, and authorial position determine source value."
          },
          {
            "question": "When using a primary source on the AP exam, you should:",
            "options": [
              "Identify author/date/audience and tie the source to a specific claim.",
              "Quote the source verbatim without analysis.",
              "Ignore the author's position.",
              "Treat the source as neutral and unbiased."
            ],
            "correctAnswer": 0,
            "explanation": "AP source-use rewards explicit attribution and analytical framing."
          }
        ]
      }
    },
    {
      id: "aasci6-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Name the source: Argues mass incarceration is a racial caste system.…\n\n2) Name the source: Frames housing discrimination and HOLC redlining as theft.…\n\n3) Name the source: Centers Black queer and women's lives within the movement.…\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Alexander, The New Jim Crow (2010)",
          "Coates, 'The Case for Reparations' (2014)",
          "BLM founding statement (2013)"
        ],
        "hint1": "Hint: Alexander, *The New Jim Crow* (2010)",
        "hint2": "Hint: Coates, 'The Case for Reparations' (2014)",
        "hint3": "Hint: BLM founding statement (2013)",
        "explanation": "Naming primary sources by author/title is essential for AP DBQ scoring."
      }
    },
    {
      id: "aasci6-dropdown",
      type: 'dropdown-select' as const,
      content: "**Match Sources to Their Function** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "Alexander, *The New Jim Crow* (2010) — purpose ___",
            "options": [
              "Argues mass incarceration is a racial caste system.",
              "Frames housing discrimination and HOLC redlining as theft.",
              "Centers Black queer and women's lives within the movement.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "Coates, 'The Case for Reparations' (2014) — purpose ___",
            "options": [
              "Frames housing discrimination and HOLC redlining as theft.",
              "Argues mass incarceration is a racial caste system.",
              "Centers Black queer and women's lives within the movement.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "BLM founding statement (2013) — purpose ___",
            "options": [
              "Centers Black queer and women's lives within the movement.",
              "Argues mass incarceration is a racial caste system.",
              "Frames housing discrimination and HOLC redlining as theft.",
              "Unrelated to this unit"
            ]
          }
        ],
        "correctAnswers": [
          "Argues mass incarceration is a racial caste system.",
          "Frames housing discrimination and HOLC redlining as theft.",
          "Centers Black queer and women's lives within the movement."
        ],
        "hint1": "Match the source to its actual function.",
        "hint2": "Date and audience matter.",
        "hint3": "Pick the description matching the title.",
        "explanation": "Each source plays a distinct evidentiary role within the unit."
      }
    },
    {
      id: "aasci6-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A strong AP citation of Alexander, *The New Jim Crow* (2010) reads:",
            "options": [
              "'According to Alexander, *The New Jim Crow* (2010), …' followed by inference about purpose and historical situation.",
              "A direct quote with no attribution.",
              "A loose paraphrase that hides the source's identity.",
              "An anachronistic reading that ignores the date."
            ],
            "correctAnswer": 0,
            "explanation": "Attribution + sourcing analysis is the AP scoring standard."
          },
          {
            "question": "Which source-analysis move earns the AP 'sourcing' point?",
            "options": [
              "Identifying author, audience, purpose, OR historical situation — and using it to support a claim.",
              "Quoting verbatim with no analysis.",
              "Ignoring the source's date.",
              "Citing only 21st-century opinion pieces."
            ],
            "correctAnswer": 0,
            "explanation": "AP DBQ rubrics explicitly reward sourcing analysis tied to claims."
          }
        ]
      }
    }
  ]
}
