// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasCivilRightsMovementPart6Data = {
  topicSlug: "aas-civil-rights-movement",
  sections: [
    {
      id: "aascrm6-intro",
      type: 'text' as const,
      content: "# 🗽 The Civil Rights Movement\n\n**Part 6 of 7 — Source & Evidence Workshop**\n\n---\n\n## Working with primary sources for Civil Rights Movement\n\nAP DBQ-style work expects students to identify a source's *purpose, audience, point of view, and historical situation* — and to use that analysis to support a claim.\n\n### Primary sources for this unit\n\n- **King, 'Letter from Birmingham Jail' (1963)** — Defends nonviolent direct action against white-moderate critics.\n- **Hamer, 1964 DNC Credentials Committee testimony** — Nationally televised account of Mississippi violence.\n- **Selma–Montgomery footage (1965)** — 'Bloody Sunday' images shift national opinion toward VRA.\n"
    },
    {
      id: "aascrm6-workshop",
      type: 'text' as const,
      content: "## Source-analysis workshop\n\nFor each source, ask:\n1. **Who** is the author? What is their position relative to events?\n2. **When** was it produced? Before, during, or after the events described?\n3. **For whom** was it written? Audience shapes argument.\n4. **What** does it claim? What does it leave out?\n\n### Worked example\n\n> *King, 'Letter from Birmingham Jail' (1963)* — Defends nonviolent direct action against white-moderate critics. A strong AP citation reads: 'According to King, 'Letter from Birmingham Jail' (1963), …' followed by an inference about authorial purpose."
    },
    {
      id: "aascrm6-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "What makes King, 'Letter from Birmingham Jail' (1963) a strong source for studying Civil Rights Movement?",
            "options": [
              "Defends nonviolent direct action against white-moderate critics.",
              "It was published in 2024 with no link to the period.",
              "It is fictional and includes no historical content.",
              "It is unsigned and undated."
            ],
            "correctAnswer": 0,
            "explanation": "Provenance, date, and authorial position determine source value."
          },
          {
            "question": "When using a primary source on the AP exam, you should:",
            "options": [
              "Identify author/date/audience and tie the source to a specific claim.",
              "Quote the source verbatim without analysis.",
              "Ignore the author's position.",
              "Treat the source as neutral and unbiased."
            ],
            "correctAnswer": 0,
            "explanation": "AP source-use rewards explicit attribution and analytical framing."
          }
        ]
      }
    },
    {
      id: "aascrm6-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Name the source: Defends nonviolent direct action against white-moderate crit…\n\n2) Name the source: Nationally televised account of Mississippi violence.…\n\n3) Name the source: 'Bloody Sunday' images shift national opinion toward VRA.…\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "King, 'Letter from Birmingham Jail' (1963)",
          "Hamer, 1964 DNC Credentials Committee testimony",
          "Selma–Montgomery footage (1965)"
        ],
        "hint1": "Hint: King, 'Letter from Birmingham Jail' (1963)",
        "hint2": "Hint: Hamer, 1964 DNC Credentials Committee testimony",
        "hint3": "Hint: Selma–Montgomery footage (1965)",
        "explanation": "Naming primary sources by author/title is essential for AP DBQ scoring."
      }
    },
    {
      id: "aascrm6-dropdown",
      type: 'dropdown-select' as const,
      content: "**Match Sources to Their Function** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "King, 'Letter from Birmingham Jail' (1963) — purpose ___",
            "options": [
              "Defends nonviolent direct action against white-moderate critics.",
              "Nationally televised account of Mississippi violence.",
              "'Bloody Sunday' images shift national opinion toward VRA.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "Hamer, 1964 DNC Credentials Committee testimony — purpose ___",
            "options": [
              "Nationally televised account of Mississippi violence.",
              "Defends nonviolent direct action against white-moderate critics.",
              "'Bloody Sunday' images shift national opinion toward VRA.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "Selma–Montgomery footage (1965) — purpose ___",
            "options": [
              "'Bloody Sunday' images shift national opinion toward VRA.",
              "Defends nonviolent direct action against white-moderate critics.",
              "Nationally televised account of Mississippi violence.",
              "Unrelated to this unit"
            ]
          }
        ],
        "correctAnswers": [
          "Defends nonviolent direct action against white-moderate critics.",
          "Nationally televised account of Mississippi violence.",
          "'Bloody Sunday' images shift national opinion toward VRA."
        ],
        "hint1": "Match the source to its actual function.",
        "hint2": "Date and audience matter.",
        "hint3": "Pick the description matching the title.",
        "explanation": "Each source plays a distinct evidentiary role within the unit."
      }
    },
    {
      id: "aascrm6-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A strong AP citation of King, 'Letter from Birmingham Jail' (1963) reads:",
            "options": [
              "'According to King, 'Letter from Birmingham Jail' (1963), …' followed by inference about purpose and historical situation.",
              "A direct quote with no attribution.",
              "A loose paraphrase that hides the source's identity.",
              "An anachronistic reading that ignores the date."
            ],
            "correctAnswer": 0,
            "explanation": "Attribution + sourcing analysis is the AP scoring standard."
          },
          {
            "question": "Which source-analysis move earns the AP 'sourcing' point?",
            "options": [
              "Identifying author, audience, purpose, OR historical situation — and using it to support a claim.",
              "Quoting verbatim with no analysis.",
              "Ignoring the source's date.",
              "Citing only 21st-century opinion pieces."
            ],
            "correctAnswer": 0,
            "explanation": "AP DBQ rubrics explicitly reward sourcing analysis tied to claims."
          }
        ]
      }
    }
  ]
}
