// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasAfricanKingdomsPart6Data = {
  topicSlug: "aas-african-kingdoms",
  sections: [
    {
      id: "aasak6-intro",
      type: 'text' as const,
      content: "# 👑 African Kingdoms & Civilizations\n\n**Part 6 of 7 — Source & Evidence Workshop**\n\n---\n\n## Working with primary sources for African Kingdoms\n\nAP DBQ-style work expects students to identify a source's *purpose, audience, point of view, and historical situation* — and to use that analysis to support a claim.\n\n### Primary sources for this unit\n\n- ***Epic of Sundiata*** — Oral tradition transmitted by Mande griots; founding narrative of Mali.\n- **Ibn Battuta, *Rihla* (1355)** — Description of Mansa Suleyman's court, mosque attendance, and royal protocol.\n- **Afonso I to João III (1526)** — King of Kongo's letter denouncing Portuguese slavers operating in his kingdom.\n- ***Tarikh al-Sudan* (al-Saʿdi, 17th c.)** — Timbuktu chronicle of Songhai rulers and scholars.\n"
    },
    {
      id: "aasak6-workshop",
      type: 'text' as const,
      content: "## Source-analysis workshop\n\nFor each source, ask:\n1. **Who** is the author? What is their position relative to events?\n2. **When** was it produced? Before, during, or after the events described?\n3. **For whom** was it written? Audience shapes argument.\n4. **What** does it claim? What does it leave out?\n\n### Worked example\n\n> **Epic of Sundiata** — Oral tradition transmitted by Mande griots; founding narrative of Mali. A strong AP citation reads: 'According to *Epic of Sundiata*, …' followed by an inference about authorial purpose."
    },
    {
      id: "aasak6-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "What makes *Epic of Sundiata* a strong source for studying African Kingdoms?",
            "options": [
              "Oral tradition transmitted by Mande griots; founding narrative of Mali.",
              "It was published in 2024 with no link to the period.",
              "It is fictional and includes no historical content.",
              "It is unsigned and undated."
            ],
            "correctAnswer": 0,
            "explanation": "Provenance, date, and authorial position determine source value."
          },
          {
            "question": "When using a primary source on the AP exam, you should:",
            "options": [
              "Identify author/date/audience and tie the source to a specific claim.",
              "Quote the source verbatim without analysis.",
              "Ignore the author's position.",
              "Treat the source as neutral and unbiased."
            ],
            "correctAnswer": 0,
            "explanation": "AP source-use rewards explicit attribution and analytical framing."
          }
        ]
      }
    },
    {
      id: "aasak6-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Name the source: Oral tradition transmitted by Mande griots; founding narrati…\n\n2) Name the source: Description of Mansa Suleyman's court, mosque attendance, an…\n\n3) Name the source: King of Kongo's letter denouncing Portuguese slavers operati…\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Epic of Sundiata",
          "Ibn Battuta, Rihla (1355)",
          "Afonso I to João III (1526)"
        ],
        "hint1": "Hint: *Epic of Sundiata*",
        "hint2": "Hint: Ibn Battuta, *Rihla* (1355)",
        "hint3": "Hint: Afonso I to João III (1526)",
        "explanation": "Naming primary sources by author/title is essential for AP DBQ scoring."
      }
    },
    {
      id: "aasak6-dropdown",
      type: 'dropdown-select' as const,
      content: "**Match Sources to Their Function** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "*Epic of Sundiata* — purpose ___",
            "options": [
              "Oral tradition transmitted by Mande griots; founding narrative of Mali.",
              "Description of Mansa Suleyman's court, mosque attendance, and royal protocol.",
              "King of Kongo's letter denouncing Portuguese slavers operating in his kingdom.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "Ibn Battuta, *Rihla* (1355) — purpose ___",
            "options": [
              "Description of Mansa Suleyman's court, mosque attendance, and royal protocol.",
              "Oral tradition transmitted by Mande griots; founding narrative of Mali.",
              "King of Kongo's letter denouncing Portuguese slavers operating in his kingdom.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "Afonso I to João III (1526) — purpose ___",
            "options": [
              "King of Kongo's letter denouncing Portuguese slavers operating in his kingdom.",
              "Oral tradition transmitted by Mande griots; founding narrative of Mali.",
              "Description of Mansa Suleyman's court, mosque attendance, and royal protocol.",
              "Unrelated to this unit"
            ]
          }
        ],
        "correctAnswers": [
          "Oral tradition transmitted by Mande griots; founding narrative of Mali.",
          "Description of Mansa Suleyman's court, mosque attendance, and royal protocol.",
          "King of Kongo's letter denouncing Portuguese slavers operating in his kingdom."
        ],
        "hint1": "Match the source to its actual function.",
        "hint2": "Date and audience matter.",
        "hint3": "Pick the description matching the title.",
        "explanation": "Each source plays a distinct evidentiary role within the unit."
      }
    },
    {
      id: "aasak6-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A strong AP citation of *Epic of Sundiata* reads:",
            "options": [
              "'According to *Epic of Sundiata*, …' followed by inference about purpose and historical situation.",
              "A direct quote with no attribution.",
              "A loose paraphrase that hides the source's identity.",
              "An anachronistic reading that ignores the date."
            ],
            "correctAnswer": 0,
            "explanation": "Attribution + sourcing analysis is the AP scoring standard."
          },
          {
            "question": "Which source-analysis move earns the AP 'sourcing' point?",
            "options": [
              "Identifying author, audience, purpose, OR historical situation — and using it to support a claim.",
              "Quoting verbatim with no analysis.",
              "Ignoring the source's date.",
              "Citing only 21st-century opinion pieces."
            ],
            "correctAnswer": 0,
            "explanation": "AP DBQ rubrics explicitly reward sourcing analysis tied to claims."
          }
        ]
      }
    }
  ]
}
