// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasFreedomEnslavementPart2Data = {
  topicSlug: "aas-freedom-enslavement",
  sections: [
    {
      id: "aasfe2-intro",
      type: 'text' as const,
      content: "# 🕊️ Freedom & Enslavement\n\n**Part 2 of 7 — Key Processes & Mechanisms**\n\n---\n\n## What drove Freedom & Enslavement?\n\nThis part focuses on the *mechanisms* — the systematic processes that produced the patterns historians describe.\n\n| Core concept | What it refers to |\n|---|---|\n| **Gradual emancipation in the North** | Pennsylvania (1780), New York (1799), New Jersey (1804) freed enslaved people only by birthdates. |\n| **Manumission** | Owner-granted freedom; often restricted by southern states after 1820s. |\n| **Citizenship contested** | *Dred Scott* (1857) declared people of African descent could never be U.S. citizens. |\n"
    },
    {
      id: "aasfe2-process",
      type: 'text' as const,
      content: "## Mechanisms in action\n\n| Event | Significance |\n|---|---|\n| **1780 PA Gradual Abolition Act** | First state emancipation law in the Atlantic world. |\n| **1787 Free African Society** | Black mutual-aid organization in Philadelphia. |\n| **1816 American Colonization Society founded** | Promoted resettlement to Liberia; Black opinion sharply divided. |\n| **1830 first National Negro Convention (Philadelphia)** | Black leaders organize collective political response. |\n\n### Causal chains\n\nAP responses on Freedom & Enslavement should make causation explicit. A strong sentence might be:\n\n> Because gradual emancipation in the north intensified, communities responded by citizenship contested, which in turn produced manumission.\n"
    },
    {
      id: "aasfe2-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which BEST describes a primary mechanism shaping Freedom & Enslavement?",
            "options": [
              "Pennsylvania (1780), New York (1799), New Jersey (1804) freed enslaved people only by birthdates.",
              "An unrelated technological invention from a different century.",
              "Pure coincidence with no identifiable cause.",
              "A modern political slogan with no historical content."
            ],
            "correctAnswer": 0,
            "explanation": "Gradual emancipation in the North is the central mechanism the AP exam expects students to explain."
          },
          {
            "question": "Absalom Jones's career illustrates which historical mechanism?",
            "options": [
              "Co-founded Philadelphia's Free African Society (1787); first Black Episcopal priest.",
              "Absalom Jones had no impact on Freedom & Enslavement.",
              "An entirely modern policy debate.",
              "A purely literary aesthetic."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards specific causal claims tied to named figures."
          }
        ]
      }
    },
    {
      id: "aasfe2-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) Which figure (1760–1831) is associated with Freedom & Enslavement?\n\n2) Which figure (1746–1818) shaped this mechanism?\n\n3) Which figure (c. 1735–1807) extended it?\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Richard Allen",
          "Absalom Jones",
          "Prince Hall"
        ],
        "hint1": "Hint: 1760–1831",
        "hint2": "Hint: 1746–1818",
        "hint3": "Hint: c. 1735–1807",
        "explanation": "Naming specific figures is essential for high-scoring AP responses."
      }
    },
    {
      id: "aasfe2-dropdown",
      type: 'dropdown-select' as const,
      content: "**Trace the Mechanism** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "The mechanism most strongly associated with Richard Allen is ___",
            "options": [
              "Founded the African Methodist Episcopal Church (1816); first Black bishop in the U.S.",
              "Co-founded Philadelphia's Free African Society (1787); first Black Episcopal priest.",
              "Founded the first Black Masonic lodge (1784); petitioned Massachusetts to end slavery.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "The mechanism most strongly associated with Absalom Jones is ___",
            "options": [
              "Co-founded Philadelphia's Free African Society (1787); first Black Episcopal priest.",
              "Founded the African Methodist Episcopal Church (1816); first Black bishop in the U.S.",
              "Founded the first Black Masonic lodge (1784); petitioned Massachusetts to end slavery.",
              "Unrelated to this unit"
            ]
          },
          {
            "label": "The mechanism most strongly associated with Prince Hall is ___",
            "options": [
              "Founded the first Black Masonic lodge (1784); petitioned Massachusetts to end slavery.",
              "Founded the African Methodist Episcopal Church (1816); first Black bishop in the U.S.",
              "Co-founded Philadelphia's Free African Society (1787); first Black Episcopal priest.",
              "Unrelated to this unit"
            ]
          }
        ],
        "correctAnswers": [
          "Founded the African Methodist Episcopal Church (1816); first Black bishop in the U.S.",
          "Co-founded Philadelphia's Free African Society (1787); first Black Episcopal priest.",
          "Founded the first Black Masonic lodge (1784); petitioned Massachusetts to end slavery."
        ],
        "hint1": "Match the figure's actual contribution.",
        "hint2": "Use the dates as a guide.",
        "hint3": "Stay within the historical period.",
        "explanation": "Each figure is associated with a distinct mechanism within the unit."
      }
    },
    {
      id: "aasfe2-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A student argues that Freedom & Enslavement happened spontaneously. The strongest counter-argument is:",
            "options": [
              "Identifying specific actors and processes — e.g., Richard Allen (1760–1831) — that drove the change.",
              "Insisting that historians cannot know causes.",
              "Citing only events from outside this period.",
              "Memorizing dates without analyzing them."
            ],
            "correctAnswer": 0,
            "explanation": "Historical causation requires named actors, dated events, and articulated mechanisms."
          },
          {
            "question": "Which mechanism is MOST closely linked to Manumission?",
            "options": [
              "Owner-granted freedom; often restricted by southern states after 1820s.",
              "Pennsylvania (1780), New York (1799), New Jersey (1804) freed enslaved people only by birthdates.",
              "*Dred Scott* (1857) declared people of African descent could never be U.S. citizens.",
              "A cause from a different historical era."
            ],
            "correctAnswer": 0,
            "explanation": "Manumission has its own historical mechanism distinct from related concepts."
          }
        ]
      }
    }
  ]
}
