// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasSlaveryInAmericaPart1Data = {
  topicSlug: "aas-slavery-in-america",
  sections: [
    {
      id: "aassia1-intro",
      type: 'text' as const,
      content: "# 🏚️ Slavery in America (c. 1619–1865)\n\n**Part 1 of 7 — Foundations & Key Concepts**\n\n---\n\n### Why this unit matters\n\nSlavery in British North America hardened from a fluid 17th-century labor system into race-based, hereditary chattel slavery. By 1860, ~4 million enslaved African Americans produced two-thirds of the world's cotton supply, financing southern wealth and northern industry.\n\n### Core concepts\n\n| Core concept | What it refers to |\n|---|---|\n| **Chattel slavery** | Legal status defining humans as inheritable property — distinct from indenture or serfdom. |\n| **Partus sequitur ventrem** | Virginia 1662 law: a child's status follows the mother's, making slavery hereditary. |\n| **Domestic slave trade** | After 1808 ban on imports, ~1 million people forcibly relocated from Upper to Lower South. |\n\n> 🔑 **Key Concept:** AP African American History rewards arguments that combine specific evidence (named figures, dates, primary sources) with claims about causation, continuity, and change.\n"
    },
    {
      id: "aassia1-figures",
      type: 'text' as const,
      content: "## 📖 Key Figures of Slavery in America\n\n| Figure | Dates | Why they matter |\n|---|---|---|\n| **Anthony Johnson** | c. 1600–1670 | Angolan-born Virginia free Black who himself owned servants — illustrates pre-1660s fluidity. |\n| **Eli Whitney** | 1765–1825 | Cotton gin (1793) made short-staple cotton profitable, expanding slavery into the Deep South. |\n| **Solomon Northup** | 1808–c. 1864 | Free Black New Yorker kidnapped into Louisiana slavery; *Twelve Years a Slave* (1853). |\n| **Harriet Jacobs** | c. 1813–1897 | *Incidents in the Life of a Slave Girl* (1861) — first-person account of sexual exploitation. |\n| **Frederick Douglass** | c. 1818–1895 | *Narrative* (1845) describes Maryland slavery and the path to literacy as resistance. |\n\n> ⚠️ **AP Alert:** Strong responses cite specific figures by name and date — e.g., 'Anthony Johnson (c. 1600–1670)' rather than 'a famous leader.'"
    },
    {
      id: "aassia1-quiz1",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which statement BEST captures why Slavery in America is foundational to AP African American History?",
            "options": [
              "Slavery in British North America hardened from a fluid 17th-century labor system into race-based, hereditary chattel slavery. By 1860, ~4 million enslaved African Americans produced two-thirds of the world's cotton supply, financing southern wealth and northern industry.",
              "Slavery in America is primarily a literary movement with no political implications.",
              "Slavery in America only matters to one decade and rarely appears on the AP exam.",
              "Slavery in America is studied to memorize dates without analyzing causes."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards students who can articulate why Slavery in America matters in the broader course narrative, not just describe it."
          },
          {
            "question": "Anthony Johnson (c. 1600–1670) is significant in this unit primarily because:",
            "options": [
              "Angolan-born Virginia free Black who himself owned servants — illustrates pre-1660s fluidity.",
              "Anthony Johnson opposed every form of African American institution building.",
              "Anthony Johnson lived after the events of Slavery in America ended.",
              "Anthony Johnson is mentioned only in passing on the AP exam."
            ],
            "correctAnswer": 0,
            "explanation": "Anthony Johnson is one of the central named figures the AP exam expects students to deploy when writing about Slavery in America."
          }
        ]
      }
    },
    {
      id: "aassia1-context",
      type: 'text' as const,
      content: "## Historical Context\n\n| Event | Significance |\n|---|---|\n| **1641 Massachusetts legalizes slavery** | First English colony to do so. |\n| **1662 Virginia partus law** | Slavery becomes hereditary through the mother. |\n| **1705 Virginia Slave Codes** | Comprehensive race-based legal regime; later models for other colonies. |\n\n### Primary sources to know\n\n- **Douglass, *Narrative* (1845)** — Argues that literacy is the road to freedom — a reframing of master-slave power.\n- **Jacobs, *Incidents* (1861)** — Reveals gendered violence largely absent from earlier male-authored narratives.\n- **Slave Codes of Virginia (1705)** — Codifies racial hierarchy in colonial law.\n"
    },
    {
      id: "aassia1-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\nUse the exact historical term:\n\n1) Plantation work organized in supervised groups, common on cotton estates\n\n2) Each enslaved person assigned a daily task; common in Lowcountry rice plantations\n\n3) Colony/state laws defining the legal status and restrictions of enslaved people\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Gang labor",
          "Task system",
          "Slave codes"
        ],
        "hint1": "Concept 1: G…",
        "hint2": "Concept 2: T…",
        "hint3": "Concept 3: S…",
        "explanation": "Gang labor, Task system, and Slave codes are core vocabulary for Slavery in America."
      }
    },
    {
      id: "aassia1-dropdown",
      type: 'dropdown-select' as const,
      content: "**Match the Concepts** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "Chattel slavery is best described as ___",
            "options": [
              "Legal status defining humans as inheritable property — distinct from indenture or serfdom.",
              "Virginia 1662 law: a child's status follows the mother's, making slavery hereditary.",
              "After 1808 ban on imports, ~1 million people forcibly relocated from Upper to Lower South.",
              "An unrelated modern policy debate"
            ]
          },
          {
            "label": "Partus sequitur ventrem is best described as ___",
            "options": [
              "Virginia 1662 law: a child's status follows the mother's, making slavery hereditary.",
              "Legal status defining humans as inheritable property — distinct from indenture or serfdom.",
              "After 1808 ban on imports, ~1 million people forcibly relocated from Upper to Lower South.",
              "A 21st-century technology trend"
            ]
          },
          {
            "label": "Domestic slave trade is best described as ___",
            "options": [
              "After 1808 ban on imports, ~1 million people forcibly relocated from Upper to Lower South.",
              "Legal status defining humans as inheritable property — distinct from indenture or serfdom.",
              "Virginia 1662 law: a child's status follows the mother's, making slavery hereditary.",
              "An economic theory unrelated to this period"
            ]
          }
        ],
        "correctAnswers": [
          "Legal status defining humans as inheritable property — distinct from indenture or serfdom.",
          "Virginia 1662 law: a child's status follows the mother's, making slavery hereditary.",
          "After 1808 ban on imports, ~1 million people forcibly relocated from Upper to Lower South."
        ],
        "hint1": "Definition tracks the concept name closely.",
        "hint2": "Match the language used in primary sources.",
        "hint3": "Use the historical, not the modern, definition.",
        "explanation": "All three are foundational concepts the AP exam expects you to define and apply within Slavery in America."
      }
    },
    {
      id: "aassia1-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "A historian argues that Slavery in America is essential for understanding African American history. Which evidence BEST supports the claim?",
            "options": [
              "Anthony Johnson (c. 1600–1670) — Angolan-born Virginia free Black who himself owned servants — illustrates pre-1660s fluidity.",
              "A 21st-century pop song references Slavery in America without historical context.",
              "Slavery in America is unrelated to broader trends in U.S. or Atlantic history.",
              "There are no primary sources for this period."
            ],
            "correctAnswer": 0,
            "explanation": "Strong AP arguments cite specific historical actors and dates, not anachronistic or vague references."
          },
          {
            "question": "Which statement most accurately describes the historical context of Slavery in America?",
            "options": [
              "Slavery in British North America hardened from a fluid 17th-century labor system into race-based, hereditary chattel slavery. By 1860, ~4 million enslaved African Americans produced two-thirds of the world's cotton supply, financing southern wealth and northern industry.",
              "Slavery in America occurred entirely outside any global or transregional context.",
              "Slavery in America produced no documentary evidence and is impossible to study.",
              "Slavery in America only appears on AP optional questions."
            ],
            "correctAnswer": 0,
            "explanation": "AP rewards contextualization — placing the topic within larger historical processes."
          }
        ]
      }
    }
  ]
}
