// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasFreedomEnslavementPart5Data = {
  topicSlug: "aas-freedom-enslavement",
  sections: [
    {
      id: "aasfe5-intro",
      type: 'text' as const,
      content: "# 🕊️ Freedom & Enslavement\n\n**Part 5 of 7 — Continuity & Change Over Time**\n\n---\n\n## Tracing Freedom & Enslavement through c. 1780–1865\n\nAP CCOT (Continuity and Change Over Time) prompts ask: *what changed, what stayed the same, and what drove the change?*\n\n| Period | What changed | What persisted |\n|---|---|---|\n| Early period | New institutions emerge | African cultural retentions persist |\n| Middle period | Mechanisms of gradual emancipation in the north expand | Citizenship contested continues |\n| Late period | Outcomes shift due to external pressure | Structural features endure |\n"
    },
    {
      id: "aasfe5-change",
      type: 'text' as const,
      content: "## Specific moments of change\n\n| Event | Significance |\n|---|---|\n| **1830 first National Negro Convention (Philadelphia)** | Black leaders organize collective political response. |\n| **1850 Fugitive Slave Act** | Federal commissioners paid more for returns than releases; sparks resistance. |\n| **1857 *Dred Scott v. Sandford*** | Taney rules Black people 'have no rights which the white man was bound to respect.' |\n\n### Strong CCOT sentence\n\n> Although gradual emancipation in the north continued throughout c. 1780–1865, the events of 1857 *Dred Scott v. Sandford* marked a decisive shift in how Black communities engaged with it."
    },
    {
      id: "aasfe5-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which best describes continuity within Freedom & Enslavement?",
            "options": [
              "Aspects such as citizenship contested persisted even as other features changed.",
              "Nothing about this topic ever changed.",
              "Continuity is irrelevant to AP scoring.",
              "Only the most recent decade matters."
            ],
            "correctAnswer": 0,
            "explanation": "Continuity = elements that persist across change — a key AP analytical category."
          },
          {
            "question": "Which event marks a decisive change within Freedom & Enslavement?",
            "options": [
              "1857 *Dred Scott v. Sandford* — Taney rules Black people 'have no rights which the white man was bound to respect.'",
              "An anecdote with no historical impact.",
              "A 21st-century news headline unrelated to the period.",
              "A purely literary aesthetic with no political effect."
            ],
            "correctAnswer": 0,
            "explanation": "Specific dated events anchor change-over-time arguments."
          }
        ]
      }
    },
    {
      id: "aasfe5-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) An aspect of Freedom & Enslavement that persisted: ___\n\n2) An event that marked decisive change: ___\n\n3) The AP analytical category for tracking these together: ___\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Citizenship contested",
          "1857 *Dred Scott v. Sandford*",
          "continuity and change"
        ],
        "hint1": "Hint: *Dred Scott* (1857) declared people of African des…",
        "hint2": "Hint: Taney rules Black people 'have no rights which the…",
        "hint3": "Hint: AP CCOT",
        "explanation": "AP CCOT prompts demand both continuity and change with specific evidence."
      }
    },
    {
      id: "aasfe5-dropdown",
      type: 'dropdown-select' as const,
      content: "**Continuity vs Change** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "Continuity in this unit is best illustrated by ___",
            "options": [
              "Citizenship contested",
              "1857 *Dred Scott v. Sandford*",
              "An unrelated modern slogan",
              "A topic from a different course"
            ]
          },
          {
            "label": "Change in this unit is best illustrated by ___",
            "options": [
              "1857 *Dred Scott v. Sandford*",
              "Citizenship contested",
              "An anecdote with no date",
              "An unrelated personal opinion"
            ]
          },
          {
            "label": "An AP CCOT response should ___",
            "options": [
              "Identify both continuities and changes with specific evidence",
              "Pick only one without analysis",
              "Avoid using dates",
              "Replace evidence with opinion"
            ]
          }
        ],
        "correctAnswers": [
          "Citizenship contested",
          "1857 *Dred Scott v. Sandford*",
          "Identify both continuities and changes with specific evidence"
        ],
        "hint1": "Continuity = persistence.",
        "hint2": "Change = decisive shift, named event.",
        "hint3": "CCOT requires both halves.",
        "explanation": "AP CCOT prompts always require both continuity and change with explicit evidence."
      }
    },
    {
      id: "aasfe5-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which CCOT thesis is strongest?",
            "options": [
              "Although citizenship contested continued, 1857 *Dred Scott v. Sandford* marked a decisive change in Freedom & Enslavement.",
              "Nothing changed and nothing stayed the same.",
              "Change is impossible to identify in history.",
              "AP rubrics do not reward CCOT analysis."
            ],
            "correctAnswer": 0,
            "explanation": "Strong CCOT theses pair specific continuities with specific changes."
          },
          {
            "question": "Which evidence move is most valuable in a CCOT response?",
            "options": [
              "Naming a specific dated event AND a continuity within the same paragraph.",
              "Listing dates without analysis.",
              "Replacing evidence with a moral judgment.",
              "Citing only post-2010 news stories."
            ],
            "correctAnswer": 0,
            "explanation": "AP CCOT scoring rewards paired specificity."
          }
        ]
      }
    }
  ]
}
