// AUTO-GENERATED by scripts/write-aas-all.py — do not edit by hand.
export const aasReconstructionJimCrowPart5Data = {
  topicSlug: "aas-reconstruction-jim-crow",
  sections: [
    {
      id: "aasrjc5-intro",
      type: 'text' as const,
      content: "# ⚖️ Reconstruction & Jim Crow\n\n**Part 5 of 7 — Continuity & Change Over Time**\n\n---\n\n## Tracing Reconstruction & Jim Crow through 1865–1900\n\nAP CCOT (Continuity and Change Over Time) prompts ask: *what changed, what stayed the same, and what drove the change?*\n\n| Period | What changed | What persisted |\n|---|---|---|\n| Early period | New institutions emerge | African cultural retentions persist |\n| Middle period | Mechanisms of reconstruction amendments expand | Disfranchisement continues |\n| Late period | Outcomes shift due to external pressure | Structural features endure |\n"
    },
    {
      id: "aasrjc5-change",
      type: 'text' as const,
      content: "## Specific moments of change\n\n| Event | Significance |\n|---|---|\n| **1890 Mississippi Plan** | Constitutional convention eliminates Black voters via poll tax/literacy test. |\n| **1896 *Plessy v. Ferguson*** | Establishes 'separate but equal'; only Justice Harlan dissents. |\n| **1898 Wilmington insurrection** | White mob overthrows multiracial NC government — only successful U.S. coup. |\n\n### Strong CCOT sentence\n\n> Although reconstruction amendments continued throughout 1865–1900, the events of 1898 Wilmington insurrection marked a decisive shift in how Black communities engaged with it."
    },
    {
      id: "aasrjc5-quiz",
      type: 'multiple-choice' as const,
      content: "**Concept Check** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which best describes continuity within Reconstruction & Jim Crow?",
            "options": [
              "Aspects such as disfranchisement persisted even as other features changed.",
              "Nothing about this topic ever changed.",
              "Continuity is irrelevant to AP scoring.",
              "Only the most recent decade matters."
            ],
            "correctAnswer": 0,
            "explanation": "Continuity = elements that persist across change — a key AP analytical category."
          },
          {
            "question": "Which event marks a decisive change within Reconstruction & Jim Crow?",
            "options": [
              "1898 Wilmington insurrection — White mob overthrows multiracial NC government — only successful U.S. coup.",
              "An anecdote with no historical impact.",
              "A 21st-century news headline unrelated to the period.",
              "A purely literary aesthetic with no political effect."
            ],
            "correctAnswer": 0,
            "explanation": "Specific dated events anchor change-over-time arguments."
          }
        ]
      }
    },
    {
      id: "aasrjc5-input",
      type: 'input-boxes' as const,
      content: "**Applied Recall** ✍️\n\n1) An aspect of Reconstruction & Jim Crow that persisted: ___\n\n2) An event that marked decisive change: ___\n\n3) The AP analytical category for tracking these together: ___\n",
      exercise: {
        "boxes": 3,
        "correctAnswers": [
          "Disfranchisement",
          "1898 Wilmington insurrection",
          "continuity and change"
        ],
        "hint1": "Hint: Poll taxes, literacy tests, grandfather clauses, w…",
        "hint2": "Hint: White mob overthrows multiracial NC government — o…",
        "hint3": "Hint: AP CCOT",
        "explanation": "AP CCOT prompts demand both continuity and change with specific evidence."
      }
    },
    {
      id: "aasrjc5-dropdown",
      type: 'dropdown-select' as const,
      content: "**Continuity vs Change** 🔍",
      exercise: {
        "dropdowns": [
          {
            "label": "Continuity in this unit is best illustrated by ___",
            "options": [
              "Disfranchisement",
              "1898 Wilmington insurrection",
              "An unrelated modern slogan",
              "A topic from a different course"
            ]
          },
          {
            "label": "Change in this unit is best illustrated by ___",
            "options": [
              "1898 Wilmington insurrection",
              "Disfranchisement",
              "An anecdote with no date",
              "An unrelated personal opinion"
            ]
          },
          {
            "label": "An AP CCOT response should ___",
            "options": [
              "Identify both continuities and changes with specific evidence",
              "Pick only one without analysis",
              "Avoid using dates",
              "Replace evidence with opinion"
            ]
          }
        ],
        "correctAnswers": [
          "Disfranchisement",
          "1898 Wilmington insurrection",
          "Identify both continuities and changes with specific evidence"
        ],
        "hint1": "Continuity = persistence.",
        "hint2": "Change = decisive shift, named event.",
        "hint3": "CCOT requires both halves.",
        "explanation": "AP CCOT prompts always require both continuity and change with explicit evidence."
      }
    },
    {
      id: "aasrjc5-applied",
      type: 'multiple-choice' as const,
      content: "**AP-Style Application** 🎯",
      exercise: {
        "questions": [
          {
            "question": "Which CCOT thesis is strongest?",
            "options": [
              "Although disfranchisement continued, 1898 Wilmington insurrection marked a decisive change in Reconstruction & Jim Crow.",
              "Nothing changed and nothing stayed the same.",
              "Change is impossible to identify in history.",
              "AP rubrics do not reward CCOT analysis."
            ],
            "correctAnswer": 0,
            "explanation": "Strong CCOT theses pair specific continuities with specific changes."
          },
          {
            "question": "Which evidence move is most valuable in a CCOT response?",
            "options": [
              "Naming a specific dated event AND a continuity within the same paragraph.",
              "Listing dates without analysis.",
              "Replacing evidence with a moral judgment.",
              "Citing only post-2010 news stories."
            ],
            "correctAnswer": 0,
            "explanation": "AP CCOT scoring rewards paired specificity."
          }
        ]
      }
    }
  ]
}
