export const calcbcArcLengthPart7Data = {
  topicSlug: 'arc-length-surface-area-calcbc',
  sections: [
    {
      id: 'al7-intro',
      type: 'text' as const,
      content: `# Arc Length & Surface Area — Comprehensive Review

**Part 7 of 7 — Full Topic Review**

### Master Formula Sheet

| Form | Arc Length $L$ | Surface Area $S$ (about $x$-axis) |
|------|---------------|-----------------------------------|
| $y = f(x)$ | $\\int_a^b \\sqrt{1+(f')^2}\\,dx$ | $2\\pi\\int_a^b f(x)\\sqrt{1+(f')^2}\\,dx$ |
| $x = g(y)$ | $\\int_c^d \\sqrt{1+(g')^2}\\,dy$ | $2\\pi\\int_c^d y\\sqrt{1+(g')^2}\\,dy$ |
| Parametric | $\\int_a^b \\sqrt{(x')^2+(y')^2}\\,dt$ | $2\\pi\\int_a^b y\\sqrt{(x')^2+(y')^2}\\,dt$ |
| Polar | $\\int_\\alpha^\\beta \\sqrt{r^2+(r')^2}\\,d\\theta$ | $2\\pi\\int_\\alpha^\\beta r\\sin\\theta\\sqrt{r^2+(r')^2}\\,d\\theta$ |

> **Key Fact:** All formulas derive from $ds = \\sqrt{dx^2 + dy^2}$ and $S = 2\\pi\\int(\\text{radius})\\,ds$.`
    },
    {
      id: 'al7-checklist',
      type: 'text' as const,
      content: `### Exam Checklist

✅ **Arc Length:**
- Identify the curve form (Cartesian/parametric/polar)
- Compute $ds$ correctly
- Check for perfect squares
- If no closed form: calculator + show integral setup

✅ **Surface Area:**
- Identify axis of revolution
- Determine the radius (distance to axis)
- Set up $S = 2\\pi\\int(\\text{radius})\\,ds$
- Verify with known shapes when possible

✅ **Common Errors to Avoid:**
- Forgetting the $2\\pi$ in surface area
- Using $y$ when revolving about $y$-axis (should be $x$)
- Not taking absolute value when curve dips below axis
- Confusing arc length with displacement`
    },
    {
      id: 'al7-mc1',
      type: 'multiple-choice' as const,
      content: '**Review Questions**',
      exercise: {
        questions: [
          {
            question: 'The arc length of $y = x^2$ from $x = 0$ to $x = 1$ is:',
            options: ['$\\int_0^1 \\sqrt{1+4x^2}\\,dx$', '$\\int_0^1 (1+4x^2)\\,dx$', '$\\int_0^1 \\sqrt{4x^2}\\,dx$', '$1 + 1/3$'],
            correctAnswer: 0,
            explanation: '$y\' = 2x$, $(y\')^2 = 4x^2$. $L = \\int_0^1\\sqrt{1+4x^2}\\,dx$. This has no elementary closed form — calculator needed.'
          },
          {
            question: 'The surface area generated by rotating $y = x$ from $0$ to $1$ about the $x$-axis is:',
            options: ['$\\pi\\sqrt{2}$', '$2\\pi$', '$\\pi$', '$2\\pi\\sqrt{2}$'],
            correctAnswer: 0,
            explanation: '$y\' = 1$, $ds = \\sqrt{2}\\,dx$. $S = 2\\pi\\int_0^1 x\\sqrt{2}\\,dx = 2\\pi\\sqrt{2}\\cdot\\frac{1}{2} = \\pi\\sqrt{2}$. Cone lateral area: $\\pi r \\ell = \\pi(1)(\\sqrt{2}) = \\pi\\sqrt{2}$. ✓'
          },
          {
            question: 'Arc length is always:',
            options: ['Non-negative', 'Greater than the net displacement', 'Equal to the integral of speed', 'All of the above'],
            correctAnswer: 3,
            explanation: 'Arc length $\\ge 0$ always, arc length $\\ge$ straight-line distance between endpoints, and $\\int \\|\\vec{v}\\|\\,dt = $ total distance = arc length of the path.'
          }
        ]
      }
    },
    {
      id: 'al7-dropdown',
      type: 'dropdown-select' as const,
      content: '**Final Concept Checks**',
      exercise: {
        dropdowns: [
          {
            label: 'The surface area of the sphere of radius $R$ is obtained by rotating $y = \\sqrt{R^2 - x^2}$ about the $x$-axis. Result:',
            options: ['$4\\pi R^2$', '$2\\pi R^2$', '$\\frac{4}{3}\\pi R^3$', '$2\\pi R$'],
            correctAnswers: ['$4\\pi R^2$'],
            hints: ['This was derived in Part 3.'],
            explanation: '$S = 2\\pi\\int_{-R}^{R} \\sqrt{R^2-x^2}\\cdot\\frac{R}{\\sqrt{R^2-x^2}}\\,dx = 2\\pi R(2R) = 4\\pi R^2$.'
          },
          {
            label: 'If an arc length integral has no elementary antiderivative, on the AP exam you should:',
            options: ['Write the integral and evaluate with a calculator', 'Skip the problem', 'Approximate with a Riemann sum', 'Use L\'Hôpital\'s rule'],
            correctAnswers: ['Write the integral and evaluate with a calculator'],
            hints: ['Show work = show the integral. Then use technology.'],
            explanation: 'Write $L = \\int_a^b \\sqrt{...}\\,dx$ explicitly, then state the calculator answer to 3 decimal places. This earns full credit.'
          }
        ]
      }
    },
    {
      id: 'al7-input',
      type: 'input-box' as const,
      content: '**Final Computation**',
      exercise: {
        question: 'The arc length of $y = \\frac{x^2}{2}$ from $x = 0$ to $x = 1$ is $L = \\int_0^1 \\sqrt{1+x^2}\\,dx$. Using the formula $\\int\\sqrt{1+x^2}\\,dx = \\frac{x\\sqrt{1+x^2}}{2} + \\frac{1}{2}\\sinh^{-1}(x) + C$, evaluate at $x = 1$: $L = \\frac{\\sqrt{2}}{2} + \\frac{1}{2}\\sinh^{-1}(1)$. What is $\\sinh^{-1}(1)$ to 2 decimal places?',
        correctAnswer: '0.88',
        acceptableAnswers: ['0.88', '0.881', '0.8814', 'ln(1+sqrt(2))'],
        hints: ['$\\sinh^{-1}(x) = \\ln(x + \\sqrt{x^2+1})$.', '$\\sinh^{-1}(1) = \\ln(1 + \\sqrt{2})$.'],
        explanation: '$\\sinh^{-1}(1) = \\ln(1 + \\sqrt{2}) = \\ln(2.4142) \\approx 0.8814 \\approx 0.88$.'
      }
    },
    {
      id: 'al7-summary',
      type: 'text' as const,
      content: `### Topic Complete!

You've mastered arc length and surface area:
- Arc length in Cartesian, parametric, and polar forms
- Surface area of revolution about both axes
- Perfect-square trick for hand computation
- AP exam strategies and partial credit optimization

$$\\boxed{L = \\int ds \\qquad S = 2\\pi\\int(\\text{radius})\\,ds}$$

> **Up next:** Infinite Sequences — the foundation of series and convergence.`
    }
  ]
};
