export const cspSafeComputingPart7Data = {
  topicSlug: "csp-safe-computing",
  sections: [
    {
      id: "cspsc7-intro",
      type: 'text' as const,
      content: `
# 🔐 Safe Computing

**Part 7 of 7 — AP Review**

---

## AP Exam Recap — Safe Computing
      `
    },
    {
      id: "cspsc7-quiz1",
      type: 'multiple-choice' as const,
      content: `
**Concept Check 🎯**
      `,
      exercise: {
        questions: [
          {
            question: "Which is most clearly NOT safe-computing best practice?",
            options: [
              "Unique strong passwords per site.",
              "MFA on important accounts.",
              "Sharing the same password everywhere \"for convenience\".",
              "Patching software promptly."
            ],
            correctAnswer: 2,
            explanation: "Password reuse is the antithesis of safe computing."
          },
          {
            question: "A \"passkey\" is ___",
            options: [
              "a physical key only.",
              "a phishing-resistant credential bound to a device and the real site origin.",
              "a compression algorithm.",
              "a CDN feature."
            ],
            correctAnswer: 1,
            explanation: "Passkeys = origin-bound device credential."
          }
        ]
      }
    },
    {
      id: "cspsc7-content",
      type: 'text' as const,
      content: `
## Final Vocab

| Term | Definition |
|------|-----------|
| Password manager | Stores unique strong passwords. |
| MFA | Multi-factor authentication. |
| Phishing | Social-engineering attack. |
| Default credentials | Out-of-box passwords. |
| Patch | Software security update. |
| Backups | Off-device data copies. |
| Threat modeling | Identifying realistic adversaries. |
| Passkey | Phishing-resistant device credential. |
| Identity provider | Account that unlocks many services. |

## Common Pitfalls

- Reusing passwords across sites.
- Skipping MFA on email.
- Sharing MFA codes.
- Ignoring TLS warnings.
- Leaving default device credentials.
- No off-device backups.
- Treating safe computing as one-time, not ongoing.
      `
    },
    {
      id: "cspsc7-input",
      type: 'input-boxes' as const,
      content: `
**Applied Recall** ✍️

1) Sharing the same password across sites enables _______ stuffing.

2) A modern alternative to passwords that resists phishing is the _______.

3) Backups stored off the device protect against device loss, theft, and _______.
      `,
      exercise: {
        boxes: 3,
        correctAnswers: ["credential", "passkey", "ransomware"],
        hint1: "Reuse attack.",
        hint2: "FIDO2.",
        hint3: "Encrypted-extortion attack.",
        explanation: "Credential stuffing / passkeys / ransomware."
      }
    },
    {
      id: "cspsc7-dropdown",
      type: 'dropdown-select' as const,
      content: `
**Targeted Practice** 🔍
      `,
      exercise: {
        dropdowns: [
          {
            label: "A password should be ___",
            options: ["unique per site, generated by a password manager", "identical across all sites", "shared with friends", "compressed"]
          },
          {
            label: "A \"click any link to verify\" email is ___",
            options: ["highly suspicious — verify out-of-band first", "always safe", "always compressed", "always TLS-protected"]
          },
          {
            label: "Email + MFA is the foundation of personal safe computing because ___",
            options: ["email is the recovery channel for almost every other account", "email is the smallest file", "TLS routes through email", "compression depends on it"]
          }
        ],
        correctAnswers: ["unique per site, generated by a password manager", "highly suspicious — verify out-of-band first", "email is the recovery channel for almost every other account"],
        hint1: "Uniqueness.",
        hint2: "Verify first.",
        hint3: "Master account.",
        explanation: "Unique passwords; verify before clicking; protect email = protect everything."
      }
    },
    {
      id: "cspsc7-strategy",
      type: 'text' as const,
      content: `
## Final Exam Tips

- Personal safe computing = unique passwords + MFA + patches + backups + skepticism.
- Email is the master account — protect it first.
- Passkeys are the future of authentication.
- Safe computing affects others connected to you.
      `
    },
    {
      id: "cspsc7-applied",
      type: 'multiple-choice' as const,
      content: `
**AP-Style Application 🎯**
      `,
      exercise: {
        questions: [
          {
            question: "A grandparent forwards \"click here to claim a prize\" emails. The CSP-aligned response is ___",
            options: [
              "mock them for falling for an obvious scam and refuse to discuss safer practices with them.",
              "gently educate: explain phishing patterns, set up MFA on important accounts, install browser protection.",
              "recommend that the grandparent upgrade to the latest transport-layer security version on all devices.",
              "recommend that the grandparent compress every forwarded email before resending it to other relatives."
            ],
            correctAnswer: 1,
            explanation: "Education + MFA + browser protection = inclusive safe computing."
          },
          {
            question: "A school deploys 1,000 student laptops. The single most impactful safe-computing default is ___",
            options: [
              "no special default — each student should configure their own laptop without any baseline policy.",
              "enforce MFA on student accounts, OS auto-updates, full-disk encryption, and unique passwords.",
              "configure a single shared admin account on every laptop so technicians can support them faster.",
              "disable operating-system updates on every laptop so students are not interrupted by restarts."
            ],
            correctAnswer: 1,
            explanation: "Defaults that favor security at fleet scale."
          }
        ]
      }
    }
  ]
};
