import type { LessonData } from './registry'
import { mcatEndoNervSubPart1Data as part1 } from './mcat-mcat-organ-systems-endocrine-nervous-mcat-part1'
import { mcatEndoNervSubPart2Data as part2 } from './mcat-mcat-organ-systems-endocrine-nervous-mcat-part2'
import { mcatEndoNervSubPart3Data as part3 } from './mcat-mcat-organ-systems-endocrine-nervous-mcat-part3'
import { mcatEndoNervSubPart4Data as part4 } from './mcat-mcat-organ-systems-endocrine-nervous-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
