import type { LessonData } from './registry'
import { mcatOchemStereoPart1Data as part1 } from './mcat-mcat-organic-chemistry-stereochemistry-mcat-part1'
import { mcatOchemStereoPart2Data as part2 } from './mcat-mcat-organic-chemistry-stereochemistry-mcat-part2'
import { mcatOchemStereoPart3Data as part3 } from './mcat-mcat-organic-chemistry-stereochemistry-mcat-part3'
import { mcatOchemStereoPart4Data as part4 } from './mcat-mcat-organic-chemistry-stereochemistry-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
