import type { LessonData } from './registry'
import { mcatReproPart1Data as part1 } from './mcat-mcat-anatomy-physiology-reproductive-mcat-part1'
import { mcatReproPart2Data as part2 } from './mcat-mcat-anatomy-physiology-reproductive-mcat-part2'
import { mcatReproPart3Data as part3 } from './mcat-mcat-anatomy-physiology-reproductive-mcat-part3'
import { mcatReproPart4Data as part4 } from './mcat-mcat-anatomy-physiology-reproductive-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
