import type { LessonData } from './registry'
import { mcatAntimicrobialsPart1Data as part1 } from './mcat-mcat-microbiology-antimicrobials-mcat-part1'
import { mcatAntimicrobialsPart2Data as part2 } from './mcat-mcat-microbiology-antimicrobials-mcat-part2'
import { mcatAntimicrobialsPart3Data as part3 } from './mcat-mcat-microbiology-antimicrobials-mcat-part3'
import { mcatAntimicrobialsPart4Data as part4 } from './mcat-mcat-microbiology-antimicrobials-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
