import type { LessonData } from './registry'
import { mcatSocioCulturePart1Data as part1 } from './mcat-mcat-sociology-culture-socialization-mcat-part1'
import { mcatSocioCulturePart2Data as part2 } from './mcat-mcat-sociology-culture-socialization-mcat-part2'
import { mcatSocioCulturePart3Data as part3 } from './mcat-mcat-sociology-culture-socialization-mcat-part3'
import { mcatSocioCulturePart4Data as part4 } from './mcat-mcat-sociology-culture-socialization-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
