import type { LessonData } from './registry'
import { electrochemistryMcatPart1 as part1 } from './mcat-mcat-physics-electricity-electrochemistry-mcat-part1'
import { electrochemistryMcatPart2 as part2 } from './mcat-mcat-physics-electricity-electrochemistry-mcat-part2'
import { electrochemistryMcatPart3 as part3 } from './mcat-mcat-physics-electricity-electrochemistry-mcat-part3'
import { electrochemistryMcatPart4 as part4 } from './mcat-mcat-physics-electricity-electrochemistry-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
