import type { LessonData } from './registry'
import { mcatAminoAcidsPart1Data as part1 } from './mcat-mcat-biochemistry-amino-acids-proteins-mcat-part1'
import { mcatAminoAcidsPart2Data as part2 } from './mcat-mcat-biochemistry-amino-acids-proteins-mcat-part2'
import { mcatAminoAcidsPart3Data as part3 } from './mcat-mcat-biochemistry-amino-acids-proteins-mcat-part3'
import { mcatAminoAcidsPart4Data as part4 } from './mcat-mcat-biochemistry-amino-acids-proteins-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
