import type { LessonData } from './registry'
import { mcatMechWorkPart1Data as part1 } from './mcat-mcat-physics-mechanics-work-energy-power-mcat-part1'
import { mcatMechWorkPart2Data as part2 } from './mcat-mcat-physics-mechanics-work-energy-power-mcat-part2'
import { mcatMechWorkPart3Data as part3 } from './mcat-mcat-physics-mechanics-work-energy-power-mcat-part3'
import { mcatMechWorkPart4Data as part4 } from './mcat-mcat-physics-mechanics-work-energy-power-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
