import type { LessonData } from './registry'
import { mcatBacteriaPart1Data as part1 } from './mcat-mcat-microbiology-bacteria-mcat-part1'
import { mcatBacteriaPart2Data as part2 } from './mcat-mcat-microbiology-bacteria-mcat-part2'
import { mcatBacteriaPart3Data as part3 } from './mcat-mcat-microbiology-bacteria-mcat-part3'
import { mcatBacteriaPart4Data as part4 } from './mcat-mcat-microbiology-bacteria-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
