import type { LessonData } from './registry'
import { mcatCellOrganellesPart1Data as part1 } from './mcat-mcat-cell-biology-organelles-mcat-part1'
import { mcatCellOrganellesPart2Data as part2 } from './mcat-mcat-cell-biology-organelles-mcat-part2'
import { mcatCellOrganellesPart3Data as part3 } from './mcat-mcat-cell-biology-organelles-mcat-part3'
import { mcatCellOrganellesPart4Data as part4 } from './mcat-mcat-cell-biology-organelles-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
