import type { LessonData } from './registry'
import { mcatPsychLearnMemPart1Data as part1 } from './mcat-mcat-psychology-behavior-learning-memory-mcat-part1'
import { mcatPsychLearnMemPart2Data as part2 } from './mcat-mcat-psychology-behavior-learning-memory-mcat-part2'
import { mcatPsychLearnMemPart3Data as part3 } from './mcat-mcat-psychology-behavior-learning-memory-mcat-part3'
import { mcatPsychLearnMemPart4Data as part4 } from './mcat-mcat-psychology-behavior-learning-memory-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
