import type { LessonData } from './registry'
import { mcatMechForcesPart1Data as part1 } from './mcat-mcat-physics-mechanics-forces-newton-laws-mcat-part1'
import { mcatMechForcesPart2Data as part2 } from './mcat-mcat-physics-mechanics-forces-newton-laws-mcat-part2'
import { mcatMechForcesPart3Data as part3 } from './mcat-mcat-physics-mechanics-forces-newton-laws-mcat-part3'
import { mcatMechForcesPart4Data as part4 } from './mcat-mcat-physics-mechanics-forces-newton-laws-mcat-part4'

/**
 * AUTO-GENERATED by scripts/gen-mcat-lesson-aggregators.cjs.
 * Do not edit by hand — edit the part files and re-run the generator.
 */
export const parts: LessonData[] = [part1, part2, part3, part4]
