#!/usr/bin/env python3
"""Add ~75 new AP Physics 2 questions to reach ~300 total."""

import pathlib

FILE = pathlib.Path(__file__).resolve().parent.parent / "src" / "data" / "exit-quizzes" / "ap-physics-2.ts"

NEW_QUESTIONS = r"""
  // ══════════════════════════════════════════════════════════════════
  //  NEW BATCH — ADDITIONAL QUESTIONS (~75) to reach ~300
  // ══════════════════════════════════════════════════════════════════

  // ── CIRCUITS (15 more) ──

  { question: 'Three resistors of 6 Ω each in parallel have an equivalent resistance of:', options: ['18 Ω', '2 Ω', '6 Ω', '3 Ω'], correctAnswer: 1, explanation: '$1/R_{eq} = 1/6 + 1/6 + 1/6 = 3/6 = 1/2$, so $R_{eq} = 2$ Ω.', difficulty: 'easy', domain: 'circuits', topicSlug: 'dc-circuits', formSet: 'both' },
  { question: 'In a series circuit, the current through each component is:', options: ['Different', 'The same', 'Zero', 'Proportional to resistance'], correctAnswer: 1, explanation: 'In series, the same current flows through all components.', difficulty: 'easy', domain: 'circuits', topicSlug: 'dc-circuits', formSet: 'both' },
  { question: 'The time constant of an RC circuit is τ = RC. For R = 10 kΩ and C = 100 μF, τ =', options: ['0.001 s', '0.01 s', '0.1 s', '1 s'], correctAnswer: 3, explanation: '$\\tau = RC = 10000 \\times 100 \\times 10^{-6} = 1$ s.', difficulty: 'medium', domain: 'circuits', topicSlug: 'rc-circuits', formSet: 'both' },
  { question: 'In an RC charging circuit, the voltage across the capacitor at $t = \\tau$ is approximately:', options: ['37% of max', '50% of max', '63% of max', '86% of max'], correctAnswer: 2, explanation: '$V_C(\\tau) = V_0(1 - e^{-1}) \\approx 0.632 V_0$, about 63%.', difficulty: 'medium', domain: 'circuits', topicSlug: 'rc-circuits', formSet: 'both' },
  { question: 'Kirchhoff\'s junction rule is based on conservation of:', options: ['Energy', 'Charge', 'Momentum', 'Power'], correctAnswer: 1, explanation: 'The junction rule states that current in = current out, which is conservation of charge.', difficulty: 'easy', domain: 'circuits', topicSlug: 'dc-circuits', formSet: 'both' },
  { question: 'A 12 V battery drives 2 A through a circuit. Total resistance is:', options: ['6 Ω', '10 Ω', '14 Ω', '24 Ω'], correctAnswer: 0, explanation: '$R = V/I = 12/2 = 6$ Ω.', difficulty: 'easy', domain: 'circuits', topicSlug: 'dc-circuits', formSet: 'both' },
  { question: 'Power dissipated by a 100 Ω resistor carrying 0.5 A:', options: ['25 W', '50 W', '12.5 W', '5 W'], correctAnswer: 0, explanation: '$P = I^2 R = (0.5)^2(100) = 25$ W.', difficulty: 'medium', domain: 'circuits', topicSlug: 'dc-circuits', formSet: 'both' },
  { question: 'After a discharging RC circuit has run for $5\\tau$, the voltage across the capacitor is approximately:', options: ['37% of initial', '5% of initial', '1% of initial', 'Nearly zero (< 1%)'], correctAnswer: 3, explanation: '$V = V_0 e^{-5} \\approx 0.0067 V_0$, less than 1%, effectively zero.', difficulty: 'medium', domain: 'circuits', topicSlug: 'rc-circuits', formSet: 'both' },
  { question: 'In parallel, the voltage across each branch is:', options: ['Different', 'The same', 'Zero', 'Inversely proportional to resistance'], correctAnswer: 1, explanation: 'In parallel, all branches share the same voltage.', difficulty: 'easy', domain: 'circuits', topicSlug: 'dc-circuits', formSet: 'both' },
  { question: 'Kirchhoff\'s loop rule is based on conservation of:', options: ['Charge', 'Energy', 'Mass', 'Current'], correctAnswer: 1, explanation: 'The loop rule says the sum of voltage changes around a closed loop is zero — conservation of energy.', difficulty: 'easy', domain: 'circuits', topicSlug: 'dc-circuits', formSet: 'both' },
  { question: 'The energy stored in a capacitor is:', options: ['$\\frac{1}{2}CV^2$', '$CV$', '$\\frac{1}{2}C^2V$', '$CV^2$'], correctAnswer: 0, explanation: '$U = \\frac{1}{2}CV^2 = \\frac{Q^2}{2C} = \\frac{1}{2}QV$.', difficulty: 'easy', domain: 'circuits', topicSlug: 'capacitance', formSet: 'both' },
  { question: 'Two capacitors C₁ = 4 μF and C₂ = 6 μF in series have equivalent capacitance:', options: ['10 μF', '2.4 μF', '24 μF', '1.5 μF'], correctAnswer: 1, explanation: '$1/C_{eq} = 1/4 + 1/6 = 5/12$, so $C_{eq} = 12/5 = 2.4$ μF.', difficulty: 'medium', domain: 'circuits', topicSlug: 'capacitance', formSet: 'both' },
  { question: 'An ammeter must have _____ internal resistance to not disturb the circuit:', options: ['Very high', 'Very low', 'Exactly 1 Ω', 'Infinite'], correctAnswer: 1, explanation: 'Ammeters are placed in series and must have very low resistance to avoid changing the current.', difficulty: 'easy', domain: 'circuits', topicSlug: 'dc-circuits', formSet: 'both' },
  { question: 'A voltmeter must have _____ internal resistance:', options: ['Very low', 'Very high', 'Equal to the load', 'Zero'], correctAnswer: 1, explanation: 'Voltmeters are placed in parallel and must have very high resistance to draw negligible current.', difficulty: 'easy', domain: 'circuits', topicSlug: 'dc-circuits', formSet: 'both' },
  { question: 'In a discharging RC circuit, the current at time t is:', options: ['$I_0 e^{-t/RC}$', '$I_0(1 - e^{-t/RC})$', '$I_0 t/RC$', '$I_0 \\ln(t/RC)$'], correctAnswer: 0, explanation: 'Discharging current decays exponentially: $I = I_0 e^{-t/RC}$.', difficulty: 'medium', domain: 'circuits', topicSlug: 'rc-circuits', formSet: 'both' },

  // ── OPTICS (12 more) ──

  { question: 'Total internal reflection occurs when light travels from a _____ medium to a _____ medium at an angle greater than the critical angle.', options: ['Less dense to more dense', 'More optically dense to less optically dense', 'Vacuum to glass', 'Any two media'], correctAnswer: 1, explanation: 'Total internal reflection occurs when light goes from higher index to lower index at an angle exceeding the critical angle.', difficulty: 'easy', domain: 'optics', topicSlug: 'geometric-optics', formSet: 'both' },
  { question: 'For a thin converging lens, if the object is at 2f, the image is:', options: ['At f, magnified', 'At 2f, same size, inverted', 'At infinity', 'Virtual, upright'], correctAnswer: 1, explanation: 'Object at 2f → image at 2f, real, inverted, same size.', difficulty: 'medium', domain: 'optics', topicSlug: 'geometric-optics', formSet: 'both' },
  { question: 'In single-slit diffraction, the central maximum is _____ the secondary maxima.', options: ['The same width as', 'Half the width of', 'Twice the width of', 'The same intensity as'], correctAnswer: 2, explanation: 'The central maximum in single-slit diffraction is twice as wide as the secondary maxima.', difficulty: 'medium', domain: 'optics', topicSlug: 'wave-optics', formSet: 'both' },
  { question: 'Young\'s double-slit experiment demonstrates that light:', options: ['Is a particle', 'Travels in straight lines only', 'Has wave properties (interference)', 'Cannot be diffracted'], correctAnswer: 2, explanation: 'Double-slit interference patterns prove the wave nature of light.', difficulty: 'easy', domain: 'optics', topicSlug: 'wave-optics', formSet: 'both' },
  { question: 'The index of refraction of a vacuum is:', options: ['0', '0.5', '1.0', '1.5'], correctAnswer: 2, explanation: 'By definition, the index of refraction of a vacuum is exactly 1.', difficulty: 'easy', domain: 'optics', topicSlug: 'geometric-optics', formSet: 'both' },
  { question: 'Increasing the number of slits in a diffraction grating:', options: ['Makes maxima broader', 'Makes maxima sharper and brighter', 'Eliminates interference', 'Changes the wavelength'], correctAnswer: 1, explanation: 'More slits produce sharper, more defined maxima with increased peak intensity.', difficulty: 'medium', domain: 'optics', topicSlug: 'wave-optics', formSet: 'both' },
  { question: 'A convex mirror always produces images that are:', options: ['Real and inverted', 'Virtual, upright, and reduced', 'Virtual and magnified', 'Real and magnified'], correctAnswer: 1, explanation: 'Convex mirrors always produce virtual, upright, and reduced images.', difficulty: 'easy', domain: 'optics', topicSlug: 'geometric-optics', formSet: 'both' },
  { question: 'For destructive interference in Young\'s experiment, the path difference must be:', options: ['mλ', '(m + ½)λ', '2mλ', 'mλ/2'], correctAnswer: 1, explanation: 'Destructive interference: path difference = (m + ½)λ, m = 0, 1, 2, ...', difficulty: 'medium', domain: 'optics', topicSlug: 'wave-optics', formSet: 'both' },
  { question: 'The critical angle for total internal reflection depends on:', options: ['The color of light only', 'The ratio of refractive indices', 'The size of the boundary', 'The thickness of the medium'], correctAnswer: 1, explanation: '$\\sin \\theta_c = n_2/n_1$; it depends on the ratio of refractive indices.', difficulty: 'medium', domain: 'optics', topicSlug: 'geometric-optics', formSet: 'both' },
  { question: 'A virtual image:', options: ['Can be projected on a screen', 'Cannot be projected on a screen', 'Is always inverted', 'Is formed only by concave mirrors'], correctAnswer: 1, explanation: 'Virtual images are formed where rays appear to diverge from; they cannot be projected on a screen.', difficulty: 'easy', domain: 'optics', topicSlug: 'geometric-optics', formSet: 'both' },
  { question: 'Thin film interference produces colorful patterns because:', options: ['Light is absorbed at different rates', 'Different wavelengths have different path length conditions for constructive interference', 'The film acts as a prism', 'Only one wavelength is transmitted'], correctAnswer: 1, explanation: 'Different wavelengths meet constructive/destructive interference conditions at different thicknesses, producing colors.', difficulty: 'medium', domain: 'optics', topicSlug: 'wave-optics', formSet: 'both' },
  { question: 'The magnification equation for a mirror/lens is m = −d_i/d_o. If m = −2, the image is:', options: ['Virtual, half size', 'Real, inverted, twice as tall', 'Virtual, twice as tall', 'Real, upright, twice as tall'], correctAnswer: 1, explanation: 'Negative m means inverted (real image). |m| = 2 means twice the size.', difficulty: 'medium', domain: 'optics', topicSlug: 'geometric-optics', formSet: 'both' },

  // ── MAGNETISM (12 more) ──

  { question: 'A moving charge in a magnetic field experiences a force that is:', options: ['Parallel to its velocity', 'Parallel to the field', 'Perpendicular to both v and B', 'In the direction of the field'], correctAnswer: 2, explanation: '$\\vec{F} = q\\vec{v} \\times \\vec{B}$ — the force is perpendicular to both velocity and field.', difficulty: 'easy', domain: 'magnetism', topicSlug: 'magnetic-fields', formSet: 'both' },
  { question: 'A charged particle moves parallel to a magnetic field. The magnetic force on it is:', options: ['Maximum', 'qvB', 'Zero', 'Proportional to charge only'], correctAnswer: 2, explanation: '$F = qvB\\sin\\theta$; when $\\theta = 0°$ (parallel), $\\sin 0° = 0$, so F = 0.', difficulty: 'easy', domain: 'magnetism', topicSlug: 'magnetic-fields', formSet: 'both' },
  { question: 'Faraday\'s law states that the induced EMF is proportional to the rate of change of:', options: ['Electric field', 'Magnetic flux', 'Current', 'Resistance'], correctAnswer: 1, explanation: '$\\mathcal{E} = -d\\Phi_B/dt$ — EMF equals the rate of change of magnetic flux.', difficulty: 'easy', domain: 'magnetism', topicSlug: 'electromagnetic-induction', formSet: 'both' },
  { question: 'Lenz\'s law states that the direction of induced current:', options: ['Enhances the change in flux', 'Opposes the change in flux that caused it', 'Is always clockwise', 'Depends on the resistance'], correctAnswer: 1, explanation: 'Lenz\'s law: induced current opposes the change in flux — this is the meaning of the negative sign in Faraday\'s law.', difficulty: 'easy', domain: 'magnetism', topicSlug: 'electromagnetic-induction', formSet: 'both' },
  { question: 'The magnetic force on a current-carrying wire of length L in field B is:', options: ['$F = qvB$', '$F = BIL\\sin\\theta$', '$F = BIL\\cos\\theta$', '$F = B/IL$'], correctAnswer: 1, explanation: '$F = BIL\\sin\\theta$, where $\\theta$ is the angle between the wire and the field.', difficulty: 'medium', domain: 'magnetism', topicSlug: 'magnetic-fields', formSet: 'both' },
  { question: 'A solenoid produces a magnetic field that is approximately:', options: ['Radial', 'Uniform inside, weak outside', 'Zero inside', 'Stronger at ends than center'], correctAnswer: 1, explanation: 'A solenoid creates a nearly uniform field inside and a very weak field outside.', difficulty: 'easy', domain: 'magnetism', topicSlug: 'magnetic-fields', formSet: 'both' },
  { question: 'The magnetic flux through a surface is $\\Phi_B = BA\\cos\\theta$. If B is perpendicular to the surface, $\\theta =$:', options: ['0°', '45°', '90°', '180°'], correctAnswer: 0, explanation: 'When B is perpendicular to the surface, the angle between B and the normal is 0°, giving max flux.', difficulty: 'easy', domain: 'magnetism', topicSlug: 'electromagnetic-induction', formSet: 'both' },
  { question: 'A charged particle in a uniform magnetic field moves in a:', options: ['Straight line', 'Parabola', 'Circle (or helix)', 'Ellipse'], correctAnswer: 2, explanation: 'The magnetic force is always perpendicular to velocity, producing circular (or helical) motion.', difficulty: 'easy', domain: 'magnetism', topicSlug: 'magnetic-fields', formSet: 'both' },
  { question: 'The radius of a charged particle\'s circular path in a magnetic field is $r = mv/(qB)$. Doubling the speed:', options: ['Halves the radius', 'Doubles the radius', 'Quadruples the radius', 'Does not change the radius'], correctAnswer: 1, explanation: '$r = mv/(qB)$; doubling v doubles r.', difficulty: 'medium', domain: 'magnetism', topicSlug: 'magnetic-fields', formSet: 'both' },
  { question: 'An EMF is induced in a loop when:', options: ['A constant magnetic field passes through it', 'The magnetic flux through it changes', 'The loop is stationary in a uniform field', 'The loop has high resistance'], correctAnswer: 1, explanation: 'By Faraday\'s law, EMF is induced only when the magnetic flux through the loop changes.', difficulty: 'easy', domain: 'magnetism', topicSlug: 'electromagnetic-induction', formSet: 'both' },
  { question: 'A transformer has 100 primary turns and 500 secondary turns. If the primary voltage is 120 V, the secondary voltage is:', options: ['24 V', '120 V', '600 V', '60000 V'], correctAnswer: 2, explanation: '$V_s/V_p = N_s/N_p \\Rightarrow V_s = 120 \\times 500/100 = 600$ V.', difficulty: 'medium', domain: 'magnetism', topicSlug: 'electromagnetic-induction', formSet: 'both' },
  { question: 'The magnetic field inside a solenoid with n turns per unit length is:', options: ['$B = \\mu_0 nI$', '$B = \\mu_0 I/n$', '$B = \\mu_0 n/I$', '$B = nI$'], correctAnswer: 0, explanation: '$B = \\mu_0 n I$ inside a long solenoid.', difficulty: 'medium', domain: 'magnetism', topicSlug: 'magnetic-fields', formSet: 'both' },

  // ── ELECTRICITY (12 more) ──

  { question: 'The electric field between two large parallel plates with voltage V and separation d is:', options: ['$E = Vd$', '$E = V/d$', '$E = d/V$', '$E = V^2/d$'], correctAnswer: 1, explanation: 'For parallel plates: $E = V/d$, uniform between the plates.', difficulty: 'easy', domain: 'electricity', topicSlug: 'electric-fields', formSet: 'both' },
  { question: 'Two charges of +2 μC and −2 μC separated by 0.1 m form a:', options: ['Monopole', 'Dipole', 'Quadrupole', 'Null charge configuration'], correctAnswer: 1, explanation: 'Equal and opposite charges separated by a distance form an electric dipole.', difficulty: 'easy', domain: 'electricity', topicSlug: 'electric-charge-and-force', formSet: 'both' },
  { question: 'The work done by an electric field moving a charge q through potential difference ΔV is:', options: ['$W = qV$', '$W = q\\Delta V$', '$W = q/\\Delta V$', '$W = \\Delta V/q$'], correctAnswer: 1, explanation: '$W = q\\Delta V$ — work equals charge times change in potential.', difficulty: 'easy', domain: 'electricity', topicSlug: 'electric-potential', formSet: 'both' },
  { question: 'Electric field lines point:', options: ['From negative to positive', 'From positive to negative', 'In circles around charges', 'Randomly'], correctAnswer: 1, explanation: 'By convention, electric field lines point from positive charges to negative charges.', difficulty: 'easy', domain: 'electricity', topicSlug: 'electric-fields', formSet: 'both' },
  { question: 'The capacitance of a parallel-plate capacitor with area A and separation d is:', options: ['$C = \\epsilon_0 A/d$', '$C = \\epsilon_0 d/A$', '$C = A d/\\epsilon_0$', '$C = \\epsilon_0/(Ad)$'], correctAnswer: 0, explanation: '$C = \\epsilon_0 A / d$ for a parallel-plate capacitor.', difficulty: 'medium', domain: 'electricity', topicSlug: 'capacitance', formSet: 'both' },
  { question: 'Inserting a dielectric into a capacitor:', options: ['Decreases capacitance', 'Increases capacitance', 'Has no effect', 'Increases voltage'], correctAnswer: 1, explanation: 'A dielectric increases capacitance by a factor of κ (dielectric constant): $C = \\kappa C_0$.', difficulty: 'medium', domain: 'electricity', topicSlug: 'capacitance', formSet: 'both' },
  { question: 'The superposition principle for electric fields states:', options: ['Fields cancel completely', 'The net field is the vector sum of all individual fields', 'Only the strongest field matters', 'Fields add as scalars'], correctAnswer: 1, explanation: 'The total electric field at a point is the vector sum of the fields from each individual charge.', difficulty: 'easy', domain: 'electricity', topicSlug: 'electric-fields', formSet: 'both' },
  { question: 'An equipotential surface is always _____ to the electric field lines.', options: ['Parallel', 'Perpendicular', 'At 45°', 'Tangent'], correctAnswer: 1, explanation: 'Equipotential surfaces are perpendicular to electric field lines — no work is done moving a charge along an equipotential.', difficulty: 'easy', domain: 'electricity', topicSlug: 'electric-potential', formSet: 'both' },
  { question: 'The electric potential at distance r from a point charge q is:', options: ['$V = kq/r$', '$V = kq/r^2$', '$V = kqr$', '$V = kq^2/r$'], correctAnswer: 0, explanation: '$V = kq/r$ — potential falls off as 1/r from a point charge.', difficulty: 'easy', domain: 'electricity', topicSlug: 'electric-potential', formSet: 'both' },
  { question: 'If the distance between two point charges is tripled, the electric force between them:', options: ['Triples', 'Is reduced to 1/3', 'Is reduced to 1/9', 'Is reduced to 1/27'], correctAnswer: 2, explanation: '$F = kq_1q_2/r^2$; tripling r gives $F/(3^2) = F/9$.', difficulty: 'easy', domain: 'electricity', topicSlug: 'electric-charge-and-force', formSet: 'both' },
  { question: 'Gauss\'s law relates the electric flux through a closed surface to:', options: ['The magnetic field inside', 'The enclosed charge', 'The surface area only', 'The potential'], correctAnswer: 1, explanation: 'Gauss\'s law: $\\oint \\vec{E} \\cdot d\\vec{A} = Q_{enc}/\\epsilon_0$.', difficulty: 'medium', domain: 'electricity', topicSlug: 'electric-fields', formSet: 'both' },
  { question: 'Two capacitors C₁ = 3 μF and C₂ = 6 μF in parallel have equivalent capacitance:', options: ['2 μF', '9 μF', '18 μF', '4.5 μF'], correctAnswer: 1, explanation: 'In parallel: $C_{eq} = C_1 + C_2 = 3 + 6 = 9$ μF.', difficulty: 'easy', domain: 'electricity', topicSlug: 'capacitance', formSet: 'both' },

  // ── THERMODYNAMICS (8 more) ──

  { question: 'In an isothermal process for an ideal gas:', options: ['Temperature changes', 'ΔU = 0 and Q = W', 'No heat is exchanged', 'Volume is constant'], correctAnswer: 1, explanation: 'Isothermal: constant T → ΔU = 0 for ideal gas → Q = W (first law).', difficulty: 'medium', domain: 'thermodynamics', topicSlug: 'thermodynamic-laws', formSet: 'both' },
  { question: 'The efficiency of a Carnot engine operating between 600 K (hot) and 300 K (cold) is:', options: ['25%', '50%', '75%', '100%'], correctAnswer: 1, explanation: '$\\eta = 1 - T_C/T_H = 1 - 300/600 = 0.50 = 50\\%$.', difficulty: 'medium', domain: 'thermodynamics', topicSlug: 'thermodynamic-laws', formSet: 'both' },
  { question: 'Heat always flows spontaneously from:', options: ['Cold to hot objects', 'Hot to cold objects', 'Low pressure to high pressure', 'Any direction equally'], correctAnswer: 1, explanation: 'The second law of thermodynamics: heat spontaneously flows from hot to cold.', difficulty: 'easy', domain: 'thermodynamics', topicSlug: 'temperature-and-heat', formSet: 'both' },
  { question: 'Specific heat capacity c is defined as the heat needed to raise the temperature of _____ of a substance by 1 K:', options: ['1 mole', '1 gram', '1 unit mass (kg)', '1 liter'], correctAnswer: 2, explanation: '$Q = mc\\Delta T$; c is heat per unit mass per unit temperature change.', difficulty: 'easy', domain: 'thermodynamics', topicSlug: 'temperature-and-heat', formSet: 'both' },
  { question: 'In an adiabatic process:', options: ['Q = 0', 'W = 0', 'ΔU = 0', 'ΔT = 0'], correctAnswer: 0, explanation: 'Adiabatic: no heat exchange with surroundings (Q = 0). ΔU = −W.', difficulty: 'easy', domain: 'thermodynamics', topicSlug: 'thermodynamic-laws', formSet: 'both' },
  { question: 'The rms speed of gas molecules is proportional to:', options: ['$\\sqrt{T}$', '$T$', '$T^2$', '$1/T$'], correctAnswer: 0, explanation: '$v_{rms} = \\sqrt{3kT/m}$, proportional to $\\sqrt{T}$.', difficulty: 'medium', domain: 'thermodynamics', topicSlug: 'kinetic-theory', formSet: 'both' },
  { question: 'Entropy of an isolated system:', options: ['Always decreases', 'Can increase or stay the same, never decrease', 'Always stays constant', 'Depends on temperature only'], correctAnswer: 1, explanation: 'Second law: entropy of an isolated system never decreases; it increases or stays the same.', difficulty: 'medium', domain: 'thermodynamics', topicSlug: 'thermodynamic-laws', formSet: 'both' },
  { question: 'Which has higher average kinetic energy: He at 300 K or O₂ at 300 K?', options: ['He', 'O₂', 'Both are the same', 'Cannot determine'], correctAnswer: 2, explanation: 'Average KE depends only on temperature: $KE_{avg} = \\frac{3}{2}kT$. Same T → same KE.', difficulty: 'medium', domain: 'thermodynamics', topicSlug: 'kinetic-theory', formSet: 'both' },

  // ── MODERN PHYSICS (8 more) ──

  { question: 'The photoelectric effect demonstrates that light:', options: ['Is a wave only', 'Has particle properties (photons)', 'Cannot eject electrons', 'Follows Snell\'s law'], correctAnswer: 1, explanation: 'The photoelectric effect showed light delivers energy in discrete quanta (photons), demonstrating particle nature.', difficulty: 'easy', domain: 'modern-physics', topicSlug: 'quantum-mechanics', formSet: 'both' },
  { question: 'The de Broglie wavelength of a particle is $\\lambda = h/p$. A faster particle has:', options: ['A longer wavelength', 'A shorter wavelength', 'The same wavelength', 'No wavelength'], correctAnswer: 1, explanation: '$\\lambda = h/(mv)$; greater v means larger p and shorter λ.', difficulty: 'easy', domain: 'modern-physics', topicSlug: 'quantum-mechanics', formSet: 'both' },
  { question: 'In alpha decay, the atomic number decreases by:', options: ['1', '2', '4', '0'], correctAnswer: 1, explanation: 'An alpha particle is ⁴₂He: mass number decreases by 4, atomic number by 2.', difficulty: 'easy', domain: 'modern-physics', topicSlug: 'nuclear-physics', formSet: 'both' },
  { question: 'Half-life is the time for _____ of a radioactive sample to decay:', options: ['All', 'Three quarters', 'Half', 'One quarter'], correctAnswer: 2, explanation: 'Half-life: the time for half the radioactive nuclei to decay.', difficulty: 'easy', domain: 'modern-physics', topicSlug: 'nuclear-physics', formSet: 'both' },
  { question: 'After 3 half-lives, what fraction of the original sample remains?', options: ['1/3', '1/6', '1/8', '1/4'], correctAnswer: 2, explanation: 'After n half-lives, fraction remaining = $(1/2)^n = (1/2)^3 = 1/8$.', difficulty: 'easy', domain: 'modern-physics', topicSlug: 'nuclear-physics', formSet: 'both' },
  { question: 'E = mc² implies that mass and energy are:', options: ['Unrelated', 'Equivalent — mass can be converted to energy', 'Only related in chemistry', 'Equal in all units'], correctAnswer: 1, explanation: 'Einstein\'s mass-energy equivalence: mass and energy are interconvertible.', difficulty: 'easy', domain: 'modern-physics', topicSlug: 'nuclear-physics', formSet: 'both' },
  { question: 'The Heisenberg uncertainty principle states that we cannot simultaneously know both:', options: ['Mass and charge', 'Position and momentum with arbitrary precision', 'Speed and direction', 'Energy and charge'], correctAnswer: 1, explanation: '$\\Delta x \\cdot \\Delta p \\geq \\hbar/2$ — there is a fundamental limit on knowing both position and momentum.', difficulty: 'medium', domain: 'modern-physics', topicSlug: 'quantum-mechanics', formSet: 'both' },
  { question: 'The Bohr model correctly predicts the energy levels of:', options: ['All atoms', 'Multi-electron atoms', 'Hydrogen-like atoms only', 'Molecules only'], correctAnswer: 2, explanation: 'The Bohr model works well for hydrogen and hydrogen-like ions (one electron) but fails for multi-electron atoms.', difficulty: 'medium', domain: 'modern-physics', topicSlug: 'atomic-structure', formSet: 'both' },

  // ── FLUIDS (8 more) ──

  { question: 'Bernoulli\'s equation relates pressure, velocity, and height for:', options: ['Compressible fluids', 'Ideal (incompressible, non-viscous) fluids in streamline flow', 'Turbulent flow only', 'Viscous fluids only'], correctAnswer: 1, explanation: 'Bernoulli\'s equation applies to ideal (incompressible, non-viscous) fluids in steady, streamline flow.', difficulty: 'easy', domain: 'fluids', topicSlug: 'fluid-dynamics', formSet: 'both' },
  { question: 'The continuity equation $A_1 v_1 = A_2 v_2$ expresses conservation of:', options: ['Energy', 'Mass (for incompressible flow)', 'Momentum', 'Pressure'], correctAnswer: 1, explanation: 'The continuity equation is conservation of mass for incompressible fluids: what flows in must flow out.', difficulty: 'easy', domain: 'fluids', topicSlug: 'fluid-dynamics', formSet: 'both' },
  { question: 'In a venturi tube, where the cross-sectional area decreases, the fluid velocity _____ and the pressure _____:', options: ['Increases, increases', 'Decreases, decreases', 'Increases, decreases', 'Decreases, increases'], correctAnswer: 2, explanation: 'By continuity, smaller area → faster flow. By Bernoulli\'s principle, faster flow → lower pressure.', difficulty: 'medium', domain: 'fluids', topicSlug: 'fluid-dynamics', formSet: 'both' },
  { question: 'Gauge pressure differs from absolute pressure by:', options: ['A factor of 2', 'The atmospheric pressure', 'The fluid density', 'The temperature'], correctAnswer: 1, explanation: 'Absolute pressure = Gauge pressure + Atmospheric pressure.', difficulty: 'easy', domain: 'fluids', topicSlug: 'fluid-pressure', formSet: 'both' },
  { question: 'A manometer measures:', options: ['Temperature', 'Pressure difference', 'Flow rate', 'Viscosity'], correctAnswer: 1, explanation: 'A manometer measures the difference in pressure between two points using a column of fluid.', difficulty: 'easy', domain: 'fluids', topicSlug: 'fluid-pressure', formSet: 'both' },
  { question: 'An object with density 800 kg/m³ in water (1000 kg/m³) will:', options: ['Sink', 'Float with 80% submerged', 'Float with 20% submerged', 'Remain suspended at any depth'], correctAnswer: 1, explanation: 'Fraction submerged = ρ_obj/ρ_fluid = 800/1000 = 0.8, so 80% submerged.', difficulty: 'medium', domain: 'fluids', topicSlug: 'buoyancy', formSet: 'both' },
  { question: 'Water flows through a pipe at 2 m/s in a section of area 0.1 m². In a section of area 0.05 m², the speed is:', options: ['1 m/s', '2 m/s', '4 m/s', '8 m/s'], correctAnswer: 2, explanation: '$A_1v_1 = A_2v_2 \\Rightarrow v_2 = 0.1(2)/0.05 = 4$ m/s.', difficulty: 'easy', domain: 'fluids', topicSlug: 'fluid-dynamics', formSet: 'both' },
  { question: 'Torricelli\'s theorem gives the speed of fluid leaving a hole at depth h as:', options: ['$v = gh$', '$v = \\sqrt{2gh}$', '$v = 2gh$', '$v = \\sqrt{gh}$'], correctAnswer: 1, explanation: '$v = \\sqrt{2gh}$ — same as free-fall speed from height h.', difficulty: 'medium', domain: 'fluids', topicSlug: 'fluid-dynamics', formSet: 'both' },
"""

text = FILE.read_text()
marker = "]\n\n/* ------------------------------------------------------------------ */\n/*  Generator function"
if marker not in text:
    # Try alternate marker
    marker = "]\n\n/* --------"
    if marker not in text:
        print("ERROR: marker not found")
        exit(1)

new_text = text.replace(marker, NEW_QUESTIONS + marker)
FILE.write_text(new_text)
print("Done. Questions inserted.")
