/**
 * Compiles agent-authored 700-800 SAT items (scratchpad JSON) into
 * src/data/exit-quizzes/sat-hard-tier.ts.
 *
 * Every item is gated first: 4 unique options, valid key, KaTeX compiles,
 * no unicode super/subscripts, no bare & or % inside math, no logarithms
 * (not on the digital SAT), and no duplicate stems.
 *   npx tsx scripts/build-sat-hard-tier.ts <scratchpadDir>
 */
import fs from 'fs'
import { globSync } from 'glob'
import katex from 'katex'

interface Item { topicSlug: string; question: string; options: string[]; correctIndex: number; explanation: string }

function reject(it: Item): string | null {
  if (!it.topicSlug || !it.question || !Array.isArray(it.options)) return 'shape'
  if (it.options.length !== 4) return `options-${it.options.length}`
  if (new Set(it.options.map(o => o.trim())).size !== 4) return 'dup-options'
  if (typeof it.correctIndex !== 'number' || it.correctIndex < 0 || it.correctIndex > 3) return 'bad-key'
  if (!it.explanation || it.explanation.length < 40) return 'thin-explanation'
  const raw = [it.question, ...it.options, it.explanation].join(' ')
  if (/[⁰¹²³⁴⁵⁶⁷⁸⁹⁻ₐ-ₜ₀-₉°]/.test(raw)) return 'unicode-glyph'
  if (/\\log|\\ln\b/.test(raw)) return 'logarithm'
  // Mask ESCAPED currency dollars first. `\$50` is literal prose, not a math
  // delimiter — the render pipeline treats it that way, and a scanner that
  // doesn't will falsely reject perfectly good items (this cost 71 items on
  // the first run).
  const all = raw.replace(/\\\$/g, '\u0000CUR\u0000')
  for (const seg of all.match(/\$\$?[^$]+\$\$?/g) ?? []) {
    const inner = seg.replace(/^\$\$?|\$\$?$/g, '').replace(/\u0000CUR\u0000/g, '\\$')
    if (/(?<!\\)[&%]/.test(inner)) return 'bare-&-or-%'
    try { katex.renderToString(inner, { throwOnError: true }) } catch { return 'katex' }
  }
  return null
}

function main() {
  const dir = process.argv[2] ?? '.'
  const files = globSync(`${dir}/sathard-*.json`)
  const bySlug = new Map<string, Item[]>()
  const seen = new Set<string>()
  const rejects: Record<string, number> = {}
  let total = 0, kept = 0

  for (const f of files.sort()) {
    let items: Item[]
    try { items = JSON.parse(fs.readFileSync(f, 'utf8')) } catch { console.log('PARSE FAIL', f); continue }
    for (const it of items) {
      total++
      const stem = it.question?.trim().toLowerCase()
      const why = reject(it) ?? (seen.has(stem) ? 'dup-stem' : null)
      if (why) { rejects[why] = (rejects[why] ?? 0) + 1; continue }
      seen.add(stem)
      bySlug.set(it.topicSlug, [...(bySlug.get(it.topicSlug) ?? []), it])
      kept++
    }
  }

  const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
  let out = `import type { ExitQuizQuestion } from './sat-linear-equations-inequalities'

/**
 * 700-800 tier SAT items.
 *
 * Authored to the College Board question bank's hard tier rather than to our
 * previous "hard" label, which topped out around 500-600 (single-step recall
 * like "Solve |x| = -2"). These require 3+ linked steps, embed the math in a
 * modeled scenario, and — critically — ask for a quantity that is NOT the
 * natural end of the computation, with the intermediate value planted as the
 * lead distractor.
 *
 * Injected into the pools by exit-quizzes/index.ts, so they reach exit
 * quizzes, adaptive Module 2, slide-deck polls and diagnostics at once.
 * Generated by scripts/build-sat-hard-tier.ts — do not hand-edit.
 */
export const SAT_HARD_TIER: Record<string, ExitQuizQuestion[]> = {
`
  for (const [slug, items] of [...bySlug.entries()].sort()) {
    out += `  '${slug}': [\n`
    items.forEach((it, i) => {
      out += `    { id: '${slug}-hard-${i + 1}', question: \`${esc(it.question)}\`, options: [${it.options.map(o => `\`${esc(o)}\``).join(', ')}], correctIndex: ${it.correctIndex}, explanation: \`${esc(it.explanation)}\`, category: 'Hard Tier', difficulty: 'hard' },\n`
    })
    out += `  ],\n`
  }
  out += `}\n\nexport function hardTierFor(slug: string): ExitQuizQuestion[] {\n  return SAT_HARD_TIER[slug] ?? []\n}\n`
  fs.writeFileSync('src/data/exit-quizzes/sat-hard-tier.ts', out)

  console.log(`files: ${files.length} | items seen: ${total} | kept: ${kept} | rejected:`, rejects)
  for (const [slug, items] of [...bySlug.entries()].sort()) console.log(`  ${items.length}  ${slug}`)
}
main()
