#!/usr/bin/env python3
"""Expand AP Psychology question pool from 64 to ~300."""

import pathlib

FILE = pathlib.Path(__file__).resolve().parent.parent / "src" / "data" / "exit-quizzes" / "ap-psychology.ts"

# Build questions in multi-line format matching existing style
NEW_QS = []

def q(question, opts, correct, explanation, diff, domain, slug, form):
    esc_q = question.replace("'", "\\'")
    esc_e = explanation.replace("'", "\\'")
    opts_str = ",\n      ".join(f"'{o}'" for o in [x.replace("'", "\\'") for x in opts])
    NEW_QS.append(f"""  {{
    question: '{esc_q}',
    options: [
      {opts_str},
    ],
    correctAnswer: {correct},
    explanation: '{esc_e}',
    difficulty: '{diff}',
    domain: '{domain}',
    topicSlug: '{slug}',
    formSet: '{form}',
  }},""")

# ══════════════════════════════════════════════════════════════════
#  HISTORY & APPROACHES  (~18 new → 24 total)
# ══════════════════════════════════════════════════════════════════
q('The humanistic perspective, associated with Carl Rogers and Abraham Maslow, emphasizes:', ['Unconscious drives', 'Observable behavior', 'Personal growth and self-actualization', 'Cognitive schemas'], 2, 'Humanistic psychology focuses on free will, personal growth, and self-fulfillment.', 'easy', 'history-approaches', 'history-approaches-psychology', 'both')
q('A double-blind study is one in which:', ['Neither participants nor researchers know who is in the control group', 'Participants cannot see the materials', 'Researchers use two control groups', 'The hypothesis is tested twice'], 0, 'In double-blind studies, neither participants nor experimenters know group assignments, reducing bias.', 'medium', 'history-approaches', 'history-approaches-psychology', 'A')
q('A correlation coefficient of −0.85 indicates:', ['A weak positive relationship', 'A strong negative relationship', 'No relationship', 'A perfect positive relationship'], 1, 'A value close to −1 indicates a strong inverse relationship between variables.', 'medium', 'history-approaches', 'history-approaches-psychology', 'B')
q('The cognitive perspective focuses on:', ['How rewards shape behavior', 'Internal mental processes like thinking and memory', 'Evolutionary advantages of behavior', 'Social interactions'], 1, 'Cognitive psychology studies how people perceive, think, remember, and solve problems.', 'easy', 'history-approaches', 'history-approaches-psychology', 'A')
q('Random assignment in experiments helps:', ['Increase the sample size', 'Ensure each participant has an equal chance of being in any group', 'Create a correlation', 'Eliminate all confounding variables'], 1, 'Random assignment distributes participant characteristics evenly across groups.', 'medium', 'history-approaches', 'history-approaches-psychology', 'B')
q('Which research method allows researchers to determine cause-and-effect?', ['Case study', 'Survey', 'Experiment', 'Naturalistic observation'], 2, 'Only experiments with controlled IVs and DVs can establish causation.', 'easy', 'history-approaches', 'history-approaches-psychology', 'both')
q('The evolutionary perspective in psychology focuses on:', ['Childhood trauma', 'Natural selection and adaptive behavior', 'Brain lesions', 'Reward and punishment'], 1, 'Evolutionary psychology examines how natural selection shaped psychological traits.', 'easy', 'history-approaches', 'history-approaches-psychology', 'A')
q('A psychologist who studies how culture influences behavior is taking which approach?', ['Psychodynamic', 'Sociocultural', 'Biological', 'Behavioral'], 1, 'The sociocultural perspective examines how cultural and social factors influence behavior.', 'easy', 'history-approaches', 'history-approaches-psychology', 'B')
q('A positively skewed distribution has:', ['The tail extending to the right', 'The tail extending to the left', 'A perfectly symmetrical shape', 'No mode'], 0, 'In a positively skewed distribution, the long tail points toward higher values.', 'medium', 'history-approaches', 'history-approaches-psychology', 'A')
q('The median is preferred over the mean when:', ['Data are normally distributed', 'Data contain extreme outliers', 'The sample size is very large', 'All scores are identical'], 1, 'The median is resistant to outliers that can distort the mean.', 'medium', 'history-approaches', 'history-approaches-psychology', 'B')
q('Informed consent requires that participants:', ['Are paid for their time', 'Understand the study procedures and can withdraw at any time', 'Are experts in psychology', 'Complete all parts of the study'], 1, 'Ethical research requires voluntary participation with full disclosure of risks.', 'easy', 'history-approaches', 'history-approaches-psychology', 'both')
q('A case study is limited primarily because:', ['It takes too long', 'Results from a single subject may not generalize', 'It uses too many participants', 'It cannot gather detailed information'], 1, 'Case studies provide depth but lack generalizability due to small sample size.', 'medium', 'history-approaches', 'history-approaches-psychology', 'A')
q('Standard deviation measures:', ['Central tendency', 'The spread of scores around the mean', 'The most frequent score', 'Statistical significance'], 1, 'Standard deviation quantifies how much scores vary from the mean.', 'medium', 'history-approaches', 'history-approaches-psychology', 'B')
q('Operational definitions in research:', ['Make variables unmeasurable', 'Specify how variables will be measured', 'Eliminate the need for hypotheses', 'Only apply to case studies'], 1, 'Operational definitions define abstract concepts in concrete, measurable terms.', 'medium', 'history-approaches', 'history-approaches-psychology', 'A')
q('Confirmation bias refers to:', ['Seeking information that supports pre-existing beliefs', 'Changing hypotheses after data collection', 'Randomly assigning participants', 'Using a double-blind procedure'], 0, 'People tend to search for evidence confirming what they already believe.', 'easy', 'history-approaches', 'history-approaches-psychology', 'both')
q('A longitudinal study:', ['Tests different age groups at one time', 'Follows the same group over an extended period', 'Uses surveys only', 'Is always cross-cultural'], 1, 'Longitudinal research tracks the same participants over time.', 'medium', 'history-approaches', 'history-approaches-psychology', 'B')
q('Cross-sectional research differs from longitudinal research in that it:', ['Studies one person intensely', 'Compares different age groups at one point in time', 'Follows the same group for years', 'Uses only experiments'], 1, 'Cross-sectional designs compare groups of different ages simultaneously.', 'medium', 'history-approaches', 'history-approaches-psychology', 'A')
q('The placebo effect occurs when:', ['A drug works as intended', 'Participants improve because they believe they received treatment', 'Researchers change the hypothesis', 'A control group is not used'], 1, 'Belief in receiving treatment can produce real improvements even without active treatment.', 'easy', 'history-approaches', 'history-approaches-psychology', 'both')

# ══════════════════════════════════════════════════════════════════
#  BIOLOGICAL BASES  (~18 new → 25 total)
# ══════════════════════════════════════════════════════════════════
q('The all-or-none principle means that a neuron:', ['Fires at varying intensities', 'Either fires at full strength or does not fire at all', 'Only fires during sleep', 'Uses only one neurotransmitter'], 1, 'Action potentials are all-or-none; they either reach threshold and fire fully, or not at all.', 'medium', 'biological-bases', 'biological-bases-brain', 'A')
q('Broca area damage typically results in:', ['Inability to understand language', 'Inability to produce fluent speech', 'Loss of vision', 'Memory loss'], 1, "Broca's area controls speech production; damage causes non-fluent (expressive) aphasia.", 'medium', 'biological-bases', 'biological-bases-brain', 'B')
q('Wernicke area damage typically results in:', ['Loss of motor control', 'Fluent but meaningless speech', 'Blindness', 'Hearing loss'], 1, "Wernicke's area processes language comprehension; damage causes fluent but nonsensical speech.", 'medium', 'biological-bases', 'biological-bases-brain', 'A')
q('The corpus callosum connects:', ['The thalamus and hypothalamus', 'The left and right cerebral hemispheres', 'The cerebellum and medulla', 'The pons and midbrain'], 1, 'The corpus callosum is a thick band of fibers allowing communication between hemispheres.', 'easy', 'biological-bases', 'biological-bases-brain', 'both')
q('The sympathetic nervous system is responsible for:', ['Rest and digestion', 'The fight-or-flight response', 'Voluntary muscle control', 'Memory consolidation'], 1, 'The sympathetic branch mobilizes the body for emergency action.', 'easy', 'biological-bases', 'biological-bases-brain', 'A')
q('The parasympathetic nervous system:', ['Activates fight-or-flight', 'Calms the body and conserves energy', 'Controls voluntary movement', 'Processes visual information'], 1, 'The parasympathetic branch promotes rest-and-digest functions.', 'easy', 'biological-bases', 'biological-bases-brain', 'B')
q('The reticular formation is important for:', ['Regulating arousal and consciousness', 'Producing hormones', 'Processing taste', 'Storing memories'], 0, 'The reticular formation in the brainstem controls alertness and sleep-wake transitions.', 'medium', 'biological-bases', 'biological-bases-brain', 'A')
q('The hypothalamus regulates:', ['Fine motor coordination', 'Hunger, thirst, body temperature, and the endocrine system', 'Speech production', 'Visual processing'], 1, 'The hypothalamus is a key regulator of homeostasis and hormonal output.', 'easy', 'biological-bases', 'biological-bases-brain', 'both')
q('The thalamus functions as the brain relay station for:', ['Motor commands only', 'Sensory information (except smell)', 'Immune responses', 'Blood pressure regulation'], 1, 'The thalamus routes incoming sensory signals to the appropriate cortical areas.', 'easy', 'biological-bases', 'biological-bases-brain', 'B')
q('Serotonin is a neurotransmitter associated with:', ['Muscle contraction', 'Mood, sleep, and appetite regulation', 'Adrenaline release', 'Visual processing'], 1, 'Low serotonin levels are linked to depression and anxiety disorders.', 'easy', 'biological-bases', 'biological-bases-brain', 'A')
q('Dopamine is involved in:', ['Bone growth', 'Reward, motivation, and motor control', 'Skin sensation', 'Hearing'], 1, 'Dopamine plays key roles in the reward system and motor pathways.', 'easy', 'biological-bases', 'biological-bases-brain', 'both')
q('GABA is the major _____ neurotransmitter in the brain:', ['Excitatory', 'Inhibitory', 'Modulatory', 'Structural'], 1, 'GABA inhibits neural firing and helps reduce anxiety.', 'medium', 'biological-bases', 'biological-bases-brain', 'A')
q('An fMRI measures brain activity by detecting changes in:', ['Electrical signals', 'Blood oxygen levels', 'Skull density', 'Neurotransmitter concentrations'], 1, 'fMRI tracks blood oxygenation to show which brain areas are active.', 'medium', 'biological-bases', 'biological-bases-brain', 'B')
q('Neuroplasticity refers to:', ['The brain being rigid and unchanging', 'The brain ability to reorganize and form new neural connections', 'Death of neurons', 'Myelination only'], 1, 'Neuroplasticity allows the brain to adapt, especially after injury or learning.', 'easy', 'biological-bases', 'biological-bases-brain', 'both')
q('The amygdala is critical for processing:', ['Language', 'Emotions, especially fear', 'Mathematical reasoning', 'Body temperature'], 1, 'The amygdala is essential for fear conditioning and emotional memory.', 'easy', 'biological-bases', 'biological-bases-brain', 'A')
q('The cerebellum is primarily involved in:', ['Decision making', 'Coordination, balance, and motor learning', 'Language comprehension', 'Emotional regulation'], 1, 'The cerebellum fine-tunes voluntary movements and maintains balance.', 'easy', 'biological-bases', 'biological-bases-brain', 'B')
q('The pituitary gland is called the master gland because it:', ['Is the largest gland', 'Controls other endocrine glands through hormone release', 'Produces all hormones', 'Connects to the spinal cord'], 1, 'The pituitary releases hormones that regulate other endocrine glands.', 'medium', 'biological-bases', 'genetics-behavior', 'A')
q('Twin studies help researchers determine:', ['How to clone organisms', 'The relative contributions of genetics and environment', 'The exact gene for a trait', 'How many neurons a person has'], 1, 'Comparing identical and fraternal twins reveals genetic vs. environmental influences.', 'medium', 'biological-bases', 'genetics-behavior', 'both')

# ══════════════════════════════════════════════════════════════════
#  SENSATION & PERCEPTION  (~18 new → 24 total)
# ══════════════════════════════════════════════════════════════════
q('The absolute threshold is the minimum level of stimulation needed to:', ['Feel pain', 'Detect a stimulus 50% of the time', 'Distinguish between two stimuli', 'Adapt to a stimulus'], 1, 'The absolute threshold is the weakest stimulus detectable half the time.', 'easy', 'sensation-perception', 'sensation-sensory-processing', 'A')
q('The difference threshold (JND) is the minimum difference needed to:', ['See any stimulus', 'Detect a change between two stimuli', 'Process smell', 'Adapt to darkness'], 1, 'The just noticeable difference is the smallest detectable difference between stimuli.', 'easy', 'sensation-perception', 'sensation-sensory-processing', 'B')
q('Sensory adaptation explains why:', ['We can see in the dark immediately', 'We stop noticing a constant stimulus over time', 'Our hearing improves with age', 'We feel more pain over time'], 1, 'Sensory adaptation reduces sensitivity to an unchanging stimulus.', 'easy', 'sensation-perception', 'sensation-sensory-processing', 'both')
q('Place theory explains that we perceive different pitches because:', ['Different areas of the basilar membrane respond to different frequencies', 'The entire membrane vibrates at the same rate', 'Hair cells are only in one location', 'Sound waves do not enter the cochlea'], 0, 'Place theory: high-frequency sounds activate specific positions on the basilar membrane.', 'medium', 'sensation-perception', 'sensation-sensory-processing', 'A')
q('Frequency theory explains pitch perception for _____ frequency sounds:', ['Very high', 'Low', 'All', 'Ultrasonic'], 1, 'Frequency theory works best for low frequencies; neural firing rate matches sound frequency.', 'medium', 'sensation-perception', 'sensation-sensory-processing', 'B')
q('The gate-control theory of pain suggests:', ['Pain signals directly reach the brain without modulation', 'The spinal cord has a gating mechanism that can block pain signals', 'Pain is entirely psychological', 'Only severe injuries cause pain'], 1, 'Nerve gate in the spinal cord opens or closes to allow or block pain signals.', 'medium', 'sensation-perception', 'perception-attention', 'A')
q('Binocular cues for depth perception include:', ['Linear perspective', 'Retinal disparity and convergence', 'Relative size', 'Texture gradient'], 1, 'Binocular cues require both eyes: retinal disparity and convergence.', 'medium', 'sensation-perception', 'perception-attention', 'B')
q('Linear perspective is a _____ depth cue:', ['Binocular', 'Monocular', 'Auditory', 'Proprioceptive'], 1, 'Linear perspective uses converging parallel lines as a monocular depth cue.', 'easy', 'sensation-perception', 'perception-attention', 'both')
q('The Gestalt principle of closure states that we:', ['See similar items as groups', 'Tend to fill in gaps to perceive complete figures', 'Prefer symmetric shapes', 'Group items by proximity'], 1, 'Closure: the brain completes incomplete shapes to perceive them as whole.', 'easy', 'sensation-perception', 'perception-attention', 'A')
q('Selective attention is demonstrated by the cocktail party effect, which is:', ['Hearing your name across a noisy room', 'Being unable to hear at parties', 'Increased volume sensitivity', 'A type of hearing loss'], 0, 'The cocktail party effect shows we can focus on one voice amid noise.', 'easy', 'sensation-perception', 'perception-attention', 'B')
q('Transduction is the process by which:', ['Sensory receptors convert stimulus energy into neural signals', 'Muscles contract', 'The brain sends motor commands', 'Information is sent from the brain to receptors'], 0, 'Transduction converts physical energy (light, sound) into electrical neural signals.', 'medium', 'sensation-perception', 'sensation-sensory-processing', 'both')
q('Rods in the retina are specialized for:', ['Color vision', 'Dim-light and peripheral vision', 'Close-up focus', 'Reading'], 1, 'Rods detect low light levels and are concentrated at the periphery of the retina.', 'easy', 'sensation-perception', 'sensation-sensory-processing', 'A')
q('Cones are responsible for:', ['Night vision', 'Color vision and fine detail', 'Peripheral vision', 'Depth perception only'], 1, 'Cones detect color and are concentrated in the fovea for sharp central vision.', 'easy', 'sensation-perception', 'sensation-sensory-processing', 'B')
q('Weber law states that the just noticeable difference is a constant _____ of the original stimulus:', ['Addition', 'Proportion', 'Subtraction', 'Multiple of ten'], 1, 'Weber: the JND is a fixed percentage (e.g., 2%) of the stimulus magnitude.', 'medium', 'sensation-perception', 'sensation-sensory-processing', 'A')
q('Top-down processing uses _____ to interpret sensory information:', ['Only raw data', 'Prior knowledge and expectations', 'A single sense at a time', 'Random guessing'], 1, 'Top-down processing applies experience and context to make sense of input.', 'easy', 'sensation-perception', 'perception-attention', 'both')
q('Bottom-up processing starts with:', ['Expectations', 'Raw sensory data from the environment', 'Memory', 'Hypotheses'], 1, 'Bottom-up processing builds perception from sensory receptor input upward.', 'easy', 'sensation-perception', 'perception-attention', 'B')
q('The opponent-process theory of color vision proposes that color is processed in:', ['Three separate channels for RGB', 'Opposing pairs (red-green, blue-yellow, black-white)', 'A single pathway', 'The visual cortex only'], 1, 'Opponent-process theory: cells respond to opposing color pairs.', 'medium', 'sensation-perception', 'sensation-sensory-processing', 'A')
q('Perceptual constancy allows us to:', ['See colors only in bright light', 'Recognize objects as unchanging despite changes in viewing conditions', 'Detect ultrasonic sounds', 'Feel no pain during surgery'], 1, 'Size, shape, and color constancy help us perceive stable objects despite changing inputs.', 'easy', 'sensation-perception', 'perception-attention', 'both')

# ══════════════════════════════════════════════════════════════════
#  LEARNING  (~20 new → 26 total)
# ══════════════════════════════════════════════════════════════════
q('In classical conditioning, the unconditioned stimulus (US) elicits a response:', ['Only after training', 'Naturally and automatically', 'After being paired with another stimulus', 'Never'], 1, 'The US produces an automatic response without prior learning.', 'easy', 'learning', 'classical-conditioning', 'A')
q('In Pavlov experiment, the bell (before conditioning) is the:', ['Unconditioned stimulus', 'Neutral stimulus', 'Conditioned response', 'Unconditioned response'], 1, 'Before conditioning, the bell is neutral — it does not naturally elicit salivation.', 'easy', 'learning', 'classical-conditioning', 'B')
q('Stimulus generalization in classical conditioning means:', ['Responding only to the exact CS', 'Responding to stimuli similar to the CS', 'Forgetting the CS', 'Increasing the US strength'], 1, 'Generalization: stimuli resembling the original CS also elicit the CR.', 'easy', 'learning', 'classical-conditioning', 'both')
q('Stimulus discrimination is the ability to:', ['Respond to all stimuli equally', 'Distinguish between the CS and similar stimuli', 'Forget the trained response', 'Only respond to the US'], 1, 'Discrimination: the organism responds to the CS but not to similar stimuli.', 'easy', 'learning', 'classical-conditioning', 'A')
q('Extinction in classical conditioning occurs when:', ['The US is removed', 'The CS is presented repeatedly without the US', 'A new CS is introduced', 'The subject is punished'], 1, 'Without reinforcement (US), the conditioned response gradually weakens.', 'medium', 'learning', 'classical-conditioning', 'B')
q('Spontaneous recovery refers to:', ['A permanent return of the CR', 'The reappearance of a previously extinguished CR after a rest period', 'Learning a new behavior', 'Stronger conditioning'], 1, 'After extinction and a rest, the CR can briefly reappear.', 'medium', 'learning', 'classical-conditioning', 'both')
q('Positive reinforcement _____ a behavior by _____ a pleasant stimulus:', ['Decreases; adding', 'Increases; adding', 'Increases; removing', 'Decreases; removing'], 1, 'Positive reinforcement adds something desirable to strengthen behavior.', 'easy', 'learning', 'operant-conditioning', 'A')
q('Negative reinforcement _____ a behavior by _____ an aversive stimulus:', ['Decreases; adding', 'Increases; removing', 'Increases; adding', 'Has no effect; ignoring'], 1, 'Negative reinforcement removes something unpleasant, increasing the behavior.', 'easy', 'learning', 'operant-conditioning', 'B')
q('Punishment _____ the likelihood of a behavior:', ['Increases', 'Decreases', 'Has no effect on', 'Randomly changes'], 1, 'Punishment applies consequences to reduce the frequency of a behavior.', 'easy', 'learning', 'operant-conditioning', 'both')
q('A variable-ratio schedule of reinforcement produces:', ['Slow, steady responding', 'High, steady rates of responding and is most resistant to extinction', 'One response then a pause', 'No responding'], 1, 'Variable-ratio schedules (like slot machines) produce high, consistent response rates.', 'medium', 'learning', 'operant-conditioning', 'A')
q('A fixed-interval schedule reinforces behavior after:', ['A set number of responses', 'A fixed amount of time has passed', 'Every response', 'Random intervals'], 1, 'Fixed-interval: reinforcement is given after a specific time period (e.g., weekly paycheck).', 'medium', 'learning', 'operant-conditioning', 'B')
q('Shaping involves reinforcing:', ['Only the final desired behavior', 'Successive approximations of the target behavior', 'Every behavior equally', 'Only incorrect responses'], 1, 'Shaping builds complex behaviors by rewarding gradually closer approximations.', 'medium', 'learning', 'operant-conditioning', 'both')
q('Latent learning, demonstrated by Tolman, shows that:', ['Punishment is needed for learning', 'Learning can occur without reinforcement but may not be shown until later', 'All learning is observable', 'Only social learning is important'], 1, 'Tolman showed rats learned mazes without rewards; performance appeared when food was introduced.', 'medium', 'learning', 'observational-learning-cognition', 'A')
q('Albert Bandura Bobo doll experiment demonstrated:', ['Classical conditioning', 'Observational (social) learning', 'Operant conditioning only', 'Instinctive behavior'], 1, 'Children imitated aggressive behavior they observed, showing social learning.', 'easy', 'learning', 'observational-learning-cognition', 'B')
q('Modeling behavior requires attention, retention, reproduction, and:', ['Punishment', 'Motivation', 'Sleep', 'Extinction'], 1, 'Bandura identified four steps: attention, retention, motor reproduction, and motivation.', 'medium', 'learning', 'observational-learning-cognition', 'both')
q('Learned helplessness, studied by Seligman, occurs when:', ['An organism learns to control outcomes', 'An organism gives up after repeated failure to control outcomes', 'Positive reinforcement is used', 'The organism is rewarded'], 1, 'Repeated uncontrollable negative events lead to passive acceptance.', 'medium', 'learning', 'observational-learning-cognition', 'A')
q('Taste aversion is unique because it:', ['Requires many pairings', 'Can be learned in a single trial with a long CS-US delay', 'Only applies to humans', 'Is not classical conditioning'], 1, 'Taste aversion forms rapidly, even with hours between eating and illness.', 'hard', 'learning', 'classical-conditioning', 'B')
q('A token economy is an example of:', ['Classical conditioning', 'Operant conditioning using secondary reinforcers', 'Modeling', 'Habituation'], 1, 'Tokens are secondary reinforcers exchanged for desired rewards.', 'medium', 'learning', 'operant-conditioning', 'both')
q('Continuous reinforcement means rewarding:', ['Every correct response', 'Only some correct responses', 'Incorrect responses', 'No responses'], 0, 'Continuous schedules reinforce every instance of the desired behavior.', 'easy', 'learning', 'operant-conditioning', 'A')
q('Instinctive drift occurs when:', ['All conditioning is permanent', 'An animal reverts to biologically predisposed behaviors during conditioning', 'Humans stop learning', 'Reinforcement is too frequent'], 1, 'Innate behavioral tendencies sometimes override conditioned responses.', 'hard', 'learning', 'operant-conditioning', 'B')

# ══════════════════════════════════════════════════════════════════
#  MEMORY  (~20 new → 26 total)
# ══════════════════════════════════════════════════════════════════
q('The three stages of the Atkinson-Shiffrin memory model are:', ['Encoding, storage, retrieval', 'Sensory, short-term, long-term memory', 'Implicit, explicit, procedural', 'Episodic, semantic, procedural'], 1, 'The multi-store model proposes sensory, short-term, and long-term memory stores.', 'easy', 'memory', 'memory-encoding-storage', 'A')
q('Working memory has a capacity of approximately:', ['3 items', '7 ± 2 items', '15 items', 'Unlimited items'], 1, "Miller's magic number: working memory holds about 7 (±2) chunks of information.", 'easy', 'memory', 'memory-encoding-storage', 'B')
q('Chunking helps memory by:', ['Reducing sensory input', 'Grouping individual items into meaningful units', 'Increasing rehearsal time', 'Eliminating forgetting'], 1, 'Chunking groups bits of info into larger, manageable units (e.g., phone numbers).', 'easy', 'memory', 'memory-encoding-storage', 'both')
q('Procedural memory is a type of:', ['Explicit memory', 'Implicit (non-declarative) memory', 'Sensory memory', 'Working memory'], 1, 'Procedural memory (skills and habits) operates unconsciously.', 'easy', 'memory', 'memory-encoding-storage', 'A')
q('Episodic memory involves:', ['General knowledge', 'Personal experiences and events', 'Motor skills', 'Language rules'], 1, 'Episodic memory stores autobiographical events and their contextual details.', 'easy', 'memory', 'memory-encoding-storage', 'B')
q('Semantic memory contains:', ['Personal experiences', 'General knowledge and facts', 'Motor procedures', 'Short-term information only'], 1, 'Semantic memory stores factual knowledge independent of personal experience.', 'easy', 'memory', 'memory-encoding-storage', 'both')
q('The serial position effect shows that we best recall:', ['Items in the middle of a list', 'Items at the beginning and end of a list', 'Only the last item', 'Only the first item'], 1, 'Primacy and recency effects: first and last items are recalled best.', 'medium', 'memory', 'retrieval-forgetting', 'A')
q('Retroactive interference occurs when:', ['Old information blocks new learning', 'New information disrupts recall of old information', 'Memories are repressed', 'Encoding fails completely'], 1, 'Retroactive interference: new learning impairs retrieval of previously stored info.', 'medium', 'memory', 'retrieval-forgetting', 'B')
q('Proactive interference occurs when:', ['New information blocks old', 'Previously learned information interferes with new learning', 'All memories decay', 'Chunking fails'], 1, 'Proactive interference: old memories make it harder to learn new information.', 'medium', 'memory', 'retrieval-forgetting', 'both')
q('The misinformation effect demonstrates that:', ['Memories are permanent', 'Post-event information can alter memories', 'Eyewitnesses are always accurate', 'Repression protects memories'], 1, 'Loftus showed that misleading questions can distort memory of events.', 'medium', 'memory', 'retrieval-forgetting', 'A')
q('State-dependent memory means:', ['Only happy memories are recalled', 'Recall is better when in the same physiological state as during encoding', 'All memories depend on the state', 'Sleep improves all recall'], 1, 'Matching internal states at encoding and retrieval can improve recall.', 'hard', 'memory', 'retrieval-forgetting', 'B')
q('Context-dependent memory suggests:', ['Environment does not affect recall', 'Being in the same environment as during learning aids retrieval', 'Only emotional memories are context-dependent', 'Context is irrelevant'], 1, 'External context cues present during encoding help trigger retrieval.', 'medium', 'memory', 'retrieval-forgetting', 'both')
q('Flashbulb memories are vivid memories typically associated with:', ['Routine daily events', 'Emotionally significant or surprising events', 'Procedural skills', 'Implicit learning'], 1, 'Flashbulb memories feel vivid and detailed, often for shocking events.', 'easy', 'memory', 'memory-encoding-storage', 'A')
q('Ebbinghaus forgetting curve shows that forgetting:', ['Is linear over time', 'Is most rapid shortly after learning, then levels off', 'Does not occur', 'Only happens during sleep'], 1, 'Most forgetting happens quickly; retention then stabilizes.', 'medium', 'memory', 'retrieval-forgetting', 'B')
q('The hippocampus is essential for:', ['Motor coordination', 'Forming new explicit memories', 'Producing speech', 'Processing visual information'], 1, 'The hippocampus consolidates new declarative memories.', 'easy', 'memory', 'memory-encoding-storage', 'both')
q('Recall is a more difficult memory task than recognition because:', ['It provides cues', 'It requires generating the answer without cues', 'It only tests implicit memory', 'It is the same as recognition'], 1, 'Recall demands retrieval without prompts; recognition provides options.', 'medium', 'memory', 'retrieval-forgetting', 'A')
q('Elaborative rehearsal improves memory by:', ['Simply repeating information', 'Connecting new information to existing knowledge', 'Reducing encoding time', 'Using only visual cues'], 1, 'Deep processing through meaningful connections enhances long-term retention.', 'medium', 'memory', 'memory-encoding-storage', 'B')
q('The spacing effect suggests studying is more effective when:', ['Massed into one session', 'Distributed over multiple sessions', 'Done only right before a test', 'Done without breaks'], 1, 'Spaced practice leads to better long-term retention than cramming.', 'easy', 'memory', 'memory-encoding-storage', 'both')
q('Source amnesia involves:', ['Forgetting where you heard information', 'Losing all memories', 'Inability to form new memories', 'Forgetting motor skills'], 0, 'Source amnesia (misattribution): remembering information but not its origin.', 'medium', 'memory', 'retrieval-forgetting', 'A')
q('Anterograde amnesia prevents the formation of:', ['Old memories', 'New memories after the injury', 'Implicit memories', 'Emotional responses'], 1, 'Anterograde amnesia: inability to form new long-term memories (as in H.M.).', 'medium', 'memory', 'retrieval-forgetting', 'B')

# ══════════════════════════════════════════════════════════════════
#  THINKING, LANGUAGE & INTELLIGENCE  (~18 new → 23 total)
# ══════════════════════════════════════════════════════════════════
q('The availability heuristic leads people to:', ['Make logical decisions always', 'Estimate probability based on how easily examples come to mind', 'Ignore all evidence', 'Never make errors'], 1, 'Events that are easily recalled (vivid, recent) are judged as more likely.', 'medium', 'thinking-language', 'thinking-problem-solving', 'A')
q('The representativeness heuristic causes people to:', ['Use statistics carefully', 'Judge likelihood by how well something matches a prototype', 'Ignore all categories', 'Always be correct'], 1, 'People judge category membership based on resemblance to a typical case.', 'medium', 'thinking-language', 'thinking-problem-solving', 'B')
q('Functional fixedness is the tendency to:', ['See only the typical use of an object', 'Flex thinking easily', 'Always find creative solutions', 'Ignore objects'], 0, 'Functional fixedness limits perception of alternative uses for familiar objects.', 'medium', 'thinking-language', 'thinking-problem-solving', 'both')
q('Divergent thinking is associated with:', ['Finding one correct answer', 'Generating multiple creative solutions', 'Rigid thinking', 'Algorithmic problem solving'], 1, 'Divergent thinking explores many possible solutions and is linked to creativity.', 'easy', 'thinking-language', 'thinking-problem-solving', 'A')
q('An algorithm guarantees a solution by:', ['Using intuition', 'Systematically trying every possibility', 'Making quick estimates', 'Ignoring options'], 1, 'Algorithms are step-by-step procedures that guarantee finding a solution.', 'easy', 'thinking-language', 'thinking-problem-solving', 'B')
q('Linguistic determinism (Sapir-Whorf hypothesis) suggests that:', ['Language has no effect on thought', 'Language shapes the way we think', 'All languages are identical', 'Thought exists without language'], 1, 'The strong version claims language determines thought; the weak version says it influences it.', 'medium', 'thinking-language', 'language-intelligence', 'both')
q('Noam Chomsky proposed that humans have an innate:', ['Reward system for language', 'Language acquisition device (LAD)', 'Visual processing center', 'Memory for words only'], 1, 'Chomsky argued humans are born with a biological capacity for language learning.', 'medium', 'thinking-language', 'language-intelligence', 'A')
q('Spearman concept of g refers to:', ['Gardener multiple intelligences', 'A general intelligence factor underlying specific abilities', 'Emotional intelligence only', 'Spatial intelligence'], 1, 'Spearman proposed that g (general intelligence) underlies performance across tasks.', 'medium', 'thinking-language', 'language-intelligence', 'B')
q('Howard Gardner theory of multiple intelligences includes:', ['Only verbal and math skills', 'At least eight different types of intelligence', 'Only IQ', 'Two types: crystallized and fluid'], 1, 'Gardner identified linguistic, musical, spatial, bodily-kinesthetic, and other intelligences.', 'easy', 'thinking-language', 'language-intelligence', 'both')
q('Sternberg triarchic theory of intelligence includes:', ['Only analytical intelligence', 'Analytical, creative, and practical intelligence', 'Emotional and social intelligence', 'Verbal and performance intelligence'], 1, 'Sternberg describes three facets: analytical (academic), creative, and practical.', 'medium', 'thinking-language', 'language-intelligence', 'A')
q('An IQ score of 100 represents:', ['Below-average intelligence', 'Exactly average intelligence', 'Genius-level intelligence', 'No intelligence'], 1, 'IQ tests are normed with 100 as the mean and 15 as the standard deviation.', 'easy', 'thinking-language', 'language-intelligence', 'B')
q('Crystallized intelligence refers to:', ['The ability to quickly solve new problems', 'Accumulated knowledge and verbal skills', 'Physical coordination', 'Musical ability'], 1, 'Crystallized intelligence grows with experience and includes vocabulary and facts.', 'easy', 'thinking-language', 'language-intelligence', 'both')
q('Fluid intelligence refers to:', ['Stored factual knowledge', 'The ability to reason and solve novel problems', 'Emotional awareness', 'Language skills only'], 1, 'Fluid intelligence involves abstract reasoning and tends to decline with age.', 'easy', 'thinking-language', 'language-intelligence', 'A')
q('Anchoring bias occurs when:', ['People rely too heavily on the first piece of information they receive', 'People forget the question', 'People use algorithms', 'People never make decisions'], 0, 'The anchor (initial information) disproportionately influences subsequent judgments.', 'medium', 'thinking-language', 'thinking-problem-solving', 'B')
q('Overconfidence bias leads people to:', ['Underestimate their abilities', 'Be more accurate than they think', 'Overestimate the accuracy of their beliefs', 'Avoid all decisions'], 2, 'People often think they know more than they actually do.', 'medium', 'thinking-language', 'thinking-problem-solving', 'both')
q('Framing effect shows that:', ['How information is presented affects decisions', 'All frames are equal', 'People ignore context', 'Only numbers influence decisions'], 0, 'The way a question or scenario is framed can change the decision people make.', 'medium', 'thinking-language', 'thinking-problem-solving', 'A')
q('Babbling in infants begins at around:', ['Birth', '4 months', '2 years', '5 years'], 1, 'Around 4 months, infants begin producing repetitive consonant-vowel sounds.', 'easy', 'thinking-language', 'language-intelligence', 'B')
q('A test has high reliability if it:', ['Measures what it claims to measure', 'Yields consistent results over time', 'Is normed on diverse populations', 'Has no questions'], 1, 'Reliability means the test produces stable, consistent scores upon repeated testing.', 'easy', 'thinking-language', 'language-intelligence', 'both')

# ══════════════════════════════════════════════════════════════════
#  MOTIVATION & EMOTION  (~18 new → 23 total)
# ══════════════════════════════════════════════════════════════════
q('Maslow hierarchy of needs places _____ at the base:', ['Self-actualization', 'Physiological needs', 'Esteem needs', 'Safety needs'], 1, 'Basic survival needs (food, water, shelter) must be met before higher needs.', 'easy', 'motivation-emotion', 'motivation-theories', 'A')
q('The drive-reduction theory suggests that behavior is motivated by:', ['Curiosity alone', 'The need to reduce biological tensions (drives)', 'External rewards only', 'Social approval'], 1, 'Physiological needs create drives that motivate behavior to restore homeostasis.', 'easy', 'motivation-emotion', 'motivation-theories', 'B')
q('Intrinsic motivation comes from:', ['External rewards', 'Internal satisfaction and personal interest', 'Fear of punishment', 'Social pressure'], 1, 'Intrinsically motivated behavior is performed for its own sake.', 'easy', 'motivation-emotion', 'motivation-theories', 'both')
q('Extrinsic motivation involves:', ['Performing a behavior for an external reward or to avoid punishment', 'Being motivated purely by curiosity', 'Having no motivation', 'Self-actualization'], 0, 'Extrinsic motivation relies on external incentives.', 'easy', 'motivation-emotion', 'motivation-theories', 'A')
q('The Yerkes-Dodson law states that performance is best at:', ['Maximum arousal', 'Moderate arousal', 'Minimum arousal', 'No arousal'], 1, 'An optimal level of arousal (not too low, not too high) leads to best performance.', 'medium', 'motivation-emotion', 'motivation-theories', 'B')
q('The James-Lange theory of emotion states that:', ['We feel emotions then react physically', 'We experience physiological arousal first, which leads to emotion', 'Emotions and arousal occur simultaneously', 'Emotions are learned'], 1, 'James-Lange: stimulus → body reaction → awareness of emotion.', 'medium', 'motivation-emotion', 'emotion-stress', 'both')
q('The Cannon-Bard theory proposes that:', ['Arousal causes emotion', 'Emotion and physiological arousal occur simultaneously', 'Cognition must precede emotion', 'Emotions are purely social constructs'], 1, 'Cannon-Bard: the body and emotion react at the same time, independently.', 'medium', 'motivation-emotion', 'emotion-stress', 'A')
q('The Schachter-Singer two-factor theory states that emotion results from:', ['Arousal alone', 'Cognition alone', 'Physiological arousal plus cognitive labeling', 'Genetics only'], 2, 'Two-factor: we experience arousal, then label it based on context.', 'medium', 'motivation-emotion', 'emotion-stress', 'B')
q('The set-point theory of weight regulation suggests:', ['The body has no mechanisms for weight control', 'The body tends to maintain a particular weight level', 'Diet always succeeds', 'Exercise has no effect'], 1, 'The hypothalamus helps maintain body weight around a preset level.', 'medium', 'motivation-emotion', 'motivation-theories', 'both')
q('Facial feedback hypothesis suggests that:', ['Facial expressions have no effect on emotion', 'Facial expressions can influence emotional experience', 'Only sadness affects facial muscles', 'Emotions cannot be changed'], 1, 'Smiling can actually enhance feelings of happiness (facial feedback effect).', 'medium', 'motivation-emotion', 'emotion-stress', 'A')
q('Paul Ekman research found that basic facial expressions are:', ['Culturally specific', 'Universal across cultures', 'Only found in Western countries', 'Not related to emotion'], 1, 'Six basic emotions (happiness, sadness, fear, anger, surprise, disgust) are universally recognized.', 'easy', 'motivation-emotion', 'emotion-stress', 'B')
q('The general adaptation syndrome (GAS) by Hans Selye includes stages of:', ['Only alarm and exhaustion', 'Alarm, resistance, and exhaustion', 'Denial, anger, and acceptance', 'Fight and flight only'], 1, 'GAS describes the body response to prolonged stress in three stages.', 'medium', 'motivation-emotion', 'emotion-stress', 'both')
q('Type A personality is characterized by:', ['Relaxed and easygoing behavior', 'Competitive, time-urgent, and hostile behavior', 'Withdrawal from social interaction', 'Low stress levels'], 1, 'Type A individuals are driven, impatient, and prone to stress-related illness.', 'easy', 'motivation-emotion', 'emotion-stress', 'A')
q('The overjustification effect occurs when:', ['External rewards decrease intrinsic motivation for a previously enjoyed activity', 'Punishing behavior increases it', 'Internal motivation is unaffected by rewards', 'No learning takes place'], 0, 'Excessive external rewards can undermine the intrinsic desire to perform a task.', 'hard', 'motivation-emotion', 'motivation-theories', 'B')
q('Arousal theory suggests that people are motivated to:', ['Always minimize arousal', 'Maintain an optimal level of arousal', 'Maximize all stimulation', 'Avoid all activity'], 1, 'People seek the right level of stimulation — not too much, not too little.', 'easy', 'motivation-emotion', 'motivation-theories', 'both')
q('Lazarus appraisal theory of emotion states that:', ['Emotions precede thought', 'Cognitive appraisal of a situation determines the emotional response', 'Emotions are independent of thought', 'Appraisal happens after the emotion'], 1, 'Lazarus: how you interpret (appraise) a situation determines the emotion you feel.', 'medium', 'motivation-emotion', 'emotion-stress', 'A')
q('Tend-and-befriend is a stress response more common in:', ['Males', 'Females', 'Both sexes equally', 'Neither sex'], 1, 'Shelley Taylor found that women more often cope with stress through social bonding.', 'medium', 'motivation-emotion', 'emotion-stress', 'B')
q('The hierarchy of needs model is criticized because:', ['It is not a hierarchy at all', 'People sometimes pursue higher needs before lower ones are fully met', 'Physiological needs are not important', 'It includes too many levels'], 1, 'People can pursue self-actualization or belonging even when safety needs are not fully satisfied.', 'medium', 'motivation-emotion', 'motivation-theories', 'both')

# ══════════════════════════════════════════════════════════════════
#  DEVELOPMENTAL  (~18 new → 23 total)
# ══════════════════════════════════════════════════════════════════
q('Piaget sensorimotor stage occurs from:', ['Birth to 2 years', '2 to 7 years', '7 to 11 years', '12 years and up'], 0, 'During the sensorimotor stage (0–2), infants learn through senses and motor actions.', 'easy', 'developmental', 'prenatal-childhood-development', 'A')
q('Object permanence develops during the _____ stage:', ['Preoperational', 'Sensorimotor', 'Concrete operational', 'Formal operational'], 1, 'Infants gain object permanence (knowing objects exist when hidden) around 8 months.', 'easy', 'developmental', 'prenatal-childhood-development', 'B')
q('Egocentrism in Piaget theory is characteristic of the _____ stage:', ['Sensorimotor', 'Preoperational', 'Concrete operational', 'Formal operational'], 1, 'Preoperational children (2–7) have difficulty seeing things from another perspective.', 'easy', 'developmental', 'prenatal-childhood-development', 'both')
q('Conservation (understanding quantity stays the same despite appearance changes) develops in the:', ['Sensorimotor stage', 'Preoperational stage', 'Concrete operational stage', 'Formal operational stage'], 2, 'Children develop conservation around age 7, in the concrete operational stage.', 'easy', 'developmental', 'prenatal-childhood-development', 'A')
q('Formal operational thinking allows for:', ['Only concrete problem solving', 'Abstract and hypothetical reasoning', 'Sensory exploration', 'Egocentrism'], 1, 'Beginning around age 12, adolescents can reason abstractly and test hypotheses.', 'easy', 'developmental', 'prenatal-childhood-development', 'B')
q('Bowlby concept of attachment suggests that infants:', ['Have no preference for caregivers', 'Are biologically predisposed to form attachments for survival', 'Only attach to mothers', 'Attach equally to strangers'], 1, 'Bowlby argued that attachment is an innate adaptive behavior.', 'medium', 'developmental', 'prenatal-childhood-development', 'both')
q('Ainsworth Strange Situation identified _____ attachment styles:', ['Two', 'Three (secure, avoidant, anxious-ambivalent)', 'Five', 'One'], 1, 'Ainsworth classified attachment as secure, avoidant, or anxious/ambivalent.', 'medium', 'developmental', 'prenatal-childhood-development', 'A')
q('Kohlberg preconventional level of moral reasoning focuses on:', ['Universal ethical principles', 'Self-interest and avoiding punishment', 'Maintaining social order', 'Following laws always'], 1, 'Preconventional: morality is based on consequences (reward/punishment).', 'medium', 'developmental', 'prenatal-childhood-development', 'B')
q('Erikson identity vs. role confusion stage occurs during:', ['Infancy', 'Early childhood', 'Adolescence', 'Late adulthood'], 2, 'Adolescents work to develop a clear sense of personal identity.', 'easy', 'developmental', 'adolescence-adulthood', 'both')
q('Erikson stage of generativity vs. stagnation occurs during:', ['Adolescence', 'Young adulthood', 'Middle adulthood', 'Late adulthood'], 2, 'Middle-aged adults strive to contribute to society and guide the next generation.', 'medium', 'developmental', 'adolescence-adulthood', 'A')
q('Teratogens are substances that:', ['Promote fetal growth', 'Can cause birth defects during prenatal development', 'Only affect adults', 'Improve nutrition'], 1, 'Teratogens (alcohol, drugs, radiation) can harm the developing embryo or fetus.', 'easy', 'developmental', 'prenatal-childhood-development', 'B')
q('The critical period for language acquisition is approximately:', ['Birth to 6 months', 'Birth to age 7-8', 'Adolescence', 'Adulthood'], 1, 'Language learning is easiest during a sensitive period in early childhood.', 'medium', 'developmental', 'prenatal-childhood-development', 'both')
q('Harlow experiments with monkeys demonstrated the importance of:', ['Food over comfort', 'Contact comfort over food', 'Punishment in learning', 'Visual stimulation'], 1, 'Infant monkeys preferred the soft cloth mother over the wire mother with food.', 'easy', 'developmental', 'prenatal-childhood-development', 'A')
q('Vygotsky zone of proximal development (ZPD) refers to:', ['What a child can do alone', 'Tasks a child can perform with guidance but not yet independently', 'Adult intelligence levels', 'Innate reflexes'], 1, 'ZPD is the gap between independent ability and assisted ability.', 'medium', 'developmental', 'prenatal-childhood-development', 'B')
q('Authoritative parenting is characterized by:', ['High demand and low responsiveness', 'High demand and high responsiveness', 'Low demand and high responsiveness', 'Low demand and low responsiveness'], 1, 'Authoritative parents set clear expectations while being warm and responsive.', 'easy', 'developmental', 'prenatal-childhood-development', 'both')
q('During puberty, the primary change is:', ['Cognitive decline', 'Development of primary and secondary sex characteristics', 'Loss of motor skills', 'Regression to earlier stages'], 1, 'Puberty involves hormonal changes leading to physical sexual maturation.', 'easy', 'developmental', 'adolescence-adulthood', 'A')
q('Integrity vs. despair is Erikson stage for:', ['Young adults', 'Middle-aged adults', 'Older adults reflecting on their lives', 'Adolescents'], 2, 'In late adulthood, people reflect on life; satisfaction leads to integrity, regret to despair.', 'easy', 'developmental', 'adolescence-adulthood', 'B')
q('Secure attachment in infancy is associated with later:', ['Social competence and resilience', 'Avoidance of all relationships', 'Aggression', 'Learning disabilities'], 0, 'Securely attached children tend to be more socially skilled and confident.', 'easy', 'developmental', 'prenatal-childhood-development', 'both')

# ══════════════════════════════════════════════════════════════════
#  PERSONALITY  (~18 new → 23 total)
# ══════════════════════════════════════════════════════════════════
q('Freud believed personality is shaped by conflicts among the:', ['Left and right brain', 'Id, ego, and superego', 'Conscious and subconscious only', 'Five personality traits'], 1, 'Freud: the id (pleasure), ego (reality), and superego (morality) interact.', 'easy', 'personality', 'personality-theories', 'A')
q('The Big Five personality traits are:', ['Introversion, intuition, feeling, perceiving, judging', 'Openness, conscientiousness, extraversion, agreeableness, neuroticism', 'Trust, autonomy, initiative, industry, identity', 'Oral, anal, phallic, latent, genital'], 1, 'OCEAN: Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism.', 'easy', 'personality', 'personality-theories', 'B')
q('The MMPI is a _____ personality test:', ['Projective', 'Self-report/objective', 'Performance-based', 'Observational'], 1, 'The MMPI is a standardized self-report inventory used to assess personality and psychopathology.', 'medium', 'personality', 'personality-theories', 'both')
q('Projective tests like the Rorschach are based on the idea that people:', ['Give identical responses', 'Project unconscious feelings onto ambiguous stimuli', 'Are always honest', 'Cannot interpret images'], 1, 'Projective tests assume responses to ambiguous stimuli reveal unconscious processes.', 'medium', 'personality', 'personality-theories', 'A')
q('Bandura concept of self-efficacy is:', ['Belief in one own ability to succeed', 'External control of behavior', 'Unconscious drives', 'Genetic determinism'], 0, 'Self-efficacy is confidence in your capacity to accomplish specific tasks.', 'easy', 'personality', 'personality-theories', 'B')
q('An internal locus of control means:', ['Events are controlled by fate', 'You believe you control your own outcomes', 'Others control your life', 'Luck determines success'], 1, 'Internal locus: believing you are responsible for what happens to you.', 'easy', 'personality', 'personality-theories', 'both')
q('Rogers unconditional positive regard means:', ['Accepting a person regardless of their behavior', 'Only praising good behavior', 'Ignoring bad behavior', 'Punishing mistakes'], 0, 'Rogers believed acceptance without conditions promotes personal growth.', 'easy', 'personality', 'personality-theories', 'A')
q('Defense mechanisms, according to Freud, operate at the _____ level:', ['Conscious', 'Unconscious', 'Preconscious only', 'Social'], 1, 'Defense mechanisms work unconsciously to protect the ego from anxiety.', 'easy', 'personality', 'personality-theories', 'B')
q('Projection as a defense mechanism involves:', ['Attributing your own unacceptable feelings to someone else', 'Returning to an earlier developmental stage', 'Redirecting feelings to a less threatening target', 'Refusing to accept reality'], 0, 'Projection assigns your own unwanted impulses to others.', 'medium', 'personality', 'personality-theories', 'both')
q('Displacement involves:', ['Transferring feelings to a safer target', 'Denying a situation', 'Rationalizing behavior', 'Projecting feelings'], 0, 'Displacement: redirecting emotions toward a less threatening person or object.', 'medium', 'personality', 'personality-theories', 'A')
q('The trait perspective focuses on:', ['Unconscious conflicts', 'Describing and measuring personality characteristics', 'Childhood experiences', 'Self-actualization'], 1, 'Trait theory identifies and measures stable personality dimensions.', 'easy', 'personality', 'personality-theories', 'B')
q('Allport distinguished between cardinal, central, and _____ traits:', ['Superego', 'Secondary', 'Primary', 'Universal'], 1, 'Secondary traits are situation-specific preferences and attitudes.', 'medium', 'personality', 'personality-theories', 'both')
q('Reciprocal determinism (Bandura) describes how:', ['Only behavior affects personality', 'Behavior, personal factors, and environment all influence each other', 'Genetics determine personality', 'The environment alone shapes personality'], 1, 'Bandura: behavior, cognition, and environment reciprocally interact.', 'medium', 'personality', 'personality-theories', 'A')
q('Sublimation is a defense mechanism that:', ['Channels unacceptable impulses into socially acceptable activities', 'Denies reality', 'Returns to an earlier stage', 'Projects feelings onto others'], 0, 'Sublimation redirects potentially harmful urges into constructive behavior.', 'medium', 'personality', 'personality-theories', 'B')
q('The self-serving bias is the tendency to:', ['Attribute successes to internal factors and failures to external factors', 'Always blame oneself', 'Be accurate in self-assessment', 'Avoid taking any credit'], 0, 'People protect self-esteem by taking credit for success and blaming circumstances for failure.', 'easy', 'personality', 'personality-theories', 'both')
q('Reaction formation as a defense mechanism involves:', ['Acting opposite to your true feelings', 'Forgetting painful experiences', 'Denying the existence of a threat', 'Redirecting emotions'], 0, 'Reaction formation: expressing the opposite of threatening desires.', 'medium', 'personality', 'personality-theories', 'A')
q('Regression as a defense mechanism involves:', ['Moving forward in development', 'Reverting to behaviors of an earlier stage', 'Projecting feelings', 'Rationalizing actions'], 1, 'Regression: retreating to childlike behavior when stressed.', 'medium', 'personality', 'personality-theories', 'B')
q('Rationalization involves:', ['Using logic correctly', 'Creating logical excuses to justify unacceptable behavior', 'Projecting feelings', 'Displacement of anger'], 1, 'Rationalization protects the ego by offering seemingly reasonable explanations.', 'easy', 'personality', 'personality-theories', 'both')

# ══════════════════════════════════════════════════════════════════
#  DISORDERS & TREATMENT  (~20 new → 26 total)
# ══════════════════════════════════════════════════════════════════
q('The DSM-5 is used to:', ['Prescribe medication', 'Classify and diagnose psychological disorders', 'Conduct brain surgery', 'Measure intelligence'], 1, 'The DSM-5 is the standard diagnostic manual for mental health professionals.', 'easy', 'disorders-treatment', 'psychological-disorders-overview', 'A')
q('Generalized anxiety disorder (GAD) involves:', ['Fear of a specific object', 'Persistent and excessive worry about many things', 'Recurrent panic attacks only', 'Social avoidance exclusively'], 1, 'GAD features chronic, free-floating anxiety about multiple areas of life.', 'easy', 'disorders-treatment', 'psychological-disorders-overview', 'B')
q('Obsessive-compulsive disorder (OCD) involves:', ['Only obsessions without compulsions', 'Unwanted repetitive thoughts and/or ritualistic behaviors', 'Delusions and hallucinations', 'Mood swings only'], 1, 'OCD: persistent obsessions lead to compulsive behaviors meant to reduce anxiety.', 'easy', 'disorders-treatment', 'psychological-disorders-overview', 'both')
q('Major depressive disorder is characterized by:', ['Brief sadness lasting hours', 'Persistent depressed mood or loss of interest for at least two weeks', 'Manic episodes', 'Hallucinations'], 1, 'MDD requires a depressed mood or anhedonia lasting at least two weeks.', 'easy', 'disorders-treatment', 'mood-psychotic-disorders', 'A')
q('Bipolar disorder involves:', ['Only depression', 'Alternating episodes of mania and depression', 'Constant anxiety', 'Multiple personalities'], 1, 'Bipolar disorder features cycles of manic highs and depressive lows.', 'easy', 'disorders-treatment', 'mood-psychotic-disorders', 'B')
q('Schizophrenia symptoms include:', ['Only mood swings', 'Delusions, hallucinations, and disorganized thinking', 'Excessive worry only', 'Only compulsive behaviors'], 1, 'Schizophrenia involves positive symptoms (delusions, hallucinations) and negative symptoms.', 'easy', 'disorders-treatment', 'mood-psychotic-disorders', 'both')
q('Dissociative identity disorder (DID) involves:', ['Loss of sensation', 'Two or more distinct personality states', 'Persistent anxiety', 'A phobia'], 1, 'DID (formerly multiple personality disorder) features distinct personality alters.', 'medium', 'disorders-treatment', 'psychological-disorders-overview', 'A')
q('Post-traumatic stress disorder (PTSD) develops after:', ['Normal stress', 'A traumatic or life-threatening event', 'Watching TV', 'Minor inconveniences'], 1, 'PTSD involves flashbacks, nightmares, and hyperarousal following trauma.', 'easy', 'disorders-treatment', 'psychological-disorders-overview', 'B')
q('SSRIs treat depression by:', ['Blocking dopamine receptors', 'Increasing serotonin availability in the synapse', 'Stimulating the adrenal glands', 'Reducing all neural activity'], 1, 'SSRIs block serotonin reuptake, increasing serotonin in the synaptic cleft.', 'medium', 'disorders-treatment', 'treatment-therapy', 'both')
q('Cognitive-behavioral therapy (CBT) focuses on:', ['Unconscious desires', 'Changing maladaptive thought patterns and behaviors', 'Free association', 'Dream analysis'], 1, 'CBT targets irrational thoughts and teaches adaptive coping strategies.', 'easy', 'disorders-treatment', 'treatment-therapy', 'A')
q('Systematic desensitization pairs relaxation with:', ['Punishment', 'Gradually increasing exposure to a feared stimulus', 'Drug therapy', 'Hypnosis'], 1, 'Wolpe: pairing relaxation techniques with a hierarchy of fear-inducing stimuli.', 'medium', 'disorders-treatment', 'treatment-therapy', 'B')
q('Psychoanalytic therapy uses techniques like:', ['Systematic desensitization', 'Free association and dream analysis', 'Token economies', 'Behavioral contracts'], 1, 'Freudian therapy aims to uncover unconscious conflicts through talking freely.', 'easy', 'disorders-treatment', 'treatment-therapy', 'both')
q('Agoraphobia is a fear of:', ['Spiders', 'Open or public spaces where escape may be difficult', 'Blood', 'Heights'], 1, 'Agoraphobia involves anxiety about situations where escape might be difficult.', 'easy', 'disorders-treatment', 'psychological-disorders-overview', 'A')
q('A specific phobia is an irrational fear of:', ['Everything', 'A particular object or situation', 'People in general', 'Going to sleep'], 1, 'Specific phobias are intense, disproportionate fears of particular stimuli.', 'easy', 'disorders-treatment', 'psychological-disorders-overview', 'B')
q('The diathesis-stress model suggests that disorders result from:', ['Only genetics', 'Only environment', 'A combination of biological predisposition and environmental stressors', 'Random chance'], 2, 'The model combines genetic vulnerability with stressful triggers.', 'medium', 'disorders-treatment', 'psychological-disorders-overview', 'both')
q('Humanistic therapy emphasizes:', ['Dream interpretation', 'Active listening, empathy, and unconditional positive regard', 'Classical conditioning techniques', 'Drug treatment'], 1, 'Rogers client-centered therapy creates a supportive environment for self-exploration.', 'easy', 'disorders-treatment', 'treatment-therapy', 'A')
q('Antipsychotic medications primarily affect:', ['Serotonin only', 'Dopamine pathways', 'GABA receptors', 'Endorphin levels'], 1, 'Antipsychotics (like chlorpromazine) block dopamine receptors to reduce psychotic symptoms.', 'medium', 'disorders-treatment', 'treatment-therapy', 'B')
q('Group therapy benefits include:', ['Complete privacy', 'Social support and shared experiences', 'One-on-one attention from the therapist', 'No structure'], 1, 'Group therapy provides peer support, feedback, and a sense of universality.', 'easy', 'disorders-treatment', 'treatment-therapy', 'both')
q('Anorexia nervosa is characterized by:', ['Binge eating followed by purging', 'Extreme calorie restriction and fear of weight gain', 'Overeating without purging', 'Cravings for specific foods'], 1, 'Anorexia involves severely limiting food intake and distorted body image.', 'easy', 'disorders-treatment', 'psychological-disorders-overview', 'A')
q('Bulimia nervosa involves:', ['Only restricting food', 'Binge eating followed by compensatory behaviors like purging', 'Gradual weight gain', 'Fear of public spaces'], 1, 'Bulimia cycles through binge eating and purging/excessive exercise.', 'easy', 'disorders-treatment', 'psychological-disorders-overview', 'B')

# ══════════════════════════════════════════════════════════════════
#  SOCIAL PSYCHOLOGY  (~18 new → 24 total)
# ══════════════════════════════════════════════════════════════════
q('The fundamental attribution error is the tendency to:', ['Blame situations for others behavior', 'Overattribute others behavior to internal traits and underestimate situational factors', 'Blame oneself for everything', 'Only consider external factors'], 1, 'FAE: we overestimate personality and underestimate situation when explaining others actions.', 'easy', 'social', 'social-influence-conformity', 'A')
q('Asch conformity experiment showed that participants:', ['Never conformed', 'Often conformed to a group incorrect answer', 'Always gave the right answer', 'Could not see the lines'], 1, 'About 75% of participants conformed at least once to the obviously wrong group answer.', 'easy', 'social', 'social-influence-conformity', 'B')
q('Milgram obedience study demonstrated that:', ['People rarely obey authority', 'A majority of participants administered perceived lethal shocks when instructed by an authority figure', 'Participants refused to continue', 'Only psychopaths obey'], 1, 'About 65% of participants obeyed fully, highlighting the power of authority.', 'easy', 'social', 'social-influence-conformity', 'both')
q('The bystander effect suggests that:', ['More bystanders increase helping', 'The presence of others decreases the likelihood of helping', 'Bystanders always help', 'Only one person needs to be present'], 1, 'Diffusion of responsibility: more people present reduces individual tendency to help.', 'easy', 'social', 'group-behavior-prejudice', 'A')
q('Social loafing occurs when:', ['Individuals work harder in groups', 'People exert less effort in a group than when working alone', 'Groups are always productive', 'Leaders do all the work'], 1, 'People may reduce effort when their contribution is not individually identifiable.', 'easy', 'social', 'group-behavior-prejudice', 'B')
q('Groupthink is a phenomenon where:', ['Groups make better decisions than individuals', 'The desire for harmony leads to irrational or poor decisions', 'Each member thinks independently', 'Leadership prevents bad decisions'], 1, 'Groupthink prioritizes consensus over critical evaluation of alternatives.', 'medium', 'social', 'group-behavior-prejudice', 'both')
q('Cognitive dissonance occurs when a person holds:', ['Two consistent beliefs', 'Two conflicting cognitions, causing discomfort', 'Only one belief', 'No beliefs'], 1, 'Dissonance: the discomfort from holding contradictory beliefs motivates change.', 'easy', 'social', 'attitudes-persuasion', 'A')
q('The foot-in-the-door technique works by:', ['Starting with a large request', 'Starting with a small request, then escalating', 'Offering a reward', 'Threatening punishment'], 1, 'Agreeing to a small initial request increases compliance with a larger later request.', 'medium', 'social', 'attitudes-persuasion', 'B')
q('The door-in-the-face technique works by:', ['Starting with a large request that is refused, then making a smaller request', 'Starting with a small request', 'Using authority', 'Providing information'], 0, 'After refusing a large request, people feel obligated to agree to a smaller one.', 'medium', 'social', 'attitudes-persuasion', 'both')
q('Deindividuation refers to:', ['Maintaining personal identity in a group', 'Loss of self-awareness and self-restraint in group situations', 'Strong personal identity', 'Individual achievement'], 1, 'Anonymity in groups can lead to reduced self-control and increased impulsive behavior.', 'medium', 'social', 'group-behavior-prejudice', 'A')
q('Zimbardo Stanford prison experiment demonstrated:', ['Prisoners always rebel', 'Situational factors can powerfully influence behavior', 'Guards are always fair', 'Personality is the only factor'], 1, 'Assigned roles dramatically influenced behavior, showing the power of situations.', 'medium', 'social', 'social-influence-conformity', 'B')
q('The mere exposure effect indicates that:', ['Unfamiliar things are preferred', 'Repeated exposure to a stimulus increases liking for it', 'People dislike familiar things', 'Exposure has no effect on preference'], 1, 'Familiarity breeds liking — we prefer things we have seen before.', 'easy', 'social', 'attitudes-persuasion', 'both')
q('The just-world hypothesis is the belief that:', ['The world is inherently unfair', 'People get what they deserve', 'Justice systems always work', 'No one is ever punished'], 1, 'This belief can lead to victim-blaming: assuming bad things happen to bad people.', 'medium', 'social', 'group-behavior-prejudice', 'A')
q('Stereotype threat occurs when:', ['Stereotypes are eliminated', 'Awareness of a negative stereotype about one group impairs performance', 'Stereotypes improve performance', 'Only children are affected'], 1, 'Concern about confirming a stereotype can undermine test performance.', 'medium', 'social', 'group-behavior-prejudice', 'B')
q('Altruism is defined as:', ['Helping others for personal gain', 'Unselfish concern for others welfare', 'Competing with others', 'Avoiding social interaction'], 1, 'Altruism is helping behavior motivated by the desire to benefit others.', 'easy', 'social', 'group-behavior-prejudice', 'both')
q('The halo effect is the tendency to:', ['Judge specific traits negatively', 'Let an overall positive impression influence judgments of specific traits', 'Ignore first impressions', 'Only notice flaws'], 1, 'A positive general impression leads to positive specific assumptions.', 'easy', 'social', 'attitudes-persuasion', 'A')
q('Scapegoating involves:', ['Blaming an innocent group for problems', 'Helping minority groups', 'Avoiding conflict', 'Rational decision making'], 0, 'Frustration can lead to displaced aggression toward a convenient target group.', 'easy', 'social', 'group-behavior-prejudice', 'B')
q('Social facilitation means that the presence of others _____ performance on simple tasks:', ['Decreases', 'Improves', 'Has no effect on', 'Eliminates'], 1, 'Being observed enhances performance on easy/well-learned tasks but impairs complex ones.', 'medium', 'social', 'group-behavior-prejudice', 'both')

# ══════════════════════════════════════════════════════════════════
#  Write to file
# ══════════════════════════════════════════════════════════════════
content = FILE.read_text()
marker = "\n]\n\nexport function generateExitQuiz"
if marker not in content:
    raise SystemExit("Could not find insertion marker")

insert_block = "\n" + "\n".join(NEW_QS) + "\n"
new_content = content.replace(marker, insert_block + marker)
FILE.write_text(new_content)

import re
count = len(re.findall(r"correctAnswer:", new_content))
print(f"✅ AP Psychology pool now has {count} questions total (was 64)")
