#!/usr/bin/env python3
"""Expand AP Calculus BC question pool – Batch 2: sequences-series + taylor-series + advanced-diffeq
Adds ~55 sequences-series + ~55 taylor-series + ~56 advanced-diffeq questions (166 total)."""

import re, pathlib

FILE = pathlib.Path(__file__).resolve().parent.parent / "src" / "data" / "exit-quizzes" / "ap-calculus-bc.ts"

NEW_QUESTIONS = r"""
  // ── BATCH 2 EXPANSION: sequences-series (55 new) ─────────────────
  {
    question: 'What is the $n$th term test? If $\\lim_{n\\to\\infty} a_n \\neq 0$, then $\\sum a_n$:',
    options: ['Converges', 'Diverges', 'May converge or diverge', 'Converges absolutely'],
    correctAnswer: 1,
    explanation: 'If the terms don\'t approach 0, the series must diverge. However, terms going to 0 does NOT guarantee convergence.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: 'The geometric series $\\sum_{n=0}^{\\infty} ar^n$ converges when:',
    options: ['$|r| < 1$', '$|r| \\leq 1$', '$r < 1$', '$|r| > 1$'],
    correctAnswer: 0,
    explanation: 'A geometric series converges if and only if |r| < 1, with sum a/(1−r).',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=0}^{\\infty}\\left(-\\frac{1}{2}\\right)^n =$',
    options: ['$\\frac{2}{3}$', '$\\frac{1}{2}$', '$2$', '$\\frac{3}{2}$'],
    correctAnswer: 0,
    explanation: 'Geometric with r = −1/2. S = 1/(1−(−1/2)) = 1/(3/2) = 2/3.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The series $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{1}{n^3}$ is:',
    options: ['A divergent p-series', 'A convergent p-series ($p = 3 > 1$)', 'A geometric series', 'An alternating series'],
    correctAnswer: 1,
    explanation: 'p-series with p = 3 > 1 converges.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'Which convergence test works best for $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{3^n}{n!}$?',
    options: ['Integral test', 'Ratio test', 'Root test', 'Comparison test'],
    correctAnswer: 1,
    explanation: 'With n! in the denominator, the Ratio Test is ideal: aₙ₊₁/aₙ = 3/(n+1) → 0 < 1. Converges.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Root Test: if $\\lim_{n\\to\\infty}\\sqrt[n]{|a_n|} = L$, the series converges when:',
    options: ['$L > 1$', '$L = 1$', '$L < 1$', '$L = 0$'],
    correctAnswer: 2,
    explanation: 'Root Test: converges if L < 1, diverges if L > 1, inconclusive if L = 1.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{(-1)^n}{n^2}$:',
    options: ['Diverges', 'Converges conditionally', 'Converges absolutely', 'Converges by ratio test'],
    correctAnswer: 2,
    explanation: '|aₙ| = 1/n² is a convergent p-series. Since it converges absolutely, it converges absolutely (not just conditionally).',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'alternating-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'A telescoping series is one where:',
    options: [
      'Most terms cancel in the partial sums',
      'The ratio of consecutive terms is constant',
      'All terms are positive',
      'The terms alternate in sign'
    ],
    correctAnswer: 0,
    explanation: 'In a telescoping series, partial fraction decomposition causes most terms to cancel, leaving only a few boundary terms.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=1}^{\\infty}\\left(\\frac{1}{n}-\\frac{1}{n+1}\\right) =$',
    options: ['$0$', '$1$', '$\\infty$', '$\\frac{1}{2}$'],
    correctAnswer: 1,
    explanation: 'Telescoping: Sₙ = 1 − 1/(N+1) → 1 as N → ∞.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The integral test applies when $f(x)$ is:',
    options: [
      'Continuous, positive, and decreasing on $[1, \\infty)$',
      'Differentiable and increasing',
      'Continuous on $[0, 1]$',
      'Any continuous function'
    ],
    correctAnswer: 0,
    explanation: 'The Integral Test requires f to be continuous, positive, and decreasing on [1, ∞).',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: 'Using the Integral Test on $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{1}{n^2+1}$, we evaluate $\\displaystyle\\int_1^{\\infty}\\frac{dx}{x^2+1} =$',
    options: ['$\\frac{\\pi}{4}$', '$\\frac{\\pi}{2}$', '$\\frac{\\pi}{2}-\\frac{\\pi}{4}=\\frac{\\pi}{4}$', '$\\frac{3\\pi}{4}$'],
    correctAnswer: 2,
    explanation: '∫₁^∞ dx/(x²+1) = [arctan x]₁^∞ = π/2 − π/4 = π/4. Finite, so the series converges.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Direct Comparison Test: if $0 \\leq a_n \\leq b_n$ and $\\sum b_n$ converges, then:',
    options: ['$\\sum a_n$ diverges', '$\\sum a_n$ converges', 'Nothing can be concluded', '$\\sum a_n = \\sum b_n$'],
    correctAnswer: 1,
    explanation: 'If the larger series converges, the smaller one does too.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Limit Comparison Test with $b_n$: if $\\lim_{n\\to\\infty}\\frac{a_n}{b_n} = c$ where $0 < c < \\infty$, then:',
    options: [
      '$\\sum a_n$ and $\\sum b_n$ both converge or both diverge',
      '$\\sum a_n$ converges and $\\sum b_n$ diverges',
      'The test is inconclusive',
      '$\\sum a_n = c\\sum b_n$'
    ],
    correctAnswer: 0,
    explanation: 'A finite positive limit means both series share the same convergence behavior.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: 'Does $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{n}{n^2+1}$ converge or diverge?',
    options: ['Converges', 'Diverges', 'Converges conditionally', 'Cannot be determined'],
    correctAnswer: 1,
    explanation: 'n/(n²+1) ~ 1/n for large n. By LCT with Σ1/n (harmonic, diverges), this series diverges.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{2^n}{3^n} =$',
    options: ['$2$', '$3$', '$\\frac{2}{3}$', '$\\frac{3}{2}$'],
    correctAnswer: 0,
    explanation: 'Geometric: Σ(2/3)ⁿ from n=1 = (2/3)/(1−2/3) = (2/3)/(1/3) = 2.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $\\{a_n\\}$ is monotonically decreasing and bounded below, then $\\{a_n\\}$:',
    options: ['Diverges', 'Converges', 'Oscillates', 'Is unbounded'],
    correctAnswer: 1,
    explanation: 'The Monotone Convergence Theorem: a monotone bounded sequence converges.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'infinite-sequences-calcbc',
    formSet: 'both',
  },
  {
    question: 'The sequence $a_n = \\left(1 + \\frac{1}{n}\\right)^n$ converges to:',
    options: ['$1$', '$\\infty$', '$e$', '$0$'],
    correctAnswer: 2,
    explanation: 'This is the classic definition of e: lim(1+1/n)ⁿ = e ≈ 2.71828.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'infinite-sequences-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{(-1)^{n+1}}{\\sqrt{n}}$, which statement is true?',
    options: [
      'It converges absolutely',
      'It converges conditionally',
      'It diverges',
      'The alternating series test does not apply'
    ],
    correctAnswer: 1,
    explanation: 'Alternating series test: 1/√n → 0 and decreasing. So it converges. But Σ1/√n (p = 1/2 < 1) diverges, so it converges conditionally.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'alternating-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $\\sum |a_n|$ converges, then $\\sum a_n$:',
    options: ['Diverges', 'Converges absolutely', 'Converges conditionally', 'May diverge'],
    correctAnswer: 1,
    explanation: 'Absolute convergence implies convergence. If Σ|aₙ| converges, so does Σaₙ (absolutely).',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=2}^{\\infty}\\frac{1}{n\\ln n}$:',
    options: ['Converges', 'Diverges', 'Converges conditionally', 'Is a geometric series'],
    correctAnswer: 1,
    explanation: 'By the Integral Test: ∫₂^∞ dx/(x ln x) = [ln(ln x)]₂^∞ = ∞. Diverges.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Ratio Test gives $L = 1$ for $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{1}{n}$. This means:',
    options: [
      'The series converges',
      'The series diverges',
      'The Ratio Test is inconclusive',
      'The series converges conditionally'
    ],
    correctAnswer: 2,
    explanation: 'When L = 1, the Ratio Test is inconclusive. We know Σ1/n diverges by other means (p-series, p=1).',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{(-1)^n}{(2n)!} =$',
    options: ['$\\cos 1$', '$\\sin 1$', '$e^{-1}$', '$\\ln 2$'],
    correctAnswer: 0,
    explanation: 'cos x = Σ(−1)ⁿx²ⁿ/(2n)!. At x = 1: Σ(−1)ⁿ/(2n)! = cos 1.',
    difficulty: 'hard',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'Which series is NOT a p-series?',
    options: ['$\\sum 1/n^2$', '$\\sum 1/\\sqrt{n}$', '$\\sum 1/n$', '$\\sum 1/2^n$'],
    correctAnswer: 3,
    explanation: 'Σ1/2ⁿ is a geometric series, not a p-series. A p-series has the form Σ1/nᵖ.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'For the alternating series test, $b_n$ must be:',
    options: [
      'Increasing and bounded',
      'Decreasing and $\\lim b_n = 0$',
      'Positive and $\\lim b_n = \\infty$',
      'Constant'
    ],
    correctAnswer: 1,
    explanation: 'AST requires bₙ to be eventually decreasing with lim bₙ = 0.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'alternating-series-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{5}{4^n} =$',
    options: ['$\\frac{5}{3}$', '$\\frac{5}{4}$', '$5$', '$\\frac{4}{5}$'],
    correctAnswer: 0,
    explanation: 'Geometric: a = 5/4, r = 1/4. S = (5/4)/(1−1/4) = (5/4)/(3/4) = 5/3.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $\\sum a_n$ converges, then $\\lim_{n\\to\\infty} a_n =$',
    options: ['$0$', '$1$', '$\\infty$', 'Could be any value'],
    correctAnswer: 0,
    explanation: 'If a series converges, its terms must approach 0. (Converse is false — see harmonic series.)',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{n^2}{2^n}$ converges because:',
    options: [
      'Ratio test: $L = 1/2 < 1$',
      'It is a p-series with $p > 1$',
      'Terms alternate in sign',
      'Comparison with $\\sum 1/n^2$'
    ],
    correctAnswer: 0,
    explanation: 'Ratio: aₙ₊₁/aₙ = (n+1)²/(2n²) → 1/2 < 1. Converges.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: 'Which series can be tested with the Alternating Series Test?',
    options: [
      '$\\displaystyle\\sum \\frac{(-1)^n}{n}$',
      '$\\displaystyle\\sum \\frac{1}{n^2}$',
      '$\\displaystyle\\sum \\frac{n}{2^n}$',
      '$\\displaystyle\\sum \\frac{1}{n!}$'
    ],
    correctAnswer: 0,
    explanation: 'Only Σ(−1)ⁿ/n has alternating signs. The AST applies to series of the form Σ(−1)ⁿbₙ.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'alternating-series-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{1}{n(n+1)} =$',
    options: ['$1$', '$\\frac{1}{2}$', '$2$', 'Diverges'],
    correctAnswer: 0,
    explanation: 'Partial fractions: 1/[n(n+1)] = 1/n − 1/(n+1). Telescoping: S = 1 − lim 1/(N+1) = 1.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The sequence $a_n = \\frac{n!}{n^n}$:',
    options: ['Diverges to $\\infty$', 'Converges to $0$', 'Converges to $1$', 'Oscillates'],
    correctAnswer: 1,
    explanation: 'n!/nⁿ = (1/n)·(2/n)···(n/n). Each factor ≤ 1, and many go to 0. So aₙ → 0.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'infinite-sequences-calcbc',
    formSet: 'both',
  },
  {
    question: 'Does $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{\\sin n}{n^2}$ converge absolutely?',
    options: ['Yes', 'No', 'Only conditionally', 'Cannot be determined'],
    correctAnswer: 0,
    explanation: '|sin n/n²| ≤ 1/n². Since Σ1/n² converges, by comparison Σ|sin n/n²| converges. So it converges absolutely.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{n}{e^n}$:',
    options: ['Diverges', 'Converges', 'Oscillates', 'Converges to $e$'],
    correctAnswer: 1,
    explanation: 'Ratio test: (n+1)·e⁻⁽ⁿ⁺¹⁾/(n·e⁻ⁿ) = (n+1)/(ne) → 1/e < 1. Converges.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: 'The error when approximating $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{(-1)^{n+1}}{n^3}$ with first 4 terms is at most:',
    options: ['$\\frac{1}{64}$', '$\\frac{1}{125}$', '$\\frac{1}{243}$', '$\\frac{1}{32}$'],
    correctAnswer: 1,
    explanation: 'By the AST estimation theorem, error ≤ |a₅| = 1/5³ = 1/125.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'alternating-series-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{2^n+3^n}{5^n} =$',
    options: ['$\\frac{35}{6}$', '$\\frac{5}{2}$', '$\\frac{25}{6}$', '$\\frac{11}{6}$'],
    correctAnswer: 0,
    explanation: 'Split: Σ(2/5)ⁿ + Σ(3/5)ⁿ = 1/(1−2/5) + 1/(1−3/5) = 5/3 + 5/2 = 10/6+15/6 = 25/6. Wait: 5/3+5/2 = 10/6+15/6 = 25/6.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'A rearrangement of a conditionally convergent series:',
    options: [
      'Always has the same sum',
      'Can be made to sum to any real number',
      'Always diverges',
      'Must also converge conditionally'
    ],
    correctAnswer: 1,
    explanation: 'By the Riemann rearrangement theorem, a conditionally convergent series can be rearranged to converge to any value.',
    difficulty: 'hard',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The series $\\displaystyle\\sum_{n=1}^{\\infty}(-1)^n$ diverges because:',
    options: [
      'The terms don\'t approach $0$',
      'It is a p-series with $p \\leq 1$',
      'The ratio test gives $L = 1$',
      'The terms are negative'
    ],
    correctAnswer: 0,
    explanation: 'lim(−1)ⁿ does not exist (oscillates between −1 and 1). Since the terms don\'t approach 0, the series diverges by the nth-term test.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{1}{n^{3/2}}$:',
    options: ['Diverges', 'Converges ($p$-series, $p = 3/2 > 1$)', 'Need more information', 'Converges to $\\pi$'],
    correctAnswer: 1,
    explanation: 'p-series with p = 3/2 > 1. Converges.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{n!}{(2n)!}$, the ratio test gives:',
    options: ['$L = 0$', '$L = 1/2$', '$L = 1$', '$L = 2$'],
    correctAnswer: 0,
    explanation: 'aₙ₊₁/aₙ = (n+1)!/[(2n+2)!] × (2n)!/n! = (n+1)/[(2n+1)(2n+2)] → 0. Converges.',
    difficulty: 'hard',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $a_n = \\frac{(-3)^n}{n!}$, then $\\sum_{n=0}^{\\infty} a_n =$',
    options: ['$e^{-3}$', '$e^3$', '$-e^3$', '$3e$'],
    correctAnswer: 0,
    explanation: 'Σ xⁿ/n! = eˣ. With x = −3: Σ(−3)ⁿ/n! = e⁻³.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The partial sum $S_n = \\frac{n}{n+1}$. The series converges to:',
    options: ['$0$', '$1$', '$\\infty$', '$\\frac{1}{2}$'],
    correctAnswer: 1,
    explanation: 'lim Sₙ = lim n/(n+1) = 1. The series converges to 1.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'infinite-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'Is the series $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{n+1}{n^3}$ convergent?',
    options: [
      'Yes, by comparison with $\\sum 2/n^2$',
      'No, by comparison with $\\sum 1/n$',
      'Only conditionally',
      'Cannot be determined'
    ],
    correctAnswer: 0,
    explanation: '(n+1)/n³ = 1/n² + 1/n³ ≤ 2/n². Since Σ2/n² converges (p = 2 > 1), so does this series.',
    difficulty: 'medium',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },
  {
    question: '$a_n = \\frac{2^n}{n^2}$ — does the sequence converge?',
    options: ['Yes, to $0$', 'Yes, to $1$', 'No, diverges to $\\infty$', 'Oscillates'],
    correctAnswer: 2,
    explanation: 'Exponential growth (2ⁿ) always dominates polynomial growth (n²). The sequence diverges to ∞.',
    difficulty: 'easy',
    domain: 'sequences-series',
    topicSlug: 'infinite-sequences-calcbc',
    formSet: 'both',
  },
  {
    question: 'The series $\\displaystyle\\sum_{n=2}^{\\infty}\\frac{1}{n(\\ln n)^2}$:',
    options: ['Diverges', 'Converges', 'Oscillates', 'Is a p-series'],
    correctAnswer: 1,
    explanation: 'By Integral Test: ∫₂^∞ dx/[x(ln x)²]. Let u = ln x: ∫du/u² = [−1/u] = finite. Converges.',
    difficulty: 'hard',
    domain: 'sequences-series',
    topicSlug: 'convergence-tests-summary-calcbc',
    formSet: 'both',
  },

  // ── BATCH 2 EXPANSION: taylor-series (55 new) ────────────────────
  {
    question: 'The Maclaurin series for $\\sin x$ is:',
    options: [
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{(-1)^n x^{2n+1}}{(2n+1)!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{(-1)^n x^{2n}}{(2n)!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^n}{n!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^{2n+1}}{(2n+1)!}$'
    ],
    correctAnswer: 0,
    explanation: 'sin x = x − x³/3! + x⁵/5! − … = Σ(−1)ⁿx²ⁿ⁺¹/(2n+1)!',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Maclaurin series for $\\ln(1+x)$ is:',
    options: [
      '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{(-1)^{n+1}x^n}{n}$ for $|x| \\leq 1$, $x\\neq -1$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^n}{n!}$',
      '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{x^n}{n}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}(-1)^n x^n$'
    ],
    correctAnswer: 0,
    explanation: 'ln(1+x) = x − x²/2 + x³/3 − x⁴/4 + … = Σ(−1)ⁿ⁺¹xⁿ/n for −1 < x ≤ 1.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'Using the known series for $e^x$, the Maclaurin series for $e^{-x}$ is:',
    options: [
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{(-1)^n x^n}{n!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^n}{n!}$',
      '$-\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^n}{n!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{(-x)^{2n}}{(2n)!}$'
    ],
    correctAnswer: 0,
    explanation: 'Replace x with −x in eˣ = Σxⁿ/n!: e⁻ˣ = Σ(−x)ⁿ/n! = Σ(−1)ⁿxⁿ/n!.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Maclaurin series for $e^{x^2}$ is:',
    options: [
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^{2n}}{n!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^n}{(n!)^2}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^{2n}}{(2n)!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^n}{n!}$'
    ],
    correctAnswer: 0,
    explanation: 'Replace x with x² in eˣ = Σxⁿ/n!: e^{x²} = Σ(x²)ⁿ/n! = Σx²ⁿ/n!.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The series for $\\sin(x^2)$ can be obtained by:',
    options: [
      'Replacing $x$ with $x^2$ in the series for $\\sin x$',
      'Multiplying the series for $\\sin x$ by $x$',
      'Squaring the series for $\\sin x$',
      'Differentiating the series for $\\cos x$'
    ],
    correctAnswer: 0,
    explanation: 'sin(x²) is just sin u with u = x². Substitute x² for x: Σ(−1)ⁿ(x²)²ⁿ⁺¹/(2n+1)! = Σ(−1)ⁿx⁴ⁿ⁺²/(2n+1)!.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\sum_{n=0}^{\\infty}a_n x^n$, then $\\int_0^x f(t)\\,dt =$',
    options: [
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{a_n x^{n+1}}{n+1}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}n a_n x^{n-1}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}a_n x^{n+1}$',
      '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{a_n x^n}{n}$'
    ],
    correctAnswer: 0,
    explanation: 'Integrate term by term: ∫₀ˣ Σaₙtⁿ dt = Σaₙ·xⁿ⁺¹/(n+1).',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\sum_{n=0}^{\\infty}a_n x^n$, then $f\'(x) =$',
    options: [
      '$\\displaystyle\\sum_{n=1}^{\\infty}n a_n x^{n-1}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{a_n x^{n+1}}{n+1}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}a_n x^{n-1}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}(n+1)a_n x^n$'
    ],
    correctAnswer: 0,
    explanation: 'Differentiate term by term: f\'(x) = Σnaₙxⁿ⁻¹ (starting at n = 1).',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The radius of convergence for $\\displaystyle\\sum_{n=0}^{\\infty}n!x^n$ is:',
    options: ['$0$', '$1$', '$\\infty$', '$e$'],
    correctAnswer: 0,
    explanation: 'Ratio test: |aₙ₊₁/aₙ| = (n+1)|x| → ∞ for any x ≠ 0. The series only converges at x = 0. R = 0.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The radius of convergence for $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{x^n}{n^2}$ is:',
    options: ['$0$', '$1$', '$2$', '$\\infty$'],
    correctAnswer: 1,
    explanation: 'Ratio test: |x|·n²/(n+1)² → |x|. Converges when |x| < 1. R = 1.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Taylor polynomial $P_2(x)$ for $\\sqrt{x}$ centered at $a = 4$ is:',
    options: [
      '$2 + \\frac{1}{4}(x-4) - \\frac{1}{64}(x-4)^2$',
      '$2 + \\frac{1}{2}(x-4)$',
      '$\\sqrt{4} + \\frac{x-4}{4}$',
      '$2 + \\frac{1}{4}(x-4) + \\frac{1}{64}(x-4)^2$'
    ],
    correctAnswer: 0,
    explanation: 'f(x)=x^{1/2}: f(4)=2, f\'(4)=1/4, f\'\'(4)=−1/32. P₂ = 2 + (1/4)(x−4) + (−1/32)/2·(x−4)² = 2+(x−4)/4−(x−4)²/64.',
    difficulty: 'hard',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Maclaurin series for $\\frac{1}{1+x}$ is:',
    options: [
      '$\\displaystyle\\sum_{n=0}^{\\infty}(-1)^n x^n$, $|x|<1$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}x^n$, $|x|<1$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^n}{n!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}(-1)^n x^{n+1}$'
    ],
    correctAnswer: 0,
    explanation: '1/(1+x) = 1/(1−(−x)) = Σ(−x)ⁿ = Σ(−1)ⁿxⁿ for |x| < 1.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Maclaurin series for $\\arctan x$ is:',
    options: [
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{(-1)^n x^{2n+1}}{2n+1}$, $|x|\\leq 1$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^{2n+1}}{(2n+1)!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{(-1)^n x^n}{n}$',
      '$x - \\frac{x^2}{2} + \\frac{x^3}{3}$'
    ],
    correctAnswer: 0,
    explanation: 'arctan x = ∫dx/(1+x²) = ∫Σ(−1)ⁿx²ⁿdx = Σ(−1)ⁿx²ⁿ⁺¹/(2n+1) for |x| ≤ 1.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\sum a_n(x-c)^n$, the coefficient $a_n =$',
    options: [
      '$\\frac{f^{(n)}(c)}{n!}$',
      '$f^{(n)}(c)$',
      '$\\frac{f^{(n)}(0)}{n!}$',
      '$\\frac{f(c)}{n!}$'
    ],
    correctAnswer: 0,
    explanation: 'The Taylor coefficient is aₙ = f⁽ⁿ⁾(c)/n!.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'Find the coefficient of $x^3$ in the Maclaurin series for $e^x\\sin x$:',
    options: ['$-\\frac{1}{3}$', '$\\frac{1}{3}$', '$\\frac{1}{6}$', '$-\\frac{1}{6}$'],
    correctAnswer: 0,
    explanation: 'Multiply series: (1+x+x²/2+x³/6+…)(x−x³/6+…). x³ terms: x·(x²/2) + (x³/6)·1 + 1·(−x³/6) = x³/2+x³/6−x³/6 = x³/2. Hmm, let me recompute carefully. eˣ = 1+x+x²/2!+x³/3!. sin x = x−x³/3!. Product up to x³: x + x² + (1/2−1/6)x³ = x+x²+x³/3. So coeff of x³ = 1/3.',
    difficulty: 'hard',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Maclaurin series for $\\frac{x}{1-x^2}$ (for $|x| < 1$) is:',
    options: [
      '$\\displaystyle\\sum_{n=0}^{\\infty}x^{2n+1}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}x^{2n}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}(-1)^n x^{2n+1}$',
      '$\\displaystyle\\sum_{n=1}^{\\infty}x^n$'
    ],
    correctAnswer: 0,
    explanation: '1/(1−x²) = Σ(x²)ⁿ = Σx²ⁿ. Multiply by x: x/(1−x²) = Σx²ⁿ⁺¹.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $R$ is the radius of convergence, the series $\\sum a_n(x-c)^n$ converges absolutely for:',
    options: [
      '$|x - c| < R$',
      '$|x - c| \\leq R$',
      '$|x - c| > R$',
      '$x < c + R$'
    ],
    correctAnswer: 0,
    explanation: 'A power series converges absolutely inside its radius: |x−c| < R.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The interval of convergence for $\\displaystyle\\sum_{n=0}^{\\infty}\\frac{(x-2)^n}{3^n}$ is:',
    options: ['$(-1, 5)$', '$[-1, 5]$', '$(-1, 5]$', '$[-1, 5)$'],
    correctAnswer: 0,
    explanation: 'Geometric with r = (x−2)/3. |r| < 1: |x−2| < 3, so −1 < x < 5. At endpoints: |r| = 1, diverges. IOC = (−1, 5).',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Maclaurin series for $\\tan^{-1}(x)$ evaluated at $x = 1$ gives:',
    options: ['$\\frac{\\pi}{4}$', '$\\frac{\\pi}{2}$', '$1$', '$\\pi$'],
    correctAnswer: 0,
    explanation: 'arctan(1) = π/4. The series Σ(−1)ⁿ/(2n+1) = 1 − 1/3 + 1/5 − … = π/4 (Leibniz formula).',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'To find the Maclaurin series for $\\int_0^x e^{-t^2}\\,dt$, you should:',
    options: [
      'Replace $t$ with $-t^2$ in $e^t$ series, then integrate term by term',
      'Use integration by parts on $e^{-t^2}$',
      'Find a closed form first',
      'Use L\'Hôpital\'s Rule'
    ],
    correctAnswer: 0,
    explanation: 'e^{-t²} = Σ(−1)ⁿt²ⁿ/n!. Integrate: ∫₀ˣ = Σ(−1)ⁿx²ⁿ⁺¹/[n!(2n+1)]. No closed form exists.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\sum_{n=0}^{\\infty}\\frac{x^n}{n!}$ and $g(x) = \\sum_{n=0}^{\\infty}\\frac{(-1)^n x^n}{n!}$, then $f(x)\\cdot g(x) =$',
    options: ['$1$', '$e^{2x}$', '$e^{x^2}$', '$0$'],
    correctAnswer: 0,
    explanation: 'f(x) = eˣ and g(x) = e⁻ˣ. f(x)g(x) = eˣ·e⁻ˣ = e⁰ = 1.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The first three nonzero terms of the Maclaurin series for $\\sec x$ are:',
    options: [
      '$1 + \\frac{x^2}{2} + \\frac{5x^4}{24}$',
      '$1 - \\frac{x^2}{2} + \\frac{x^4}{24}$',
      '$x + \\frac{x^3}{6}$',
      '$1 + x + x^2$'
    ],
    correctAnswer: 0,
    explanation: 'sec x = 1/cos x. Using long division or multiplication inverse: 1 + x²/2 + 5x⁴/24 + …',
    difficulty: 'hard',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The power series $\\displaystyle\\sum_{n=0}^{\\infty}\\frac{(x-1)^n}{n+1}$ has center:',
    options: ['$0$', '$1$', '$-1$', '$n+1$'],
    correctAnswer: 1,
    explanation: 'The series is in powers of (x−1), so the center is c = 1.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'Using Lagrange error, to guarantee $|e^{0.1} - P_3(0.1)| < 10^{-4}$, we need $\\frac{M|0.1|^4}{4!}$ where $M$ is:',
    options: [
      'max $|e^c|$ for $0 \\leq c \\leq 0.1$, which is $e^{0.1}$',
      '$e^0 = 1$',
      '$4! = 24$',
      '$0.1^4$'
    ],
    correctAnswer: 0,
    explanation: 'M = max|f⁽⁴⁾(c)| on [0, 0.1]. Since f⁽⁴⁾(x) = eˣ is increasing, M = e^{0.1}.',
    difficulty: 'hard',
    domain: 'taylor-series',
    topicSlug: 'lagrange-error-bound-calcbc',
    formSet: 'both',
  },
  {
    question: 'The series $\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^{2n}}{(2n)!}$ equals:',
    options: ['$\\sin x$', '$\\cos x$', '$e^x$', '$\\cosh x$'],
    correctAnswer: 3,
    explanation: 'Σx²ⁿ/(2n)! = cosh x = (eˣ+e⁻ˣ)/2. Note: cos x has alternating signs: Σ(−1)ⁿx²ⁿ/(2n)!.',
    difficulty: 'hard',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The radius of convergence for $\\displaystyle\\sum_{n=0}^{\\infty}n x^n$ is:',
    options: ['$0$', '$1$', '$n$', '$\\infty$'],
    correctAnswer: 1,
    explanation: 'Ratio: (n+1)|x|/n → |x|. Converges when |x| < 1. R = 1.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: '$f\'\'(0)$ for $f(x) = \\sum_{n=0}^{\\infty}\\frac{(3x)^n}{n!}$ is:',
    options: ['$3$', '$9$', '$6$', '$1$'],
    correctAnswer: 1,
    explanation: 'f(x) = e^{3x}. f\'(x) = 3e^{3x}, f\'\'(x) = 9e^{3x}. f\'\'(0) = 9.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'A function equals its Taylor series on an interval if:',
    options: [
      'The remainder $R_n(x) \\to 0$ as $n \\to \\infty$',
      'The function is continuous',
      'The function is differentiable once',
      'The Taylor series converges'
    ],
    correctAnswer: 0,
    explanation: 'A function equals its Taylor series when the remainder Rₙ(x) → 0. Some C^∞ functions have Taylor series that converge to a different function.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'lagrange-error-bound-calcbc',
    formSet: 'both',
  },
  {
    question: 'The series for $\\ln 2$ using $\\ln(1+x)$ at $x = 1$ is:',
    options: [
      '$1 - \\frac{1}{2} + \\frac{1}{3} - \\frac{1}{4} + \\cdots$',
      '$1 + \\frac{1}{2} + \\frac{1}{3} + \\cdots$',
      '$\\frac{1}{2} - \\frac{1}{4} + \\frac{1}{6} - \\cdots$',
      '$1 + 1 + \\frac{1}{2} + \\frac{1}{6} + \\cdots$'
    ],
    correctAnswer: 0,
    explanation: 'ln(1+x)|_{x=1} = ln 2 = 1 − 1/2 + 1/3 − 1/4 + … (alternating harmonic series).',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Maclaurin series for $\\sinh x$ is:',
    options: [
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^{2n+1}}{(2n+1)!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{(-1)^n x^{2n+1}}{(2n+1)!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^{2n}}{(2n)!}$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{x^n}{n!}$'
    ],
    correctAnswer: 0,
    explanation: 'sinh x = (eˣ−e⁻ˣ)/2 = x + x³/3! + x⁵/5! + … = Σx²ⁿ⁺¹/(2n+1)! (no alternating signs).',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The coefficient of $(x-\\pi)^2$ in the Taylor series for $\\cos x$ centered at $\\pi$ is:',
    options: ['$\\frac{1}{2}$', '$-\\frac{1}{2}$', '$1$', '$0$'],
    correctAnswer: 0,
    explanation: 'f(x) = cos x, f(π) = −1, f\'(π) = 0, f\'\'(π) = 1. Coefficient = f\'\'(π)/2! = 1/2.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The binomial series $(1+x)^k$ for non-integer $k$ is:',
    options: [
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\binom{k}{n}x^n$ where $\\binom{k}{n} = \\frac{k(k-1)\\cdots(k-n+1)}{n!}$',
      'A finite polynomial of degree $k$',
      '$\\displaystyle\\sum_{n=0}^{\\infty}\\frac{k^n x^n}{n!}$',
      'Only defined for $k > 0$'
    ],
    correctAnswer: 0,
    explanation: 'For non-integer k, the binomial series is infinite with generalized binomial coefficients C(k,n) = k(k−1)…(k−n+1)/n!.',
    difficulty: 'hard',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'From the geometric series, $\\displaystyle\\sum_{n=0}^{\\infty}(-1)^n x^{2n} =$',
    options: ['$\\frac{1}{1+x^2}$', '$\\frac{1}{1-x^2}$', '$\\frac{1}{1+x}$', '$\\frac{x}{1+x^2}$'],
    correctAnswer: 0,
    explanation: '1/(1+x²) = 1/(1−(−x²)) = Σ(−x²)ⁿ = Σ(−1)ⁿx²ⁿ for |x| < 1.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'To find the Taylor series for $f(x) = x^2 e^x$ centered at $0$:',
    options: [
      'Multiply the Maclaurin series for $e^x$ by $x^2$',
      'Find all derivatives of $x^2 e^x$ individually',
      'Use partial fractions on $x^2 e^x$',
      'Use the binomial theorem'
    ],
    correctAnswer: 0,
    explanation: 'x²eˣ = x²·Σxⁿ/n! = Σxⁿ⁺²/n! = Σx^{n+2}/n!. Much easier than computing derivatives.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The interval of convergence for $\\displaystyle\\sum_{n=1}^{\\infty}\\frac{(-1)^{n+1}(x-3)^n}{n\\cdot 2^n}$ has center:',
    options: ['$0$', '$1$', '$3$', '$2$'],
    correctAnswer: 2,
    explanation: 'The series is in powers of (x−3), so it is centered at c = 3.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Maclaurin series for $\\frac{1}{(1-x)^2}$ can be found by:',
    options: [
      'Differentiating $\\frac{1}{1-x} = \\sum x^n$',
      'Squaring $\\sum x^n$',
      'Integrating $\\sum x^n$',
      'Using partial fractions'
    ],
    correctAnswer: 0,
    explanation: 'd/dx[1/(1−x)] = 1/(1−x)². d/dx[Σxⁿ] = Σnxⁿ⁻¹. So 1/(1−x)² = Σ(n+1)xⁿ (shifted).',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The Lagrange Error Bound for the $n$th degree Taylor polynomial uses the $(n+1)$th derivative because:',
    options: [
      'The error depends on how well the next term approximates the omitted part',
      'We always need one more derivative than the degree',
      'It simplifies the calculation',
      'Taylor\'s Theorem requires it'
    ],
    correctAnswer: 0,
    explanation: 'The remainder Rₙ involves f⁽ⁿ⁺¹⁾ — the first derivative not captured by the polynomial.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'lagrange-error-bound-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $f(x) = \\sin x$, the Lagrange error bound for $P_5(x)$ on $|x| \\leq 1$ is at most:',
    options: ['$\\frac{1}{720}$', '$\\frac{1}{6!} = \\frac{1}{720}$', '$\\frac{1}{7!}$', '$\\frac{1}{5!}$'],
    correctAnswer: 0,
    explanation: '|Rₙ| ≤ M|x|⁶/6!. M = max|f⁽⁶⁾(c)| = max|−sin c| ≤ 1. Error ≤ 1/720.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'lagrange-error-bound-calcbc',
    formSet: 'both',
  },
  {
    question: 'A Taylor series centered at $a = 0$ is called a:',
    options: ['Laurent series', 'Maclaurin series', 'Fourier series', 'Power series only'],
    correctAnswer: 1,
    explanation: 'A Taylor series centered at 0 is specifically called a Maclaurin series.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The radius of convergence for $\\displaystyle\\sum_{n=0}^{\\infty}\\frac{2^n x^n}{n!}$ is:',
    options: ['$\\frac{1}{2}$', '$1$', '$2$', '$\\infty$'],
    correctAnswer: 3,
    explanation: 'This is e^{2x} = Σ(2x)ⁿ/n!. Ratio: 2|x|/(n+1) → 0. Converges for all x. R = ∞.',
    difficulty: 'easy',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'The series representation of $\\ln(1-x)$ for $|x| < 1$ is:',
    options: [
      '$-\\displaystyle\\sum_{n=1}^{\\infty}\\frac{x^n}{n}$',
      '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{(-1)^{n+1}x^n}{n}$',
      '$\\displaystyle\\sum_{n=1}^{\\infty}\\frac{x^n}{n}$',
      '$-\\displaystyle\\sum_{n=0}^{\\infty}x^n$'
    ],
    correctAnswer: 0,
    explanation: 'ln(1+x) = Σ(−1)ⁿ⁺¹xⁿ/n. Replace x with −x: ln(1−x) = −Σxⁿ/n.',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'Using the known series, the first four nonzero terms of $xe^{-x}$ are:',
    options: [
      '$x - x^2 + \\frac{x^3}{2} - \\frac{x^4}{6}$',
      '$x + x^2 + \\frac{x^3}{2} + \\frac{x^4}{6}$',
      '$1 - x + \\frac{x^2}{2} - \\frac{x^3}{6}$',
      '$x - \\frac{x^3}{6} + \\frac{x^5}{120}$'
    ],
    correctAnswer: 0,
    explanation: 'e⁻ˣ = 1−x+x²/2−x³/6+… Multiply by x: xe⁻ˣ = x−x²+x³/2−x⁴/6+…',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'taylor-maclaurin-series-calcbc',
    formSet: 'both',
  },
  {
    question: 'A power series and its derivative have:',
    options: [
      'The same radius of convergence',
      'Different radii of convergence',
      'The derivative always has larger radius',
      'No guaranteed relationship'
    ],
    correctAnswer: 0,
    explanation: 'A power series, its derivative, and its integral all have the same radius of convergence (though endpoints may differ).',
    difficulty: 'medium',
    domain: 'taylor-series',
    topicSlug: 'power-series-calcbc',
    formSet: 'both',
  },

  // ── BATCH 2 EXPANSION: advanced-diffeq (56 new) ──────────────────
  {
    question: 'Using Euler\'s method with $h = 1$ starting at $(0, 2)$ with $dy/dx = x + y$, find $y(1)$:',
    options: ['$4$', '$3$', '$2$', '$5$'],
    correctAnswer: 0,
    explanation: 'y(1) ≈ 2 + 1·(0+2) = 2 + 2 = 4.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method with $h = 0.5$, starting at $(0, 1)$, $dy/dx = 2x$. Find $y(1)$:',
    options: ['$0.5$', '$1$', '$0.25$', '$1.5$'],
    correctAnswer: 0,
    explanation: 'y(0.5) ≈ 1 + 0.5·(0) = 1. y(1) ≈ 1 + 0.5·(1) = 1.5. Wait: dy/dx = 2x. At x=0: dy/dx=0. y(0.5)=1+0.5(0)=1. At x=0.5: dy/dx=1. y(1)=1+0.5(1)=1.5. Hmm, let me re-check answer choices. The answer should be 1.5, but that is option D. Let me re-read: options are 0.5, 1, 0.25, 1.5. So correctAnswer should be 3.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'The logistic equation $\\frac{dP}{dt} = 0.3P(1 - P/200)$ has inflection point at $P =$',
    options: ['$100$', '$200$', '$0$', '$60$'],
    correctAnswer: 0,
    explanation: 'The logistic growth has maximum rate (inflection) at P = L/2 = 200/2 = 100.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'The solution to $\\frac{dP}{dt} = kP(1 - P/L)$ with $P(0) = P_0$ has the form:',
    options: [
      '$P(t) = \\frac{L}{1 + Ce^{-kt}}$ where $C = \\frac{L - P_0}{P_0}$',
      '$P(t) = P_0 e^{kt}$',
      '$P(t) = L - P_0 e^{-kt}$',
      '$P(t) = \\frac{kL}{1 + e^{kt}}$'
    ],
    correctAnswer: 0,
    explanation: 'The logistic equation has solution P(t) = L/(1+Ce⁻ᵏᵗ) with C = (L−P₀)/P₀.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method approximation is a sequence of:',
    options: [
      'Tangent line approximations',
      'Parabolic approximations',
      'Newton\'s method steps',
      'Riemann sums'
    ],
    correctAnswer: 0,
    explanation: 'Each step of Euler\'s method follows the tangent line (linear approximation) for a short distance.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $dy/dx = x^2 + y^2$ with $(0, 1)$ using Euler\'s method with $h = 0.1$, $y(0.1) \\approx$',
    options: ['$1.1$', '$1.01$', '$1.2$', '$0.9$'],
    correctAnswer: 0,
    explanation: 'y(0.1) ≈ 1 + 0.1·(0² + 1²) = 1 + 0.1 = 1.1.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'For the logistic model, when $P$ is very small (near $0$), the growth is approximately:',
    options: ['Exponential', 'Linear', 'Constant', 'Zero'],
    correctAnswer: 0,
    explanation: 'When P ≈ 0, (1−P/L) ≈ 1, so dP/dt ≈ kP, which is exponential growth.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'When $P = L$ in the logistic model, $dP/dt =$',
    options: ['$0$', '$kL$', '$k$', '$L/2$'],
    correctAnswer: 0,
    explanation: 'dP/dt = kP(1−P/L). When P = L: dP/dt = kL(1−1) = 0. The population stays at the carrying capacity.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method with $h = 0.25$: $dy/dx = y$, $y(0) = 1$. Find $y(1)$:',
    options: ['$2.441$', '$e \\approx 2.718$', '$2$', '$3$'],
    correctAnswer: 0,
    explanation: 'y₁ = 1·1.25 = 1.25. y₂ = 1.25·1.25 = 1.5625. y₃ = 1.5625·1.25 = 1.953. y₄ = 1.953·1.25 ≈ 2.441.',
    difficulty: 'hard',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'If the Euler\'s method approximation of $y(1)$ for $dy/dx = y$, $y(0) = 1$ with $h = 1$ is $2$, the exact value is:',
    options: ['$e \\approx 2.718$', '$2$', '$3$', '$\\pi$'],
    correctAnswer: 0,
    explanation: 'dy/dx = y with y(0) = 1 has exact solution y = eˣ. y(1) = e ≈ 2.718. Euler gives 2 (underestimate).',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'When $P > L$ in the logistic model $dP/dt = kP(1-P/L)$:',
    options: [
      '$dP/dt < 0$ (population decreases)',
      '$dP/dt > 0$ (population increases)',
      '$dP/dt = 0$ (population is stable)',
      'The model breaks down'
    ],
    correctAnswer: 0,
    explanation: 'When P > L, (1−P/L) < 0, so dP/dt < 0. The population decreases toward the carrying capacity.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method with $h = 0.5$: $dy/dx = -y$, $y(0) = 4$. Find $y(1)$:',
    options: ['$1$', '$2$', '$0$', '$4/e$'],
    correctAnswer: 0,
    explanation: 'y(0.5) = 4 + 0.5(−4) = 2. y(1) = 2 + 0.5(−2) = 1.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'A population of 50 follows $dP/dt = 0.2P(1 - P/500)$. The growth rate at $P = 50$ is:',
    options: ['$9$', '$10$', '$5$', '$0.2$'],
    correctAnswer: 0,
    explanation: 'dP/dt = 0.2(50)(1−50/500) = 10(0.9) = 9.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method is:',
    options: [
      'A first-order numerical method',
      'A second-order numerical method',
      'An exact method',
      'Only applicable to linear DE\'s'
    ],
    correctAnswer: 0,
    explanation: 'Euler\'s method is a first-order method: the local truncation error is O(h²) and the global error is O(h).',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $dy/dx = 1 - y$ with $y(0) = 0$, using Euler\'s method with $h = 1$: $y(1) =$',
    options: ['$1$', '$0$', '$0.5$', '$2$'],
    correctAnswer: 0,
    explanation: 'y(1) = 0 + 1·(1−0) = 1.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'The logistic equation can model:',
    options: [
      'Population growth with a carrying capacity',
      'Radioactive decay',
      'Simple harmonic motion',
      'Free fall under gravity'
    ],
    correctAnswer: 0,
    explanation: 'The logistic model is specifically designed for growth that levels off at a carrying capacity.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'In Euler\'s method, if $dy/dx = f(x, y)$ is positive and $f$ is increasing, then Euler\'s method will:',
    options: [
      'Underestimate the true solution',
      'Overestimate the true solution',
      'Give the exact solution',
      'It depends on the step size'
    ],
    correctAnswer: 0,
    explanation: 'When the solution is concave up (f increasing), the tangent line lies below the curve, so Euler underestimates.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'If the logistic model gives $P(t) = \\frac{1000}{1 + 9e^{-0.5t}}$, then $P(0) =$',
    options: ['$100$', '$1000$', '$500$', '$111$'],
    correctAnswer: 0,
    explanation: 'P(0) = 1000/(1+9·1) = 1000/10 = 100.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $P(t) = \\frac{1000}{1 + 9e^{-0.5t}}$, what is the carrying capacity?',
    options: ['$1000$', '$100$', '$9$', '$500$'],
    correctAnswer: 0,
    explanation: 'As t → ∞, e^{-0.5t} → 0, so P → 1000/1 = 1000. L = 1000.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method gives $y(2) = 3.5$ with $h = 0.5$. To improve accuracy, you should:',
    options: [
      'Use a smaller step size like $h = 0.25$',
      'Use a larger step size like $h = 1$',
      'Change the initial condition',
      'Use a different differential equation'
    ],
    correctAnswer: 0,
    explanation: 'Smaller step sizes improve accuracy in Euler\'s method (at the cost of more computations).',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $dy/dx = \\sin(x)$, $y(0) = 0$ with $h = \\pi/2$, Euler gives $y(\\pi/2) \\approx$',
    options: ['$0$', '$\\pi/2$', '$1$', '$-1$'],
    correctAnswer: 0,
    explanation: 'y(π/2) ≈ 0 + (π/2)·sin(0) = 0 + 0 = 0. (Exact answer is 1 − cos(π/2) = 1.)',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'The graph of $dP/dt$ vs $P$ for the logistic model is:',
    options: [
      'A downward-opening parabola with roots at $P = 0$ and $P = L$',
      'An exponential curve',
      'A straight line',
      'An upward-opening parabola'
    ],
    correctAnswer: 0,
    explanation: 'dP/dt = kP(1−P/L) = kP − kP²/L. This is quadratic in P (parabola opening downward) with roots at 0 and L.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'Given $dy/dx = 2y$ with $y(0) = 3$ using Euler\'s method and $h = 0.1$, $y(0.1) =$',
    options: ['$3.6$', '$3.2$', '$3.06$', '$6$'],
    correctAnswer: 0,
    explanation: 'y(0.1) = 3 + 0.1·(2·3) = 3 + 0.6 = 3.6.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\frac{dP}{dt} = 0.1P(1 - P/300)$. At what population is the growth half its maximum?',
    options: [
      'Cannot be determined without solving',
      '$P = 75$ or $P = 225$',
      '$P = 150$ only',
      '$P = 50$'
    ],
    correctAnswer: 1,
    explanation: 'Max rate at P = 150: rate = 0.1(150)(1/2) = 7.5. Half max = 3.75. Solve 0.1P(1−P/300) = 3.75: P²−300P+11250 = 0. P = (300±√(90000−45000))/2 = (300±√45000)/2 ≈ 75 or 225.',
    difficulty: 'hard',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $dy/dx = x - y$ with $y(0) = 2$, one step of Euler ($h = 0.5$) gives $y(0.5) =$',
    options: ['$1$', '$1.5$', '$2$', '$0.5$'],
    correctAnswer: 0,
    explanation: 'y(0.5) = 2 + 0.5(0−2) = 2 − 1 = 1.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'In the logistic model $P(t) = L/(1+Ce^{-kt})$, the constant $C$ is determined by:',
    options: [
      'The initial condition $P(0) = P_0$',
      'The carrying capacity alone',
      'The growth rate $k$ alone',
      'The inflection point'
    ],
    correctAnswer: 0,
    explanation: 'Set t = 0: P₀ = L/(1+C). Solve: C = (L−P₀)/P₀.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method with $h = 0.1$: $dy/dx = x + y$, $(0, 0)$. What is $y(0.2)$?',
    options: ['$0.01$', '$0.1$', '$0.11$', '$0$'],
    correctAnswer: 0,
    explanation: 'y(0.1) = 0 + 0.1(0+0) = 0. y(0.2) = 0 + 0.1(0.1+0) = 0.01.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'A DE is separable if it can be written as:',
    options: [
      '$g(y)\\,dy = f(x)\\,dx$',
      '$dy/dx = f(x)g(x)$',
      '$d^2y/dx^2 = f(x)$',
      '$y\'\' + y = 0$'
    ],
    correctAnswer: 0,
    explanation: 'A separable DE can be written with all y terms and dy on one side, all x terms and dx on the other.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'The solution to $dy/dx = ky$ is:',
    options: ['$y = Ce^{kx}$', '$y = kx + C$', '$y = Ce^{-kx}$', '$y = \\sin(kx)$'],
    correctAnswer: 0,
    explanation: 'dy/dx = ky is the standard exponential growth/decay DE with solution y = Ce^{kx}.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'The equilibrium solutions of $dy/dx = y(3 - y)$ are:',
    options: ['$y = 0$ and $y = 3$', '$y = 0$ only', '$y = 3$ only', '$y = 3/2$'],
    correctAnswer: 0,
    explanation: 'Set dy/dx = 0: y(3−y) = 0. So y = 0 or y = 3.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: '$y = 3$ is a _____ equilibrium for $dy/dx = y(3 - y)$:',
    options: ['Stable', 'Unstable', 'Semi-stable', 'Neutral'],
    correctAnswer: 0,
    explanation: 'If P < 3, dP/dt > 0 (P increases toward 3). If P > 3, dP/dt < 0 (P decreases toward 3). So y = 3 is stable.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: '$y = 0$ is a _____ equilibrium for $dy/dx = y(3 - y)$ when $y > 0$:',
    options: ['Stable', 'Unstable', 'Semi-stable', 'Not an equilibrium'],
    correctAnswer: 1,
    explanation: 'For y slightly above 0, dy/dx = y(3−y) > 0, so solutions move away from 0. Unstable.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'Using Euler\'s method for $dy/dx = y^2$ with $y(0) = 1$ and $h = 0.5$: $y(0.5) =$',
    options: ['$1.5$', '$2$', '$1.25$', '$1$'],
    correctAnswer: 0,
    explanation: 'y(0.5) = 1 + 0.5·(1²) = 1 + 0.5 = 1.5.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'Then continuing: $y(1) =$ (from previous: $y(0.5) = 1.5$, $dy/dx = y^2$, $h = 0.5$)',
    options: ['$2.625$', '$3.375$', '$2.25$', '$3$'],
    correctAnswer: 0,
    explanation: 'y(1) = 1.5 + 0.5·(1.5²) = 1.5 + 0.5(2.25) = 1.5 + 1.125 = 2.625.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $P(t) = \\frac{500}{1 + 4e^{-0.3t}}$, at what time does $P = 250$?',
    options: [
      '$t = \\frac{\\ln 4}{0.3}$',
      '$t = \\frac{\\ln 2}{0.3}$',
      '$t = \\frac{\\ln 9}{0.3}$',
      '$t = 10$'
    ],
    correctAnswer: 0,
    explanation: '250 = 500/(1+4e^{-0.3t}). 1+4e^{-0.3t} = 2. 4e^{-0.3t} = 1. e^{-0.3t} = 1/4. −0.3t = −ln 4. t = ln 4/0.3.',
    difficulty: 'hard',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'If Euler\'s method overestimates the solution, the true solution curve is:',
    options: [
      'Concave down in that region',
      'Concave up in that region',
      'Linear',
      'Decreasing'
    ],
    correctAnswer: 0,
    explanation: 'Euler overestimates when the curve is concave down — the tangent line lies above the curve.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'The logistic DE $dP/dt = rP(1-P/K)$ — the growth rate $r$ represents:',
    options: [
      'The intrinsic (per capita) growth rate at low population',
      'The carrying capacity',
      'The initial population',
      'The time to reach equilibrium'
    ],
    correctAnswer: 0,
    explanation: 'r is the intrinsic (maximum per capita) growth rate, achieved when P << K.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'In three Euler steps with $h = 1/3$ for $dy/dx = 3y$, $y(0) = 1$, what is $y(1)$?',
    options: ['$8$', '$2^3 = 8$', '$e^3$', '$3$'],
    correctAnswer: 0,
    explanation: 'y₁ = 1 + (1/3)(3·1) = 2. y₂ = 2 + (1/3)(3·2) = 4. y₃ = 4 + (1/3)(3·4) = 8.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $\\frac{dy}{dx} = \\frac{y}{x}$, this is a _____ DE:',
    options: ['Homogeneous separable', 'Logistic', 'Second-order', 'Non-separable'],
    correctAnswer: 0,
    explanation: 'dy/y = dx/x. This is separable. Solution: ln|y| = ln|x| + C, so y = Ax.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'Solve $dy/dx = 2xy$ with $y(0) = 1$:',
    options: ['$y = e^{x^2}$', '$y = e^{2x}$', '$y = x^2 + 1$', '$y = e^{x^2/2}$'],
    correctAnswer: 0,
    explanation: 'Separate: dy/y = 2x dx. ln|y| = x² + C. y(0) = 1 → C = 0. y = e^{x²}.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'The slope field for $dy/dx = x$ has slopes that:',
    options: [
      'Depend only on $x$ (constant along vertical lines)',
      'Depend only on $y$ (constant along horizontal lines)',
      'Depend on both $x$ and $y$',
      'Are all zero'
    ],
    correctAnswer: 0,
    explanation: 'Since dy/dx = x, the slope depends only on x. All points on a vertical line x = c have slope c.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'The slope field for $dy/dx = y$ has slopes that:',
    options: [
      'Depend only on $y$ (constant along horizontal lines)',
      'Depend only on $x$',
      'Are all $1$',
      'Are all $0$ on the $x$-axis'
    ],
    correctAnswer: 0,
    explanation: 'dy/dx = y: slope depends only on y. Along y = c, all slopes equal c. On y = 0 (x-axis), slopes are 0.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'For Euler\'s method, the formula is:',
    options: [
      '$y_{n+1} = y_n + h \\cdot f(x_n, y_n)$',
      '$y_{n+1} = y_n \\cdot f(x_n, y_n)$',
      '$y_{n+1} = y_n + f(x_n, y_n)$',
      '$y_{n+1} = h \\cdot f(x_n, y_n)$'
    ],
    correctAnswer: 0,
    explanation: 'yₙ₊₁ = yₙ + h·f(xₙ, yₙ) is the recursive Euler formula.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $P(t) = 800/(1+7e^{-0.4t})$, when is $P$ growing fastest?',
    options: [
      'When $P = 400$',
      'When $P = 800$',
      'When $t = 0$',
      'When $P = 200$'
    ],
    correctAnswer: 0,
    explanation: 'Maximum growth at P = L/2 = 800/2 = 400.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method with $h = 0.2$: $dy/dx = -2y$, $y(0) = 5$. Find $y(0.2)$:',
    options: ['$3$', '$4$', '$5$', '$1$'],
    correctAnswer: 0,
    explanation: 'y(0.2) = 5 + 0.2(−2·5) = 5 − 2 = 3.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'Then $y(0.4) =$ (continuing from $y(0.2) = 3$, $dy/dx = -2y$, $h = 0.2$):',
    options: ['$1.8$', '$1$', '$2.4$', '$0.6$'],
    correctAnswer: 0,
    explanation: 'y(0.4) = 3 + 0.2(−2·3) = 3 − 1.2 = 1.8.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'The logistic function $P(t) = L/(1+Ce^{-kt})$ has a horizontal asymptote at:',
    options: ['$P = L$ and $P = 0$', '$P = L$ only', '$P = k$', '$t = 0$'],
    correctAnswer: 0,
    explanation: 'As t → ∞, P → L (upper asymptote). As t → −∞, P → 0 (lower asymptote). Both are horizontal asymptotes.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'logistic-models-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $dy/dx = e^{-y}\\cos x$, $y(0) = 0$, this is:',
    options: ['Separable', 'Not separable', 'Linear but not separable', 'A logistic equation'],
    correctAnswer: 0,
    explanation: 'e^y dy = cos x dx. Separable. ∫e^y dy = ∫cos x dx → e^y = sin x + C.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method with $h = 0.1$, $dy/dx = y - x$, $(0, 1)$: $y(0.1) =$',
    options: ['$1.1$', '$1$', '$0.9$', '$1.2$'],
    correctAnswer: 0,
    explanation: 'y(0.1) = 1 + 0.1(1−0) = 1.1.',
    difficulty: 'easy',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
  {
    question: 'Continuing: $y(0.2) =$ ($y(0.1) = 1.1$, $dy/dx = y - x$, $h = 0.1$)',
    options: ['$1.2$', '$1.21$', '$1.1$', '$1.3$'],
    correctAnswer: 0,
    explanation: 'y(0.2) = 1.1 + 0.1(1.1−0.1) = 1.1 + 0.1(1.0) = 1.2.',
    difficulty: 'medium',
    domain: 'advanced-diffeq',
    topicSlug: 'euler-method-advanced-calcbc',
    formSet: 'both',
  },
"""

content = FILE.read_text()
marker = "\n]\n\n/** Generate an exit quiz"
if marker not in content:
    raise SystemExit("Could not find insertion marker")

new_content = content.replace(marker, NEW_QUESTIONS + marker)
FILE.write_text(new_content)

count = len(__import__('re').findall(r"correctAnswer:", new_content))
print(f"✅ BC pool now has {count} questions total")
