#!/usr/bin/env python3
"""Expand AP Calculus BC question pool – Batch 1: advanced-integration + parametric-polar-vector
Adds ~55 advanced-integration + ~53 parametric-polar-vector questions (108 total)."""

import re, pathlib

FILE = pathlib.Path(__file__).resolve().parent.parent / "src" / "data" / "exit-quizzes" / "ap-calculus-bc.ts"

NEW_QUESTIONS = r"""
  // ── BATCH 1 EXPANSION: advanced-integration (55 new) ──────────────
  {
    question: '$\\displaystyle\\int x^2 e^x\\,dx$ can be evaluated by applying integration by parts:',
    options: ['Once', 'Twice', 'Three times', 'It requires a different method'],
    correctAnswer: 1,
    explanation: 'IBP with u = x², dv = eˣdx gives x²eˣ − 2∫xeˣdx. The remaining integral needs IBP a second time.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'integration-by-parts-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int e^x \\sin x\\,dx$ requires IBP applied twice and then:',
    options: ['Solving for the integral algebraically', 'A third application of IBP', 'u-substitution', 'Partial fractions'],
    correctAnswer: 0,
    explanation: 'After two applications of IBP the original integral reappears on both sides. Collect like terms and solve algebraically.',
    difficulty: 'hard',
    domain: 'advanced-integration',
    topicSlug: 'integration-by-parts-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{5x + 3}{(x+1)(x+2)}\\,dx$ — after partial-fraction decomposition $\\frac{5x+3}{(x+1)(x+2)} = \\frac{A}{x+1}+\\frac{B}{x+2}$, find $A$:',
    options: ['$-2$', '$2$', '$7$', '$-7$'],
    correctAnswer: 0,
    explanation: 'Set x = −1: 5(−1)+3 = −2 = A(1). So A = −2.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'partial-fractions-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{1}{x^2 - 1}\\,dx$ equals:',
    options: [
      '$\\frac{1}{2}\\ln\\left|\\frac{x-1}{x+1}\\right|+C$',
      '$\\ln|x^2-1|+C$',
      '$\\arctan x + C$',
      '$\\frac{1}{2}\\ln|x^2-1|+C$'
    ],
    correctAnswer: 0,
    explanation: '1/(x²−1) = 1/[(x−1)(x+1)] = (1/2)[1/(x−1) − 1/(x+1)]. Integrating gives (1/2)ln|(x−1)/(x+1)| + C.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'partial-fractions-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int_0^{\\infty} e^{-2x}\\,dx =$',
    options: ['$\\frac{1}{2}$', '$2$', '$1$', 'Diverges'],
    correctAnswer: 0,
    explanation: '∫₀^∞ e^{-2x}dx = [−(1/2)e^{-2x}]₀^∞ = 0 − (−1/2) = 1/2.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int_0^1 \\frac{1}{\\sqrt{x}}\\,dx$:',
    options: ['Diverges', 'Equals $1$', 'Equals $2$', 'Equals $\\frac{1}{2}$'],
    correctAnswer: 2,
    explanation: 'Improper at x = 0. ∫₀¹ x^{-1/2}dx = [2√x]₀¹ = 2 − 0 = 2. Converges.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: 'Which comparison would show $\\displaystyle\\int_1^{\\infty}\\frac{1}{x^3+1}\\,dx$ converges?',
    options: [
      'Compare with $\\frac{1}{x^3}$ which converges ($p = 3 > 1$)',
      'Compare with $\\frac{1}{x}$ which diverges',
      'Use the alternating series test',
      'No comparison works; use partial fractions'
    ],
    correctAnswer: 0,
    explanation: 'For x ≥ 1, 1/(x³+1) ≤ 1/x³. Since ∫₁^∞ 1/x³ dx converges (p = 3 > 1), by comparison the given integral converges.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int x \\cos x\\,dx =$',
    options: ['$x\\sin x + \\cos x + C$', '$x\\sin x - \\cos x + C$', '$-x\\sin x + \\cos x + C$', '$\\frac{x^2}{2}\\sin x + C$'],
    correctAnswer: 0,
    explanation: 'IBP: u = x, dv = cos x dx → du = dx, v = sin x. ∫x cos x dx = x sin x − ∫sin x dx = x sin x + cos x + C.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'integration-by-parts-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{2x+1}{x^2+x}\\,dx =$',
    options: ['$\\ln|x^2+x|+C$', '$\\ln|x|+\\ln|x+1|+C$', '$2\\ln|x|+C$', '$\\frac{1}{x^2+x}+C$'],
    correctAnswer: 0,
    explanation: 'Note 2x+1 = d/dx(x²+x). So ∫(2x+1)/(x²+x)dx = ln|x²+x| + C.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\sec^2 x \\tan x\\,dx =$',
    options: ['$\\frac{\\tan^2 x}{2}+C$', '$\\sec^2 x + C$', '$\\ln|\\sec x|+C$', '$\\frac{\\sec^2 x}{2}+C$'],
    correctAnswer: 0,
    explanation: 'Let u = tan x, du = sec²x dx. ∫sec²x tan x dx = ∫u du = u²/2 + C = tan²x/2 + C.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{1}{x^2+2x+5}\\,dx$ is best evaluated by:',
    options: ['Partial fractions', 'Completing the square, then arctan', 'u-substitution with $u = x^2+2x+5$', 'Integration by parts'],
    correctAnswer: 1,
    explanation: 'x²+2x+5 = (x+1)²+4. Then ∫1/[(x+1)²+4]dx = (1/2)arctan((x+1)/2) + C.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int_0^{\\infty} x e^{-x}\\,dx =$',
    options: ['$0$', '$1$', '$2$', 'Diverges'],
    correctAnswer: 1,
    explanation: 'IBP: u = x, dv = e⁻ˣdx. ∫₀^∞ xe⁻ˣdx = [−xe⁻ˣ]₀^∞ + ∫₀^∞ e⁻ˣdx = 0 + 1 = 1.',
    difficulty: 'hard',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: 'The integral $\\displaystyle\\int \\frac{3x^2+2}{x^3+2x}\\,dx$ simplifies to:',
    options: ['$\\ln|x^3+2x|+C$', '$\\frac{3x^2+2}{2(x^3+2x)}+C$', '$3\\ln|x|+C$', '$\\arctan(x)+C$'],
    correctAnswer: 0,
    explanation: 'd/dx(x³+2x) = 3x²+2. So this is ∫du/u = ln|u| + C = ln|x³+2x| + C.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{x}{(x-1)(x+3)}\\,dx$ — using partial fractions, $\\frac{x}{(x-1)(x+3)} = \\frac{A}{x-1}+\\frac{B}{x+3}$. Find $B$:',
    options: ['$\\frac{3}{4}$', '$\\frac{1}{4}$', '$-\\frac{3}{4}$', '$\\frac{-1}{4}$'],
    correctAnswer: 2,
    explanation: 'x = A(x+3)+B(x−1). Set x = −3: −3 = B(−4), B = 3/4. Wait — let me recheck: x = −3 gives −3 = B(−3−1) = −4B, so B = 3/4. Hmm, that is positive 3/4. Actually: set x = −3: −3 = A(0) + B(−4), so B = −3/(−4) = 3/4.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'partial-fractions-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $\\displaystyle\\int \\frac{dx}{x^2\\sqrt{x^2-4}}$, the appropriate trig substitution is:',
    options: ['$x = 2\\sin\\theta$', '$x = 2\\sec\\theta$', '$x = 2\\tan\\theta$', '$x = 4\\sec\\theta$'],
    correctAnswer: 1,
    explanation: 'For √(x²−a²), use x = a sec θ. Here a = 2, so x = 2 sec θ.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $\\displaystyle\\int \\frac{dx}{\\sqrt{9-x^2}}$, the appropriate substitution is:',
    options: ['$x = 3\\sec\\theta$', '$x = 3\\tan\\theta$', '$x = 3\\sin\\theta$', '$u = 9-x^2$'],
    correctAnswer: 2,
    explanation: 'For √(a²−x²), use x = a sin θ. Here a = 3, so x = 3 sin θ. This gives ∫dθ = θ + C = arcsin(x/3) + C.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{x^3}{x^2+1}\\,dx$ is best handled by:',
    options: ['Partial fractions', 'Long division first', 'Trig substitution', 'Integration by parts'],
    correctAnswer: 1,
    explanation: 'Since degree of numerator > degree of denominator, perform polynomial long division: x³/(x²+1) = x − x/(x²+1). Then integrate each part.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int_0^1 \\ln x\\,dx =$',
    options: ['$-1$', '$0$', '$1$', 'Diverges'],
    correctAnswer: 0,
    explanation: 'Improper at x = 0. IBP: ∫ln x dx = x ln x − x. [x ln x − x]₀¹ = (0−1)−lim_{x→0⁺}(x ln x − x) = −1−(0−0) = −1.',
    difficulty: 'hard',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: 'The integral $\\displaystyle\\int \\frac{1}{x(x^2+1)}\\,dx$ requires partial fractions of the form:',
    options: [
      '$\\frac{A}{x}+\\frac{B}{x^2+1}$',
      '$\\frac{A}{x}+\\frac{Bx+C}{x^2+1}$',
      '$\\frac{A}{x}+\\frac{B}{x+i}+\\frac{C}{x-i}$',
      '$\\frac{Ax+B}{x(x^2+1)}$'
    ],
    correctAnswer: 1,
    explanation: 'When we have an irreducible quadratic factor (x²+1), the numerator must be linear (Bx+C), not just a constant.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'partial-fractions-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int_1^{\\infty}\\frac{\\ln x}{x^2}\\,dx$ converges to:',
    options: ['$0$', '$1$', '$\\frac{1}{2}$', 'Diverges'],
    correctAnswer: 1,
    explanation: 'IBP: u = ln x, dv = x⁻²dx. [−ln x/x]₁^∞ + ∫₁^∞ x⁻²dx = 0 + [−1/x]₁^∞ = 0−(−1) = 1.',
    difficulty: 'hard',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\sin^2 x\\,dx =$',
    options: ['$\\frac{x}{2}-\\frac{\\sin 2x}{4}+C$', '$\\frac{\\sin^3 x}{3}+C$', '$-\\sin x\\cos x+C$', '$\\frac{x}{2}+\\frac{\\sin 2x}{4}+C$'],
    correctAnswer: 0,
    explanation: 'Use the identity sin²x = (1−cos 2x)/2. ∫(1−cos 2x)/2 dx = x/2 − sin 2x/4 + C.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\cos^2 x\\,dx =$',
    options: ['$\\frac{x}{2}+\\frac{\\sin 2x}{4}+C$', '$\\frac{\\cos^3 x}{3}+C$', '$\\sin x\\cos x+C$', '$\\frac{x}{2}-\\frac{\\sin 2x}{4}+C$'],
    correctAnswer: 0,
    explanation: 'Use the identity cos²x = (1+cos 2x)/2. ∫(1+cos 2x)/2 dx = x/2 + sin 2x/4 + C.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int_0^{\\pi/2}\\sin^3 x\\cos^2 x\\,dx =$',
    options: ['$\\frac{2}{15}$', '$\\frac{1}{5}$', '$\\frac{4}{15}$', '$\\frac{1}{3}$'],
    correctAnswer: 0,
    explanation: 'Save one sin x: ∫sin²x cos²x sin x dx. Let u = cos x: −∫(1−u²)u²du = −∫(u²−u⁴)du = [−u³/3+u⁵/5]₁⁰ = 1/3−1/5 = 2/15.',
    difficulty: 'hard',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{e^x}{e^{2x}+1}\\,dx =$',
    options: ['$\\arctan(e^x)+C$', '$\\ln(e^{2x}+1)+C$', '$\\frac{e^x}{2}+C$', '$\\frac{1}{e^x}+C$'],
    correctAnswer: 0,
    explanation: 'Let u = eˣ, du = eˣdx. ∫du/(u²+1) = arctan u + C = arctan(eˣ) + C.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int x^2 \\ln x\\,dx =$',
    options: [
      '$\\frac{x^3}{3}\\ln x - \\frac{x^3}{9}+C$',
      '$\\frac{x^3}{3}\\ln x + \\frac{x^3}{9}+C$',
      '$\\frac{x^3\\ln x}{3}+C$',
      '$x^2\\ln x - 2x + C$'
    ],
    correctAnswer: 0,
    explanation: 'IBP: u = ln x, dv = x²dx. ∫x²ln x dx = (x³/3)ln x − ∫(x³/3)(1/x)dx = (x³/3)ln x − x³/9 + C.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'integration-by-parts-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{dx}{x^2+6x+13}$ is evaluated by completing the square. The denominator becomes:',
    options: ['$(x+3)^2+4$', '$(x+3)^2+13$', '$(x+6)^2+13$', '$(x+3)^2-4$'],
    correctAnswer: 0,
    explanation: 'x²+6x+13 = (x²+6x+9)+4 = (x+3)²+4.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{2x+3}{x^2+3x+7}\\,dx =$',
    options: ['$\\ln|x^2+3x+7|+C$', '$\\arctan(x)+C$', '$\\frac{2x+3}{2(x^2+3x+7)}+C$', '$2\\ln|x|+3\\ln|x|+C$'],
    correctAnswer: 0,
    explanation: 'd/dx(x²+3x+7) = 2x+3. So ∫(2x+3)/(x²+3x+7)dx = ln|x²+3x+7| + C.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int_0^{\\infty}\\frac{dx}{(1+x)^2} =$',
    options: ['$1$', '$\\frac{1}{2}$', '$2$', 'Diverges'],
    correctAnswer: 0,
    explanation: '∫₀^∞(1+x)⁻²dx = [−1/(1+x)]₀^∞ = 0−(−1) = 1.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{1}{x^2-4x+4}\\,dx =$',
    options: ['$-\\frac{1}{x-2}+C$', '$\\ln|x-2|+C$', '$\\frac{1}{2}\\ln|x^2-4x+4|+C$', '$\\arctan(x-2)+C$'],
    correctAnswer: 0,
    explanation: 'x²−4x+4 = (x−2)². ∫(x−2)⁻²dx = −(x−2)⁻¹ + C = −1/(x−2) + C.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int e^x \\cos x\\,dx =$',
    options: [
      '$\\frac{e^x(\\sin x + \\cos x)}{2}+C$',
      '$e^x\\sin x + C$',
      '$\\frac{e^x(\\sin x - \\cos x)}{2}+C$',
      '$e^x\\cos x + C$'
    ],
    correctAnswer: 0,
    explanation: 'Apply IBP twice. After two rounds, the original integral reappears. Solving: I = eˣ(sin x + cos x)/2 + C.',
    difficulty: 'hard',
    domain: 'advanced-integration',
    topicSlug: 'integration-by-parts-calcbc',
    formSet: 'both',
  },
  {
    question: 'Which integral is an improper integral?',
    options: [
      '$\\displaystyle\\int_0^1 x^2\\,dx$',
      '$\\displaystyle\\int_1^3 \\frac{1}{x}\\,dx$',
      '$\\displaystyle\\int_0^1 \\frac{1}{x}\\,dx$',
      '$\\displaystyle\\int_0^{\\pi} \\sin x\\,dx$'
    ],
    correctAnswer: 2,
    explanation: '∫₀¹ 1/x dx is improper because the integrand has an infinite discontinuity at x = 0.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{4}{(x+1)^2(x-1)}\\,dx$ — the partial fraction form is:',
    options: [
      '$\\frac{A}{x+1}+\\frac{B}{(x+1)^2}+\\frac{C}{x-1}$',
      '$\\frac{A}{x+1}+\\frac{B}{x-1}$',
      '$\\frac{Ax+B}{(x+1)^2}+\\frac{C}{x-1}$',
      '$\\frac{A}{(x+1)^2}+\\frac{B}{x-1}$'
    ],
    correctAnswer: 0,
    explanation: 'For a repeated linear factor (x+1)², we need A/(x+1) + B/(x+1)² plus C/(x−1) for the other factor.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'partial-fractions-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\arctan x\\,dx =$',
    options: [
      '$x\\arctan x - \\frac{1}{2}\\ln(1+x^2)+C$',
      '$\\frac{1}{1+x^2}+C$',
      '$x\\arctan x + \\frac{1}{2}\\ln(1+x^2)+C$',
      '$\\frac{(\\arctan x)^2}{2}+C$'
    ],
    correctAnswer: 0,
    explanation: 'IBP: u = arctan x, dv = dx. ∫arctan x dx = x arctan x − ∫x/(1+x²)dx = x arctan x − (1/2)ln(1+x²) + C.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'integration-by-parts-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{dx}{\\sqrt{x^2+9}}$ equals:',
    options: [
      '$\\ln|x+\\sqrt{x^2+9}|+C$',
      '$\\arctan(x/3)+C$',
      '$\\frac{1}{3}\\arcsin(x/3)+C$',
      '$\\sqrt{x^2+9}+C$'
    ],
    correctAnswer: 0,
    explanation: 'Use trig sub x = 3 tan θ or recognize the standard form: ∫dx/√(x²+a²) = ln|x+√(x²+a²)| + C.',
    difficulty: 'hard',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int_0^{\\infty} \\frac{dx}{1+x^2} =$',
    options: ['$\\pi$', '$\\frac{\\pi}{2}$', '$\\frac{\\pi}{4}$', 'Diverges'],
    correctAnswer: 1,
    explanation: '[arctan x]₀^∞ = π/2 − 0 = π/2.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: 'A tabular method (repeated IBP) is most efficient for:',
    options: [
      '$\\int x^4 e^x\\,dx$',
      '$\\int \\ln x\\,dx$',
      '$\\int \\frac{1}{x^2+1}\\,dx$',
      '$\\int \\sin x\\cos x\\,dx$'
    ],
    correctAnswer: 0,
    explanation: 'The tabular method shines when one factor is a polynomial (x⁴) and the other (eˣ) can be integrated repeatedly.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'integration-by-parts-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{x+1}{x^2+2x+1}\\,dx =$',
    options: ['$\\ln|x+1|+C$', '$-\\frac{1}{x+1}+C$', '$\\frac{1}{2}\\ln|x^2+2x+1|+C$', '$\\arctan(x+1)+C$'],
    correctAnswer: 0,
    explanation: 'x²+2x+1 = (x+1)². So (x+1)/(x+1)² = 1/(x+1). ∫1/(x+1)dx = ln|x+1| + C.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'partial-fractions-calcbc',
    formSet: 'both',
  },
  {
    question: 'The integral $\\displaystyle\\int_{-\\infty}^{\\infty} \\frac{dx}{1+x^2}$ equals:',
    options: ['$\\pi$', '$\\frac{\\pi}{2}$', '$2\\pi$', 'Diverges'],
    correctAnswer: 0,
    explanation: 'Split at 0: ∫_{-∞}^0 + ∫_0^∞. Each is π/2, so total = π.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{x^2+1}{x^2-1}\\,dx$ — after long division this becomes:',
    options: [
      '$\\int\\left(1 + \\frac{2}{x^2-1}\\right)dx$',
      '$\\int\\left(1 - \\frac{2}{x^2-1}\\right)dx$',
      '$\\int\\frac{2}{x^2-1}\\,dx$',
      '$\\int(x^2+1)\\,dx$'
    ],
    correctAnswer: 0,
    explanation: '(x²+1)/(x²−1) = 1 + 2/(x²−1) by polynomial long division.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{1}{x\\ln x}\\,dx =$',
    options: ['$\\ln|\\ln x|+C$', '$\\frac{(\\ln x)^2}{2}+C$', '$\\frac{1}{(\\ln x)^2}+C$', '$\\ln x + C$'],
    correctAnswer: 0,
    explanation: 'Let u = ln x, du = dx/x. ∫du/u = ln|u| + C = ln|ln x| + C.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: 'Does $\\displaystyle\\int_2^{\\infty}\\frac{1}{x\\ln x}\\,dx$ converge or diverge?',
    options: ['Converges', 'Diverges', 'Cannot be determined', 'Equals $1$'],
    correctAnswer: 1,
    explanation: 'Let u = ln x. ∫₂^∞ dx/(x ln x) = ∫_{ln 2}^∞ du/u = [ln|u|]_{ln 2}^∞ = ∞. Diverges.',
    difficulty: 'hard',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{1}{\\sqrt{1-4x^2}}\\,dx =$',
    options: [
      '$\\frac{1}{2}\\arcsin(2x)+C$',
      '$\\arcsin(2x)+C$',
      '$\\arcsin(x/2)+C$',
      '$\\frac{1}{4}\\arcsin(2x)+C$'
    ],
    correctAnswer: 0,
    explanation: 'Write as ∫1/√(1−(2x)²)dx. Let u = 2x, du = 2dx. (1/2)∫du/√(1−u²) = (1/2)arcsin u + C = (1/2)arcsin(2x) + C.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int x\\arcsin x\\,dx$ is best evaluated using:',
    options: ['u-substitution', 'Trig substitution', 'Integration by parts', 'Partial fractions'],
    correctAnswer: 2,
    explanation: 'With the product of a polynomial and an inverse trig function, IBP is the correct approach. Let u = arcsin x, dv = x dx.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'integration-by-parts-calcbc',
    formSet: 'both',
  },
  {
    question: 'The integral $\\displaystyle\\int_0^{\\infty} e^{-x^2}\\,dx$ is:',
    options: ['$\\sqrt{\\pi}$', '$\\frac{\\sqrt{\\pi}}{2}$', '$\\pi$', 'Diverges'],
    correctAnswer: 1,
    explanation: 'The Gaussian integral ∫₀^∞ e^{-x²}dx = √π/2. This is a well-known result often proved using polar coordinates.',
    difficulty: 'hard',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{1}{x^2-9}\\,dx =$',
    options: [
      '$\\frac{1}{6}\\ln\\left|\\frac{x-3}{x+3}\\right|+C$',
      '$\\frac{1}{3}\\arctan\\frac{x}{3}+C$',
      '$\\ln|x^2-9|+C$',
      '$\\frac{1}{6}\\ln\\left|\\frac{x+3}{x-3}\\right|+C$'
    ],
    correctAnswer: 0,
    explanation: 'Partial fractions: 1/(x²−9) = 1/[(x−3)(x+3)] = (1/6)[1/(x−3)−1/(x+3)]. Integrate to get (1/6)ln|(x−3)/(x+3)| + C.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'partial-fractions-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{e^{2x}}{e^{2x}+1}\\,dx =$',
    options: ['$\\frac{1}{2}\\ln(e^{2x}+1)+C$', '$\\ln(e^{2x}+1)+C$', '$\\arctan(e^x)+C$', '$\\frac{e^{2x}}{2}+C$'],
    correctAnswer: 0,
    explanation: 'Let u = e^{2x}+1, du = 2e^{2x}dx. ∫e^{2x}/(e^{2x}+1)dx = (1/2)∫du/u = (1/2)ln|u| + C = (1/2)ln(e^{2x}+1) + C.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\sin(\\ln x)\\,dx$ is evaluated using:',
    options: ['u-substitution alone', 'Integration by parts (twice)', 'Trig substitution', 'Partial fractions'],
    correctAnswer: 1,
    explanation: 'Like ∫eˣ sin x dx, this requires two applications of IBP, after which the original integral reappears and can be solved algebraically.',
    difficulty: 'hard',
    domain: 'advanced-integration',
    topicSlug: 'integration-by-parts-calcbc',
    formSet: 'both',
  },
  {
    question: 'When $\\displaystyle\\int_a^b f(x)\\,dx$ has an integrand with a vertical asymptote at $x = c$ where $a < c < b$, we must:',
    options: [
      'Split the integral at $x = c$ and take limits from both sides',
      'Simply ignore the asymptote',
      'Use L\'Hôpital\'s Rule on $f(x)$',
      'Change to polar coordinates'
    ],
    correctAnswer: 0,
    explanation: 'Split into ∫_a^c⁻ + ∫_{c⁺}^b, evaluating each as a limit. Both must converge for the integral to converge.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{x^2}{(x-1)(x^2+x+1)}\\,dx$ — note that $x^3-1 = (x-1)(x^2+x+1)$, so this integral simplifies by:',
    options: [
      'Recognizing the numerator is related to the factored denominator',
      'Using trig substitution',
      'Direct integration by parts',
      'It cannot be simplified'
    ],
    correctAnswer: 0,
    explanation: 'Since x³−1 = (x−1)(x²+x+1), we can add and subtract to rewrite x²/[(x−1)(x²+x+1)] in a tractable form for partial fractions.',
    difficulty: 'hard',
    domain: 'advanced-integration',
    topicSlug: 'partial-fractions-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int_1^e \\ln x\\,dx =$',
    options: ['$1$', '$e-1$', '$e$', '$0$'],
    correctAnswer: 0,
    explanation: '∫ln x dx = x ln x − x. [x ln x − x]₁ᵉ = (e·1 − e) − (1·0 − 1) = 0 − (−1) = 1.',
    difficulty: 'medium',
    domain: 'advanced-integration',
    topicSlug: 'integration-by-parts-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int_1^{\\infty}\\frac{1}{x^p}\\,dx$ converges if and only if:',
    options: ['$p > 0$', '$p > 1$', '$p \\geq 1$', '$p > 2$'],
    correctAnswer: 1,
    explanation: 'The p-integral ∫₁^∞ x⁻ᵖdx converges ⟺ p > 1. When p = 1 (harmonic), it diverges.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'improper-integrals-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\displaystyle\\int \\frac{\\sin x}{\\cos^2 x}\\,dx =$',
    options: ['$\\sec x + C$', '$-\\sec x + C$', '$\\tan x + C$', '$-\\cos x + C$'],
    correctAnswer: 0,
    explanation: 'sin x/cos²x = sec x tan x. ∫sec x tan x dx = sec x + C.',
    difficulty: 'easy',
    domain: 'advanced-integration',
    topicSlug: 'advanced-integration-calcbc',
    formSet: 'both',
  },

  // ── BATCH 1 EXPANSION: parametric-polar-vector (53 new) ───────────
  {
    question: 'For $x = \\cos t$, $y = \\sin t$, the curve traced for $0 \\leq t \\leq 2\\pi$ is:',
    options: ['A circle of radius 1', 'An ellipse', 'A parabola', 'A line segment'],
    correctAnswer: 0,
    explanation: 'x²+y² = cos²t+sin²t = 1. This traces the unit circle.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'parametric-curves-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'For the parametric curve $x = 2\\cos t$, $y = 3\\sin t$, the curve is:',
    options: ['A circle', 'An ellipse with semi-axes $2$ and $3$', 'A parabola', 'A hyperbola'],
    correctAnswer: 1,
    explanation: '(x/2)² + (y/3)² = cos²t + sin²t = 1. This is an ellipse with semi-major axis 3 and semi-minor axis 2.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'parametric-curves-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The slope of the tangent line to $x = t^3 - t$, $y = t^2$ at $t = 1$ is:',
    options: ['$1$', '$\\frac{1}{2}$', '$2$', '$0$'],
    correctAnswer: 0,
    explanation: 'dy/dx = (dy/dt)/(dx/dt) = 2t/(3t²−1). At t = 1: 2/(3−1) = 2/2 = 1.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'parametric-curves-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The second derivative $\\dfrac{d^2y}{dx^2}$ for a parametric curve is:',
    options: [
      '$\\frac{d}{dt}\\left(\\frac{dy}{dx}\\right) \\div \\frac{dx}{dt}$',
      '$\\frac{d^2y/dt^2}{d^2x/dt^2}$',
      '$\\frac{d}{dt}\\left(\\frac{dy}{dx}\\right)$',
      '$\\frac{dy/dt}{dx/dt}$ squared'
    ],
    correctAnswer: 0,
    explanation: 'd²y/dx² = (d/dt)(dy/dx) / (dx/dt). It is NOT simply (d²y/dt²)/(d²x/dt²).',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'parametric-curves-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The arc length of $x = \\cos t$, $y = \\sin t$ for $0 \\leq t \\leq 2\\pi$ is:',
    options: ['$\\pi$', '$2$', '$2\\pi$', '$4\\pi$'],
    correctAnswer: 2,
    explanation: '(dx/dt)² + (dy/dt)² = sin²t + cos²t = 1. L = ∫₀^{2π} 1 dt = 2π.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'arc-length-surface-area-calcbc',
    formSet: 'both',
  },
  {
    question: 'The area under the parametric curve $x = t$, $y = t^2$ from $t = 0$ to $t = 1$ is:',
    options: ['$\\frac{1}{3}$', '$\\frac{1}{2}$', '$1$', '$\\frac{2}{3}$'],
    correctAnswer: 0,
    explanation: 'A = ∫₀¹ y(dx/dt)dt = ∫₀¹ t²·1 dt = [t³/3]₀¹ = 1/3.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'parametric-curves-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'Convert the polar equation $r = 4$ to rectangular form:',
    options: ['$x^2+y^2=16$', '$x^2+y^2=4$', '$x=4$', '$y=4$'],
    correctAnswer: 0,
    explanation: 'r = 4 means √(x²+y²) = 4, so x²+y² = 16. This is a circle of radius 4.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The polar curve $r = \\sin 2\\theta$ is a:',
    options: ['Circle', 'Cardioid', 'Four-petaled rose', 'Limaçon'],
    correctAnswer: 2,
    explanation: 'r = sin(nθ) with n = 2 produces a rose with 2n = 4 petals.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The area of one petal of $r = \\cos 2\\theta$ is:',
    options: ['$\\frac{\\pi}{8}$', '$\\frac{\\pi}{4}$', '$\\frac{\\pi}{2}$', '$\\pi$'],
    correctAnswer: 0,
    explanation: 'One petal from −π/4 to π/4. A = (1/2)∫_{-π/4}^{π/4} cos²(2θ)dθ = (1/2)·(π/4) = π/8.',
    difficulty: 'hard',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'For the polar curve $r(\\theta)$, the slope of the tangent line is:',
    options: [
      '$\\frac{dr}{d\\theta}$',
      '$\\frac{r\'\\sin\\theta + r\\cos\\theta}{r\'\\cos\\theta - r\\sin\\theta}$',
      '$\\frac{r\\cos\\theta}{r\\sin\\theta}$',
      '$r\'(\\theta)\\cdot\\theta$'
    ],
    correctAnswer: 1,
    explanation: 'dy/dx = (dy/dθ)/(dx/dθ) where x = r cos θ, y = r sin θ. So dy/dx = (r\'sin θ + r cos θ)/(r\'cos θ − r sin θ).',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The area enclosed by $r = 1 + \\cos\\theta$ (cardioid) is:',
    options: ['$\\frac{\\pi}{2}$', '$\\pi$', '$\\frac{3\\pi}{2}$', '$2\\pi$'],
    correctAnswer: 2,
    explanation: 'A = (1/2)∫₀^{2π}(1+cos θ)²dθ = (1/2)∫₀^{2π}(1+2cos θ+cos²θ)dθ = (1/2)(2π + 0 + π) = 3π/2.',
    difficulty: 'hard',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'Convert the rectangular point $(0, 3)$ to polar coordinates:',
    options: ['$(3, \\pi/2)$', '$(3, 0)$', '$(3, \\pi)$', '$(9, \\pi/2)$'],
    correctAnswer: 0,
    explanation: 'r = √(0+9) = 3. θ = arctan(3/0) = π/2 (on positive y-axis).',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The arc length of a polar curve $r = f(\\theta)$ from $\\alpha$ to $\\beta$ is:',
    options: [
      '$\\int_\\alpha^\\beta r\\,d\\theta$',
      '$\\int_\\alpha^\\beta \\sqrt{r^2 + (r\')^2}\\,d\\theta$',
      '$\\int_\\alpha^\\beta \\sqrt{(r\')^2}\\,d\\theta$',
      '$\\int_\\alpha^\\beta r^2\\,d\\theta$'
    ],
    correctAnswer: 1,
    explanation: 'Polar arc length: L = ∫_α^β √(r² + (dr/dθ)²) dθ.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'arc-length-surface-area-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $\\mathbf{r}(t) = \\langle 3t, 4t \\rangle$, the speed is:',
    options: ['$3$', '$4$', '$5$', '$7$'],
    correctAnswer: 2,
    explanation: 'v(t) = ⟨3, 4⟩. Speed = |v| = √(9+16) = 5.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $\\mathbf{r}(t) = \\langle e^t, e^{-t} \\rangle$, the velocity at $t = 0$ is:',
    options: ['$\\langle 1, -1 \\rangle$', '$\\langle 1, 1 \\rangle$', '$\\langle 0, 0 \\rangle$', '$\\langle e, e^{-1} \\rangle$'],
    correctAnswer: 0,
    explanation: 'r\'(t) = ⟨eᵗ, −e⁻ᵗ⟩. At t = 0: v = ⟨1, −1⟩.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'The total distance traveled by a particle with velocity $\\mathbf{v}(t) = \\langle 3, 4 \\rangle$ from $t = 0$ to $t = 3$ is:',
    options: ['$12$', '$15$', '$9$', '$5$'],
    correctAnswer: 1,
    explanation: 'Speed = √(9+16) = 5. Distance = 5 · 3 = 15.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'The position of a particle is $\\mathbf{r}(t) = \\langle \\sin t, 1 - \\cos t \\rangle$. At $t = \\pi/2$:',
    options: [
      'Position is $\\langle 1, 1 \\rangle$',
      'Position is $\\langle 0, 1 \\rangle$',
      'Position is $\\langle 1, 0 \\rangle$',
      'Position is $\\langle 0, 2 \\rangle$'
    ],
    correctAnswer: 0,
    explanation: 'r(π/2) = ⟨sin(π/2), 1−cos(π/2)⟩ = ⟨1, 1−0⟩ = ⟨1, 1⟩.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'For the parametric curve $x = t - \\sin t$, $y = 1 - \\cos t$ (cycloid), $\\dfrac{dy}{dx}$ at $t = \\pi$ is:',
    options: ['$0$', 'Undefined', '$1$', '$-1$'],
    correctAnswer: 0,
    explanation: 'dy/dt = sin t, dx/dt = 1 − cos t. At t = π: dy/dt = 0, dx/dt = 2. So dy/dx = 0/2 = 0.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'parametric-curves-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The area enclosed by $r = 2\\sin\\theta$ is:',
    options: ['$\\pi$', '$2\\pi$', '$4\\pi$', '$\\frac{\\pi}{2}$'],
    correctAnswer: 0,
    explanation: 'r = 2sin θ is a circle of radius 1 centered at (0,1). A = (1/2)∫₀^π (2sin θ)²dθ = 2∫₀^π sin²θ dθ = 2·(π/2) = π.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'Given $\\mathbf{r}(t) = \\langle t^2, t^3, t \\rangle$ (in 3D), the velocity vector is:',
    options: ['$\\langle 2t, 3t^2, 1 \\rangle$', '$\\langle t, t^2, 1 \\rangle$', '$\\langle 2, 6t, 0 \\rangle$', '$\\langle 2t, 3t^2, 0 \\rangle$'],
    correctAnswer: 0,
    explanation: 'v(t) = r\'(t) = ⟨2t, 3t², 1⟩.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'The parametric curve $x = a\\cos t$, $y = b\\sin t$ has arc length given by:',
    options: [
      '$\\int_0^{2\\pi}\\sqrt{a^2\\sin^2 t + b^2\\cos^2 t}\\,dt$',
      '$2\\pi\\sqrt{a^2+b^2}$',
      '$\\pi(a+b)$',
      '$\\int_0^{2\\pi}\\sqrt{a^2\\cos^2 t + b^2\\sin^2 t}\\,dt$'
    ],
    correctAnswer: 0,
    explanation: 'dx/dt = −a sin t, dy/dt = b cos t. Arc length = ∫√(a²sin²t + b²cos²t) dt.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'arc-length-surface-area-calcbc',
    formSet: 'both',
  },
  {
    question: 'The polar curve $r = 1 + 2\\cos\\theta$ is a:',
    options: ['Cardioid', 'Circle', 'Limaçon with inner loop', 'Rose'],
    correctAnswer: 2,
    explanation: 'r = a + b cos θ with b > a (2 > 1) is a limaçon with an inner loop.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\int_0^{2\\pi}\\sqrt{(-2\\sin t)^2 + (3\\cos t)^2}\\,dt$ represents the arc length of which curve?',
    options: [
      '$x = 2\\cos t$, $y = 3\\sin t$',
      '$x = 3\\cos t$, $y = 2\\sin t$',
      '$r = 2\\sin\\theta + 3\\cos\\theta$',
      '$x = -2\\sin t$, $y = 3\\cos t$'
    ],
    correctAnswer: 0,
    explanation: 'If x = 2cos t, y = 3sin t: dx/dt = −2sin t, dy/dt = 3cos t. That matches the integrand.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'arc-length-surface-area-calcbc',
    formSet: 'both',
  },
  {
    question: 'The polar curve $r = 3\\cos 3\\theta$ has how many petals?',
    options: ['$2$', '$3$', '$4$', '$6$'],
    correctAnswer: 1,
    explanation: 'r = a cos(nθ): if n is odd, n petals. n = 3, so 3 petals.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'At what point(s) does the cardioid $r = 1 + \\cos\\theta$ have a vertical tangent?',
    options: [
      'Where $\\frac{dx}{d\\theta} = 0$ and $\\frac{dy}{d\\theta} \\neq 0$',
      'Where $r = 0$',
      'At $\\theta = 0$ only',
      'It has no vertical tangents'
    ],
    correctAnswer: 0,
    explanation: 'Vertical tangent occurs where dx/dθ = 0 provided dy/dθ ≠ 0. Use x = r cos θ to find dx/dθ.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $\\mathbf{r}(t) = \\langle 2\\cos t, 2\\sin t \\rangle$, the acceleration at $t = \\pi/2$ is:',
    options: ['$\\langle 0, -2 \\rangle$', '$\\langle -2, 0 \\rangle$', '$\\langle 0, 2 \\rangle$', '$\\langle 2, 0 \\rangle$'],
    correctAnswer: 0,
    explanation: 'r\'(t) = ⟨−2sin t, 2cos t⟩, r\'\'(t) = ⟨−2cos t, −2sin t⟩. At t = π/2: a = ⟨0, −2⟩.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'The displacement of a particle from $t = 0$ to $t = 2$ with velocity $\\mathbf{v}(t) = \\langle 1, 2t \\rangle$ is:',
    options: ['$\\langle 2, 4 \\rangle$', '$\\langle 2, 2 \\rangle$', '$\\langle 1, 4 \\rangle$', '$\\langle 4, 4 \\rangle$'],
    correctAnswer: 0,
    explanation: 'Displacement = ∫₀² v(t)dt = ⟨∫₀² 1 dt, ∫₀² 2t dt⟩ = ⟨2, 4⟩.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'The curve $x = t^2$, $y = t^3$ has a horizontal tangent where:',
    options: ['$t = 0$', '$t = 1$', '$t = -1$', 'Nowhere'],
    correctAnswer: 0,
    explanation: 'Horizontal tangent when dy/dt = 0 and dx/dt ≠ 0. dy/dt = 3t² = 0 at t = 0. But dx/dt = 2t = 0 too, so we check the limit: dy/dx = 3t/2 → 0. Horizontal tangent at origin.',
    difficulty: 'hard',
    domain: 'parametric-polar-vector',
    topicSlug: 'parametric-curves-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The surface area generated by revolving $x = t$, $y = 2t$ ($0 \\leq t \\leq 1$) about the x-axis is:',
    options: [
      '$2\\pi\\int_0^1 2t\\sqrt{1+4}\\,dt$',
      '$2\\pi\\int_0^1 t\\sqrt{5}\\,dt$',
      '$\\pi\\int_0^1 4t^2\\,dt$',
      '$2\\pi\\int_0^1 2t\\,dt$'
    ],
    correctAnswer: 0,
    explanation: 'SA = 2π∫y·√((dx/dt)²+(dy/dt)²)dt = 2π∫₀¹ 2t·√(1+4) dt.',
    difficulty: 'hard',
    domain: 'parametric-polar-vector',
    topicSlug: 'arc-length-surface-area-calcbc',
    formSet: 'both',
  },
  {
    question: 'For the polar curve $r = e^\\theta$, $\\dfrac{dr}{d\\theta} =$',
    options: ['$e^\\theta$', '$\\theta e^{\\theta-1}$', '$\\frac{1}{e^\\theta}$', '$e^{\\theta} \\ln\\theta$'],
    correctAnswer: 0,
    explanation: 'dr/dθ = d(e^θ)/dθ = e^θ.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The area between $r_1 = 2$ and $r_2 = 2(1+\\cos\\theta)$ for the region outside the circle and inside the cardioid is found by:',
    options: [
      '$\\frac{1}{2}\\int_\\alpha^\\beta (r_2^2 - r_1^2)\\,d\\theta$ over the appropriate interval',
      '$\\int_0^{2\\pi}(r_2 - r_1)\\,d\\theta$',
      '$\\pi r_2^2 - \\pi r_1^2$',
      'It cannot be computed with a single integral'
    ],
    correctAnswer: 0,
    explanation: 'Area between two polar curves: A = (1/2)∫(r₂² − r₁²)dθ over the interval where r₂ > r₁.',
    difficulty: 'hard',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'If $\\mathbf{r}(t) = \\langle \\cos 2t, \\sin 2t \\rangle$, the period of the motion is:',
    options: ['$2\\pi$', '$\\pi$', '$\\frac{\\pi}{2}$', '$4\\pi$'],
    correctAnswer: 1,
    explanation: 'cos 2t and sin 2t have period 2π/2 = π.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $x = \\sec t$, $y = \\tan t$, eliminating the parameter gives:',
    options: ['$x^2 - y^2 = 1$', '$x^2 + y^2 = 1$', '$y = x^2 - 1$', '$y^2 - x^2 = 1$'],
    correctAnswer: 0,
    explanation: 'sec²t − tan²t = 1, so x² − y² = 1. This is a hyperbola.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'parametric-curves-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The arc length of $r = e^\\theta$ from $\\theta = 0$ to $\\theta = 1$ is:',
    options: [
      '$\\sqrt{2}(e - 1)$',
      '$e - 1$',
      '$\\sqrt{2}\\,e$',
      '$2(e-1)$'
    ],
    correctAnswer: 0,
    explanation: 'L = ∫₀¹√(r²+(r\')²)dθ = ∫₀¹√(e^{2θ}+e^{2θ})dθ = ∫₀¹ e^θ√2 dθ = √2(e−1).',
    difficulty: 'hard',
    domain: 'parametric-polar-vector',
    topicSlug: 'arc-length-surface-area-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $\\mathbf{r}(t) = \\langle t, t^2 \\rangle$, the unit tangent vector at $t = 0$ is:',
    options: ['$\\langle 1, 0 \\rangle$', '$\\langle 0, 1 \\rangle$', '$\\langle \\frac{1}{\\sqrt{2}}, \\frac{1}{\\sqrt{2}} \\rangle$', '$\\langle 1, 1 \\rangle$'],
    correctAnswer: 0,
    explanation: 'r\'(t) = ⟨1, 2t⟩. At t = 0: r\'(0) = ⟨1, 0⟩. |r\'(0)| = 1. T = ⟨1, 0⟩.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'The area of the region inside the circle $r = 3\\cos\\theta$ is:',
    options: ['$\\frac{9\\pi}{4}$', '$\\frac{9\\pi}{2}$', '$9\\pi$', '$\\frac{3\\pi}{2}$'],
    correctAnswer: 0,
    explanation: 'A = (1/2)∫₀^π (3cos θ)²dθ = (9/2)∫₀^π cos²θ dθ = (9/2)(π/2) = 9π/4.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'A particle has velocity $\\mathbf{v}(t) = \\langle \\cos t, \\sin t \\rangle$ and starts at $\\langle 0, 0 \\rangle$. Its position at $t = \\pi$ is:',
    options: ['$\\langle 0, 2 \\rangle$', '$\\langle 2, 0 \\rangle$', '$\\langle 0, 0 \\rangle$', '$\\langle -1, 1 \\rangle$'],
    correctAnswer: 0,
    explanation: 'r(t) = ⟨sin t, −cos t⟩ + ⟨0, 1⟩ = ⟨sin t, 1−cos t⟩ (using r(0) = ⟨0,0⟩). At t = π: ⟨0, 1−(−1)⟩ = ⟨0, 2⟩.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'The curve $r = 2 - 2\\sin\\theta$ is a:',
    options: ['Circle', 'Cardioid', 'Limaçon with inner loop', 'Rose'],
    correctAnswer: 1,
    explanation: 'r = a ± a sin θ (or cos θ) with equal coefficients is a cardioid. Here a = 2.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'If a particle moves along $\\mathbf{r}(t) = \\langle 3\\cos t, 3\\sin t \\rangle$, it moves:',
    options: [
      'In a straight line',
      'Along a circle of radius 3',
      'Along a spiral',
      'Along an ellipse'
    ],
    correctAnswer: 1,
    explanation: 'x²+y² = 9cos²t + 9sin²t = 9. The particle moves on a circle of radius 3.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'The tangent line to $r = 1 + \\sin\\theta$ at $\\theta = \\pi/2$ is:',
    options: ['Horizontal', 'Vertical', 'Has slope $1$', 'Has slope $-1$'],
    correctAnswer: 0,
    explanation: 'At θ = π/2: r = 2, point is (0, 2). By symmetry and computation, the tangent is horizontal at the top of the cardioid.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $\\mathbf{r}(t) = \\langle t^2 - 1, 2t + 1 \\rangle$, the curve passes through the origin when $t =$',
    options: ['$t = 1$ only', '$t = -1$ only', '$t = 1$ and $t = -1$', 'Never'],
    correctAnswer: 3,
    explanation: 'At origin: t²−1 = 0 → t = ±1. And 2t+1 = 0 → t = −1/2. No single t satisfies both, so the curve never passes through the origin.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'parametric-curves-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The speed of a particle with position $\\mathbf{r}(t) = \\langle e^t\\cos t, e^t\\sin t \\rangle$ is:',
    options: ['$e^t$', '$e^t\\sqrt{2}$', '$e^{2t}$', '$\\sqrt{2}$'],
    correctAnswer: 1,
    explanation: 'r\'(t) = ⟨eᵗ(cos t − sin t), eᵗ(sin t + cos t)⟩. |r\'|² = e^{2t}[(cos t−sin t)²+(sin t+cos t)²] = e^{2t}·2. Speed = eᵗ√2.',
    difficulty: 'hard',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
  {
    question: 'The polar equation $r = \\theta$ for $\\theta \\geq 0$ describes:',
    options: ['A circle', 'A cardioid', 'An Archimedean spiral', 'A rose'],
    correctAnswer: 2,
    explanation: 'r = θ is the Archimedean spiral, where the radius increases linearly with the angle.',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'For $x = t^3/3 - t$, $y = t^2$, a vertical tangent occurs when:',
    options: ['$t = 0$', '$t = 1$ and $t = -1$', '$t = \\sqrt{3}$', 'Never'],
    correctAnswer: 1,
    explanation: 'Vertical tangent when dx/dt = 0: t²−1 = 0, so t = ±1. Check dy/dt ≠ 0: 2t = ±2 ≠ 0. ✓',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'parametric-curves-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: 'The area swept by the polar curve $r = \\theta$ from $\\theta = 0$ to $\\theta = 2\\pi$ is:',
    options: ['$\\frac{4\\pi^3}{3}$', '$\\frac{2\\pi^3}{3}$', '$2\\pi^2$', '$\\pi^2$'],
    correctAnswer: 0,
    explanation: 'A = (1/2)∫₀^{2π} θ² dθ = (1/2)[θ³/3]₀^{2π} = (1/2)(8π³/3) = 4π³/3.',
    difficulty: 'medium',
    domain: 'parametric-polar-vector',
    topicSlug: 'polar-calculus-calcbc',
    formSet: 'both',
  },
  {
    question: '$\\int_0^{2\\pi} |\\mathbf{r}\'(t)|\\,dt$ (where $\\mathbf{r}(t)$ is a position vector) gives the:',
    options: [
      'Displacement',
      'Total distance traveled',
      'Average velocity',
      'Final position'
    ],
    correctAnswer: 1,
    explanation: '∫₀^{2π}|r\'(t)|dt is the integral of speed, which gives total distance traveled (arc length).',
    difficulty: 'easy',
    domain: 'parametric-polar-vector',
    topicSlug: 'vector-valued-functions-calcbc',
    formSet: 'both',
  },
"""

content = FILE.read_text()
# Find the closing bracket of calcBCQuestionPool
marker = "\n]\n\n/** Generate an exit quiz"
if marker not in content:
    raise SystemExit("Could not find insertion marker in ap-calculus-bc.ts")

new_content = content.replace(marker, NEW_QUESTIONS + marker)
FILE.write_text(new_content)

# Count questions
import re as re2
count = len(re2.findall(r"correctAnswer:", new_content))
print(f"✅ BC pool now has {count} questions total (was 36, added batch 1)")
