#!/usr/bin/env python3
"""Expand AP Biology question pool from 40 to ~300 questions."""

import pathlib

FILE = pathlib.Path(__file__).resolve().parent.parent / "src" / "data" / "exit-quizzes" / "ap-biology.ts"

# Generate new questions as compact single-line objects
NEW_QS = []

def q(id_num, slug, cat, question, opts, correct, explanation):
    o = "[" + ", ".join(f"'{o}'" for o in opts) + "]"
    NEW_QS.append(
        f"  {{ id: 'bio-q{id_num}', topicSlug: '{slug}', category: '{cat}', "
        f"question: '{question}', options: {o}, correctIndex: {correct}, "
        f"explanation: '{explanation}' }},"
    )

n = 41  # starting ID

# ══════════════════════════════════════════════════════════════════
# CHEMISTRY OF LIFE (20 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'Which bond holds the two strands of DNA together?', ['Covalent', 'Ionic', 'Hydrogen', 'Peptide'], 2, 'Hydrogen bonds between complementary bases hold the double helix together.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'Enzymes lower the:', ['Free energy of the products', 'Activation energy of a reaction', 'Equilibrium constant', 'Entropy of the universe'], 1, 'Enzymes reduce the activation energy needed to start a reaction.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'A buffer resists changes in:', ['Temperature', 'pH', 'Salinity', 'Volume'], 1, 'Buffers accept or donate H+ ions to maintain relatively constant pH.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'Dehydration synthesis produces water and:', ['Breaks polymers', 'Builds polymers', 'Denatures enzymes', 'Requires no energy'], 1, 'Monomers join via dehydration synthesis, releasing water.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'Which functional group is found in all amino acids?', ['Hydroxyl', 'Amino and carboxyl groups', 'Phosphate', 'Methyl only'], 1, 'All amino acids share an amino group (-NH₂) and a carboxyl group (-COOH).'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'Lipids are primarily characterized by being:', ['Highly soluble in water', 'Hydrophobic', 'Made of amino acids', 'Always saturated'], 1, 'Lipids are largely nonpolar and hydrophobic.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'A peptide bond forms between:', ['Two fatty acids', 'Two amino acids', 'A sugar and a base', 'Two nucleotides'], 1, 'Peptide bonds link the carboxyl group of one amino acid to the amino group of the next.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'Which element is found in proteins but NOT in carbohydrates?', ['Carbon', 'Oxygen', 'Nitrogen', 'Hydrogen'], 2, 'Proteins contain nitrogen in their amino groups; carbohydrates have only C, H, and O.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'The primary structure of a protein is its:', ['3D shape', 'Amino acid sequence', 'Alpha-helix pattern', 'Quaternary arrangement'], 1, 'Primary structure is the linear sequence of amino acids.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'Competitive inhibitors bind to the:', ['Allosteric site', 'Active site', 'Substrate directly', 'Product'], 1, 'Competitive inhibitors compete with substrate for the active site.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'What type of reaction breaks polymers into monomers?', ['Dehydration synthesis', 'Hydrolysis', 'Oxidation', 'Condensation'], 1, 'Hydrolysis adds water to break bonds between monomers.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'Saturated fats have:', ['Double bonds between carbons', 'No double bonds between carbons', 'Fewer hydrogens', 'Only short chains'], 1, 'Saturated fatty acids have only single bonds between carbon atoms.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'The induced fit model of enzyme action states that:', ['Enzymes are rigid locks', 'The enzyme changes shape slightly upon substrate binding', 'Substrates never change shape', 'Enzymes work at any temperature'], 1, 'The enzyme active site adjusts to fit the substrate more closely.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'Phospholipids are amphipathic because they have:', ['Two polar heads', 'A polar head and nonpolar tails', 'No charged groups', 'Only ionic bonds'], 1, 'The phosphate head is hydrophilic while the fatty acid tails are hydrophobic.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'Cellulose and starch are both made of glucose but differ in:', ['Monomer type', 'Glycosidic linkage orientation', 'Number of carbon atoms per unit', 'Both being digestible by humans'], 1, 'Cellulose has beta-1,4 linkages; starch has alpha-1,4 linkages.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'An allosteric activator:', ['Blocks the active site', 'Changes enzyme shape to increase activity', 'Permanently denatures the enzyme', 'Competes with the substrate'], 1, 'Allosteric activators bind elsewhere and enhance enzyme activity.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'The cohesion of water is due to:', ['Ionic bonds', 'Hydrogen bonds between water molecules', 'Covalent bonds with solutes', 'Van der Waals forces only'], 1, 'Hydrogen bonds between water molecules create cohesion.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'A disaccharide is formed by joining:', ['Two amino acids', 'Two monosaccharides', 'A sugar and an amino acid', 'Two nucleotides'], 1, 'Two monosaccharides join via glycosidic linkage to form a disaccharide.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'At high temperatures, enzymes typically:', ['Work faster indefinitely', 'Denature and lose function', 'Become more specific', 'Increase in concentration'], 1, 'High temperatures disrupt the 3D shape of enzymes, denaturing them.'); n+=1
q(n, 'ap-bio-chemistry-of-life', 'Chemistry of Life', 'The R-group (side chain) of an amino acid determines its:', ['Unique properties', 'Peptide bond type', 'Position in DNA', 'Sugar content'], 0, 'The R-group gives each amino acid its specific chemical properties.'); n+=1

# ══════════════════════════════════════════════════════════════════
# CELL STRUCTURE & FUNCTION (18 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'Prokaryotic cells lack:', ['DNA', 'A membrane-bound nucleus', 'Ribosomes', 'Cell membranes'], 1, 'Prokaryotes have no nuclear envelope.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'The rough endoplasmic reticulum has ribosomes that:', ['Produce lipids', 'Synthesize proteins for secretion', 'Break down old organelles', 'Generate ATP'], 1, 'Rough ER ribosomes make proteins destined for membranes or export.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'Mitochondria are thought to have originated via:', ['Spontaneous generation', 'Endosymbiosis', 'Budding from the nucleus', 'Viral infection'], 1, 'Endosymbiotic theory: mitochondria were once free-living bacteria engulfed by a host cell.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'The cytoskeleton includes:', ['Microfilaments, intermediate filaments, and microtubules', 'Only the cell wall', 'DNA strands', 'Lipid bilayer components'], 0, 'Three main cytoskeletal elements provide structure and movement.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'Lysosomes function primarily in:', ['Photosynthesis', 'Intracellular digestion', 'DNA replication', 'Protein synthesis'], 1, 'Lysosomes contain hydrolytic enzymes that break down macromolecules.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'Plant cells, unlike animal cells, have:', ['Cell walls and chloroplasts', 'Mitochondria', 'Ribosomes', 'Cell membranes'], 0, 'Plants have rigid cell walls and chloroplasts for photosynthesis.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'The smooth endoplasmic reticulum is involved in:', ['Protein synthesis', 'Lipid synthesis and detoxification', 'DNA repair', 'Cell division'], 1, 'Smooth ER synthesizes lipids and detoxifies substances.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'The nucleolus is the site of:', ['mRNA processing', 'Ribosomal RNA synthesis', 'DNA replication', 'Protein folding'], 1, 'The nucleolus produces ribosomal RNA (rRNA).'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'Cilia and flagella are composed mainly of:', ['Actin microfilaments', 'Microtubules in a 9+2 arrangement', 'Intermediate filaments', 'Collagen fibers'], 1, 'Cilia and flagella have a core of microtubules arranged in a 9+2 pattern.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'The central vacuole in plant cells functions in:', ['Storage, turgor pressure, and waste disposal', 'ATP production', 'Protein synthesis', 'Cell division'], 0, 'The central vacuole stores water, ions, and waste, maintaining turgor.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'Peroxisomes are involved in:', ['Protein secretion', 'Breaking down fatty acids and detoxifying hydrogen peroxide', 'Photosynthesis', 'DNA packaging'], 1, 'Peroxisomes oxidize fatty acids and neutralize H₂O₂ with catalase.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'The selectivity of membrane transport is primarily due to:', ['The cell wall', 'Transport proteins and lipid bilayer properties', 'Ribosomes on the membrane', 'Nuclear pores'], 1, 'Specific transport proteins and the hydrophobic bilayer determine what passes through.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'Tight junctions between cells:', ['Allow free passage of molecules', 'Prevent leakage between cells', 'Enable cell communication', 'Store calcium'], 1, 'Tight junctions seal adjacent cells to prevent extracellular leakage.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'Gap junctions allow:', ['Structural support only', 'Direct cytoplasmic communication between cells', 'Cell division', 'Antigen presentation'], 1, 'Gap junctions are channels that let ions and small molecules pass between cells.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'The endomembrane system includes all EXCEPT:', ['ER', 'Golgi apparatus', 'Mitochondria', 'Lysosomes'], 2, 'Mitochondria are not part of the endomembrane system (they have their own DNA and double membrane from endosymbiosis).'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'Cholesterol in the cell membrane:', ['Makes the membrane rigid at all temperatures', 'Helps maintain fluidity across temperature ranges', 'Blocks all transport', 'Only exists in plant cells'], 1, 'Cholesterol buffers membrane fluidity—prevents too fluid at high temp, too rigid at low.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'Plasmodesmata in plant cells function like:', ['Tight junctions', 'Gap junctions in animal cells', 'Desmosomes', 'Lysosomes'], 1, 'Plasmodesmata are channels between plant cells, similar to gap junctions.'); n+=1
q(n, 'ap-bio-cell-structure-function', 'Cell Structure', 'The extracellular matrix (ECM) of animal cells contains:', ['Cellulose', 'Collagen and proteoglycans', 'Chitin', 'Lignin'], 1, 'The ECM is composed of proteins like collagen and carbohydrate-rich proteoglycans.'); n+=1

# ══════════════════════════════════════════════════════════════════
# MEMBRANE TRANSPORT (12 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'A cell placed in a hypertonic solution will:', ['Swell', 'Shrink (crenate)', 'Stay the same', 'Divide'], 1, 'Water leaves the cell by osmosis, causing it to shrink.'); n+=1
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'Facilitated diffusion requires:', ['ATP', 'Transport proteins but no energy input', 'Endocytosis', 'Active pumping'], 1, 'Facilitated diffusion uses channel or carrier proteins but follows the concentration gradient (no ATP).'); n+=1
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'The sodium-potassium pump moves:', ['3 Na+ out and 2 K+ in per cycle', '2 Na+ out and 3 K+ in', 'Equal Na+ and K+', 'Only Na+ out'], 0, 'The Na+/K+-ATPase pumps 3 Na+ out and 2 K+ in per ATP hydrolyzed.'); n+=1
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'Endocytosis brings material INTO the cell by:', ['Diffusion', 'Membrane invagination forming vesicles', 'Pumping ions', 'Channel proteins'], 1, 'The plasma membrane folds inward to engulf material in a vesicle.'); n+=1
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'Aquaporins facilitate:', ['Ion transport', 'Rapid water movement across membranes', 'Glucose uptake', 'Amino acid transport'], 1, 'Aquaporins are channel proteins specific to water molecules.'); n+=1
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'In an isotonic solution, a cell:', ['Gains water', 'Loses water', 'Has no net water movement', 'Always lyses'], 2, 'Equal solute concentration inside and outside means no net osmosis.'); n+=1
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'Phagocytosis is a type of endocytosis involving:', ['Small dissolved molecules', 'Large particles or whole cells', 'Water only', 'Ions only'], 1, 'Phagocytosis engulfs large particles (cell eating).'); n+=1
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'The electrochemical gradient is determined by:', ['Concentration gradient and electrical potential', 'Only temperature', 'Only pressure', 'Enzyme activity alone'], 0, 'Both the concentration difference and charge difference across the membrane matter.'); n+=1
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'Exocytosis releases materials by:', ['Diffusion through channels', 'Fusion of vesicles with the plasma membrane', 'Breaking the cell wall', 'Nuclear export'], 1, 'Vesicles fuse with the membrane and dump contents outside.'); n+=1
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'Cotransport (symport) involves:', ['Two solutes moving in opposite directions', 'Two solutes moving in the same direction', 'Only one solute', 'No membrane proteins'], 1, 'Symport moves two substances in the same direction across a membrane.'); n+=1
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'Pinocytosis differs from phagocytosis in that it takes in:', ['Large solid particles', 'Small dissolved molecules and fluid', 'Only proteins', 'Only lipids'], 1, 'Pinocytosis is cell drinking—uptake of fluid and dissolved solutes.'); n+=1
q(n, 'ap-bio-membrane-transport', 'Membrane Transport', 'Water potential (Ψ) determines:', ['The direction of water movement', 'Enzyme activity', 'Cell division rate', 'Gene expression levels'], 0, 'Water moves from high Ψ to low Ψ.'); n+=1

# ══════════════════════════════════════════════════════════════════
# CELLULAR ENERGETICS (20 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'Glycolysis occurs in the:', ['Mitochondrial matrix', 'Cytoplasm', 'Chloroplast stroma', 'Nucleus'], 1, 'Glycolysis takes place in the cytoplasm of all cells.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'The net ATP produced by glycolysis is:', ['0', '2', '4', '36'], 1, 'Glycolysis produces 4 ATP but uses 2, netting 2 ATP.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'Pyruvate is converted to acetyl-CoA in the:', ['Cytoplasm', 'Mitochondrial matrix', 'Inner membrane', 'Outer membrane'], 1, 'Pyruvate enters the mitochondrial matrix for conversion to acetyl-CoA.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'NADH acts as an electron:', ['Acceptor', 'Carrier/donor', 'Destroyer', 'Inhibitor'], 1, 'NADH carries high-energy electrons to the electron transport chain.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'Chemiosmosis uses the H+ gradient to drive:', ['DNA synthesis', 'ATP synthase and ATP production', 'Protein folding', 'Glycolysis'], 1, 'H+ flows through ATP synthase, powering ATP production.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'In alcoholic fermentation, pyruvate is converted to:', ['Lactic acid', 'Ethanol and CO₂', 'Acetyl-CoA', 'Citric acid'], 1, 'Yeasts produce ethanol and CO₂ during alcoholic fermentation.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'Lactic acid fermentation occurs in:', ['Plants only', 'Human muscle cells during intense exercise', 'Only anaerobic bacteria', 'Chloroplasts'], 1, 'When O₂ is limited, muscle cells produce lactic acid.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'The Krebs cycle produces:', ['Large amounts of ATP directly', 'NADH, FADH₂, and some ATP/GTP', 'Glucose', 'Oxygen'], 1, 'The Krebs cycle generates electron carriers (NADH, FADH₂) and a small amount of ATP.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'The electron transport chain is located in the:', ['Cytoplasm', 'Inner mitochondrial membrane', 'Outer membrane', 'Nuclear envelope'], 1, 'The ETC is embedded in the inner mitochondrial membrane (cristae).'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'Anaerobic respiration differs from aerobic in that it uses:', ['Oxygen as final electron acceptor', 'An inorganic molecule other than O₂ as final electron acceptor', 'No electron transport chain', 'Only glycolysis'], 1, 'Anaerobic respiration uses molecules like sulfate or nitrate instead of O₂.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'Substrate-level phosphorylation produces ATP by:', ['Chemiosmosis', 'Directly transferring a phosphate to ADP', 'Photophosphorylation', 'Electron transport'], 1, 'A phosphate group is transferred directly from a substrate to ADP.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'The purpose of oxygen in cellular respiration is to:', ['Be released as a waste product', 'Accept electrons at the end of the ETC', 'Power glycolysis', 'Act as a coenzyme'], 1, 'O₂ is the terminal electron acceptor, forming water.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'FADH₂ delivers electrons to the ETC at a _____ energy level than NADH:', ['Higher', 'Lower', 'Equal', 'Variable'], 1, 'FADH₂ enters the ETC at Complex II (lower energy), producing fewer ATP.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'Feedback inhibition occurs when:', ['Products activate earlier enzyme steps', 'End products inhibit an earlier enzyme in the pathway', 'Substrates are destroyed', 'ATP is broken down'], 1, 'The product of a pathway inhibits an upstream enzyme, regulating the pathway.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'ATP has three phosphate groups; energy is released when:', ['A phosphate bond is broken (hydrolysis)', 'All three phosphates are removed at once', 'ATP is synthesized', 'The adenine base detaches'], 0, 'Hydrolysis of the terminal phosphate releases energy (~7.3 kcal/mol).'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'The proton gradient in mitochondria is established by:', ['ATP synthase', 'Complexes I, III, and IV of the ETC', 'Glycolysis', 'The Krebs cycle directly'], 1, 'ETC complexes pump H+ from the matrix to the intermembrane space.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'Uncoupling the proton gradient from ATP synthase would:', ['Increase ATP production', 'Release energy as heat without making ATP', 'Stop electron transport', 'Have no effect'], 1, 'Uncouplers dissipate the gradient, releasing energy as heat (like in brown fat).'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'FAD is reduced to FADH₂ during:', ['Glycolysis', 'The Krebs cycle', 'Fermentation', 'The Calvin cycle'], 1, 'FAD picks up electrons during the Krebs cycle (succinate → fumarate step).'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'Cyanide poisoning is lethal because it:', ['Blocks glycolysis', 'Inhibits Complex IV of the ETC, halting ATP production', 'Destroys the cell membrane', 'Prevents DNA replication'], 1, 'Cyanide binds to cytochrome c oxidase (Complex IV), blocking electron flow.'); n+=1
q(n, 'ap-bio-cellular-energetics', 'Cellular Energetics', 'The total ATP yield from one glucose molecule in aerobic respiration is approximately:', ['2', '4', '30-32', '100'], 2, 'Aerobic respiration yields about 30-32 ATP per glucose via glycolysis, Krebs, and oxidative phosphorylation.'); n+=1

# ══════════════════════════════════════════════════════════════════
# PHOTOSYNTHESIS (16 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'The light reactions occur in the:', ['Stroma', 'Thylakoid membranes', 'Cytoplasm', 'Mitochondria'], 1, 'Light-dependent reactions happen in/on the thylakoid membranes.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'Photosystem II splits water to produce:', ['Glucose', 'O₂, H+, and electrons', 'CO₂', 'NADH'], 1, 'Water is split (photolysis) in PSII, releasing O₂, H+, and electrons.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'The Calvin cycle fixes CO₂ using the enzyme:', ['ATP synthase', 'RuBisCO', 'Helicase', 'DNA polymerase'], 1, 'RuBisCO catalyzes CO₂ fixation by combining CO₂ with RuBP.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'NADPH is produced during:', ['The Calvin cycle', 'The light reactions', 'Glycolysis', 'Fermentation'], 1, 'NADP+ is reduced to NADPH at the end of the electron transport chain in the light reactions.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'C4 plants fix CO₂ initially into a:', ['3-carbon compound', '4-carbon compound (oxaloacetate)', '5-carbon compound', '6-carbon compound'], 1, 'C4 plants use PEP carboxylase to fix CO₂ into a 4-carbon molecule.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'CAM plants open stomata at:', ['Night to reduce water loss', 'Midday only', 'All times equally', 'Never'], 0, 'CAM plants fix CO₂ at night when stomata open, conserving water during the day.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'Photorespiration is a problem for C3 plants because:', ['It produces extra glucose', 'RuBisCO fixes O₂ instead of CO₂, wasting energy', 'It stops the light reactions', 'It increases NADPH'], 1, 'When O₂ competes with CO₂ at the RuBisCO active site, energy is wasted.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'The products of the light reactions used by the Calvin cycle are:', ['Glucose and O₂', 'ATP and NADPH', 'CO₂ and H₂O', 'Pyruvate and NADH'], 1, 'ATP and NADPH from light reactions provide energy and reducing power for the Calvin cycle.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'The overall equation for photosynthesis is:', ['CO₂ + H₂O → C₆H₁₂O₆ + O₂ (with light energy)', 'C₆H₁₂O₆ + O₂ → CO₂ + H₂O', 'N₂ + H₂ → NH₃', 'H₂O → H₂ + O₂'], 0, '6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ using light energy.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'Accessory pigments such as carotenoids:', ['Replace chlorophyll entirely', 'Absorb wavelengths chlorophyll cannot and pass energy to chlorophyll a', 'Only function in animals', 'Absorb green light'], 1, 'Carotenoids broaden the spectrum of light that drives photosynthesis.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'The electron transport chain in chloroplasts creates a H+ gradient in the:', ['Stroma', 'Thylakoid lumen', 'Cytoplasm', 'Matrix'], 1, 'Protons accumulate inside the thylakoid lumen, driving ATP synthase.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'G3P (glyceraldehyde-3-phosphate) is the direct product of:', ['Light reactions', 'The Calvin cycle', 'Glycolysis', 'Krebs cycle'], 1, 'G3P is produced in the reduction phase of the Calvin cycle and used to make glucose.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'How many turns of the Calvin cycle are needed to produce one glucose molecule?', ['1', '3', '6', '12'], 2, 'Each turn fixes one CO₂. Six turns produce two G3P molecules → one glucose.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'Cyclic electron flow produces:', ['ATP only (no NADPH or O₂)', 'NADPH only', 'Both ATP and NADPH', 'Glucose directly'], 0, 'Cyclic flow recycles electrons through PSI, generating ATP without NADPH or O₂.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'The action spectrum of photosynthesis most closely matches the:', ['Absorption spectrum of chlorophyll', 'Transmission spectrum of glass', 'Emission spectrum of the sun', 'Reflection spectrum of leaves'], 0, 'The action spectrum shows highest photosynthesis at wavelengths where pigments absorb most.'); n+=1
q(n, 'ap-bio-photosynthesis', 'Photosynthesis', 'Bundle sheath cells in C4 plants are where:', ['CO₂ is initially fixed', 'The Calvin cycle occurs', 'Light reactions exclusively happen', 'Water is split'], 1, 'C4 plants shuttle CO₂ to bundle sheath cells for the Calvin cycle, away from O₂.'); n+=1

# ══════════════════════════════════════════════════════════════════
# CELL CYCLE / MITOSIS / MEIOSIS (16 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-cell-cycle-mitosis', 'Cell Cycle', 'Cyclin-dependent kinases (CDKs) regulate the cell cycle by:', ['Destroying DNA', 'Phosphorylating target proteins at checkpoints', 'Synthesizing RNA', 'Directly splitting cells'], 1, 'CDKs, activated by cyclins, phosphorylate proteins to advance the cell cycle.'); n+=1
q(n, 'ap-bio-cell-cycle-mitosis', 'Cell Cycle', 'The G1 checkpoint primarily checks for:', ['Proper chromosome alignment', 'Adequate cell size and growth signals', 'Complete DNA replication', 'Successful cytokinesis'], 1, 'The G1 checkpoint ensures conditions are favorable before entering S phase.'); n+=1
q(n, 'ap-bio-cell-cycle-mitosis', 'Cell Cycle', 'Sister chromatids are separated during:', ['Prophase', 'Metaphase', 'Anaphase', 'Telophase'], 2, 'Anaphase: centromeres split and sister chromatids move to opposite poles.'); n+=1
q(n, 'ap-bio-cell-cycle-mitosis', 'Cell Cycle', 'Tumor suppressor genes like p53:', ['Promote uncontrolled division', 'Inhibit cell division or promote apoptosis when damage is detected', 'Only function in cancer cells', 'Encode growth factors'], 1, 'p53 halts the cell cycle or triggers apoptosis if DNA is damaged.'); n+=1
q(n, 'ap-bio-cell-cycle-mitosis', 'Cell Cycle', 'Proto-oncogenes become oncogenes through:', ['Normal regulation', 'Mutations that cause overactivity', 'Deletion of all copies', 'Proper checkpoint function'], 1, 'Mutations converting proto-oncogenes to oncogenes lead to uncontrolled growth.'); n+=1
q(n, 'ap-bio-cell-cycle-mitosis', 'Cell Cycle', 'Cytokinesis in plant cells involves:', ['A cleavage furrow', 'Formation of a cell plate', 'Budding', 'Binary fission'], 1, 'Plant cells build a cell plate from Golgi vesicles to divide the cytoplasm.'); n+=1
q(n, 'ap-bio-cell-cycle-mitosis', 'Cell Cycle', 'Mitosis produces:', ['4 haploid cells', '2 genetically identical diploid cells', '1 diploid cell', '2 haploid cells'], 1, 'Mitosis results in two genetically identical daughter cells.'); n+=1
q(n, 'ap-bio-cell-cycle-mitosis', 'Cell Cycle', 'The mitotic spindle is composed of:', ['Actin filaments', 'Microtubules', 'Intermediate filaments', 'Collagen fibers'], 1, 'Spindle fibers are microtubules that attach to kinetochores and move chromosomes.'); n+=1
q(n, 'ap-bio-meiosis', 'Meiosis', 'Meiosis produces:', ['2 diploid cells', '4 haploid cells', '4 diploid cells', '2 haploid cells'], 1, 'Meiosis I and II together produce four haploid daughter cells.'); n+=1
q(n, 'ap-bio-meiosis', 'Meiosis', 'Nondisjunction results in:', ['Normal chromosome numbers', 'Aneuploidy (abnormal chromosome numbers)', 'Polyploidy only', 'Gene mutations only'], 1, 'Failure of chromosomes to separate properly leads to too many or too few chromosomes.'); n+=1
q(n, 'ap-bio-meiosis', 'Meiosis', 'Homologous chromosomes pair during:', ['Mitosis', 'Meiosis I only', 'Meiosis II only', 'Both meiosis I and II'], 1, 'Synapsis of homologs occurs in prophase I of meiosis.'); n+=1
q(n, 'ap-bio-meiosis', 'Meiosis', 'The reduction in chromosome number occurs during:', ['Meiosis I', 'Meiosis II', 'Mitosis', 'S phase'], 0, 'Meiosis I separates homologs, reducing chromosome number by half.'); n+=1
q(n, 'ap-bio-meiosis', 'Meiosis', 'Down syndrome is caused by trisomy of chromosome:', ['13', '18', '21', 'X'], 2, 'Three copies of chromosome 21 cause Down syndrome.'); n+=1
q(n, 'ap-bio-meiosis', 'Meiosis', 'Genetic recombination during meiosis increases:', ['Mutation rate', 'Genetic diversity in offspring', 'Chromosome number', 'Cell size'], 1, 'Crossing over and independent assortment create new allele combinations.'); n+=1
q(n, 'ap-bio-meiosis', 'Meiosis', 'Meiosis II is similar to mitosis because:', ['Homologs pair up', 'Sister chromatids separate', 'Crossing over occurs', 'DNA replication happens before it'], 1, 'In meiosis II, sister chromatids are separated, like in mitosis.'); n+=1
q(n, 'ap-bio-meiosis', 'Meiosis', 'Chiasmata are visible evidence of:', ['DNA replication', 'Crossing over between homologs', 'Gene mutation', 'Independent assortment'], 1, 'Chiasmata are the physical X-shaped connections where crossing over occurred.'); n+=1

# ══════════════════════════════════════════════════════════════════
# MOLECULAR GENETICS & GENE REGULATION (24 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'DNA replication is described as semiconservative because:', ['Both strands are entirely new', 'Each new molecule has one old and one new strand', 'Only one strand is copied', 'Replication is error-free'], 1, 'Each daughter DNA molecule retains one parental strand.'); n+=1
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'Okazaki fragments are found on the:', ['Leading strand', 'Lagging strand', 'RNA primer', 'Both strands equally'], 1, 'The lagging strand is synthesized in short Okazaki fragments away from the replication fork.'); n+=1
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'RNA polymerase:', ['Requires a primer', 'Does not require a primer to initiate transcription', 'Only works on single-stranded DNA', 'Reads DNA 3′ to 5′ and builds RNA 3′ to 5′'], 1, 'Unlike DNA polymerase, RNA polymerase can start a new strand without a primer.'); n+=1
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'Introns are:', ['Coding sequences', 'Non-coding sequences removed during RNA processing', 'Parts of the ribosome', 'Regulatory regions only'], 1, 'Introns are spliced out of pre-mRNA; exons are expressed.'); n+=1
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'A missense mutation:', ['Changes one amino acid', 'Creates a premature stop codon', 'Has no effect on protein', 'Inserts an extra base'], 0, 'A missense mutation substitutes one amino acid for another in the protein.'); n+=1
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'Frameshift mutations are caused by:', ['Base substitutions', 'Insertions or deletions of bases not in multiples of 3', 'Silent mutations', 'Copying the correct sequence'], 1, 'Insertions or deletions shift the reading frame, altering all downstream codons.'); n+=1
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'Translation occurs on:', ['DNA', 'Ribosomes', 'The nuclear membrane', 'Telomeres'], 1, 'Ribosomes are the site of translation (protein synthesis).'); n+=1
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'tRNA carries:', ['DNA sequences', 'Amino acids to the ribosome', 'mRNA to the nucleus', 'Lipids for membrane assembly'], 1, 'tRNA anticodons match mRNA codons, delivering the correct amino acid.'); n+=1
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'The central dogma of molecular biology is:', ['DNA → RNA → Protein', 'Protein → RNA → DNA', 'RNA → DNA → Protein', 'Protein → DNA → RNA'], 0, 'Information flows from DNA to RNA to protein.'); n+=1
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'A point mutation that does not change the amino acid is called:', ['Missense', 'Nonsense', 'Silent', 'Frameshift'], 2, 'Silent mutations change a codon but code for the same amino acid due to redundancy.'); n+=1
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'Telomerase:', ['Shortens chromosomes', 'Extends telomeres to prevent chromosome shortening', 'Repairs mismatches', 'Unwinds DNA at the origin'], 1, 'Telomerase adds repetitive sequences to chromosome ends, preventing degradation.'); n+=1
q(n, 'ap-bio-molecular-genetics', 'Molecular Genetics', 'The 5′ cap and poly-A tail of mRNA function to:', ['Splice introns', 'Protect mRNA from degradation and aid in ribosome binding', 'Create tRNA', 'Inhibit translation'], 1, 'These modifications stabilize mRNA and help initiate translation.'); n+=1
q(n, 'ap-bio-gene-regulation', 'Gene Regulation', 'A promoter is a region where:', ['Transcription ends', 'RNA polymerase binds to begin transcription', 'Introns are removed', 'Translation begins'], 1, 'The promoter is the DNA sequence recognized by RNA polymerase.'); n+=1
q(n, 'ap-bio-gene-regulation', 'Gene Regulation', 'Enhancers can be located:', ['Only directly before the gene', 'Thousands of base pairs away from the gene they regulate', 'Only in prokaryotes', 'On a different chromosome exclusively'], 1, 'Enhancers can act at great distances from the promoter through DNA looping.'); n+=1
q(n, 'ap-bio-gene-regulation', 'Gene Regulation', 'DNA methylation typically:', ['Activates gene expression', 'Silences gene expression', 'Deletes genes', 'Creates new genes'], 1, 'Methyl groups added to DNA (especially CpG islands) usually suppress transcription.'); n+=1
q(n, 'ap-bio-gene-regulation', 'Gene Regulation', 'microRNAs (miRNAs) regulate gene expression by:', ['Enhancing translation', 'Binding to and degrading or blocking mRNA', 'Methylating DNA', 'Activating operons'], 1, 'miRNAs silence genes post-transcriptionally by targeting complementary mRNA.'); n+=1
q(n, 'ap-bio-gene-regulation', 'Gene Regulation', 'Alternative splicing allows:', ['One gene to encode multiple proteins', 'DNA to replicate faster', 'Mutations to be repaired', 'Chromosomes to condense'], 0, 'Different combinations of exons produce different mRNA variants from one gene.'); n+=1
q(n, 'ap-bio-gene-regulation', 'Gene Regulation', 'Histone acetylation generally:', ['Condenses chromatin', 'Loosens chromatin and promotes transcription', 'Methylates DNA', 'Removes histones entirely'], 1, 'Acetylation reduces histone-DNA affinity, opening chromatin for transcription.'); n+=1
q(n, 'ap-bio-gene-regulation', 'Gene Regulation', 'The trp operon in E. coli is regulated by:', ['An activator that turns it on when tryptophan is present', 'A repressor activated by tryptophan (negative feedback)', 'Lactose concentration', 'Temperature only'], 1, 'When tryptophan is abundant, it binds the repressor, which then blocks transcription.'); n+=1
q(n, 'ap-bio-gene-regulation', 'Gene Regulation', 'CRISPR-Cas9 technology allows scientists to:', ['Only study bacteria', 'Edit specific DNA sequences in organisms', 'Replace all genes at once', 'Stop all mutations permanently'], 1, 'CRISPR-Cas9 is a precise genome-editing tool guided by a short RNA sequence.'); n+=1
q(n, 'ap-bio-gene-regulation', 'Gene Regulation', 'Stem cells are important because they can:', ['Only form blood cells', 'Differentiate into specialized cell types', 'Never divide', 'Only exist in embryos'], 1, 'Stem cells have the potential to become many different cell types.'); n+=1
q(n, 'ap-bio-gene-regulation', 'Gene Regulation', 'Cell differentiation results from:', ['Losing genes', 'Differential gene expression', 'DNA mutations in every cell', 'Chromosome deletion'], 1, 'All cells have the same DNA; different genes are expressed in different cell types.'); n+=1

# ══════════════════════════════════════════════════════════════════
# CELL COMMUNICATION (10 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-cell-communication', 'Cell Communication', 'Paracrine signaling involves:', ['Hormones in the bloodstream', 'Local signals to nearby cells', 'Direct cell-to-cell contact', 'Signals to the same cell'], 1, 'Paracrine signals affect nearby target cells (short-range).'); n+=1
q(n, 'ap-bio-cell-communication', 'Cell Communication', 'Autocrine signaling means:', ['A cell signals itself', 'Signals travel through blood', 'Neurons release neurotransmitters', 'Cells communicate by touch'], 0, 'In autocrine signaling, the cell releases a signal that binds to its own receptors.'); n+=1
q(n, 'ap-bio-cell-communication', 'Cell Communication', 'G-protein coupled receptors activate:', ['Ion channels directly', 'G proteins that then activate enzymes or channels', 'Ribosomes', 'DNA polymerase'], 1, 'GPCRs transmit signals by activating associated G proteins inside the cell.'); n+=1
q(n, 'ap-bio-cell-communication', 'Cell Communication', 'Second messengers like cAMP:', ['Leave the cell', 'Amplify signals inside the cell', 'Block all receptors', 'Only work in plants'], 1, 'cAMP is a common intracellular second messenger that amplifies the signal.'); n+=1
q(n, 'ap-bio-cell-communication', 'Cell Communication', 'Apoptosis is:', ['Uncontrolled cell growth', 'Programmed cell death', 'Cell division', 'Cell fusion'], 1, 'Apoptosis is the orderly, programmed destruction of a cell.'); n+=1
q(n, 'ap-bio-cell-communication', 'Cell Communication', 'Signal transduction pathways often involve:', ['Phosphorylation cascades', 'Direct gene deletion', 'Chromosome duplication', 'Random protein degradation'], 0, 'Kinase cascades phosphorylate a series of proteins, relaying the signal.'); n+=1
q(n, 'ap-bio-cell-communication', 'Cell Communication', 'Endocrine signaling uses:', ['Direct cell contact', 'Hormones traveling through the bloodstream', 'Gap junctions', 'Plasmodesmata'], 1, 'Endocrine glands secrete hormones that travel via blood to distant targets.'); n+=1
q(n, 'ap-bio-cell-communication', 'Cell Communication', 'Receptor tyrosine kinases (RTKs) activate by:', ['Binding DNA', 'Dimerizing and cross-phosphorylating upon ligand binding', 'Releasing second messengers without enzymes', 'Blocking ion channels'], 1, 'Ligand binding causes RTKs to dimerize and phosphorylate each other.'); n+=1
q(n, 'ap-bio-cell-communication', 'Cell Communication', 'The IP₃/DAG pathway releases Ca²+ from the:', ['Mitochondria', 'Endoplasmic reticulum', 'Golgi apparatus', 'Nucleus'], 1, 'IP₃ binds ER receptors, releasing stored Ca²+ into the cytoplasm.'); n+=1
q(n, 'ap-bio-cell-communication', 'Cell Communication', 'Quorum sensing is used by:', ['Only human cells', 'Bacteria to coordinate group behaviors', 'Plants for phototropism', 'Fungi for sporulation only'], 1, 'Bacteria use quorum sensing to detect population density and coordinate activities.'); n+=1

# ══════════════════════════════════════════════════════════════════
# MENDELIAN + BEYOND GENETICS (16 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'A testcross determines:', ['If an organism is homozygous or heterozygous', 'The sex of offspring', 'If a trait is autosomal', 'The mutation rate'], 0, 'Crossing with a homozygous recessive reveals the unknown genotype.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'Codominance means:', ['One allele is dominant over the other', 'Both alleles are fully expressed in the heterozygote', 'Alleles blend together', 'Neither allele is expressed'], 1, 'Both alleles contribute equally and are visible (e.g., AB blood type).'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'Incomplete dominance results in a _____ phenotype in heterozygotes:', ['Dominant', 'Recessive', 'Blended/intermediate', 'Variable'], 2, 'Neither allele is fully dominant; the heterozygote shows an intermediate phenotype.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'Epistasis occurs when:', ['One gene masks the expression of another gene', 'Two genes are on the same chromosome', 'Both alleles are codominant', 'Genes are linked'], 0, 'An epistatic gene influences the phenotypic expression of another gene.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'Polygenic traits are controlled by:', ['One gene with multiple alleles', 'Multiple genes contributing to one phenotype', 'Mitochondrial DNA only', 'Environmental factors alone'], 1, 'Multiple genes contribute additively (e.g., skin color, height).'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'X-linked recessive traits are more common in males because:', ['Males have two X chromosomes', 'Males have only one X chromosome, so one copy of the allele is expressed', 'Y chromosome carries the same genes', 'Males have more mutations'], 1, 'With only one X, males express any recessive allele present on it.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'The law of segregation states that:', ['Linked genes always stay together', 'Allele pairs separate during gamete formation', 'All traits sort independently', 'Offspring always resemble parents'], 1, 'Each parent passes one allele per gene to offspring; alleles segregate in meiosis.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'A dihybrid cross AaBb × AaBb gives a phenotype ratio of:', ['3:1', '1:2:1', '9:3:3:1', '1:1:1:1'], 2, 'Independent assortment of two genes gives 9:3:3:1 in the F2 generation.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'Linked genes:', ['Always sort independently', 'Are on the same chromosome and tend to be inherited together', 'Are always on different chromosomes', 'Cannot undergo crossing over'], 1, 'Genes close together on the same chromosome are linked.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'A pedigree chart can be used to:', ['Track inheritance patterns through generations', 'Sequence a gene', 'Clone organisms', 'Measure enzyme activity'], 0, 'Pedigrees map phenotypes across family members to determine inheritance patterns.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'Pleiotropy means:', ['One gene affects only one trait', 'One gene affects multiple phenotypic traits', 'Multiple genes affect one trait', 'Genes have no phenotype'], 1, 'A pleiotropic gene influences several seemingly unrelated phenotypes.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'The Hardy-Weinberg equation p² + 2pq + q² = 1 represents:', ['Genotype frequencies in a non-evolving population', 'Allele frequencies only', 'Phenotype ratios in a cross', 'Mutation rates'], 0, 'p², 2pq, q² give expected frequencies of AA, Aa, aa genotypes at equilibrium.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'Multiple alleles in a population means:', ['Each individual has more than two alleles', 'The gene has more than two alleles in the population', 'There is only one phenotype', 'Individuals are triploid'], 1, 'A gene can have many alleles in a population (e.g., ABO blood group: I^A, I^B, i).'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'A chi-square test in genetics is used to:', ['Determine DNA sequence', 'Test whether observed ratios differ significantly from expected', 'Measure enzyme kinetics', 'Count chromosomes'], 1, 'Chi-square compares observed vs expected phenotypic ratios.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'Maternal inheritance patterns suggest the trait is encoded by:', ['Autosomal genes', 'Mitochondrial DNA', 'Y-linked genes', 'X-linked dominant genes'], 1, 'Mitochondria are inherited from the mother; maternal inheritance points to mtDNA.'); n+=1
q(n, 'ap-bio-mendelian-genetics', 'Genetics', 'Genomic imprinting involves:', ['Expression depending on which parent contributed the allele', 'Both alleles always being expressed equally', 'Deletion of one allele', 'Random X-inactivation'], 0, 'Imprinted genes are expressed in a parent-of-origin-specific manner.'); n+=1

# ══════════════════════════════════════════════════════════════════
# EVOLUTION (24 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-natural-selection', 'Evolution', 'Stabilizing selection favors:', ['Extreme phenotypes', 'The intermediate phenotype', 'Only the largest individuals', 'Random phenotypes'], 1, 'Stabilizing selection reduces variation by favoring the average.'); n+=1
q(n, 'ap-bio-natural-selection', 'Evolution', 'Directional selection shifts the population mean toward:', ['The center', 'One extreme of the trait distribution', 'Multiple peaks', 'No particular direction'], 1, 'Directional selection favors individuals at one end of the phenotypic range.'); n+=1
q(n, 'ap-bio-natural-selection', 'Evolution', 'Disruptive selection results in:', ['One dominant phenotype', 'Two or more extreme phenotypes being favored', 'Stabilization of the mean', 'No evolutionary change'], 1, 'Disruptive selection favors both extremes at the expense of intermediates.'); n+=1
q(n, 'ap-bio-natural-selection', 'Evolution', 'A bottleneck event:', ['Increases genetic diversity', 'Drastically reduces population size and genetic variation', 'Only occurs in large populations', 'Is a form of natural selection'], 1, 'A drastic reduction in population size leads to reduced genetic diversity.'); n+=1
q(n, 'ap-bio-natural-selection', 'Evolution', 'The founder effect occurs when:', ['A large population stays in place', 'A small group colonizes a new area with limited genetic variation', 'Natural selection acts on large populations', 'Mutation rates increase'], 1, 'A small founding population carries only a subset of the original gene pool.'); n+=1
q(n, 'ap-bio-natural-selection', 'Evolution', 'Gene flow between populations tends to:', ['Increase differences between populations', 'Decrease differences between populations', 'Have no effect', 'Only transfer mutations'], 1, 'Migration and gene flow homogenize allele frequencies between populations.'); n+=1
q(n, 'ap-bio-natural-selection', 'Evolution', 'Sexual selection can lead to:', ['Traits that reduce survival but increase mating success', 'Only increased body size', 'Reduced genetic variation', 'No phenotypic changes'], 0, 'Sexual selection may favor elaborate traits (like peacock tails) despite survival costs.'); n+=1
q(n, 'ap-bio-natural-selection', 'Evolution', 'Fitness in evolutionary terms means:', ['Physical strength', 'Reproductive success (contribution to next generation)', 'Speed and agility', 'Size of the organism'], 1, 'Biological fitness is measured by reproductive output, not physical prowess.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'Analogous structures result from:', ['Common ancestry', 'Convergent evolution', 'Gene flow', 'Genetic drift'], 1, 'Similar structures in unrelated organisms evolved independently for similar functions.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'Vestigial structures are evidence of evolution because they:', ['Have essential current functions', 'Are remnants of structures useful in ancestors', 'Appear only in fossils', 'Are identical across species'], 1, 'Vestigial organs (like the human appendix) indicate descent from ancestors that used them.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'Biogeography supports evolution by showing that:', ['All species are found everywhere', 'Species distributions reflect evolutionary history and continental drift', 'Only one continent has life', 'Islands have no unique species'], 1, 'Geographic distribution of species correlates with evolutionary and geological history.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'Molecular evidence (DNA comparisons) shows that:', ['More closely related species have more similar DNA', 'All species have identical DNA', 'DNA cannot be compared across species', 'Proteins are unrelated to genes'], 0, 'DNA sequence similarity correlates with evolutionary relatedness.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'Speciation requires:', ['Reproductive isolation', 'Geographic proximity', 'Identical environments', 'Cloning'], 0, 'New species form when populations become reproductively isolated.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'Allopatric speciation occurs when:', ['Populations are separated by a geographic barrier', 'Populations live in the same area', 'Only plants speciate', 'Mutations stop occurring'], 0, 'A physical barrier (mountain, river) separates populations, leading to divergence.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'Sympatric speciation can occur through:', ['Geographic isolation', 'Polyploidy or habitat differentiation without physical barriers', 'Genetic drift in large populations', 'Convergent evolution'], 1, 'Sympatric speciation happens within the same area, often via polyploidy in plants.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'Adaptive radiation is:', ['Rapid diversification of a lineage into many ecological niches', 'Gradual extinction', 'Convergent evolution', 'Unchanged species over time'], 0, 'A single ancestor rapidly diversifies into many forms filling different niches.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'Punctuated equilibrium proposes that:', ['Evolution is always gradual', 'Species change little for long periods, then change rapidly', 'No species ever go extinct', 'Natural selection does not exist'], 1, 'Long periods of stasis are punctuated by brief episodes of rapid change.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'Endosymbiotic theory explains the origin of:', ['Ribosomes', 'Mitochondria and chloroplasts', 'The nucleus', 'Cell walls'], 1, 'Mitochondria and chloroplasts were once independent prokaryotes engulfed by a host cell.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'The Miller-Urey experiment demonstrated that:', ['Life can be created in a lab', 'Organic molecules can form from inorganic precursors under early Earth conditions', 'DNA can self-replicate', 'Cells form spontaneously'], 1, 'The experiment showed that amino acids and other organics can form abiotically.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'Phylogenetic trees are constructed based on:', ['Physical size only', 'Shared derived characteristics and molecular data', 'Geographic location', 'Common names'], 1, 'Phylogenies use morphological, molecular, and fossil evidence for classification.'); n+=1
q(n, 'ap-bio-natural-selection', 'Evolution', 'Microevolution refers to:', ['Large-scale evolutionary changes over millions of years', 'Small changes in allele frequencies within a population', 'Origin of new phyla', 'Only fossil evidence'], 1, 'Microevolution is changes in allele frequencies at the population level over short time.'); n+=1
q(n, 'ap-bio-natural-selection', 'Evolution', 'Heterozygote advantage (overdominance) occurs when:', ['Homozygotes have the highest fitness', 'Heterozygotes have higher fitness than either homozygote', 'Only recessive alleles are favored', 'There is no selection'], 1, 'Heterozygote advantage maintains both alleles (e.g., sickle cell trait and malaria resistance).'); n+=1
q(n, 'ap-bio-natural-selection', 'Evolution', 'Artificial selection differs from natural selection in that:', ['Humans choose which traits to favor', 'It does not change allele frequencies', 'It only works on plants', 'It cannot produce variation'], 0, 'Humans deliberately breed for desired traits in artificial selection.'); n+=1
q(n, 'ap-bio-evolution-evidence', 'Evolution', 'A clade on a phylogenetic tree includes:', ['Only extant species', 'An ancestor and all its descendants', 'Only extinct species', 'Unrelated organisms'], 1, 'A clade is a monophyletic group containing a common ancestor and all descendants.'); n+=1

# ══════════════════════════════════════════════════════════════════
# ECOLOGY (24 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-ecology-energy-flow', 'Ecology', 'Decomposers play a key role by:', ['Creating new energy', 'Recycling nutrients back into the ecosystem', 'Being top predators', 'Fixing nitrogen from the air'], 1, 'Decomposers break down dead matter, returning nutrients to the soil.'); n+=1
q(n, 'ap-bio-ecology-energy-flow', 'Ecology', 'A food web differs from a food chain in that it:', ['Shows only one pathway', 'Shows multiple interconnected feeding relationships', 'Ignores decomposers', 'Only includes producers'], 1, 'Food webs show the complexity of feeding relationships in an ecosystem.'); n+=1
q(n, 'ap-bio-ecology-energy-flow', 'Ecology', 'Gross primary productivity (GPP) minus respiration equals:', ['Net primary productivity (NPP)', 'Total biomass', 'Carrying capacity', 'Entropy'], 0, 'NPP = GPP − R; it is the energy available for consumers.'); n+=1
q(n, 'ap-bio-ecology-energy-flow', 'Ecology', 'Nitrogen fixation is performed by:', ['All plants', 'Certain bacteria and archaea', 'Animals', 'Fungi only'], 1, 'Only specific prokaryotes can convert N₂ gas to ammonia (NH₃).'); n+=1
q(n, 'ap-bio-ecology-energy-flow', 'Ecology', 'The carbon cycle includes:', ['Only photosynthesis', 'Photosynthesis, respiration, decomposition, and combustion', 'Only combustion', 'Only respiration'], 1, 'Carbon cycles through biological and geological processes.'); n+=1
q(n, 'ap-bio-ecology-energy-flow', 'Ecology', 'Eutrophication is caused by:', ['Excess nutrients leading to algal blooms', 'Drought', 'Predator removal', 'Volcanic eruptions'], 0, 'Excess nitrogen/phosphorus causes algal overgrowth, depleting O₂.'); n+=1
q(n, 'ap-bio-ecology-interactions', 'Ecology', 'Commensalism is when:', ['Both species benefit', 'One benefits and the other is unaffected', 'Both are harmed', 'One is harmed'], 1, 'In commensalism, one organism benefits while the other is neither helped nor harmed.'); n+=1
q(n, 'ap-bio-ecology-interactions', 'Ecology', 'Parasitism differs from predation in that the parasite:', ['Kills the host immediately', 'Lives on or in the host, usually not killing it immediately', 'Benefits the host', 'Is always larger than the host'], 1, 'Parasites exploit hosts over time without usually killing them quickly.'); n+=1
q(n, 'ap-bio-ecology-interactions', 'Ecology', 'Keystone species:', ['Are always the most abundant', 'Have a disproportionately large effect on community structure', 'Only include predators', 'Have no ecological impact'], 1, 'Removal of a keystone species causes significant community changes.'); n+=1
q(n, 'ap-bio-ecology-interactions', 'Ecology', 'Primary succession occurs on:', ['Previously inhabited land', 'Newly formed or exposed surfaces with no soil', 'Farmland', 'Established forests'], 1, 'Primary succession begins on bare rock or new land (e.g., after a volcanic eruption).'); n+=1
q(n, 'ap-bio-ecology-interactions', 'Ecology', 'Secondary succession occurs after:', ['Complete destruction of soil', 'A disturbance that leaves soil and seeds intact', 'Formation of a new island', 'Glacier retreat on bare rock'], 1, 'Secondary succession is faster because soil and seed banks remain.'); n+=1
q(n, 'ap-bio-ecology-interactions', 'Ecology', 'Biodiversity is generally highest in:', ['Polar regions', 'Tropical regions', 'Deserts', 'Deep ocean trenches'], 1, 'Tropical ecosystems support the greatest species diversity.'); n+=1
q(n, 'ap-bio-population-ecology', 'Population Ecology', 'Exponential growth is modeled by:', ['dN/dt = rN', 'dN/dt = rN(K-N)/K', 'N = K', 'dN/dt = K'], 0, 'Exponential growth: dN/dt = rN, with no carrying capacity limit.'); n+=1
q(n, 'ap-bio-population-ecology', 'Population Ecology', 'Logistic growth is modeled by:', ['dN/dt = rN', 'dN/dt = rN(K-N)/K', 'N = rK', 'dN/dt = K/N'], 1, 'Logistic growth incorporates carrying capacity K.'); n+=1
q(n, 'ap-bio-population-ecology', 'Population Ecology', 'r-selected species tend to:', ['Be large with few offspring', 'Be small with many offspring and rapid reproduction', 'Live in stable environments', 'Have long lifespans'], 1, 'r-selected species prioritize quantity of offspring and fast reproduction.'); n+=1
q(n, 'ap-bio-population-ecology', 'Population Ecology', 'K-selected species tend to:', ['Have many offspring with little parental care', 'Have few offspring with extensive parental care', 'Reproduce only once', 'Be invasive species'], 1, 'K-selected species invest heavily in fewer offspring.'); n+=1
q(n, 'ap-bio-population-ecology', 'Population Ecology', 'A survivorship curve Type I indicates:', ['High mortality early in life', 'Constant mortality rate', 'High survival until old age', 'No pattern'], 2, 'Type I organisms (e.g., humans) have low mortality until late in life.'); n+=1
q(n, 'ap-bio-population-ecology', 'Population Ecology', 'Interspecific competition is competition between:', ['Members of the same species', 'Different species for the same resources', 'Plants and animals only', 'Predator and prey'], 1, 'Interspecific = between species; intraspecific = within one species.'); n+=1
q(n, 'ap-bio-population-ecology', 'Population Ecology', 'The competitive exclusion principle states that:', ['Two species can share the same niche indefinitely', 'Two species competing for the same resources cannot coexist indefinitely', 'Competition always leads to extinction', 'Predators prevent all competition'], 1, 'Two species with identical niches cannot coexist; one will outcompete the other.'); n+=1
q(n, 'ap-bio-population-ecology', 'Population Ecology', 'Resource partitioning allows competing species to coexist by:', ['Ignoring each other', 'Using different portions of the resource or habitat', 'Increasing population sizes', 'Eliminating predators'], 1, 'Niche differentiation reduces overlap and allows coexistence.'); n+=1
q(n, 'ap-bio-ecology-interactions', 'Ecology', 'Biological magnification refers to:', ['Increasing population size', 'Toxin concentration increasing up the food chain', 'Magnifying glass use in fieldwork', 'Nutrient cycling'], 1, 'Toxins like DDT become more concentrated at higher trophic levels.'); n+=1
q(n, 'ap-bio-ecology-interactions', 'Ecology', 'An ecological niche includes:', ['Only where an organism lives', 'The role and all interactions of an organism in its environment', 'Only food sources', 'Only predators'], 1, 'An ecological niche encompasses habitat, diet, behavior, and all interactions.'); n+=1

# ══════════════════════════════════════════════════════════════════
# BIOTECHNOLOGY & SCIENTIFIC PRACTICES (12 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-biotechnology', 'Biotechnology', 'Gel electrophoresis separates DNA fragments by:', ['Color', 'Size (smaller fragments travel farther)', 'Shape', 'Temperature'], 1, 'DNA is negatively charged and migrates toward the positive electrode; smaller fragments move faster.'); n+=1
q(n, 'ap-bio-biotechnology', 'Biotechnology', 'A plasmid is a:', ['Type of virus', 'Small circular DNA molecule in bacteria used as a vector', 'Protein structure', 'Part of the ribosome'], 1, 'Plasmids can carry foreign DNA into bacterial cells for cloning.'); n+=1
q(n, 'ap-bio-biotechnology', 'Biotechnology', 'Genetically modified organisms (GMOs) contain:', ['No DNA changes', 'DNA from another organism inserted using biotechnology', 'Only natural mutations', 'Extra chromosomes from the same species'], 1, 'GMOs have been engineered with genes from other species for desired traits.'); n+=1
q(n, 'ap-bio-biotechnology', 'Biotechnology', 'DNA fingerprinting is used in forensics because:', ['All humans have identical DNA', 'Individuals (except identical twins) have unique DNA profiles', 'DNA cannot be extracted from crime scenes', 'Proteins are more unique than DNA'], 1, 'STR (short tandem repeat) patterns are unique to each individual.'); n+=1
q(n, 'ap-bio-biotechnology', 'Biotechnology', 'Reverse transcriptase creates:', ['RNA from DNA', 'DNA from an RNA template', 'Protein from RNA', 'Lipids from protein'], 1, 'Reverse transcriptase synthesizes cDNA from mRNA.'); n+=1
q(n, 'ap-bio-biotechnology', 'Biotechnology', 'Gene therapy aims to:', ['Remove all genes', 'Replace or supplement a faulty gene with a functional copy', 'Clone entire organisms', 'Increase mutation rates'], 1, 'Gene therapy introduces functional genes to treat genetic disorders.'); n+=1
q(n, 'ap-bio-experimental-design', 'Scientific Practices', 'A null hypothesis states that:', ['The experiment will succeed', 'There is no significant difference between groups', 'The results are always significant', 'Variables are always correlated'], 1, 'The null hypothesis predicts no effect or difference.'); n+=1
q(n, 'ap-bio-experimental-design', 'Scientific Practices', 'Replication in experiments:', ['Is unnecessary', 'Increases reliability of results', 'Should be avoided', 'Only applies to genetics'], 1, 'Repeating experiments increases confidence in the results.'); n+=1
q(n, 'ap-bio-experimental-design', 'Scientific Practices', 'A large sample size is important because it:', ['Guarantees no errors', 'Reduces the effect of random variation', 'Eliminates all variables', 'Is easier than small samples'], 1, 'Larger samples better represent the population and reduce sampling error.'); n+=1
q(n, 'ap-bio-experimental-design', 'Scientific Practices', 'The independent variable in an experiment is:', ['What you measure', 'What you manipulate', 'What stays constant', 'The control group'], 1, 'The independent variable is deliberately changed by the researcher.'); n+=1
q(n, 'ap-bio-experimental-design', 'Scientific Practices', 'A p-value less than 0.05 suggests:', ['Results are not significant', 'Results are statistically significant', 'The null hypothesis is proven true', 'More data is always needed'], 1, 'A p-value < 0.05 means there is less than a 5% chance the results are due to chance.'); n+=1
q(n, 'ap-bio-experimental-design', 'Scientific Practices', 'Standard error measures:', ['The mean of the data set', 'Variability of sample means around the population mean', 'Total population size', 'The mode of the data'], 1, 'Standard error indicates how much sample means are expected to vary.'); n+=1

# ══════════════════════════════════════════════════════════════════
# IMMUNE SYSTEM / PHYSIOLOGY (12 new)
# ══════════════════════════════════════════════════════════════════
q(n, 'ap-bio-immune-system', 'Physiology', 'Innate immunity includes:', ['Antibody production', 'Skin barriers, phagocytes, and inflammation', 'Memory cells', 'Helper T cell activation'], 1, 'Innate immunity is nonspecific and includes physical barriers and phagocytes.'); n+=1
q(n, 'ap-bio-immune-system', 'Physiology', 'Adaptive immunity is characterized by:', ['Nonspecific responses', 'Specificity and memory', 'Only involving skin', 'No involvement of lymphocytes'], 1, 'Adaptive immunity targets specific pathogens and develops immunological memory.'); n+=1
q(n, 'ap-bio-immune-system', 'Physiology', 'Helper T cells are important because they:', ['Directly kill infected cells', 'Activate B cells and cytotoxic T cells', 'Produce antibodies', 'Only function in innate immunity'], 1, 'Helper T cells coordinate the adaptive immune response.'); n+=1
q(n, 'ap-bio-immune-system', 'Physiology', 'Cytotoxic T cells destroy:', ['Bacteria outside cells', 'Virus-infected or cancerous cells', 'Antibodies', 'All types of white blood cells'], 1, 'Cytotoxic (killer) T cells target and destroy infected or abnormal cells.'); n+=1
q(n, 'ap-bio-immune-system', 'Physiology', 'MHC molecules function to:', ['Transport oxygen', 'Display antigen fragments on cell surfaces', 'Produce antibodies', 'Form clot factors'], 1, 'MHC proteins present antigens to T cells for recognition.'); n+=1
q(n, 'ap-bio-immune-system', 'Physiology', 'Passive immunity is gained by:', ['Vaccination', 'Receiving pre-formed antibodies (e.g., from mother)', 'Infection', 'Bone marrow transplant'], 1, 'Passive immunity involves receiving antibodies rather than producing them.'); n+=1
q(n, 'ap-bio-immune-system', 'Physiology', 'Autoimmune diseases occur when:', ['The immune system attacks foreign pathogens', 'The immune system attacks the body own cells', 'No immune response occurs', 'Only innate immunity is active'], 1, 'Autoimmunity results from self-recognition failure.'); n+=1
q(n, 'ap-bio-immune-system', 'Physiology', 'Antigens are:', ['Antibodies', 'Molecules that trigger immune responses', 'White blood cells', 'Complement proteins'], 1, 'Antigens are foreign molecules recognized by the immune system.'); n+=1
q(n, 'ap-bio-immune-system', 'Physiology', 'Inflammation serves to:', ['Spread pathogens', 'Recruit immune cells and increase blood flow to the site', 'Reduce immune response', 'Only cause pain'], 1, 'Inflammation is a protective response that brings immune cells to the infection site.'); n+=1
q(n, 'ap-bio-immune-system', 'Physiology', 'Clonal selection explains how:', ['One B cell makes many types of antibodies', 'A B cell specific to an antigen proliferates to produce many identical cells', 'T cells become B cells', 'All lymphocytes are activated at once'], 1, 'Antigen binding selects and activates a specific B cell clone that then proliferates.'); n+=1
q(n, 'ap-bio-immune-system', 'Physiology', 'The complement system:', ['Is part of adaptive immunity only', 'Enhances phagocytosis and forms membrane attack complexes', 'Only works against viruses', 'Produces antibodies'], 1, 'Complement proteins assist in pathogen destruction and inflammation.'); n+=1
q(n, 'ap-bio-immune-system', 'Physiology', 'Allergic reactions are caused by:', ['Normal immune function', 'Overreaction of the immune system to harmless substances', 'Underactive immune system', 'Only bacterial infections'], 1, 'Allergies are hypersensitivity reactions to normally harmless antigens.'); n+=1

content = FILE.read_text()

# Find insertion point - before the closing bracket
marker = "\n]\n\nexport function generateExitQuiz"
if marker not in content:
    raise SystemExit("Could not find insertion marker in ap-biology.ts")

insert_block = "\n" + "\n".join(NEW_QS) + "\n"
new_content = content.replace(marker, insert_block + marker)
FILE.write_text(new_content)

# Count
import re
count = len(re.findall(r"correctIndex:", new_content))
print(f"✅ AP Biology pool now has {count} questions total (was 40)")
