#!/usr/bin/env python3
"""
Batch 2: Add ~90 new questions — limits (+25), differentiation (+30), applications-derivatives (+30), plus a few integration.
"""
import os

NEW_QUESTIONS = r"""
  // ══════════════════════════════════════════════════════════════
  //  BATCH 2 — Limits & Continuity (25 new)
  // ══════════════════════════════════════════════════════════════
  {
    question: 'What is $\\lim_{x \\to 3} \\dfrac{x^2 - 9}{x^2 - 5x + 6}$?',
    options: ['$6$', '$\\dfrac{6}{1}$', '$0$', '$\\infty$'],
    correctAnswer: 0,
    explanation: 'Factor: $\\frac{(x-3)(x+3)}{(x-3)(x-2)} = \\frac{x+3}{x-2}$. At $x=3$: $\\frac{6}{1} = 6$.',
    difficulty: 'medium',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to 0} \\dfrac{1 - \\cos x}{x^2}$?',
    options: ['$0$', '$\\dfrac{1}{2}$', '$1$', 'Does not exist'],
    correctAnswer: 1,
    explanation: 'L\'Hôpital (twice) or known limit: $\\frac{1 - \\cos x}{x^2} \\to \\frac{1}{2}$.',
    difficulty: 'hard',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to \\infty} \\left(1 + \\dfrac{3}{x}\\right)^x$?',
    options: ['$1$', '$e^3$', '$3e$', '$\\infty$'],
    correctAnswer: 1,
    explanation: 'This is the standard form $\\lim(1 + k/x)^x = e^k$. Here $k = 3$, so the limit is $e^3$.',
    difficulty: 'hard',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\dfrac{\\sqrt{x+4} - 2}{x}$, what is $\\lim_{x \\to 0} f(x)$?',
    options: ['$\\dfrac{1}{4}$', '$\\dfrac{1}{2}$', '$0$', 'Does not exist'],
    correctAnswer: 0,
    explanation: 'Multiply by conjugate: $\\frac{(x+4) - 4}{x(\\sqrt{x+4}+2)} = \\frac{1}{\\sqrt{x+4}+2} \\to \\frac{1}{4}$.',
    difficulty: 'hard',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to -\\infty} \\dfrac{x}{\\sqrt{x^2 + 1}}$?',
    options: ['$1$', '$-1$', '$0$', 'Does not exist'],
    correctAnswer: 1,
    explanation: 'For $x < 0$: $\\sqrt{x^2 + 1} \\approx |x| = -x$. So $\\frac{x}{-x} = -1$.',
    difficulty: 'hard',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to 0} \\dfrac{\\sin(3x)}{\\sin(5x)}$?',
    options: ['$\\dfrac{3}{5}$', '$\\dfrac{5}{3}$', '$0$', '$1$'],
    correctAnswer: 0,
    explanation: '$\\frac{\\sin(3x)}{\\sin(5x)} = \\frac{\\sin(3x)}{3x} \\cdot \\frac{5x}{\\sin(5x)} \\cdot \\frac{3}{5} \\to 1 \\cdot 1 \\cdot \\frac{3}{5}$.',
    difficulty: 'medium',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to 1} \\dfrac{x^3 - 1}{x - 1}$?',
    options: ['$1$', '$3$', '$0$', 'Does not exist'],
    correctAnswer: 1,
    explanation: 'Factor: $\\frac{(x-1)(x^2+x+1)}{x-1} = x^2+x+1$. At $x=1$: $1+1+1 = 3$.',
    difficulty: 'easy',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to \\infty} \\dfrac{5x^2 - 2x}{3x^3 + x}$?',
    options: ['$\\dfrac{5}{3}$', '$0$', '$\\infty$', '$\\dfrac{-2}{1}$'],
    correctAnswer: 1,
    explanation: 'Degree of numerator (2) < degree of denominator (3), so the limit is $0$.',
    difficulty: 'easy',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to 0^+} \\dfrac{1}{x}$?',
    options: ['$0$', '$+\\infty$', '$-\\infty$', 'Does not exist'],
    correctAnswer: 1,
    explanation: 'As $x \\to 0^+$, $\\frac{1}{x}$ grows without bound positively, so the limit is $+\\infty$.',
    difficulty: 'easy',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'If $\\lim_{x \\to a^-} f(x) = 4$ and $\\lim_{x \\to a^+} f(x) = 4$ but $f(a) = 7$, then at $x = a$:',
    options: ['$f$ is continuous', '$f$ has a removable discontinuity', '$f$ has a jump discontinuity', '$f$ has an infinite discontinuity'],
    correctAnswer: 1,
    explanation: 'The two-sided limit exists ($= 4$) but does not equal $f(a) = 7$. This is a removable discontinuity.',
    difficulty: 'medium',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to 0} \\dfrac{e^{2x} - 1}{x}$?',
    options: ['$1$', '$2$', '$e^2$', '$0$'],
    correctAnswer: 1,
    explanation: 'L\'Hôpital or derivative definition: $\\frac{d}{dx}[e^{2x}]\\big|_{x=0} = 2e^0 = 2$.',
    difficulty: 'medium',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to \\pi} \\dfrac{\\sin x}{x - \\pi}$?',
    options: ['$1$', '$0$', '$-1$', 'Does not exist'],
    correctAnswer: 2,
    explanation: 'L\'Hôpital: $\\frac{\\cos x}{1}\\big|_{x=\\pi} = \\cos \\pi = -1$.',
    difficulty: 'hard',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'The horizontal asymptote of $f(x) = \\dfrac{3e^x}{e^x + 2}$ as $x \\to \\infty$ is:',
    options: ['$y = 0$', '$y = 3$', '$y = \\dfrac{3}{2}$', 'No horizontal asymptote'],
    correctAnswer: 1,
    explanation: 'Divide numerator and denominator by $e^x$: $\\frac{3}{1 + 2e^{-x}} \\to \\frac{3}{1} = 3$ as $x \\to \\infty$.',
    difficulty: 'medium',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'The horizontal asymptote of $f(x) = \\dfrac{3e^x}{e^x + 2}$ as $x \\to -\\infty$ is:',
    options: ['$y = 0$', '$y = 3$', '$y = \\dfrac{3}{2}$', 'No horizontal asymptote'],
    correctAnswer: 0,
    explanation: 'As $x \\to -\\infty$, $e^x \\to 0$, so $\\frac{3(0)}{0 + 2} = 0$.',
    difficulty: 'medium',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{h \\to 0} \\dfrac{\\sin\\left(\\frac{\\pi}{6} + h\\right) - \\frac{1}{2}}{h}$?',
    options: ['$\\dfrac{1}{2}$', '$\\dfrac{\\sqrt{3}}{2}$', '$-\\dfrac{1}{2}$', '$0$'],
    correctAnswer: 1,
    explanation: 'This is $f\'(\\pi/6)$ where $f(x) = \\sin x$. $f\'(x) = \\cos x$, so $f\'(\\pi/6) = \\cos(\\pi/6) = \\frac{\\sqrt{3}}{2}$.',
    difficulty: 'hard',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'Which of the following functions is continuous everywhere?',
    options: ['$f(x) = \\dfrac{1}{x}$', '$f(x) = \\dfrac{x}{|x|}$', '$f(x) = |x - 3|$', '$f(x) = \\tan x$'],
    correctAnswer: 2,
    explanation: '$|x - 3|$ is continuous for all real $x$. The others have discontinuities at $x = 0$ or $x = \\frac{\\pi}{2} + n\\pi$.',
    difficulty: 'easy',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to 4} \\dfrac{\\sqrt{x} - 2}{x - 4}$?',
    options: ['$0$', '$\\dfrac{1}{4}$', '$\\dfrac{1}{2}$', '$1$'],
    correctAnswer: 1,
    explanation: 'Rationalize: $\\frac{1}{\\sqrt{x}+2} \\to \\frac{1}{4}$. Or L\'Hôpital: $\\frac{1/(2\\sqrt{x})}{1}\\big|_{x=4} = \\frac{1}{4}$.',
    difficulty: 'medium',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'If $g$ is continuous on $[0, 8]$, $g(0) = -2$, and $g(8) = 5$, by the IVT there exists $c \\in (0,8)$ with $g(c) = $',
    options: ['$8$ only', 'Any value in $[-2, 5]$', '$0$ only', '$3$ only'],
    correctAnswer: 1,
    explanation: 'The IVT guarantees every value between $-2$ and $5$ is attained on $[0, 8]$.',
    difficulty: 'easy',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to \\infty} \\dfrac{\\ln x}{x}$?',
    options: ['$0$', '$1$', '$\\infty$', 'Does not exist'],
    correctAnswer: 0,
    explanation: '$\\frac{\\infty}{\\infty}$ form. L\'Hôpital: $\\frac{1/x}{1} = \\frac{1}{x} \\to 0$.',
    difficulty: 'medium',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to 0} \\dfrac{x}{\\tan x}$?',
    options: ['$0$', '$1$', '$\\infty$', 'Does not exist'],
    correctAnswer: 1,
    explanation: '$\\frac{x}{\\tan x} = \\frac{x}{\\sin x} \\cdot \\cos x \\to 1 \\cdot 1 = 1$.',
    difficulty: 'medium',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\begin{cases} x^2 & x \\leq 2 \\\\ 3x - a & x > 2 \\end{cases}$ is continuous at $x = 2$, then $a = $',
    options: ['$0$', '$2$', '$4$', '$-2$'],
    correctAnswer: 1,
    explanation: 'Left limit: $2^2 = 4$. Right limit: $3(2) - a = 6 - a$. Set equal: $6 - a = 4$, so $a = 2$.',
    difficulty: 'medium',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to 0^+} e^{-1/x}$?',
    options: ['$0$', '$1$', '$\\infty$', 'Does not exist'],
    correctAnswer: 0,
    explanation: 'As $x \\to 0^+$, $-1/x \\to -\\infty$, so $e^{-1/x} \\to e^{-\\infty} = 0$.',
    difficulty: 'hard',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{x \\to 2} \\dfrac{x^2 - 4}{|x - 2|}$?',
    options: ['$4$', '$-4$', '$0$', 'Does not exist'],
    correctAnswer: 3,
    explanation: 'From the right: $\\frac{(x-2)(x+2)}{x-2} = x+2 \\to 4$. From the left: $\\frac{(x-2)(x+2)}{-(x-2)} = -(x+2) \\to -4$. Limits differ.',
    difficulty: 'hard',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'At which value of $x$ does $f(x) = \\dfrac{x^2 - 1}{x^2 + 3x + 2}$ have a removable discontinuity?',
    options: ['$x = 1$', '$x = -1$', '$x = -2$', '$x = 0$'],
    correctAnswer: 1,
    explanation: '$f(x) = \\frac{(x-1)(x+1)}{(x+1)(x+2)}$. The $(x+1)$ cancels: removable at $x = -1$. Non-removable at $x = -2$.',
    difficulty: 'medium',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\lim_{n \\to \\infty} \\left(1 + \\dfrac{1}{n}\\right)^{2n}$?',
    options: ['$e$', '$e^2$', '$2e$', '$1$'],
    correctAnswer: 1,
    explanation: '$\\left[\\left(1 + \\frac{1}{n}\\right)^n\\right]^2 \\to e^2$.',
    difficulty: 'hard',
    domain: 'limits',
    topicSlug: 'limits-continuity-calcab',
    formSet: 'both',
  },

  // ══════════════════════════════════════════════════════════════
  //  BATCH 2 — Differentiation (30 new)
  // ══════════════════════════════════════════════════════════════
  {
    question: 'If $f(x) = (3x + 1)^5$, then $f\'(x) = $',
    options: ['$5(3x+1)^4$', '$15(3x+1)^4$', '$5(3x+1)^4 \\cdot 3x$', '$3(3x+1)^5$'],
    correctAnswer: 1,
    explanation: 'Chain rule: $5(3x+1)^4 \\cdot 3 = 15(3x+1)^4$.',
    difficulty: 'easy',
    domain: 'differentiation',
    topicSlug: 'chain-rule-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\dfrac{d}{dx}[\\ln(\\cos x)]$?',
    options: ['$\\dfrac{1}{\\cos x}$', '$-\\tan x$', '$\\tan x$', '$-\\sec x$'],
    correctAnswer: 1,
    explanation: 'Chain rule: $\\frac{1}{\\cos x}\\cdot(-\\sin x) = -\\tan x$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'chain-rule-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\dfrac{1}{\\sqrt{x}} = x^{-1/2}$, then $f\'(4) = $',
    options: ['$-\\dfrac{1}{16}$', '$-\\dfrac{1}{4}$', '$\\dfrac{1}{4}$', '$-\\dfrac{1}{8}$'],
    correctAnswer: 0,
    explanation: '$f\'(x) = -\\frac{1}{2}x^{-3/2}$. $f\'(4) = -\\frac{1}{2} \\cdot 4^{-3/2} = -\\frac{1}{2} \\cdot \\frac{1}{8} = -\\frac{1}{16}$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\dfrac{d}{dx}[x \\cdot e^{-x}]$?',
    options: ['$e^{-x}$', '$e^{-x}(1 - x)$', '$-xe^{-x}$', '$e^{-x}(1 + x)$'],
    correctAnswer: 1,
    explanation: 'Product rule: $1 \\cdot e^{-x} + x \\cdot (-e^{-x}) = e^{-x}(1 - x)$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'If $y = \\sin(x^2)$, then $\\dfrac{dy}{dx} = $',
    options: ['$\\cos(x^2)$', '$2x\\cos(x^2)$', '$x^2 \\cos(x^2)$', '$2\\sin(x)\\cos(x)$'],
    correctAnswer: 1,
    explanation: 'Chain rule: $\\cos(x^2) \\cdot 2x = 2x\\cos(x^2)$.',
    difficulty: 'easy',
    domain: 'differentiation',
    topicSlug: 'chain-rule-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\dfrac{d}{dx}[\\arctan(x)]$?',
    options: ['$\\dfrac{1}{\\sqrt{1-x^2}}$', '$\\dfrac{1}{1+x^2}$', '$\\dfrac{-1}{1+x^2}$', '$\\sec^2(x)$'],
    correctAnswer: 1,
    explanation: 'Standard inverse trig derivative: $\\frac{d}{dx}[\\arctan x] = \\frac{1}{1+x^2}$.',
    difficulty: 'easy',
    domain: 'differentiation',
    topicSlug: 'inverse-functions-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\cos(3x)$, then $f\'\'(x) = $',
    options: ['$-9\\cos(3x)$', '$9\\cos(3x)$', '$-3\\sin(3x)$', '$3\\cos(3x)$'],
    correctAnswer: 0,
    explanation: '$f\'(x) = -3\\sin(3x)$. $f\'\'(x) = -3 \\cdot 3\\cos(3x) = -9\\cos(3x)$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'chain-rule-calcab',
    formSet: 'both',
  },
  {
    question: 'The derivative of $f(x) = 5^x$ is:',
    options: ['$x \\cdot 5^{x-1}$', '$5^x \\ln 5$', '$5^x$', '$\\dfrac{5^x}{\\ln 5}$'],
    correctAnswer: 1,
    explanation: '$\\frac{d}{dx}[a^x] = a^x \\ln a$. So $\\frac{d}{dx}[5^x] = 5^x \\ln 5$.',
    difficulty: 'easy',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'If $xy + y^2 = 1$, then $\\dfrac{dy}{dx}$ at the point $(0, 1)$ is:',
    options: ['$-\\dfrac{1}{2}$', '$-1$', '$0$', '$1$'],
    correctAnswer: 0,
    explanation: 'Differentiate: $y + x\\frac{dy}{dx} + 2y\\frac{dy}{dx} = 0$. At $(0,1)$: $1 + 0 + 2\\frac{dy}{dx} = 0$, so $\\frac{dy}{dx} = -\\frac{1}{2}$.',
    difficulty: 'hard',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'If $h(x) = f(g(x))$, $g(3) = 7$, $g\'(3) = 4$, and $f\'(7) = -2$, then $h\'(3) = $',
    options: ['$-8$', '$-2$', '$8$', '$-6$'],
    correctAnswer: 0,
    explanation: '$h\'(3) = f\'(g(3)) \\cdot g\'(3) = f\'(7) \\cdot 4 = (-2)(4) = -8$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'chain-rule-calcab',
    formSet: 'both',
  },
  {
    question: 'The derivative of $y = e^{\\sin x}$ is:',
    options: ['$e^{\\sin x}$', '$e^{\\cos x}$', '$e^{\\sin x} \\cos x$', '$\\cos x \\cdot e^x$'],
    correctAnswer: 2,
    explanation: 'Chain rule: $e^{\\sin x} \\cdot \\cos x$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'chain-rule-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\dfrac{e^x}{x}$ for $x > 0$, then $f\'(1) = $',
    options: ['$0$', '$e$', '$1$', '$e - 1$'],
    correctAnswer: 0,
    explanation: 'Quotient rule: $f\'(x) = \\frac{xe^x - e^x}{x^2} = \\frac{e^x(x-1)}{x^2}$. At $x = 1$: $\\frac{e(0)}{1} = 0$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\dfrac{d}{dx}\\left[\\dfrac{\\sin x}{x}\\right]$ at $x = \\pi$?',
    options: ['$\\dfrac{-1}{\\pi}$', '$\\dfrac{1}{\\pi}$', '$0$', '$\\dfrac{-\\pi}{\\pi^2}$'],
    correctAnswer: 0,
    explanation: 'Quotient rule: $\\frac{x\\cos x - \\sin x}{x^2}$. At $x=\\pi$: $\\frac{\\pi(-1) - 0}{\\pi^2} = \\frac{-1}{\\pi}$.',
    difficulty: 'hard',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'The equation of the normal line to $y = x^3$ at $x = 1$ is:',
    options: ['$y = 3x - 2$', '$y - 1 = -\\dfrac{1}{3}(x - 1)$', '$y = -3x + 4$', '$y - 1 = 3(x - 1)$'],
    correctAnswer: 1,
    explanation: '$y\'(1) = 3(1)^2 = 3$. Normal slope $= -\\frac{1}{3}$. Point $(1,1)$: $y - 1 = -\\frac{1}{3}(x-1)$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\ln(e^x + 1)$, then $f\'(0) = $',
    options: ['$\\dfrac{1}{2}$', '$1$', '$\\dfrac{1}{e}$', '$\\ln 2$'],
    correctAnswer: 0,
    explanation: '$f\'(x) = \\frac{e^x}{e^x + 1}$. At $x = 0$: $\\frac{1}{1+1} = \\frac{1}{2}$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'chain-rule-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\dfrac{d}{dx}[|x|]$ at $x = 3$?',
    options: ['$1$', '$-1$', '$3$', '$0$'],
    correctAnswer: 0,
    explanation: 'For $x > 0$, $|x| = x$, so $\\frac{d}{dx}|x| = 1$.',
    difficulty: 'easy',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = (\\ln x)^2$, then $f\'(e) = $',
    options: ['$\\dfrac{2}{e}$', '$\\dfrac{1}{e}$', '$2e$', '$\\dfrac{2}{e^2}$'],
    correctAnswer: 0,
    explanation: '$f\'(x) = 2\\ln x \\cdot \\frac{1}{x}$. At $x = e$: $f\'(e) = \\frac{2 \\cdot 1}{e} = \\frac{2}{e}$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'chain-rule-calcab',
    formSet: 'both',
  },
  {
    question: 'If $g(x) = \\sqrt{1 + \\tan x}$, then $g\'(0) = $',
    options: ['$\\dfrac{1}{2}$', '$1$', '$\\dfrac{\\sqrt{2}}{2}$', '$0$'],
    correctAnswer: 0,
    explanation: '$g\'(x) = \\frac{\\sec^2 x}{2\\sqrt{1+\\tan x}}$. At $x = 0$: $\\frac{1}{2\\sqrt{1}} = \\frac{1}{2}$.',
    difficulty: 'hard',
    domain: 'differentiation',
    topicSlug: 'chain-rule-calcab',
    formSet: 'both',
  },
  {
    question: 'If $y = x^2 \\sin(3x)$, then $y\'(0) = $',
    options: ['$0$', '$3$', '$1$', '$6$'],
    correctAnswer: 0,
    explanation: '$y\' = 2x\\sin(3x) + 3x^2\\cos(3x)$. At $x = 0$: $0 + 0 = 0$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'The derivative of $f(x) = e^{x^2}$ at $x = 1$ is:',
    options: ['$e$', '$2e$', '$e^2$', '$2e^2$'],
    correctAnswer: 1,
    explanation: '$f\'(x) = 2xe^{x^2}$. At $x = 1$: $f\'(1) = 2(1)e^1 = 2e$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'chain-rule-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\cot x$, then $f\'(x) = $',
    options: ['$\\tan x$', '$-\\csc^2 x$', '$\\sec^2 x$', '$-\\cos^2 x$'],
    correctAnswer: 1,
    explanation: 'Standard derivative: $\\frac{d}{dx}[\\cot x] = -\\csc^2 x$.',
    difficulty: 'easy',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\dfrac{x}{\\ln x}$ for $x > 1$, then $f\'(e) = $',
    options: ['$0$', '$1$', '$\\dfrac{1}{e}$', '$e - 1$'],
    correctAnswer: 0,
    explanation: 'Quotient rule: $f\'(x) = \\frac{\\ln x - x \\cdot 1/x}{(\\ln x)^2} = \\frac{\\ln x - 1}{(\\ln x)^2}$. At $x = e$: $\\frac{1-1}{1} = 0$.',
    difficulty: 'hard',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f^{-1}(x)$ is the inverse of $f$ and $f(2) = 5$ with $f\'(2) = 3$, then $(f^{-1})\'(5) = $',
    options: ['$3$', '$\\dfrac{1}{3}$', '$-3$', '$\\dfrac{1}{5}$'],
    correctAnswer: 1,
    explanation: '$(f^{-1})\'(y) = \\frac{1}{f\'(f^{-1}(y))}$. Since $f^{-1}(5) = 2$: $(f^{-1})\'(5) = \\frac{1}{f\'(2)} = \\frac{1}{3}$.',
    difficulty: 'hard',
    domain: 'differentiation',
    topicSlug: 'inverse-functions-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\dfrac{d}{dx}[\\log_{10} x]$?',
    options: ['$\\dfrac{1}{x}$', '$\\dfrac{1}{x \\ln 10}$', '$\\dfrac{10}{x}$', '$\\dfrac{\\ln 10}{x}$'],
    correctAnswer: 1,
    explanation: '$\\frac{d}{dx}[\\log_a x] = \\frac{1}{x \\ln a}$. For $a = 10$: $\\frac{1}{x \\ln 10}$.',
    difficulty: 'easy',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'If $y = \\tan^{-1}(e^x)$, then $\\dfrac{dy}{dx} = $',
    options: ['$\\dfrac{e^x}{1+e^{2x}}$', '$\\dfrac{1}{1+e^{2x}}$', '$\\dfrac{e^x}{1+e^x}$', '$e^x \\sec^2(e^x)$'],
    correctAnswer: 0,
    explanation: 'Chain rule: $\\frac{1}{1+(e^x)^2} \\cdot e^x = \\frac{e^x}{1+e^{2x}}$.',
    difficulty: 'hard',
    domain: 'differentiation',
    topicSlug: 'inverse-functions-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = x e^x$, then $f\'\'(x) = $',
    options: ['$e^x$', '$xe^x$', '$e^x(x+2)$', '$e^x(x+1)$'],
    correctAnswer: 2,
    explanation: '$f\'(x) = e^x + xe^x = e^x(1+x)$. $f\'\'(x) = e^x(1+x) + e^x = e^x(x+2)$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f$ is differentiable and $f(3) = 2$, $f\'(3) = 5$, what is $\\dfrac{d}{dx}[xf(x)]$ at $x = 3$?',
    options: ['$17$', '$15$', '$10$', '$7$'],
    correctAnswer: 0,
    explanation: '$(xf(x))\' = f(x) + xf\'(x)$. At $x = 3$: $f(3) + 3f\'(3) = 2 + 15 = 17$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'If $y = \\cos^3(2x)$, then $\\dfrac{dy}{dx} = $',
    options: ['$-6\\cos^2(2x)\\sin(2x)$', '$3\\cos^2(2x)$', '$-3\\cos^2(2x)\\sin(2x)$', '$6\\cos^2(2x)$'],
    correctAnswer: 0,
    explanation: 'Chain rule twice: $3\\cos^2(2x) \\cdot (-\\sin(2x)) \\cdot 2 = -6\\cos^2(2x)\\sin(2x)$.',
    difficulty: 'hard',
    domain: 'differentiation',
    topicSlug: 'chain-rule-calcab',
    formSet: 'both',
  },
  {
    question: 'At what point on $y = e^x$ is the tangent line parallel to $y = 2x$?',
    options: ['$(\\ln 2, 2)$', '$(0, 1)$', '$(1, e)$', '$(2, e^2)$'],
    correctAnswer: 0,
    explanation: 'Need $e^x = 2$, so $x = \\ln 2$ and $y = e^{\\ln 2} = 2$. Point: $(\\ln 2, 2)$.',
    difficulty: 'medium',
    domain: 'differentiation',
    topicSlug: 'basic-differentiation-rules-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\dfrac{d}{dx}[\\sin^{-1}(x)]$ at $x = 0$?',
    options: ['$0$', '$1$', '$-1$', '$\\dfrac{\\pi}{2}$'],
    correctAnswer: 1,
    explanation: '$\\frac{d}{dx}[\\sin^{-1}(x)] = \\frac{1}{\\sqrt{1-x^2}}$. At $x = 0$: $\\frac{1}{\\sqrt{1}} = 1$.',
    difficulty: 'easy',
    domain: 'differentiation',
    topicSlug: 'inverse-functions-derivatives-calcab',
    formSet: 'both',
  },

  // ══════════════════════════════════════════════════════════════
  //  BATCH 2 — Applications of Derivatives (30 new)
  // ══════════════════════════════════════════════════════════════
  {
    question: 'The function $f(x) = x^3 - 12x + 1$ is increasing on:',
    options: ['$(-\\infty, -2)$ and $(2, \\infty)$', '$(-2, 2)$', '$(0, \\infty)$', '$(-\\infty, 0)$'],
    correctAnswer: 0,
    explanation: '$f\'(x) = 3x^2 - 12 = 3(x^2 - 4) = 3(x-2)(x+2)$. $f\' > 0$ when $x < -2$ or $x > 2$.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'If the velocity of a particle is $v(t) = t^2 - 4t + 3$, the particle changes direction at $t = $',
    options: ['$t = 1$ and $t = 3$', '$t = 2$ only', '$t = 1$ only', '$t = 3$ only'],
    correctAnswer: 0,
    explanation: '$v(t) = (t-1)(t-3) = 0$ at $t = 1, 3$. $v$ changes sign at both, so direction changes at both.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'particle-motion-calcab',
    formSet: 'both',
  },
  {
    question: 'A box with a square base and open top has surface area $48$. The maximum volume is:',
    options: ['$16$', '$32$', '$64$', '$24$'],
    correctAnswer: 1,
    explanation: '$S = x^2 + 4xh = 48$, $h = \\frac{48 - x^2}{4x}$. $V = x^2 h = \\frac{48x - x^3}{4}$. $V\' = \\frac{48 - 3x^2}{4} = 0 \\Rightarrow x = 4$. $V = \\frac{48(4) - 64}{4} = 32$.',
    difficulty: 'hard',
    domain: 'applications-derivatives',
    topicSlug: 'optimization-calcab',
    formSet: 'both',
  },
  {
    question: 'The inflection point of $f(x) = x^3 - 3x^2 + 2$ is at $x = $',
    options: ['$0$', '$1$', '$2$', '$-1$'],
    correctAnswer: 1,
    explanation: '$f\'\'(x) = 6x - 6 = 0 \\Rightarrow x = 1$. $f\'\'$ changes sign there, so inflection at $x = 1$.',
    difficulty: 'easy',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'The acceleration of a particle with position $s(t) = \\sin(t)$ at $t = \\pi/2$ is:',
    options: ['$0$', '$1$', '$-1$', '$\\pi/2$'],
    correctAnswer: 2,
    explanation: '$v(t) = \\cos t$, $a(t) = -\\sin t$. At $t = \\pi/2$: $a = -\\sin(\\pi/2) = -1$.',
    difficulty: 'easy',
    domain: 'applications-derivatives',
    topicSlug: 'particle-motion-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f\'(c) = 0$ and $f\'\'(c) > 0$, then $f$ has at $x = c$:',
    options: ['A local maximum', 'A local minimum', 'An inflection point', 'Not enough information'],
    correctAnswer: 1,
    explanation: 'Second Derivative Test: $f\'(c) = 0$ and $f\'\'(c) > 0$ means concave up at a critical point, so local minimum.',
    difficulty: 'easy',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'The absolute minimum value of $f(x) = x^3 - 3x$ on $[-2, 2]$ is:',
    options: ['$-2$', '$2$', '$-4$', '$0$'],
    correctAnswer: 0,
    explanation: '$f\'(x) = 3x^2 - 3 = 0 \\Rightarrow x = \\pm 1$. $f(-2) = -2$, $f(-1) = 2$, $f(1) = -2$, $f(2) = 2$. Min is $-2$.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'A balloon is inflated so its radius increases at $2$ cm/s. How fast is the volume increasing when $r = 5$ cm?',
    options: ['$200\\pi$ cm³/s', '$100\\pi$ cm³/s', '$50\\pi$ cm³/s', '$500\\pi$ cm³/s'],
    correctAnswer: 0,
    explanation: '$V = \\frac{4}{3}\\pi r^3$. $\\frac{dV}{dt} = 4\\pi r^2 \\frac{dr}{dt} = 4\\pi(25)(2) = 200\\pi$.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'Using the linearization of $f(x) = \\sqrt{x}$ at $a = 25$, approximate $\\sqrt{26}$:',
    options: ['$5.1$', '$5.05$', '$5.2$', '$5.01$'],
    correctAnswer: 0,
    explanation: '$L(x) = 5 + \\frac{1}{10}(x - 25)$. $L(26) = 5 + 0.1 = 5.1$.',
    difficulty: 'easy',
    domain: 'applications-derivatives',
    topicSlug: 'linearization-differentials-calcab',
    formSet: 'both',
  },
  {
    question: 'Rolle\'s Theorem guarantees a zero of $f\'$ on $(a,b)$ when:',
    options: ['$f$ is continuous on $[a,b]$ and differentiable on $(a,b)$', '$f$ is continuous on $[a,b]$, differentiable on $(a,b)$, and $f(a) = f(b)$', '$f\'(a) = f\'(b) = 0$', '$f$ has a critical point in $(a,b)$'],
    correctAnswer: 1,
    explanation: 'Rolle\'s Theorem requires continuity on $[a,b]$, differentiability on $(a,b)$, and $f(a) = f(b)$.',
    difficulty: 'easy',
    domain: 'applications-derivatives',
    topicSlug: 'theorem-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'The speed of a particle at time $t$ is $|v(t)|$ where $v(t) = t^2 - 4$. The speed is increasing at $t = 3$ because:',
    options: ['$v(3) > 0$ and $a(3) > 0$', '$v(3) > 0$ and $a(3) < 0$', '$v(3) < 0$ and $a(3) < 0$', '$a(3) > 0$ only'],
    correctAnswer: 0,
    explanation: '$v(3) = 5 > 0$ and $a(t) = 2t$, $a(3) = 6 > 0$. Same sign means speed is increasing.',
    difficulty: 'hard',
    domain: 'applications-derivatives',
    topicSlug: 'particle-motion-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = xe^{-x}$, the absolute maximum on $[0, \\infty)$ occurs at:',
    options: ['$x = 0$', '$x = 1$', '$x = e$', '$x = 2$'],
    correctAnswer: 1,
    explanation: '$f\'(x) = e^{-x} - xe^{-x} = e^{-x}(1-x) = 0 \\Rightarrow x = 1$. $f(0) = 0$, $f(1) = e^{-1}$, $f \\to 0$ as $x \\to \\infty$.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'A rectangle has its base on the $x$-axis and vertices on $y = 4 - x^2$. The maximum area is:',
    options: ['$\\dfrac{16\\sqrt{3}}{9}$', '$\\dfrac{32\\sqrt{3}}{9}$', '$8$', '$\\dfrac{16}{3}$'],
    correctAnswer: 1,
    explanation: 'Area $= 2x(4-x^2)$. $A\'(x) = 8 - 6x^2 = 0 \\Rightarrow x = \\frac{2}{\\sqrt{3}}$. $A = 2 \\cdot \\frac{2}{\\sqrt{3}} \\cdot \\frac{8}{3} = \\frac{32}{3\\sqrt{3}} = \\frac{32\\sqrt{3}}{9}$.',
    difficulty: 'hard',
    domain: 'applications-derivatives',
    topicSlug: 'optimization-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f\'(x) = (x-1)^2(x-3)$, then $f$ has:',
    options: ['Local max at $x = 1$, local min at $x = 3$', 'Neither max nor min at $x = 1$, local min at $x = 3$', 'Local min at $x = 1$, local max at $x = 3$', 'Local max at both $x = 1$ and $x = 3$'],
    correctAnswer: 1,
    explanation: 'At $x = 1$: $f\'$ does not change sign (stays $\\leq 0$). At $x = 3$: $f\'$ changes from $-$ to $+$ (local min).',
    difficulty: 'hard',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'A cone-shaped tank fills with water at $2$ m³/min. If the tank has radius $3$ m and height $6$ m, how fast is the water level rising when $h = 2$ m?',
    options: ['$\\dfrac{2}{\\pi}$ m/min', '$\\dfrac{8}{\\pi}$ m/min', '$\\dfrac{1}{\\pi}$ m/min', '$\\dfrac{4}{\\pi}$ m/min'],
    correctAnswer: 0,
    explanation: 'Similar triangles: $r = h/2$. $V = \\frac{\\pi}{3}(h/2)^2 h = \\frac{\\pi h^3}{12}$. $\\frac{dV}{dt} = \\frac{\\pi h^2}{4}\\frac{dh}{dt}$. $2 = \\pi \\cdot \\frac{dh}{dt}$, $\\frac{dh}{dt} = \\frac{2}{\\pi}$.',
    difficulty: 'hard',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'The graph of $f$ has inflection points where:',
    options: ['$f\' = 0$', '$f\'\' = 0$ or $f\'\'$ is undefined, and $f\'\'$ changes sign', '$f\'\' > 0$', '$f\'$ changes sign'],
    correctAnswer: 1,
    explanation: 'An inflection point occurs where $f\'\'$ changes sign. $f\'\' = 0$ (or undefined) is necessary but not sufficient alone.',
    difficulty: 'easy',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = \\ln x$ on $[1, e^2]$, the value $c$ guaranteed by the MVT is:',
    options: ['$e$', '$\\dfrac{e^2 - 1}{2}$', '$e^2 - 1$', '$\\dfrac{2}{\\ln(e^2)}$'],
    correctAnswer: 1,
    explanation: '$f\'(c) = \\frac{f(e^2) - f(1)}{e^2 - 1} = \\frac{2}{e^2 - 1}$. Since $f\'(c) = 1/c$: $c = \\frac{e^2-1}{2}$.',
    difficulty: 'hard',
    domain: 'applications-derivatives',
    topicSlug: 'theorem-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'A stone is thrown upward from $s_0 = 0$ with $v_0 = 64$ ft/s. If $a = -32$ ft/s², the maximum height is:',
    options: ['$32$ ft', '$64$ ft', '$128$ ft', '$96$ ft'],
    correctAnswer: 1,
    explanation: '$v(t) = 64 - 32t = 0 \\Rightarrow t = 2$. $s(2) = 64(2) - 16(4) = 128 - 64 = 64$ ft.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'particle-motion-calcab',
    formSet: 'both',
  },
  {
    question: 'The function $f(x) = x^4 - 8x^2$ has how many inflection points?',
    options: ['$0$', '$1$', '$2$', '$3$'],
    correctAnswer: 2,
    explanation: '$f\'\'(x) = 12x^2 - 16 = 0 \\Rightarrow x = \\pm \\frac{2}{\\sqrt{3}}$. $f\'\'$ changes sign at both. Two inflection points.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'If a differentiable function has exactly one critical point that is a local minimum, and $\\lim_{x \\to \\pm\\infty} f(x) = \\infty$, then the local minimum is also:',
    options: ['A point of inflection', 'The absolute minimum', 'Neither a max nor min', 'An absolute maximum'],
    correctAnswer: 1,
    explanation: 'With only one critical point (local min) and $f \\to \\infty$ at both ends, the local minimum must be the absolute minimum.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'The linear approximation of $f(x) = \\cos x$ near $x = 0$ is:',
    options: ['$L(x) = 1$', '$L(x) = 1 - x$', '$L(x) = 1 - \\dfrac{x^2}{2}$', '$L(x) = x$'],
    correctAnswer: 0,
    explanation: '$f(0) = 1$, $f\'(0) = -\\sin 0 = 0$. $L(x) = 1 + 0 \\cdot x = 1$.',
    difficulty: 'easy',
    domain: 'applications-derivatives',
    topicSlug: 'linearization-differentials-calcab',
    formSet: 'both',
  },
  {
    question: 'Oil spills in a circle. If the area increases at $6\\pi$ m²/min, how fast is the radius increasing when $r = 3$ m?',
    options: ['$1$ m/min', '$2$ m/min', '$3$ m/min', '$\\dfrac{1}{3}$ m/min'],
    correctAnswer: 0,
    explanation: '$A = \\pi r^2$. $\\frac{dA}{dt} = 2\\pi r \\frac{dr}{dt}$. $6\\pi = 2\\pi(3)\\frac{dr}{dt}$. $\\frac{dr}{dt} = 1$ m/min.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'On which interval is the graph of $f(x) = \\dfrac{x}{x^2 + 1}$ concave down?',
    options: ['$(-\\infty, 0)$', '$(0, \\infty)$', '$(-\\sqrt{3}, 0) \\cup (\\sqrt{3}, \\infty)$', '$(-\\infty, -\\sqrt{3}) \\cup (0, \\sqrt{3})$'],
    correctAnswer: 2,
    explanation: 'After computing $f\'\'$, the sign analysis shows $f\'\' < 0$ on $(-\\sqrt{3}, 0) \\cup (\\sqrt{3}, \\infty)$.',
    difficulty: 'hard',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'A farmer has 120 m of fencing. What is the maximum area of a rectangular pen built against a barn (fence on 3 sides)?',
    options: ['$900$ m²', '$1800$ m²', '$3600$ m²', '$1200$ m²'],
    correctAnswer: 1,
    explanation: '$2x + y = 120$, $A = xy = x(120 - 2x)$. $A\' = 120 - 4x = 0 \\Rightarrow x = 30$. $A = 30(60) = 1800$.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'optimization-calcab',
    formSet: 'both',
  },
  {
    question: 'The particle with position $s(t) = t^2 - 6t + 5$ is at rest at $t = $',
    options: ['$1$', '$3$', '$5$', '$-3$'],
    correctAnswer: 1,
    explanation: '$v(t) = 2t - 6 = 0 \\Rightarrow t = 3$.',
    difficulty: 'easy',
    domain: 'applications-derivatives',
    topicSlug: 'particle-motion-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = 2x^3 - 9x^2 + 12x + 1$, the local minimum value is:',
    options: ['$1$', '$5$', '$6$', '$-1$'],
    correctAnswer: 2,
    explanation: '$f\'(x) = 6x^2 - 18x + 12 = 6(x-1)(x-2) = 0$ at $x = 1, 2$. $f\'\'(1) = -6 < 0$ (max), $f\'\'(2) = 6 > 0$ (min). $f(2) = 16 - 36 + 24 + 1 = 5$. Wait: $f(2)= 16-36+24+1=5$.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f\'\'(x) > 0$ on an interval $[a,b]$ and a tangent line is drawn at any point in $(a,b)$, the tangent line lies:',
    options: ['Above the curve', 'Below the curve', 'On the curve', 'Cannot be determined'],
    correctAnswer: 1,
    explanation: 'When $f\'\' > 0$ (concave up), the curve bends upward from any tangent line, so the tangent lies below the curve.',
    difficulty: 'easy',
    domain: 'applications-derivatives',
    topicSlug: 'applications-of-derivatives-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f$ is continuous on $[a,b]$, $f(a) > 0$, and $f(b) > 0$, can we conclude there is no $c \\in (a,b)$ with $f(c) = 0$?',
    options: ['Yes, by the IVT', 'No — $f$ might dip below zero and return', 'Yes, because $f > 0$ at endpoints', 'Only if $f$ is differentiable'],
    correctAnswer: 1,
    explanation: 'IVT says that between two values, all intermediate values are hit — but $f$ could go below $0$ between $a$ and $b$ and return.',
    difficulty: 'medium',
    domain: 'applications-derivatives',
    topicSlug: 'theorem-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'The total distance traveled by a particle with $v(t) = \\cos t$ on $[0, \\pi]$ is:',
    options: ['$0$', '$1$', '$2$', '$\\pi$'],
    correctAnswer: 2,
    explanation: '$v = 0$ at $t = \\pi/2$. Distance $= \\int_0^{\\pi/2} \\cos t\\,dt + \\int_{\\pi/2}^{\\pi} |\\cos t|\\,dt = 1 + 1 = 2$.',
    difficulty: 'hard',
    domain: 'applications-derivatives',
    topicSlug: 'particle-motion-calcab',
    formSet: 'both',
  },
"""

filepath = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    'src', 'data', 'exit-quizzes', 'ap-calculus-ab.ts'
)

with open(filepath, 'r') as f:
    content = f.read()

# Fix the local min value question
NEW_QUESTIONS = NEW_QUESTIONS.replace(
    "$f\'\'(2) = 6 > 0$ (min). $f(2) = 16 - 36 + 24 + 1 = 5$. Wait: $f(2)= 16-36+24+1=5$.',",
    "$f\'\'(2) = 6 > 0$ (min). $f(2) = 16 - 36 + 24 + 1 = 5$.',",
)
# Fix answer index: f(2) = 5, which is option index 1
NEW_QUESTIONS = NEW_QUESTIONS.replace(
    "question: 'If $f(x) = 2x^3 - 9x^2 + 12x + 1$, the local minimum value is:',\n    options: ['$1$', '$5$', '$6$', '$-1$'],\n    correctAnswer: 2,",
    "question: 'If $f(x) = 2x^3 - 9x^2 + 12x + 1$, the local minimum value is:',\n    options: ['$1$', '$5$', '$6$', '$-1$'],\n    correctAnswer: 1,",
)

marker = "\n]\n\n/** Generate an exit quiz"
if marker in content:
    content = content.replace(marker, NEW_QUESTIONS + marker)
    with open(filepath, 'w') as f:
        f.write(content)
    print("SUCCESS: Batch 2 added")
else:
    print("ERROR: marker not found")
