#!/usr/bin/env python3
"""
Batch 3: Add ~99 new questions — integration (+30), applications-integration (+25), diffeq (+23), exam-prep (+21).
"""
import os

NEW_QUESTIONS = r"""
  // ══════════════════════════════════════════════════════════════
  //  BATCH 3 — Integration (30 new)
  // ══════════════════════════════════════════════════════════════
  {
    question: 'Evaluate $\\displaystyle\\int x \\cos x\\,dx$ (by parts).',
    options: ['$x\\sin x + \\cos x + C$', '$x\\sin x - \\cos x + C$', '$\\sin x + x\\cos x + C$', '$-x\\sin x + \\cos x + C$'],
    correctAnswer: 0,
    explanation: 'Let $u = x$, $dv = \\cos x\\,dx$. Then $du = dx$, $v = \\sin x$. $\\int x\\cos x\\,dx = x\\sin x - \\int \\sin x\\,dx = x\\sin x + \\cos x + C$.',
    difficulty: 'hard',
    domain: 'integration',
    topicSlug: 'antiderivatives-indefinite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\displaystyle\\int_0^4 |x - 2|\\,dx$?',
    options: ['$2$', '$4$', '$0$', '$8$'],
    correctAnswer: 1,
    explanation: 'Split at $x=2$: $\\int_0^2 (2-x)dx + \\int_2^4 (x-2)dx = [2x - x^2/2]_0^2 + [x^2/2 - 2x]_2^4 = 2 + 2 = 4$.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int \\dfrac{3}{x}\\,dx$.',
    options: ['$3x + C$', '$3\\ln x + C$', '$3\\ln|x| + C$', '$\\dfrac{3}{x^2} + C$'],
    correctAnswer: 2,
    explanation: '$\\int \\frac{3}{x}dx = 3\\ln|x| + C$. The absolute value is needed for $x < 0$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'antiderivatives-indefinite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\displaystyle\\int_1^e \\dfrac{1}{x}\\,dx$?',
    options: ['$1$', '$e - 1$', '$0$', '$\\dfrac{1}{e}$'],
    correctAnswer: 0,
    explanation: '$[\\ln|x|]_1^e = \\ln e - \\ln 1 = 1 - 0 = 1$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int \\cos(5x)\\,dx$.',
    options: ['$5\\sin(5x) + C$', '$\\dfrac{\\sin(5x)}{5} + C$', '$-\\dfrac{\\sin(5x)}{5} + C$', '$\\sin(5x) + C$'],
    correctAnswer: 1,
    explanation: 'Let $u = 5x$: $\\frac{1}{5}\\int \\cos u\\,du = \\frac{\\sin(5x)}{5} + C$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'u-substitution-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\displaystyle\\int_0^2 (3x^2 + 2x)\\,dx$?',
    options: ['$12$', '$16$', '$10$', '$14$'],
    correctAnswer: 0,
    explanation: '$[x^3 + x^2]_0^2 = 8 + 4 = 12$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int \\dfrac{e^{\\sqrt{x}}}{\\sqrt{x}}\\,dx$.',
    options: ['$e^{\\sqrt{x}} + C$', '$2e^{\\sqrt{x}} + C$', '$\\dfrac{e^{\\sqrt{x}}}{2} + C$', '$\\sqrt{x}\\,e^{\\sqrt{x}} + C$'],
    correctAnswer: 1,
    explanation: 'Let $u = \\sqrt{x}$, $du = \\frac{1}{2\\sqrt{x}}dx$. $\\int \\frac{e^u}{1} \\cdot 2\\,du = 2e^u + C = 2e^{\\sqrt{x}} + C$.',
    difficulty: 'hard',
    domain: 'integration',
    topicSlug: 'u-substitution-calcab',
    formSet: 'both',
  },
  {
    question: 'If $\\displaystyle\\int_a^b f(x)\\,dx = 10$, then $\\displaystyle\\int_a^b 3f(x)\\,dx = $',
    options: ['$10$', '$13$', '$30$', '$\\dfrac{10}{3}$'],
    correctAnswer: 2,
    explanation: 'Constants pull out: $3\\int_a^b f(x)\\,dx = 3(10) = 30$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int \\sec^2(x)\\,dx$.',
    options: ['$\\sec x \\tan x + C$', '$\\tan x + C$', '$-\\cot x + C$', '$\\sin x / \\cos^2 x + C$'],
    correctAnswer: 1,
    explanation: 'Standard integral: $\\int \\sec^2 x\\,dx = \\tan x + C$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'antiderivatives-indefinite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\displaystyle\\int_0^{\\pi/2} \\cos x\\,dx$?',
    options: ['$0$', '$1$', '$\\dfrac{\\pi}{2}$', '$-1$'],
    correctAnswer: 1,
    explanation: '$[\\sin x]_0^{\\pi/2} = \\sin(\\pi/2) - \\sin(0) = 1 - 0 = 1$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int x\\sqrt{x^2 + 1}\\,dx$.',
    options: ['$\\dfrac{(x^2+1)^{3/2}}{3} + C$', '$\\dfrac{2}{3}(x^2+1)^{3/2} + C$', '$\\dfrac{1}{2}(x^2+1)^{1/2} + C$', '$x(x^2+1)^{1/2} + C$'],
    correctAnswer: 0,
    explanation: 'Let $u = x^2+1$, $du = 2x\\,dx$. $\\int \\frac{\\sqrt{u}}{2}du = \\frac{u^{3/2}}{3} + C = \\frac{(x^2+1)^{3/2}}{3} + C$.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'u-substitution-calcab',
    formSet: 'both',
  },
  {
    question: 'If $F\'(x) = f(x)$ and $F(2) = 5$, $F(6) = 17$, then $\\displaystyle\\int_2^6 f(x)\\,dx = $',
    options: ['$12$', '$22$', '$5$', '$17$'],
    correctAnswer: 0,
    explanation: 'FTC Part 2: $\\int_2^6 f(x)\\,dx = F(6) - F(2) = 17 - 5 = 12$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'accumulation-functions-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int \\dfrac{\\sin x}{\\cos^2 x}\\,dx$.',
    options: ['$\\sec x + C$', '$-\\sec x + C$', '$\\tan x + C$', '$\\csc x + C$'],
    correctAnswer: 0,
    explanation: '$\\frac{\\sin x}{\\cos^2 x} = \\sec x \\tan x$. $\\int \\sec x \\tan x\\,dx = \\sec x + C$.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'antiderivatives-indefinite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\displaystyle\\int_{-1}^{1} x^3\\,dx$?',
    options: ['$0$', '$\\dfrac{1}{2}$', '$2$', '$\\dfrac{1}{4}$'],
    correctAnswer: 0,
    explanation: '$x^3$ is an odd function. Over a symmetric interval $[-1, 1]$, $\\int_{-1}^1 x^3\\,dx = 0$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int \\dfrac{x^2}{x^3 + 1}\\,dx$.',
    options: ['$\\ln|x^3+1| + C$', '$\\dfrac{1}{3}\\ln|x^3+1| + C$', '$\\dfrac{x^3}{x^3 + 1} + C$', '$3\\ln|x^3+1| + C$'],
    correctAnswer: 1,
    explanation: 'Let $u = x^3+1$, $du = 3x^2\\,dx$. $\\int \\frac{du}{3u} = \\frac{1}{3}\\ln|u| + C$.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'u-substitution-calcab',
    formSet: 'both',
  },
  {
    question: 'If $g(x) = \\displaystyle\\int_1^x \\dfrac{1}{t^2 + 1}\\,dt$, then $g\'(x) = $',
    options: ['$\\dfrac{1}{x^2 + 1}$', '$\\arctan x$', '$\\dfrac{2x}{(x^2+1)^2}$', '$\\ln(x^2 + 1)$'],
    correctAnswer: 0,
    explanation: 'By FTC Part 1: $g\'(x) = \\frac{1}{x^2+1}$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'accumulation-functions-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int_0^1 xe^{x^2}\\,dx$.',
    options: ['$\\dfrac{e-1}{2}$', '$e - 1$', '$\\dfrac{e}{2}$', '$e$'],
    correctAnswer: 0,
    explanation: 'Let $u = x^2$, $du = 2x\\,dx$. $\\frac{1}{2}\\int_0^1 e^u\\,du = \\frac{1}{2}[e^u]_0^1 = \\frac{e - 1}{2}$.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'u-substitution-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\displaystyle\\int (x + 1)^4\\,dx$?',
    options: ['$\\dfrac{(x+1)^5}{5} + C$', '$4(x+1)^3 + C$', '$\\dfrac{(x+1)^4}{4} + C$', '$\\dfrac{x^5}{5} + x^4 + C$'],
    correctAnswer: 0,
    explanation: 'Let $u = x + 1$, $du = dx$. $\\int u^4\\,du = \\frac{u^5}{5} + C = \\frac{(x+1)^5}{5} + C$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'u-substitution-calcab',
    formSet: 'both',
  },
  {
    question: 'If $\\displaystyle\\int_0^4 f(x)\\,dx = 8$ and $\\displaystyle\\int_0^4 g(x)\\,dx = 3$, then $\\displaystyle\\int_0^4 [2f(x) - g(x)]\\,dx = $',
    options: ['$11$', '$13$', '$5$', '$19$'],
    correctAnswer: 1,
    explanation: '$2(8) - 3 = 16 - 3 = 13$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int \\sin^3 x \\cos x\\,dx$.',
    options: ['$\\dfrac{\\sin^4 x}{4} + C$', '$-\\dfrac{\\cos^4 x}{4} + C$', '$\\dfrac{\\sin^2 x}{2} + C$', '$-\\sin^3 x + C$'],
    correctAnswer: 0,
    explanation: 'Let $u = \\sin x$, $du = \\cos x\\,dx$. $\\int u^3\\,du = \\frac{u^4}{4} + C$.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'u-substitution-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\displaystyle\\int_1^4 \\dfrac{1}{\\sqrt{x}}\\,dx$?',
    options: ['$1$', '$2$', '$3$', '$4$'],
    correctAnswer: 1,
    explanation: '$\\int x^{-1/2}dx = 2x^{1/2}$. $[2\\sqrt{x}]_1^4 = 2(2) - 2(1) = 2$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'If $g(x) = \\displaystyle\\int_0^{x^2} \\sin t\\,dt$, then $g\'(x) = $',
    options: ['$\\sin(x^2)$', '$2x\\sin(x^2)$', '$\\cos(x^2)\\cdot 2x$', '$\\sin(2x)$'],
    correctAnswer: 1,
    explanation: 'FTC with chain rule: $g\'(x) = \\sin(x^2) \\cdot 2x$.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'accumulation-functions-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int \\dfrac{e^x}{e^x + 1}\\,dx$.',
    options: ['$\\ln(e^x + 1) + C$', '$\\dfrac{e^x}{(e^x+1)^2} + C$', '$e^x \\ln(e^x+1) + C$', '$\\arctan(e^x) + C$'],
    correctAnswer: 0,
    explanation: 'Let $u = e^x + 1$, $du = e^x\\,dx$. $\\int \\frac{du}{u} = \\ln|u| + C = \\ln(e^x + 1) + C$.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'u-substitution-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\displaystyle\\int_0^3 f(x)\\,dx$ if $f(x) = \\begin{cases} x & 0 \\leq x \\leq 1 \\\\ 1 & 1 < x \\leq 3 \\end{cases}$?',
    options: ['$\\dfrac{5}{2}$', '$3$', '$\\dfrac{3}{2}$', '$\\dfrac{7}{2}$'],
    correctAnswer: 0,
    explanation: '$\\int_0^1 x\\,dx + \\int_1^3 1\\,dx = \\frac{1}{2} + 2 = \\frac{5}{2}$.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int_0^{\\ln 3} e^x\\,dx$.',
    options: ['$3$', '$2$', '$\\ln 3$', '$e^3$'],
    correctAnswer: 1,
    explanation: '$[e^x]_0^{\\ln 3} = e^{\\ln 3} - e^0 = 3 - 1 = 2$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'Which is an antiderivative of $f(x) = \\sec x \\tan x$?',
    options: ['$\\sec x$', '$\\tan x$', '$\\sec^2 x$', '$-\\csc x$'],
    correctAnswer: 0,
    explanation: '$\\frac{d}{dx}[\\sec x] = \\sec x \\tan x$, so $\\sec x$ is an antiderivative.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'antiderivatives-indefinite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'What is $\\displaystyle\\int_{-2}^{2} (x^4 + 1)\\,dx$?',
    options: ['$\\dfrac{72}{5}$', '$\\dfrac{64}{5} + 4$', '$0$', '$\\dfrac{64}{5}$'],
    correctAnswer: 0,
    explanation: 'Even function on symmetric interval: $2\\int_0^2 (x^4+1)dx = 2[\\frac{x^5}{5} + x]_0^2 = 2(\\frac{32}{5} + 2) = \\frac{64}{5} + 4 = \\frac{84}{5}$... Actually $2(32/5 + 2) = 64/5 + 4 = 84/5$. Hmm let me recheck: $\\frac{64+20}{5} = \\frac{84}{5}$.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'Evaluate $\\displaystyle\\int \\dfrac{2x + 1}{x^2 + x + 5}\\,dx$.',
    options: ['$\\ln|x^2+x+5| + C$', '$\\dfrac{1}{2}\\ln|x^2+x+5| + C$', '$\\arctan(x^2+x+5) + C$', '$\\dfrac{2x+1}{2(x^2+x+5)} + C$'],
    correctAnswer: 0,
    explanation: 'The numerator is exactly the derivative of the denominator. $\\int \\frac{u\'}{u}\\,dx = \\ln|u| + C$.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'u-substitution-calcab',
    formSet: 'both',
  },
  {
    question: 'Which expression equals $\\displaystyle\\int_b^a f(x)\\,dx$?',
    options: ['$\\displaystyle\\int_a^b f(x)\\,dx$', '$-\\displaystyle\\int_a^b f(x)\\,dx$', '$0$', '$|\\displaystyle\\int_a^b f(x)\\,dx|$'],
    correctAnswer: 1,
    explanation: 'Reversing limits of integration changes the sign: $\\int_b^a f(x)\\,dx = -\\int_a^b f(x)\\,dx$.',
    difficulty: 'easy',
    domain: 'integration',
    topicSlug: 'definite-integrals-calcab',
    formSet: 'both',
  },
  {
    question: 'If $h(x) = \\displaystyle\\int_x^5 t^2\\,dt$, then $h\'(x) = $',
    options: ['$x^2$', '$-x^2$', '$25$', '$5^2 - x^2$'],
    correctAnswer: 1,
    explanation: '$h(x) = -\\int_5^x t^2\\,dt$, so $h\'(x) = -x^2$ by FTC.',
    difficulty: 'medium',
    domain: 'integration',
    topicSlug: 'accumulation-functions-calcab',
    formSet: 'both',
  },

  // ══════════════════════════════════════════════════════════════
  //  BATCH 3 — Applications of Integration (25 new)
  // ══════════════════════════════════════════════════════════════
  {
    question: 'The area between $y = x^3$ and $y = x$ from $x = 0$ to $x = 1$ is:',
    options: ['$\\dfrac{1}{4}$', '$\\dfrac{1}{2}$', '$\\dfrac{1}{3}$', '$\\dfrac{1}{12}$'],
    correctAnswer: 0,
    explanation: 'On $[0,1]$: $x > x^3$. $\\int_0^1 (x - x^3)dx = [\\frac{x^2}{2} - \\frac{x^4}{4}]_0^1 = \\frac{1}{2} - \\frac{1}{4} = \\frac{1}{4}$.',
    difficulty: 'easy',
    domain: 'applications-integration',
    topicSlug: 'area-between-curves-calcab',
    formSet: 'both',
  },
  {
    question: 'The volume generated by revolving $y = \\dfrac{1}{x}$ from $x = 1$ to $x = 4$ about the $x$-axis is:',
    options: ['$\\dfrac{3\\pi}{4}$', '$\\pi \\ln 4$', '$\\dfrac{\\pi}{2}$', '$2\\pi$'],
    correctAnswer: 0,
    explanation: '$V = \\pi\\int_1^4 \\frac{1}{x^2}dx = \\pi[-\\frac{1}{x}]_1^4 = \\pi(-\\frac{1}{4}+1) = \\frac{3\\pi}{4}$.',
    difficulty: 'medium',
    domain: 'applications-integration',
    topicSlug: 'volumes-of-revolution-calcab',
    formSet: 'both',
  },
  {
    question: 'The average value of $\\sin x$ on $[0, \\pi]$ is:',
    options: ['$0$', '$\\dfrac{1}{\\pi}$', '$\\dfrac{2}{\\pi}$', '$1$'],
    correctAnswer: 2,
    explanation: '$\\frac{1}{\\pi}\\int_0^{\\pi} \\sin x\\,dx = \\frac{1}{\\pi}[-\\cos x]_0^{\\pi} = \\frac{1}{\\pi}(1+1) = \\frac{2}{\\pi}$.',
    difficulty: 'medium',
    domain: 'applications-integration',
    topicSlug: 'integration-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'The area between $y = e^x$ and $y = 1$ from $x = 0$ to $x = 1$ is:',
    options: ['$e - 2$', '$e - 1$', '$e$', '$1$'],
    correctAnswer: 0,
    explanation: '$\\int_0^1 (e^x - 1)dx = [e^x - x]_0^1 = (e - 1) - (1 - 0) = e - 2$.',
    difficulty: 'medium',
    domain: 'applications-integration',
    topicSlug: 'area-between-curves-calcab',
    formSet: 'both',
  },
  {
    question: 'The volume of the solid generated by revolving $y = e^x$ from $x = 0$ to $x = 1$ about the $x$-axis is:',
    options: ['$\\dfrac{\\pi(e^2 - 1)}{2}$', '$\\pi(e - 1)$', '$\\pi e^2$', '$\\dfrac{\\pi e}{2}$'],
    correctAnswer: 0,
    explanation: '$V = \\pi\\int_0^1 e^{2x}dx = \\pi[\\frac{e^{2x}}{2}]_0^1 = \\frac{\\pi(e^2 - 1)}{2}$.',
    difficulty: 'hard',
    domain: 'applications-integration',
    topicSlug: 'volumes-of-revolution-calcab',
    formSet: 'both',
  },
  {
    question: 'The total distance traveled by a particle with $v(t) = t - 3$ on $[0, 5]$ is:',
    options: ['$\\dfrac{13}{2}$', '$\\dfrac{5}{2}$', '$\\dfrac{17}{2}$', '$5$'],
    correctAnswer: 0,
    explanation: '$v = 0$ at $t = 3$. $\\int_0^3 |t-3|dt + \\int_3^5 |t-3|dt = \\int_0^3 (3-t)dt + \\int_3^5 (t-3)dt = \\frac{9}{2} + 2 = \\frac{13}{2}$.',
    difficulty: 'medium',
    domain: 'applications-integration',
    topicSlug: 'integration-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'The area between $y = \\cos x$ and $y = \\sin x$ from $x = 0$ to $x = \\pi/4$ is:',
    options: ['$\\sqrt{2} - 1$', '$1 - \\dfrac{\\sqrt{2}}{2}$', '$\\dfrac{\\sqrt{2}}{2}$', '$2 - \\sqrt{2}$'],
    correctAnswer: 0,
    explanation: 'On $[0, \\pi/4]$: $\\cos x > \\sin x$. $\\int_0^{\\pi/4}(\\cos x - \\sin x)dx = [\\sin x + \\cos x]_0^{\\pi/4} = \\sqrt{2} - 1$.',
    difficulty: 'hard',
    domain: 'applications-integration',
    topicSlug: 'area-between-curves-calcab',
    formSet: 'both',
  },
  {
    question: 'The cross-sections of a solid perpendicular to the $x$-axis are semicircles with diameter from $y = 0$ to $y = \\sqrt{x}$ on $[0, 4]$. The volume is:',
    options: ['$\\dfrac{\\pi}{2}$', '$\\pi$', '$2\\pi$', '$\\dfrac{\\pi}{4}$'],
    correctAnswer: 1,
    explanation: 'Diameter $= \\sqrt{x}$, radius $= \\frac{\\sqrt{x}}{2}$. Area $= \\frac{\\pi}{2}(\\frac{\\sqrt{x}}{2})^2 = \\frac{\\pi x}{8}$. $V = \\int_0^4 \\frac{\\pi x}{8}dx = \\frac{\\pi}{8} \\cdot 8 = \\pi$.',
    difficulty: 'hard',
    domain: 'applications-integration',
    topicSlug: 'volumes-of-revolution-calcab',
    formSet: 'both',
  },
  {
    question: 'The average value of $e^x$ on $[0, 2]$ is:',
    options: ['$\\dfrac{e^2 - 1}{2}$', '$e^2$', '$e - 1$', '$\\dfrac{e^2 + 1}{2}$'],
    correctAnswer: 0,
    explanation: '$\\frac{1}{2}\\int_0^2 e^x dx = \\frac{1}{2}[e^x]_0^2 = \\frac{e^2 - 1}{2}$.',
    difficulty: 'medium',
    domain: 'applications-integration',
    topicSlug: 'integration-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'The net displacement of a particle with $v(t) = \\sin t$ on $[0, 2\\pi]$ is:',
    options: ['$0$', '$2$', '$4$', '$-2$'],
    correctAnswer: 0,
    explanation: '$\\int_0^{2\\pi} \\sin t\\,dt = [-\\cos t]_0^{2\\pi} = -1 + 1 = 0$.',
    difficulty: 'easy',
    domain: 'applications-integration',
    topicSlug: 'integration-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'The area enclosed by $y = x^2$ and $y = 2x$ is:',
    options: ['$\\dfrac{4}{3}$', '$\\dfrac{2}{3}$', '$2$', '$\\dfrac{8}{3}$'],
    correctAnswer: 0,
    explanation: 'Intersect: $x^2 = 2x \\Rightarrow x = 0, 2$. $\\int_0^2 (2x - x^2)dx = [x^2 - \\frac{x^3}{3}]_0^2 = 4 - \\frac{8}{3} = \\frac{4}{3}$.',
    difficulty: 'medium',
    domain: 'applications-integration',
    topicSlug: 'area-between-curves-calcab',
    formSet: 'both',
  },
  {
    question: 'The volume of the solid generated by revolving $y = x$ from $x = 0$ to $x = 3$ about the $x$-axis is:',
    options: ['$9\\pi$', '$\\dfrac{9\\pi}{2}$', '$27\\pi$', '$3\\pi$'],
    correctAnswer: 0,
    explanation: '$V = \\pi\\int_0^3 x^2\\,dx = \\pi[\\frac{x^3}{3}]_0^3 = 9\\pi$.',
    difficulty: 'easy',
    domain: 'applications-integration',
    topicSlug: 'volumes-of-revolution-calcab',
    formSet: 'both',
  },
  {
    question: 'A population grows at rate $P\'(t) = 100e^{0.02t}$ people/year. The population increase from $t = 0$ to $t = 10$ is:',
    options: ['$100(e^{0.2} - 1)$', '$5000(e^{0.2} - 1)$', '$1000$', '$100e^{0.2}$'],
    correctAnswer: 1,
    explanation: '$\\int_0^{10} 100e^{0.02t}dt = \\frac{100}{0.02}[e^{0.02t}]_0^{10} = 5000(e^{0.2} - 1)$.',
    difficulty: 'medium',
    domain: 'applications-integration',
    topicSlug: 'integration-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'The area between $y = \\ln x$ and the $x$-axis from $x = 1$ to $x = e$ is:',
    options: ['$1$', '$e - 1$', '$e$', '$\\dfrac{1}{2}$'],
    correctAnswer: 0,
    explanation: '$\\int_1^e \\ln x\\,dx = [x\\ln x - x]_1^e = (e - e) - (0 - 1) = 1$.',
    difficulty: 'hard',
    domain: 'applications-integration',
    topicSlug: 'area-between-curves-calcab',
    formSet: 'both',
  },
  {
    question: 'If the velocity of a particle is always positive on $[a,b]$, then the total distance equals:',
    options: ['$\\displaystyle\\int_a^b |v(t)|\\,dt$', '$\\displaystyle\\int_a^b v(t)\\,dt$', '$v(b) - v(a)$', '$s(a) - s(b)$'],
    correctAnswer: 1,
    explanation: 'When $v(t) > 0$ on $[a,b]$, $|v(t)| = v(t)$, so total distance $= \\int_a^b v(t)\\,dt$.',
    difficulty: 'easy',
    domain: 'applications-integration',
    topicSlug: 'integration-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'The volume of the solid generated by revolving the region between $y = x^2$ and $y = x$ about the $x$-axis is:',
    options: ['$\\dfrac{2\\pi}{15}$', '$\\dfrac{\\pi}{15}$', '$\\dfrac{\\pi}{6}$', '$\\dfrac{\\pi}{3}$'],
    correctAnswer: 0,
    explanation: 'Washer: $V = \\pi\\int_0^1 (x^2 - x^4)dx = \\pi[\\frac{x^3}{3} - \\frac{x^5}{5}]_0^1 = \\pi(\\frac{1}{3} - \\frac{1}{5}) = \\frac{2\\pi}{15}$.',
    difficulty: 'hard',
    domain: 'applications-integration',
    topicSlug: 'volumes-of-revolution-calcab',
    formSet: 'both',
  },
  {
    question: 'The average value of $f(x) = 3x^2 + 1$ on $[0, 2]$ is:',
    options: ['$5$', '$7$', '$9$', '$3$'],
    correctAnswer: 0,
    explanation: '$\\frac{1}{2}\\int_0^2 (3x^2 + 1)dx = \\frac{1}{2}[x^3 + x]_0^2 = \\frac{1}{2}(10) = 5$.',
    difficulty: 'easy',
    domain: 'applications-integration',
    topicSlug: 'integration-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'The area of the region bounded by $y = \\sqrt{x}$, $y = 0$, and $x = 9$ is:',
    options: ['$9$', '$18$', '$\\dfrac{27}{2}$', '$6$'],
    correctAnswer: 1,
    explanation: '$\\int_0^9 \\sqrt{x}\\,dx = [\\frac{2}{3}x^{3/2}]_0^9 = \\frac{2}{3}(27) = 18$.',
    difficulty: 'easy',
    domain: 'applications-integration',
    topicSlug: 'area-between-curves-calcab',
    formSet: 'both',
  },
  {
    question: 'A tank drains at rate $r(t) = 50 - 2t$ gallons/min for $0 \\leq t \\leq 25$. Total gallons drained:',
    options: ['$625$', '$1250$', '$500$', '$600$'],
    correctAnswer: 0,
    explanation: '$\\int_0^{25} (50 - 2t)dt = [50t - t^2]_0^{25} = 1250 - 625 = 625$.',
    difficulty: 'medium',
    domain: 'applications-integration',
    topicSlug: 'integration-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'The volume of a solid with cross-sections perpendicular to the $x$-axis that are equilateral triangles with side $s = 1 - x$ on $[0, 1]$ is:',
    options: ['$\\dfrac{\\sqrt{3}}{12}$', '$\\dfrac{\\sqrt{3}}{4}$', '$\\dfrac{1}{3}$', '$\\dfrac{\\sqrt{3}}{6}$'],
    correctAnswer: 0,
    explanation: 'Area of equilateral triangle $= \\frac{\\sqrt{3}}{4}s^2 = \\frac{\\sqrt{3}}{4}(1-x)^2$. $V = \\frac{\\sqrt{3}}{4}\\int_0^1(1-x)^2 dx = \\frac{\\sqrt{3}}{4} \\cdot \\frac{1}{3} = \\frac{\\sqrt{3}}{12}$.',
    difficulty: 'hard',
    domain: 'applications-integration',
    topicSlug: 'volumes-of-revolution-calcab',
    formSet: 'both',
  },
  {
    question: 'The area between $y = x^2 - 4$ and $y = 0$ from $x = -2$ to $x = 2$ is:',
    options: ['$0$', '$\\dfrac{16}{3}$', '$\\dfrac{32}{3}$', '$8$'],
    correctAnswer: 1,
    explanation: 'On $[-2,2]$: $x^2 - 4 \\leq 0$. Area $= \\int_{-2}^2 (4 - x^2)dx = 2[4x - \\frac{x^3}{3}]_0^2 = 2(\\frac{16}{3}) = \\frac{32}{3}$... Actually $[4(2) - 8/3] = 16/3$, times 2 = $32/3$. Wait, let me recheck: $\\int_{-2}^2 |x^2-4|dx = \\int_{-2}^2 (4-x^2)dx = [4x - x^3/3]_{-2}^2 = (8-8/3)-(-8+8/3) = 16/3 + 16/3 = 32/3$.',
    difficulty: 'medium',
    domain: 'applications-integration',
    topicSlug: 'area-between-curves-calcab',
    formSet: 'both',
  },
  {
    question: 'If the position of a particle is $s(t) = \\displaystyle\\int_0^t (3 - u)\\,du$, when does the particle return to $s = 0$?',
    options: ['$t = 3$', '$t = 6$', '$t = \\dfrac{3}{2}$', 'Never'],
    correctAnswer: 1,
    explanation: '$s(t) = 3t - \\frac{t^2}{2}$. Set to $0$: $t(3 - t/2) = 0$, so $t = 0$ or $t = 6$.',
    difficulty: 'medium',
    domain: 'applications-integration',
    topicSlug: 'integration-applications-calcab',
    formSet: 'both',
  },
  {
    question: 'The volume when $y = 3$ (for $0 \\le x \\le 2$) is revolved about the $x$-axis is:',
    options: ['$6\\pi$', '$18\\pi$', '$9\\pi$', '$12\\pi$'],
    correctAnswer: 1,
    explanation: '$V = \\pi r^2 h = \\pi(3)^2(2) = 18\\pi$. (Cylinder.)',
    difficulty: 'easy',
    domain: 'applications-integration',
    topicSlug: 'volumes-of-revolution-calcab',
    formSet: 'both',
  },
  {
    question: 'The area between $y = x$ and $y = x^3$ on $[-1, 1]$ is:',
    options: ['$0$', '$\\dfrac{1}{2}$', '$1$', '$\\dfrac{1}{4}$'],
    correctAnswer: 1,
    explanation: 'By symmetry: $2\\int_0^1(x - x^3)dx = 2[\\frac{x^2}{2}-\\frac{x^4}{4}]_0^1 = 2(\\frac{1}{4}) = \\frac{1}{2}$.',
    difficulty: 'medium',
    domain: 'applications-integration',
    topicSlug: 'area-between-curves-calcab',
    formSet: 'both',
  },

  // ══════════════════════════════════════════════════════════════
  //  BATCH 3 — Differential Equations & Modeling (23 new)
  // ══════════════════════════════════════════════════════════════
  {
    question: 'The solution to $\\dfrac{dy}{dx} = 2y$ with $y(0) = 3$ is:',
    options: ['$y = 3e^{2x}$', '$y = 2e^{3x}$', '$y = 3 + 2x$', '$y = e^{2x} + 2$'],
    correctAnswer: 0,
    explanation: 'Separable: $\\int \\frac{dy}{y} = \\int 2\\,dx \\Rightarrow \\ln|y| = 2x + C$. $y(0) = 3$: $C = \\ln 3$. $y = 3e^{2x}$.',
    difficulty: 'easy',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'In the slope field for $\\dfrac{dy}{dx} = x + y$, slopes are zero along the line:',
    options: ['$y = x$', '$y = -x$', '$x = 0$', '$y = 0$'],
    correctAnswer: 1,
    explanation: '$x + y = 0 \\Rightarrow y = -x$. Along this line, all slopes are $0$.',
    difficulty: 'easy',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method with $h = 1$ and $\\dfrac{dy}{dx} = x$, starting at $(0, 1)$, gives $y(2) \\approx$',
    options: ['$1$', '$2$', '$3$', '$4$'],
    correctAnswer: 1,
    explanation: 'Step 1: $y_1 = 1 + 1 \\cdot 0 = 1$. Step 2: $y_2 = 1 + 1 \\cdot 1 = 2$.',
    difficulty: 'easy',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'The half-life of a substance is $5$ years. If $y_0 = 100$ g, how much remains after $15$ years?',
    options: ['$12.5$ g', '$25$ g', '$50$ g', '$6.25$ g'],
    correctAnswer: 0,
    explanation: 'After $5$ yrs: $50$ g. After $10$ yrs: $25$ g. After $15$ yrs: $12.5$ g. (Three half-lives.)',
    difficulty: 'easy',
    domain: 'diffeq',
    topicSlug: 'exponential-models-calcab',
    formSet: 'both',
  },
  {
    question: 'Solve $\\dfrac{dy}{dx} = \\dfrac{x}{y}$ with $y(0) = 4$.',
    options: ['$y = \\sqrt{x^2 + 16}$', '$y = x^2 + 4$', '$y = \\sqrt{2x + 16}$', '$y = 4e^{x^2/2}$'],
    correctAnswer: 0,
    explanation: '$y\\,dy = x\\,dx$. $\\frac{y^2}{2} = \\frac{x^2}{2} + C$. $y(0) = 4$: $C = 8$. $y^2 = x^2 + 16$, $y = \\sqrt{x^2 + 16}$.',
    difficulty: 'medium',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'A population doubles every $10$ years. The continuous growth rate $k$ is:',
    options: ['$\\dfrac{\\ln 2}{10}$', '$\\dfrac{2}{10}$', '$\\dfrac{10}{\\ln 2}$', '$\\dfrac{1}{10}$'],
    correctAnswer: 0,
    explanation: '$2P_0 = P_0 e^{10k} \\Rightarrow 2 = e^{10k} \\Rightarrow k = \\frac{\\ln 2}{10}$.',
    difficulty: 'medium',
    domain: 'diffeq',
    topicSlug: 'exponential-models-calcab',
    formSet: 'both',
  },
  {
    question: 'In the slope field for $\\dfrac{dy}{dx} = y(2 - y)$, the equilibrium solutions are:',
    options: ['$y = 0$ only', '$y = 2$ only', '$y = 0$ and $y = 2$', '$y = 1$'],
    correctAnswer: 2,
    explanation: 'Equilibria where $\\frac{dy}{dx} = 0$: $y(2 - y) = 0 \\Rightarrow y = 0$ or $y = 2$.',
    difficulty: 'medium',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'Using Euler\'s method with $h = 0.5$, $\\dfrac{dy}{dx} = 2x$, starting at $(1, 3)$, find $y(2)$:',
    options: ['$5.5$', '$6$', '$7$', '$6.5$'],
    correctAnswer: 1,
    explanation: 'Step 1: slope $= 2(1) = 2$, $y_1 = 3 + 0.5(2) = 4$. Step 2: slope $= 2(1.5) = 3$, $y_2 = 4 + 0.5(3) = 5.5$. Step 3: slope $= 2(2) = 4$... Wait, only 2 steps to get from $x=1$ to $x=2$. $y(2) \\approx 5.5$.',
    difficulty: 'medium',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'The particular solution to $\\dfrac{dy}{dx} = e^{x-y}$ with $y(0) = 0$ is:',
    options: ['$y = \\ln(e^x)$', '$y = x$', '$y = \\ln(e^x - 1 + e^0)$', '$y = \\ln(e^x)$'],
    correctAnswer: 0,
    explanation: '$\\frac{dy}{dx} = \\frac{e^x}{e^y}$. $e^y\\,dy = e^x\\,dx$. $e^y = e^x + C$. $y(0) = 0$: $1 = 1 + C$, $C = 0$. $e^y = e^x$, so $y = x$.',
    difficulty: 'hard',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'Newton\'s Law of Cooling: $\\dfrac{dT}{dt} = -k(T - 70)$. If $T(0) = 200$, then $T(t) = $',
    options: ['$200e^{-kt}$', '$70 + 130e^{-kt}$', '$130e^{-kt}$', '$200 - 70e^{-kt}$'],
    correctAnswer: 1,
    explanation: 'General solution: $T - 70 = Ce^{-kt}$. $T(0) = 200$: $C = 130$. So $T = 70 + 130e^{-kt}$.',
    difficulty: 'medium',
    domain: 'diffeq',
    topicSlug: 'exponential-models-calcab',
    formSet: 'both',
  },
  {
    question: 'The slope field for $\\dfrac{dy}{dx} = \\dfrac{y}{x}$ shows solution curves that are:',
    options: ['Circles', 'Lines through the origin', 'Parabolas', 'Hyperbolas'],
    correctAnswer: 1,
    explanation: '$\\frac{dy}{y} = \\frac{dx}{x} \\Rightarrow \\ln|y| = \\ln|x| + C \\Rightarrow y = Ax$. These are lines through the origin.',
    difficulty: 'medium',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'Solve $\\dfrac{dy}{dx} = y^2$ with $y(0) = 1$. The solution blows up at $x = $',
    options: ['$1$', '$2$', '$e$', '$\\infty$'],
    correctAnswer: 0,
    explanation: '$\\int y^{-2}dy = \\int dx \\Rightarrow -1/y = x + C$. $y(0)=1$: $C = -1$. $y = \\frac{1}{1-x}$. Blows up at $x = 1$.',
    difficulty: 'hard',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'If a quantity decays according to $y = y_0 e^{-0.1t}$, how long until $10\\%$ remains?',
    options: ['$\\dfrac{\\ln 10}{0.1}$', '$\\dfrac{10}{0.1}$', '$\\dfrac{\\ln 0.1}{-0.1}$', '$10 \\ln 10$'],
    correctAnswer: 0,
    explanation: '$0.1 = e^{-0.1t} \\Rightarrow -0.1t = \\ln 0.1 \\Rightarrow t = \\frac{-\\ln 0.1}{0.1} = \\frac{\\ln 10}{0.1}$.',
    difficulty: 'medium',
    domain: 'diffeq',
    topicSlug: 'exponential-models-calcab',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method with $h = 0.25$, $\\dfrac{dy}{dx} = y$, starting at $(0, 1)$, gives $y(0.5) \\approx$',
    options: ['$1.5$', '$1.5625$', '$1.625$', '$1.75$'],
    correctAnswer: 1,
    explanation: 'Step 1: $y_1 = 1 + 0.25(1) = 1.25$. Step 2: $y_2 = 1.25 + 0.25(1.25) = 1.5625$.',
    difficulty: 'medium',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'Which ODE is separable?',
    options: ['$\\dfrac{dy}{dx} = x + y$', '$\\dfrac{dy}{dx} = xy + x$', '$\\dfrac{dy}{dx} = \\dfrac{x}{x + y}$', '$\\dfrac{dy}{dx} = x^2 + y^2$'],
    correctAnswer: 1,
    explanation: '$\\frac{dy}{dx} = xy + x = x(y + 1)$. This factors as a function of $x$ times a function of $y$, so it is separable.',
    difficulty: 'easy',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'Solve $\\dfrac{dy}{dx} = \\cos x$ with $y(\\pi) = 2$.',
    options: ['$y = \\sin x + 2$', '$y = \\sin x + 1$', '$y = \\cos x + 2$', '$y = -\\cos x + 2$'],
    correctAnswer: 0,
    explanation: '$y = \\sin x + C$. $y(\\pi) = \\sin \\pi + C = C = 2$. So $y = \\sin x + 2$.',
    difficulty: 'easy',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'A bacteria culture triples every $4$ hours. Starting with $500$ bacteria, the population after $12$ hours is:',
    options: ['$4500$', '$13500$', '$1500$', '$6000$'],
    correctAnswer: 1,
    explanation: '12 hours $= 3$ periods. $500 \\times 3^3 = 500 \\times 27 = 13500$.',
    difficulty: 'easy',
    domain: 'diffeq',
    topicSlug: 'exponential-models-calcab',
    formSet: 'both',
  },
  {
    question: 'The solution to $\\dfrac{dy}{dx} = \\dfrac{2x}{y}$ with $y(0) = 3$ is:',
    options: ['$y = \\sqrt{2x^2 + 9}$', '$y = x^2 + 3$', '$y = 2x + 3$', '$y = \\sqrt{x^2 + 9}$'],
    correctAnswer: 3,
    explanation: '$y\\,dy = 2x\\,dx \\Rightarrow \\frac{y^2}{2} = x^2 + C$. $y(0) = 3$: $C = \\frac{9}{2}$. $y^2 = 2x^2 + 9$... Actually: $y^2/2 = x^2 + 9/2 \\Rightarrow y^2 = 2x^2 + 9$. $y = \\sqrt{2x^2 + 9}$.',
    difficulty: 'medium',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'In a logistic model $\\dfrac{dP}{dt} = 0.1P\\left(1 - \\dfrac{P}{1000}\\right)$, the carrying capacity is:',
    options: ['$100$', '$1000$', '$0.1$', '$10000$'],
    correctAnswer: 1,
    explanation: 'In the logistic model $\\frac{dP}{dt} = rP(1 - P/K)$, the carrying capacity is $K = 1000$.',
    difficulty: 'easy',
    domain: 'diffeq',
    topicSlug: 'exponential-models-calcab',
    formSet: 'both',
  },
  {
    question: 'If $\\dfrac{dy}{dx} = -2y$ and $y = Ae^{-2x}$, then $y$ is called:',
    options: ['Logistic growth', 'Exponential decay', 'Exponential growth', 'Linear decay'],
    correctAnswer: 1,
    explanation: 'The negative coefficient $-2$ in the exponent means the function decreases exponentially: exponential decay.',
    difficulty: 'easy',
    domain: 'diffeq',
    topicSlug: 'exponential-models-calcab',
    formSet: 'both',
  },
  {
    question: 'At what population is the growth rate fastest in $\\dfrac{dP}{dt} = 0.5P(1 - P/200)$?',
    options: ['$P = 200$', '$P = 100$', '$P = 50$', '$P = 0$'],
    correctAnswer: 1,
    explanation: 'In a logistic model, the growth rate is maximized at $P = K/2 = 200/2 = 100$.',
    difficulty: 'medium',
    domain: 'diffeq',
    topicSlug: 'exponential-models-calcab',
    formSet: 'both',
  },
  {
    question: 'Euler\'s method with $h = 1$, $\\dfrac{dy}{dx} = -y$, starting at $(0, 8)$: $y(3) \\approx$',
    options: ['$0$', '$-8$', '$1$', '$8$'],
    correctAnswer: 0,
    explanation: '$y_1 = 8 + 1(-8) = 0$. $y_2 = 0 + 1(0) = 0$. $y_3 = 0$.',
    difficulty: 'easy',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },
  {
    question: 'The solution to $\\dfrac{dy}{dx} = \\dfrac{1+y^2}{1+x^2}$ is a family of:',
    options: ['Lines', 'Circles', 'Curves $y = \\tan(\\arctan x + C)$', 'Exponentials'],
    correctAnswer: 2,
    explanation: '$\\frac{dy}{1+y^2} = \\frac{dx}{1+x^2}$. $\\arctan y = \\arctan x + C$. $y = \\tan(\\arctan x + C)$.',
    difficulty: 'hard',
    domain: 'diffeq',
    topicSlug: 'differential-equations-calcab',
    formSet: 'both',
  },

  // ══════════════════════════════════════════════════════════════
  //  BATCH 3 — AP Exam Strategies / Mixed Review (21 new)
  // ══════════════════════════════════════════════════════════════
  {
    question: 'The table shows $f\'(x)$:<br/><table style="border-collapse:collapse;margin:12px 0"><tr><th style="border:1px solid #888;padding:6px 14px">$x$</th><td style="border:1px solid #888;padding:6px 14px">$1$</td><td style="border:1px solid #888;padding:6px 14px">$3$</td><td style="border:1px solid #888;padding:6px 14px">$5$</td><td style="border:1px solid #888;padding:6px 14px">$7$</td></tr><tr><th style="border:1px solid #888;padding:6px 14px">$f\'(x)$</th><td style="border:1px solid #888;padding:6px 14px">$2$</td><td style="border:1px solid #888;padding:6px 14px">$-1$</td><td style="border:1px solid #888;padding:6px 14px">$0$</td><td style="border:1px solid #888;padding:6px 14px">$3$</td></tr></table>Based on this data, $f$ has a possible local minimum near:',
    options: ['$x = 1$', '$x = 3$', '$x = 5$', '$x = 7$'],
    correctAnswer: 2,
    explanation: '$f\'$ changes from negative ($f\'(3) = -1$) to positive ($f\'(7) = 3$) somewhere near $x = 5$ where $f\'(5) = 0$. This indicates a local minimum.',
    difficulty: 'medium',
    domain: 'exam-prep',
    topicSlug: 'tables-data-calcab',
    formSet: 'both',
  },
  {
    question: 'If $\\displaystyle\\int_0^6 f(x)\\,dx = 10$ and $\\displaystyle\\int_0^6 g(x)\\,dx = 4$, what is $\\displaystyle\\int_0^6 [f(x) + 3g(x)]\\,dx$?',
    options: ['$14$', '$22$', '$34$', '$42$'],
    correctAnswer: 1,
    explanation: '$\\int_0^6 f(x)\\,dx + 3\\int_0^6 g(x)\\,dx = 10 + 12 = 22$.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'A right Riemann sum with $n = 4$ for $\\int_0^8 f(x)\\,dx$ uses subintervals of width:',
    options: ['$1$', '$2$', '$4$', '$8$'],
    correctAnswer: 1,
    explanation: '$\\Delta x = \\frac{8 - 0}{4} = 2$.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'tables-data-calcab',
    formSet: 'both',
  },
  {
    question: 'The table shows selected values of $g(t)$:<br/><table style="border-collapse:collapse;margin:12px 0"><tr><th style="border:1px solid #888;padding:6px 14px">$t$</th><td style="border:1px solid #888;padding:6px 14px">$0$</td><td style="border:1px solid #888;padding:6px 14px">$2$</td><td style="border:1px solid #888;padding:6px 14px">$4$</td><td style="border:1px solid #888;padding:6px 14px">$6$</td></tr><tr><th style="border:1px solid #888;padding:6px 14px">$g(t)$</th><td style="border:1px solid #888;padding:6px 14px">$5$</td><td style="border:1px solid #888;padding:6px 14px">$8$</td><td style="border:1px solid #888;padding:6px 14px">$6$</td><td style="border:1px solid #888;padding:6px 14px">$10$</td></tr></table>The trapezoidal approximation of $\\int_0^6 g(t)\\,dt$ is:',
    options: ['$42$', '$44$', '$46$', '$48$'],
    correctAnswer: 1,
    explanation: '$\\frac{2}{2}(5+8) + \\frac{2}{2}(8+6) + \\frac{2}{2}(6+10) = 13 + 14 + 16 = 43$... Recalculating: $(5+8) + (8+6) + (6+10) = 13+14+16 = 43$. Hmm, that does not match. Actually each piece is $\\frac{\\Delta t}{2}(a+b) = 1 \\cdot (a+b)$. So $13 + 14 + 16 = 43$.',
    difficulty: 'medium',
    domain: 'exam-prep',
    topicSlug: 'tables-data-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f(x) = x^3 - 6x^2 + 9x + 2$, the values of $x$ at which $f$ has a critical point are:',
    options: ['$x = 1$ and $x = 3$', '$x = 0$ and $x = 2$', '$x = 2$ and $x = 6$', '$x = -1$ and $x = 3$'],
    correctAnswer: 0,
    explanation: '$f\'(x) = 3x^2 - 12x + 9 = 3(x^2 - 4x + 3) = 3(x-1)(x-3) = 0$ at $x = 1$ and $x = 3$.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'If $g\'(x) = \\dfrac{x}{x^2 + 1}$ and $g(0) = 5$, then $g(x) = $',
    options: ['$\\dfrac{1}{2}\\ln(x^2+1) + 5$', '$\\ln(x^2+1) + 5$', '$\\arctan x + 5$', '$\\dfrac{x^2}{x^2+1} + 5$'],
    correctAnswer: 0,
    explanation: '$g(x) = \\int \\frac{x}{x^2+1}dx = \\frac{1}{2}\\ln(x^2+1) + C$. $g(0) = 0 + C = 5$, so $C = 5$.',
    difficulty: 'medium',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'Which theorem guarantees a value $c$ in $(a,b)$ with $f\'(c) = \\dfrac{f(b) - f(a)}{b - a}$?',
    options: ['Intermediate Value Theorem', 'Extreme Value Theorem', 'Mean Value Theorem', 'Rolle\'s Theorem'],
    correctAnswer: 2,
    explanation: 'This is the conclusion of the Mean Value Theorem (MVT).',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'The position of a particle is given by $s(t) = t^3 - 6t^2 + 9t$. At $t = 1$, the velocity and acceleration are:',
    options: ['$v = 0$, $a = -6$', '$v = 0$, $a = 6$', '$v = 6$, $a = 0$', '$v = -6$, $a = 0$'],
    correctAnswer: 0,
    explanation: '$v(t) = 3t^2 - 12t + 9$; $v(1) = 3 - 12 + 9 = 0$. $a(t) = 6t - 12$; $a(1) = -6$.',
    difficulty: 'medium',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f$ is continuous on $[0,4]$ and $\\int_0^4 f(x)\\,dx = 20$, the average value of $f$ on $[0,4]$ is:',
    options: ['$4$', '$5$', '$10$', '$20$'],
    correctAnswer: 1,
    explanation: 'Average value $= \\frac{1}{b-a}\\int_a^b f(x)\\,dx = \\frac{20}{4} = 5$.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'A left Riemann sum with $n = 3$ for $\\int_1^7 f(x)\\,dx$ given $f(1) = 2$, $f(3) = 5$, $f(5) = 3$, $f(7) = 6$ is:',
    options: ['$20$', '$28$', '$24$', '$16$'],
    correctAnswer: 0,
    explanation: '$\\Delta x = 2$. Left sum $= f(1)(2) + f(3)(2) + f(5)(2) = 4 + 10 + 6 = 20$.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'tables-data-calcab',
    formSet: 'both',
  },
  {
    question: 'The Extreme Value Theorem states that if $f$ is continuous on $[a,b]$, then $f$ attains:',
    options: ['A zero on $(a,b)$', 'Both an absolute max and absolute min on $[a,b]$', 'A critical point on $(a,b)$', 'An inflection point on $(a,b)$'],
    correctAnswer: 1,
    explanation: 'EVT guarantees a continuous function on a closed interval attains both its absolute maximum and minimum.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'The table gives $h(t)$ (height in meters):<br/><table style="border-collapse:collapse;margin:12px 0"><tr><th style="border:1px solid #888;padding:6px 14px">$t$ (s)</th><td style="border:1px solid #888;padding:6px 14px">$0$</td><td style="border:1px solid #888;padding:6px 14px">$1$</td><td style="border:1px solid #888;padding:6px 14px">$3$</td><td style="border:1px solid #888;padding:6px 14px">$4$</td></tr><tr><th style="border:1px solid #888;padding:6px 14px">$h(t)$</th><td style="border:1px solid #888;padding:6px 14px">$10$</td><td style="border:1px solid #888;padding:6px 14px">$15$</td><td style="border:1px solid #888;padding:6px 14px">$12$</td><td style="border:1px solid #888;padding:6px 14px">$8$</td></tr></table>The average rate of change of $h$ on $[0, 4]$ is:',
    options: ['$-\\dfrac{1}{2}$ m/s', '$\\dfrac{1}{2}$ m/s', '$-2$ m/s', '$2$ m/s'],
    correctAnswer: 0,
    explanation: '$\\frac{h(4) - h(0)}{4 - 0} = \\frac{8 - 10}{4} = \\frac{-2}{4} = -\\frac{1}{2}$ m/s.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'tables-data-calcab',
    formSet: 'both',
  },
  {
    question: 'If the graph of $f\'$ crosses the $x$-axis from positive to negative at $x = c$, then $f$ has:',
    options: ['A local minimum at $x = c$', 'A local maximum at $x = c$', 'An inflection point at $x = c$', 'A discontinuity at $x = c$'],
    correctAnswer: 1,
    explanation: '$f\'$ changing from $+$ to $-$ means $f$ goes from increasing to decreasing: local maximum.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'Given $f(2) = 3$ and $f\'(2) = -4$, the tangent-line approximation at $x = 2.1$ is:',
    options: ['$2.6$', '$3.4$', '$3.6$', '$2.4$'],
    correctAnswer: 0,
    explanation: '$f(2.1) \\approx f(2) + f\'(2)(0.1) = 3 + (-4)(0.1) = 3 - 0.4 = 2.6$.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'If $\\dfrac{d}{dx}\\left[\\int_0^x f(t)\\,dt\\right] = \\sin(x^2)$, then $f(x) = $',
    options: ['$\\sin(x^2)$', '$2x\\cos(x^2)$', '$\\cos(x^2)$', '$x\\sin(x^2)$'],
    correctAnswer: 0,
    explanation: 'By FTC Part 1: $\\frac{d}{dx}\\int_0^x f(t)dt = f(x)$. So $f(x) = \\sin(x^2)$.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'A midpoint Riemann sum with $n = 3$ for $\\displaystyle\\int_0^6 f(x)\\,dx$ uses sample points at:',
    options: ['$x = 1, 3, 5$', '$x = 0, 2, 4$', '$x = 2, 4, 6$', '$x = 0, 3, 6$'],
    correctAnswer: 0,
    explanation: '$\\Delta x = 2$. Subintervals: $[0,2], [2,4], [4,6]$. Midpoints: $1, 3, 5$.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'tables-data-calcab',
    formSet: 'both',
  },
  {
    question: 'A particle has velocity $v(t) = 4 - 2t$ on $[0, 5]$. The displacement is:',
    options: ['$-5$', '$5$', '$-15$', '$15$'],
    correctAnswer: 0,
    explanation: '$\\int_0^5 (4 - 2t)dt = [4t - t^2]_0^5 = 20 - 25 = -5$.',
    difficulty: 'medium',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'The error in a trapezoidal approximation is generally reduced by:',
    options: ['Using fewer subintervals', 'Using more subintervals', 'Using a left Riemann sum instead', 'Taking the reciprocal'],
    correctAnswer: 1,
    explanation: 'More subintervals $\\Rightarrow$ smaller $\\Delta x$ $\\Rightarrow$ better approximation.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'tables-data-calcab',
    formSet: 'both',
  },
  {
    question: 'If $f\'(x) = 0$ at $x = 2$ and $f\'\'(2) = 0$, what can we conclude?',
    options: ['$f$ has a local max at $x = 2$', '$f$ has a local min at $x = 2$', 'The second derivative test is inconclusive', '$f$ has an inflection point at $x = 2$'],
    correctAnswer: 2,
    explanation: 'When $f\'(c) = 0$ and $f\'\'(c) = 0$, the second derivative test gives no conclusion. Further analysis is needed.',
    difficulty: 'medium',
    domain: 'exam-prep',
    topicSlug: 'free-response-strategies-calcab',
    formSet: 'both',
  },
  {
    question: 'A right Riemann sum with $n = 3$ on $[0, 6]$ for an increasing function $f$ will:',
    options: ['Overestimate $\\int_0^6 f(x)\\,dx$', 'Underestimate $\\int_0^6 f(x)\\,dx$', 'Equal $\\int_0^6 f(x)\\,dx$', 'Cannot determine without more info'],
    correctAnswer: 0,
    explanation: 'For an increasing function, each right rectangle height exceeds the function on its subinterval, causing overestimation.',
    difficulty: 'easy',
    domain: 'exam-prep',
    topicSlug: 'tables-data-calcab',
    formSet: 'both',
  },
"""

filepath = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    'src', 'data', 'exit-quizzes', 'ap-calculus-ab.ts'
)

with open(filepath, 'r') as f:
    content = f.read()

# Fix the (x^4+1) integral: 2*(32/5+2)=2*42/5=84/5... let me fix options & answer
NEW_QUESTIONS = NEW_QUESTIONS.replace(
    "options: ['$\\\\dfrac{72}{5}$', '$\\\\dfrac{64}{5} + 4$', '$0$', '$\\\\dfrac{64}{5}$'],\n    correctAnswer: 0,\n    explanation: 'Even function on symmetric interval: $2\\\\int_0^2 (x^4+1)dx = 2[\\\\frac{x^5}{5} + x]_0^2 = 2(\\\\frac{32}{5} + 2) = \\\\frac{64}{5} + 4 = \\\\frac{84}{5}$... Actually $2(32/5 + 2) = 64/5 + 4 = 84/5$. Hmm let me recheck: $\\\\frac{64+20}{5} = \\\\frac{84}{5}$.',",
    "options: ['$\\\\dfrac{84}{5}$', '$\\\\dfrac{64}{5}$', '$0$', '$\\\\dfrac{72}{5}$'],\n    correctAnswer: 0,\n    explanation: 'Even function on symmetric interval: $2\\\\int_0^2 (x^4+1)dx = 2[\\\\frac{x^5}{5} + x]_0^2 = 2(\\\\frac{32}{5} + 2) = \\\\frac{84}{5}$.',",
)

# Fix the trapezoidal sum: it should be 43, not 44
NEW_QUESTIONS = NEW_QUESTIONS.replace(
    "options: ['$42$', '$44$', '$46$', '$48$'],\n    correctAnswer: 1,\n    explanation: '$\\\\frac{2}{2}(5+8) + \\\\frac{2}{2}(8+6) + \\\\frac{2}{2}(6+10) = 13 + 14 + 16 = 43$... Recalculating: $(5+8) + (8+6) + (6+10) = 13+14+16 = 43$. Hmm, that does not match. Actually each piece is $\\\\frac{\\\\Delta t}{2}(a+b) = 1 \\\\cdot (a+b)$. So $13 + 14 + 16 = 43$.',",
    "options: ['$43$', '$44$', '$46$', '$48$'],\n    correctAnswer: 0,\n    explanation: '$\\\\frac{2}{2}(5+8) + \\\\frac{2}{2}(8+6) + \\\\frac{2}{2}(6+10) = 13 + 14 + 16 = 43$.',",
)

# Fix the dy/dx = 2x/y solution: y^2 = 2x^2 + 9, answer should be index 0 not 3
NEW_QUESTIONS = NEW_QUESTIONS.replace(
    "options: ['$y = \\\\sqrt{2x^2 + 9}$', '$y = x^2 + 3$', '$y = 2x + 3$', '$y = \\\\sqrt{x^2 + 9}$'],\n    correctAnswer: 3,\n    explanation: '$y\\\\,dy = 2x\\\\,dx \\\\Rightarrow \\\\frac{y^2}{2} = x^2 + C$. $y(0) = 3$: $C = \\\\frac{9}{2}$. $y^2 = 2x^2 + 9$... Actually: $y^2/2 = x^2 + 9/2 \\\\Rightarrow y^2 = 2x^2 + 9$. $y = \\\\sqrt{2x^2 + 9}$.',",
    "options: ['$y = \\\\sqrt{2x^2 + 9}$', '$y = x^2 + 3$', '$y = 2x + 3$', '$y = \\\\sqrt{x^2 + 9}$'],\n    correctAnswer: 0,\n    explanation: '$y\\\\,dy = 2x\\\\,dx \\\\Rightarrow \\\\frac{y^2}{2} = x^2 + C$. $y(0) = 3$: $C = \\\\frac{9}{2}$. $y^2 = 2x^2 + 9$. $y = \\\\sqrt{2x^2 + 9}$.',",
)

# Fix the Euler's method question: solution y=x is correct, not y=ln(e^x)
NEW_QUESTIONS = NEW_QUESTIONS.replace(
    "options: ['$y = \\\\ln(e^x)$', '$y = x$', '$y = \\\\ln(e^x - 1 + e^0)$', '$y = \\\\ln(e^x)$'],\n    correctAnswer: 0,",
    "options: ['$y = \\\\ln(e^x)$', '$y = x$', '$y = \\\\ln(e^x - 1 + e^0)$', '$y = e^{x-1}$'],\n    correctAnswer: 1,",
)

# Fix Euler's method with h=0.5 for dy/dx=2x: only 2 steps from x=1 to x=2
NEW_QUESTIONS = NEW_QUESTIONS.replace(
    "options: ['$5.5$', '$6$', '$7$', '$6.5$'],\n    correctAnswer: 1,\n    explanation: 'Step 1: slope $= 2(1) = 2$, $y_1 = 3 + 0.5(2) = 4$. Step 2: slope $= 2(1.5) = 3$, $y_2 = 4 + 0.5(3) = 5.5$. Step 3: slope $= 2(2) = 4$... Wait, only 2 steps to get from $x=1$ to $x=2$. $y(2) \\\\approx 5.5$.',",
    "options: ['$5.5$', '$6$', '$7$', '$6.5$'],\n    correctAnswer: 0,\n    explanation: 'Step 1: slope $= 2(1) = 2$, $y_1 = 3 + 0.5(2) = 4$. Step 2: slope $= 2(1.5) = 3$, $y_2 = 4 + 0.5(3) = 5.5$.',",
)

# Fix the area between y=x^2-4 question: answer is 32/3 which is option index 2
NEW_QUESTIONS = NEW_QUESTIONS.replace(
    "question: 'The area between $y = x^2 - 4$ and $y = 0$ from $x = -2$ to $x = 2$ is:',\n    options: ['$0$', '$\\\\dfrac{16}{3}$', '$\\\\dfrac{32}{3}$', '$8$'],\n    correctAnswer: 1,\n    explanation: 'On $[-2,2]$: $x^2 - 4 \\\\leq 0$. Area $= \\\\int_{-2}^2 (4 - x^2)dx = 2[4x - \\\\frac{x^3}{3}]_0^2 = 2(\\\\frac{16}{3}) = \\\\frac{32}{3}$... Actually $[4(2) - 8/3] = 16/3$, times 2 = $32/3$. Wait, let me recheck: $\\\\int_{-2}^2 |x^2-4|dx = \\\\int_{-2}^2 (4-x^2)dx = [4x - x^3/3]_{-2}^2 = (8-8/3)-(-8+8/3) = 16/3 + 16/3 = 32/3$.',",
    "question: 'The area between $y = x^2 - 4$ and $y = 0$ from $x = -2$ to $x = 2$ is:',\n    options: ['$0$', '$\\\\dfrac{16}{3}$', '$\\\\dfrac{32}{3}$', '$8$'],\n    correctAnswer: 2,\n    explanation: 'On $[-2,2]$: $x^2 - 4 \\\\leq 0$. Area $= \\\\int_{-2}^2 (4 - x^2)dx = [4x - x^3/3]_{-2}^2 = (8-8/3)-(-8+8/3) = 16/3 + 16/3 = 32/3$.',",
)

marker = "\n]\n\n/** Generate an exit quiz"
if marker in content:
    content = content.replace(marker, NEW_QUESTIONS + marker)
    with open(filepath, 'w') as f:
        f.write(content)
    print("SUCCESS: Batch 3 added")
else:
    print("ERROR: marker not found")
