/**
 * Generate the two course lookup tables used by assignments:
 *   src/lib/unit-tests/course-units.ts     — course slug -> its unit list
 *   src/lib/course-activity-routes.ts      — course slug -> unit-test / FRQ page
 *
 * Both are emitted as PLAIN LITERALS on purpose. The configs in
 * src/data/unit-tests/ each carry a full question pool, so a lookup that
 * imported them would pull every pool into a single module — enough to run the
 * production build out of memory. This script does the importing offline, at
 * generation time, so the shipped tables stay data-only.
 *
 * That also means courses whose units are COMPUTED (sat and mcat build theirs
 * from domain data) are picked up correctly, which a source-text scrape could
 * not do — they were silently missing before.
 *
 *   npx tsx scripts/gen-course-lookups.ts
 *
 * A vitest guard (tests/lib/course-lookups.test.ts) fails if either generated
 * file ever grows an import from src/data, so this stays the only way in.
 */
import fs from 'fs'
import path from 'path'

const ROOT = path.join(__dirname, '..')
const UNIT_DIR = path.join(ROOT, 'src', 'data', 'unit-tests')

interface UnitLike { id: string; unitNumber: number; name: string }
interface ConfigLike { courseSlug?: string; unitTestRoute?: string; units?: UnitLike[] }

/** tsx's CJS interop puts named exports under `default`. */
function unwrap(raw: Record<string, unknown>): Record<string, unknown> {
  const hasNamed = Object.keys(raw).some((k) => k !== 'default')
  return hasNamed ? raw : ((raw.default as Record<string, unknown>) ?? raw)
}

async function loadConfigs(): Promise<ConfigLike[]> {
  const out: ConfigLike[] = []
  for (const file of fs.readdirSync(UNIT_DIR).filter((f) => f.endsWith('.ts')).sort()) {
    const mod = unwrap((await import(path.join(UNIT_DIR, file))) as Record<string, unknown>)
    const key = Object.keys(mod).find((k) => k.endsWith('_UNIT_TESTS_CONFIG'))
    if (!key) continue
    const cfg = mod[key] as ConfigLike
    if (cfg?.courseSlug && Array.isArray(cfg.units) && cfg.units.length > 0) out.push(cfg)
  }
  return out
}

/** FRQ route keys that differ from the class-plan key for the same course. */
const FRQ_KEY_ALIASES: Record<string, string> = {
  'ap-calc-ab': 'calcab',
  'ap-calc-bc': 'calcbc',
  'ap-physics-1': 'ap-physics1',
  'ap-physics-2': 'ap-physics2',
  'ap-precalc': 'ap-precalculus',
  'ap-african-american-studies': 'ap-aas',
}

async function frqRoutes(): Promise<Record<string, string>> {
  const planMod = unwrap((await import(path.join(ROOT, 'src', 'lib', 'class-plan-config.ts'))) as Record<string, unknown>)
  const courses = planMod.CLASS_PLAN_COURSES as { key: string; courseSlug?: string }[]
  const keyToSlug = new Map(courses.filter((c) => c.courseSlug).map((c) => [c.key, c.courseSlug!]))

  const routes: Record<string, string> = {}
  for (const dir of fs.readdirSync(path.join(ROOT, 'src', 'app')).filter((d) => d.endsWith('-frq')).sort()) {
    const page = path.join(ROOT, 'src', 'app', dir, 'page.tsx')
    if (!fs.existsSync(page)) continue
    const m = fs.readFileSync(page, 'utf8').match(/fetch\('\/api\/frq\/([a-z0-9-]+)'/)
    if (!m) continue
    const slug = keyToSlug.get(FRQ_KEY_ALIASES[m[1]] ?? m[1])
    if (slug) routes[slug] = `/${dir}`
  }
  return routes
}

const banner = (what: string) => `// AUTO-GENERATED by scripts/gen-course-lookups.ts — do not edit by hand.
// ${what}
//
// Plain literals on purpose: the configs in src/data/unit-tests/ each carry a
// full question pool, so importing them here would pull every pool into one
// module and run the production build out of memory. The generator imports
// them offline instead. A vitest guard fails if this file gains a src/data
// import, so regenerate rather than "tidying" it into imports.
`

async function main() {
  const configs = await loadConfigs()

  const unitEntries = configs
    .slice()
    .sort((a, b) => a.courseSlug!.localeCompare(b.courseSlug!))
    .map((c) => {
      const units = c.units!
        .map((u) => `{ id: ${JSON.stringify(u.id)}, unitNumber: ${u.unitNumber}, name: ${JSON.stringify(u.name)} }`)
        .join(', ')
      return `  ${JSON.stringify(c.courseSlug)}: [${units}],`
    })
    .join('\n')

  fs.writeFileSync(
    path.join(ROOT, 'src', 'lib', 'unit-tests', 'course-units.ts'),
    `${banner('Course slug -> the units a teacher can target when assigning a unit test.')}
export interface UnitOption {
  id: string
  unitNumber: number
  name: string
}

const UNITS_BY_COURSE: Record<string, UnitOption[]> = {
${unitEntries}
}

/** Units available for a course's unit tests, or [] when the course has none. */
export function unitsForCourse(courseSlug: string): UnitOption[] {
  return UNITS_BY_COURSE[courseSlug] ?? []
}

/** Course slugs that actually have unit tests, for the assignment picker. */
export function coursesWithUnitTests(): string[] {
  return Object.keys(UNITS_BY_COURSE)
}
`,
  )

  const unitRoutes: Record<string, string> = {}
  for (const c of configs) if (c.unitTestRoute) unitRoutes[c.courseSlug!] = c.unitTestRoute
  const frq = await frqRoutes()
  const asBlock = (d: Record<string, string>) =>
    Object.entries(d).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n')

  fs.writeFileSync(
    path.join(ROOT, 'src', 'lib', 'course-activity-routes.ts'),
    `${banner("Where a course's unit tests and free-response practice live, so an assignment of those types can send a student to the right page.")}
const UNIT_TEST_ROUTES: Record<string, string> = {
${asBlock(unitRoutes)}
}

const FRQ_ROUTES: Record<string, string> = {
${asBlock(frq)}
}

/** The unit-tests page for a course, or null if it has none. */
export function unitTestRouteFor(courseSlug: string | null | undefined): string | null {
  return courseSlug ? UNIT_TEST_ROUTES[courseSlug] ?? null : null
}

/** The free-response page for a course, or null if it has none. */
export function frqRouteFor(courseSlug: string | null | undefined): string | null {
  return courseSlug ? FRQ_ROUTES[courseSlug] ?? null : null
}
`,
  )

  const totalUnits = configs.reduce((n, c) => n + c.units!.length, 0)
  console.log(`✓ course-units.ts: ${configs.length} courses, ${totalUnits} units`)
  console.log(`✓ course-activity-routes.ts: ${Object.keys(unitRoutes).length} unit-test routes, ${Object.keys(frq).length} FRQ routes`)
}

main().catch((e) => { console.error(e); process.exit(1) })
