#!/usr/bin/env python3
"""AP Psychology entrance quizzes — Batch 2: Learning & Cognition (6 topics)."""
from __future__ import annotations
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _psych_quiz_common import write_batch

EXPECTED = {
    "classical-conditioning",
    "operant-conditioning",
    "observational-learning-cognition",
    "memory-encoding-storage",
    "retrieval-forgetting",
    "thinking-problem-solving",
}

T = {
    "classical-conditioning": {
        "title": "Classical Conditioning",
        "prefix": "cc",
        "qs": [
            ("Ivan Pavlov (~1902, Nobel 1904) discovered classical conditioning while studying:",
             ["Memory in pigeons", "Salivation/digestion in dogs — dogs began salivating to cues that predicted food", "Phobias", "Reinforcement schedules"], 1,
             "Pavlov was studying digestive physiology when he noticed dogs salivating to lab assistants and bells before food arrived."),
            ("In Pavlov's terminology, food in the mouth is the:",
             ["CS (conditioned stimulus)", "UCS (unconditioned stimulus) — naturally elicits salivation without learning", "CR (conditioned response)", "Neutral stimulus"], 1,
             "UCS = food (innate trigger). UCR = salivation. After pairing, the bell (CS) → salivation (CR)."),
            ("Acquisition of a CR is generally STRONGEST when:",
             ["The CS comes AFTER the UCS (backward conditioning)", "The CS appears shortly BEFORE the UCS — the CS becomes a reliable predictor (forward, short-delay conditioning)", "CS and UCS are simultaneous", "UCS occurs alone"], 1,
             "Forward, short-delay conditioning is most effective; backward and simultaneous conditioning produce weaker learning."),
            ("Extinction occurs when the CS is presented:",
             ["With the UCS", "REPEATEDLY without the UCS, until the CR fades", "Once and never again", "Only briefly"], 1,
             "Extinction = CS-alone trials. The CR weakens but is not erased — see spontaneous recovery."),
            ("Spontaneous recovery refers to:",
             ["A new conditioning trial", "Reappearance of an extinguished CR after a rest period (no further pairing)", "Generalization to similar stimuli", "Higher-order conditioning"], 1,
             "Spontaneous recovery shows extinction inhibits but does not erase the original learning."),
            ("Stimulus generalization occurs when:",
             ["Only the exact CS triggers a CR", "Stimuli SIMILAR to the CS also trigger the CR (a child bitten by a golden retriever fears all dogs)", "The CR weakens", "The UCS is omitted"], 1,
             "Generalization gradient: response strength decreases as stimuli become less similar to the original CS."),
            ("Stimulus discrimination is:",
             ["Failing to learn", "LEARNED responding to one specific CS but NOT to similar stimuli (a dog salivates to 1000 Hz tone but not 500 Hz)", "Innate", "The same as generalization"], 1,
             "Discrimination is trained by pairing the UCS with one CS and presenting similar stimuli WITHOUT the UCS."),
            ("In higher-order conditioning, a previously conditioned CS:",
             ["Stops working", "Acts AS a UCS to condition a new neutral stimulus (light + bell → salivation, then light alone → salivation)", "Causes only extinction", "Triggers no response"], 1,
             "Second-order conditioning explains how complex chains of associations form (e.g., advertising linking products to already-conditioned cues)."),
            ("Watson & Rayner's 'Little Albert' study (1920) classically conditioned an 11-month-old infant to fear:",
             ["A spider", "A white rat by pairing it with a loud clanging steel bar (UCS) — fear generalized to other furry objects", "His mother", "Bright lights"], 1,
             "Little Albert demonstrated that emotional responses (phobias) can be classically conditioned. Ethically unacceptable today."),
            ("Garcia and Koelling (1966) showed taste-aversion learning is BIOLOGICALLY PREPARED because:",
             ["All stimuli pair equally with all USes", "Rats associate TASTE (not lights/sounds) with later illness, and shock with audiovisual cues — biological preparedness violates strict equipotentiality", "Rats cannot learn at all", "Only humans show preparedness"], 1,
             "Garcia effect: animals readily learn evolutionarily relevant CS-UCS pairings (taste→nausea) even with hours of delay; other pairings resist learning."),
            ("Mary Cover Jones (1924) and later Joseph Wolpe developed counter-conditioning, the basis of:",
             ["Psychoanalysis", "Systematic desensitization — pairing a feared CS with relaxation to extinguish phobia", "Token economies", "Trephination"], 1,
             "Counter-conditioning replaces the CR with an incompatible response (relaxation), foundational to behavioral therapies for phobias."),
            ("Robert Rescorla (1968) demonstrated that classical conditioning requires the CS to:",
             ["Simply co-occur with the UCS", "PREDICT the UCS — providing reliable information; mere contiguity is not sufficient", "Be presented after the UCS", "Be biologically prepared"], 1,
             "Rescorla's contingency model replaced strict contiguity: a CS that does not improve UCS prediction (e.g., random pairings) does not condition."),
            ("On the AP Psych exam, a question describing a chemotherapy patient who feels nauseated walking into the clinic months later expects:",
             ["Operant conditioning", "Classical conditioning (the clinic = CS, chemo drugs = UCS, nausea = CR) — often called conditioned nausea or taste-aversion-like learning", "Observational learning", "Reinforcement schedules"], 1,
             "Bovbjerg and others documented anticipatory nausea: classical conditioning generalizes to clinic sights/smells."),
            ("Which AP-style claim is correct?",
             ["Classical conditioning works equally well for all CS-UCS pairings", "Classical conditioning is shaped by biological preparedness, contingency (predictiveness), and timing — not just contiguity", "It explains all learning", "It applies only to dogs"], 1,
             "Modern view (post-Rescorla, Garcia) integrates predictive value and biological constraints with traditional contiguity."),
        ],
    },

    "operant-conditioning": {
        "title": "Operant Conditioning",
        "prefix": "oc",
        "qs": [
            ("Operant conditioning was systematized by:",
             ["Pavlov", "B.F. Skinner (building on Thorndike's Law of Effect, 1898) using operant chambers ('Skinner boxes')", "Wundt", "Freud"], 1,
             "Thorndike (1898) Law of Effect: behaviors followed by satisfying consequences are more likely to recur. Skinner extended this systematically."),
            ("Thorndike's Law of Effect states behaviors followed by:",
             ["Punishment are repeated", "Satisfying consequences are STRENGTHENED; behaviors followed by aversive consequences are weakened", "Nothing change", "Time delays vanish"], 1,
             "Thorndike's puzzle-box cats learned to escape faster after each successful trial — basis of all instrumental learning research."),
            ("POSITIVE reinforcement:",
             ["Removes a stimulus", "ADDS a desirable stimulus to increase a behavior (e.g., praise after homework)", "Removes a chore", "Decreases behavior"], 1,
             "'Positive' = added; 'reinforcement' = increases behavior. Both reinforcement types INCREASE behavior."),
            ("NEGATIVE reinforcement:",
             ["Adds a punisher", "REMOVES an aversive stimulus to increase a behavior (buckling a seatbelt to stop the beeping)", "Decreases behavior", "Is the same as punishment"], 1,
             "Negative reinforcement is NOT punishment — it removes something unpleasant, INCREASING the behavior that ended the aversive state."),
            ("POSITIVE punishment:",
             ["Removes a desired item", "ADDS an aversive stimulus to DECREASE behavior (a speeding ticket)", "Increases behavior", "Removes a chore"], 1,
             "Both punishments DECREASE behavior. 'Positive' = added stimulus; 'negative' = removed stimulus."),
            ("NEGATIVE punishment (response cost):",
             ["Adds a chore", "REMOVES a desirable stimulus to DECREASE behavior (taking away phone privileges)", "Adds praise", "Increases behavior"], 1,
             "Time-out and loss of privileges are negative punishment. Skinner generally favored reinforcement over punishment as more effective."),
            ("A primary reinforcer is:",
             ["A learned reinforcer", "Innately reinforcing — satisfies a biological need (food, water, warmth)", "Money", "A grade"], 1,
             "Primary reinforcers are biologically wired. Secondary (conditioned) reinforcers (money, grades) acquire value through pairing."),
            ("Shaping is:",
             ["One-trial learning", "Reinforcing successive APPROXIMATIONS toward a target behavior (used to train animals and shape complex skills)", "Removing reinforcement", "Punishment", ], 1,
             "Skinner shaped pigeons to peck disks, play ping-pong, etc. — by reinforcing closer-and-closer behaviors."),
            ("A FIXED-RATIO (FR) schedule reinforces:",
             ["After variable time", "After every Nth response (e.g., FR-10) — produces high response rates with brief post-reinforcement pauses", "Random", "Continuous"], 1,
             "FR (e.g., piecework pay) → fast steady responding with a pause right after each reinforcer."),
            ("A VARIABLE-RATIO (VR) schedule (e.g., slot machines) produces:",
             ["The lowest response rate", "The HIGHEST and most extinction-resistant response rates — reinforcement after an unpredictable number of responses", "Slow responding", "No learning"], 1,
             "VR schedules drive gambling and many addictive behaviors. Hard to extinguish because every response could be 'the one.'"),
            ("FIXED-INTERVAL (FI) schedules produce:",
             ["Steady responding throughout", "A SCALLOPED pattern — slow responding after reinforcement, accelerating just before the next reinforcer (e.g., studying right before a weekly quiz)", "Random bursts", "No responding"], 1,
             "FI: only the first response after a fixed time period is reinforced. Cumulative records show characteristic scallop."),
            ("Cognitive map / latent learning was demonstrated by:",
             ["Watson", "Edward Tolman (1948) — rats that explored a maze without reinforcement showed sudden mastery once reward was introduced, implying mental maps", "Skinner", "Thorndike"], 1,
             "Tolman's rats challenged strict behaviorism: learning can occur WITHOUT immediate reinforcement (latent learning) and includes cognitive representations."),
            ("On the AP Psych exam, a question about a child whining until a parent gives candy describes:",
             ["Positive punishment for the child", "Negative reinforcement FOR THE PARENT (whining stops when candy is given) and positive reinforcement FOR THE CHILD (candy)", "Extinction", "Shaping"], 1,
             "Many parent-child cycles involve mutual reinforcement: each party's behavior strengthens the other's."),
            ("Which AP-style claim is correct?",
             ["Punishment is generally the most effective behavior change", "Reinforcement (especially positive) tends to be more effective than punishment for shaping new behavior; punishment can suppress behavior temporarily but has side effects (fear, aggression, modeling)", "Schedules don't matter", "Operant and classical conditioning are identical"], 1,
             "Modern behavior analysis emphasizes positive reinforcement, with punishment used cautiously due to documented side effects."),
        ],
    },

    "observational-learning-cognition": {
        "title": "Observational Learning & Cognition",
        "prefix": "olc",
        "qs": [
            ("Observational (social) learning was systematized by:",
             ["B.F. Skinner", "Albert Bandura — Social Learning / Social Cognitive Theory (1960s-)", "Pavlov", "Tolman"], 1,
             "Bandura argued people learn by observing models, not just through direct reinforcement — extending behaviorism toward cognitive social learning."),
            ("Bandura's Bobo doll study (1961) found that children who watched an aggressive adult model:",
             ["Were less aggressive", "Were MORE likely to imitate the specific aggressive acts toward the doll, even without reinforcement", "Showed no effect", "Became calmer"], 1,
             "Bobo doll experiments demonstrated imitation/modeling and influenced later concerns about media violence."),
            ("Bandura's four key processes for observational learning are:",
             ["Eat, sleep, move, repeat", "Attention, retention, reproduction (motor), motivation", "Stimulus, response, reward, punishment", "Id, ego, superego, drive"], 1,
             "Each step can fail: didn't pay attention, didn't remember, can't physically reproduce, or no motivation to perform."),
            ("Vicarious reinforcement / vicarious punishment occurs when:",
             ["You receive reinforcement", "Observing a model BEING reinforced or punished changes the observer's likelihood of performing the behavior", "Behaviors decrease randomly", "Only humans use it"], 1,
             "Bobo follow-ups: children imitated MORE when the model was rewarded and LESS when punished, even though the children themselves received nothing."),
            ("Mirror neurons (di Pellegrino, Rizzolatti et al. 1992) fire both when an animal:",
             ["Sleeps and wakes", "Performs an action AND when it observes another performing the same action", "Eats and digests", "Sees and hears"], 1,
             "Macaque mirror neurons (premotor F5) suggested a neural basis for imitation, though their role in human social cognition is debated."),
            ("Observational learning is especially powerful when the model is:",
             ["Strange and unrelated", "Similar to the observer, high-status, attractive, warm, or successful", "Punished severely", "Unknown"], 1,
             "Bandura: model characteristics (status, similarity, warmth) increase attention and motivation to imitate."),
            ("Insight learning (Wolfgang Köhler's chimps, ~1925) is:",
             ["Slow trial-and-error", "Sudden 'aha' solution after restructuring the problem (Sultan stacking boxes to reach bananas)", "Reinforcement-driven", "Imitation"], 1,
             "Köhler's Mentality of Apes argued some learning is sudden/cognitive, not just incremental — challenging strict behaviorism."),
            ("Latent learning (Tolman & Honzik 1930) showed:",
             ["Learning requires immediate reinforcement", "Learning can occur WITHOUT reinforcement and remain hidden until reward provides MOTIVATION to perform", "Animals cannot learn mazes", "Only classical conditioning works"], 1,
             "Rats with no reward formed cognitive maps; once rewarded, they performed as well as continuously-rewarded rats."),
            ("The overjustification effect (Lepper, Greene, & Nisbett 1973) found that:",
             ["External rewards always boost interest", "Excessive EXTERNAL rewards for an already-intrinsically-rewarding activity can REDUCE intrinsic motivation", "Rewards do nothing", "Punishment increases interest"], 1,
             "Children who liked drawing lost interest after being rewarded for it — implications for classroom and parenting practice."),
            ("Carol Dweck's (1988-) growth vs fixed mindset research found that students taught a:",
             ["Fixed mindset achieve more", "GROWTH mindset (intelligence is malleable with effort) tend to show greater resilience and improvement than those with a fixed mindset", "Mindsets don't matter", "Reward mindset is best"], 1,
             "Dweck's mindset interventions are influential, though effect sizes are debated and replication results are mixed."),
            ("Prosocial modeling (e.g., children who see helpful models help more) and antisocial modeling (e.g., bullying spread by peer models) both demonstrate:",
             ["Operant conditioning only", "The power of OBSERVATIONAL learning to spread both helpful and harmful behaviors across social networks", "Classical conditioning", "Innate reflexes"], 1,
             "Bandura emphasized that modeling is a major mechanism for cultural transmission of values and behavior."),
            ("Bandura's concept of self-efficacy refers to:",
             ["Self-esteem in general", "A person's BELIEF in their capability to perform a specific task — predicts persistence and achievement", "IQ", "Locus of control"], 1,
             "Self-efficacy beliefs influence task choice, effort, persistence, and resilience — distinct from global self-esteem."),
            ("On the AP Psych exam, a question about teens copying risky stunts after watching a viral video describes:",
             ["Operant conditioning", "Observational learning / modeling (Bandura)", "Classical conditioning", "Habituation"], 1,
             "Imitation of media models is the modern extension of Bandura's Bobo work."),
            ("Which AP-style claim is correct?",
             ["Only direct reinforcement teaches new behavior", "Humans learn extensively by observing others, allowing cultural transmission of skills, language, and values that direct reinforcement could not efficiently teach", "Cognition plays no role in learning", "Mirror neurons fully explain imitation"], 1,
             "Bandura's social cognitive theory expanded learning theory to include attention, expectation, and self-regulation."),
        ],
    },

    "memory-encoding-storage": {
        "title": "Memory: Encoding & Storage",
        "prefix": "mes",
        "qs": [
            ("The Atkinson-Shiffrin (1968) model proposes three memory stores:",
             ["Working, episodic, semantic", "Sensory memory → Short-term (working) memory → Long-term memory", "Procedural, declarative, implicit", "Iconic only"], 1,
             "The 'modal model' became the dominant framework, later updated by Baddeley's working memory model (1974)."),
            ("Sperling (1960) demonstrated ICONIC memory (visual sensory store) lasts about:",
             ["Several minutes", "About 0.5 seconds (partial-report procedure showed brief but high-capacity visual trace)", "30 seconds", "Permanent"], 1,
             "Sperling's partial-report technique inferred ~9-12 items briefly available, fading rapidly."),
            ("Echoic memory (auditory sensory store) lasts approximately:",
             ["30 minutes", "About 3-4 seconds", "Less than 0.1 seconds", "Permanent"], 1,
             "Echoic memory is longer-lasting than iconic, allowing speech sounds to be processed across time."),
            ("George Miller's (1956) classic paper described short-term memory capacity as:",
             ["About 100 items", "The 'magical number SEVEN, plus or minus two' — about 5-9 items (modern estimates often closer to 4 chunks)", "Unlimited", "Two items"], 1,
             "Miller's 7±2 was foundational; Cowan (2001) revised the estimate downward to ~4 chunks of unrelated information."),
            ("Chunking expands STM capacity by:",
             ["Talking faster", "Grouping items into MEANINGFUL units (e.g., 1-7-7-6 → '1776')", "Adding noise", "Reducing meaning"], 1,
             "Expert chess players chunk piece configurations, allowing them to recall game positions far better than novices."),
            ("Baddeley & Hitch's (1974) WORKING memory model adds components beyond passive STM:",
             ["Sensory store and LTM", "Phonological loop, visuospatial sketchpad, episodic buffer, all coordinated by a CENTRAL EXECUTIVE", "Iconic and echoic", "Implicit and explicit"], 1,
             "Working memory is an active workspace, not just storage. The episodic buffer was added in 2000."),
            ("Encoding refers to:",
             ["Recalling information", "Getting information INTO memory (visual, acoustic, semantic processing)", "Storing it long-term", "Forgetting"], 1,
             "Encoding can be effortful (study) or automatic (well-learned info, time of day, well-known names)."),
            ("Levels-of-processing theory (Craik & Lockhart 1972) proposes that:",
             ["Maintenance rehearsal is best", "DEEPER (semantic) processing produces better long-term retention than shallow (visual/acoustic) processing", "Depth doesn't matter", "Forgetting is automatic"], 1,
             "Asking about MEANING (semantic) of words yields better recall than asking about appearance or sound."),
            ("Long-term memory is divided into:",
             ["Iconic and echoic", "Explicit (declarative: episodic + semantic) and Implicit (procedural, classical conditioning, priming)", "Sensory and working", "STM and WM"], 1,
             "Squire's taxonomy: episodic (events), semantic (facts) are explicit; procedural skills and conditioned responses are implicit."),
            ("Episodic memory depends heavily on the:",
             ["Cerebellum", "Hippocampus and surrounding medial temporal lobe (HM's lesion impaired episodic encoding)", "Amygdala only", "Brainstem"], 1,
             "Hippocampus consolidates new explicit memories; older memories gradually become independent of hippocampal activity."),
            ("Procedural (motor skill) memory depends on the:",
             ["Hippocampus only", "Cerebellum and basal ganglia (intact in HM, who could learn new skills despite amnesia)", "Frontal lobe only", "Pituitary"], 1,
             "Procedural memory is preserved in many amnesias, supporting separate memory systems."),
            ("The serial position effect predicts better recall for items at the:",
             ["Middle only", "Beginning (PRIMACY: rehearsed into LTM) and end (RECENCY: still in STM) of a list", "End only", "Random positions"], 1,
             "Primacy + recency yields the U-shaped serial position curve, supporting two memory stores."),
            ("On the AP Psych exam, a question about a chess master remembering a real board position more accurately than a random arrangement tests:",
             ["Capacity of LTM", "CHUNKING — meaningful patterns are encoded as units (Chase & Simon, 1973)", "Procedural memory", "Iconic memory"], 1,
             "Chase & Simon: experts' superior memory depends on meaningful structure; performance falls to novice levels with random pieces."),
            ("Which AP-style claim is correct?",
             ["Memory is a single unitary store", "Memory comprises multiple distinct systems (sensory, working, long-term explicit, long-term implicit) supported by different brain regions", "All memory is conscious", "STM has unlimited capacity"], 1,
             "Modern view: memory is multiple dissociable systems with different neural substrates."),
        ],
    },

    "retrieval-forgetting": {
        "title": "Retrieval & Forgetting",
        "prefix": "rf",
        "qs": [
            ("RECALL requires you to:",
             ["Choose from options", "RETRIEVE information without cues (e.g., short-answer test)", "Recognize", "Re-learn"], 1,
             "Recall (free or cued) is harder than recognition because it requires generating the information."),
            ("RECOGNITION requires you to:",
             ["Generate without cues", "IDENTIFY previously learned information from options (e.g., multiple-choice)", "Re-derive everything", "Forget"], 1,
             "Recognition memory is much more sensitive than recall — we recognize many faces and words we cannot freely produce."),
            ("RELEARNING (Ebbinghaus 1885) showed:",
             ["No memory after one day", "Saving SCORES — relearning previously studied material is faster, even when conscious recall is gone", "Total amnesia", "Recall always equals recognition"], 1,
             "Ebbinghaus's savings method demonstrated implicit retention of forgotten material; foundation for the forgetting curve."),
            ("Ebbinghaus's forgetting curve shows:",
             ["Linear forgetting", "RAPID initial forgetting that slows over time (most loss in first hours/days)", "No forgetting", "Steady decline"], 1,
             "Negatively accelerated decay — review timed to slow points improves long-term retention (basis of spaced repetition)."),
            ("The encoding-specificity principle (Tulving) holds that retrieval is best when:",
             ["The cue is unrelated to encoding", "Retrieval CUES match the conditions present at encoding (context, mood, location)", "Mood doesn't matter", "Cues should be distinctive only"], 1,
             "Godden & Baddeley (1975): scuba divers learning words underwater recall best underwater. State-dependent and context-dependent learning."),
            ("Mood-congruent memory describes the tendency to:",
             ["Recall events that match current mood", "Recall events whose emotional valence MATCHES current mood (happy mood → happy memories)", "Forget all emotions", "Recall random events"], 1,
             "Mood congruence can perpetuate depressive episodes (depressed mood → biased recall of negative memories)."),
            ("Proactive interference is when:",
             ["New learning blocks old", "OLD information disrupts learning or retrieval of NEW information (your old phone number intrudes on the new one)", "No interference occurs", "Encoding fails"], 1,
             "Proactive: PRO = forward; old → new. Retroactive: RETRO = backward; new → old."),
            ("Retroactive interference is when:",
             ["Old blocks new", "NEW information disrupts retrieval of OLDER information", "Encoding fails", "No interference"], 1,
             "Sleeping shortly after study reduces retroactive interference compared to waking activity (Jenkins & Dallenbach 1924)."),
            ("Loftus & Palmer (1974) showed eyewitness memory is shaped by:",
             ["Photographs only", "POST-event suggestion — wording of a question ('smashed' vs 'hit') altered estimated speeds and false memory of broken glass — the misinformation effect", "Polygraph", "Hypnosis only"], 1,
             "Loftus's work demonstrated memory is reconstructive, not videotape-like, with major implications for eyewitness testimony."),
            ("Loftus's 'lost in the mall' technique demonstrated:",
             ["Memory is photographic", "Researchers can implant FALSE childhood memories in a substantial minority of participants through suggestion and repetition", "All memories are accurate", "Children cannot be misled"], 1,
             "Loftus & Pickrell (1995): ~25% of adults came to believe (and 'remember') a fabricated childhood event."),
            ("Tip-of-the-tongue (TOT) experiences illustrate:",
             ["Total forgetting", "RETRIEVAL FAILURE — information is stored but momentarily inaccessible (often partial info available: first letter, syllable count)", "No memory", "Encoding failure"], 1,
             "TOT shows storage and retrieval are dissociable; partial activation indicates the trace exists but lookup falters."),
            ("Repressed-memory therapy (popularized 1980s-90s) is now considered:",
             ["Strong scientifically", "Largely DISCREDITED — much of what was 'recovered' was likely shaped by suggestive techniques and the misinformation effect (APA 1996; multiple court cases reversed)", "Required practice", "Universal"], 1,
             "Mainstream consensus (Loftus, McNally, McHugh) holds that suggestive 'recovery' techniques can implant rather than retrieve memories."),
            ("On the AP Psych exam, a question describing a witness whose police-interview wording changed her later 'memory' tests:",
             ["State-dependent learning", "Misinformation effect (Loftus)", "Procedural memory", "Iconic memory"], 1,
             "AP Psych emphasizes Loftus's misinformation paradigm and the reconstructive nature of memory."),
            ("Which AP-style claim is correct?",
             ["Memory replays exactly what happened", "Memory is reconstructive — affected by encoding context, retrieval cues, interference, and post-event suggestion — even confident memories can be wrong", "Forgetting is rare", "Hypnosis recovers buried truths"], 1,
             "AP Psych frames memory as actively reconstructed; eyewitness reform (sequential lineups, blind administration) reflects this science."),
        ],
    },

    "thinking-problem-solving": {
        "title": "Thinking & Problem Solving",
        "prefix": "tps",
        "qs": [
            ("A CONCEPT is:",
             ["A specific event", "A mental grouping of similar objects, events, or ideas (e.g., 'furniture')", "An emotion", "A neuron"], 1,
             "Concepts let us treat new instances by their category. Hierarchies (basic, superordinate, subordinate) organize them (Rosch)."),
            ("Eleanor Rosch's PROTOTYPE theory holds we judge category membership by:",
             ["Strict definitions", "Similarity to a 'best example' or PROTOTYPE (a robin is a more typical bird than a penguin)", "Random sampling", "Alphabetical order"], 1,
             "Rosch (1975) showed graded category membership and prototypicality effects in reaction times and ratings."),
            ("An ALGORITHM is:",
             ["A guess", "A step-by-step procedure that GUARANTEES a solution (e.g., long division)", "A bias", "A heuristic"], 1,
             "Algorithms are systematic but can be slow. Heuristics trade certainty for speed."),
            ("A HEURISTIC is:",
             ["A guaranteed solution", "A mental SHORTCUT (rule of thumb) that often works but can fail", "A random guess", "A reflex"], 1,
             "Heuristics enable fast judgments under uncertainty. Tversky & Kahneman documented systematic biases that arise from them."),
            ("The AVAILABILITY heuristic (Tversky & Kahneman 1973) is judging probability by:",
             ["Statistics", "How EASILY examples come to mind (vivid plane crashes inflate fear of flying vs driving)", "Logical analysis", "Survey data"], 1,
             "Availability explains many risk perception errors: rare-but-vivid events feel more probable than they are."),
            ("The REPRESENTATIVENESS heuristic is judging probability by:",
             ["Available examples", "Similarity to a STEREOTYPE/prototype (Linda problem: more people judge 'feminist bank teller' more probable than 'bank teller')", "Base rates", "Probability theory"], 1,
             "Tversky & Kahneman 'Linda problem' demonstrates conjunction fallacy — overlooking that P(A∩B) ≤ P(A)."),
            ("CONFIRMATION bias is the tendency to:",
             ["Seek disconfirming evidence", "SEEK and remember information that CONFIRMS one's existing beliefs while underweighting disconfirming evidence", "Be perfectly objective", "Reverse beliefs"], 1,
             "Confirmation bias affects political reasoning, scientific theorizing, and everyday judgment. Identified by Wason (1960) selection task."),
            ("MENTAL SET (Luchins water-jar problem, 1942) is:",
             ["Random thinking", "Tendency to use a previously SUCCESSFUL approach even when a simpler one is available", "Always optimal", "A bias-free strategy"], 1,
             "Luchins showed people kept using a complex 3-jar formula even when a simple one-step solution was available."),
            ("FUNCTIONAL FIXEDNESS is the tendency to:",
             ["Be flexible", "See objects only in their USUAL function (failing to use a pliers as a pendulum weight in Maier's two-string problem, 1931)", "Use objects creatively", "Solve novel problems quickly"], 1,
             "Functional fixedness blocks creative problem solving when familiar uses dominate. Reduced by reframing the object generically."),
            ("FRAMING effects (Tversky & Kahneman 1981) show choices change when options are described as:",
             ["Identical numbers", "GAINS vs LOSSES (e.g., '90% survival rate' vs '10% mortality') — even though equivalent, framing alters preferences", "Equally desirable", "Random"], 1,
             "Prospect theory: people are loss-averse, so loss-framed options are weighted differently than mathematically equivalent gain-framed options."),
            ("The ANCHORING effect is:",
             ["Ignoring reference points", "RELYING too heavily on the first piece of information ('anchor') when making estimates (used in negotiations, sale prices)", "Random estimates", "Pure logic"], 1,
             "Even arbitrary anchors (random numbers spun on a wheel) influence subsequent quantitative estimates."),
            ("Belief PERSEVERANCE refers to:",
             ["Updating beliefs rationally", "Clinging to initial beliefs even after evidence supporting them is discredited", "Always changing beliefs", "Bayesian reasoning"], 1,
             "Ross, Lepper, & Hubbard (1975): beliefs persist even when their original evidentiary basis is removed."),
            ("On the AP Psych exam, a question about overestimating shark attack risk after seeing news coverage tests:",
             ["Confirmation bias", "Availability heuristic", "Anchoring", "Functional fixedness"], 1,
             "Vivid, recent, emotional examples come easily to mind, distorting perceived probability — the availability heuristic."),
            ("Which AP-style claim is correct?",
             ["Human reasoning is fully rational", "Human reasoning relies on heuristics that are usually adaptive but produce systematic biases (Tversky-Kahneman, Nobel 2002 to Kahneman)", "Heuristics are always wrong", "Algorithms are always slower"], 1,
             "Dual-process accounts (Kahneman 'Thinking Fast and Slow', 2011) integrate fast/heuristic and slow/deliberative thinking."),
        ],
    },
}

if __name__ == "__main__":
    write_batch(T, EXPECTED)
