#!/usr/bin/env python3
"""AP Psychology entrance quizzes — Batch 3: Development, Motivation, Personality (5 topics)."""
from __future__ import annotations
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _psych_quiz_common import write_batch

EXPECTED = {
    "adolescence-adulthood",
    "language-intelligence",
    "motivation-theories",
    "emotion-stress",
    "personality-theories",
}

T = {
    "adolescence-adulthood": {
        "title": "Adolescence & Adulthood",
        "prefix": "aa",
        "qs": [
            ("Puberty in girls is typically marked by MENARCHE around age:",
             ["6", "About 12 (range 9-16); average has dropped over the past century, partly due to nutrition", "20", "30"], 1,
             "Secular trend: average menarche fell from ~16 in 1840 to ~12 today in industrialized countries (better nutrition, lower infectious load)."),
            ("During adolescence, the PREFRONTAL cortex matures:",
             ["Earlier than the limbic system", "LATER than limbic/reward systems — creating a developmental gap that helps explain risk-taking and impulsivity", "At the same time", "Not at all"], 1,
             "Casey, Steinberg, and others document the limbic-prefrontal asymmetry of adolescence (~ages 12-25)."),
            ("Erik Erikson's adolescent stage is:",
             ["Trust vs Mistrust", "Identity vs Role Confusion — forming a coherent sense of self", "Generativity vs Stagnation", "Integrity vs Despair"], 1,
             "Erikson saw adolescence as a psychosocial moratorium for exploring values, vocation, and identity."),
            ("James Marcia (1966) identified four IDENTITY STATUSES based on exploration × commitment:",
             ["Only 'achieved' and 'lost'", "Identity diffusion, foreclosure, moratorium, achievement", "Just two: child / adult", "Stages identical to Erikson"], 1,
             "Marcia operationalized Erikson's theory: foreclosure = commitment without exploration; achievement = both."),
            ("Kohlberg's POSTCONVENTIONAL morality is characterized by:",
             ["Obedience to authority", "Reasoning from universal ethical PRINCIPLES that may override laws (e.g., civil disobedience)", "Self-interest only", "Blind rule-following"], 1,
             "Postconventional reasoning is uncommon and developed late, if at all. Kohlberg said many adults remain at conventional level."),
            ("Carol Gilligan (1982) critiqued Kohlberg by arguing his stages:",
             ["Were too lenient", "Underemphasized a 'CARE' orientation (relationships, responsibility) more typical of how women describe moral dilemmas", "Were too strict for males", "Did not exist"], 1,
             "Gilligan's 'In a Different Voice' argued for a relational ethic of care alongside the justice orientation."),
            ("ADOLESCENT egocentrism (Elkind 1967) includes the:",
             ["IMAGINARY AUDIENCE (teens feel constantly watched/judged) and PERSONAL FABLE (teens feel uniquely invulnerable or special)", "Sensory adaptation", "Object permanence", "Phi phenomenon"], 0,
             "These cognitive distortions help explain self-consciousness and risk taking in adolescence."),
            ("Authoritative parenting (Baumrind 1967, 1971) combines:",
             ["Low warmth and high control", "HIGH warmth and HIGH control — generally associated with the most positive child outcomes in Western samples", "Low both", "High warmth, no rules"], 1,
             "Baumrind's other styles: authoritarian (low warmth/high control), permissive (high warmth/low control), neglectful (low both)."),
            ("Levinson (1978) and others described EMERGING adulthood (Arnett 2000, ages ~18-25) as:",
             ["A return to childhood", "A distinct stage of identity exploration, instability, and feeling 'in-between' — increasingly delayed marriage, parenthood, financial independence", "Identity foreclosure", "Senescence"], 1,
             "Arnett's emerging adulthood concept reflects demographic changes since the 1970s in industrialized societies."),
            ("Erikson's MIDDLE adulthood stage is:",
             ["Identity vs Role Confusion", "Generativity vs Stagnation — contributing to the next generation through work, parenting, mentorship", "Trust vs Mistrust", "Industry vs Inferiority"], 1,
             "Generativity researchers (McAdams) link generativity to higher well-being in midlife."),
            ("Crystallized vs Fluid INTELLIGENCE across the lifespan:",
             ["Both decline rapidly after 30", "Crystallized (knowledge, vocabulary) tends to RISE or hold steady into older age; fluid (novel reasoning, processing speed) tends to DECLINE earlier", "Both rise indefinitely", "Both are unrelated to age"], 1,
             "Cattell-Horn-Carroll model. Fluid IQ peaks in 20s; crystallized IQ can rise into 60s-70s."),
            ("Elisabeth Kübler-Ross (1969) proposed five stages of grief:",
             ["Bargaining only", "Denial, Anger, Bargaining, Depression, Acceptance — descriptive (not strictly sequential or universal)", "Three stages", "None"], 1,
             "Modern bereavement research (Bonanno) finds many trajectories (resilience common); the 'stages' are not a required sequence."),
            ("On the AP Psych exam, a question about a midlife adult mentoring younger employees and finding meaning in shaping the next generation tests:",
             ["Identity vs role confusion", "Generativity vs Stagnation (Erikson, middle adulthood)", "Trust vs mistrust", "Integrity vs despair"], 1,
             "Generativity is the central task of middle adulthood in Erikson's framework."),
            ("Which AP-style claim is correct?",
             ["Cognitive decline in old age is universal and rapid", "Aging shows differential changes — speed-based cognition declines while knowledge and emotional regulation often improve; lifestyle and health buffer decline", "All older adults develop dementia", "Personality changes radically every decade"], 1,
             "Modern lifespan research (Carstensen, Salthouse) emphasizes both losses and gains in adult development."),
        ],
    },

    "language-intelligence": {
        "title": "Language & Intelligence",
        "prefix": "li",
        "qs": [
            ("Language has hierarchical levels:",
             ["Sentences only", "Phonemes (sounds) → morphemes (smallest meaning units) → words → syntax → semantics", "Just words", "Letters only"], 1,
             "Phonology, morphology, syntax, semantics, and pragmatics are the standard linguistic levels."),
            ("Infants begin BABBLING (e.g., 'ba-ba-ga-ga') around:",
             ["12 months", "About 4 months — and initially produce phonemes from many languages, then narrow to native sounds", "24 months", "8 years"], 1,
             "Babbling becomes language-specific by ~10 months as infants tune to their language's phonemes."),
            ("Children produce ONE-WORD utterances around:",
             ["6 months", "About 12 months", "3 years", "5 years"], 1,
             "First words ~12 months; vocabulary expands rapidly during the second year (~50 words by 18 months)."),
            ("TELEGRAPHIC speech (e.g., 'want cookie') emerges around:",
             ["6 months", "About 18-24 months — short sentences with mostly content words", "5 years", "10 years"], 1,
             "Telegraphic speech reflects emerging syntax with limited grammatical morphemes."),
            ("Noam Chomsky (1957, 1965) argued language acquisition requires:",
             ["Pure reinforcement", "An innate language acquisition device / Universal Grammar — humans are biologically prepared for language", "No learning", "Imitation only"], 1,
             "Chomsky's nativist view stressed the 'poverty of the stimulus': children acquire complex grammar far beyond what reinforcement could explain."),
            ("Critical/sensitive period evidence (e.g., Genie 1970; Newport on second-language learners) suggests:",
             ["Language can be learned equally well at any age", "Language acquisition is much harder after early childhood; later second-language learners rarely reach native-like grammar", "Only adults learn language", "Critical periods do not exist"], 1,
             "Lenneberg (1967) proposed a critical period; modern view: sensitive period with gradually closing window, especially for phonology and syntax."),
            ("The Sapir-Whorf (linguistic relativity) hypothesis claims:",
             ["Language has no effect on thought", "Language INFLUENCES thought (modern moderate version) — strong determinism is largely rejected", "Thought determines language entirely", "Languages are identical"], 1,
             "Modern research (Boroditsky) supports modest effects on perception and memory; strong determinism is not supported."),
            ("Charles Spearman's 'g' refers to:",
             ["Multiple unrelated abilities", "GENERAL intelligence — a common factor across diverse cognitive tests, identified by factor analysis (1904)", "Emotional intelligence", "Crystallized only"], 1,
             "Spearman observed positive manifold (correlations among cognitive tests). Modern hierarchical models (CHC) include g at the top."),
            ("Howard Gardner's Theory of Multiple Intelligences (1983) proposes:",
             ["A single 'g' factor", "Multiple relatively independent intelligences (linguistic, logical-mathematical, spatial, musical, bodily-kinesthetic, interpersonal, intrapersonal, naturalistic)", "Only IQ matters", "Two intelligences"], 1,
             "Gardner's theory is influential in education but lacks strong psychometric support; many psychologists view his 'intelligences' as overlapping with 'g' or as talents."),
            ("Robert Sternberg's TRIARCHIC theory distinguishes:",
             ["Only 'g'", "Analytical, Creative, and Practical intelligence", "Crystallized only", "Two types only"], 1,
             "Sternberg argues real-world success draws on practical intelligence beyond analytical IQ tests."),
            ("Alfred Binet & Théodore Simon (1905) developed:",
             ["The first modern personality test", "The first widely used INTELLIGENCE test (Binet-Simon scale) to identify Paris schoolchildren needing extra help", "Operant conditioning", "The Rorschach"], 1,
             "Mental age concept (Binet); William Stern proposed IQ = MA/CA × 100 (1912). Modern Wechsler uses deviation IQ."),
            ("The FLYNN effect refers to:",
             ["Falling IQ scores worldwide", "RISING average IQ scores (~3 points/decade through 20th century in industrialized countries) requiring periodic re-norming of tests", "Stable IQ scores forever", "Genetic IQ decline"], 1,
             "James Flynn documented secular IQ rises; recent data suggest the trend has slowed or reversed in some countries."),
            ("On the AP Psych exam, a question about a child whose IQ score on the WISC is at the population mean expects:",
             ["IQ = 70", "IQ = 100 (mean of standard IQ tests, SD = 15)", "IQ = 200", "IQ varies by test"], 1,
             "Modern Wechsler/Stanford-Binet are normed to mean 100, SD 15."),
            ("Which AP-style claim is correct?",
             ["IQ is fixed at birth and predicts everything", "IQ is moderately heritable but influenced by environment (education, nutrition); it predicts academic and some occupational outcomes but is not the only valuable cognitive ability", "IQ is meaningless", "IQ is purely environmental"], 1,
             "Modern view treats IQ as a useful but partial measure; group differences are heavily influenced by environmental factors."),
        ],
    },

    "motivation-theories": {
        "title": "Motivation Theories",
        "prefix": "mot",
        "qs": [
            ("INSTINCT theory (early 20th century, James, McDougall) explained motivation by:",
             ["Learned habits", "Innate, fixed action patterns shared by a species — fell out of favor as 'instincts' multiplied without explanation", "Reinforcement schedules", "Cognitive appraisal"], 1,
             "Instinct theory was largely abandoned as the list of named instincts ballooned past 6,000 with little predictive value."),
            ("DRIVE-REDUCTION theory (Hull 1943) holds that:",
             ["Motivation is purely external", "Physiological NEEDS create drives that organisms are motivated to REDUCE, restoring homeostasis", "All behavior is innate", "Drives don't exist"], 1,
             "Drive reduction explains hunger and thirst well but not curiosity, exploration, or seeking arousal."),
            ("AROUSAL theory predicts performance is best at:",
             ["Maximum arousal", "An OPTIMAL (often moderate) level — Yerkes-Dodson law (1908): too low = bored; too high = anxious; optimal varies with task difficulty", "Zero arousal", "Random arousal"], 1,
             "Yerkes-Dodson: simple/well-learned tasks tolerate higher arousal; complex novel tasks need lower arousal."),
            ("Abraham Maslow's HIERARCHY of needs (1943) ranks (bottom to top):",
             ["Self-actualization first", "Physiological → Safety → Love/Belonging → Esteem → Self-Actualization (with self-transcendence sometimes added at top)", "Random order", "Just two levels"], 1,
             "Maslow's pyramid: lower needs typically must be at least partially met before higher ones become motivating, though the strict ordering is debated."),
            ("Self-Determination Theory (Deci & Ryan, 1985-) emphasizes three innate needs:",
             ["Food, water, sleep", "Autonomy, Competence, and Relatedness — supporting INTRINSIC motivation", "Money, fame, power", "Pleasure only"], 1,
             "SDT distinguishes intrinsic motivation (doing for its own sake) from extrinsic motivation, and warns of overjustification effects."),
            ("Hunger is regulated partly by the LATERAL hypothalamus (LH) and VENTROMEDIAL hypothalamus (VMH). Stimulation of the LH:",
             ["Stops eating", "Triggers eating (LH = 'on'); lesion of VMH causes overeating (VMH = 'off' satiety)", "Has no effect", "Causes sleep"], 1,
             "Classic dual-center model is simplified; modern view involves arcuate nucleus (NPY/POMC neurons) and many peripheral signals."),
            ("Hormones in eating regulation include:",
             ["Insulin only", "Ghrelin (stomach, ↑ hunger), leptin (fat cells, ↓ hunger), insulin, PYY", "Adrenaline only", "Melatonin only"], 1,
             "Leptin (Friedman 1994) signals long-term energy stores; ghrelin spikes before meals."),
            ("Set-point theory holds that:",
             ["Body weight is infinitely flexible", "Body has a 'set point' weight that homeostatic mechanisms defend (after dieting, basal metabolism drops; obesity may reflect upward drift of set point)", "Diets are easy", "Weight is purely behavioral"], 1,
             "Set-point partially explains why most diets fail long-term; the set point can shift over time with diet/exercise patterns."),
            ("Sexual motivation in humans involves:",
             ["Hormones only", "Hormonal influences (testosterone), neural circuits, and strong cognitive/cultural learning — far less rigidly tied to estrus than in many mammals", "Cognition only", "No biological factors"], 1,
             "Masters & Johnson (1966) human sexual response cycle. Hormones permit but learning shapes human sexual behavior."),
            ("Need for ACHIEVEMENT (nAch, McClelland 1953) is measured by:",
             ["A simple questionnaire", "Projective tests (TAT) and behavioral choice — high nAch individuals seek moderate challenges with feedback", "Brain scans only", "Reaction times"], 1,
             "McClelland's nAch research linked achievement motivation to economic development and entrepreneurial behavior."),
            ("Approach-approach, approach-avoidance, and avoidance-avoidance CONFLICTS (Lewin 1935) describe:",
             ["Reflexes", "Motivational conflicts between competing goals — avoidance-avoidance often produces vacillation/escape", "Hormonal cycles", "Sleep stages"], 1,
             "Kurt Lewin's field theory introduced conflict types still used in motivational psychology."),
            ("Intrinsic motivation can be undermined by EXCESSIVE external rewards — the:",
             ["Yerkes-Dodson effect", "OVERJUSTIFICATION effect (Lepper, Greene, Nisbett 1973)", "Drive reduction", "Set-point"], 1,
             "Children rewarded for an already-enjoyed activity later showed reduced interest — an important caution for incentive design."),
            ("On the AP Psych exam, a question about an athlete who performs poorly under intense pressure of a championship game tests:",
             ["Yerkes-Dodson law (over-arousal hurts complex performance)", "Drive reduction", "Maslow's hierarchy", "Set-point theory"], 0,
             "Inverted-U: high-pressure situations push arousal past the optimal point, especially for complex skills."),
            ("Which AP-style claim is correct?",
             ["A single theory explains all motivation", "Motivation is best explained by a combination of biological (hunger, hormones), cognitive (expectancies), social (incentives, modeling), and developmental factors", "Motivation is purely conscious", "Only Maslow's theory is supported"], 1,
             "Modern motivation science integrates multiple frameworks; AP Psych expects students to apply theories to scenarios."),
        ],
    },

    "emotion-stress": {
        "title": "Emotion & Stress",
        "prefix": "es",
        "qs": [
            ("The James-Lange theory (1884-1885) proposes:",
             ["Emotion causes bodily arousal", "Bodily AROUSAL comes FIRST and the emotion is our perception of that arousal ('we feel afraid because we tremble')", "Emotion and arousal are simultaneous", "Cognition produces all emotion"], 1,
             "James-Lange: stimulus → physiological response → labeled emotion. Critiqued because many emotions share similar arousal patterns."),
            ("The Cannon-Bard theory (1927) proposes:",
             ["Sequential", "SIMULTANEOUS arousal and emotional experience — both result from thalamic processing", "Cognition first", "Behavior first"], 1,
             "Cannon-Bard rejected James-Lange because (a) similar arousal accompanies different emotions and (b) arousal is too slow."),
            ("Schachter-Singer TWO-FACTOR theory (1962) holds emotion = ",
             ["Arousal alone", "Physiological AROUSAL + cognitive LABEL (interpretation of context)", "Cognition alone", "Reflex"], 1,
             "Schachter-Singer epinephrine experiment: same arousal interpreted as anger or euphoria depending on confederate's behavior."),
            ("Lazarus's COGNITIVE-MEDIATIONAL theory (1984) holds:",
             ["Arousal precedes appraisal", "APPRAISAL of an event determines the emotion (primary appraisal: threat? secondary: can I cope?)", "Emotion has no cognition", "Reflex only"], 1,
             "Lazarus debated Zajonc on whether emotion can occur without cognitive appraisal; both positions partly correct."),
            ("Zajonc (1980) argued:",
             ["All emotion requires cognition", "Some emotional responses occur WITHOUT conscious cognitive appraisal — the 'mere exposure effect' increases liking even with subliminal exposure", "No emotions are automatic", "Lazarus is fully wrong"], 1,
             "Zajonc-Lazarus debate. LeDoux's amygdala 'low road' (subcortical fear path) supports rapid pre-cognitive emotional responses."),
            ("Paul Ekman's research identified UNIVERSAL facial expressions for at least:",
             ["1 emotion", "6-7 basic emotions (happiness, sadness, anger, fear, surprise, disgust, contempt) recognized across cultures", "100 emotions", "0 emotions"], 1,
             "Ekman's cross-cultural studies (e.g., Fore of Papua New Guinea, 1972) supported universality of basic emotions."),
            ("The FACIAL FEEDBACK hypothesis (Strack et al. 1988) proposes:",
             ["Facial expressions reflect but don't cause emotion", "Facial muscle activity FEEDS BACK to influence felt emotion (holding a pen in teeth → mild positive mood) — weak/inconsistent in recent replications", "Faces are unrelated to emotion", "Only voice matters"], 1,
             "The classic pen-in-teeth study failed to replicate in a 2016 multi-lab effort, illustrating the replication crisis."),
            ("Hans Selye (1936) described the General Adaptation Syndrome (GAS) with three stages:",
             ["Inflammation only", "Alarm → Resistance → Exhaustion", "Cognitive appraisal stages", "Sleep stages"], 1,
             "GAS describes the body's stereotyped stress response; chronic stress wears down resistance into exhaustion."),
            ("The HPA axis releases ____ in response to stress:",
             ["Insulin", "Cortisol (from adrenal cortex, via hypothalamic CRH and pituitary ACTH)", "Melatonin", "Estrogen"], 1,
             "Acute cortisol mobilizes energy; chronic elevation suppresses immunity and damages hippocampus."),
            ("Chronic stress is associated with INCREASED risk of:",
             ["Better sleep", "Cardiovascular disease, suppressed immunity, depression, and impaired memory (hippocampal effects)", "Faster healing", "Lower cortisol"], 1,
             "Psychoneuroimmunology (Ader, Cohen) documents stress-immune links; chronic stress raises infection risk."),
            ("PROBLEM-FOCUSED vs EMOTION-FOCUSED coping (Lazarus & Folkman 1984):",
             ["Both target the body", "Problem-focused tries to change the stressor; emotion-focused tries to change one's emotional response — best choice depends on controllability", "They are identical", "Only one works"], 1,
             "Controllable stressors → problem-focused coping. Uncontrollable losses → emotion-focused coping."),
            ("The Type A behavior pattern (Friedman & Rosenman 1959) was originally linked to coronary disease; modern refinement points specifically to:",
             ["Time urgency alone", "HOSTILITY/anger as the toxic component, more than competitive drive or time urgency", "Ambition only", "Talkativeness"], 1,
             "Decades of follow-up studies refined Type A: hostility is the strongest cardiovascular risk component."),
            ("On the AP Psych exam, a question describing a roller-coaster rider on a first date who interprets racing heart as romantic attraction tests:",
             ["James-Lange", "Schachter-Singer two-factor theory (misattribution of arousal — Dutton & Aron 1974 bridge study)", "Cannon-Bard", "Facial feedback"], 1,
             "The bridge-misattribution study showed arousal from height was misattributed to attraction, supporting two-factor theory."),
            ("Which AP-style claim is correct?",
             ["Emotion is purely physiological", "Emotion involves an interaction of physiological arousal, cognitive appraisal, behavioral expression, and culture — captured by combining James-Lange, Cannon-Bard, two-factor, and appraisal theories", "Emotion is purely cognitive", "Cultures share no emotional features"], 1,
             "AP Psych emphasizes integrating multiple theories to explain emotional phenomena."),
        ],
    },

    "personality-theories": {
        "title": "Personality Theories",
        "prefix": "pt",
        "qs": [
            ("Freud's PSYCHOANALYTIC theory divides personality into:",
             ["Conscious and unconscious only", "Id (pleasure principle, unconscious), Ego (reality principle), Superego (conscience/ideal)", "Big Five traits", "Conditioning histories"], 1,
             "Freud's structural model (1923, The Ego and the Id). Ego mediates between id impulses and superego ideals using defense mechanisms."),
            ("DEFENSE mechanisms (e.g., REPRESSION) function to:",
             ["Increase anxiety", "Reduce ANXIETY by distorting reality unconsciously (repression, projection, displacement, sublimation, rationalization)", "Improve decision-making", "Replace memory"], 1,
             "Modern psychology retains the concept of unconscious defense (especially among ego-psychologists) though Freud's specific list is debated."),
            ("Carl Jung's analytical psychology added concepts including:",
             ["Operant conditioning", "The COLLECTIVE unconscious and ARCHETYPES (universal symbols), plus introversion/extraversion", "The Big Five", "Self-actualization"], 1,
             "Jung broke from Freud (1913). His introversion/extraversion construct survived and influences modern trait theory."),
            ("Alfred Adler emphasized:",
             ["Sexual conflicts", "Striving for superiority, social interest, and the influence of birth order — 'individual psychology'", "Reinforcement schedules", "Big Five"], 1,
             "Adler's neo-Freudian work emphasized social/family dynamics over Freud's sexual focus."),
            ("HUMANISTIC personality theory (Rogers, Maslow) emphasizes:",
             ["Unconscious conflicts", "The drive toward SELF-ACTUALIZATION; Rogers stressed UNCONDITIONAL POSITIVE REGARD as fostering congruence between self and ideal self", "Reinforcement", "Trait dimensions"], 1,
             "Rogers's client-centered therapy used genuineness, empathy, and unconditional positive regard."),
            ("The BIG FIVE (Five-Factor Model; Costa & McCrae) personality dimensions are (OCEAN):",
             ["Only neuroticism and extraversion", "Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism", "id, ego, superego", "Anxiety only"], 1,
             "Big Five emerged from factor analyses of trait words across many languages; replicated in many cultures."),
            ("Trait CONSCIENTIOUSNESS predicts:",
             ["Worse health and shorter life", "BETTER academic and job performance, longer life, healthier behaviors", "No outcomes", "Only popularity"], 1,
             "Conscientiousness has the strongest links of the Big Five to longevity (Friedman & Martin 'Longevity Project') and job performance (Barrick & Mount 1991)."),
            ("Walter Mischel (1968) Personality and Assessment challenged trait theory by arguing:",
             ["Traits are stable", "Behavior is highly SITUATION-specific; trait-behavior correlations are often only ~0.3 — sparking the person-situation debate", "Traits don't exist", "Only situations matter"], 1,
             "Modern resolution: traits and situations both matter; aggregated behavior across situations shows substantial trait stability."),
            ("Bandura's RECIPROCAL DETERMINISM (social cognitive theory) holds that personality emerges from interactions among:",
             ["Genes only", "Personal factors (cognition, beliefs), Behavior, and Environment — each influences the others", "Reinforcement only", "Unconscious only"], 1,
             "Reciprocal determinism integrates internal and external factors and emphasizes self-efficacy."),
            ("Locus of CONTROL (Rotter 1966):",
             ["Always external", "INTERNAL locus = belief one's outcomes depend on own efforts; EXTERNAL = depend on luck/fate; internal generally linked to better outcomes", "Always internal", "Identical to self-efficacy"], 1,
             "Internal locus of control is associated with better health behaviors, academic achievement, and well-being on average."),
            ("PROJECTIVE personality tests (Rorschach 1921; TAT — Murray 1943):",
             ["Have strong psychometric support", "Show generally weak reliability and validity by modern standards; mainstream personality assessment relies on self-report inventories like the MMPI-2 or NEO-PI-R", "Are required in research", "Only use ink blots"], 1,
             "Lilienfeld et al. critiqued projective tests; only a few Rorschach scales meet psychometric standards."),
            ("The MMPI-2 (Minnesota Multiphasic Personality Inventory) is:",
             ["Projective", "An empirically keyed self-report inventory widely used in clinical assessment, with VALIDITY scales detecting faking", "Free response", "Brain imaging"], 1,
             "MMPI was developed by Hathaway & McKinley (1943) using the criterion-keying method. MMPI-2 (1989) updated norms; MMPI-3 released 2020."),
            ("On the AP Psych exam, a question about a long-term personality study finding strong stability of conscientiousness from age 20 to 60 supports:",
             ["Mischel's situational view", "Trait theory and the Big Five — traits show meaningful long-term stability while still allowing change", "Freud's stages", "Psychoanalysis"], 1,
             "Roberts et al. meta-analyses show meaningful trait stability with gradual maturation (greater conscientiousness, agreeableness, lower neuroticism with age)."),
            ("Which AP-style claim is correct?",
             ["Personality is fixed and unconscious", "Modern personality science integrates traits (Big Five), social-cognitive factors (efficacy, locus of control), and biological influences; traits are stable but malleable, with strong predictive validity for life outcomes", "Personality is purely behavioral", "Projective tests are gold standard"], 1,
             "AP Psych frames personality as multi-level and empirically grounded in trait research and social-cognitive theory."),
        ],
    },
}

if __name__ == "__main__":
    write_batch(T, EXPECTED)
