#!/usr/bin/env python3
"""
AAS entrance quizzes — Batch 1 (5 topics):
  aas-origins-diaspora, aas-african-kingdoms, aas-transatlantic-slave-trade,
  aas-slavery-in-america, aas-resistance-abolition
"""
from __future__ import annotations
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _aas_quiz_common import write_batch  # type: ignore

T: dict = {}

# ────────────────────────────────────────────────────────────────────────────
# 1. Origins of the African Diaspora
# ────────────────────────────────────────────────────────────────────────────
T["aas-origins-diaspora"] = {
    "title": "Origins of the African Diaspora",
    "prefix": "aasod",
    "qs": [
        # Part 1 — Core Concepts
        ("In AP African American Studies, the term \"African Diaspora\" refers to:",
         ["The voluntary migration of Europeans into Africa during the colonial era.",
          "The dispersal of Africans and their descendants worldwide, primarily through the transatlantic and Indian Ocean slave trades.",
          "The internal migration of West Africans across the Sahara before 1500.",
          "The post-1965 migration of African students to U.S. universities."],
         1,
         "The African Diaspora describes the global dispersal of Africans and their descendants — most consequentially via the transatlantic slave trade (c. 1500–1866) — and the cultures they built in the Americas, Europe, and the Indian Ocean world."),
        ("The phrase \"Black Atlantic,\" coined by sociologist Paul Gilroy in 1993, emphasizes that:",
         ["African and African-diasporic cultures developed in isolation from Europe and the Americas.",
          "African American culture was shaped by a continuous transatlantic exchange of people, ideas, and music linking Africa, Europe, the Caribbean, and the Americas.",
          "The Atlantic Ocean was a barrier that prevented cultural contact between Africa and the Americas.",
          "Black identity is rooted exclusively in the United States after 1865."],
         1,
         "Paul Gilroy's *The Black Atlantic* (1993) reframed Black identity as a transnational, oceanic culture forged by movement — voluntary and forced — across the Atlantic basin."),
        # Part 2 — Key Processes
        ("Which of the following best describes the four main streams of the African Diaspora before 1900?",
         ["Trans-Saharan, Indian Ocean, Red Sea, and transatlantic.",
          "Pacific, Arctic, Mediterranean, and trans-Saharan.",
          "Trans-Saharan, Mississippi, Congo, and Rhine.",
          "Indian Ocean, Hudson Bay, Mediterranean, and trans-Pacific."],
         0,
         "Historians (e.g., Patrick Manning, *African Diaspora: A History Through Culture*, 2009) identify four major slave-trade streams: trans-Saharan (c. 650–1900), Red Sea, Indian Ocean (East Africa to Arabia/India), and the transatlantic trade (c. 1500–1866)."),
        ("In the AP framework, \"diasporic identity\" most often refers to:",
         ["A nationality assigned by the country of birth alone.",
          "The double-consciousness of belonging both to the country of residence and to a wider African heritage, as theorized by W. E. B. Du Bois in *The Souls of Black Folk* (1903).",
          "A purely religious affiliation with no cultural component.",
          "A legal classification used in the 1790 U.S. Naturalization Act."],
         1,
         "Du Bois's \"double-consciousness\" — the sense of \"two-ness\" of being both American and Black/African — anchors the AP unit's discussion of diasporic identity."),
        # Part 3 — Patterns & Examples
        ("Which dated example best illustrates the geographic breadth of the African Diaspora in the Americas?",
         ["By 1820, roughly 4 million enslaved Africans had been forcibly transported to Brazil, more than ten times the number sent to British North America.",
          "By 1820, the largest enslaved African population in the Americas lived in Canada.",
          "By 1820, the transatlantic slave trade had not yet reached Brazil.",
          "By 1820, the United States had imported more enslaved Africans than every other American destination combined."],
         0,
         "Per the Trans-Atlantic Slave Trade Database (Eltis & Richardson, 2010), Brazil received ~4–5 million captives — about 40% of all transatlantic arrivals — versus ~388,000 to British North America/U.S. (~3.6%)."),
        ("Which named region was a major Indian Ocean diaspora destination?",
         ["Iceland, where enslaved Africans staffed Norse settlements after 1500.",
          "The Persian Gulf and western India, where the Siddi communities of Gujarat and Karnataka descend from East African captives transported via the Indian Ocean trade.",
          "Mongolia, where the Yuan dynasty imported East African captives in the 1300s.",
          "Greenland, which received West African captives via the Spanish in the 1600s."],
         1,
         "The Siddi/Sheedi communities of South Asia (modern India and Pakistan) descend from East Africans transported across the Indian Ocean — a recognized non-Atlantic diaspora stream."),
        # Part 4 — Connections & Interactions
        ("How does the Origins unit best connect to the African Kingdoms unit?",
         ["The Origins unit treats Africa as historyless before 1500; the Kingdoms unit ignores it.",
          "The Diaspora's source societies — Mali, Songhai, Kongo, Benin, Yoruba city-states — were politically and culturally sophisticated long before contact, shaping the religions, languages, and skills enslaved Africans brought to the Americas.",
          "The two units cover identical material with no meaningful overlap.",
          "The Kingdoms unit exclusively concerns East Africa while Origins concerns only North America."],
         1,
         "AP synthesis prompts ask students to connect specific African polities (Kongo Catholicism, Yoruba Ifá, Mande griot traditions) to retentions in the Americas (Vodou, Candomblé, ring shouts)."),
        ("Which AP analytical skill is foregrounded when comparing the trans-Saharan trade to the transatlantic trade?",
         ["Memorization without analysis.",
          "Comparison: identifying both shared features (forced labor, gendered patterns) and differences (scale, racialization, plantation chattel slavery).",
          "Quotation without context.",
          "Listing without thesis."],
         1,
         "AP rewards explicit comparison: similarities (slavery existed in both) and differences (transatlantic was racialized, hereditary, plantation-based, and far larger in volume per century after 1700)."),
        # Part 5 — Change Over Time
        ("Which event marked a major change in the volume of the transatlantic diaspora?",
         ["The opening of the Suez Canal in 1869 doubled the slave trade.",
          "After the British Slave Trade Act of 1807 and the U.S. Act Prohibiting Importation of Slaves of 1808, transatlantic shipments shifted south to Brazil and Cuba, peaking c. 1820–1850 before suppression by the British West Africa Squadron.",
          "The Treaty of Tordesillas (1494) ended all transatlantic slaving.",
          "The American Revolution (1776) abolished the slave trade worldwide."],
         1,
         "1807/08 abolition of the *trade* (not slavery) by Britain and the U.S. shifted the bulk of transatlantic shipments to Brazil and Cuba, where it persisted until the 1860s under British naval suppression."),
        ("Which best describes a continuity across the early African Diaspora?",
         ["Enslaved Africans abandoned all African cultural practices on arrival.",
          "Despite forced separation by language and ethnicity, captives created new syncretic cultures — Gullah, Creole, Vodou, Candomblé, Lucumí — that retained African religious, musical, linguistic, and culinary elements.",
          "African cultural retention is not a topic recognized by historians.",
          "All diasporic communities adopted identical European customs."],
         1,
         "Cultural retention and creolization are central AP themes — see Sterling Stuckey, *Slave Culture* (1987), and Sidney Mintz & Richard Price, *The Birth of African American Culture* (1976)."),
        # Part 6 — Problem-Solving Workshop
        ("A historian wants to estimate how many enslaved Africans arrived in a given American port between 1700 and 1800. Which source is most directly useful?",
         ["The 1903 *Souls of Black Folk*, a sociological essay collection.",
          "The Trans-Atlantic Slave Trade Database (slavevoyages.org), an open-source compilation of ~36,000 documented voyages with origin, destination, and captive counts.",
          "Modern population census data from 2020.",
          "An undated personal letter with no provenance."],
         1,
         "The Trans-Atlantic Slave Trade Database (David Eltis, David Richardson, et al.) is the standard quantitative source on voyage volume, mortality, and routes."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point on a diaspora prompt?",
         ["Quoting a source verbatim without comment.",
          "Identifying the author, audience, purpose, or historical situation of the source — and using it to support a claim (e.g., noting that Olaudah Equiano's 1789 *Interesting Narrative* was written for a British abolitionist audience).",
          "Citing only secondary sources and ignoring all primary documents.",
          "Listing the date of the source without analysis."],
         1,
         "AP DBQ rubrics award sourcing when the student explains *why* author/audience/purpose/situation matters for a specific claim — not just citing it."),
        # Part 7 — AP Review
        ("Which is the strongest one-sentence thesis for an essay on the origins of the African Diaspora?",
         ["The African Diaspora was important.",
          "Between roughly 1500 and 1866, the transatlantic slave trade — alongside the older trans-Saharan and Indian Ocean trades — forcibly dispersed more than 12 million Africans across the globe, producing creolized cultures that retained African religious, linguistic, and musical practices even under chattel slavery.",
          "Nothing meaningful happened during the transatlantic slave trade.",
          "African Americans have no cultural ties to Africa."],
         1,
         "Strong AP theses combine a periodized claim, scale (numbers/dates), causation, and a complexity move (retention under chattel slavery)."),
        ("Which AP-skill move is most rewarded when writing about the Origins unit?",
         ["Listing names without analysis.",
          "Combining a clear thesis with at least one named figure (e.g., Olaudah Equiano), one dated event (e.g., 1808 U.S. trade ban), and one primary source (e.g., the *Interesting Narrative*).",
          "Citing only 21st-century pop culture for events before 1800.",
          "Avoiding all dates and names."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, primary sources — tied to a defensible thesis."),
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# 2. African Kingdoms & Civilizations (c. 700–1600)
# ────────────────────────────────────────────────────────────────────────────
T["aas-african-kingdoms"] = {
    "title": "African Kingdoms & Civilizations (c. 700–1600)",
    "prefix": "aasak",
    "qs": [
        # Part 1
        ("Which best captures the historical significance of the West African empires of Ghana, Mali, and Songhai?",
         ["They were small, isolated polities with no long-distance trade.",
          "From roughly 300 to 1591 CE they controlled the trans-Saharan gold–salt trade, sustained large literate Muslim cities (Timbuktu, Djenné, Gao), and rivaled contemporary European states in wealth and scale.",
          "They existed only after 1700 and never participated in long-distance trade.",
          "They were colonies founded by Portugal in the 1500s."],
         1,
         "Ghana (c. 300–1076), Mali (c. 1235–1600), and Songhai (c. 1464–1591) successively dominated the trans-Saharan gold–salt trade and supported major centers of Islamic scholarship."),
        ("In the AP framework, the term \"trans-Saharan trade\" refers to:",
         ["A modern free-trade agreement signed in 1994.",
          "Camel-caravan networks crossing the Sahara that connected West African gold and ivory to North African and Mediterranean markets, exchanging gold and enslaved people southbound for salt, copper, cloth, and Islamic scholarship.",
          "Maritime trade across the Pacific Ocean.",
          "Internal river trade entirely within the Congo basin."],
         1,
         "Trans-Saharan trade (peaking c. 800–1500) used camel caravans to link sub-Saharan Africa with the Maghreb and the wider Mediterranean/Islamic world."),
        # Part 2
        ("Which named figure founded the Mali Empire?",
         ["Mansa Musa, who ruled 1312–1337.",
          "Sundiata Keita, who defeated the Sosso king Sumanguru at the Battle of Kirina (c. 1235) — events preserved in the orally transmitted *Epic of Sundiata*.",
          "Askia Muhammad, ruler of Songhai 1493–1528.",
          "Sonni Ali, founder of Songhai's military expansion in the 1460s."],
         1,
         "Sundiata Keita (r. c. 1235–1255) founded the Mali Empire after defeating Sumanguru at Kirina; his story survives in the griot-transmitted *Epic of Sundiata*."),
        ("Mansa Musa's 1324 hajj is historically significant because:",
         ["It established the first Christian pilgrimage route to Mecca.",
          "His distribution of so much gold in Cairo reportedly destabilized Egyptian currency for roughly a decade and placed Mali on European maps such as the 1375 Catalan Atlas.",
          "It marked Mali's military conquest of Egypt.",
          "It ended the trans-Saharan trade in 1324."],
         1,
         "Mansa Musa's hajj (1324) demonstrated Mali's wealth on a global stage; the Catalan Atlas (1375) depicts him holding a gold nugget."),
        # Part 3
        ("Which dated polity is most associated with stone-built urbanism in southeastern Africa?",
         ["The Aztec Empire, c. 1428–1521.",
          "Great Zimbabwe (c. 1100–1450), whose dry-stone enclosures housed an estimated 18,000 people and controlled gold trade with Swahili coast cities such as Sofala and Kilwa.",
          "The Mongol Empire, c. 1206–1368.",
          "The Roman Republic, c. 509 BCE."],
         1,
         "Great Zimbabwe (c. 1100–1450) was a major Shona stone-built capital connected via Sofala to Indian Ocean trade; \"Zimbabwe\" derives from *dzimba dzemabwe* (\"houses of stone\")."),
        ("The Swahili coast city-states (c. 800–1500) are best characterized by:",
         ["A landlocked agricultural economy with no ocean trade.",
          "An archipelago of cosmopolitan port cities — Kilwa, Mombasa, Lamu, Mogadishu — whose Swahili language fused Bantu grammar with Arabic vocabulary and whose wealth came from Indian Ocean trade in gold, ivory, and enslaved people.",
          "A unified empire ruled from Cairo until 1600.",
          "Inland mining settlements with no contact with Asia."],
         1,
         "Swahili (\"coastal\") city-states from Mogadishu to Kilwa were Bantu-Muslim port cities integrated into the Indian Ocean trade with Arabia, Persia, and India; Kilwa's Husuni Kubwa palace dates to c. 1310."),
        # Part 4
        ("How do the African Kingdoms connect to the Origins of the Diaspora unit?",
         ["The kingdoms had no relation to later Atlantic slaving.",
          "Kingdoms such as Kongo (Christianized after 1491), Asante, Dahomey, and Oyo were direct participants in — and sometimes targets of — the Atlantic slave trade, shaping which African ethnicities and cultures were transported to specific American regions.",
          "All West African polities collapsed before any Atlantic contact.",
          "The kingdoms exported only gold, never people."],
         1,
         "Kongo's 1491 conversion to Catholicism, Asante and Dahomey's role in the trade, and Yoruba dispersal from Oyo's collapse (c. 1830s) directly shaped Atlantic diaspora cultures (e.g., Yoruba Ifá → Cuban Lucumí, Haitian Vodou)."),
        ("Which AP analytical skill is most directly tested by comparing Mali to Songhai?",
         ["Periodization without comparison.",
          "Comparison: identifying both continuities (Islamic scholarship at Timbuktu, gold–salt trade, Niger River basin) and changes (Songhai's larger territorial reach under Askia Muhammad, replaced by Moroccan invasion at Tondibi 1591).",
          "Free recall of unrelated facts.",
          "Citing only modern sources."],
         1,
         "AP comparison rewards explicit similarity *and* difference statements with named actors and dates (e.g., Tondibi 1591 ended Songhai)."),
        # Part 5
        ("Which event marked a decisive change for West African empires?",
         ["The Treaty of Versailles (1919).",
          "The 1591 Battle of Tondibi, where a Moroccan army equipped with arquebuses defeated Songhai's much larger force, fragmenting the last great Sahelian empire.",
          "The fall of Constantinople in 1453.",
          "The Glorious Revolution of 1688."],
         1,
         "Tondibi (1591) — Moroccan firearms versus Songhai cavalry — collapsed Songhai and ended the era of Sahelian super-empires built on trans-Saharan gold."),
        ("Which best describes a continuity across the African Kingdoms unit (c. 700–1600)?",
         ["African societies had no political institutions before European contact.",
          "Across Ghana, Mali, Songhai, Kongo, Benin, and the Swahili city-states, long-distance trade (gold, salt, ivory, enslaved people) supported centralized rulers, urban scholarship, and craft production over centuries.",
          "All African polities were nomadic and acephalous.",
          "Political centralization began only after 1600."],
         1,
         "Continuity = trade-financed centralized states with literate religious–legal institutions, persisting across multiple successive empires before 1600."),
        # Part 6
        ("Which primary source is most useful for studying the Mali Empire firsthand?",
         ["The 2010 U.S. Census.",
          "Ibn Battuta's *Rihla* (Travels), c. 1355, which records his 1352–1353 visit to Mali under Mansa Sulayman, including descriptions of court ceremony, judicial practice, and Islamic life.",
          "A 21st-century novel set in pre-Columbian America.",
          "A 1980 Cold War policy memo."],
         1,
         "Ibn Battuta (1304–1369) visited Mali in 1352–53; his *Rihla* is the principal eyewitness Arabic-language source on 14th-century Mali."),
        ("Which DBQ sourcing move would earn the AP \"sourcing\" point on an Ibn Battuta excerpt?",
         ["Quoting it without comment.",
          "Noting that Ibn Battuta was a Muslim Moroccan jurist whose audience was a literate Islamic court — and using that to evaluate his sometimes-critical view of Malian women's public roles or non-Islamic practices.",
          "Citing only the page number with no analysis.",
          "Ignoring the author's perspective entirely."],
         1,
         "AP sourcing requires *use* of audience/purpose/situation — Ibn Battuta's elite Islamic perspective shapes which Malian practices he praises or critiques."),
        # Part 7
        ("Which is the strongest one-sentence thesis for an essay on African Kingdoms?",
         ["African kingdoms were rich.",
          "Between roughly 700 and 1600 CE, successive West African empires — Ghana, Mali, and Songhai — and East African Swahili city-states built large, literate, and commercially sophisticated states whose trade networks integrated sub-Saharan Africa into the Islamic and Indian Ocean worlds long before European Atlantic contact.",
          "Nothing politically significant happened in Africa before 1500.",
          "African societies are not a topic for AP essays."],
         1,
         "Strong AP theses combine periodization, named polities, scale (trade networks), and a complexity move (predating European contact)."),
        ("On the AP exam, the strongest move when writing about African Kingdoms is to:",
         ["Use only modern examples for medieval claims.",
          "Anchor each claim in a named figure (Sundiata, Mansa Musa, Askia Muhammad), a dated event (1235 Kirina, 1324 hajj, 1591 Tondibi), and a primary source (*Epic of Sundiata*, Ibn Battuta's *Rihla*, the Catalan Atlas).",
          "Avoid all dates and names.",
          "Cite only 21st-century newspaper articles."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# 3. Transatlantic Slave Trade
# ────────────────────────────────────────────────────────────────────────────
T["aas-transatlantic-slave-trade"] = {
    "title": "Transatlantic Slave Trade",
    "prefix": "aastst",
    "qs": [
        # Part 1
        ("In AP African American Studies, the \"Middle Passage\" refers specifically to:",
         ["The land journey across the Sahara from Mali to Morocco.",
          "The forced oceanic voyage transporting captive Africans from West and West-Central Africa to the Americas — one leg of the broader triangular Atlantic trade.",
          "The voyage of European migrants from Britain to the New England colonies.",
          "The travel of returning African Americans to Liberia in the 1820s."],
         1,
         "The Middle Passage (\"middle\" because it was the second leg of the triangular trade: Europe→Africa→Americas→Europe) was the forced transatlantic voyage of captives."),
        ("The \"triangular trade\" of the 17th–18th centuries refers to:",
         ["A purely overland route between Egypt, Carthage, and Rome.",
          "The interconnected circuit by which European manufactured goods (textiles, iron, firearms, rum) were exchanged for African captives, who were transported to the Americas to produce sugar, tobacco, and rice for export back to Europe.",
          "A shipping route connecting only India, China, and Japan.",
          "A Pacific trade among California, Hawaii, and the Philippines."],
         1,
         "The triangular trade tied European industry, African captive labor, and American plantation production into a single Atlantic system from c. 1500 to 1866."),
        # Part 2
        ("Which named law or treaty marked the official end of the legal U.S. transatlantic slave trade?",
         ["The Compromise of 1850.",
          "The Act Prohibiting Importation of Slaves (1807, effective January 1, 1808), passed under President Jefferson per Article I, §9 of the Constitution.",
          "The Missouri Compromise (1820).",
          "The Kansas-Nebraska Act (1854)."],
         1,
         "The 1807 Act, effective January 1, 1808, criminalized further importation; smuggling persisted, and the domestic interstate slave trade continued and expanded until 1865."),
        ("Which figure led the British abolitionist parliamentary campaign against the slave trade?",
         ["Frederick Douglass, a U.S. former-slave abolitionist.",
          "William Wilberforce, who campaigned in Parliament from 1787 until passage of the Slave Trade Act of 1807; aided by Thomas Clarkson's investigative work and the Quaker-led Society for Effecting the Abolition of the Slave Trade (founded 1787).",
          "Toussaint Louverture, leader of the Haitian Revolution.",
          "John Brown, who led the 1859 Harpers Ferry raid."],
         1,
         "Wilberforce's parliamentary leadership, alongside Clarkson's evidence-gathering and the Quaker-founded 1787 abolition society, drove the 1807 British Slave Trade Act."),
        # Part 3
        ("Which dated estimate best reflects scholarly consensus on the scale of the transatlantic slave trade?",
         ["About 100,000 captives total were transported between 1500 and 1866.",
          "Roughly 12.5 million Africans were embarked and about 10.7 million disembarked in the Americas between 1501 and 1866 — with mortality of ~12–15 percent during the Middle Passage.",
          "About 50 million captives were transported in a single decade.",
          "About 500 captives total were transported, all to North America."],
         1,
         "Per the Trans-Atlantic Slave Trade Database (Eltis & Richardson): ~12.5M embarked, ~10.7M disembarked; ~12–15% mortality at sea."),
        ("Which best characterizes the regional distribution of disembarkations?",
         ["Roughly 95 percent of captives went to the United States.",
          "Brazil received ~40–45 percent and the Caribbean ~40 percent (Saint-Domingue, Jamaica, Cuba, Barbados); only ~3.6 percent (~388,000) went to British North America/the U.S.",
          "Roughly half went to Canada and Iceland.",
          "Roughly equal numbers went to all American regions."],
         1,
         "Brazil and the Caribbean received the overwhelming majority; the U.S. received a small but demographically self-reproducing share — a pattern central to AP comparative arguments."),
        # Part 4
        ("How does the transatlantic trade unit connect to the African Kingdoms unit?",
         ["The kingdoms had no role in the trade.",
          "Coastal African polities — Asante, Dahomey, Oyo, Kongo — actively supplied captives, while the destabilization of inland states (Kongo civil wars, Oyo's c. 1830s collapse) reflected and accelerated the trade's violence.",
          "Only Europeans participated in the trade with no African agents.",
          "All African states refused to participate at any point."],
         1,
         "AP synthesis prompts ask students to recognize African political agency in the trade — coastal polities profited; inland societies were raided; and African resistance also shaped its course (e.g., Queen Nzinga of Ndongo, r. 1624–1663)."),
        ("Which historical economic concept is most associated with the Atlantic slave trade?",
         ["Mercantilism — state-backed European trading companies (Royal African Company chartered 1672; Dutch West India Company 1621) sought to monopolize transatlantic flows of captives, sugar, and bullion to enrich the metropole.",
          "Keynesian demand management.",
          "21st-century cryptocurrency speculation.",
          "Soviet five-year planning."],
         0,
         "AP courses connect the trade to mercantilism: chartered monopolies (RAC, Dutch WIC), Navigation Acts, and the bullionist logic that drove European Atlantic expansion."),
        # Part 5
        ("Which best describes a major change in the trade between c. 1500 and 1866?",
         ["The trade was constant in volume across all four centuries.",
          "Volume rose from a Portuguese-dominated trickle in the 1500s, peaked in the 1700s under British, French, and Portuguese carriers, then shifted south to Brazil and Cuba after the 1807–1808 abolitions until British naval suppression and Brazil's 1850 Eusébio de Queirós Law.",
          "The trade ended in 1500 and never resumed.",
          "Volume declined steadily every decade from 1500 to 1866."],
         1,
         "The Atlantic trade peaked in the late 18th century; after 1807/08 it shifted to Brazil and Cuba, suppressed by the British West Africa Squadron and Brazil's 1850 Eusébio de Queirós Law."),
        ("Which best describes a continuity of the Middle Passage experience?",
         ["Captives were always treated humanely with low mortality.",
          "Across centuries, captives endured tight-packed holds, chained confinement, sexual violence, and ~12–15 percent mortality from disease, suicide, and shipboard violence — conditions described by Olaudah Equiano (1789) and visualized in the *Brookes* slave-ship diagram (1788).",
          "Captives traveled freely on deck with no restraints.",
          "Mortality was zero across all voyages."],
         1,
         "Continuity = brutal shipboard conditions and high mortality, documented in survivor narratives (Equiano 1789) and abolitionist iconography (the *Brookes* diagram, 1788)."),
        # Part 6
        ("A historian wants to estimate Middle Passage mortality on a specific 1750 voyage. Which source is most directly useful?",
         ["A 21st-century novel set in the Caribbean.",
          "The Trans-Atlantic Slave Trade Database voyage record, which compiles ship logs, customs records, and captain's accounts to report embarked/disembarked counts and mortality per voyage.",
          "A 1960 economics textbook with no primary data.",
          "An undated personal blog post."],
         1,
         "The Trans-Atlantic Slave Trade Database aggregates ship-level data (logs, ledgers, port records) and is the standard quantitative source for voyage-specific analysis."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point when using Olaudah Equiano's *Interesting Narrative* (1789)?",
         ["Quoting Equiano without comment.",
          "Noting that Equiano wrote for a British abolitionist audience during the parliamentary campaign, and using that purpose to evaluate his vivid Middle Passage testimony as both eyewitness account and abolitionist persuasion.",
          "Listing only the publication date with no analysis.",
          "Citing only modern secondary sources."],
         1,
         "AP DBQ sourcing rewards using author/audience/purpose/situation to *evaluate* a source — Equiano's abolitionist purpose is essential context for his Middle Passage chapter."),
        # Part 7
        ("Which is the strongest one-sentence thesis on the transatlantic slave trade?",
         ["The slave trade was bad.",
          "Between 1501 and 1866, an estimated 12.5 million Africans were forcibly embarked across the Atlantic — the largest forced migration in human history — sustained by mercantilist European empires and coastal African polities, and ended only after sustained Black resistance, abolitionist organizing, and British naval suppression.",
          "Nothing important happened during the transatlantic slave trade.",
          "The slave trade had no measurable economic consequences."],
         1,
         "Strong AP theses combine scale (12.5M), periodization (1501–1866), causation (mercantilism + African coastal politics), and a complexity move (resistance + abolition driving its end)."),
        ("On the AP exam, the strongest move when writing about the slave trade is to:",
         ["Avoid all dates and named actors.",
          "Anchor claims in a named figure (Equiano, Wilberforce, Queen Nzinga), a dated event (1788 *Brookes*, 1807/08 abolitions, 1850 Eusébio de Queirós Law), and a primary source (Equiano's *Interesting Narrative*, the *Brookes* diagram).",
          "Cite only 21st-century pop culture references.",
          "Use only round numbers without sources."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# 4. Slavery in America
# ────────────────────────────────────────────────────────────────────────────
T["aas-slavery-in-america"] = {
    "title": "Slavery in America",
    "prefix": "aassia",
    "qs": [
        # Part 1
        ("Which best describes \"chattel slavery\" as practiced in the Americas?",
         ["A temporary indentured contract that ended after seven years.",
          "A racialized, hereditary system in which enslaved people were defined as movable property under law, transferable by sale, gift, or inheritance, with status passed through the mother (*partus sequitur ventrem*).",
          "A communal labor obligation owed to the king for one season.",
          "A guild apprenticeship paid in wages."],
         1,
         "Chattel slavery — codified in colonies such as Virginia's 1662 *partus sequitur ventrem* law — defined enslaved people as inheritable property and made enslavement matrilineal."),
        ("Virginia's 1662 *partus sequitur ventrem* statute mattered because:",
         ["It freed all children born to enslaved women.",
          "It made the legal status of a child follow the mother's status, which permanently embedded slavery as a hereditary, racialized institution and incentivized the sexual exploitation of enslaved women.",
          "It applied only to indentured European servants.",
          "It abolished slavery in Virginia."],
         1,
         "By making children of enslaved women enslaved at birth, the 1662 law converted slavery into a hereditary, racialized, and self-reproducing system."),
        # Part 2
        ("Which 1808 federal law ended legal U.S. participation in the international slave trade — but did not end slavery itself?",
         ["The Northwest Ordinance of 1787.",
          "The Act Prohibiting Importation of Slaves (passed 1807, effective January 1, 1808), which closed the legal Atlantic trade but spurred the expansion of the *domestic* interstate slave trade.",
          "The Compromise of 1850.",
          "The Emancipation Proclamation (1863)."],
         1,
         "The 1808 ban closed the international trade but the *internal* slave trade — moving roughly 1 million enslaved people from the Upper South to the Cotton Belt — expanded sharply."),
        ("Which technology most accelerated the expansion of cotton slavery in the U.S. South after 1793?",
         ["The steam locomotive.",
          "Eli Whitney's cotton gin (1793), which mechanized the separation of seeds from short-staple cotton fiber, making upland cotton commercially viable across the Deep South.",
          "The telegraph (1844).",
          "The Bessemer steel process (1856)."],
         1,
         "Whitney's cotton gin (1793) transformed short-staple upland cotton into a profitable cash crop, fueling the Cotton Kingdom's expansion across Alabama, Mississippi, Louisiana, and Texas."),
        # Part 3
        ("Which dated event illustrates the geographic expansion of U.S. slavery?",
         ["The Louisiana Purchase (1803), which roughly doubled U.S. territory and opened vast new lands — including future Arkansas, Missouri, and Louisiana sugar parishes — to plantation slavery.",
          "The 1620 Mayflower landing.",
          "The 1607 founding of Jamestown.",
          "The Treaty of Tordesillas (1494)."],
         0,
         "The Louisiana Purchase (1803) doubled the national territory and made possible the cotton-and-sugar expansion of the Deep South over the next half-century."),
        ("Which best characterizes the demography of U.S. slavery on the eve of the Civil War?",
         ["About 100,000 enslaved people lived in the South in 1860.",
          "The 1860 U.S. Census enumerated about 3.95 million enslaved people, roughly one-third of the South's population, concentrated in the cotton, sugar, rice, and tobacco belts.",
          "Slavery had effectively ended in the South by 1860.",
          "Enslaved people were a tiny fraction (under 1 percent) of the Southern population."],
         1,
         "Per the 1860 Census, ~3.95 million enslaved people lived in the U.S. — roughly one-third of the South's population and a majority in states such as South Carolina and Mississippi."),
        # Part 4
        ("How does the Slavery in America unit connect to the Resistance & Abolition unit?",
         ["The two units cover unrelated subjects.",
          "Slavery's daily violence, family separation, and economic logic generated continuous resistance — from everyday acts of refusal documented by Stephanie Camp (*Closer to Freedom*, 2004) to organized rebellions (Stono 1739, Gabriel 1800, Vesey 1822, Nat Turner 1831) and abolitionist organizing (Frederick Douglass, Harriet Tubman, William Lloyd Garrison).",
          "Resistance never occurred under slavery.",
          "Abolition began only after 1900."],
         1,
         "AP synthesis links slavery's structure to the resistance it generated — both everyday (Camp 2004) and organized (Stono, Gabriel, Vesey, Turner)."),
        ("Which AP analytical skill is most directly tested by comparing slavery in Brazil and the U.S.?",
         ["Memorization without comparison.",
          "Comparison: identifying similarities (chattel status, racial hierarchy, plantation export agriculture) and differences (Brazil's higher manumission rate and continuous African importation through 1850; the U.S.'s natural increase and 1808 import ban).",
          "Quotation without analysis.",
          "Listing dates without thesis."],
         1,
         "AP comparison rewards explicit similarity *and* difference statements with named scholars (Frank Tannenbaum 1946; Carl Degler 1971) and dated structural features."),
        # Part 5
        ("Which event marked a turning point in the legal status of slavery in the United States?",
         ["The Boston Tea Party (1773).",
          "The Thirteenth Amendment (ratified December 6, 1865), which abolished slavery and involuntary servitude \"except as a punishment for crime\" — the constitutional end of the institution Lincoln's 1863 Emancipation Proclamation could only partially reach.",
          "The Stamp Act (1765).",
          "The Treaty of Paris (1783)."],
         1,
         "The 13th Amendment (1865) constitutionally abolished slavery; the Emancipation Proclamation (Jan 1, 1863) had freed enslaved people only in Confederate-held areas not under Union control."),
        ("Which best describes a continuity of slavery from 1619 to 1865?",
         ["Slavery affected only Northern states.",
          "Across more than two centuries, slavery's defining features — racial hierarchy, hereditary status, family separation through sale, denial of literacy and legal personhood, and the constant threat of physical violence — persisted even as crops, regions, and laws changed.",
          "Slavery was a brief experiment that ended by 1700.",
          "Enslaved people held full legal personhood throughout the period."],
         1,
         "Continuity = the structural features of chattel slavery (race, heredity, violence, sale-driven family separation) persisted even as the crop economy shifted from tobacco/rice to cotton/sugar."),
        # Part 6
        ("A student wants to study the daily life of enslaved people from their own perspective. Which source is most directly useful?",
         ["The 1860 U.S. Census aggregate population tables only.",
          "The WPA Federal Writers' Project Slave Narratives (1936–1938), ~2,300 oral interviews with formerly enslaved people, paired with antebellum narratives such as Frederick Douglass (1845), Harriet Jacobs (1861), and Solomon Northup (1853).",
          "A 21st-century novel with no documentary basis.",
          "An undated speech with no provenance."],
         1,
         "The WPA Slave Narratives plus 19th-century autobiographical narratives (Douglass 1845; Jacobs 1861; Northup 1853) are the principal first-person sources for the AP exam."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point when using Harriet Jacobs's *Incidents in the Life of a Slave Girl* (1861)?",
         ["Quoting Jacobs verbatim without comment.",
          "Noting that Jacobs published under the pseudonym Linda Brent for a Northern white female abolitionist audience in 1861 — and using that audience and purpose to evaluate her account of sexual coercion under slavery.",
          "Citing only the page number with no analysis.",
          "Ignoring the author's perspective entirely."],
         1,
         "AP sourcing requires *use* of author/audience/purpose/situation — Jacobs's pseudonym, abolitionist female audience, and 1861 publication shape how she frames sexual violence."),
        # Part 7
        ("Which is the strongest one-sentence thesis on slavery in America?",
         ["Slavery was a long-running institution.",
          "Between 1619 and 1865, racialized chattel slavery in British North America and the United States grew from a fringe colonial labor system into the foundation of the Cotton Kingdom — enslaving roughly 4 million people by 1860 — and was ended only by Civil War, the Emancipation Proclamation (1863), and the Thirteenth Amendment (1865).",
          "Slavery had no economic significance.",
          "Slavery existed only briefly in colonial Virginia."],
         1,
         "Strong AP theses combine periodization (1619–1865), scale (4M by 1860), causation (cotton economy), and a complexity move (multi-stage end: war + EP + 13th Am)."),
        ("On the AP exam, the strongest move when writing about U.S. slavery is to:",
         ["Avoid all dates and named figures.",
          "Anchor claims in a named figure (Douglass, Jacobs, Turner), a dated event (1662 *partus sequitur ventrem*, 1793 cotton gin, 1808 import ban, 1865 13th Amendment), and a primary source (Douglass 1845, Jacobs 1861, WPA Narratives).",
          "Use only modern pop-culture examples for antebellum claims.",
          "Cite no sources at all."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# 5. Resistance & Abolition
# ────────────────────────────────────────────────────────────────────────────
T["aas-resistance-abolition"] = {
    "title": "Resistance & Abolition",
    "prefix": "aasra",
    "qs": [
        # Part 1
        ("In AP African American Studies, \"everyday resistance\" under slavery refers to:",
         ["Only large armed rebellions.",
          "Daily acts of refusal — work slowdowns, tool breakage, feigned illness, theft of food, running away temporarily, preserving forbidden literacy and worship — that historian Stephanie Camp (*Closer to Freedom*, 2004) calls a \"rival geography\" of enslaved life.",
          "Voluntary cooperation with enslavers in all matters.",
          "A purely 20th-century concept with no antebellum referent."],
         1,
         "Camp's *Closer to Freedom* (2004) and earlier work by Eugene Genovese (*Roll, Jordan, Roll*, 1974) describe \"everyday resistance\" as the ordinary infrapolitics of enslaved life."),
        ("The term \"abolitionism\" most precisely refers to:",
         ["The 19th-century movement to end slavery — initially gradualist (Pennsylvania Abolition Society 1775) and later \"immediatist\" after William Lloyd Garrison's *The Liberator* (founded 1831) and the American Anti-Slavery Society (founded 1833).",
          "A movement to expand slavery into new western territories.",
          "A 20th-century civil rights organization founded after WWII.",
          "A purely religious revival with no political content."],
         0,
         "Abolitionism shifted in the 1830s from gradual emancipation to \"immediatism\" with Garrison's *Liberator* (1831) and the American Anti-Slavery Society (1833)."),
        # Part 2
        ("Which named uprising was the largest enslaved rebellion in U.S. history by participants?",
         ["The Stono Rebellion (1739), South Carolina.",
          "The 1811 German Coast Uprising (Louisiana), in which roughly 200–500 enslaved people marched on New Orleans — the largest enslaved revolt by participants in U.S. history — led by Charles Deslondes.",
          "Bacon's Rebellion (1676).",
          "Shays's Rebellion (1786)."],
         1,
         "The 1811 German Coast Uprising mobilized ~200–500 enslaved participants under Charles Deslondes — by participant count the largest U.S. enslaved revolt; suppressed within days."),
        ("Nat Turner's 1831 rebellion in Southampton County, Virginia, was historically significant because:",
         ["It freed all enslaved people in Virginia.",
          "It killed approximately 55 white people, prompted brutal reprisals, intensified Southern slave codes (literacy bans, restrictions on Black preachers), and helped catalyze Garrison's immediatist abolitionism that same year.",
          "It established Virginia as a free state.",
          "It had no measurable consequences."],
         1,
         "Turner's August 1831 revolt killed ~55 white Virginians, drove harsher slave codes across the South, and coincided with Garrison's launch of *The Liberator* (Jan 1831), reshaping abolitionist debate."),
        # Part 3
        ("Which dated example best illustrates organized free-Black political activity before the Civil War?",
         ["The first Negro Convention (Philadelphia, 1830), which inaugurated a series of national meetings of free Black leaders — including Richard Allen, James Forten, and Frederick Douglass — debating emigration, education, and abolition.",
          "The 1965 Voting Rights Act.",
          "The 1909 founding of the NAACP.",
          "The Niagara Movement (1905)."],
         0,
         "The Negro Convention Movement (1830 onward) was a foundational free-Black political institution led by Richard Allen, James Forten, and later Frederick Douglass."),
        ("Which best characterizes the Underground Railroad?",
         ["A literal underground rail system built in the 1850s.",
          "A loosely organized clandestine network of free Black communities, formerly enslaved guides, and white sympathizers (including Quakers) that aided perhaps 30,000–100,000 freedom-seekers between c. 1800 and 1865 — most famously associated with Harriet Tubman, who made roughly 13 rescue trips.",
          "A government-funded transportation program.",
          "A maritime smuggling route limited to the Caribbean."],
         1,
         "The Underground Railroad was a clandestine, decentralized network — Tubman made ~13 documented trips; estimates of total fugitives aided range widely (30K–100K)."),
        # Part 4
        ("How do enslaved rebellions in the U.S. connect to the Haitian Revolution (1791–1804)?",
         ["The Haitian Revolution had no influence on U.S. enslaved people.",
          "Toussaint Louverture's leadership and Haiti's 1804 founding as a Black republic inspired conspiracies including Gabriel Prosser's planned 1800 Richmond uprising and Denmark Vesey's planned 1822 Charleston revolt — and intensified white Southern fears that drove harsher slave codes.",
          "Haiti became a U.S. state in 1804.",
          "U.S. abolitionists ignored Haiti entirely."],
         1,
         "Haitian victory (1791–1804) reverberated across the Atlantic — inspiring Gabriel (1800) and Vesey (1822) and intensifying Southern white fear and codes."),
        ("Which AP analytical skill is foregrounded by comparing William Lloyd Garrison and Frederick Douglass?",
         ["Memorization without comparison.",
          "Comparison: shared immediatism and moral suasion (1830s–40s), but contrasting trajectories — Garrison's pacifism and burning of the Constitution as \"a covenant with death\" versus Douglass's eventual embrace of political action, the U.S. Constitution as antislavery, and armed resistance after the Fugitive Slave Act of 1850.",
          "Free recall of unrelated facts.",
          "Citing only modern sources."],
         1,
         "AP comparison rewards explicit similarity *and* difference — Garrison and Douglass split publicly in 1851 over political action and the Constitution."),
        # Part 5
        ("Which 1850 federal law marked a major change in the politics of resistance and abolition?",
         ["The Fugitive Slave Act of 1850, part of the Compromise of 1850, which required Northern citizens and officials to assist in the capture of escaped enslaved people, criminalized aid to fugitives, and radicalized many previously moderate Northerners and Black communities (e.g., the 1851 Christiana Resistance in Pennsylvania).",
          "The Northwest Ordinance (1787).",
          "The Missouri Compromise (1820).",
          "The Kansas-Nebraska Act (1854)."],
         0,
         "The Fugitive Slave Act of 1850 federalized fugitive recapture and criminalized assistance, sparking events like the Christiana Resistance (1851) and Anthony Burns case (1854) and pushing Northern opinion toward antislavery."),
        ("Which best describes a continuity of African American resistance to slavery from 1619 to 1865?",
         ["Resistance was a brief, late-19th-century phenomenon.",
          "From maroon communities (Great Dismal Swamp, c. 1700s–1860s) and shipboard revolts (the *Amistad*, 1839; the *Creole*, 1841) through everyday refusal, organized rebellion (Stono 1739, Gabriel 1800, Vesey 1822, Turner 1831), Underground Railroad work, and Black abolitionist organizing, enslaved and free Black people resisted slavery across more than two centuries.",
          "Enslaved people accepted slavery without protest until 1860.",
          "Resistance occurred only in the Caribbean."],
         1,
         "Continuity = sustained, multi-form Black resistance across the entire era of U.S. slavery — maroon communities, shipboard revolts, organized rebellions, abolitionist organizing."),
        # Part 6
        ("A student wants to analyze the rhetoric of Black abolitionism. Which source is most directly useful?",
         ["A 21st-century policy memo.",
          "Frederick Douglass's *Narrative of the Life of Frederick Douglass, an American Slave* (1845) and his July 5, 1852 oration \"What to the Slave Is the Fourth of July?\" — paired with David Walker's *Appeal to the Coloured Citizens of the World* (1829) and Maria Stewart's 1832–33 Boston speeches.",
          "An undated anonymous pamphlet.",
          "A modern textbook with no primary excerpts."],
         1,
         "Douglass (1845, 1852), Walker (1829), and Stewart (1832–33) are the foundational primary sources for AP analysis of Black abolitionist rhetoric."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point on Douglass's 1852 \"Fourth of July\" speech?",
         ["Quoting it without comment.",
          "Noting that Douglass delivered it to a Rochester, NY anti-slavery audience on July 5, 1852 — purposely not the 4th — to indict the gap between American liberty rhetoric and chattel slavery, and using that audience and purpose to evaluate his use of irony and prophetic denunciation.",
          "Listing only the date with no analysis.",
          "Citing only its republication in modern anthologies."],
         1,
         "AP sourcing requires *use* of audience/purpose/situation — Douglass's pointed July 5 (not 4) date, Rochester abolitionist audience, and indictment purpose are essential to interpreting the speech."),
        # Part 7
        ("Which is the strongest one-sentence thesis on resistance and abolition?",
         ["Some people opposed slavery.",
          "Between 1619 and 1865, enslaved and free African Americans resisted slavery through everyday refusal, maroon communities, organized rebellions (Gabriel 1800, Vesey 1822, Turner 1831), the Underground Railroad, and Black abolitionist organizing — pressuring white allies into immediatist abolition (Garrison 1831, the AASS 1833) and ultimately reshaping the Civil War into a war of emancipation.",
          "Slavery ended without any Black resistance.",
          "Abolition was a purely European movement with no Black participation."],
         1,
         "Strong AP theses combine multiple forms of resistance, named figures and dated events, and a complexity move (Black resistance reshaping the war into emancipation)."),
        ("On the AP exam, the strongest move when writing about resistance and abolition is to:",
         ["Avoid all dates and named figures.",
          "Anchor claims in a named figure (Douglass, Tubman, Turner, Walker, Garrison), a dated event (1739 Stono, 1800 Gabriel, 1822 Vesey, 1831 Turner / *Liberator*, 1850 Fugitive Slave Act), and a primary source (Douglass 1845/1852, Walker 1829).",
          "Use only modern pop-culture examples.",
          "Cite no sources at all."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

if __name__ == "__main__":
    EXPECTED = {
        "aas-origins-diaspora",
        "aas-african-kingdoms",
        "aas-transatlantic-slave-trade",
        "aas-slavery-in-america",
        "aas-resistance-abolition",
    }
    write_batch(T, EXPECTED)
