#!/usr/bin/env python3
"""AP Psychology entrance quizzes — Batch 4: Clinical & Social (6 topics)."""
from __future__ import annotations
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _psych_quiz_common import write_batch

EXPECTED = {
    "psychological-disorders-overview",
    "mood-psychotic-disorders",
    "treatment-therapy",
    "social-influence-conformity",
    "attitudes-persuasion",
    "group-behavior-prejudice",
}

T = {
    "psychological-disorders-overview": {
        "title": "Psychological Disorders Overview",
        "prefix": "pdo",
        "qs": [
            ("Mental disorder is generally defined by clinically significant disturbance that:",
             ["Always involves hallucinations", "Causes distress or impairment in functioning and is not culturally normative or due to expected reactions (DSM-5-TR criterion)", "Requires brain damage", "Must include violence"], 1,
             "DSM-5-TR (2022) defines disorder by significant distress, dysfunction, or risk of harm; ordinary grief or culturally sanctioned beliefs are excluded."),
            ("The DSM-5-TR is published by the:",
             ["WHO", "American Psychiatric Association (APA — the psychiatry one, not the psychology APA)", "FDA", "U.S. Department of Education"], 1,
             "The DSM (Diagnostic and Statistical Manual) is published by the American Psychiatric Association. The ICD-11 is published by WHO."),
            ("DSM-5 (2013) eliminated the multi-axial system of DSM-IV. Instead it uses:",
             ["Five axes", "A SINGLE list of categorical diagnoses with separate dimensional severity ratings and notes on context", "No diagnoses", "Only ICD codes"], 1,
             "DSM-IV's 5 axes (clinical disorders, personality, medical, psychosocial, GAF) were replaced; functioning is now noted via WHODAS."),
            ("The BIOPSYCHOSOCIAL model of mental disorder holds that disorders arise from:",
             ["Genes only", "Interacting biological, psychological, and social/cultural factors — adopted by modern psychiatry and AP Psych", "Demonic possession", "Trauma alone"], 1,
             "Engel (1977) introduced the biopsychosocial model. AP Psych emphasizes integration over single-cause explanations."),
            ("The DIATHESIS-STRESS model proposes that:",
             ["Stress alone causes disorder", "A predisposition (diathesis: genetic, biological, cognitive) interacts with STRESSORS to produce disorder", "Genes alone cause disorder", "Disorders are random"], 1,
             "Diathesis-stress is widely applied to schizophrenia, depression, PTSD, and anxiety disorders."),
            ("ANXIETY disorders include:",
             ["Schizophrenia", "Generalized anxiety disorder, panic disorder, specific phobia, social anxiety disorder, agoraphobia", "Bipolar I", "Major depression"], 1,
             "DSM-5 separated OCD and PTSD into their own chapters; both were previously classified with anxiety disorders."),
            ("OCD is characterized by:",
             ["Mood swings", "Recurrent OBSESSIONS (intrusive thoughts) and/or COMPULSIONS (repetitive behaviors aimed at reducing anxiety)", "Hallucinations only", "Personality change only"], 1,
             "OCD has its own DSM-5 chapter ('Obsessive-Compulsive and Related Disorders') and responds to SSRIs and exposure-and-response prevention (ERP)."),
            ("PTSD requires:",
             ["No prior trauma", "Exposure to actual or threatened death/serious injury followed by intrusion symptoms, avoidance, negative cognitions/mood, and arousal/reactivity changes", "Two unrelated stressors", "Mood elevation"], 1,
             "PTSD is now in its own 'Trauma- and Stressor-Related Disorders' chapter in DSM-5."),
            ("DISSOCIATIVE Identity Disorder (formerly multiple personality) is:",
             ["Universally accepted", "Controversial — some clinicians argue it is iatrogenically induced by suggestive therapy; others see it as a real trauma response", "Always faked", "Always present at birth"], 1,
             "Diagnosis rates spiked after the 1973 'Sybil' case; DSM-5 retains the diagnosis but evidence remains debated."),
            ("PERSONALITY disorders are:",
             ["Brief mood states", "Enduring patterns of inner experience and behavior that deviate markedly from cultural expectations and cause distress/impairment", "The same as anxiety", "Diagnosed in infancy"], 1,
             "DSM-5 keeps Cluster A (odd/eccentric), B (dramatic/erratic, includes BPD/antisocial), C (anxious/fearful)."),
            ("Borderline Personality Disorder (BPD) is characterized by:",
             ["Calm stability", "Instability of mood, identity, and relationships; impulsivity; recurrent self-harm/suicidal behavior", "Hallucinations only", "Manic episodes"], 1,
             "Linehan's Dialectical Behavior Therapy (DBT, 1993) is a leading evidence-based treatment for BPD."),
            ("CULTURE-BOUND syndromes (e.g., taijin kyofusho in Japan, ataque de nervios in Latin America) illustrate that:",
             ["Disorders are identical across cultures", "Cultural context shapes expression, idiom, and prevalence of mental distress; DSM-5 includes a Cultural Formulation Interview", "Culture is irrelevant", "Only Western diagnoses are real"], 1,
             "DSM-5 acknowledges culture-bound syndromes and provides cultural formulation tools, reflecting greater cross-cultural awareness."),
            ("On the AP Psych exam, a question about a person who shows persistent worry about everyday matters for over six months tests:",
             ["Specific phobia", "Generalized Anxiety Disorder (GAD)", "Bipolar I", "Schizophrenia"], 1,
             "GAD: ≥6 months of excessive, hard-to-control worry across multiple domains, with somatic symptoms (DSM-5)."),
            ("Which AP-style claim is correct?",
             ["Diagnosing mental disorders is purely subjective", "Modern diagnosis uses standardized criteria (DSM-5-TR, ICD-11) integrated with cultural and contextual judgment; reliability has improved but classification remains a model, not a perfect biological fact", "DSM is genetic", "Mental disorders are rare"], 1,
             "AP Psych emphasizes both the value and limitations of DSM categorical diagnosis."),
        ],
    },

    "mood-psychotic-disorders": {
        "title": "Mood & Psychotic Disorders",
        "prefix": "mpd",
        "qs": [
            ("Major Depressive Disorder (MDD) requires at least:",
             ["1 day of low mood", "5 of 9 symptoms (incl. depressed mood OR anhedonia) for ≥2 weeks, causing impairment", "Mania", "Hallucinations only"], 1,
             "DSM-5 MDD criteria: depressed mood, anhedonia, sleep, appetite/weight, psychomotor, fatigue, guilt/worthlessness, concentration, suicidal ideation."),
            ("Lifetime prevalence of MDD in the U.S. is approximately:",
             ["<1%", "About 17-20% (women ~2x men)", "75%", "0%"], 1,
             "NCS-R (Kessler 2005): MDD lifetime ~16-20%. Sex difference appears at puberty."),
            ("PERSISTENT depressive disorder (formerly dysthymia) is:",
             ["A brief mood episode", "A milder but CHRONIC depression lasting ≥2 years (≥1 year in children)", "A psychotic disorder", "Mania"], 1,
             "DSM-5 merged dysthymia and chronic MDD into Persistent Depressive Disorder."),
            ("BIPOLAR I disorder requires at least one episode of:",
             ["Major depression only", "MANIA (≥1 week of elevated/irritable mood with ↑ energy, decreased sleep need, grandiosity, etc.)", "Hallucinations only", "Anxiety"], 1,
             "Bipolar II requires hypomania (less severe, ≥4 days) plus a major depressive episode."),
            ("First-line drug treatment for bipolar disorder includes:",
             ["SSRIs alone", "MOOD STABILIZERS — lithium (Cade 1949) is the prototype; also valproate, lamotrigine; SSRIs alone risk inducing mania", "Antipsychotics only", "Caffeine"], 1,
             "Lithium reduces suicide risk and mania recurrence; requires blood-level monitoring (narrow therapeutic window)."),
            ("Cognitive theory of depression (Aaron Beck 1967) emphasizes:",
             ["Unconscious conflicts", "The negative COGNITIVE TRIAD — negative views of self, world, and future — maintained by automatic thoughts and schemas", "Reinforcement only", "Brain damage"], 1,
             "Beck's cognitive therapy targets distorted thinking and is highly effective for depression."),
            ("LEARNED helplessness (Seligman 1967) is the tendency to:",
             ["Try harder", "Stop trying after exposure to UNCONTROLLABLE aversive events — proposed model of depression and trauma", "Be intrinsically motivated", "Recover quickly"], 1,
             "Seligman's reformulated learned helplessness emphasized attributional style: stable, internal, global attributions for negative events."),
            ("Schizophrenia is characterized by:",
             ["Mood swings only", "Positive symptoms (hallucinations, delusions, disorganized thought/speech), negative symptoms (flat affect, alogia, avolition), and cognitive symptoms", "Phobias", "Compulsions"], 1,
             "DSM-5 schizophrenia: ≥2 symptoms (with at least one being hallucinations, delusions, or disorganized speech) for ≥1 month, with social/occupational decline ≥6 months."),
            ("Hallucinations in schizophrenia are most often:",
             ["Visual", "AUDITORY (e.g., voices commenting or commanding)", "Tactile", "Olfactory"], 1,
             "Auditory hallucinations are the most common positive symptom in schizophrenia."),
            ("Delusions are:",
             ["Sensory perceptions", "Fixed FALSE BELIEFS not amenable to evidence (persecutory, grandiose, referential, somatic)", "Memories", "Reflexes"], 1,
             "Persecutory delusions are most common in schizophrenia; delusions distinguish psychosis from non-psychotic disorders."),
            ("The DOPAMINE hypothesis of schizophrenia holds that:",
             ["Dopamine is too low", "EXCESS dopamine activity (especially mesolimbic D2) underlies positive symptoms; classic antipsychotics block D2 receptors", "Serotonin alone causes it", "GABA is irrelevant"], 1,
             "Modern revision: hyperdopaminergic in mesolimbic pathway (positive symptoms) but hypodopaminergic in mesocortical pathway (negative/cognitive symptoms)."),
            ("Lifetime prevalence of schizophrenia worldwide is approximately:",
             ["10%", "About 0.3-1% (commonly cited ~1%)", "20%", "0%"], 1,
             "Schizophrenia prevalence is roughly equal across cultures; onset usually late adolescence/early adulthood (men slightly earlier)."),
            ("On the AP Psych exam, a question about a college student who suddenly hears voices commanding them and believes the FBI is monitoring their phone tests:",
             ["Major depression", "Schizophrenia (positive symptoms: auditory hallucinations + persecutory delusion, typical age of onset)", "Bipolar I", "OCD"], 1,
             "Schizophrenia commonly emerges in late teens / early 20s with positive symptoms predominating in early phases."),
            ("Which AP-style claim is correct?",
             ["Mood and psychotic disorders are purely psychological", "These disorders involve genetic, neurochemical, and environmental contributions; treatment is most effective when biological (medication) and psychological (therapy) approaches are combined", "Medication alone always works", "Therapy alone always works"], 1,
             "Combined treatment (e.g., antidepressants + CBT for MDD; antipsychotics + psychosocial for schizophrenia) typically outperforms either alone."),
        ],
    },

    "treatment-therapy": {
        "title": "Treatment & Therapy",
        "prefix": "tt",
        "qs": [
            ("Psychoanalysis (Freud) uses techniques such as:",
             ["Token economies", "FREE ASSOCIATION, dream analysis, interpretation of resistance and TRANSFERENCE", "Cognitive restructuring", "Exposure therapy"], 1,
             "Modern psychodynamic therapy is briefer but retains attention to unconscious processes and the therapeutic relationship."),
            ("Carl Rogers's CLIENT-CENTERED therapy emphasizes:",
             ["Confrontation", "Genuineness, empathic understanding, and UNCONDITIONAL POSITIVE REGARD — letting the client direct the work", "Operant conditioning", "Brain stimulation"], 1,
             "Rogers (1951) reframed the relationship as 'client' (not patient) and 'therapist as facilitator' — foundational for humanistic therapy."),
            ("BEHAVIOR therapies apply learning principles. SYSTEMATIC DESENSITIZATION (Wolpe 1958) treats phobias by:",
             ["Random reinforcement", "Pairing graduated exposure to the feared CS with relaxation (counter-conditioning)", "Free association", "Hypnosis"], 1,
             "Systematic desensitization is highly effective for specific phobias; modern variants use in-vivo and virtual-reality exposure."),
            ("EXPOSURE-and-Response Prevention (ERP) is the gold standard for:",
             ["Schizophrenia", "Obsessive-Compulsive Disorder — exposing client to triggers WHILE preventing the compulsion until anxiety subsides", "Bipolar disorder", "Dementia"], 1,
             "Foa's ERP shows large effect sizes for OCD, often equaling or exceeding SSRIs."),
            ("AVERSION therapy pairs an unwanted behavior with:",
             ["A reward", "An UNPLEASANT stimulus (e.g., disulfiram for alcohol → nausea when drinking) — modest evidence base", "Free association", "ECT"], 1,
             "Aversion therapy has been controversial; effect often does not generalize beyond the conditioning context."),
            ("Cognitive-Behavioral Therapy (CBT) combines:",
             ["Drugs and surgery", "Cognitive restructuring (changing distorted thoughts) AND behavioral techniques (exposure, behavioral activation)", "Hypnosis only", "Free association"], 1,
             "CBT (Beck, Ellis, Meichenbaum) is the most empirically supported psychotherapy across depression, anxiety, PTSD, OCD, and many other disorders."),
            ("Albert Ellis's RATIONAL EMOTIVE Behavior Therapy (REBT) targets:",
             ["Reflexes", "Irrational BELIEFS (the 'B' in his ABC model: Activating event → Belief → Consequence) — directly disputing them", "Hormones", "Memories only"], 1,
             "Ellis (1955) developed REBT before Beck's cognitive therapy. Both emphasize cognition's role in emotional disorder."),
            ("DIALECTICAL Behavior Therapy (DBT, Linehan 1993) was developed for:",
             ["Schizophrenia", "Borderline Personality Disorder; combines CBT with mindfulness, emotion regulation, distress tolerance, and interpersonal skills", "Dementia", "Specific phobia"], 1,
             "DBT has the strongest evidence base for BPD and is also used for self-harm and chronic suicidality."),
            ("SSRIs (e.g., fluoxetine/Prozac, FDA-approved 1987) work by:",
             ["Blocking dopamine receptors", "Selectively inhibiting reuptake of SEROTONIN, increasing synaptic 5-HT", "Increasing GABA", "Stimulating ACh release"], 1,
             "SSRIs are first-line for MDD, anxiety, OCD; effect typically takes 2-6 weeks despite immediate biochemical change."),
            ("Antipsychotic medications work primarily by:",
             ["Blocking serotonin only", "Blocking dopamine D2 receptors (typicals); atypicals also affect serotonin (5-HT2A)", "Releasing dopamine", "Suppressing acetylcholine"], 1,
             "Typical antipsychotics (chlorpromazine 1952, haloperidol) cause more extrapyramidal side effects; atypicals (clozapine, risperidone) reduce these but increase metabolic risk."),
            ("Electroconvulsive therapy (ECT) is most clearly effective for:",
             ["Mild anxiety", "SEVERE, treatment-resistant depression — rapid response, especially when suicide risk or psychotic features present; main side effect = transient memory loss", "Specific phobia", "Schizophrenia in remission"], 1,
             "Modern ECT (unilateral, brief-pulse, with anesthesia) is far safer than mid-20th-century practice and remains an important option."),
            ("Lobotomy (Moniz 1936; popularized in U.S. by Freeman 1940s) is now:",
             ["Standard practice", "Largely abandoned as crude and harmful — replaced by medications and far more targeted neurosurgical procedures (deep brain stimulation, anterior cingulotomy in rare cases)", "Used routinely for depression", "Mandatory for schizophrenia"], 1,
             "Moniz received the 1949 Nobel Prize for prefrontal leucotomy — now seen as one of the most regrettable medical Nobels."),
            ("On the AP Psych exam, a question about a clinician disputing a client's belief that 'one bad grade means I am a complete failure' tests:",
             ["Free association", "Cognitive therapy / cognitive restructuring (Beck, Ellis)", "Token economy", "Aversion therapy"], 1,
             "Identifying and challenging cognitive distortions (overgeneralization, all-or-nothing) is core to cognitive therapy."),
            ("Which AP-style claim is correct?",
             ["Therapy effectiveness depends only on technique", "Outcome research finds therapy is generally effective; common factors (therapeutic alliance, client expectations) account for substantial variance, with specific techniques (e.g., CBT for anxiety, DBT for BPD) showing additional disorder-specific benefits", "All therapies are equally effective for everything", "Therapy doesn't work"], 1,
             "Wampold's Common Factors model + evidence-based practice both supported. AP Psych emphasizes evidence-based treatment."),
        ],
    },

    "social-influence-conformity": {
        "title": "Social Influence & Conformity",
        "prefix": "sic",
        "qs": [
            ("Solomon Asch's line-judgment experiments (1951) found that participants conformed to the wrong group answer about:",
             ["1% of trials", "About 37% of trials on average; ~75% conformed at least once", "100% always", "Never"], 1,
             "Asch demonstrated normative social influence even on perceptually obvious tasks. Conformity dropped sharply with one dissenting ally."),
            ("Asch showed conformity DECREASED when:",
             ["The group was unanimous", "Any single ally also dissented from the majority", "Group size grew past 30", "Participants were anonymous to themselves"], 1,
             "Even one ally dramatically reduced conformity, suggesting social support breaks the unanimity pressure."),
            ("Sherif's autokinetic effect study (1935) demonstrated:",
             ["Normative conformity", "INFORMATIONAL social influence — in an ambiguous situation, individuals' estimates converged on a group norm", "Obedience", "Bystander effect"], 1,
             "Sherif used a stationary point of light in darkness (apparent motion). Norms persisted when participants were retested alone, even a year later."),
            ("Stanley Milgram's obedience studies (1961-63) found that approximately ____ of participants delivered the maximum 450-volt shock:",
             ["1%", "About 65% in the baseline condition", "100%", "10%"], 1,
             "Milgram's findings shocked psychology by showing ordinary adults would obey legitimate authority to apparently lethal levels."),
            ("Milgram's obedience DECREASED when:",
             ["Authority wore a lab coat", "The experimenter was distant, the authority's legitimacy was undermined, OR the participant saw a peer disobey", "The victim was unseen", "The shock was real"], 1,
             "Proximity to victim, distance from authority, location prestige, and presence of disobedient models all reduced obedience."),
            ("Zimbardo's Stanford Prison Experiment (1971) is now:",
             ["Considered a model study", "Heavily critiqued for methodology, demand characteristics, and ethics — Zimbardo coached guards; recent reanalyses (Le Texier 2019; Texier-Reicher) challenge the 'situational power' interpretation", "Required reading uncritically", "Replicated successfully"], 1,
             "Modern reappraisal: SPE is more demonstration than experiment; AP Psych still teaches it but with important caveats."),
            ("INFORMATIONAL social influence (vs normative) is conforming because we believe the group:",
             ["Will reward us", "Has accurate information when we are uncertain", "Is the same as us", "Will punish us"], 1,
             "Informational influence drives genuine attitude change; normative influence drives public compliance to gain acceptance."),
            ("FOOT-IN-THE-DOOR (Freedman & Fraser 1966) is a compliance technique that:",
             ["Asks the big request first", "Asks a small request first; once granted, larger requests are more likely to be granted", "Uses force", "Uses authority"], 1,
             "Foot-in-the-door exploits commitment/consistency. Door-in-the-face does the opposite (large then reasonable)."),
            ("The BYSTANDER effect (Latané & Darley 1968) refers to:",
             ["Faster help with more bystanders", "REDUCED helping when more bystanders are present, due to diffusion of responsibility and pluralistic ignorance", "Random helping", "Helping only strangers"], 1,
             "Triggered by 1964 Kitty Genovese case (later journalism revised many details). The lab effect itself is robust."),
            ("Latané & Darley's smoke-filled-room study found participants reported the smoke:",
             ["Faster when alone vs in a group", "More slowly when other (passive) bystanders were present — pluralistic ignorance", "At the same rate", "Only with female confederates"], 1,
             "When others remained calm, participants suppressed their own concern, illustrating pluralistic ignorance."),
            ("Social FACILITATION (Triplett 1898; Zajonc 1965) refers to:",
             ["Worse performance under arousal", "Improved performance on WELL-LEARNED/simple tasks but IMPAIRED performance on novel/complex tasks when others are present (arousal × dominant response)", "Identical performance", "No effect of audience"], 1,
             "Zajonc explained mixed early results by tying audience effects to dominant-response strength."),
            ("Social LOAFING (Latané, Williams, Harkins 1979) is the tendency to:",
             ["Work harder in groups", "Exert LESS effort in groups when individual contributions are not identifiable", "Work alone always", "Avoid groups"], 1,
             "Social loafing is reduced when individual performance is monitored, the task is engaging, or group identification is high."),
            ("On the AP Psych exam, a question about an employee going along with a coworker majority on an obviously incorrect answer to avoid awkwardness tests:",
             ["Informational social influence", "Normative social influence (Asch-style conformity)", "Obedience", "Bystander effect"], 1,
             "Going along to avoid disapproval, knowing the answer is wrong, is normative influence."),
            ("Which AP-style claim is correct?",
             ["Social influence is rare and weak", "Classic social psychology (Asch, Milgram, Latané/Darley) shows that ordinary situational forces — conformity, obedience, diffusion of responsibility — powerfully shape behavior, often more than personality traits", "Personality alone explains behavior", "Bystander effect was disconfirmed"], 1,
             "AP Psych emphasizes the 'power of the situation' demonstrated by classic social-psychological research."),
        ],
    },

    "attitudes-persuasion": {
        "title": "Attitudes & Persuasion",
        "prefix": "ap",
        "qs": [
            ("An ATTITUDE is generally defined as:",
             ["A behavior", "An evaluative belief and/or feeling toward an object, person, or idea (cognitive, affective, behavioral components)", "A trait", "A reflex"], 1,
             "Tripartite ABC model: Affect, Behavior tendencies, Cognition."),
            ("LaPiere's (1934) restaurant study found that attitudes (verbal prejudice toward Chinese visitors) and behavior (actual service):",
             ["Matched perfectly", "Often DIVERGED — attitudes do not always predict behavior, especially under social and situational pressures", "Were unrelated", "Always opposite"], 1,
             "LaPiere's study challenged simple attitude-behavior assumptions. Attitudes predict behavior best when specific, strong, and accessible."),
            ("Festinger's COGNITIVE DISSONANCE theory (1957) holds that:",
             ["Attitudes never change", "Holding inconsistent cognitions creates DISCOMFORT that motivates attitude change to restore consistency", "Behavior never affects attitude", "All attitudes are stable"], 1,
             "Dissonance reduction often involves changing the more flexible cognition; powerful explanation of post-decision and induced-compliance shifts."),
            ("Festinger & Carlsmith (1959) had participants do a boring task and tell others it was fun for $1 OR $20. Those paid:",
             ["$20 rated the task more enjoyable", "$1 rated the task MORE enjoyable — insufficient external justification → dissonance reduction by changing attitude", "Both rated equally", "Neither rated"], 1,
             "Classic dissonance demonstration: the less external justification, the greater the attitude change."),
            ("The ELABORATION LIKELIHOOD model (Petty & Cacioppo 1986) distinguishes:",
             ["One persuasion route", "CENTRAL route (careful processing of strong arguments) vs PERIPHERAL route (cues like attractiveness, length, expertise)", "Two attitudes", "Reflexes only"], 1,
             "ELM predicts central-route attitude change is more durable and behavior-predictive; peripheral route is faster but more fragile."),
            ("CENTRAL-route persuasion is most likely when:",
             ["Audience is unmotivated and distracted", "Audience is motivated and ABLE to think carefully about the message", "Audience is angry", "Source is irrelevant"], 1,
             "ELM moderators: motivation (personal relevance) and ability (knowledge, distraction)."),
            ("FOOT-IN-THE-DOOR was explained partly by:",
             ["Social loafing", "SELF-PERCEPTION theory (Bem 1972) and consistency motives — agreeing to a small request makes one see oneself as 'a helpful person'", "Operant conditioning", "Bystander effect"], 1,
             "Bem's self-perception theory complements dissonance theory, especially when initial attitudes are weak."),
            ("Bem's SELF-PERCEPTION theory holds that we infer our attitudes by:",
             ["Polling others", "Observing our own BEHAVIOR and the situation, much as outside observers would (especially when prior attitudes are weak)", "Genetic readout", "Reflex"], 1,
             "Self-perception explains some classic dissonance results without invoking arousal; both processes likely operate in different conditions."),
            ("FEAR appeals are most persuasive when they:",
             ["Just scare the audience", "Both arouse fear AND provide a CLEAR, FEASIBLE action to reduce the threat", "Scare without instructions", "Use mild fear only"], 1,
             "Witte's Extended Parallel Process Model: fear must be paired with self-efficacy and response efficacy to motivate protective behavior."),
            ("The MERE EXPOSURE effect (Zajonc 1968) is:",
             ["Disliking with familiarity", "INCREASED liking for a stimulus simply through repeated exposure (without conscious processing)", "Forgetting", "Habituation only"], 1,
             "Mere exposure influences advertising, music popularity, and political familiarity effects."),
            ("The SLEEPER effect describes:",
             ["Immediate persuasion", "DELAYED persuasion as the audience separates a strong message from its initially discounted (low-credibility) source", "No persuasion", "Backfire effect"], 1,
             "Hovland's WWII propaganda studies first documented the sleeper effect."),
            ("Inoculation theory (McGuire 1964) proposes:",
             ["Avoid all opposing views", "Pre-exposing people to weakened forms of opposing arguments can BUILD resistance to later persuasion (a 'mental vaccine')", "Inoculation does not work", "Only repetition matters"], 1,
             "Inoculation is now applied to misinformation pre-bunking; modest but real effects in field studies."),
            ("On the AP Psych exam, a question about a celebrity (rather than evidence) being used to sell a watch tests:",
             ["Central route persuasion", "Peripheral route persuasion (cues like source attractiveness)", "Cognitive dissonance", "Self-perception"], 1,
             "Celebrity endorsement, music, and visual appeal are peripheral cues — most effective when audience is unmotivated/unable to evaluate the message."),
            ("Which AP-style claim is correct?",
             ["Attitudes always cause behavior", "The attitude-behavior link depends on attitude specificity, strength, accessibility, and situational pressures; persuasion works through both effortful (central) and shortcut (peripheral) routes", "Attitudes are unchangeable", "Persuasion has no science"], 1,
             "AP Psych integrates dissonance, self-perception, and ELM as complementary frameworks for attitude change."),
        ],
    },

    "group-behavior-prejudice": {
        "title": "Group Behavior & Prejudice",
        "prefix": "gbp",
        "qs": [
            ("GROUP polarization is the tendency for:",
             ["Group decisions to moderate", "Group discussion to STRENGTHEN the average pre-existing tendency of members (initially leaning risky → riskier; initially cautious → more cautious)", "Random shifts", "Reduce conformity"], 1,
             "Polarization driven by persuasive arguments and social comparison; observed in juries, online forums, political groups."),
            ("GROUPTHINK (Janis 1972) is:",
             ["Healthy debate", "A mode of decision-making in cohesive groups where the desire for harmony OVERRIDES realistic appraisal — symptoms include illusion of invulnerability, self-censorship, mindguards", "Brainstorming", "Random voting"], 1,
             "Janis applied groupthink to Bay of Pigs (1961), Pearl Harbor, Challenger; reduced by devil's advocates and outside critics."),
            ("DEINDIVIDUATION (Festinger, Pepitone, Newcomb 1952; Zimbardo) refers to:",
             ["Strong personal identity", "Loss of self-awareness/personal responsibility in group settings, especially with anonymity and arousal — can facilitate antinormative behavior (mob violence, online trolling)", "Bystander effect", "Conformity"], 1,
             "Anonymity (uniforms, masks, online avatars) and group arousal increase deindividuation; effect is moderated by group norms."),
            ("IN-GROUP bias (Tajfel's MINIMAL group studies, 1971) shows that:",
             ["People only favor major real groups", "Even arbitrary group assignments (coin flip, art preference) lead participants to favor in-group members in resource allocation", "There is no in-group bias", "People always favor out-group"], 1,
             "Minimal group paradigm helped found Social Identity Theory: group membership itself shapes evaluation and behavior."),
            ("Social Identity Theory (Tajfel & Turner 1979) explains in-group favoritism via:",
             ["Pure self-interest", "Self-esteem motives — boosting the in-group enhances one's social identity and self-concept", "Reinforcement", "Reflex"], 1,
             "SIT predicts strongest in-group favoritism when group membership is salient and self-esteem is threatened."),
            ("Out-group HOMOGENEITY effect:",
             ["Out-group members seem distinctive", "We tend to perceive members of OUT-groups as more similar to each other than members of our IN-group", "All groups equally varied", "In-group is more uniform"], 1,
             "Out-group homogeneity contributes to stereotyping ('they're all alike') and underlies prejudice."),
            ("Allport's CONTACT hypothesis (1954) proposes that intergroup contact reduces prejudice when:",
             ["Contact is brief and competitive", "Contact is sustained, with EQUAL status, common goals, cooperation, and institutional support", "Any contact suffices", "Contact has no effect"], 1,
             "Pettigrew & Tropp (2006) meta-analysis: contact under Allport's conditions reliably reduces prejudice; even less ideal contact has small positive effects."),
            ("Sherif's ROBBERS CAVE study (1954) at a boys' summer camp showed conflict was reduced by:",
             ["More competition", "Pursuing SUPERORDINATE GOALS that required cooperation between rival groups (broken truck, water supply)", "Separation", "Punishment"], 1,
             "Robbers Cave demonstrated both how easily intergroup conflict is created AND how cooperation reduces it."),
            ("STEREOTYPE THREAT (Steele & Aronson 1995) refers to:",
             ["Stereotypes always being wrong", "PERFORMANCE impairment that occurs when an individual fears confirming a negative stereotype about their group on a relevant task", "Reverse discrimination", "Self-stereotyping"], 1,
             "Steele & Aronson found Black college students performed worse on a difficult verbal test framed as diagnostic of intelligence; effect replicated across many groups and domains."),
            ("Devine's (1989) work on automatic vs controlled prejudice argued:",
             ["Bias is purely conscious", "Cultural stereotypes can be automatically activated even in low-prejudice individuals; controlled processing is needed to inhibit/correct biased responses", "Bias is always intentional", "Implicit bias does not exist"], 1,
             "Modern dual-process models distinguish implicit (automatic) and explicit (controlled) prejudice; intervention research increasingly targets both."),
            ("Implicit Association Test (IAT; Greenwald, McGhee, Schwartz 1998):",
             ["Has settled all questions about prejudice", "Measures relative speed of associations (e.g., good/bad with race); useful for AGGREGATE patterns but contested as a predictor of INDIVIDUAL behavior", "Is unanimously accepted", "Replaced explicit measures"], 1,
             "IAT is widely used but its individual-level reliability and validity have been challenged (Oswald et al. 2013, 2015)."),
            ("FUNDAMENTAL ATTRIBUTION ERROR (Lee Ross 1977) is the tendency to:",
             ["Underestimate dispositions", "OVER-ESTIMATE personal disposition and UNDER-ESTIMATE situational factors when explaining OTHERS' behavior", "Overweight situations", "Equally weight both"], 1,
             "FAE contributes to prejudice (attributing group outcomes to traits rather than structural factors); weaker in some collectivist cultures."),
            ("On the AP Psych exam, a question about a jury becoming more punitive after deliberation when individual jurors started leaning punitive tests:",
             ["Bystander effect", "Group polarization", "Groupthink", "Conformity"], 1,
             "Group polarization specifically describes amplification of pre-existing group leanings through discussion."),
            ("Which AP-style claim is correct?",
             ["Prejudice is purely individual and conscious", "Prejudice involves cognitive (categorization, stereotypes), affective (out-group anxiety), and social-structural factors; reduction is most effective with sustained, equal-status, cooperative contact and structural change", "Contact never helps", "Prejudice cannot change"], 1,
             "AP Psych integrates social-cognitive, motivational, and structural accounts of prejudice and its reduction."),
        ],
    },
}

if __name__ == "__main__":
    write_batch(T, EXPECTED)
