#!/usr/bin/env python3
"""
Rebuild all 13 AP Microeconomics entrance quizzes with topic-specific content.
Replaces boilerplate with real micro content (graphs, formulas, named cases).
"""
from __future__ import annotations
import os, json, re

# These generators contain ONLY currency dollar signs (all math is written as
# plain text). A quiz field with >= 2 currency tokens would otherwise collide
# as KaTeX $...$ inline-math delimiters and swallow the prose between them, so
# escape each amount as $\$N$ (KaTeX renders a literal "$N"). Single-token
# fields render fine as plain text and are left untouched to minimize churn.
_MONEY = re.compile(r'(?<!\\)\$((?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?)([A-Za-z]*)')


def esc_money(s: str) -> str:
    if len(_MONEY.findall(s)) < 2:
        return s
    return _MONEY.sub(lambda m: '$\\$' + m.group(1).replace(',', '{,}') + '$' + m.group(2), s)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "src", "data", "entrance-quizzes")

PART_TITLES = {
    1: "Core Concepts",
    2: "Key Processes",
    3: "Patterns & Examples",
    4: "Connections & Interactions",
    5: "Change Over Time",
    6: "Problem-Solving Workshop",
    7: "AP Review",
}

T = {
    "micro-scarcity-marginal-analysis": {
        "title": "Scarcity & Marginal Analysis",
        "qs": [
            ("Scarcity is best defined as:",
             ["A temporary shortage caused by trade barriers",
              "Unlimited human wants confronting limited productive resources",
              "Government rationing during wartime",
              "A lack of money in the economy"], 1,
             "Scarcity is the universal condition that human wants exceed the resources available to satisfy them."),
            ("Opportunity cost is:",
             ["The dollar price of a chosen good",
              "The value of the next-best alternative forgone",
              "Total of all alternatives not chosen",
              "Sunk cost"], 1,
             "Opportunity cost = next-best alternative forgone — not all alternatives, and not sunk costs."),
            ("A rational decision-maker continues an activity as long as:",
             ["Total benefit > total cost",
              "Marginal benefit > marginal cost",
              "Average benefit > average cost",
              "Sunk cost is recovered"], 1,
             "Marginal-decision rule: continue while MB > MC; stop where MB = MC."),
            ("Sunk costs should:",
             ["Heavily influence future decisions",
              "Be ignored in marginal decisions because they cannot be recovered",
              "Be split between marginal benefit and marginal cost",
              "Be added to the next decision's MC"], 1,
             "Sunk costs are bygones — irrelevant to forward-looking marginal analysis."),
            ("If MB of one more hour studying = $20 and MC = $25, a rational student should:",
             ["Study one more hour",
              "Stop studying — MB < MC",
              "Study indefinitely",
              "Study only if total benefit > total cost"], 1,
             "MB < MC → stop. Continuing would reduce net benefit."),
            ("A bowed-out PPC reflects:",
             ["Constant opportunity cost",
              "Increasing opportunity cost as resources reallocate",
              "Decreasing OC",
              "Zero OC at every point"], 1,
             "Bowed-out PPC: resources are not equally suited to all goods → increasing OC."),
            ("Movement ALONG the PPC implies:",
             ["Economic growth",
              "Reallocation of fixed resources between goods",
              "An increase in the labor force",
              "A technology breakthrough"], 1,
             "Along a fixed PPC, gaining more of one good means giving up some of another — pure reallocation."),
            ("Outward shifts of the PPC result from:",
             ["Reallocation between two existing goods",
              "More resources, more capital, or technological progress",
              "A short-run recession",
              "Higher inflation"], 1,
             "Long-run growth shifts the PPC outward; reallocation just moves along it."),
            ("U.S. real GDP per capita has grown approximately how fast since 1870?",
             ["0.1% per year",
              "About 2% per year",
              "8% per year",
              "Above 15% per year"], 1,
             "Long-run U.S. growth ≈ 2% per capita per year (Maddison data) — doubles roughly every 35 years."),
            ("A point INSIDE the PPC indicates:",
             ["Productive efficiency",
              "Unemployment or unused capacity (productive INefficiency)",
              "Output above potential",
              "Long-run equilibrium"], 1,
             "Inside-PPC points = idle resources; movement to the frontier requires no new resources."),
            ("Calculate marginal benefit of the 3rd hour of studying if total benefit = $50 (1 hr), $90 (2 hr), $120 (3 hr):",
             ["$120",
              "$30 (= $120 − $90)",
              "$40",
              "$50"], 1,
             "MB of nth unit = TB(n) − TB(n−1). MB(3) = $120 − $90 = $30."),
            ("A student spends 3 hours studying instead of working a $15/hr job. Opportunity cost is:",
             ["The grade earned",
              "$45 in forgone wages (plus any non-monetary alternative)",
              "$0",
              "Three hours of leisure only"], 1,
             "OC = next-best forgone use of those 3 hours, here $45 in forgone wages."),
            ("On the AP exam, a question asking 'optimal quantity' typically expects:",
             ["Maximize total benefit only",
              "Set MB = MC",
              "Minimize total cost",
              "Set price = cost"], 1,
             "Optimization rule across AP Micro: equate marginal benefit and marginal cost."),
            ("Which AP-style claim is correct?",
             ["Scarcity exists only in poor countries",
              "Even rich countries face scarcity because human wants are unlimited",
              "Scarcity disappears with technology",
              "Scarcity = shortage"], 1,
             "Scarcity is universal — it persists even in wealthy economies because wants outpace resources."),
        ]},
    "micro-supply-demand": {
        "title": "Supply & Demand",
        "qs": [
            ("The law of demand states that, ceteris paribus:",
             ["Higher price → higher quantity demanded",
              "Higher price → lower quantity demanded (downward-sloping D)",
              "Demand always rises",
              "Price doesn't affect quantity"], 1,
             "Law of demand: P↑ → Q_d↓ (substitution + income effects), holding other factors constant."),
            ("The law of supply states that, ceteris paribus:",
             ["Higher price → lower quantity supplied",
              "Higher price → higher quantity supplied (upward-sloping S)",
              "Supply is always vertical",
              "Price has no effect on Q_s"], 1,
             "Law of supply: P↑ → Q_s↑ (firms have higher MC at higher Q and need higher P to cover it)."),
            ("A movement ALONG the demand curve is caused by:",
             ["A change in income",
              "A change in the good's own price",
              "A change in price of a substitute",
              "A change in tastes"], 1,
             "Own-price change → movement along D (change in quantity demanded). Other factors → SHIFT of D."),
            ("Which causes demand for coffee to SHIFT RIGHT?",
             ["A rise in coffee's price",
              "A study showing coffee improves health (taste/preference change)",
              "A decrease in income (if coffee is normal)",
              "A drop in coffee bean prices"], 1,
             "Demand shifters: tastes, income (for normal goods), prices of related goods, expectations, # of buyers."),
            ("If income RISES and demand for ramen FALLS, ramen is:",
             ["A normal good",
              "An inferior good",
              "A complement",
              "A substitute"], 1,
             "Inferior good: demand falls as income rises. Examples: instant ramen, used cars, generic groceries."),
            ("Coffee and tea are SUBSTITUTES. A rise in coffee's price will:",
             ["Decrease tea demand",
              "Increase tea demand (shift right)",
              "Have no effect on tea",
              "Lower tea price"], 1,
             "Substitutes: when one's P rises, demand for the other shifts right."),
            ("Cars and gasoline are COMPLEMENTS. A fall in gasoline price will:",
             ["Decrease car demand",
              "Increase car demand (shift right)",
              "Have no effect",
              "Lower car price only"], 1,
             "Complements: when one's P falls, demand for the other shifts right."),
            ("A new technology that lowers production cost causes:",
             ["Demand to shift right",
              "Supply to shift right (lower MC at every Q)",
              "Demand to shift left",
              "Movement along supply only"], 1,
             "Supply shifters: input prices, technology, # of sellers, expected future prices, taxes/subsidies."),
            ("During the 2020 COVID toilet-paper shortage, equilibrium was disturbed by:",
             ["A leftward shift in supply only",
              "A sharp rightward shift in DEMAND (panic buying) overwhelming supply",
              "A leftward shift in demand",
              "Tariffs"], 1,
             "March 2020 saw demand surge from panic buying while supply chains had limited capacity → shortages and price spikes."),
            ("In the 1970s, OPEC oil embargoes caused gasoline shortages because:",
             ["Demand shifted right",
              "Supply shifted LEFT and U.S. price controls created persistent shortages and queues",
              "Price ceilings increased Q",
              "There was no shortage"], 1,
             "1973-74 OPEC embargo shifted oil supply left; U.S. price controls (Nixon 1971+) prevented prices from clearing → gasoline lines."),
            ("Equilibrium price is where:",
             ["Demand = Supply curves cross",
              "Quantity demanded = Quantity supplied (no shortage or surplus)",
              "Demand is highest",
              "MC = 0"], 1,
             "Equilibrium: Q_d = Q_s; market clears with no excess demand or supply."),
            ("If P > equilibrium price, the result is:",
             ["A shortage",
              "A surplus that pushes price down",
              "Equilibrium",
              "An increase in demand"], 1,
             "Above equilibrium: Q_s > Q_d → surplus → competitive pressure pushes P down toward equilibrium."),
            ("On the AP exam, a question asking the effect of two simultaneous shifts (e.g., D right and S right) tests:",
             ["Only the price effect (always rises)",
              "That one variable (P or Q) is determinate, the other indeterminate without magnitudes",
              "Both must rise",
              "Both must fall"], 1,
             "When D and S both shift right, Q definitely rises but P direction is indeterminate without knowing magnitudes."),
            ("Which AP-style claim is correct?",
             ["A change in the good's own price shifts the demand curve",
              "A change in the good's own price causes movement ALONG the demand curve",
              "Tastes shift only the supply curve",
              "Income shifts only the supply curve"], 1,
             "Own-price change → movement along D (Δquantity demanded). Other factors → shift of D (Δdemand)."),
        ]},
    "micro-demand-supply-equilibrium": {
        "title": "Market Equilibrium & Welfare",
        "qs": [
            ("Consumer surplus equals:",
             ["The area below price and above demand",
              "The area below demand and above price (down to Q traded)",
              "Total revenue",
              "Total cost"], 1,
             "CS = sum of (willingness to pay − price) across consumers = triangle below D, above P."),
            ("Producer surplus equals:",
             ["Area above supply and below price (up to Q traded)",
              "Total revenue",
              "Average cost × Q",
              "Profit minus fixed cost"], 0,
             "PS = sum of (price − minimum acceptable price) across producers = triangle above S, below P."),
            ("Total surplus is maximized at:",
             ["Maximum quantity",
              "Free-market equilibrium where MB = MC",
              "Minimum price",
              "Government-set quotas"], 1,
             "At free-market equilibrium, MB (D) = MC (S). Any other Q creates DWL — total surplus is maximized at equilibrium."),
            ("A binding price CEILING below equilibrium causes:",
             ["A surplus and falling price",
              "A shortage, DWL, and possible non-price rationing (queues, rationing)",
              "An increase in CS for all consumers",
              "Equilibrium to move higher"], 1,
             "Binding ceiling → Q_d > Q_s → shortage. Non-price rationing emerges; some consumers gain (lucky buyers), others get nothing."),
            ("A binding price FLOOR above equilibrium causes:",
             ["A shortage",
              "A surplus and DWL (e.g., minimum-wage unemployment)",
              "Equilibrium to fall",
              "No effect"], 1,
             "Binding floor → Q_s > Q_d → surplus. Examples: minimum wage (labor surplus = unemployment), agricultural price supports."),
            ("U.S. rent-control example: New York City under WWII-era controls (1943) led to:",
             ["Lower vacancy rates and reduced quality, with persistent shortages",
              "Increased housing supply",
              "Equilibrium pricing",
              "No effect"], 0,
             "NYC rent controls (since 1943) created chronic shortages, low vacancy, deferred maintenance — classic price-ceiling pathology."),
            ("U.S. minimum wage in 2024 (federal) is:",
             ["$5.15/hr",
              "$7.25/hr (unchanged since 2009)",
              "$15.00/hr",
              "$20.00/hr"], 1,
             "Federal min wage = $7.25 since July 2009 — though many states/cities have higher rates."),
            ("An excise tax on producers shifts:",
             ["Demand left by the tax",
              "Supply LEFT (upward) by the per-unit tax amount",
              "Both curves up",
              "Neither curve"], 1,
             "Per-unit tax on producers shifts S upward by exactly the tax wedge."),
            ("Tax incidence falls more heavily on the side with:",
             ["More elastic curve",
              "Less elastic (more inelastic) curve",
              "Equal elasticity",
              "Government regulation"], 1,
             "Inelastic side bears more of the tax — they have fewer alternatives, so they absorb more of the burden."),
            ("Calculate DWL of a $2/unit tax that reduces equilibrium Q from 100 to 80:",
             ["$0",
              "$20 (= ½ × $2 × 20)",
              "$200",
              "$160"], 1,
             "DWL = ½ × tax wedge × ΔQ = ½ × $2 × 20 = $20."),
            ("Calculate consumer surplus if WTP for first 10 units = $50 each, market price = $30:",
             ["$0",
              "$200 ((50−30) × 10)",
              "$500",
              "$300"], 1,
             "CS for inframarginal units = ($50 − $30) × 10 = $200."),
            ("If a price floor is set BELOW equilibrium price, the effect is:",
             ["Surplus",
              "Non-binding — no effect (market clears at equilibrium)",
              "Shortage",
              "DWL"], 1,
             "Floors below equilibrium and ceilings above equilibrium are non-binding — they don't affect outcomes."),
            ("On the AP exam, identifying DWL on a graph requires you to find:",
             ["The shaded area between MSB and MSC for units NOT traded due to the policy",
              "The total surplus rectangle",
              "Government revenue rectangle",
              "Consumer surplus only"], 0,
             "DWL = triangle between D (MSB) and S (MSC) for units between the new and original equilibrium quantities."),
            ("Which AP-style policy raises efficiency relative to a price control?",
             ["Quotas",
              "Lump-sum redistribution combined with free-market prices (avoid distorting allocation)",
              "Tariffs",
              "Price ceilings"], 1,
             "Lump-sum transfers achieve distributional goals without distorting marginal decisions → preserve allocative efficiency."),
        ]},
    "micro-elasticity": {
        "title": "Elasticity",
        "qs": [
            ("Price elasticity of demand (PED) measures:",
             ["Slope of the demand curve",
              "Percent change in Q_d divided by percent change in P (in absolute value)",
              "Total revenue",
              "Marginal cost"], 1,
             "PED = |%ΔQ_d / %ΔP|. Pure ratio of percentages — independent of units."),
            ("If |PED| > 1, demand is:",
             ["Inelastic",
              "Elastic (Q changes proportionally MORE than P)",
              "Unit elastic",
              "Perfectly inelastic"], 1,
             "Elastic: |PED| > 1 → consumers very responsive to price changes."),
            ("If |PED| < 1, raising price will:",
             ["Decrease total revenue",
              "Increase total revenue (TR)",
              "Have no effect on TR",
              "Always increase quantity sold"], 1,
             "Inelastic demand: price hike outweighs quantity loss → TR rises."),
            ("If |PED| > 1, raising price will:",
             ["Increase TR",
              "Decrease TR (Q falls more than P rises in %)",
              "Have no effect",
              "Always increase profit"], 1,
             "Elastic demand: quantity loss outweighs price hike → TR falls when P rises."),
            ("Determinants of demand elasticity include:",
             ["Income only",
              "Substitutes available, share of budget, time horizon, necessity vs luxury",
              "Cost of production",
              "Government regulation"], 1,
             "More substitutes, larger budget share, longer time horizon, and luxury status → MORE elastic demand."),
            ("Insulin demand for diabetics is highly:",
             ["Elastic",
              "Inelastic (no substitutes, necessity)",
              "Perfectly elastic",
              "Unit elastic"], 1,
             "Insulin = life-saving necessity with no close substitutes → highly inelastic demand."),
            ("Long-run gasoline demand is more ELASTIC than short-run because:",
             ["Cars become more important",
              "Consumers can switch vehicles, locations, or transit modes given enough time",
              "Government regulates more",
              "Prices fall"], 1,
             "Time allows substitution: hybrids, EVs, public transit, relocating closer to work → long-run E > short-run E."),
            ("Income elasticity of demand for normal goods is:",
             ["Negative",
              "Positive",
              "Zero",
              "Always greater than 1"], 1,
             "Normal goods: income↑ → demand↑ → income elasticity > 0. Luxuries have YED > 1; necessities have 0 < YED < 1."),
            ("Cross-price elasticity between two SUBSTITUTES is:",
             ["Negative",
              "Positive",
              "Zero",
              "Undefined"], 1,
             "Substitutes have positive cross-price elasticity (Coke price up → Pepsi demand up)."),
            ("Cross-price elasticity between two COMPLEMENTS is:",
             ["Negative",
              "Positive",
              "Zero",
              "Undefined"], 0,
             "Complements have negative cross-price elasticity (cars and gasoline; coffee and cream)."),
            ("Calculate PED using midpoint when P rises from $4 to $6 and Q falls from 100 to 80:",
             ["0.45",
              "0.56 (= |−22.2%/40%|)",
              "1.25",
              "2.00"], 1,
             "Midpoint: %ΔQ = (80−100)/90 = −22.2%; %ΔP = (6−4)/5 = 40%. PED = 22.2/40 = 0.555."),
            ("If demand is perfectly INELASTIC, the demand curve is:",
             ["Horizontal",
              "Vertical (Q doesn't change with P)",
              "Upward sloping",
              "Downward sloping with slope = 1"], 1,
             "Perfectly inelastic: PED = 0 → vertical demand curve. Real-world close approximation: insulin, life-saving treatments."),
            ("On the AP exam, the connection between elasticity and tax incidence is:",
             ["More elastic side bears more tax",
              "Less elastic (more inelastic) side bears more of the tax",
              "Tax falls equally regardless of elasticity",
              "Elasticity doesn't affect tax incidence"], 1,
             "Tax incidence: more inelastic side bears more burden (cigarette taxes mostly fall on consumers)."),
            ("Which AP-style scenario implies elastic demand?",
             ["Insulin",
              "Premium dining options at one of many local restaurants (many close substitutes)",
              "Water",
              "A life-saving medication"], 1,
             "Many close substitutes → high elasticity. Necessities with few substitutes → inelastic."),
        ]},
    "micro-production-costs": {
        "title": "Production & Costs",
        "qs": [
            ("In the SHORT RUN:",
             ["All inputs are variable",
              "At least one input (typically capital) is FIXED; others are variable",
              "All inputs are fixed",
              "Firms cannot produce"], 1,
             "Short run = at least one input fixed (usually plant size). Long run = all inputs variable."),
            ("The law of DIMINISHING MARGINAL RETURNS states that, holding fixed inputs constant:",
             ["Adding more variable input always raises MP",
              "Beyond some point, additional variable input adds LESS extra output (MP_L falls)",
              "MP rises forever",
              "Output cannot increase"], 1,
             "Diminishing MP: with fixed capital, each extra unit of labor eventually adds less extra output."),
            ("Marginal cost (MC) eventually RISES because of:",
             ["Diminishing marginal returns to the variable input",
              "Increasing returns to scale",
              "Falling input prices",
              "Government regulation"], 0,
             "Falling MP_L (diminishing returns) → rising MC: each extra unit of output requires more variable input."),
            ("ATC = AFC + AVC. As Q rises:",
             ["AFC rises",
              "AFC falls (fixed cost spread over more units); AVC eventually rises; ATC is U-shaped",
              "Both AFC and AVC always fall",
              "ATC is constant"], 1,
             "AFC = FC/Q always falls. AVC and ATC are U-shaped due to diminishing returns and spreading effect."),
            ("Marginal cost intersects ATC and AVC at:",
             ["Their maximums",
              "Their MINIMUMS (geometric property of marginal-average relationship)",
              "Q = 0",
              "Origin"], 1,
             "MC cuts ATC and AVC at their minimum points — when MC < AVG, AVG falls; when MC > AVG, AVG rises."),
            ("In the LONG RUN, all inputs are variable, so the long-run ATC (LRATC) shows:",
             ["Constant returns to scale always",
              "Economies of scale (LRATC falls), constant returns, then diseconomies of scale (LRATC rises)",
              "Always rising costs",
              "Always falling costs"], 1,
             "U-shaped LRATC: economies (specialization), then constant returns, then diseconomies (coordination problems)."),
            ("ECONOMIC profit differs from ACCOUNTING profit because:",
             ["Economic profit subtracts only explicit costs",
              "Economic profit subtracts both explicit AND implicit (opportunity) costs",
              "They are identical",
              "Accounting includes implicit costs only"], 1,
             "Accounting profit = Revenue − Explicit Costs. Economic profit = Revenue − Explicit − Implicit (opportunity) costs."),
            ("If Total Cost = $1,000 at Q = 100, then ATC equals:",
             ["$1,000",
              "$10 ($1,000/100)",
              "$100",
              "$1"], 1,
             "ATC = TC/Q = $1,000/100 = $10."),
            ("Henry Ford's 1913 moving assembly line at Highland Park reduced Model T production time per chassis from:",
             ["Days to weeks",
              "About 12.5 hours to 1.5 hours (achieving massive economies of scale)",
              "It had no effect",
              "Years to months"], 1,
             "Ford's assembly line cut chassis assembly from 12.5 hours (1913) to 1.5 hours, exemplifying economies of scale through specialization."),
            ("Calculate marginal cost between Q=10 (TC=$50) and Q=11 (TC=$58):",
             ["$8 (ΔTC/ΔQ)",
              "$58",
              "$5",
              "$108"], 0,
             "MC = ΔTC/ΔQ = ($58 − $50)/(11 − 10) = $8."),
            ("If MP_L is rising and the wage is constant, MC is:",
             ["Rising",
              "Falling (each extra worker adds more output for the same wage)",
              "Constant",
              "Zero"], 1,
             "MC = w/MP_L. Rising MP_L with constant w → MC falls (initial range before diminishing returns)."),
            ("If MC = $20 and ATC = $25 at Q = 100, then producing one more unit will:",
             ["Raise ATC",
              "LOWER ATC (since MC < ATC pulls average down)",
              "Leave ATC unchanged",
              "Raise FC"], 1,
             "When MC < ATC, average falls (you're adding a below-average cost unit). When MC > ATC, average rises."),
            ("On the AP exam, the SHUTDOWN price for a competitive firm is:",
             ["Minimum ATC",
              "Minimum AVC (below this, even VC isn't covered → firm shuts down in short run)",
              "Zero",
              "Maximum MC"], 1,
             "Short-run shutdown: P < min AVC → firm cannot cover variable costs → produce 0 (lose only FC)."),
            ("Which AP-style claim is correct?",
             ["Implicit costs are not real costs",
              "Implicit costs (e.g., owner's forgone wages) are real opportunity costs and reduce economic profit",
              "Implicit costs apply only to corporations",
              "Implicit costs equal sunk costs"], 1,
             "Implicit costs (forgone wages, forgone interest on owner's capital) are real opportunity costs — central to economic profit."),
        ]},
    "micro-perfect-competition": {
        "title": "Perfect Competition",
        "qs": [
            ("Perfectly competitive markets have:",
             ["A few large firms",
              "Many small firms, identical products, free entry/exit, perfect information",
              "Differentiated products",
              "Significant barriers to entry"], 1,
             "PC = many price-taking firms, homogeneous product, free entry, perfect information. Approximated by agriculture, currency markets."),
            ("A perfectly competitive firm's demand curve is:",
             ["Downward sloping",
              "Horizontal at the market price (perfectly elastic) — firm is a price taker",
              "Vertical",
              "Upward sloping"], 1,
             "Price-taking firm faces horizontal D = MR = AR = P at the market price."),
            ("Profit-maximization rule for a competitive firm is:",
             ["P = ATC",
              "P = MC = MR (set MR = MC where MC is rising)",
              "Maximum revenue",
              "Minimum AVC"], 1,
             "All firms maximize where MR = MC. For PC firms, MR = P, so P = MC (where MC slopes up)."),
            ("In the SHORT RUN, a competitive firm earns positive economic profit when:",
             ["P < ATC",
              "P > ATC at the profit-maximizing Q (where P = MC)",
              "P = AVC",
              "P = MC"], 1,
             "Profit per unit = P − ATC > 0. Total profit = (P − ATC) × Q."),
            ("A competitive firm's SHORT-RUN supply curve is:",
             ["The entire MC curve",
              "The portion of MC above the minimum AVC",
              "ATC curve",
              "AFC curve"], 1,
             "Short-run supply = MC above min AVC. Below min AVC, firm shuts down (Q=0)."),
            ("If a competitive firm earns positive economic profit in the short run, the LONG-RUN response is:",
             ["More firms exit",
              "New firms ENTER, supply shifts right, price falls until P = min ATC",
              "Existing firms expand only",
              "Government regulates"], 1,
             "Free entry response: profit attracts new firms → market S right → P falls → zero economic profit at long-run equilibrium."),
            ("In the LONG RUN, perfectly competitive firms earn:",
             ["Positive economic profit",
              "Zero economic profit (= normal profit, just covering all opportunity costs)",
              "Negative profit always",
              "Maximum profit"], 1,
             "LR equilibrium: P = min ATC = MC → zero economic profit. Firms earn normal accounting profit covering implicit costs."),
            ("Long-run equilibrium in perfect competition is characterized by:",
             ["P = MC = min ATC (productively AND allocatively efficient)",
              "P > MC always",
              "P < MC always",
              "P > min ATC"], 0,
             "PC LR: P = MC (allocative efficiency) AND P = min ATC (productive efficiency)."),
            ("Which real-world market most closely approximates perfect competition?",
             ["Smartphones",
              "Wheat farming and large agricultural commodity markets",
              "Auto manufacturing",
              "Pharmaceuticals"], 1,
             "Wheat: many small producers, homogeneous product, free entry, transparent commodity prices."),
            ("If P = $20 and a firm's MC = $20, ATC = $14, AVC = $10 at Q = 500, profit is:",
             ["−$2,000",
              "$3,000 (= ($20 − $14) × 500)",
              "$1,000",
              "$10,000"], 1,
             "Profit = (P − ATC) × Q = ($20 − $14)(500) = $3,000."),
            ("If P = $9 and AVC at the optimal Q = $10, the firm should:",
             ["Continue producing",
              "SHUT DOWN in the short run (P < AVC)",
              "Expand output",
              "Raise price"], 1,
             "Shutdown rule: P < min AVC → shut down (don't even cover VC). Firm loses only fixed costs."),
            ("If a competitive industry has rising input costs as it expands, the LONG-RUN industry supply is:",
             ["Horizontal",
              "Upward-sloping (increasing-cost industry)",
              "Vertical",
              "Downward-sloping"], 1,
             "Increasing-cost industry: as more firms enter, input prices rise → LR supply slopes up. Constant-cost = horizontal."),
            ("On the AP exam, a question asking how a positive demand shock affects PC firms in SR vs LR tests:",
             ["Just the SR price increase",
              "SR profit attracts entry, LR returns to zero economic profit at potentially new P (depending on industry cost structure)",
              "Permanent price increase",
              "No quantity change"], 1,
             "AP rubric: SR P↑, profit↑ → entry → LR S right → P returns toward original (constant-cost) or partway (increasing-cost)."),
            ("Which AP-style claim is correct?",
             ["PC firms set price",
              "PC firms are PRICE TAKERS — they accept the market price and choose Q",
              "PC firms have downward-sloping demand",
              "PC firms always earn positive profit"], 1,
             "Price-taking is the defining feature: each firm is too small to influence market price; choose only quantity."),
        ]},
    "micro-monopoly": {
        "title": "Monopoly",
        "qs": [
            ("A monopoly exists when:",
             ["Many firms compete",
              "A SINGLE firm is the sole producer with no close substitutes and high barriers to entry",
              "There are exactly two firms",
              "Firms are price takers"], 1,
             "Pure monopoly: one seller, unique product, blocked entry. Rare in pure form; degree of monopoly power varies."),
            ("Sources of monopoly power include:",
             ["Free entry",
              "Patents, control of key resources, government franchises, natural monopoly (economies of scale)",
              "Many small competitors",
              "Perfect information for all"], 1,
             "Barriers to entry: patents (drugs), key resources (De Beers diamonds), gov franchises (utilities), natural monopoly, network effects."),
            ("A monopolist's marginal revenue (MR) curve:",
             ["Equals price",
              "Lies BELOW the demand curve (because lowering P to sell one more unit reduces revenue on inframarginal units)",
              "Is horizontal",
              "Is vertical"], 1,
             "Monopolist faces downward D, so to sell more it must lower P on ALL units → MR < P. For linear D, MR has same intercept and twice the slope."),
            ("Profit-maximization for a monopoly:",
             ["P = MC",
              "MR = MC, then read price off the demand curve at Q*",
              "P = MR",
              "Maximum revenue"], 1,
             "All firms: MR = MC. For monopoly, MR < P, so P > MC at the profit-maximizing quantity (price markup)."),
            ("Compared to perfect competition, a single-price monopoly produces:",
             ["More output at lower price",
              "LESS output at HIGHER price, with deadweight loss",
              "The same Q and P",
              "Zero output"], 1,
             "Monopoly restricts output below competitive (where P = MC) and charges higher P → DWL triangle."),
            ("Deadweight loss in monopoly arises because:",
             ["Producer surplus is zero",
              "Units between Q_m and Q_eff have MSB > MSC but are not produced — society loses gains from trade",
              "MC > MR",
              "Government taxes"], 1,
             "Between Q_m and the allocatively efficient Q (where P = MC), MSB exceeds MSC — these mutually beneficial trades are forgone."),
            ("PERFECT (first-degree) price discrimination requires:",
             ["Many firms",
              "Market power, ability to identify each consumer's WTP, and prevent resale",
              "Free entry",
              "Constant returns to scale"], 1,
             "Three conditions: market power, identify WTP, no arbitrage. First-degree captures all CS as PS."),
            ("Under perfect price discrimination, the monopolist produces at:",
             ["Q_m (single-price)",
              "Q where P = MC (allocatively efficient quantity, no DWL, but all surplus to producer)",
              "Q = 0",
              "Q above MC = MR"], 1,
             "Perfect PD: each consumer charged WTP → MR = D → produce until P = MC. CS = 0; PS = entire trapezoid."),
            ("U.S. patent length for new drugs is generally:",
             ["5 years",
              "20 years from filing (often ~10-12 years effective after FDA approval)",
              "Forever",
              "1 year"], 1,
             "U.S. patents = 20 years from filing date. Drugs face long FDA review, so effective marketed life is shorter, then generics enter."),
            ("After Lipitor's 2011 patent expiration, generic atorvastatin entered, and the price fell roughly:",
             ["By less than 5%",
              "By 90%+ within a year (generic competition crashes monopoly markups)",
              "It remained the same",
              "It rose"], 1,
             "Lipitor's price fell ~95% within one year of generic entry, illustrating the impact of breaking monopoly via free entry."),
            ("If a monopolist faces P = 100 − Q and MC = $10, profit-maximizing Q satisfies MR = MC where MR = 100 − 2Q. Solve:",
             ["Q = 100",
              "Q = 45 (100 − 2Q = 10)",
              "Q = 90",
              "Q = 50"], 1,
             "MR = MC: 100 − 2Q = 10 → 2Q = 90 → Q = 45."),
            ("Continuing the previous question, P at Q=45 equals:",
             ["$10",
              "$55 (P = 100 − 45)",
              "$100",
              "$45"], 1,
             "P = 100 − Q = 100 − 45 = $55."),
            ("On the AP exam, identifying a monopoly's DWL requires shading:",
             ["The CS rectangle",
              "The triangle between Q_m and Q_eff (where D = MC), bounded above by D and below by MC",
              "The PS area",
              "The total surplus"], 1,
             "DWL = triangle between monopoly Q_m and competitive Q_eff, between D and MC."),
            ("Which AP-style policy can REDUCE monopoly DWL?",
             ["Raise barriers to entry",
              "Antitrust enforcement, price regulation (P = ATC for natural monopoly), patent shortening, public ownership",
              "Eliminate competition",
              "Increase the monopolist's MC"], 1,
             "Policy responses: antitrust (Sherman Act 1890), regulation, shorter patents, public utilities — to push P toward MC."),
        ]},
    "micro-monopolistic-oligopoly": {
        "title": "Monopolistic Competition & Oligopoly",
        "qs": [
            ("Monopolistic competition has:",
             ["One firm",
              "MANY firms with DIFFERENTIATED products and free entry/exit",
              "Two firms",
              "Identical products"], 1,
             "Mon comp: many firms (like PC) but differentiated products (each firm has slight market power)."),
            ("In the SHORT RUN, a monopolistically competitive firm:",
             ["Always earns zero profit",
              "Can earn positive economic profit (faces downward-sloping D, sets MR = MC)",
              "Always loses money",
              "Charges P = MC"], 1,
             "SR: like a monopoly, mon comp firm sets MR = MC and can earn positive economic profit."),
            ("In the LONG RUN, monopolistic competition:",
             ["Earns positive profit",
              "Earns ZERO economic profit (entry causes D to shift left until tangent to ATC)",
              "Behaves like pure monopoly",
              "Has negative profit"], 1,
             "Free entry erodes profit: D for each firm shifts left until tangent to ATC → P = ATC > MC, zero economic profit."),
            ("Monopolistic competition produces with:",
             ["Productive efficiency",
              "EXCESS capacity (P > MC and Q below min ATC) and product variety as a trade-off",
              "P = min ATC",
              "P = MC"], 1,
             "Mon comp LR: tangency on downward-sloping D means firm produces below min ATC (excess capacity); P > MC means allocative inefficiency."),
            ("Real-world examples of monopolistic competition include:",
             ["Wheat farming",
              "Restaurants, clothing brands, hair salons (many sellers, differentiated products)",
              "Local water utility",
              "Diamond mining"], 1,
             "Mon comp: restaurants, fashion brands, books, salons — differentiated by location, style, brand, quality."),
            ("Oligopoly is characterized by:",
             ["Many small firms",
              "A FEW large firms with mutual interdependence and significant barriers to entry",
              "One firm",
              "Identical products always"], 1,
             "Oligopoly: few firms (3-10), each firm's actions affect rivals → strategic interaction. Cars, airlines, oil refining."),
            ("In a Prisoner's Dilemma payoff matrix, the NASH EQUILIBRIUM is:",
             ["The cooperative outcome",
              "Each player's BEST RESPONSE given the other's choice; often inferior to cooperation",
              "Random",
              "Zero payoff"], 1,
             "Nash: no player can improve by unilateral deviation. In PD, dominant strategies → mutual defection (worse than cooperation)."),
            ("OPEC was founded in 1960 as a CARTEL to:",
             ["Eliminate oil production",
              "Coordinate output to raise prices and increase member revenue",
              "Privatize national oil companies",
              "Phase out fossil fuels"], 1,
             "OPEC (Organization of Petroleum Exporting Countries, 1960) coordinates production quotas to support oil prices — classic cartel."),
            ("OPEC members frequently CHEAT on production quotas because:",
             ["Quotas are non-binding",
              "Each member individually gains by exceeding quota when others comply (dominant defect strategy in repeated game)",
              "OPEC enforces strictly",
              "Cheating reduces revenue"], 1,
             "Each member's individual incentive: produce extra to capture revenue, while collective quota holds prices up. Classic cartel instability."),
            ("Repeated games can sustain cooperation through:",
             ["One-shot dominance",
              "Tit-for-tat strategies and credible punishment (Axelrod 1984)",
              "Random play",
              "Public announcements only"], 1,
             "In repeated games (Folk Theorem), credible punishment for defection (e.g., tit-for-tat) can sustain cooperation that fails in one-shot games."),
            ("If two firms have payoffs (50, 50) for cooperate and (30, 30) for defect, but defect is dominant, they end up at:",
             ["Cooperate (better outcome)",
              "Defect (Nash equilibrium); Pareto inferior outcome — Prisoner's Dilemma",
              "Mixed strategy",
              "No equilibrium"], 1,
             "Dominant defect strategy → both defect → (30,30) Nash equilibrium, despite (50,50) being available — Prisoner's Dilemma."),
            ("Compared to perfect competition, oligopoly typically has:",
             ["Lower prices",
              "Higher prices, lower output, and possible DWL (varies by market structure)",
              "Identical outcomes",
              "Zero profit always"], 1,
             "Oligopoly markup over MC creates DWL similar to monopoly, though magnitude varies with rivalry intensity."),
            ("On the AP exam, a question asking 'identify the dominant strategy' requires you to:",
             ["Look at row sums",
              "Compare each player's payoffs across the OTHER player's strategies; choose the strategy that's best regardless",
              "Add all payoffs",
              "Choose the highest single number"], 1,
             "Dominant strategy: best response to EVERY action of the opponent. Compare payoffs in each opponent column."),
            ("Which AP-style claim about cartels is correct?",
             ["Cartels are illegal in the U.S. under antitrust law (Sherman Act 1890)",
              "Cartels always succeed",
              "Cartels increase consumer surplus",
              "Cartels lower prices"], 0,
             "Sherman Antitrust Act 1890 § 1 prohibits price-fixing and output restriction agreements — cartels are per se illegal in the U.S."),
        ]},
    "micro-factor-markets": {
        "title": "Factor Markets (Labor & Capital)",
        "qs": [
            ("Demand for labor is a DERIVED demand, meaning:",
             ["Labor demand is independent of output",
              "Labor demand depends on the demand for the goods labor produces",
              "Labor demand is set by government",
              "Labor demand is fixed"], 1,
             "Derived demand: D for inputs comes from D for the outputs they help produce. If car demand falls, auto-worker demand falls."),
            ("Marginal Revenue Product of Labor (MRP_L) equals:",
             ["MP_L × P (in PC output market) or MP_L × MR (in imperfect output market)",
              "Total revenue",
              "Wage divided by output",
              "MC × Q"], 0,
             "MRP_L = MP_L × MR. In PC output market, MR = P, so MRP_L = MP_L × P (= VMP_L)."),
            ("A profit-maximizing firm hires labor up to:",
             ["L where MRP_L = wage (MFC in PC labor market)",
              "Until output is maximized",
              "Until MP_L = 0",
              "Until profit is zero"], 0,
             "Hiring rule: MRP_L = MFC_L. In PC labor market, MFC = wage → hire where MRP_L = w."),
            ("In a PERFECTLY COMPETITIVE labor market, the firm faces:",
             ["A horizontal supply of labor at the market wage (price taker)",
              "An upward-sloping supply",
              "A vertical supply",
              "A downward-sloping supply"], 0,
             "PC labor: firm is a wage-taker; supplies as much labor as it wants at market wage → horizontal MFC = w."),
            ("In a MONOPSONY labor market:",
             ["The firm is a wage-taker",
              "The firm is the sole employer; faces upward-sloping S_L; MFC > S_L (steeper)",
              "Many firms compete for workers",
              "There are no workers"], 1,
             "Monopsony: single buyer of labor → faces upward S_L; MFC steeper because hiring one more worker raises wage for ALL workers."),
            ("A monopsonist hires:",
             ["Where W = MRP_L",
              "FEWER workers and pays a LOWER wage than the competitive market",
              "Where MFC = wage",
              "More workers than competition"], 1,
             "Monopsony: MFC = MRP_L → L_m below competitive L_c; wage from S_L is below MRP_L. Wage and employment both lower."),
            ("A binding minimum wage in a competitive labor market:",
             ["Increases employment",
              "Creates UNEMPLOYMENT (Q_s > Q_d at the floor)",
              "Has no effect",
              "Lowers all wages"], 1,
             "PC labor + binding floor: surplus labor = unemployment (textbook result; magnitudes debated empirically)."),
            ("A binding minimum wage in a MONOPSONY labor market can:",
             ["Always reduce employment",
              "INCREASE both wages and employment (Card-Krueger 1994 result)",
              "Eliminate the market",
              "Have no effect"], 1,
             "Monopsony + min wage between W_m and W_c: effective MFC becomes horizontal at min wage → firm hires up to MRP = min wage → both W and L rise."),
            ("U.S. labor unions reached peak membership of about what % of the workforce in the mid-1950s?",
             ["5%",
              "About 35% (now ~10%)",
              "70%",
              "1%"], 1,
             "U.S. union density peaked at ~35% in 1954, has declined to ~10% by 2024 (BLS) — affecting wage-setting power."),
            ("Card and Krueger's 1994 study of New Jersey vs Pennsylvania fast-food workers found:",
             ["Massive job losses from minimum wage hikes",
              "Modest minimum-wage increases did NOT reduce employment in fast food, suggesting some monopsony power",
              "All restaurants closed",
              "Wages fell"], 1,
             "Card-Krueger 1994 NJ-PA min wage study challenged the textbook model, suggesting monopsony or other market frictions in low-wage labor markets."),
            ("Calculate MRP_L if MP_L = 5 units and P = $10 (PC output market):",
             ["$50 (5 × $10)",
              "$15",
              "$2",
              "$5"], 0,
             "MRP_L = MP_L × P = 5 × $10 = $50."),
            ("If MRP_L = $50 and wage = $40 in a PC labor market, the firm should:",
             ["Hire fewer workers",
              "Hire MORE workers (MRP > wage → profitable to expand)",
              "Hire same workers",
              "Stop producing"], 1,
             "MRP_L > wage → next worker adds more revenue than cost → hire more. Continue until MRP_L = w."),
            ("On the AP exam, a question asking 'how does monopsony differ from PC labor market' tests knowledge of:",
             ["MFC > S_L for monopsony, leading to lower L and W",
              "Only the wage rate",
              "Only employment level",
              "No difference"], 0,
             "Key AP point: monopsony's MFC > S_L → hires less labor at lower wage than PC equilibrium."),
            ("Which AP-style claim is correct?",
             ["Labor demand is independent of output prices",
              "Higher product prices INCREASE labor demand (since MRP_L = MP_L × P rises)",
              "Labor demand only depends on wage",
              "Labor demand is fixed"], 1,
             "MRP_L depends on P (output price) and MP_L. Output-price changes shift labor demand."),
        ]},
    "micro-labor-markets": {
        "title": "Labor Markets & Income Distribution",
        "qs": [
            ("The supply of labor is generally:",
             ["Backward-bending at very high wages (income effect dominates)",
              "Upward-sloping with possible backward-bend at very high wages",
              "Vertical",
              "Always horizontal"], 1,
             "Substitution effect: higher wage → more work. Income effect: higher wage → more leisure. SE dominates at low wages; IE may dominate at very high wages → backward-bending S_L."),
            ("Compensating wage differentials are higher pay to compensate for:",
             ["Higher productivity",
              "Unpleasant or risky job characteristics (e.g., logging, deep-sea fishing, night shift)",
              "Lower productivity",
              "Government regulation"], 1,
             "Adam Smith (1776): equally productive workers earn higher wages in dangerous, unpleasant, or stigmatized jobs to compensate."),
            ("Human capital investment (education, training) raises:",
             ["Labor demand only",
              "Worker productivity → higher MRP_L → higher wages",
              "Unemployment",
              "Sunk costs only"], 1,
             "Becker (1962, 1964): education raises productivity → MRP_L↑ → higher wages. Returns to schooling estimated 8-12% per year."),
            ("U.S. college wage premium (college vs HS earnings) rose from about 40% in 1980 to:",
             ["Below 20% by 2024",
              "About 65-80% by 2024 (skill-biased technological change)",
              "Constant at 40%",
              "Negative"], 1,
             "College premium rose sharply with computerization (Goldin-Katz 2008) — though has plateaued and even declined slightly post-2010."),
            ("Discrimination in labor markets (Becker 1957) implies:",
             ["No wage gaps",
              "Wage gaps not explained by productivity differences (e.g., gender gap, racial gap)",
              "Equal pay for equal work always",
              "Higher productivity for some groups"], 1,
             "Becker (1957) modeled discrimination as taste-based or statistical; produces wage gaps net of human capital."),
            ("U.S. female-to-male median earnings ratio for full-time workers in 2024 was approximately:",
             ["50%",
              "About 84% (with portion of gap explained by occupation/hours, residual unexplained)",
              "100%",
              "20%"], 1,
             "BLS 2024: women full-time, year-round earn ~84% of men. Adjusted gap (controlling for occupation, hours, experience) is smaller but persistent."),
            ("Income inequality in the U.S. has RISEN since 1980, with the top 1% income share rising from about:",
             ["20% to 40%",
              "10% in 1980 to about 22% by 2020 (Saez-Piketty data)",
              "Falling steadily",
              "Constant at 5%"], 1,
             "Top 1% income share rose from ~10% (1980) to ~22% (2020), a Gini-coefficient-amplifying trend (Piketty-Saez-Zucman)."),
            ("The Lorenz curve plots:",
             ["Wages vs hours worked",
              "Cumulative income share against cumulative population share",
              "GDP over time",
              "Unemployment vs inflation"], 1,
             "Lorenz curve: cumulative % of households (X) vs cumulative % of income (Y). Diagonal = perfect equality."),
            ("The Gini coefficient ranges from:",
             ["−1 to 1",
              "0 (perfect equality) to 1 (perfect inequality)",
              "0 to 100",
              "Negative numbers"], 1,
             "Gini = area between Lorenz curve and diagonal / total triangle area. 0 = perfect equality, 1 = one person has all income."),
            ("U.S. Gini coefficient (income, post-tax) is approximately:",
             ["0.20",
              "About 0.39-0.41 (one of the highest among OECD; Sweden ~0.27)",
              "0.80",
              "0.05"], 1,
             "U.S. post-tax Gini ≈ 0.39-0.41 (Census Bureau, OECD), higher than most peer rich countries."),
            ("Calculate labor's share of MRP if MP_L = 4 units, P = $25, wage = $80:",
             ["100% (wage = MRP_L = $100)",
              "80% (wage $80 / MRP_L $100)",
              "20%",
              "200%"], 1,
             "MRP_L = 4 × $25 = $100. Wage share = $80/$100 = 80%."),
            ("Earned Income Tax Credit (EITC, 1975+) is designed to:",
             ["Reduce labor supply",
              "Raise after-tax income for low-wage workers and increase labor supply (subsidy phases in)",
              "Tax labor",
              "Replace minimum wage"], 1,
             "EITC subsidizes low-wage work; CBO and Eissa-Liebman (1996) find positive labor-supply effect on single mothers."),
            ("On the AP exam, a question asking 'why do CEOs earn more than custodians' likely tests:",
             ["Discrimination only",
              "Differences in MRP_L (productivity, scarcity of skill, firm size, market for executive talent)",
              "Random factors",
              "Government regulation"], 1,
             "AP rubric: wages = MRP_L. CEOs at large firms have very high MRP because their decisions affect billions in shareholder value."),
            ("Which AP-style claim is correct?",
             ["Minimum wage always reduces employment",
              "Effect of minimum wage on employment is theoretically ambiguous in monopsony or imperfectly competitive labor markets",
              "Minimum wage has no effect",
              "Minimum wage helps only employers"], 1,
             "Empirically and theoretically, min wage effects depend on labor-market structure: PC predicts unemployment; monopsony allows employment to rise."),
        ]},
    "micro-government-intervention": {
        "title": "Government Intervention",
        "qs": [
            ("A binding price CEILING (e.g., rent control) below equilibrium causes:",
             ["A surplus and falling rents",
              "A SHORTAGE, DWL, deteriorating quality, and possible black markets",
              "Equilibrium pricing",
              "No effect"], 1,
             "Binding ceiling: Q_d > Q_s → shortage. Long-run effects: reduced quality, less new construction, queues."),
            ("A binding price FLOOR (e.g., minimum wage) above equilibrium causes:",
             ["A shortage of labor",
              "A SURPLUS of labor (unemployment) and DWL",
              "Equilibrium",
              "Lower wages"], 1,
             "Binding floor: Q_s > Q_d → surplus. Min wage above equilibrium → unemployment among low-skill workers (in textbook competitive model)."),
            ("Excise taxes on producers shift:",
             ["Demand left",
              "Supply LEFT (upward) by the per-unit tax — wedge between price paid and price received",
              "Both curves left",
              "Neither curve"], 1,
             "Per-unit tax on producers shifts S up by tax. New equilibrium: P_consumer > P_producer with wedge = tax."),
            ("Tax incidence falls more heavily on the side with:",
             ["Higher elasticity",
              "Lower elasticity (more inelastic side absorbs more)",
              "Equal elasticity",
              "Government regulation"], 1,
             "Incidence ∝ inelasticity. Cigarette taxes mostly fall on smokers (inelastic D); luxury taxes mostly fall on producers (elastic D)."),
            ("U.S. federal tariffs on Chinese imports rose sharply during:",
             ["1930s only",
              "2018-19 (Section 301 tariffs on $370B+) and 2024-25",
              "1995-2001",
              "Never"], 1,
             "Trump 2018-19 Section 301 tariffs on ~$370B Chinese imports; further escalations 2024-25 raise effective tariff rates further."),
            ("Smoot-Hawley Tariff Act (1930) raised tariffs on ~20,000 imports and:",
             ["Boosted U.S. exports",
              "Triggered retaliatory tariffs that contributed to the Great Depression's depth (international trade fell ~65%)",
              "Lowered domestic prices",
              "Eliminated unemployment"], 1,
             "Smoot-Hawley raised average tariffs to ~60%; world trade collapsed by ~65% by 1934, deepening the Depression (Eichengreen, Irwin)."),
            ("A subsidy to producers shifts:",
             ["Supply LEFT",
              "Supply RIGHT, lowering P_consumer and raising P_producer with deadweight loss (overproduction)",
              "Demand right",
              "No curves"], 1,
             "Per-unit subsidy = anti-tax. S shifts down/right by subsidy amount. New equilibrium: more Q, lower P_consumer, higher P_producer; DWL from overproduction beyond efficient."),
            ("U.S. agricultural price supports above market equilibrium typically lead to:",
             ["Shortage",
              "Surplus production that government must buy or store; commodity programs date to AAA 1933",
              "Higher consumer prices only",
              "No effect on Q"], 1,
             "Price floor above equilibrium → surplus. AAA 1933 (Agricultural Adjustment Act) created supply-management programs continuing in modified form today."),
            ("DWL from a per-unit tax equals:",
             ["Tax revenue",
              "½ × tax wedge × ΔQ (the lost-trades triangle)",
              "Total revenue",
              "Tax × Q traded"], 1,
             "DWL = ½ × t × ΔQ; tax revenue = t × Q_after-tax (separate area)."),
            ("U.S. NYC rent stabilization (post-1969) covers about how many apartments?",
             ["10 thousand",
              "About 1 million units (~50% of NYC rental stock)",
              "5 million",
              "Zero"], 1,
             "NYC has ~1 million rent-stabilized apartments (Census 2023, ~50% of rental stock); persistent shortages, deferred maintenance documented."),
            ("Calculate DWL of a $3/unit tax that reduces Q from 200 to 150:",
             ["$0",
              "$75 (= ½ × $3 × 50)",
              "$450",
              "$600"], 1,
             "DWL = ½ × tax wedge × ΔQ = ½ × $3 × 50 = $75."),
            ("Calculate tax revenue from the previous question:",
             ["$150",
              "$450 (= $3 × 150)",
              "$600",
              "$75"], 1,
             "Revenue = tax × Q_after-tax = $3 × 150 = $450."),
            ("On the AP exam, a question on 'who bears the burden of a payroll tax' likely tests:",
             ["Workers always",
              "Employers always",
              "Statutory vs. economic incidence — true incidence depends on relative elasticities, not who legally pays",
              "Both 50/50 always"], 2,
             "Economic incidence (who actually bears the burden) is independent of statutory incidence; depends on labor demand/supply elasticities."),
            ("Which AP-style claim is correct?",
             ["Tariffs always benefit consumers",
              "Tariffs raise domestic prices, reduce consumer surplus, increase producer surplus, raise gov revenue, and create DWL",
              "Tariffs eliminate DWL",
              "Tariffs reduce producer surplus"], 1,
             "Standard tariff effects: ↑P_domestic, ↓CS, ↑PS, ↑Gov revenue, net DWL (CS loss > PS + Rev gains)."),
        ]},
    "micro-externalities-public-goods": {
        "title": "Externalities & Public Goods",
        "qs": [
            ("A NEGATIVE production externality (e.g., pollution) results in:",
             ["Underproduction",
              "OVERPRODUCTION at the unregulated equilibrium because firms ignore external costs",
              "Equilibrium efficiency",
              "Zero output"], 1,
             "Negative externality: MSC > MPC. Free market produces where MPB = MPC, beyond the socially optimal Q (where MSB = MSC)."),
            ("A POSITIVE consumption externality (e.g., vaccinations) results in:",
             ["Overproduction",
              "UNDERCONSUMPTION at the unregulated equilibrium because consumers ignore external benefits",
              "Equilibrium efficiency",
              "Zero consumption"], 1,
             "Positive externality: MSB > MPB. Free market consumes where MPB = MPC < socially optimal (MSB = MSC)."),
            ("A Pigouvian TAX equal to the marginal external COST corrects:",
             ["Positive externalities",
              "NEGATIVE externalities by internalizing the external cost (shifts MPC to MSC)",
              "All market failures",
              "Income inequality"], 1,
             "Pigouvian tax = MEC. Adding it to MPC makes private cost = social cost → new private equilibrium = socially optimal."),
            ("A Pigouvian SUBSIDY equal to the marginal external BENEFIT corrects:",
             ["Negative externalities",
              "POSITIVE externalities by internalizing the external benefit (shifts MPB to MSB)",
              "Public goods only",
              "Inflation"], 1,
             "Subsidy = MEB lifts private benefit to social benefit; private optimal Q rises to social optimal."),
            ("Public goods are:",
             ["Excludable and rivalrous",
              "NON-EXCLUDABLE and NON-RIVALROUS (e.g., national defense, lighthouses, broadcast TV)",
              "Excludable but non-rivalrous",
              "Rivalrous but non-excludable"], 1,
             "Public goods: cannot exclude non-payers AND one person's use doesn't reduce another's. Examples: defense, lighthouses, basic research."),
            ("The free-rider problem leads to:",
             ["Overproduction of public goods",
              "Underproduction (private market underprovides; people understate WTP since they cannot be excluded)",
              "Efficient allocation",
              "Government surplus"], 1,
             "Free riders: each person hopes others pay. Private firms cannot recover costs → underprovision → market failure."),
            ("To value a public good, sum individual demands:",
             ["Horizontally",
              "VERTICALLY (since all consume the same unit, sum WTPs)",
              "Diagonally",
              "Don't sum"], 1,
             "Public goods: vertical sum of individual MBs = MSB (everyone consumes same unit). Private goods: horizontal sum."),
            ("Common-pool resources (e.g., fisheries, groundwater) are:",
             ["Excludable but non-rivalrous",
              "RIVALROUS but NON-EXCLUDABLE → tragedy of the commons (overuse)",
              "Public goods",
              "Private goods"], 1,
             "Commons = rivalrous + non-excludable → overuse. Hardin (1968) 'Tragedy of the Commons'; Ostrom (2009 Nobel) showed local institutions can manage."),
            ("The Coase Theorem (1960) states that, with WELL-DEFINED PROPERTY RIGHTS and LOW transaction costs:",
             ["Government must always intervene",
              "Private parties can BARGAIN to an efficient outcome regardless of initial rights assignment",
              "Externalities are impossible",
              "Markets always fail"], 1,
             "Coase 1960: with clear rights and low transaction costs, parties negotiate efficiently. Real-world transaction costs limit applicability."),
            ("EU Emissions Trading System (EU ETS) launched 2005 covers:",
             ["No sectors",
              "About 40% of EU GHG emissions via cap-and-trade allowance permits",
              "100% of all sectors",
              "Only agriculture"], 1,
             "EU ETS covers ~40% of GHG emissions (power, industry, intra-EU aviation); uses cap-and-trade to internalize carbon externality."),
            ("Calculate Pigouvian tax to correct an externality where MEC = $30/unit:",
             ["$0",
              "$30 per unit (set tax = MEC)",
              "$60",
              "$15"], 1,
             "Pigouvian tax = MEC = $30/unit, shifting MPC to coincide with MSC."),
            ("If three residents value a streetlight at $40, $30, $20 and MC = $75, the town should:",
             ["Not install (MSB = $90, but only $40 willing individually)",
              "Install — MSB = vertical sum = $90 > MC = $75",
              "Install only if all three pay equally",
              "Auction the streetlight"], 1,
             "Public good: MSB = vertical sum = $40+$30+$20 = $90 > MC = $75 → socially efficient to install. Free-rider problem prevents private provision."),
            ("On the AP exam, a question asking the socially optimal Q in a NEGATIVE externality graph requires you to find:",
             ["Where MPB = MPC (free market)",
              "Where MSB = MSC (lower than free-market Q)",
              "Where MSB = MPC",
              "Where MR = MC"], 1,
             "Socially optimal Q: where MSB intersects MSC. For negative externality, this is LESS than the unregulated Q."),
            ("Which AP-style policy is best for a NEGATIVE production externality?",
             ["Subsidy",
              "Pigouvian tax = MEC, OR cap-and-trade emission permits",
              "Price ceiling",
              "Tariff"], 1,
             "Both Pigouvian taxes and quantity instruments (cap-and-trade) can achieve the socially optimal Q if calibrated correctly."),
        ]},
    "micro-market-failure": {
        "title": "Market Failure & Asymmetric Information",
        "qs": [
            ("Market failure occurs when:",
             ["Markets always fail",
              "The free-market outcome is NOT allocatively efficient (e.g., externalities, public goods, info asymmetry, market power)",
              "Government regulates",
              "Producers earn profit"], 1,
             "Market failure = free market doesn't maximize total surplus. Sources: externalities, public goods, asymmetric info, market power."),
            ("ASYMMETRIC INFORMATION exists when:",
             ["Buyers and sellers have equal information",
              "One party has more information than the other (e.g., used cars, insurance, labor)",
              "Information is costless",
              "All info is public"], 1,
             "Asymmetric info: information advantage on one side. Akerlof (1970) showed this can collapse markets ('market for lemons')."),
            ("ADVERSE SELECTION arises when:",
             ["Both sides know the same things",
              "Hidden characteristics before contracting cause higher-risk types to disproportionately participate (e.g., sickest people buy health insurance)",
              "Behavior changes after contracting",
              "Government intervenes"], 1,
             "Adverse selection: hidden characteristics → low-quality types crowd out high-quality. Lemons in used cars; sickest enroll in insurance."),
            ("MORAL HAZARD arises when:",
             ["Hidden info before contract",
              "Behavior changes after contract because one party doesn't bear full consequences (e.g., insured drivers take more risk)",
              "All info is shared",
              "No contract is signed"], 1,
             "Moral hazard: hidden ACTION after contract. Insured drivers take more risk; bailed-out banks take more risk."),
            ("Akerlof's (1970) 'Market for Lemons' explains why:",
             ["Used car prices rise",
              "Asymmetric info can cause high-quality used cars to be DRIVEN OUT of the market (only lemons remain)",
              "Markets always work efficiently",
              "Government must own all car dealers"], 1,
             "Akerlof Nobel 2001 work: buyers can't tell good from bad cars → offer average price → owners of good cars don't sell → market unravels."),
            ("Health insurance markets often face adverse selection because:",
             ["Healthy people buy more",
              "Sicker people are more likely to enroll → premiums rise → healthy exit (death spiral)",
              "Government provides all insurance",
              "Premiums are equal for all"], 1,
             "ACA (2010) addresses this with mandates, subsidies, and community rating to keep healthy people in the pool."),
            ("Signaling (Spence 1973) refers to:",
             ["Hiding information",
              "Informed parties revealing characteristics through observable actions (e.g., education signals worker ability)",
              "Government regulation",
              "Random selection"], 1,
             "Spence Nobel 2001: education may signal pre-existing productivity rather than (or in addition to) building human capital."),
            ("The 2008 financial crisis was partly attributed to:",
             ["Equilibrium efficiency",
              "Asymmetric info in mortgage-backed securities (MBS originators knew quality, investors didn't); moral hazard from 'too big to fail'",
              "Excess government regulation",
              "Free trade"], 1,
             "GFC drivers included asymmetric info on subprime MBS quality, moral hazard from implicit bailout expectations (TBTF), and regulatory failures."),
            ("U.S. Dodd-Frank Act (2010) responded to the GFC by:",
             ["Eliminating banks",
              "Imposing higher capital requirements, stress tests, CFPB consumer protection, and Volcker Rule restrictions on prop trading",
              "Removing all regulation",
              "Fixing exchange rates"], 1,
             "Dodd-Frank 2010 introduced macroprudential regulation, Consumer Financial Protection Bureau, and Volcker Rule (limits proprietary trading)."),
            ("FDIC deposit insurance (1933, current limit $250,000) addresses:",
             ["Adverse selection only",
              "Bank-run dynamics + asymmetric info between depositors and banks (depositors can't easily verify bank solvency)",
              "Externalities",
              "Public goods"], 1,
             "FDIC reduces bank-run risk by guaranteeing deposits, eliminating depositors' need to monitor bank solvency in real-time."),
            ("If lemons make up 50% of used cars and quality is unverifiable, market price will likely:",
             ["Equal good-car value",
              "Fall toward the average between good and lemon, driving out good-car sellers (Akerlof)",
              "Equal lemon value only",
              "Rise above good-car value"], 1,
             "Market price reflects average expected quality → sellers of high-quality cars find offers too low → good cars exit, only lemons trade."),
            ("Moral hazard in 2008 banking arose because:",
             ["Banks bore all losses",
              "Implicit 'too big to fail' guarantees and bailouts meant banks took risks knowing taxpayers would absorb losses",
              "Banks were uninsured",
              "There was no Federal Reserve"], 1,
             "TBTF moral hazard: banks knew government would bail them out → took excessive leverage and risk. Bear Stearns (2008), AIG bailout exemplified this."),
            ("On the AP exam, a question on 'why insurance markets need regulation' likely tests:",
             ["Government wants to control",
              "Adverse selection (death spirals) and moral hazard make pure private insurance unstable",
              "Insurance is a luxury good",
              "Insurance is a public good"], 1,
             "AP rubric: insurance markets fail due to adverse selection (sicker enroll, premiums rise) and moral hazard (insured take more risk)."),
            ("Which AP-style claim is correct?",
             ["Government always improves efficiency when intervening",
              "Government can SOMETIMES improve efficiency (correcting market failure), but also can create government failure (rent-seeking, capture)",
              "Markets are always efficient",
              "Government should never intervene"], 1,
             "Both market failure and government failure are real; policy analysis weighs them case-by-case (Stigler 1971; Buchanan public choice)."),
        ]},
}


def render(slug: str, data: dict) -> str:
    title = data["title"]
    qs = data["qs"]
    assert len(qs) == 14, f"{slug}: need 14 questions, got {len(qs)}"

    lines = []
    for idx, (q, opts, correct, expl) in enumerate(qs):
        part_num = (idx // 2) + 1
        sub = "a" if idx % 2 == 0 else "b"
        qid = f"micr-ent-{part_num}{sub}"
        q = esc_money(q)
        opts = [esc_money(o) for o in opts]
        expl = esc_money(expl)
        opts_js = json.dumps(opts, ensure_ascii=False)
        lines.append(
            f"  {{ id: {json.dumps(qid)}, question: {json.dumps(q, ensure_ascii=False)}, "
            f"options: {opts_js}, correctIndex: {correct}, "
            f"explanation: {json.dumps(expl, ensure_ascii=False)}, "
            f"partNumber: {part_num}, partTitle: {json.dumps(PART_TITLES[part_num])} }}"
        )

    body = ",\n".join(lines)
    return (
        f"/**\n"
        f" * Entrance Quiz — {title} (AP Microeconomics)\n"
        f" * 14 questions · 7 parts (2 per part)\n"
        f" * AUTO-GENERATED by scripts/write-micro-entrance-quizzes.py\n"
        f" */\n\n"
        f"import type {{ EntranceQuizQuestion }} from './moles-molar-mass'\n\n"
        f"const questions: EntranceQuizQuestion[] = [\n{body}\n]\n\n"
        f"export function generateEntranceQuiz(): EntranceQuizQuestion[] {{\n"
        f"  return [...questions].sort(() => Math.random() - 0.5)\n"
        f"}}\n\n"
        f"export function getEntranceQuizParts(): {{ partNumber: number; partTitle: string }}[] {{\n"
        f"  return [\n"
        f"    {{ partNumber: 1, partTitle: 'Core Concepts' }},\n"
        f"    {{ partNumber: 2, partTitle: 'Key Processes' }},\n"
        f"    {{ partNumber: 3, partTitle: 'Patterns & Examples' }},\n"
        f"    {{ partNumber: 4, partTitle: 'Connections & Interactions' }},\n"
        f"    {{ partNumber: 5, partTitle: 'Change Over Time' }},\n"
        f"    {{ partNumber: 6, partTitle: 'Problem-Solving Workshop' }},\n"
        f"    {{ partNumber: 7, partTitle: 'AP Review' }}\n"
        f"  ]\n"
        f"}}\n"
    )


def main():
    expected = {
        "micro-demand-supply-equilibrium", "micro-elasticity",
        "micro-externalities-public-goods", "micro-factor-markets",
        "micro-government-intervention", "micro-labor-markets",
        "micro-market-failure", "micro-monopolistic-oligopoly",
        "micro-monopoly", "micro-perfect-competition",
        "micro-production-costs", "micro-scarcity-marginal-analysis",
        "micro-supply-demand",
    }
    missing = expected - set(T)
    extra = set(T) - expected
    if missing:
        raise SystemExit(f"Missing topics: {missing}")
    if extra:
        raise SystemExit(f"Unexpected topics: {extra}")

    for slug, data in T.items():
        path = os.path.join(OUT_DIR, f"{slug}.ts")
        with open(path, "w", encoding="utf-8") as f:
            f.write(render(slug, data))
        print(f"Wrote {path}")
    print(f"\nDone: {len(T)} entrance quiz files.")


if __name__ == "__main__":
    main()
