#!/usr/bin/env python3
"""
AAS entrance quizzes — Batch 2 (5 topics):
  aas-freedom-enslavement, aas-reconstruction-jim-crow, aas-wwi-wwii-era,
  aas-great-migration-harlem, aas-civil-rights-movement
"""
from __future__ import annotations
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _aas_quiz_common import write_batch  # type: ignore

T: dict = {}

# ────────────────────────────────────────────────────────────────────────────
# 6. Freedom & Enslavement (Civil War era)
# ────────────────────────────────────────────────────────────────────────────
T["aas-freedom-enslavement"] = {
    "title": "Freedom & Enslavement (Civil War Era)",
    "prefix": "aasfre",
    "qs": [
        # Part 1
        ("In AP African American Studies, the \"contraband of war\" doctrine refers to:",
         ["A naval blockade strategy unrelated to slavery.",
          "Union General Benjamin Butler's May 1861 decision at Fort Monroe, Virginia, to refuse return of three escaped enslaved men — Frank Baker, James Townsend, and Shepard Mallory — declaring them \"contraband of war,\" a precedent that drew tens of thousands of self-emancipating Black people behind Union lines.",
          "A 19th-century tariff policy on imported cotton.",
          "A purely Confederate legal category."],
         1,
         "Butler's contraband doctrine (May 1861) — codified in the First Confiscation Act (Aug 1861) — turned escape into a de facto wartime emancipation route long before the formal proclamation."),
        ("Which best describes \"self-emancipation\" during the Civil War?",
         ["A strategy in which the Confederate government voluntarily freed enslaved people.",
          "The process by which enslaved African Americans — perhaps 500,000 by war's end — fled to Union lines, joined the Union army and navy, or simply abandoned plantations, forcing federal policy toward emancipation, as historian Steven Hahn argues in *A Nation Under Our Feet* (2003).",
          "A formal British colonial program.",
          "A 21st-century academic concept with no wartime referent."],
         1,
         "Self-emancipation describes Black people's own agency — fleeing to Union lines and enlisting — that pushed Lincoln and Congress toward emancipation. Roughly 500,000 escaped during the war."),
        # Part 2
        ("Lincoln's Emancipation Proclamation, effective January 1, 1863, did what?",
         ["Freed all enslaved people in the United States immediately.",
          "Declared free all enslaved people in Confederate-held territory not yet under Union control, recharacterized the war as a war for emancipation, and authorized Black enlistment in the U.S. Army — but did not free enslaved people in loyal border states or already-occupied Confederate areas.",
          "Outlawed slavery in the loyal border states first.",
          "Ended the Civil War in January 1863."],
         1,
         "The Proclamation was a wartime measure under Lincoln's commander-in-chief authority — it freed enslaved people in rebellious areas not under Union control and opened Black enlistment; full national abolition required the 13th Amendment (1865)."),
        ("The 54th Massachusetts Volunteer Infantry, mustered in 1863, is significant because:",
         ["It was the first all-Black regiment of the Civil War.",
          "It was one of the earliest official Black regiments in the U.S. Army; led by Col. Robert Gould Shaw, it suffered heavy losses at Fort Wagner, S.C. (July 18, 1863), demonstrating Black soldiers' valor and accelerating Black enlistment under the United States Colored Troops (USCT) — ultimately ~180,000 Black soldiers and ~19,000 sailors.",
          "It was a Confederate cavalry unit.",
          "It served only on garrison duty far from combat."],
         1,
         "Fort Wagner (July 18, 1863) and the 54th Massachusetts catalyzed wider Black enlistment under the USCT — ~180,000 Black soldiers + 19,000 sailors served by 1865, roughly 10% of the Union army."),
        # Part 3
        ("Which dated event most clearly marked the constitutional end of slavery in the United States?",
         ["The First Confiscation Act (1861).",
          "The Thirteenth Amendment, passed by Congress January 31, 1865 and ratified December 6, 1865, which abolished slavery and involuntary servitude \"except as a punishment for crime\" throughout the United States.",
          "The Compromise of 1877.",
          "The Wade-Davis Bill (1864)."],
         1,
         "The 13th Amendment (ratified December 6, 1865) constitutionally abolished slavery — the EP (1863) and Confiscation Acts (1861/62) were wartime measures of more limited scope."),
        ("Which best describes the Freedmen's Bureau, established by Congress in March 1865?",
         ["A long-term federal agency that survived into the 20th century.",
          "The Bureau of Refugees, Freedmen, and Abandoned Lands — operated 1865–1872 under the War Department — distributed rations, established roughly 3,000 schools and the historically Black colleges (Howard, Fisk, Hampton among them), adjudicated labor contracts, and helped reunite families separated by sale.",
          "A Confederate veterans' welfare agency.",
          "A purely state-level institution in South Carolina only."],
         1,
         "The Freedmen's Bureau (1865–1872) provided food, schools (~3,000 founded; Howard, Fisk, Hampton tied to Bureau-era support), and labor adjudication — a foundational Reconstruction institution."),
        # Part 4
        ("How does the Freedom & Enslavement unit connect to the Resistance & Abolition unit?",
         ["The two units cover unrelated subjects.",
          "Black self-emancipation, USCT enlistment, and abolitionist pressure (Frederick Douglass's meetings with Lincoln in 1863 and 1864; the *North Star* and AME church networks) converted a war for Union into a war for emancipation — the culmination of decades of Black-led resistance and abolitionist organizing.",
          "Self-emancipation never occurred during the war.",
          "Black abolitionists played no role in wartime emancipation."],
         1,
         "AP synthesis links wartime self-emancipation and USCT service to the longer arc of Black resistance and abolition (Douglass, AME, *North Star*) that pressured federal policy toward emancipation."),
        ("Which AP analytical skill is most directly tested by comparing the Emancipation Proclamation (1863) and the Thirteenth Amendment (1865)?",
         ["Memorization without comparison.",
          "Comparison: shared aim (ending slavery) but different scope (the EP was a war measure limited to Confederate-held territory; the 13th Amendment was a constitutional, nationwide ban with the \"except as a punishment for crime\" exception).",
          "Free recall of unrelated events.",
          "Citing only modern policy debates."],
         1,
         "AP comparison rewards explicit similarity *and* difference — same aim, different legal authority and reach (war power vs. constitutional amendment; partial vs. national)."),
        # Part 5
        ("Which dated event marked a turning point from war emancipation toward Reconstruction politics?",
         ["The Tenure of Office Act (1867).",
          "The April 14, 1865 assassination of Abraham Lincoln by John Wilkes Booth at Ford's Theatre, which elevated Andrew Johnson — a Tennessee Unionist hostile to Black political rights — to the presidency just five days after Appomattox.",
          "The Battle of Antietam (1862).",
          "The Pendleton Act (1883)."],
         1,
         "Lincoln's April 14, 1865 assassination brought Andrew Johnson to power; his lenient white-restoration Reconstruction policies clashed with Radical Republicans and shaped the politics of Black freedom 1865–1868."),
        ("Which best describes a continuity from slavery into the immediate postwar era?",
         ["All vestiges of unfree labor ended on January 1, 1863.",
          "The 13th Amendment's \"except as a punishment for crime\" clause and the Black Codes (Mississippi 1865; South Carolina 1865) — combined with sharecropping, debt peonage, and convict leasing — preserved coercive labor regimes that constrained Black freedom long after formal emancipation.",
          "Black Southerners enjoyed full economic and political equality by 1866.",
          "Sharecropping was abolished in 1865."],
         1,
         "Continuity = coercive labor under new legal forms — Black Codes (1865), sharecropping, debt peonage, convict leasing under the 13th Amendment's punishment exception."),
        # Part 6
        ("A historian wants to study Black soldiers' experiences in their own words. Which source is most directly useful?",
         ["A modern novel about the Civil War.",
          "Letters and pension files of United States Colored Troops soldiers, the *Christian Recorder* (AME newspaper), and Frederick Douglass's editorials (e.g., \"Men of Color, To Arms!,\" March 1863) calling for Black enlistment.",
          "An undated anonymous broadside.",
          "Confederate cabinet memoranda only."],
         1,
         "USCT pension files, the *Christian Recorder*, and Douglass's recruiting editorials are core primary sources for AP analysis of Black wartime experience."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point on Lincoln's 1863 Emancipation Proclamation?",
         ["Quoting it without comment.",
          "Noting that Lincoln issued it under his commander-in-chief war power, after the partial Union victory at Antietam (Sept 1862), targeting Confederate-held territory specifically — and using that situation and purpose to explain its limited geographic reach.",
          "Citing only its date with no analysis.",
          "Ignoring Lincoln's audience and motivation."],
         1,
         "AP sourcing requires *use* of audience/purpose/situation — Lincoln's war-power authority, post-Antietam timing, and military rationale shape the Proclamation's contours."),
        # Part 7
        ("Which is the strongest one-sentence thesis on freedom and enslavement in the Civil War era?",
         ["The Civil War ended slavery.",
          "Between 1861 and 1865, Black self-emancipation, USCT military service, abolitionist pressure, and federal action (the contraband doctrine 1861, EP 1863, USCT enlistment, and the 13th Amendment ratified 1865) together transformed a war for Union into a war for emancipation — though the 13th Amendment's punishment exception and postwar Black Codes preserved coercive labor regimes.",
          "Slavery ended without African American participation.",
          "The Civil War had no constitutional consequences."],
         1,
         "Strong AP theses combine periodization (1861–65), Black agency, named federal acts, and a complexity move (13th Am punishment exception + Black Codes)."),
        ("On the AP exam, the strongest move when writing about Civil War-era freedom is to:",
         ["Avoid all dates and named figures.",
          "Anchor claims in a named figure (Douglass, Butler, Tubman, Robert Gould Shaw), a dated event (May 1861 Fort Monroe contraband, Jan 1, 1863 EP, July 18, 1863 Fort Wagner, Dec 6, 1865 13th Amendment), and a primary source (Douglass's \"Men of Color, To Arms!\" 1863, the EP).",
          "Cite no sources at all.",
          "Use only modern op-eds."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# 7. Reconstruction & Jim Crow
# ────────────────────────────────────────────────────────────────────────────
T["aas-reconstruction-jim-crow"] = {
    "title": "Reconstruction & Jim Crow",
    "prefix": "aasrjc",
    "qs": [
        # Part 1
        ("The \"Reconstruction Amendments\" comprise:",
         ["The 1st, 2nd, and 4th Amendments.",
          "The 13th (1865, abolishing slavery), 14th (1868, citizenship and equal protection), and 15th (1870, voting rights regardless of race).",
          "The 18th, 19th, and 21st Amendments.",
          "The 22nd, 23rd, and 24th Amendments."],
         1,
         "The Reconstruction Amendments — 13th (1865), 14th (1868), 15th (1870) — established constitutional birthright citizenship, equal protection, due process, and the right to vote regardless of race."),
        ("\"Jim Crow\" most precisely refers to:",
         ["A Reconstruction-era civil rights coalition.",
          "The system of state and local laws and customs that mandated racial segregation in the U.S. South (and, more informally, the North) from roughly the 1880s through the 1960s — named after a blackface minstrel character popularized by Thomas \"Daddy\" Rice in the 1830s.",
          "A federal voting rights program of the 1870s.",
          "A 21st-century academic theory only."],
         1,
         "\"Jim Crow\" — from the antebellum minstrel character — became shorthand for de jure segregation laws (separate schools, transit, drinking fountains, etc.) that crystallized in the 1880s–90s."),
        # Part 2
        ("Which 1896 Supreme Court decision provided the constitutional foundation for de jure segregation?",
         ["*Dred Scott v. Sandford* (1857).",
          "*Plessy v. Ferguson* (1896), which upheld Louisiana's Separate Car Act under the doctrine of \"separate but equal,\" with Justice John Marshall Harlan as the lone dissenter declaring the Constitution \"color-blind.\"",
          "*Brown v. Board of Education* (1954).",
          "*Korematsu v. United States* (1944)."],
         1,
         "*Plessy v. Ferguson* (1896) constitutionalized \"separate but equal\" until *Brown v. Board* (1954); Harlan's dissent (\"Our Constitution is color-blind\") became foundational to later civil rights jurisprudence."),
        ("Which methods most centrally enforced Black disenfranchisement in the Jim Crow South?",
         ["Federal supervision of every Southern election.",
          "Poll taxes (Mississippi Plan 1890), literacy tests, the white primary (rendered unconstitutional in *Smith v. Allwright* 1944), grandfather clauses (struck down in *Guinn v. United States* 1915), and racial terror — including roughly 4,400 documented lynchings 1877–1950 (Equal Justice Initiative).",
          "Mandatory federal voter registration of Black citizens.",
          "Compulsory voting laws."],
         1,
         "Disenfranchisement combined legal devices (Mississippi Plan 1890, literacy tests, white primary, grandfather clauses) with extrajudicial racial terror (~4,400 lynchings 1877–1950 per the Equal Justice Initiative)."),
        # Part 3
        ("Which dated event illustrates the political achievements of Black Reconstruction?",
         ["The 1872 election of Frederick Douglass as president.",
          "The 1870 election of Hiram Revels (Mississippi) to the U.S. Senate — the first Black U.S. Senator — and the service of about 2,000 Black officeholders during Reconstruction (16 in Congress, including Joseph Rainey of South Carolina, the first Black member of the U.S. House).",
          "The 1880 founding of the NAACP.",
          "The 1900 ratification of the 19th Amendment."],
         1,
         "Hiram Revels (1870) was the first Black U.S. Senator; Joseph Rainey (1870) the first Black U.S. House member; ~2,000 Black officeholders served during Reconstruction (Eric Foner, *Reconstruction*, 1988)."),
        ("Which best characterizes the Compromise of 1877?",
         ["A constitutional amendment guaranteeing Black voting rights.",
          "An informal political bargain that resolved the disputed 1876 Hayes–Tilden election: Republican Rutherford B. Hayes received the presidency in exchange for the withdrawal of remaining federal troops from Louisiana and South Carolina, effectively ending federal Reconstruction enforcement.",
          "A federal land-grant program for freedpeople.",
          "A treaty with European powers about cotton tariffs."],
         1,
         "The Compromise of 1877 (Hayes–Tilden) ended federal military Reconstruction in the South and inaugurated the slow consolidation of \"Redeemer\" white-supremacist Democratic rule and Jim Crow."),
        # Part 4
        ("How does Reconstruction connect to the later Civil Rights Movement?",
         ["The two periods are unrelated.",
          "The 13th, 14th, and 15th Amendments (1865–1870) provided the constitutional foundation that Civil Rights Movement litigation (NAACP Legal Defense Fund) and federal legislation (Civil Rights Act 1964, Voting Rights Act 1965) later activated against Jim Crow — what Eric Foner calls Reconstruction's \"unfinished revolution.\"",
          "The Civil Rights Movement avoided the Reconstruction Amendments.",
          "Reconstruction was reversed completely with no lasting legal foundation."],
         1,
         "Foner (*Reconstruction*, 1988) frames Reconstruction as an \"unfinished revolution\" — its constitutional foundation underwrote later civil rights litigation and legislation."),
        ("Which AP analytical skill is foregrounded by comparing W. E. B. Du Bois and Booker T. Washington?",
         ["Memorization without comparison.",
          "Comparison: both responded to Jim Crow, but Washington's 1895 \"Atlanta Compromise\" emphasized vocational education and economic self-help while accommodating disenfranchisement; Du Bois's *The Souls of Black Folk* (1903) called for the \"Talented Tenth,\" liberal arts education, and immediate civil and political rights — leading to the Niagara Movement (1905) and NAACP (1909).",
          "Free recall of unrelated facts.",
          "Citing only modern sources."],
         1,
         "AP comparison rewards explicit similarity *and* difference — Washington (1895 Atlanta) vs. Du Bois (1903 *Souls*; 1905 Niagara; 1909 NAACP) defined the central postbellum strategic debate."),
        # Part 5
        ("Which best describes a major change between Reconstruction and the early 20th-century South?",
         ["No political change occurred between 1870 and 1900.",
          "Black voter participation collapsed: in Louisiana, 130,344 Black men were registered in 1896, but only 1,342 by 1904, after the state's 1898 disenfranchisement constitution — a pattern repeated across Mississippi (1890), South Carolina (1895), and other Southern states.",
          "Black voter participation rose continuously through 1900.",
          "Federal troops continued to enforce Black voting rights through 1900."],
         1,
         "Louisiana's collapse from 130,344 Black registered voters (1896) to 1,342 (1904) exemplifies the post-1890 disenfranchisement wave (Mississippi 1890, South Carolina 1895, Louisiana 1898)."),
        ("Which best describes a continuity across Reconstruction and the Jim Crow era?",
         ["Black political mobilization disappeared after 1877.",
          "Despite disenfranchisement, Black communities sustained continuous institution-building — historically Black colleges and universities (HBCUs); the Black church (AME, AME Zion, NBC); the Black press (e.g., the *Chicago Defender* 1905); fraternal orders; and protest organizations from the Niagara Movement (1905) through the NAACP (1909) and Ida B. Wells's antilynching campaigns (from 1892).",
          "All Black institutions collapsed by 1880.",
          "There was no Black press before 1950."],
         1,
         "Continuity = sustained Black institution-building (HBCUs, churches, press, NAACP) and resistance (Wells's antilynching from 1892) even under disenfranchisement."),
        # Part 6
        ("A student wants to analyze the strategy of the early NAACP. Which source is most directly useful?",
         ["A 21st-century policy memo.",
          "The NAACP's *The Crisis* magazine (founded 1910, edited by W. E. B. Du Bois), the *Niagara Movement Declaration of Principles* (1905), and the NAACP's antilynching campaigns and case files (e.g., *Buchanan v. Warley* 1917 striking down residential segregation ordinances).",
          "An undated anonymous flyer.",
          "A modern blog with no archival sourcing."],
         1,
         "*The Crisis* (Du Bois, from 1910), the Niagara Declaration (1905), and early NAACP cases (*Buchanan v. Warley* 1917) are core primary sources for early civil rights strategy."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point on Booker T. Washington's 1895 Atlanta Exposition speech?",
         ["Quoting it without comment.",
          "Noting that Washington spoke to a mostly white Southern audience at the 1895 Cotton States and International Exposition, in the context of post-1877 Redemption and rising lynching, and using that audience and situation to evaluate his \"cast down your bucket where you are\" accommodationist appeal.",
          "Citing only its date with no analysis.",
          "Ignoring his audience entirely."],
         1,
         "AP sourcing requires *use* of audience/purpose/situation — Washington's white Southern Atlanta audience in 1895, amid disenfranchisement and lynching, is essential to interpreting the speech."),
        # Part 7
        ("Which is the strongest one-sentence thesis on Reconstruction and Jim Crow?",
         ["Reconstruction was a brief experiment.",
          "Between 1865 and the early 20th century, Reconstruction's constitutional revolution (13th, 14th, 15th Amendments) and brief Black political ascendancy (~2,000 officeholders) were rolled back by white-supremacist violence, the Compromise of 1877, *Plessy v. Ferguson* (1896), and disenfranchisement laws — yet the Reconstruction Amendments survived as a legal foundation that Black-led organizing (Wells, Du Bois, the NAACP) preserved for later civil rights litigation.",
          "Black freedom was secured permanently in 1870.",
          "Jim Crow had no constitutional foundation."],
         1,
         "Strong AP theses combine periodization, the rise-and-rollback arc, named legal landmarks, and a complexity move (constitutional foundation surviving for later use)."),
        ("On the AP exam, the strongest move when writing about Reconstruction and Jim Crow is to:",
         ["Avoid all dates and named figures.",
          "Anchor claims in a named figure (Hiram Revels, Ida B. Wells, Du Bois, Booker T. Washington), a dated event (1865 13th Am, 1868 14th, 1870 15th, 1877 Compromise, 1890 Mississippi Plan, 1896 *Plessy*, 1909 NAACP), and a primary source (the *Niagara Declaration* 1905, Du Bois's *Souls* 1903).",
          "Cite no sources at all.",
          "Use only 21st-century pop culture."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# 8. WWI / WWII Era
# ────────────────────────────────────────────────────────────────────────────
T["aas-wwi-wwii-era"] = {
    "title": "WWI / WWII Era",
    "prefix": "aasww",
    "qs": [
        # Part 1
        ("In AP African American Studies, the \"Double V\" campaign of WWII referred to:",
         ["Victory in the air and at sea, with no domestic dimension.",
          "A 1942 *Pittsburgh Courier* slogan — Victory over fascism abroad and Victory over racism at home — that framed Black wartime service as a claim on full citizenship.",
          "A military strategy unrelated to civil rights.",
          "A 21st-century branding campaign."],
         1,
         "James G. Thompson's January 1942 letter to the *Pittsburgh Courier* launched the Double V campaign, linking the global anti-fascist war to the domestic struggle against Jim Crow."),
        ("The Harlem Hellfighters (369th Infantry Regiment) in WWI are significant because:",
         ["They never deployed overseas.",
          "Assigned to the French army because of U.S. military segregation, they spent 191 days in combat — longer than any other U.S. regiment — and earned the *Croix de Guerre*; their service highlighted the contradiction between Black sacrifice and Jim Crow at home.",
          "They served only as cooks and laborers behind the lines.",
          "They fought for the Central Powers."],
         1,
         "The 369th Infantry — assigned to French command due to U.S. Army segregation — spent 191 days in combat, the longest of any U.S. regiment in WWI, and were collectively awarded the French *Croix de Guerre*."),
        # Part 2
        ("Which executive order banned racial discrimination in the federal defense industry during WWII?",
         ["Executive Order 9066 (1942).",
          "Executive Order 8802 (June 25, 1941), issued by President Franklin D. Roosevelt under pressure from A. Philip Randolph's threatened March on Washington Movement, which also created the Fair Employment Practices Committee (FEPC).",
          "Executive Order 9981 (1948).",
          "Executive Order 10925 (1961)."],
         1,
         "EO 8802 (June 25, 1941) banned racial discrimination in defense industries and created the FEPC; it was extracted from FDR by A. Philip Randolph's MOWM threat."),
        ("Which 1948 executive order desegregated the U.S. armed forces?",
         ["Executive Order 8802 (1941).",
          "Executive Order 9981 (July 26, 1948), signed by President Harry S. Truman, which directed the integration of the U.S. armed forces — a process completed during the Korean War (1950–1953).",
          "Executive Order 9066 (1942).",
          "Executive Order 11246 (1965)."],
         1,
         "Truman's EO 9981 (July 26, 1948) ordered desegregation of the armed forces; integration was largely accomplished during the Korean War."),
        # Part 3
        ("Which dated example best illustrates Black wartime aviation service?",
         ["The Tuskegee Airmen, the 332nd Fighter Group and 477th Bombardment Group trained at Tuskegee Army Air Field beginning in 1941, who flew approximately 1,500 missions in Europe — including bomber escort over Italy and Germany — and earned numerous Distinguished Flying Crosses, helping prove the case against military segregation.",
          "The all-white 8th Air Force.",
          "The Air Force did not exist until 1947, so no Black aviators served in WWII.",
          "Black aviation units served only in the Pacific."],
         0,
         "The Tuskegee Airmen (332nd Fighter Group, 477th Bombardment Group) trained at Tuskegee Army Air Field beginning in 1941; their record helped pressure Truman toward EO 9981 (1948)."),
        ("The 1943 Detroit and Harlem riots are best characterized as:",
         ["Voluntary parades celebrating wartime unity.",
          "Wartime racial uprisings driven by housing competition, defense-industry job tensions, and police actions — Detroit (June 20–22, 1943) killed 34 (25 Black, 9 white); Harlem (August 1–2, 1943) killed 6 — illustrating that the \"Double V\" was contested at home as well as abroad.",
          "Confederate uprisings in 1943.",
          "Pacifist demonstrations against the war."],
         1,
         "The 1943 Detroit (34 killed, 25 Black) and Harlem (6 killed) riots showed that wartime racial conflict over housing, jobs, and policing erupted even as Black soldiers fought abroad."),
        # Part 4
        ("How does the WWI/WWII era connect to the Great Migration?",
         ["The two are unrelated.",
          "Wartime industrial mobilization in 1917–18 and 1941–45 — combined with the closure of European immigration — pulled hundreds of thousands of Black Southerners to Northern and Western defense-industry cities, accelerating the First (c. 1910–1940) and Second (c. 1940–1970) Great Migrations.",
          "The world wars halted Black migration entirely.",
          "All Black migration occurred only after 1965."],
         1,
         "WWI and WWII labor demand — combined with European immigration restrictions — were principal drivers of the First and Second Great Migrations (Isabel Wilkerson, *The Warmth of Other Suns*, 2010)."),
        ("Which AP analytical skill is most directly tested by comparing the New Negro of the 1920s with the Double V campaign of 1942?",
         ["Memorization without comparison.",
          "Comparison: both reframed Black identity around dignity, militancy, and full citizenship after wartime service (Alain Locke's *The New Negro*, 1925; the *Pittsburgh Courier*'s Double V, 1942), but the 1940s campaign more directly leveraged federal war mobilization to extract policy concessions (EO 8802 1941; EO 9981 1948).",
          "Free recall of unrelated facts.",
          "Citing only modern sources."],
         1,
         "AP comparison rewards explicit similarity *and* difference — both frames demanded full citizenship after wartime service; Double V translated more directly into federal action."),
        # Part 5
        ("Which 1944 case marked a major change in the legal status of the white primary?",
         ["*Plessy v. Ferguson* (1896).",
          "*Smith v. Allwright* (1944), in which the Supreme Court struck down Texas's white primary, removing one of the most effective Jim Crow disenfranchisement devices and helping spur a sharp rise in Southern Black voter registration after WWII.",
          "*Brown v. Board of Education* (1954).",
          "*Korematsu v. United States* (1944)."],
         1,
         "*Smith v. Allwright* (1944) struck down the white primary; combined with WWII activism, it drove rising Southern Black voter registration in the late 1940s."),
        ("Which best describes a continuity across the wartime decades for African Americans?",
         ["Black Americans abandoned protest during the world wars.",
          "From WWI through WWII, the NAACP, the Black press (the *Crisis*, *Pittsburgh Courier*, *Chicago Defender*), and labor leaders (A. Philip Randolph, Brotherhood of Sleeping Car Porters founded 1925) sustained a strategy of leveraging federal power and wartime exigency to attack lynching, segregation, and disenfranchisement.",
          "The NAACP suspended operations during the world wars.",
          "Black labor organizing did not exist before 1960."],
         1,
         "Continuity = sustained NAACP, Black press, and Black labor (Randolph, BSCP 1925) leveraging federal power across both world wars."),
        # Part 6
        ("A historian wants to study Black political thought during WWII. Which source is most directly useful?",
         ["A 21st-century novel about WWII.",
          "James G. Thompson's January 1942 *Pittsburgh Courier* letter launching the Double V campaign, A. Philip Randolph's writings on the March on Washington Movement, and the NAACP's *Crisis* editorials calling for federal antilynching legislation.",
          "An undated wartime poster with no provenance.",
          "A modern academic textbook with no primary excerpts."],
         1,
         "Thompson's 1942 *Courier* letter, Randolph on MOWM, and *Crisis* editorials are core primary sources for AP analysis of WWII-era Black political thought."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point on FDR's Executive Order 8802?",
         ["Quoting it without comment.",
          "Noting that Roosevelt issued it on June 25, 1941 — six months before Pearl Harbor — under direct pressure from A. Philip Randolph's threatened March on Washington of 100,000 Black workers, and using that situation to evaluate the order as a politically extracted concession rather than a presidential initiative.",
          "Citing only the order number with no analysis.",
          "Ignoring Randolph's role entirely."],
         1,
         "AP sourcing requires *use* of audience/purpose/situation — EO 8802's pre-Pearl Harbor timing and Randolph's MOWM pressure are essential to interpreting it."),
        # Part 7
        ("Which is the strongest one-sentence thesis on the WWI / WWII era?",
         ["Black Americans served in the world wars.",
          "Between 1917 and 1948, African Americans leveraged the contradictions of two world wars — the 369th Infantry's combat record in WWI, A. Philip Randolph's 1941 March on Washington Movement, the Tuskegee Airmen, the Double V campaign (1942), *Smith v. Allwright* (1944), and Truman's EO 9981 (1948) — to extract concrete federal concessions while building the political infrastructure for the postwar Civil Rights Movement.",
          "Black wartime service had no political consequences.",
          "Civil rights activism began only in 1954."],
         1,
         "Strong AP theses combine periodization, named figures and units, dated federal acts, and a complexity move (wartime contradictions as leverage)."),
        ("On the AP exam, the strongest move when writing about the WWI / WWII era is to:",
         ["Avoid all dates and named figures.",
          "Anchor claims in a named figure (369th, Tuskegee Airmen, A. Philip Randolph, James G. Thompson), a dated event (1917–18 combat, EO 8802 June 25 1941, Double V 1942, *Smith v. Allwright* 1944, EO 9981 July 26 1948), and a primary source (Thompson's 1942 *Courier* letter).",
          "Cite no sources at all.",
          "Use only modern op-eds."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# 9. Great Migration & Harlem Renaissance
# ────────────────────────────────────────────────────────────────────────────
T["aas-great-migration-harlem"] = {
    "title": "Great Migration & Harlem Renaissance",
    "prefix": "aasgm",
    "qs": [
        # Part 1
        ("In AP African American Studies, the \"Great Migration\" refers specifically to:",
         ["A 19th-century westward movement of African Americans across the Mississippi River.",
          "The two-stage 20th-century movement of roughly 6 million African Americans from the rural South to Northern, Midwestern, and Western cities — c. 1910–1940 (First) and c. 1940–1970 (Second) — chronicled by Isabel Wilkerson in *The Warmth of Other Suns* (2010).",
          "A purely intra-Southern rural-to-rural migration.",
          "A post-1980 return migration to the Deep South."],
         1,
         "The Great Migration moved ~6M African Americans from the South over two waves (1910–1940 and 1940–1970); Wilkerson's *Warmth of Other Suns* (2010) is the major narrative history."),
        ("The \"Harlem Renaissance\" is best defined as:",
         ["A late-19th-century New England literary movement.",
          "A 1920s flowering of African American literature, music, visual art, and political thought centered in Harlem, New York City — featuring Langston Hughes, Zora Neale Hurston, Countee Cullen, Aaron Douglas, Duke Ellington, and Bessie Smith — and theorized by Alain Locke in *The New Negro* (1925).",
          "A 19th-century European art movement.",
          "A 21st-century gentrification movement."],
         1,
         "The Harlem Renaissance (c. 1918–1935) was a Black cultural flowering centered in Harlem; Locke's *The New Negro* (1925) was its theoretical manifesto."),
        # Part 2
        ("Which named newspaper most actively recruited Black migrants to the North during the First Great Migration?",
         ["The *New York Times*.",
          "The *Chicago Defender*, founded 1905 by Robert S. Abbott, which printed train schedules, job listings, and editorials urging Southern Black readers to leave the Jim Crow South — distributed across the South by Pullman porters.",
          "The *Wall Street Journal*.",
          "The *Atlanta Constitution*."],
         1,
         "Robert S. Abbott's *Chicago Defender* (founded 1905) was the most influential Black newspaper of the migration era; its Southern circulation was sustained by Pullman porters."),
        ("Which mechanism was central to the First Great Migration's pull?",
         ["Federal homestead grants for Black migrants.",
          "Wartime industrial labor demand from 1917 to 1918, combined with the wartime collapse of European immigration, opened previously closed industrial jobs (auto, steel, meatpacking) to Black workers in cities such as Chicago, Detroit, Cleveland, and Philadelphia.",
          "Federal scholarships to Northern universities.",
          "A Soviet-style relocation program."],
         1,
         "WWI labor demand + the collapse of European immigration (1914–18) opened Northern industrial jobs to Black Southern workers — the central pull factor of the First Great Migration."),
        # Part 3
        ("Which dated event illustrates the violent reception Black migrants often faced in the urban North?",
         ["The 1919 \"Red Summer,\" a series of more than 25 anti-Black urban riots — including the Chicago race riot (July 27–August 3, 1919, ~38 killed) and Washington, D.C. — provoked by white competition over housing and jobs after WWI.",
          "The 1929 stock market crash.",
          "The 1934 Securities Exchange Act.",
          "The 1955 Montgomery bus boycott."],
         0,
         "The Red Summer of 1919 saw 25+ anti-Black riots after WWI demobilization, including Chicago (~38 killed); chronicled by Cameron McWhirter, *Red Summer* (2011)."),
        ("Which figure best embodied the Garveyite Black nationalism of the 1920s?",
         ["W. E. B. Du Bois, NAACP integrationist.",
          "Marcus Garvey, founder of the Universal Negro Improvement Association (UNIA, 1914 in Jamaica; relocated to Harlem 1916), whose Black Star Line and \"Africa for the Africans\" program built the largest mass Black movement of the era before his 1923 mail-fraud conviction and 1927 deportation.",
          "Booker T. Washington, who died in 1915 before the Renaissance.",
          "James Weldon Johnson."],
         1,
         "Marcus Garvey's UNIA (founded 1914 Jamaica; Harlem from 1916) and the Black Star Line built the largest mass Black movement of the 1920s; Garvey was convicted of mail fraud (1923) and deported (1927)."),
        # Part 4
        ("How does the Harlem Renaissance connect to later Black cultural movements?",
         ["It had no influence on later movements.",
          "Its insistence on Black aesthetic autonomy and self-representation — Locke's \"New Negro\" (1925), Hughes's *The Negro Artist and the Racial Mountain* (1926), Hurston's anthropological fiction — directly shaped the Black Arts Movement of the 1960s–70s (Amiri Baraka, Sonia Sanchez) and contemporary hip-hop and Afrofuturism.",
          "It was a one-off literary fad with no later resonance.",
          "Later movements explicitly rejected all Harlem Renaissance themes."],
         1,
         "The Harlem Renaissance's aesthetic autonomy and self-representation flow forward into the Black Arts Movement (1960s–70s) and contemporary Black cultural production."),
        ("Which AP analytical skill is most directly tested by comparing W. E. B. Du Bois's NAACP integrationism with Marcus Garvey's UNIA Black nationalism?",
         ["Memorization without comparison.",
          "Comparison: both responded to Jim Crow and the Great Migration's urban concentration of Black population, but Du Bois (1909 NAACP, *The Crisis*) pursued integration through litigation while Garvey (1914 UNIA, Black Star Line) pursued race pride, economic separatism, and a return to Africa.",
          "Free recall of unrelated facts.",
          "Citing only modern sources."],
         1,
         "AP comparison rewards explicit similarity *and* difference — both responded to Jim Crow + the migration; their strategies (integration vs. separatism) and audiences (educated elite vs. mass working-class) differed sharply."),
        # Part 5
        ("Which best describes a major change brought by the Great Migration?",
         ["Black Americans remained ~90 percent rural through 1970.",
          "The Black population shifted from ~90 percent Southern and rural in 1900 to roughly half Northern/Western and predominantly urban by 1970, transforming Black political power in cities like Chicago, Detroit, New York, Philadelphia, and Los Angeles.",
          "The Black population became more rural over the 20th century.",
          "There was no measurable change in Black geography after 1900."],
         1,
         "By 1970, ~47% of African Americans lived outside the South (vs. ~10% in 1900) and the population was predominantly urban — reshaping electoral politics, housing markets, and culture."),
        ("Which best describes a continuity across the migration era?",
         ["Black migrants assimilated entirely into white urban culture.",
          "Migrants carried Southern Black religious, musical, and culinary traditions north — sustaining the Black church (AME, NBC, COGIC), gospel and blues (which fed jazz and later R&B and hip-hop), and Southern foodways — while building new Black urban institutions (Pullman porters' Brotherhood 1925; the *Defender*; Negro Leagues baseball).",
          "Migrants abandoned all Southern cultural practices.",
          "Black churches did not exist in Northern cities."],
         1,
         "Continuity = transplanted Black religious, musical, and culinary cultures + new Black urban institutions (BSCP 1925, *Chicago Defender*, Negro Leagues) sustained Black community life under Northern Jim Crow."),
        # Part 6
        ("A student wants to analyze the cultural manifesto of the New Negro movement. Which source is most directly useful?",
         ["A 21st-century podcast transcript.",
          "Alain Locke's edited anthology *The New Negro: An Interpretation* (1925); paired with Langston Hughes's essay \"The Negro Artist and the Racial Mountain\" (*The Nation*, 1926) and Zora Neale Hurston's *Their Eyes Were Watching God* (1937).",
          "An undated, anonymous magazine article.",
          "A modern textbook with no primary excerpts."],
         1,
         "Locke's *The New Negro* (1925), Hughes's \"Racial Mountain\" (1926), and Hurston's *Their Eyes Were Watching God* (1937) are core primary sources for AP analysis of Harlem Renaissance thought."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point on Hughes's 1926 \"The Negro Artist and the Racial Mountain\"?",
         ["Quoting it without comment.",
          "Noting that Hughes published it in *The Nation* in 1926 as a generational manifesto against Black writers (he names Countee Cullen by allusion) who sought white aesthetic approval, and using that audience and intra-movement debate to evaluate his call for artistic autonomy.",
          "Listing only the date with no analysis.",
          "Ignoring the intra-movement debate it joined."],
         1,
         "AP sourcing requires *use* of audience/purpose/situation — Hughes's 1926 *Nation* essay was a public intra-movement intervention against Black writers chasing white approval."),
        # Part 7
        ("Which is the strongest one-sentence thesis on the Great Migration and Harlem Renaissance?",
         ["The Great Migration changed cities.",
          "Between 1910 and 1940, the First Great Migration moved roughly 1.6 million Black Southerners to Northern and Western cities — pulled by WWI labor demand and the *Chicago Defender* — producing the demographic, institutional, and cultural conditions for the Harlem Renaissance (Locke's *New Negro* 1925, Hughes, Hurston) and Garveyite mass nationalism, even as Red Summer (1919) demonstrated the violent limits of Northern \"freedom.\"",
          "Black migration had no cultural consequences.",
          "The Harlem Renaissance was unrelated to migration."],
         1,
         "Strong AP theses combine periodization, scale (1.6M), causation (WWI + *Defender*), cultural outputs (Locke 1925, Hughes, Hurston), and a complexity move (Red Summer's violent limits)."),
        ("On the AP exam, the strongest move when writing about the migration and Renaissance is to:",
         ["Avoid all dates and named figures.",
          "Anchor claims in a named figure (Robert S. Abbott, Marcus Garvey, Langston Hughes, Zora Neale Hurston, Alain Locke), a dated event (1905 *Defender*, 1914 UNIA, 1919 Red Summer, 1925 *New Negro*, 1927 Garvey deportation), and a primary source (Locke 1925, Hughes 1926).",
          "Cite no sources at all.",
          "Use only 21st-century pop culture."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# 10. Civil Rights Movement
# ────────────────────────────────────────────────────────────────────────────
T["aas-civil-rights-movement"] = {
    "title": "Civil Rights Movement",
    "prefix": "aascrm",
    "qs": [
        # Part 1
        ("In AP African American Studies, the \"Civil Rights Movement\" most precisely refers to:",
         ["A purely 1960s federal legislative campaign with no Black grassroots component.",
          "The sustained mass movement, c. 1954–1968, combining NAACP litigation, Black church-based organizing, student-led nonviolent direct action, and federal legislation, that dismantled de jure segregation and disenfranchisement in the U.S. South.",
          "A 19th-century abolitionist movement.",
          "A 1990s academic theory only."],
         1,
         "The classical Civil Rights Movement (c. 1954–1968) combined litigation (NAACP LDF), church-based organizing (SCLC), student direct action (SNCC), and federal action (CRA 1964, VRA 1965)."),
        ("\"Massive resistance\" referred to:",
         ["A federal program to enforce *Brown v. Board*.",
          "The coordinated white Southern response to *Brown v. Board* (1954) — the 1956 \"Southern Manifesto\" signed by 101 members of Congress, school closures (e.g., Prince Edward County, VA, 1959–1964), state interposition statutes, and white-citizens' councils.",
          "A purely African American organizing strategy.",
          "A NATO Cold War defense plan."],
         1,
         "\"Massive resistance\" denotes the white Southern political and grassroots backlash to *Brown* — the 1956 Southern Manifesto, school closures, white-citizens' councils, interposition statutes."),
        # Part 2
        ("Which 1954 case overturned *Plessy v. Ferguson* in public education?",
         ["*Smith v. Allwright* (1944).",
          "*Brown v. Board of Education of Topeka* (1954), in which a unanimous Supreme Court led by Chief Justice Earl Warren ruled racial segregation in public schools unconstitutional under the 14th Amendment, citing Kenneth and Mamie Clark's doll studies and culminating an NAACP litigation campaign led by Thurgood Marshall.",
          "*Korematsu v. United States* (1944).",
          "*Loving v. Virginia* (1967)."],
         1,
         "*Brown v. Board* (1954) — Chief Justice Warren writing for a unanimous Court — overturned *Plessy*'s \"separate but equal\" in public education; *Brown II* (1955) added \"with all deliberate speed.\""),
        ("Which 1955–1956 boycott elevated Martin Luther King, Jr. to national leadership?",
         ["The Birmingham bus boycott (1962).",
          "The Montgomery Bus Boycott (December 5, 1955 – December 20, 1956), launched after Rosa Parks's December 1, 1955 arrest, organized through the Montgomery Improvement Association under King's leadership, and won via *Browder v. Gayle* (1956) — the federal court ruling that desegregated Montgomery's buses.",
          "The 1947 Journey of Reconciliation.",
          "The 1965 Selma-to-Montgomery march."],
         1,
         "The Montgomery Bus Boycott (Dec 5 1955 – Dec 20 1956) followed Rosa Parks's arrest, was led by King through the MIA, and was won by *Browder v. Gayle* (1956)."),
        # Part 3
        ("Which dated event illustrates student-led nonviolent direct action?",
         ["The Greensboro sit-ins, beginning February 1, 1960, when four North Carolina A&T freshmen — Ezell Blair Jr. (Jibreel Khazan), Franklin McCain, Joseph McNeil, and David Richmond — sat at a Woolworth's lunch counter, sparking sit-ins across more than 50 cities and the founding of the Student Nonviolent Coordinating Committee (SNCC) at Shaw University in April 1960.",
          "The 1947 Truman EO 9981.",
          "The 1898 Wilmington massacre.",
          "The 1925 founding of the Brotherhood of Sleeping Car Porters."],
         0,
         "The Feb 1, 1960 Greensboro sit-ins led directly to the founding of SNCC at Shaw University (April 15–17, 1960) under Ella Baker's mentorship."),
        ("The Freedom Rides of 1961 are best characterized as:",
         ["Voluntary tourist trips through the Deep South.",
          "Interracial bus rides organized by CORE (and joined by SNCC) testing federal desegregation rulings — *Morgan v. Virginia* (1946) and *Boynton v. Virginia* (1960) — on interstate transportation; riders were violently attacked in Anniston and Birmingham, Alabama (May 14, 1961), forcing ICC enforcement of interstate desegregation in November 1961.",
          "A military convoy operation.",
          "A 1980s commemorative tour."],
         1,
         "CORE's 1961 Freedom Rides tested *Morgan* (1946) and *Boynton* (1960); attacks at Anniston and Birmingham (May 14, 1961) forced ICC enforcement of interstate desegregation in November 1961."),
        # Part 4
        ("How does the Civil Rights Movement connect to the Reconstruction unit?",
         ["The two periods are unrelated.",
          "The 13th, 14th, and 15th Amendments (1865–1870) were the constitutional foundation activated by Civil Rights litigation (the NAACP LDF's *Brown* campaign) and federal legislation (Civil Rights Act 1964, Voting Rights Act 1965) to dismantle Jim Crow — completing what historian Eric Foner calls Reconstruction's \"unfinished revolution.\"",
          "The Reconstruction Amendments played no role in 1960s litigation.",
          "Civil Rights litigation rejected the 14th Amendment."],
         1,
         "Foner (*Reconstruction*, 1988) frames Reconstruction as an \"unfinished revolution\"; the 14th Amendment EP Clause underwrote *Brown* (1954) and the 15th underwrote VRA (1965)."),
        ("Which AP analytical skill is most directly tested by comparing King's nonviolent integrationism with Malcolm X's early-1960s Nation of Islam separatism?",
         ["Memorization without comparison.",
          "Comparison: both responded to Jim Crow violence and Northern de facto segregation, but King (SCLC, 1957) pursued nonviolent direct action and federal civil rights legislation while Malcolm X (Nation of Islam through 1964; Organization of Afro-American Unity, 1964) emphasized self-defense, Black autonomy, and human rights internationalism.",
          "Free recall of unrelated facts.",
          "Citing only modern sources."],
         1,
         "AP comparison rewards explicit similarity *and* difference — both addressed segregation; their strategies (nonviolence + federal legislation vs. self-defense + autonomy + internationalism) differed sharply."),
        # Part 5
        ("Which 1965 federal law was the most consequential statutory change of the era?",
         ["The Civil Rights Act of 1957.",
          "The Voting Rights Act of 1965, signed August 6, 1965 after the Selma-to-Montgomery marches and \"Bloody Sunday\" (March 7, 1965), which suspended literacy tests and authorized federal voter registrars and Section 5 preclearance — driving Black voter registration in Mississippi from ~6.7 percent (1964) to ~59.8 percent (1967).",
          "The Glass-Steagall Act (1933).",
          "The Wagner Act (1935)."],
         1,
         "The VRA (Aug 6, 1965) was the most consequential single law of the era; Mississippi Black voter registration rose from ~6.7% (1964) to ~59.8% (1967)."),
        ("Which best describes a continuity across the Civil Rights Movement?",
         ["The movement was led by a single charismatic male leader.",
          "Behind the iconic male leadership, women — Ella Baker (SCLC, SNCC mentor), Septima Clark (Citizenship Schools), Fannie Lou Hamer (MFDP, 1964), Diane Nash (Nashville sit-ins; Selma planning), and Daisy Bates (Little Rock 1957) — sustained the movement's grassroots organizing across the entire era.",
          "Black women played no organizing role.",
          "All organizing collapsed after each major federal law."],
         1,
         "Women's grassroots organizing (Baker, Clark, Hamer, Nash, Bates) was a constant — see Barbara Ransby, *Ella Baker and the Black Freedom Movement* (2003)."),
        # Part 6
        ("A student wants to analyze King's strategic theory. Which source is most directly useful?",
         ["A 21st-century policy memo.",
          "Martin Luther King Jr.'s \"Letter from Birmingham Jail\" (April 16, 1963), responding to eight white Alabama clergymen, paired with his \"I Have a Dream\" address (August 28, 1963) at the March on Washington for Jobs and Freedom and his \"Beyond Vietnam\" speech (April 4, 1967).",
          "An undated, anonymous flyer.",
          "A modern textbook with no primary excerpts."],
         1,
         "King's \"Letter from Birmingham Jail\" (1963), \"I Have a Dream\" (1963), and \"Beyond Vietnam\" (1967) are core AP primary sources for analyzing his evolving strategy."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point on King's \"Letter from Birmingham Jail\" (1963)?",
         ["Quoting it without comment.",
          "Noting that King wrote it from a Birmingham jail cell on April 16, 1963 in direct response to eight white Alabama clergy who had publicly criticized the Birmingham campaign as \"unwise and untimely\" — and using that audience and immediate situation to evaluate his arguments about \"just\" versus \"unjust\" laws.",
          "Listing only the date with no analysis.",
          "Ignoring the white clergy letter that prompted it."],
         1,
         "AP sourcing requires *use* of audience/purpose/situation — King's letter directly answered eight named white Alabama clergy; that exchange is essential context."),
        # Part 7
        ("Which is the strongest one-sentence thesis on the Civil Rights Movement?",
         ["The Civil Rights Movement happened.",
          "Between 1954 and 1968, a coalition of NAACP litigation (*Brown* 1954), Black church-based organizing (Montgomery 1955–56, SCLC 1957), and student-led direct action (Greensboro 1960, SNCC 1960, Freedom Rides 1961, Birmingham 1963, Selma 1965) — sustained by women organizers (Baker, Hamer, Clark) — extracted the Civil Rights Act (1964) and Voting Rights Act (1965), dismantling de jure Jim Crow even as de facto Northern segregation and economic inequality persisted.",
          "Federal legislation alone produced civil rights gains.",
          "The movement had no measurable consequences."],
         1,
         "Strong AP theses combine periodization, multi-organization coalition, named events and laws, and a complexity move (Northern de facto and economic limits)."),
        ("On the AP exam, the strongest move when writing about the Civil Rights Movement is to:",
         ["Avoid all dates and named figures.",
          "Anchor claims in a named figure (King, Baker, Hamer, Marshall, Nash), a dated event (May 17, 1954 *Brown*; Dec 1, 1955 Parks; Feb 1, 1960 Greensboro; April 1960 SNCC; April 16, 1963 Birmingham letter; March 7, 1965 Bloody Sunday; Aug 6, 1965 VRA), and a primary source (King's 1963 letter, the VRA).",
          "Cite no sources at all.",
          "Use only modern op-eds."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

if __name__ == "__main__":
    EXPECTED = {
        "aas-freedom-enslavement",
        "aas-reconstruction-jim-crow",
        "aas-wwi-wwii-era",
        "aas-great-migration-harlem",
        "aas-civil-rights-movement",
    }
    write_batch(T, EXPECTED)
