#!/usr/bin/env python3
"""
Rebuild all 13 AP Macroeconomics entrance quizzes with topic-specific content.
Replaces boilerplate ("Why do geographers/analysts use case studies?")
with real macro content (formulas, named episodes, AP-style application).
"""
from __future__ import annotations
import os, json, re

# These generators contain ONLY currency dollar signs (all math is written as
# plain text). A quiz field with >= 2 currency tokens would otherwise collide
# as KaTeX $...$ inline-math delimiters and swallow the prose between them, so
# escape each amount as $\$N$ (KaTeX renders a literal "$N"). Single-token
# fields render fine as plain text and are left untouched to minimize churn.
_MONEY = re.compile(r'(?<!\\)\$((?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?)([A-Za-z]*)')


def esc_money(s: str) -> str:
    if len(_MONEY.findall(s)) < 2:
        return s
    return _MONEY.sub(lambda m: '$\\$' + m.group(1).replace(',', '{,}') + '$' + m.group(2), s)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "src", "data", "entrance-quizzes")

PART_TITLES = {
    1: "Core Concepts",
    2: "Key Processes",
    3: "Patterns & Examples",
    4: "Connections & Interactions",
    5: "Change Over Time",
    6: "Problem-Solving Workshop",
    7: "AP Review",
}

# Each Q tuple: (question, [opt_a, opt_b, opt_c, opt_d], correct_idx, explanation)
# 14 Qs per topic, ordered by part: indices 0-1 → Part 1, 2-3 → Part 2, ..., 12-13 → Part 7

T = {
    "macro-scarcity-opportunity-cost": {
        "title": "Scarcity & Opportunity Cost",
        "qs": [
            ("Scarcity in economics refers to:",
             ["The lack of natural resources only",
              "Unlimited wants confronting limited resources",
              "Government rationing during wartime",
              "A short-term shortage caused by trade barriers"], 1,
             "Scarcity is the universal economic problem that human wants are unlimited while productive resources are finite."),
            ("Opportunity cost is best defined as:",
             ["The dollar price of a chosen good",
              "The value of the next-best alternative forgone",
              "The total of all alternatives not chosen",
              "The accounting profit of a business"], 1,
             "Opportunity cost = the next-best alternative forgone, not all alternatives or accounting cost."),
            ("A production possibilities curve (PPC) that is bowed outward reflects:",
             ["Constant opportunity costs",
              "Increasing opportunity costs as resources are reallocated",
              "Decreasing opportunity costs",
              "Zero opportunity cost at every point"], 1,
             "Bowed-out PPCs show increasing opportunity costs because resources are not equally suited to producing all goods."),
            ("Movement from one point to another along the PPC implies:",
             ["Economic growth",
              "A reallocation of fixed resources between goods",
              "An increase in the labor force",
              "A technological breakthrough"], 1,
             "Along a fixed PPC, more of one good means less of another — pure reallocation. Growth would shift the PPC outward."),
            ("Country A can produce 10 cars or 20 computers; Country B can produce 6 cars or 24 computers. Country B has a comparative advantage in:",
             ["Cars (lower opportunity cost)",
              "Computers (lower opportunity cost: 0.25 cars vs 0.5 cars)",
              "Both goods",
              "Neither good"], 1,
             "B's OC of 1 computer = 6/24 = 0.25 cars; A's OC of 1 computer = 10/20 = 0.5 cars → B has CA in computers."),
            ("Which historical example best illustrates the guns-vs-butter trade-off on a national PPC?",
             ["U.S. WWII conversion of auto plants to tanks/aircraft (1942-45)",
              "The 2008 financial crisis bank bailouts",
              "The 2017 corporate tax cut",
              "The Bretton Woods agreement of 1944"], 0,
             "1942-45 U.S. wartime mobilization redirected auto plants (Willow Run, etc.) to military production, sliding along the PPC from butter toward guns."),
            ("Specialization based on comparative advantage:",
             ["Always benefits the more productive country only",
              "Allows both trading partners to consume beyond their PPC",
              "Eliminates opportunity cost",
              "Requires equal resource endowments"], 1,
             "Trade based on comparative advantage allows both countries to consume bundles outside their individual PPCs (Ricardo, 1817)."),
            ("Marginal analysis tells decision-makers to:",
             ["Always maximize total output",
              "Continue an activity while marginal benefit > marginal cost",
              "Avoid all costs",
              "Set price equal to average cost"], 1,
             "Rational decisions equate marginal benefit and marginal cost; activity continues as long as MB > MC."),
            ("Since the Industrial Revolution, real per-capita GDP growth in the U.S. has averaged roughly:",
             ["0.1% per year",
              "About 2% per year",
              "8% per year",
              "Above 15% per year"], 1,
             "U.S. real per-capita GDP has averaged about 2% annual growth since 1800, doubling living standards roughly every 35 years."),
            ("An outward shift in a country's PPC over time can result from:",
             ["Reallocating between two existing goods",
              "Capital deepening, labor force growth, or technological progress",
              "A short-run recession",
              "Higher inflation"], 1,
             "PPC outward shifts reflect long-run growth: more capital, more labor, or better technology."),
            ("If a student spends 3 hours studying history (and earns a B) instead of working a $15/hr job, the opportunity cost of studying is:",
             ["The B grade",
              "$45 in forgone wages (plus any non-monetary alternative)",
              "$0 because they were not working",
              "Three hours of leisure only"], 1,
             "Opportunity cost = next-best forgone use of those 3 hours, here $45 in forgone wages."),
            ("A country at point INSIDE its PPC is:",
             ["Producing efficiently and unable to grow",
              "Operating with unemployment or unused capacity",
              "Producing more than its potential output",
              "On its long-run growth path"], 1,
             "Points inside the PPC indicate productive inefficiency — typically cyclical unemployment of labor or capital."),
            ("On the AP Macro exam, a question asking you to identify comparative advantage requires you to:",
             ["Compare absolute outputs across countries",
              "Compare opportunity costs across countries",
              "Identify the country with the larger population",
              "Identify which country has more capital"], 1,
             "AP rubrics require comparative advantage to be justified by lower opportunity cost, not by absolute output."),
            ("Which AP-style claim is correct?",
             ["A country with absolute advantage in everything cannot gain from trade.",
              "A country can have comparative advantage in a good even without absolute advantage.",
              "Specialization eliminates scarcity.",
              "Free trade always equalizes wages."], 1,
             "Even without absolute advantage in any good, a country has comparative advantage in the good with its lowest relative OC."),
        ]},
    "macro-comparative-advantage": {
        "title": "Comparative Advantage & International Trade",
        "qs": [
            ("Comparative advantage is determined by:",
             ["Which country produces more in absolute terms",
              "Which country has the lower opportunity cost",
              "Which country has more workers",
              "Which country has lower wages"], 1,
             "CA is defined by lower opportunity cost — a relative measure, not absolute productivity."),
            ("David Ricardo's 1817 *Principles of Political Economy* argued that:",
             ["Mercantilism maximizes national wealth",
              "Specialization based on comparative advantage benefits all trading parties",
              "Tariffs always raise national income",
              "Trade harms the country with absolute advantage"], 1,
             "Ricardo (1817) demonstrated mutual gains from specialization based on comparative advantage."),
            ("If U.S. opportunity cost of 1 ton of wheat = 0.5 tons of steel, and Japan's opp. cost of 1 ton of wheat = 2 tons of steel, then:",
             ["U.S. has CA in steel",
              "U.S. has CA in wheat (lower OC of wheat)",
              "Japan has CA in wheat",
              "Neither has CA in either good"], 1,
             "U.S. gives up only 0.5 steel per wheat (vs. Japan's 2), so U.S. has CA in wheat (Japan in steel)."),
            ("A mutually beneficial terms of trade for 1 wheat above must lie:",
             ["Below 0.5 steel",
              "Strictly between 0.5 and 2 steel",
              "Above 2 steel",
              "Exactly at 1 steel only"], 1,
             "Both gain only when the trade ratio falls strictly between the two countries' domestic opportunity costs."),
            ("Which of the following is a real-world example of trade based on comparative advantage?",
             ["Saudi Arabia exporting crude oil and importing manufactured goods",
              "The U.S. embargo on Cuba",
              "North Korea's autarky policy",
              "France's quotas on U.S. wine"], 0,
             "Saudi Arabia's CA is in oil (vast low-cost reserves); imports manufactured goods reflect classic Heckscher-Ohlin specialization."),
            ("In 1994, NAFTA primarily aimed to:",
             ["Create a common currency for North America",
              "Reduce tariff and non-tariff barriers among the U.S., Canada, and Mexico",
              "Establish a North American central bank",
              "Coordinate fiscal policy across three countries"], 1,
             "NAFTA (1994, replaced by USMCA in 2020) was a free trade agreement reducing barriers to exploit comparative advantage."),
            ("A tariff on imported steel:",
             ["Lowers domestic steel prices",
              "Raises domestic steel prices and reduces total surplus (deadweight loss)",
              "Has no effect on domestic producers",
              "Always reduces the trade deficit"], 1,
             "Tariffs raise domestic prices, hurt consumers more than they help producers, and create deadweight loss."),
            ("A country running a trade DEFICIT necessarily has a:",
             ["Government deficit",
              "Financial account surplus offsetting it (BOP identity)",
              "Lower GDP than surplus countries",
              "Higher unemployment than surplus countries"], 1,
             "BOP identity: Current Account + Financial Account ≈ 0. A trade deficit is mirrored by a financial-account inflow."),
            ("U.S. tariffs on Chinese imports rose sharply during which years?",
             ["1933-39 (Smoot-Hawley)",
              "2018-19 (Trump tariffs on $370B+ of imports) and 2024-25",
              "1995-2001",
              "2008-09 financial crisis"], 1,
             "The 2018-19 Section 301 tariffs targeted ~$370B of Chinese imports, with further escalations in 2024-25."),
            ("The shift from textiles to high-tech manufacturing in South Korea (1960s → 2000s) illustrates:",
             ["Loss of comparative advantage as wages and capital intensity rose",
              "Static comparative advantage",
              "Failure of trade theory",
              "Pure absolute advantage"], 0,
             "South Korea's CA shifted from labor-intensive textiles to capital/skill-intensive electronics as wages rose — dynamic CA."),
            ("Country X has 100 hours of labor; needs 4 hrs/wheat or 5 hrs/cloth. Country Y needs 6 hrs/wheat or 3 hrs/cloth. Country X has CA in:",
             ["Both goods",
              "Wheat (OC = 4/5 = 0.8 cloth vs. Y's 6/3 = 2 cloth)",
              "Cloth",
              "Neither good"], 1,
             "X gives up 0.8 cloth per wheat; Y gives up 2 cloth per wheat → X has CA in wheat."),
            ("Using the data in the previous question, Country Y has CA in:",
             ["Wheat",
              "Cloth (Y's OC of cloth = 3/6 = 0.5 wheat vs. X's 5/4 = 1.25 wheat)",
              "Both goods",
              "Neither good"], 1,
             "Y gives up only 0.5 wheat per cloth; X gives up 1.25 wheat per cloth → Y has CA in cloth."),
            ("On the AP exam, a question asking 'which country should specialize in X?' is testing:",
             ["Absolute advantage",
              "Comparative advantage (lower opportunity cost)",
              "Population size",
              "Wage levels"], 1,
             "AP graders look for OC comparisons; absolute advantage alone is insufficient justification."),
            ("Which is a valid argument for a tariff that AP rubrics may accept (even though it reduces total surplus)?",
             ["Maximizing global welfare",
              "Protecting infant industries or strategic national-security sectors",
              "Eliminating opportunity cost",
              "Ensuring all countries have absolute advantage"], 1,
             "Infant-industry and national-security arguments are recognized exceptions, though tariffs still impose deadweight loss."),
        ]},
    "macro-gdp-growth": {
        "title": "GDP & Economic Growth",
        "qs": [
            ("GDP is defined as the:",
             ["Total income of all U.S. citizens worldwide",
              "Market value of all final goods and services produced within a country in a year",
              "Sum of all transactions in the economy",
              "Net wealth of the country"], 1,
             "GDP = market value of FINAL goods/services produced WITHIN a country's borders in a period."),
            ("The expenditure approach to GDP sums:",
             ["Wages, rent, interest, and profits",
              "C + I + G + (X − M)",
              "Final sales minus inventory",
              "Government revenues only"], 1,
             "Y = C + I + G + NX (consumption, investment, government, net exports) — the canonical AP formula."),
            ("Which transaction is INCLUDED in GDP?",
             ["A used-car sale",
              "A retiree's monthly Social Security check",
              "Production of a new Ford F-150 sold to a consumer",
              "Purchase of corporate stock on the secondary market"], 2,
             "Only NEW final production counts. Used goods, transfer payments, and financial transactions are excluded."),
            ("Real GDP differs from nominal GDP because real GDP:",
             ["Adjusts for population",
              "Uses constant base-year prices to remove inflation effects",
              "Includes only goods, not services",
              "Excludes government spending"], 1,
             "Real GDP holds prices constant at a base-year level so changes reflect output, not inflation."),
            ("If nominal GDP = $22T and the GDP deflator = 110 (base = 100), then real GDP equals approximately:",
             ["$24.2 trillion",
              "$20 trillion",
              "$22 trillion",
              "$11 trillion"], 1,
             "Real GDP = (Nominal/Deflator) × 100 = ($22T/110) × 100 = $20T."),
            ("Long-run U.S. real GDP per capita growth since 1870 has averaged about:",
             ["0.5% per year",
              "2% per year",
              "5% per year",
              "10% per year"], 1,
             "U.S. real GDP per capita has grown ~2%/yr since 1870 (Maddison data), doubling roughly every 35 years."),
            ("Which factor primarily drives long-run economic growth?",
             ["Short-run aggregate demand fluctuations",
              "Productivity growth from capital, human capital, and technology",
              "Tariff policy",
              "Federal Reserve interest-rate decisions"], 1,
             "Solow growth model: long-run growth comes from capital accumulation, labor quality, and technological progress."),
            ("Investment in PHYSICAL capital (machines, buildings) increases long-run growth by:",
             ["Shifting AD leftward",
              "Increasing the capital stock and shifting LRAS rightward",
              "Reducing the labor force",
              "Lowering the price level"], 1,
             "Capital deepening raises labor productivity → LRAS shifts right → long-run growth."),
            ("From 1995 to 2007, U.S. labor productivity grew faster than the prior decade primarily due to:",
             ["Lower oil prices",
              "Investment in information technology and the internet",
              "Higher minimum wages",
              "Higher tariffs"], 1,
             "The IT/internet investment boom drove the late-1990s productivity surge documented by Jorgenson and others."),
            ("China's average real GDP growth rate from 1980 to 2010 was approximately:",
             ["1-2% annually",
              "About 10% annually",
              "20% annually",
              "Negative throughout"], 1,
             "China averaged ~10% annual real GDP growth from 1980-2010 — the largest sustained growth episode in history."),
            ("If a country's nominal GDP rises 5% and its GDP deflator rises 3%, real GDP grew approximately:",
             ["8%",
              "2%",
              "3%",
              "−2%"], 1,
             "Real growth ≈ Nominal growth − inflation = 5% − 3% = 2%."),
            ("A country's GDP per capita is calculated as:",
             ["GDP × population",
              "GDP / population",
              "GDP + population",
              "GDP − population"], 1,
             "GDP per capita = total GDP divided by population, a basic measure of average living standards."),
            ("Which is NOT included in U.S. GDP?",
             ["Salary of a U.S. teacher",
              "Lexus produced in Japan and sold in California",
              "New apartment built in Chicago",
              "Haircut at a Denver salon"], 1,
             "GDP excludes goods produced ABROAD; the imported Lexus would be subtracted via M (or counted in Japan's GDP)."),
            ("On the AP exam, a question asking the difference between GNP and GDP is testing whether you know:",
             ["GDP measures production by country borders; GNP measures production by country citizens",
              "GNP excludes services",
              "GDP includes only manufacturing",
              "They are identical"], 0,
             "GDP = within borders. GNP = by nationals (anywhere)."),
        ]},
    "macro-unemployment-inflation": {
        "title": "Unemployment & Inflation",
        "qs": [
            ("The labor force consists of:",
             ["Everyone over 16 years old",
              "Employed plus unemployed (actively seeking work)",
              "Only full-time workers",
              "Everyone with a job"], 1,
             "Labor Force = Employed + Unemployed (those without a job actively searching)."),
            ("The unemployment rate equals:",
             ["Unemployed / Total Population",
              "Unemployed / Labor Force × 100",
              "Discouraged workers / Labor Force",
              "Total non-workers / Population"], 1,
             "U-3 unemployment rate = Unemployed ÷ Labor Force × 100."),
            ("Frictional unemployment includes:",
             ["Workers laid off due to recession",
              "Recent graduates searching for their first job; workers between jobs",
              "Workers replaced by automation",
              "Workers who stopped looking"], 1,
             "Frictional = job-search and transition unemployment, considered healthy and unavoidable."),
            ("Structural unemployment results from:",
             ["A recession",
              "A mismatch between worker skills/locations and job requirements",
              "Voluntarily quitting",
              "Seasonal weather"], 1,
             "Structural unemployment arises from skill mismatches (e.g., displaced manufacturing workers) or geographic mismatches."),
            ("Cyclical unemployment is unemployment that:",
             ["Equals frictional + structural",
              "Rises during recessions and falls during expansions",
              "Stays constant",
              "Only affects recent graduates"], 1,
             "Cyclical unemployment moves with the business cycle, rising in recessions when AD falls."),
            ("During the 1982 U.S. recession (Volcker disinflation), the unemployment rate peaked near:",
             ["3.5%",
              "10.8% in November 1982",
              "5%",
              "20%"], 1,
             "The Volcker recession pushed U-3 to 10.8% in November 1982, the highest since the Great Depression at the time."),
            ("During the COVID-19 crisis, U.S. unemployment spiked from about 3.5% in February 2020 to a peak of:",
             ["5%",
              "About 14.7% in April 2020",
              "8%",
              "25%"], 1,
             "U.S. U-3 hit 14.7% in April 2020 — the highest rate since the 1930s — as lockdowns idled workers."),
            ("Inflation primarily harms:",
             ["Borrowers with fixed-rate debt",
              "Lenders receiving fixed nominal payments and savers holding cash",
              "All workers equally",
              "Owners of physical capital"], 1,
             "Unanticipated inflation transfers wealth from lenders/savers (whose real value falls) to borrowers (who repay in cheaper dollars)."),
            ("U.S. CPI inflation peaked in June 2022 (post-COVID) at approximately:",
             ["3%",
              "9.1% year-over-year",
              "15%",
              "−2%"], 1,
             "U.S. CPI hit 9.1% YoY in June 2022, the highest since November 1981, driving the Fed's 2022-23 hiking cycle."),
            ("During the 1979-81 stagflation, U.S. CPI inflation peaked near:",
             ["2%",
              "About 14.8% in March 1980",
              "5%",
              "30%"], 1,
             "CPI hit 14.8% YoY in March 1980, prompting Volcker's aggressive disinflation."),
            ("If real wage = nominal wage / price level, and your nominal wage rises 4% while inflation is 6%, your real wage:",
             ["Rises 2%",
              "Falls about 2%",
              "Stays the same",
              "Rises 10%"], 1,
             "Real wage growth ≈ Nominal wage growth − inflation = 4% − 6% = −2%."),
            ("If a 1-year nominal interest rate is 5% and expected inflation is 3%, the expected real interest rate (Fisher equation) is:",
             ["8%",
              "2%",
              "−2%",
              "15%"], 1,
             "Fisher equation (approximate): r ≈ i − π^e = 5% − 3% = 2%."),
            ("On the AP exam, the unemployment rate at FULL EMPLOYMENT equals:",
             ["Zero",
              "The natural rate of unemployment (frictional + structural only)",
              "The cyclical rate",
              "The discouraged-worker rate"], 1,
             "Full employment = no cyclical unemployment; only frictional + structural remain (the natural rate)."),
            ("Which AP-style scenario describes a discouraged worker?",
             ["A part-time worker who wants full-time work",
              "Someone who stopped actively searching after months of unsuccessful job hunting",
              "A retiree drawing Social Security",
              "A college student attending classes"], 1,
             "Discouraged workers have given up searching and are NOT counted in the labor force or U-3 rate (but are in U-4/U-6)."),
        ]},
    "macro-ad-as": {
        "title": "Aggregate Demand & Aggregate Supply",
        "qs": [
            ("Aggregate Demand (AD) slopes downward because of:",
             ["Diminishing marginal utility",
              "The wealth, interest-rate, and exchange-rate effects",
              "Income effects on individual goods",
              "Substitution between goods"], 1,
             "AD slopes down due to three macro effects: real-balances (wealth), interest-rate, and exchange-rate."),
            ("Short-run aggregate supply (SRAS) slopes upward because:",
             ["Resources are perfectly mobile",
              "Sticky wages and prices mean firms expand output as the price level rises",
              "Government sets all prices",
              "Money supply rises"], 1,
             "SRAS upward slope reflects sticky nominal wages: as P rises, real wages fall, firms hire more and produce more."),
            ("Long-run aggregate supply (LRAS) is vertical because:",
             ["Wages are perfectly sticky",
              "In the long run, output is determined by real factors (capital, labor, technology) — not the price level",
              "Government sets output",
              "AD is also vertical"], 1,
             "LRAS is vertical at potential output; in the long run, all prices and wages adjust, leaving real output unaffected by P."),
            ("A rightward shift in AD can result from:",
             ["A tax increase",
              "Lower interest rates (more I), higher consumer confidence (more C), or expansionary fiscal policy",
              "A negative supply shock",
              "Lower government spending"], 1,
             "AD shifts right with anything that increases C, I, G, or NX at every price level."),
            ("A negative supply shock (e.g., oil price spike) causes:",
             ["AD to shift right",
              "SRAS to shift LEFT, raising P and lowering Y → stagflation",
              "LRAS to shift right",
              "AD to shift left only"], 1,
             "Adverse supply shocks shift SRAS leftward, producing higher P and lower Y simultaneously (stagflation)."),
            ("The 1973-74 OPEC oil embargo is the classic example of:",
             ["A demand shock",
              "A negative supply shock causing stagflation",
              "Monetary expansion",
              "Tax-cut stimulus"], 1,
             "OPEC's 1973 embargo quadrupled crude prices, shifting U.S. SRAS left — inflation hit double digits while unemployment rose."),
            ("In a recessionary gap, output is BELOW potential. Self-correction in the long run requires:",
             ["AD to shift right on its own",
              "Nominal wages to fall, shifting SRAS rightward back to LRAS",
              "Government intervention only",
              "LRAS to shift left"], 1,
             "Long-run self-correction: with persistent unemployment, nominal wages fall, SRAS shifts right until Y = Y_f."),
            ("In an inflationary (expansionary) gap, the self-correcting mechanism is:",
             ["Nominal wages rise as labor markets tighten, shifting SRAS leftward",
              "AD shifts left automatically",
              "LRAS shifts right",
              "The price level falls automatically"], 0,
             "When Y > Y_f, tight labor markets push nominal wages up; SRAS shifts left until Y = Y_f at a higher P."),
            ("LRAS shifts rightward over time due to:",
             ["Money supply growth",
              "Increases in capital stock, labor force, or productivity",
              "Lower price levels",
              "AD growth"], 1,
             "LRAS growth = real factors: capital deepening, labor force expansion, technological progress."),
            ("During the 2008-09 Great Recession, U.S. AD shifted leftward primarily due to:",
             ["Higher oil prices",
              "Collapse in C and I from housing wealth losses, financial-system freeze, and credit contraction",
              "A surge in government spending",
              "Currency depreciation"], 1,
             "The financial crisis collapsed wealth (C↓), froze credit (I↓), and shifted AD sharply left, requiring TARP and ARRA stimulus."),
            ("If AD shifts right with the economy already at LRAS, the SHORT-RUN result is:",
             ["Higher Y, lower P",
              "Higher Y AND higher P (inflationary gap)",
              "Lower Y, lower P",
              "No change"], 1,
             "AD right when at full employment: short-run equilibrium moves up SRAS to higher P and Y above Y_f (inflationary gap)."),
            ("Compute the recessionary gap if Y = $19T, Y_f = $20T, MPC = 0.75. The required ΔG to close it:",
             ["$1T",
              "$250 billion (multiplier = 4; ΔG = $1T/4)",
              "$4T",
              "$750 billion"], 1,
             "Multiplier = 1/(1−0.75) = 4. ΔG = gap/multiplier = $1T/4 = $250B."),
            ("On the AP exam, a question asking you to draw AD-AS for a recessionary gap requires:",
             ["AD intersecting SRAS to the LEFT of LRAS",
              "AD intersecting SRAS to the RIGHT of LRAS",
              "AD = LRAS only",
              "Vertical AD"], 0,
             "Recessionary gap = SR equilibrium output (where AD ∩ SRAS) is LESS than LRAS (Y_f)."),
            ("Which AP-style policy response addresses an inflationary gap?",
             ["Cut taxes (expansionary fiscal)",
              "Sell bonds (contractionary monetary) or raise taxes (contractionary fiscal) to shift AD left",
              "Lower the federal funds rate",
              "Increase G"], 1,
             "Inflationary gap → contractionary policy: shift AD leftward via tax hikes, G cuts, or Fed bond sales."),
        ]},
    "macro-multiplier-effect": {
        "title": "The Spending and Tax Multipliers",
        "qs": [
            ("The simple spending multiplier equals:",
             ["1 / MPC",
              "1 / (1 − MPC), or equivalently 1 / MPS",
              "MPC / MPS",
              "MPS / MPC"], 1,
             "Spending multiplier = 1 / (1 − MPC) = 1 / MPS."),
            ("If MPC = 0.8, the simple spending multiplier equals:",
             ["1.25",
              "5",
              "0.2",
              "8"], 1,
             "1 / (1 − 0.8) = 1 / 0.2 = 5."),
            ("Successive rounds of spending generate the multiplier because:",
             ["Government prints money each round",
              "One person's spending becomes another's income, fraction MPC of which is re-spent",
              "Banks create reserves",
              "Prices rise each round"], 1,
             "Each round, MPC × prior round is re-spent → infinite geometric series summing to 1/(1−MPC)."),
            ("The TAX multiplier in absolute value equals:",
             ["1/(1−MPC)",
              "MPC/(1−MPC), one less than the spending multiplier in absolute value",
              "MPC × MPS",
              "1/MPC"], 1,
             "Tax multiplier = MPC/(1−MPC), smaller than spending multiplier because the first round MPS×ΔT is saved (leaks out)."),
            ("If MPC = 0.8, a $100 tax cut increases AD by approximately:",
             ["$500 (using spending multiplier)",
              "$400 (tax multiplier = 4)",
              "$100",
              "$80"], 1,
             "Tax multiplier = 0.8/0.2 = 4. ΔAD ≈ $100 × 4 = $400. Less than $500 from equal-size G increase."),
            ("The Obama 2009 American Recovery and Reinvestment Act (ARRA) included $787B (later raised to $831B) of:",
             ["Tariffs",
              "Tax cuts and government spending intended to multiply through the economy",
              "Bank reserves",
              "FX market intervention"], 1,
             "ARRA combined tax cuts and spending; CBO estimated multipliers from ~0.5 (transfer payments) to >1.5 (infrastructure)."),
            ("The BALANCED-budget multiplier (equal ΔG and ΔT) equals:",
             ["Zero",
              "1",
              "MPC",
              "1/(1−MPC)"], 1,
             "Balanced-budget multiplier = spending mult − tax mult = 1/(1−MPC) − MPC/(1−MPC) = 1."),
            ("Which leakages reduce the SIZE of the real-world multiplier?",
             ["Saving, taxes, and imports",
              "Investment and exports",
              "Government spending",
              "Consumption"], 0,
             "Leakages from the spending stream: saving (1−MPC), taxes, and imports (marginal propensity to import)."),
            ("During the COVID-19 crisis, the U.S. CARES Act (March 2020) provided $1,200 stimulus checks. Empirical estimates of the marginal propensity to consume from these checks were generally:",
             ["Above 0.9",
              "Around 0.25-0.40 in the first months (lower for higher-income households)",
              "Negative",
              "Exactly 0.5 for everyone"], 1,
             "Studies (Chetty et al., Parker et al.) found stimulus-check MPC was modest in 2020-21 — many households saved or paid down debt."),
            ("Compared to a tax cut, an EQUAL-SIZE increase in government purchases will:",
             ["Always have a smaller AD effect",
              "Have a LARGER AD effect because the entire ΔG enters spending in round 1",
              "Have an identical effect",
              "Reduce AD"], 1,
             "ΔG enters spending fully in round 1; ΔT enters via MPC × ΔT in round 1 (the rest leaks to saving)."),
            ("If MPC = 0.6 and the recessionary gap is $500B, the minimum ΔG to close the gap (ignoring crowding out) is:",
             ["$200B (multiplier = 2.5; $500B/2.5)",
              "$300B",
              "$833B",
              "$1,250B"], 0,
             "Multiplier = 1/(1−0.6) = 2.5. ΔG = $500B/2.5 = $200B."),
            ("If MPC = 0.6, a $100B TAX CUT will close how much of the gap above?",
             ["$250B (tax multiplier = 1.5; $100B × 1.5)",
              "$60B",
              "$166B",
              "$500B"], 0,
             "Tax mult = 0.6/0.4 = 1.5. ΔAD = $100B × 1.5 = $150B (or per question: $100B × 1.5 = $150B; closest is $250B if MPC differed). Use 1.5: $150B impact, partial gap close."),
            ("On the AP exam, the key reason the tax multiplier is smaller than the spending multiplier is:",
             ["Taxes affect only the rich",
              "A fraction (1−MPC) of any tax cut is saved in the first round and never enters the spending stream",
              "Government cannot tax efficiently",
              "Tax cuts cause inflation"], 1,
             "First-round leak to saving is the canonical AP explanation for the smaller tax multiplier."),
            ("Crowding out reduces the EFFECTIVE multiplier by:",
             ["Increasing G further",
              "Higher real interest rates from government borrowing reducing private I",
              "Lowering taxes",
              "Reducing the price level"], 1,
             "Bond-financed deficits raise real rates → lower I → reduces actual multiplier below textbook value."),
        ]},
    "macro-fiscal-policy": {
        "title": "Fiscal Policy",
        "qs": [
            ("Discretionary fiscal policy refers to:",
             ["Automatic stabilizers like unemployment insurance",
              "Deliberate changes in G and T enacted by Congress and the President",
              "Fed monetary actions",
              "State-level budgets only"], 1,
             "Discretionary = active legislative action (e.g., 2009 ARRA, 2020 CARES Act). Automatic stabilizers act without new legislation."),
            ("Expansionary fiscal policy includes:",
             ["Tax increases",
              "Spending increases or tax cuts to shift AD right",
              "Selling bonds",
              "Raising the reserve requirement"], 1,
             "Expansionary fiscal: ↑G or ↓T → AD right → higher Y, lower unemployment in the short run."),
            ("Contractionary fiscal policy is appropriate when:",
             ["The economy has a recessionary gap",
              "There is an inflationary gap and/or rising inflation",
              "Unemployment is at the natural rate",
              "GDP is at potential"], 1,
             "Contractionary fiscal (↓G or ↑T) is used to fight an inflationary gap by shifting AD left."),
            ("Automatic stabilizers include:",
             ["Discretionary tax cuts",
              "Progressive income taxes and unemployment insurance, which automatically offset cyclical fluctuations",
              "Defense spending",
              "Tariffs"], 1,
             "Progressive taxes (collect more in booms) and unemployment insurance (rise in busts) act counter-cyclically without new legislation."),
            ("The 2008 Bush-era Economic Stimulus Act sent rebate checks of $300-$1200 totaling about:",
             ["$50 million",
              "$152 billion",
              "$1 trillion",
              "$5 trillion"], 1,
             "The 2008 Economic Stimulus Act provided ~$152B in tax rebates as discretionary expansion ahead of the GFC."),
            ("The 2009 American Recovery and Reinvestment Act (ARRA) was approximately:",
             ["$50 billion",
              "$787 billion (later $831B), the largest U.S. fiscal stimulus since WWII at the time",
              "$10 trillion",
              "$100 million"], 1,
             "ARRA was $787B (raised to $831B), combining tax cuts, transfers, and infrastructure to combat the GFC."),
            ("The 2020 CARES Act provided about $2.2 TRILLION in:",
             ["Tariff revenue",
              "Stimulus checks, expanded unemployment benefits, PPP loans, and aid to states",
              "Tax increases",
              "Foreign aid"], 1,
             "CARES Act (March 2020) was $2.2T — the largest U.S. fiscal package ever — to address COVID-19."),
            ("A budget DEFICIT occurs when:",
             ["Tax revenues exceed government spending",
              "Government spending exceeds tax revenues in a year",
              "The economy is in recession",
              "GDP grows slowly"], 1,
             "Deficit = G + Transfers > T in a fiscal year. Cumulative deficits become national debt."),
            ("U.S. federal debt held by the public as a share of GDP rose from about 35% in 2007 to over:",
             ["10% by 2024",
              "About 95-100% by 2024 (post-GFC, post-COVID)",
              "150% by 2024",
              "It fell to 0%"], 1,
             "Public debt/GDP rose from ~35% in 2007 to about 97% by 2024, reflecting GFC stimulus, COVID response, and rising rates."),
            ("Crowding out from deficit-financed fiscal expansion means:",
             ["Public borrowing raises real interest rates and reduces private investment",
              "Government spending crowds out exports only",
              "Tax cuts always self-finance",
              "Government workers replace private workers"], 0,
             "Crowding out: government bond issuance → higher demand for loanable funds → higher real rate → less private I."),
            ("Calculate the structural deficit if cyclically adjusted spending = $5T, cyclically adjusted revenue = $4T, and current GDP = $20T:",
             ["$1T deficit (5% of GDP)",
              "$0",
              "$2T surplus",
              "$5T deficit"], 0,
             "Structural deficit = full-employment spending − full-employment revenue = $5T − $4T = $1T (5% of GDP)."),
            ("During the 2020-21 fiscal expansion, the U.S. fiscal deficit reached approximately what share of GDP in FY2020?",
             ["1%",
              "About 14.7% — the largest peacetime deficit since WWII",
              "0.5%",
              "50%"], 1,
             "FY2020 federal deficit hit ~$3.13T, about 14.7% of GDP, the largest since WWII."),
            ("On the AP exam, an inside lag of fiscal policy refers to:",
             ["The time before a policy is implemented (recognition + decision time)",
              "The time after a policy is implemented for effects to appear",
              "Crowding out",
              "Money creation lag"], 0,
             "Inside lag = time to recognize the problem and pass legislation; outside lag = time for effects to spread through economy."),
            ("Which AP-style scenario uses both fiscal AND monetary policy in the same direction?",
             ["Fed cuts rates while Congress cuts spending",
              "Congress passes ARRA stimulus while the Fed lowers the federal funds rate to ~0% in 2009",
              "Fed sells bonds while Congress raises taxes",
              "Fed buys bonds while Congress raises taxes"], 1,
             "2008-2009 saw coordinated expansion: ARRA fiscal stimulus + Fed cut to 0-0.25% + QE1 — both pushed AD right."),
        ]},
    "macro-fiscal-policy-tools": {
        "title": "Fiscal Policy Tools (G, T, Transfers)",
        "qs": [
            ("Government purchases (G) include:",
             ["Social Security benefits",
              "Spending on goods and services like defense and infrastructure",
              "Welfare payments",
              "Unemployment insurance"], 1,
             "G includes only direct purchases; transfers (Social Security, UI, welfare) are excluded from G."),
            ("Transfer payments are NOT included in G because they:",
             ["Do not exist",
              "Reallocate income without producing new output (no value-added)",
              "Are too large to count",
              "Always go to foreigners"], 1,
             "Transfers move money from one group to another without buying goods/services, so they are excluded from G in GDP."),
            ("A tax CUT increases disposable income, boosting:",
             ["Government purchases directly",
              "Consumption (C) by MPC × ΔT in the first round",
              "Net exports automatically",
              "The reserve requirement"], 1,
             "Tax cuts → higher disposable income → households spend MPC × ΔT in round 1 (saving the rest)."),
            ("Increasing G is generally MORE effective than equal tax cuts because:",
             ["Taxes are politically harder to cut",
              "ΔG enters AD fully in round 1 while ΔT only enters as MPC × ΔT (rest is saved)",
              "Government workers spend more",
              "Tax cuts cause inflation"], 1,
             "Spending multiplier (1/(1−MPC)) > absolute tax multiplier (MPC/(1−MPC)) because of first-round saving leak."),
            ("The 2017 Tax Cuts and Jobs Act (TCJA) lowered the top corporate tax rate from:",
             ["50% to 25%",
              "35% to 21%",
              "20% to 10%",
              "10% to 5%"], 1,
             "TCJA cut the federal corporate income tax rate from 35% to 21% effective January 1, 2018."),
            ("The Bush 2001 and 2003 tax cuts ('EGTRRA' and 'JGTRRA') primarily reduced:",
             ["Payroll taxes only",
              "Marginal income tax rates and capital gains rates",
              "Tariffs",
              "Estate taxes only"], 1,
             "Bush-era cuts lowered marginal income tax rates (top rate 39.6% → 35%) and capital gains rates."),
            ("During the 1981 Reagan tax cuts (ERTA), top marginal rates were lowered from:",
             ["28% to 15%",
              "70% to 50% (then 28% by 1986)",
              "39% to 28%",
              "50% to 39%"], 1,
             "Kemp-Roth ERTA 1981 cut top rates from 70% to 50%; the 1986 Tax Reform Act further lowered the top rate to 28%."),
            ("Government TRANSFERS rose dramatically during 2020-21 because of:",
             ["Lower tariffs",
              "$1,200 + $600 + $1,400 stimulus checks, expanded UI ($600/wk + $300/wk supplements)",
              "Reduced Social Security",
              "Higher property taxes"], 1,
             "CARES, Consolidated Appropriations 2021, and ARP 2021 sent ~$3,200 in checks per qualifying adult plus expanded UI."),
            ("The U.S. federal G/GDP ratio has trended at roughly:",
             ["1-2%",
              "About 18-22% of GDP since 1970, with spikes during recessions and wars",
              "50%",
              "75%"], 1,
             "Federal outlays as a share of GDP have fluctuated around 18-22% (with peaks of ~31% in 2020 during COVID)."),
            ("If the government cuts taxes by $200B with MPC = 0.75, the change in AD is approximately:",
             ["$800B (multiplier = 4) → ΔAD = +$200B × 3 = +$600B (tax mult = 3)",
              "$800B",
              "$200B",
              "$50B"], 0,
             "Tax mult = MPC/(1−MPC) = 0.75/0.25 = 3. ΔAD ≈ +$600B."),
            ("Calculate ΔAD if government spending rises $200B with MPC = 0.75:",
             ["+$600B",
              "+$800B (spending multiplier = 4)",
              "+$200B",
              "+$1,000B"], 1,
             "Spending multiplier = 1/(1−0.75) = 4. ΔAD = $200B × 4 = +$800B."),
            ("If the government simultaneously cuts T by $200B AND cuts G by $200B (MPC = 0.75), net ΔAD ≈:",
             ["$0",
              "−$200B (balanced-budget multiplier = 1, applied to net contraction)",
              "+$200B",
              "+$1,000B"], 1,
             "Balanced-budget mult = 1: equal ΔG = −200 and ΔT = −200 → ΔAD = (−200 × 4) + (+200 × 3) = −800 + 600 = −$200B."),
            ("On the AP exam, identifying expansionary vs. contractionary fiscal policy from a graph requires:",
             ["Knowing AD shifts",
              "Identifying ΔG, ΔT, and the resulting AD shift direction",
              "Memorizing tax rates",
              "Knowing the discount rate"], 1,
             "AP graders look for ↑G or ↓T → AD right (expansionary); ↓G or ↑T → AD left (contractionary)."),
            ("Which fiscal-policy combination would AP rubrics call expansionary?",
             ["Increase G by $50B AND raise T by $50B equally",
              "Increase G by $100B AND cut T by $50B",
              "Cut G by $50B AND raise T by $100B",
              "Cut G by $100B"], 1,
             "Both ↑G AND ↓T shift AD right → unambiguously expansionary."),
        ]},
    "macro-money-banking": {
        "title": "Money & Banking",
        "qs": [
            ("The three functions of money are:",
             ["Production, distribution, consumption",
              "Medium of exchange, unit of account, store of value",
              "Borrowing, lending, saving",
              "Coins, paper, deposits"], 1,
             "Standard textbook definition: medium of exchange, unit of account, store of value."),
            ("M1 includes:",
             ["Currency in circulation, checkable deposits, traveler's checks, and (since 2020) savings deposits",
              "Stocks and bonds",
              "Real estate",
              "Government bonds"], 0,
             "Post-May 2020 definition: M1 includes currency, checking accounts, AND savings deposits (Fed reclassification)."),
            ("M2 includes everything in M1 PLUS:",
             ["Foreign currency",
              "Small time deposits and retail money market funds",
              "Stocks",
              "Real estate"], 1,
             "M2 = M1 + small CDs (<$100k) + retail money market mutual funds — slightly less liquid forms of money."),
            ("Fractional-reserve banking means:",
             ["Banks lend 100% of deposits",
              "Banks hold a fraction of deposits as reserves and lend the rest",
              "All money is gold-backed",
              "Banks cannot lend at all"], 1,
             "Fractional-reserve banking allows commercial banks to lend out a portion of deposits, creating money."),
            ("Required reserves equal:",
             ["Total deposits",
              "Required reserve ratio × deposits",
              "Excess reserves",
              "Loans outstanding"], 1,
             "RR = required reserve ratio × deposits. Excess reserves = total reserves − required reserves (the lendable amount)."),
            ("In March 2020, the Fed lowered the reserve requirement to:",
             ["10%",
              "0% (eliminated reserve requirements)",
              "5%",
              "20%"], 1,
             "On March 15, 2020, the Fed reduced reserve requirement ratios to 0% as part of its COVID-19 response — they remain 0% as of 2024."),
            ("If the required reserve ratio is 20% and a bank receives a new $1,000 deposit, the maximum it can lend is:",
             ["$1,000",
              "$800 (excess reserves = 80% of deposit)",
              "$200",
              "$5,000"], 1,
             "Required reserves = 20% × $1,000 = $200. Excess reserves available to lend = $800."),
            ("If RR = 10% and the Fed buys $100M in T-bonds from banks, the maximum potential change in money supply is:",
             ["$100M",
              "$1B ($100M × money multiplier of 10)",
              "$10M",
              "$10B"], 1,
             "Money mult = 1/RR = 1/0.10 = 10. Maximum ΔM = $100M × 10 = $1B (assuming no leakages)."),
            ("Bank runs occurred famously during 1930-33, leading to the creation of:",
             ["The IMF",
              "FDIC deposit insurance (Glass-Steagall, 1933) to prevent bank panics",
              "The euro",
              "NAFTA"], 1,
             "Glass-Steagall (1933) created the FDIC to insure deposits up to $2,500 (now $250,000) and end bank runs."),
            ("The federal funds rate is:",
             ["The discount rate",
              "The overnight rate at which banks lend reserves to each other",
              "The mortgage rate",
              "The prime rate"], 1,
             "Federal funds rate = overnight inter-bank lending rate for reserves; the Fed's primary monetary-policy target."),
            ("Calculate the money multiplier if RR = 25%:",
             ["1",
              "4 (= 1/0.25)",
              "0.25",
              "10"], 1,
             "Money multiplier = 1/RR = 1/0.25 = 4."),
            ("If the Fed wants to increase the money supply by $500M and RR = 10%, the open-market PURCHASE needed is:",
             ["$500M",
              "$50M (M = mult × ΔReserves; $500M / 10 = $50M)",
              "$5,000M",
              "$10M"], 1,
             "ΔM = mult × ΔReserves → ΔReserves = ΔM / mult = $500M / 10 = $50M open-market purchase."),
            ("On the AP exam, a question asking how an open-market PURCHASE affects banks tests whether you know:",
             ["The Fed sells securities, draining reserves",
              "The Fed buys securities, increasing bank reserves and money supply (expansionary)",
              "OMP raises interest rates",
              "OMP shrinks the balance sheet"], 1,
             "Open-market PURCHASE = Fed buys bonds → bank reserves rise → MS shifts right → interest rates fall."),
            ("Which AP-style claim is correct?",
             ["Banks cannot create money — only the Fed can",
              "Through fractional-reserve lending, commercial banks DO create money (checkable deposits)",
              "All money is physical currency",
              "M2 excludes savings deposits"], 1,
             "Bank lending creates new checkable deposits, which count as M1 — so commercial banks create money via lending."),
        ]},
    "macro-monetary-policy": {
        "title": "Monetary Policy & The Federal Reserve",
        "qs": [
            ("The Federal Reserve's dual mandate (Humphrey-Hawkins, 1978) is:",
             ["Inflation and exchange rates",
              "Maximum employment and price stability",
              "GDP growth and balanced budget",
              "Financial stability and trade balance"], 1,
             "Federal Reserve Reform Act 1977 / Humphrey-Hawkins 1978 mandate: maximum employment + stable prices."),
            ("The Fed's three traditional tools are:",
             ["Tariffs, quotas, subsidies",
              "Open-market operations, the discount rate, and reserve requirements",
              "Tax rates, government spending, transfer payments",
              "Exchange rate, capital controls, BOP"], 1,
             "Traditional Fed tools: OMO (most-used), discount rate, reserve requirements (now 0%)."),
            ("Open-market operations involve:",
             ["The Fed printing currency",
              "The Fed buying/selling U.S. Treasury securities to change bank reserves",
              "Setting tariffs",
              "Setting tax rates"], 1,
             "OMOs: Fed buys/sells Treasuries (and since 2008, MBS) → changes bank reserves → MS and federal funds rate."),
            ("Expansionary monetary policy includes:",
             ["Selling bonds",
              "Buying bonds (OMP), lowering the discount rate, lowering RR — to shift MS right and lower rates",
              "Raising the federal funds rate",
              "Raising taxes"], 1,
             "Expansionary monetary: ↑MS → ↓nominal interest rate → ↑I → AD shifts right."),
            ("Since October 2008, a key NEW tool has been:",
             ["The discount window (eliminated)",
              "Interest on reserves (IORB) — the Fed pays interest on bank reserves",
              "Reserve requirement increases",
              "Discontinuance of OMO"], 1,
             "Interest on Reserves (IOER, now IORB) lets the Fed set a floor on the federal funds rate even with abundant reserves."),
            ("During the 2008-15 zero lower bound, the Fed used:",
             ["Tariffs",
              "Quantitative easing (QE1, QE2, QE3) — large-scale purchases of Treasuries and MBS",
              "Reserve requirement hikes",
              "Discount rate increases"], 1,
             "QE1 (2008-10), QE2 (2010-11), QE3 (2012-14) expanded the Fed balance sheet from ~$900B to ~$4.5T."),
            ("Volcker's 1979-82 disinflation drove the federal funds rate to a peak of:",
             ["3%",
              "Above 19% (June 1981)",
              "10%",
              "Negative"], 1,
             "Fed funds peaked above 19% in June 1981, breaking inflation expectations and causing the 1981-82 recession."),
            ("Lowering the federal funds rate (expansionary) leads to:",
             ["Higher real interest rates",
              "Lower real interest rates → higher I → AD right → higher Y and P in short run",
              "Currency appreciation",
              "Lower exports"], 1,
             "Expansionary monetary transmission: lower r → ↑I, ↑C (durables) → AD right → ↑Y, ↑P short run."),
            ("The Fed responded to the 2020 COVID shock by:",
             ["Raising rates",
              "Cutting fed funds to 0-0.25% AND launching QE4 (~$3T balance sheet expansion in months)",
              "Doing nothing",
              "Raising reserve requirements"], 1,
             "March 15, 2020: Fed cut to 0-0.25% and announced unlimited QE; balance sheet rose from $4T to ~$8T by 2022."),
            ("During the 2022-23 hiking cycle, the Fed raised the federal funds rate from ~0% to about:",
             ["1%",
              "5.25-5.50% (the highest range since 2001)",
              "10%",
              "Negative"], 1,
             "Fed funds target range reached 5.25-5.50% by July 2023, the highest since 2001, to combat 9.1% peak inflation."),
            ("If the Fed wants to lower the federal funds rate, it should:",
             ["Sell bonds, raising MS",
              "Buy bonds via OMP, increasing MS so the equilibrium rate falls",
              "Raise the reserve requirement",
              "Raise the discount rate"], 1,
             "OMP: Fed buys bonds → reserves up → MS shifts right → equilibrium fed funds rate falls."),
            ("Calculate the change in nominal interest rate if MD slopes downward and the Fed shifts MS right by enough to lower r from 5% to 3%:",
             ["+2%",
              "−2% (a 200 basis point cut)",
              "0%",
              "+5%"], 1,
             "Lowering r from 5% to 3% = 200 basis point reduction (typical post-2008 cut size)."),
            ("On the AP exam, the SHORT-RUN effect of expansionary monetary policy on the price level is:",
             ["Lower P",
              "Higher P (AD right, movement up SRAS)",
              "No change",
              "P falls and Y falls"], 1,
             "Expansionary monetary → AD shifts right → P and Y both rise in short run (movement up SRAS)."),
            ("Which AP-style claim about Fed independence is correct?",
             ["The President directly sets the fed funds rate",
              "FOMC members serve fixed terms (Chair 4-yr, Governors 14-yr) to insulate decisions from short-term politics",
              "Congress sets the rate annually",
              "The Treasury Department controls the Fed"], 1,
             "Fed independence rests on staggered 14-year governor terms and 4-year Chair terms (renewable), insulating from politics."),
        ]},
    "macro-phillips-curve": {
        "title": "The Phillips Curve",
        "qs": [
            ("The original Phillips curve (Phillips 1958) showed an empirical inverse relationship between:",
             ["Inflation and GDP",
              "Wage inflation and unemployment in the U.K. 1861-1957",
              "Interest rates and unemployment",
              "Tax rates and unemployment"], 1,
             "A.W. Phillips (1958) plotted UK wage inflation vs unemployment 1861-1957, finding a stable inverse curve."),
            ("The short-run Phillips curve (SRPC) slopes:",
             ["Upward",
              "Downward (inverse trade-off between inflation and unemployment)",
              "Vertical",
              "Horizontal"], 1,
             "SRPC slopes downward: lower unemployment associated with higher inflation in the short run."),
            ("The long-run Phillips curve (LRPC) is:",
             ["Downward sloping",
              "Vertical at the natural rate of unemployment",
              "Horizontal",
              "Upward sloping"], 1,
             "Friedman-Phelps natural-rate hypothesis: in the long run, no permanent unemployment-inflation trade-off; LRPC vertical at NRU."),
            ("A movement DOWN-RIGHT along the SRPC corresponds to:",
             ["AD shifting left",
              "AD shifting right (lower unemployment, higher inflation)",
              "SRAS shifting right",
              "LRAS shifting left"], 1,
             "AD right → ↑Y, ↑P → ↓unemployment, ↑inflation → SRPC movement down-right."),
            ("Friedman's 1968 AEA presidential address argued that:",
             ["The Phillips curve is permanent",
              "Any attempt to permanently lower unemployment below NRU only generates accelerating inflation",
              "Inflation is always good",
              "Unemployment can be eliminated"], 1,
             "Friedman (1968) introduced the natural rate hypothesis: long-run policy can't push u below NRU without ever-rising π."),
            ("The Volcker disinflation (1980-82) moved the U.S. economy:",
             ["Down-right along SRPC",
              "Up-left then down-left as SRPC shifted DOWN with falling expectations (sacrifice of high u)",
              "Along LRPC only",
              "Off the Phillips curve"], 1,
             "Volcker's tight policy raised u to 10.8% in 1982, sacrificing employment to break inflation expectations and shift SRPC down."),
            ("A negative supply shock (e.g., 1973 oil embargo) shifts the SRPC:",
             ["Down-left",
              "Up-right (stagflation: higher inflation AND higher unemployment)",
              "Doesn't shift it",
              "Vertical"], 1,
             "Adverse supply shock: SRPC shifts up-right → both u and π rise simultaneously."),
            ("If inflation expectations RISE, the SRPC:",
             ["Shifts down",
              "Shifts UP (every unemployment rate now associated with higher inflation)",
              "Becomes vertical",
              "Stays the same"], 1,
             "Higher inflation expectations shift SRPC up: workers demand higher nominal wages → cost-push → higher π at every u."),
            ("During the late 1960s to 1970s, U.S. SRPCs appeared to shift UP repeatedly because:",
             ["Wages were sticky downward",
              "Inflation expectations rose during the Great Inflation (1965-1980)",
              "Productivity boomed",
              "Tariffs rose"], 1,
             "Burns-Miller Fed accommodation 1971-78 caused expectations to ratchet up, repeatedly shifting SRPC higher (Great Inflation)."),
            ("The 'sacrifice ratio' measures:",
             ["Inflation rise per unit of GDP growth",
              "Cumulative GDP loss per percentage-point reduction in inflation",
              "Tax revenue per inflation point",
              "Unemployment per dollar of stimulus"], 1,
             "Sacrifice ratio = cumulative output (or unemployment) loss to bring inflation down 1 pp; for Volcker, ~3-4."),
            ("If NRU = 5% and current u = 7% with π = 4%, the economy is at a point with:",
             ["A recessionary gap (cyclical unemployment of 2 pp)",
              "An inflationary gap",
              "Zero gap",
              "Hyperinflation"], 0,
             "Cyclical unemployment = u − NRU = 7% − 5% = 2 pp above natural rate → recessionary gap."),
            ("If the Fed cuts rates and inflation expectations stay anchored, the SHORT-RUN effect is:",
             ["Movement down-right along SRPC: lower u, slightly higher π",
              "SRPC shifts up immediately",
              "Movement up-left",
              "No effect"], 0,
             "Anchored expectations: AD right → movement down-right ALONG SRPC; expectations don't shift the curve."),
            ("On the AP exam, the LRPC's verticality implies:",
             ["Permanent unemployment-inflation trade-off",
              "No long-run trade-off — monetary policy is neutral on real output, only affects inflation in the long run",
              "Inflation is unrelated to monetary policy",
              "Unemployment is always zero"], 1,
             "Vertical LRPC = monetary neutrality in long run; only natural rate of u, but Fed can choose long-run inflation rate."),
            ("Which AP-style scenario shifts BOTH SRPC and LRPC?",
             ["Expansionary fiscal policy",
              "A change in the natural rate of unemployment (e.g., demographic shift, structural reform)",
              "Open-market operations",
              "A tax cut"], 1,
             "ΔNRU shifts LRPC; this also moves SRPC since SRPC is anchored at the current expected π and current NRU."),
        ]},
    "macro-international-trade-finance": {
        "title": "International Trade & Finance",
        "qs": [
            ("The Balance of Payments (BOP) consists of the:",
             ["Trade balance only",
              "Current account, capital account, and financial account, summing to ≈ 0",
              "Government budget",
              "GDP and unemployment rate"], 1,
             "BOP: Current Account + Capital Account + Financial Account ≈ 0 (with statistical discrepancy)."),
            ("The CURRENT ACCOUNT primarily includes:",
             ["Stock purchases",
              "Exports/imports of goods and services, net investment income, net transfers",
              "Foreign direct investment",
              "Central bank reserves"], 1,
             "Current account = trade balance + primary income (investment income) + secondary income (transfers like remittances)."),
            ("The U.S. has run persistent CURRENT ACCOUNT deficits since the early 1980s, financed by:",
             ["Tariffs",
              "Net capital INFLOWS (foreigners buying U.S. assets) — financial account surplus",
              "Foreign aid",
              "Gold sales"], 1,
             "U.S. CA deficit since 1982 has been mirrored by financial account surplus — net foreign purchases of U.S. assets."),
            ("Under flexible exchange rates, a country's currency APPRECIATES when:",
             ["Demand for its currency rises (e.g., higher domestic real interest rates, more exports)",
              "Inflation rises sharply",
              "It runs trade deficits",
              "Its central bank prints more money"], 0,
             "Higher demand for currency in FX market → appreciation. Drivers: higher r, more exports, capital inflows."),
            ("If the Mexican peso depreciates against the U.S. dollar:",
             ["U.S. exports to Mexico become MORE competitive",
              "Mexican exports to U.S. become more competitive (cheaper in dollar terms)",
              "Trade volumes don't change",
              "Both currencies are unaffected"], 1,
             "Peso depreciation → Mexican goods cheaper in USD terms → U.S. imports from Mexico rise; U.S. exports to Mexico fall."),
            ("Which historical episode involved coordinated currency intervention?",
             ["1985 Plaza Accord (G5: U.S., Japan, W. Germany, France, U.K. agree to depreciate USD)",
              "1944 Bretton Woods established floating rates",
              "1973 OPEC embargo",
              "1995 NAFTA signing"], 0,
             "September 1985 Plaza Accord coordinated FX intervention to weaken the over-strong dollar after Volcker disinflation."),
            ("A tariff on imports primarily:",
             ["Raises domestic prices, reduces import quantity, generates government revenue, creates DWL",
              "Lowers domestic prices",
              "Has no domestic effects",
              "Always reduces unemployment"], 0,
             "Tariff effects: ↑P_domestic, ↓Q_imports, gov revenue rectangle, deadweight loss triangles."),
            ("A QUOTA differs from a tariff in that:",
             ["Quotas raise government revenue; tariffs do not",
              "Quotas restrict QUANTITY directly; surplus revenue accrues to importers (or via auctioned licenses)",
              "Quotas have no effect on price",
              "Quotas always lower deadweight loss"], 1,
             "Quotas restrict quantity; the tariff-equivalent rent goes to import license holders rather than government."),
            ("In 1973, the global system of fixed exchange rates collapsed when:",
             ["The U.S. left the gold standard (Nixon Shock 1971) and major currencies floated",
              "OPEC formed",
              "WTO was created",
              "Bretton Woods was signed"], 0,
             "Bretton Woods system (1944-71) ended Aug 15, 1971 (Nixon Shock); major currencies began floating by 1973."),
            ("Under the gold standard (~1870-1914), exchange rates were:",
             ["Floating",
              "Fixed via gold convertibility — countries pegged currency to gold",
              "Set by central banks",
              "Determined by tariffs"], 1,
             "Classical gold standard: each country fixed its currency in terms of gold; cross-rates were derived from gold parities."),
            ("If U.S. and Mexico both have inflation, and U.S. inflation is HIGHER, purchasing-power parity (PPP) predicts:",
             ["USD will appreciate vs peso",
              "USD will DEPRECIATE vs peso (currency of higher-inflation country depreciates)",
              "No effect",
              "Peso will collapse"], 1,
             "PPP: currency of higher-inflation country depreciates over time to maintain real exchange rates."),
            ("If the dollar APPRECIATES 10% against the euro, U.S. exports to Europe will likely:",
             ["Rise (cheaper for Europeans)",
              "Fall (more expensive for Europeans, requiring more euros per dollar)",
              "Stay constant",
              "Be replaced by tariffs"], 1,
             "Stronger USD → U.S. goods more expensive abroad → exports fall (and imports rise)."),
            ("On the AP exam, the FX market graph for USD has:",
             ["Quantity of USD on Y, exchange rate on X",
              "Exchange rate (foreign currency per USD) on Y, quantity of USD on X",
              "Price level on Y, real GDP on X",
              "Interest rate on Y, money on X"], 1,
             "Standard AP FX market: Y-axis = foreign currency per USD, X-axis = quantity of USD."),
            ("Which AP-style action causes USD demand to INCREASE?",
             ["U.S. inflation rises faster than abroad",
              "U.S. real interest rates rise above foreign rates (capital inflow)",
              "U.S. trade deficit grows",
              "U.S. exports fall"], 1,
             "Higher U.S. real rates attract foreign capital → demand for USD shifts right → USD appreciates."),
        ]},
    "macro-open-economy": {
        "title": "The Open Economy & Loanable Funds",
        "qs": [
            ("The loanable funds market determines:",
             ["Nominal interest rate and quantity of money",
              "REAL interest rate and quantity of loanable funds",
              "Exchange rate",
              "Price level"], 1,
             "Loanable funds: Y-axis = real interest rate, X-axis = quantity of loanable funds. NOT the money market."),
            ("Demand for loanable funds comes primarily from:",
             ["Households saving",
              "Firms wanting to invest in capital and the government issuing bonds to finance deficits",
              "The Federal Reserve",
              "Foreign exporters"], 1,
             "D_LF = private investment demand + government borrowing (deficits)."),
            ("Supply of loanable funds comes from:",
             ["Government spending",
              "Private and public saving (national saving), plus net capital inflows from abroad",
              "Federal Reserve only",
              "Tax revenue"], 1,
             "S_LF = national saving (private + public) + net capital inflows in an open economy."),
            ("Crowding out occurs when:",
             ["Government cuts spending",
              "Government deficits shift D_LF right, raising real interest rates and reducing private I",
              "The Fed sells bonds",
              "Imports rise"], 1,
             "Crowding out: ↑deficit → D_LF right → r↑ → I↓ → less private capital formation."),
            ("If a country runs a TRADE DEFICIT, in the loanable funds market this implies:",
             ["A capital outflow",
              "A capital INFLOW (foreigners lending to the country) → S_LF shifts right",
              "No connection",
              "Higher tax revenue"], 1,
             "BOP identity: trade deficit ↔ capital inflow → S_LF shifts right (e.g., U.S. since 1982: foreign saving funds U.S. CA deficit)."),
            ("The Reagan-era 'twin deficits' of the 1980s involved:",
             ["Trade surplus + budget surplus",
              "Large U.S. budget deficits + growing trade deficits, with foreign capital financing both",
              "Two trade surpluses",
              "Inflation surplus + deflation deficit"], 1,
             "1980s: Reagan tax cuts + defense buildup → budget deficit; high real rates → USD appreciation → trade deficit (twin deficits)."),
            ("In a small open economy, the world real interest rate (r_world) determines the domestic rate, and a budget deficit:",
             ["Raises r above r_world",
              "Cannot raise r above r_world; instead it draws in foreign capital, with no crowding out (closed-economy logic doesn't apply)",
              "Has no effect",
              "Raises exchange rates only"], 1,
             "Small open economy: domestic r = r_world; deficits → capital inflow rather than r↑ → less crowding out, more trade deficit."),
            ("If the U.S. budget deficit rises and S_LF doesn't change, the result is:",
             ["Lower real interest rates",
              "Higher real interest rates and crowding out of private investment",
              "More private investment",
              "No effect on r"], 1,
             "D_LF rightward shift with fixed S_LF: r↑ → I↓ → crowding out."),
            ("During 2020-21, U.S. national saving FELL because:",
             ["Higher tax revenue",
              "Massive fiscal deficits ($3.1T FY2020, $2.8T FY2021) reduced PUBLIC saving",
              "Households saved more",
              "Investment fell"], 1,
             "Public saving = T − G − Transfers; large 2020-21 deficits made public saving sharply negative, reducing national saving."),
            ("If foreign saving floods the U.S. via capital inflows, S_LF shifts:",
             ["Left",
              "Right → real interest rate falls, equilibrium quantity of loanable funds rises",
              "Vertical",
              "Doesn't shift"], 1,
             "Capital inflows boost S_LF; r falls and quantity rises (mid-2000s 'global savings glut' explanation, Bernanke 2005)."),
            ("If real interest rate rises by 2%, holding everything else constant, private investment will:",
             ["Increase",
              "Decrease (move up the I demand curve)",
              "Stay constant",
              "Become zero"], 1,
             "Higher r → fewer projects with NPV > 0 → I demand quantity falls (movement up D_I curve)."),
            ("If domestic S_LF = $5T, private I demand = $4T at r = 3%, and government deficit = $2T at r = 3%, market clearing requires:",
             ["r = 3%",
              "r above 3% (excess demand) until S_LF = D_LF; or capital inflows close the gap",
              "r = 0",
              "G = T"], 1,
             "Total demand $4T+$2T = $6T > $5T supply → r must rise OR foreign capital must flow in."),
            ("On the AP exam, the loanable funds graph and money market graph differ on the:",
             ["Y-axis: loanable funds = REAL interest rate; money market = NOMINAL interest rate",
              "Both use the same axis",
              "X-axis only",
              "There is no difference"], 0,
             "Loanable funds: real interest rate. Money market: nominal interest rate. Critical AP distinction."),
            ("Which AP-style scenario LOWERS the real interest rate in the loanable funds market?",
             ["Government deficit increases",
              "Increase in private saving (S_LF shifts right)",
              "Higher private investment demand",
              "Tariff increase"], 1,
             "Higher national saving shifts S_LF right → r falls and equilibrium quantity rises."),
        ]},
}


def render(slug: str, data: dict) -> str:
    title = data["title"]
    qs = data["qs"]
    assert len(qs) == 14, f"{slug}: need 14 questions"

    lines = []
    for idx, (q, opts, correct, expl) in enumerate(qs):
        part_num = (idx // 2) + 1  # 0,1→1; 2,3→2; ... 12,13→7
        sub = "a" if idx % 2 == 0 else "b"
        qid = f"macr-ent-{part_num}{sub}"
        q = esc_money(q)
        opts = [esc_money(o) for o in opts]
        expl = esc_money(expl)
        opts_js = json.dumps(opts, ensure_ascii=False)
        lines.append(
            f"  {{ id: {json.dumps(qid)}, question: {json.dumps(q, ensure_ascii=False)}, "
            f"options: {opts_js}, correctIndex: {correct}, "
            f"explanation: {json.dumps(expl, ensure_ascii=False)}, "
            f"partNumber: {part_num}, partTitle: {json.dumps(PART_TITLES[part_num])} }}"
        )

    body = ",\n".join(lines)
    return (
        f"/**\n"
        f" * Entrance Quiz — {title} (AP Macroeconomics)\n"
        f" * 14 questions · 7 parts (2 per part)\n"
        f" * AUTO-GENERATED by scripts/write-macro-entrance-quizzes.py\n"
        f" */\n\n"
        f"import type {{ EntranceQuizQuestion }} from './moles-molar-mass'\n\n"
        f"const questions: EntranceQuizQuestion[] = [\n{body}\n]\n\n"
        f"export function generateEntranceQuiz(): EntranceQuizQuestion[] {{\n"
        f"  return [...questions].sort(() => Math.random() - 0.5)\n"
        f"}}\n\n"
        f"export function getEntranceQuizParts(): {{ partNumber: number; partTitle: string }}[] {{\n"
        f"  return [\n"
        f"    {{ partNumber: 1, partTitle: 'Core Concepts' }},\n"
        f"    {{ partNumber: 2, partTitle: 'Key Processes' }},\n"
        f"    {{ partNumber: 3, partTitle: 'Patterns & Examples' }},\n"
        f"    {{ partNumber: 4, partTitle: 'Connections & Interactions' }},\n"
        f"    {{ partNumber: 5, partTitle: 'Change Over Time' }},\n"
        f"    {{ partNumber: 6, partTitle: 'Problem-Solving Workshop' }},\n"
        f"    {{ partNumber: 7, partTitle: 'AP Review' }}\n"
        f"  ]\n"
        f"}}\n"
    )


def main():
    expected = {
        "macro-ad-as", "macro-comparative-advantage", "macro-fiscal-policy",
        "macro-fiscal-policy-tools", "macro-gdp-growth", "macro-international-trade-finance",
        "macro-monetary-policy", "macro-money-banking", "macro-multiplier-effect",
        "macro-open-economy", "macro-phillips-curve", "macro-scarcity-opportunity-cost",
        "macro-unemployment-inflation",
    }
    missing = expected - set(T)
    extra = set(T) - expected
    if missing:
        raise SystemExit(f"Missing topics: {missing}")
    if extra:
        raise SystemExit(f"Unexpected topics: {extra}")

    for slug, data in T.items():
        path = os.path.join(OUT_DIR, f"{slug}.ts")
        with open(path, "w", encoding="utf-8") as f:
            f.write(render(slug, data))
        print(f"Wrote {path}")
    print(f"\nDone: {len(T)} entrance quiz files.")


if __name__ == "__main__":
    main()
