#!/usr/bin/env python3
"""AP Psychology entrance quizzes — Batch 1: Foundations & Biology (6 topics)."""
from __future__ import annotations
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _psych_quiz_common import write_batch

EXPECTED = {
    "history-approaches-psychology",
    "biological-bases-brain",
    "genetics-behavior",
    "sensation-sensory-processing",
    "perception-attention",
    "prenatal-childhood-development",
}

T = {
    "history-approaches-psychology": {
        "title": "History & Approaches of Psychology",
        "prefix": "hap",
        "qs": [
            ("Psychology as a formal discipline began with Wilhelm Wundt's 1879 lab in Leipzig. Wundt's school of psychology was:",
             ["Behaviorism", "Structuralism (using introspection to break consciousness into elements)", "Psychoanalysis", "Humanism"], 1,
             "Wundt (1879, Leipzig) and his student Edward Titchener pioneered structuralism, using trained introspection to identify the basic elements of conscious experience."),
            ("William James, author of 'Principles of Psychology' (1890), founded:",
             ["Structuralism", "Functionalism — studying how mental processes help organisms ADAPT and survive", "Behaviorism", "Cognitive psychology"], 1,
             "James, influenced by Darwin, asked WHY mental processes exist (their adaptive function) rather than what their elements are."),
            ("John B. Watson's 1913 paper 'Psychology as the Behaviorist Views It' argued psychology should:",
             ["Focus on the unconscious", "Study only observable behavior — abandoning introspection and consciousness", "Use brain scans", "Emphasize free will"], 1,
             "Watson rejected introspection as unscientific. Behaviorism (Watson, then Skinner) studied stimulus-response relationships only."),
            ("Sigmund Freud's psychoanalytic theory (developed ~1890s-1939) emphasized:",
             ["Conditioning", "Unconscious conflicts, childhood experiences, and sexual/aggressive drives shaping behavior", "Self-actualization", "Cognitive schemas"], 1,
             "Freud's psychoanalysis: id/ego/superego, defense mechanisms, and the unconscious. Largely unfalsifiable but historically dominant."),
            ("The 'cognitive revolution' of the 1950s-60s rejected behaviorism's strict S-R model. A landmark figure was:",
             ["B.F. Skinner", "Ulric Neisser (1967 'Cognitive Psychology') / George Miller (1956 'Magical Number 7±2')", "Carl Rogers", "Wilhelm Wundt"], 1,
             "Miller's 1956 paper on short-term memory capacity and Neisser's 1967 textbook formalized the return to studying mental processes."),
            ("Humanistic psychology (Maslow, Rogers; ~1950s-60s) emphasized:",
             ["Conditioning histories", "Free will, self-actualization, and human potential — a 'third force' between behaviorism and psychoanalysis", "Brain chemistry", "Innate reflexes only"], 1,
             "Maslow (hierarchy of needs) and Rogers (client-centered therapy) reacted against behaviorism's determinism and Freud's pessimism."),
            ("The biopsychosocial model holds that behavior results from:",
             ["Biology alone", "Interacting biological, psychological, AND social-cultural influences", "Free will alone", "Environment alone"], 1,
             "Modern psychology integrates levels of analysis: genes/neurons (bio) + thoughts/learning (psych) + culture/family (social)."),
            ("The natural-selection / evolutionary perspective (e.g., Buss) explains behavior in terms of:",
             ["Childhood trauma", "Adaptive value — traits that historically increased survival and reproduction", "Operant reinforcement only", "Free choice"], 1,
             "Evolutionary psychology asks why a behavior tendency was selected for in ancestral environments (e.g., disgust at spoiled food)."),
            ("Mary Whiton Calkins (1905) and Margaret Floy Washburn (1894) are notable for:",
             ["Founding behaviorism", "Being the first female president of the APA (Calkins) and first woman to earn a psychology PhD (Washburn) — early women in a male-dominated field", "Developing classical conditioning", "Inventing IQ tests"], 1,
             "Despite Harvard refusing to grant Calkins her earned PhD, she became APA president in 1905. Washburn earned her PhD at Cornell in 1894."),
            ("A psychiatrist differs from a psychologist primarily in that the psychiatrist:",
             ["Holds a PhD in psychology", "Holds an MD and can prescribe medication; usually treats severe mental illness biomedically", "Cannot do therapy", "Studies animals only"], 1,
             "Psychiatrists are physicians (MD/DO) who can prescribe drugs. Clinical psychologists hold PhD/PsyD and traditionally cannot prescribe (with limited state exceptions)."),
            ("Across the 20th century, psychology shifted from behaviorism (1920s-60s) to cognitive science (1960s+) largely because:",
             ["Behaviorism explained everything", "Behaviorism could not adequately explain language acquisition (Chomsky's 1959 critique of Skinner) or memory/problem solving", "Computers were banned", "Freud was rediscovered"], 1,
             "Chomsky's 1959 review of Skinner's 'Verbal Behavior' argued language richness exceeds what reinforcement alone could shape."),
            ("Modern positive psychology (Seligman, ~1998-) studies:",
             ["Mental illness only", "Strengths, virtues, and conditions that allow individuals and communities to thrive (well-being, flow, gratitude)", "Phobias", "The unconscious"], 1,
             "Seligman launched positive psychology to balance the field's heavy focus on disorder with study of flourishing."),
            ("On the AP Psych exam, identifying a 'theoretical perspective' from a vignette requires matching to:",
             ["Behavioral, biological, cognitive, evolutionary, humanistic, psychodynamic, or sociocultural perspectives", "One single 'correct' theory", "Only behaviorism", "Only Freud"], 0,
             "AP Psych Unit 1 expects students to recognize the seven major perspectives and identify which fits a given explanation."),
            ("Which AP-style claim is correct about psychology's history?",
             ["It became scientific only in the 21st century", "Its emergence (Wundt 1879) marks the separation from philosophy/physiology, with multiple competing schools developing throughout the 20th century", "Freud's theories are now experimentally confirmed", "Behaviorism remains the dominant approach today"], 1,
             "Wundt's 1879 lab is the conventional 'birth of psychology'; modern psychology is pluralistic, drawing on cognitive, biological, and social approaches."),
        ],
    },

    "biological-bases-brain": {
        "title": "Biological Bases of Behavior & the Brain",
        "prefix": "bbb",
        "qs": [
            ("A neuron's resting potential is approximately:",
             ["+30 mV", "−70 mV (inside negative relative to outside)", "0 mV", "−200 mV"], 1,
             "At rest, the neuron's interior is ~−70 mV due to the Na+/K+ pump and selective permeability."),
            ("An action potential occurs when depolarization reaches the:",
             ["Resting potential", "Threshold (~−55 mV), triggering Na+ channels to open and rapid depolarization to ~+30 mV", "Refractory period", "Synaptic cleft"], 1,
             "Threshold (~−55 mV) opens voltage-gated Na+ channels, producing the all-or-none action potential."),
            ("Action potentials follow the all-or-none law, meaning:",
             ["Stronger stimuli produce larger spikes", "A neuron either fires at full strength or not at all; intensity is coded by FREQUENCY of firing", "Neurons fire continuously", "Only some axons fire"], 1,
             "Stimulus strength is encoded by firing rate and number of neurons firing, not by AP amplitude."),
            ("Myelin sheath increases conduction speed by enabling:",
             ["Continuous depolarization", "Saltatory conduction — APs jump between Nodes of Ranvier", "Slower transmission", "Direct synapse formation"], 1,
             "Myelin (oligodendrocytes in CNS, Schwann cells in PNS) insulates axons; demyelination → multiple sclerosis."),
            ("Acetylcholine (ACh) at the neuromuscular junction causes:",
             ["Muscle relaxation only", "Muscle contraction; loss of ACh-producing neurons is implicated in Alzheimer's disease", "Pain transmission", "Sleep onset"], 1,
             "ACh contracts skeletal muscle. Botulinum toxin blocks ACh release (paralysis); curare blocks ACh receptors."),
            ("Dopamine is heavily implicated in:",
             ["Vision", "Reward, movement (Parkinson's = dopamine loss in substantia nigra), and addiction", "Sleep cycles only", "Hunger only"], 1,
             "Dopamine: reward circuits (VTA → nucleus accumbens), motor control. Schizophrenia involves excess dopamine activity (dopamine hypothesis)."),
            ("Serotonin (5-HT) low levels are associated with:",
             ["Mania only", "Depression and anxiety; SSRIs (e.g., Prozac, 1987) increase synaptic 5-HT", "Memory loss", "Hunger"], 1,
             "Selective serotonin reuptake inhibitors (SSRIs) treat major depression by blocking serotonin reuptake."),
            ("The sympathetic nervous system activates:",
             ["Rest-and-digest", "Fight-or-flight: ↑ heart rate, ↑ pupil dilation, ↓ digestion (epinephrine release from adrenal medulla)", "Sleep", "Salivation"], 1,
             "Sympathetic = arousal/stress response. Parasympathetic returns the body to baseline ('rest and digest')."),
            ("Lesion of the AMYGDALA produces:",
             ["Memory loss for facts", "Reduced fear response and difficulty recognizing fearful faces (e.g., patient SM, Klüver-Bucy syndrome)", "Loss of language", "Loss of vision"], 1,
             "Amygdala (limbic system) processes fear/threat. Patient SM (bilateral amygdala damage) shows fearlessness."),
            ("Phineas Gage (1848) — railroad worker whose tamping iron pierced his frontal lobe — provided early evidence that:",
             ["The brain is irrelevant to personality", "The frontal cortex is critical for personality, planning, and impulse control", "Language lives in the cerebellum", "Memory is in the brainstem"], 1,
             "Gage's personality changed dramatically post-injury (1848), demonstrating frontal-lobe role in executive function and social behavior."),
            ("Patient H.M. (Henry Molaison, 1953 surgery) had bilateral hippocampal removal. He could:",
             ["Form new long-term declarative memories", "Form new procedural skills but NOT new explicit (declarative) memories — proving hippocampus encodes new long-term memory", "Speak no language", "Not see"], 1,
             "H.M. (studied by Brenda Milner) showed memory is not unitary: procedural learning was intact, but new episodic/semantic memory was impossible."),
            ("Broca's area (left frontal lobe) damage causes:",
             ["Fluent but meaningless speech", "Non-fluent (expressive) aphasia: laborious, telegraphic speech with intact comprehension", "Total deafness", "Visual agnosia"], 1,
             "Broca (1861) identified left inferior frontal gyrus from patient 'Tan' — damage produces effortful, non-fluent speech."),
            ("On the AP Psych exam, an fMRI vs EEG question expects you to know:",
             ["fMRI has poor spatial but good temporal resolution", "fMRI = high spatial resolution / slow (~seconds); EEG = low spatial resolution / millisecond temporal resolution", "Both are identical", "Only EEG measures blood flow"], 1,
             "fMRI tracks BOLD signal (blood oxygenation, slow). EEG records scalp electrical activity (very fast, but spatially diffuse)."),
            ("Which AP-style claim is correct?",
             ["The corpus callosum produces dopamine", "The corpus callosum is the band of axons connecting the two cerebral hemispheres; severed in split-brain surgery (Sperry & Gazzaniga, 1960s)", "Split-brain patients lose all language", "The cerebellum controls vision"], 1,
             "Roger Sperry (Nobel 1981) studied split-brain patients (corpus callosotomy for epilepsy) revealing hemispheric specialization."),
        ],
    },

    "genetics-behavior": {
        "title": "Genetics & Behavior",
        "prefix": "gb",
        "qs": [
            ("Monozygotic (identical) twins share approximately:",
             ["50% of DNA", "100% of nuclear DNA (from a single zygote that split)", "25%", "0%"], 1,
             "MZ twins arise from one fertilized egg → genetically identical (apart from rare somatic mutations)."),
            ("Dizygotic (fraternal) twins share, on average:",
             ["100%", "About 50% of DNA — like ordinary siblings (two separate eggs and sperm)", "0%", "75%"], 1,
             "DZ twins are no more genetically related than typical siblings; they share a uterus but separate genotypes."),
            ("Heritability (h²) of a trait is:",
             ["The proportion of an INDIVIDUAL's trait due to genes", "The proportion of VARIATION in a trait within a population attributable to genetic differences (specific to that population & environment)", "Always 100%", "Always 50%"], 1,
             "Heritability is a population-level statistic — NOT 'how much of one person's IQ is genetic.' It varies by environment."),
            ("Estimated heritability of adult height in well-nourished populations is approximately:",
             ["10%", "About 80% — yet average height has risen ~10 cm in many countries since 1900 due to nutrition (high heritability ≠ unchangeable)", "0%", "100%"], 1,
             "Galton/modern twin studies: h² ~0.8 for height. The Flynn-like rise in stature shows environment still matters at population level."),
            ("Adoption studies separate genetic from environmental influence by comparing adoptees to:",
             ["Only their adoptive parents", "Both biological AND adoptive parents — and to biological vs adoptive siblings", "Strangers only", "Twins only"], 1,
             "Adoption designs (e.g., Texas Adoption Project, Minnesota Twin Study) leverage the natural separation of genes and rearing environment."),
            ("The Minnesota Study of Twins Reared Apart (Bouchard, 1979-) found MZ twins reared apart are surprisingly similar in:",
             ["Nothing", "Personality, intelligence, interests, and many physiological measures (challenging strict environmental views)", "Only height", "Only eye color"], 1,
             "Bouchard's MISTRA documented striking similarities in MZ-A twins, supporting substantial heritability for many psychological traits."),
            ("A genome-wide association study (GWAS) typically finds that complex traits (e.g., height, IQ, depression risk) involve:",
             ["A single gene", "Hundreds-to-thousands of genetic variants each with very small effects (polygenic architecture)", "Only mitochondrial DNA", "No genetic influence"], 1,
             "Modern GWAS show 'missing heritability' partly resolved by polygenic scores summing many small-effect variants."),
            ("Epigenetics studies how:",
             ["DNA sequence changes during life", "Environment can alter gene EXPRESSION (e.g., methylation) without changing the DNA sequence — sometimes heritable across generations", "Genes are deleted", "Cells divide"], 1,
             "Epigenetic marks (methylation, histone modification) can silence/activate genes. Maternal stress during pregnancy can alter offspring HPA-axis methylation."),
            ("Phenylketonuria (PKU) is a classic case of:",
             ["A disorder where genes determine the outcome regardless of environment", "Gene-environment interaction — homozygous PKU genotype causes severe disability ONLY if dietary phenylalanine is not restricted", "A purely environmental disorder", "An epigenetic-only disorder"], 1,
             "PKU (autosomal recessive) shows that even strongly genetic disorders may be entirely manageable by environmental intervention (low-Phe diet)."),
            ("Behavior geneticists distinguish 'shared' from 'non-shared' environment. Surprisingly, on personality:",
             ["Shared environment (same family) explains most variance", "NON-shared (unique) environment matters far more than shared family environment for adult personality", "Genes explain nothing", "Only birth order matters"], 1,
             "Behavior-genetic studies (Plomin, Daniels 1987) find shared family effects on adult personality near zero; non-shared experiences and genes dominate."),
            ("The nature-nurture debate is now generally resolved as:",
             ["Pure nature wins", "Nature AND nurture interact dynamically (gene × environment, epigenetics, evocative correlations) — both matter for nearly every trait", "Pure nurture wins", "Neither matters"], 1,
             "Modern consensus: the question is HOW genes and environments combine, not which one 'wins.'"),
            ("Twin/adoption heritability estimates for major depressive disorder are about:",
             ["0%", "30-40% — substantial but far from determining; environment, stress, and life events also strongly contribute", "100%", "Always 80%"], 1,
             "MDD twin studies (Sullivan et al. 2000 meta-analysis) estimate h² ≈ 0.37, leaving ~60% of variance to non-genetic factors."),
            ("On the AP Psych exam, a question asking about heritability expects you to:",
             ["Equate heritability with destiny", "Recognize heritability as the proportion of population variance due to genes — NOT a statement about an individual or about changeability", "Ignore environment", "Always answer 50%"], 1,
             "AP Psych emphasizes the population-level meaning of h² and the danger of misinterpreting it at the individual level."),
            ("Which AP-style claim is correct?",
             ["Genes alone determine behavior", "Behavior emerges from interactions among many genes, prenatal/postnatal environments, and learning histories — captured by the biopsychosocial model", "Environment alone determines behavior", "Heritability is always near 0"], 1,
             "AP Psych adopts an integrative biopsychosocial framing for nature-nurture questions."),
        ],
    },

    "sensation-sensory-processing": {
        "title": "Sensation & Sensory Processing",
        "prefix": "ssp",
        "qs": [
            ("Sensation refers to:",
             ["Interpreting stimuli", "DETECTION of physical energy by sensory receptors and transmission to the brain (bottom-up)", "Memory of stimuli", "Choosing a response"], 1,
             "Sensation = receptor detection + transduction. Perception = brain's interpretation/organization of those signals."),
            ("Transduction is the process of:",
             ["Sending nerves to muscles", "Converting physical energy (light, sound, pressure) into neural impulses", "Storing memories", "Talking"], 1,
             "Each sensory system has specialized transducers (rods/cones for light; hair cells for sound)."),
            ("The absolute threshold is defined as the minimum stimulus intensity detected:",
             ["100% of the time", "50% of the time", "Always", "Never"], 1,
             "Classic psychophysics defines absolute threshold as the intensity at which a person detects a stimulus on 50% of trials."),
            ("Weber's Law states the just-noticeable difference (JND) is:",
             ["Constant in absolute units", "A constant PROPORTION of the original stimulus (e.g., ~2% for weight)", "Unrelated to intensity", "Always 1 unit"], 1,
             "Ernst Weber (1834): ΔI/I = k. To notice a change, the increase must be a constant fraction of the baseline."),
            ("Signal Detection Theory (Tanner & Swets, 1954) holds that detection depends on:",
             ["Sensory acuity only", "BOTH sensory sensitivity (d') and a decision criterion influenced by motivation, expectation, fatigue", "Stimulus alone", "Cognition alone"], 1,
             "SDT explains hits/misses/false alarms by separating sensitivity from response bias."),
            ("Light enters the eye through the cornea and pupil, then is focused by the LENS via:",
             ["Translation", "Accommodation — changing lens shape to focus near vs far objects", "Refraction only", "Saccade"], 1,
             "Ciliary muscles change lens curvature (accommodation). Loss of flexibility → presbyopia with age."),
            ("Rods (vs cones) are specialized for:",
             ["Color vision in bright light", "Black-and-white vision in low light, peripheral vision; concentrated outside the fovea", "Daylight color", "Hearing"], 1,
             "~120M rods peripheral; ~6M cones in the fovea (red/green/blue). Cones for color and detail; rods for night/peripheral vision."),
            ("Trichromatic theory (Young-Helmholtz) states color vision arises from:",
             ["One receptor type", "Three cone types tuned roughly to short (blue), medium (green), and long (red) wavelengths", "Four cone types", "Rods only"], 1,
             "Young (1802)/Helmholtz (1852) trichromatic theory was confirmed when three cone photopigments were identified."),
            ("Opponent-process theory (Hering, 1878) explains:",
             ["Rod sensitivity", "Color afterimages and color blindness — neurons fire in opposing pairs (red-green, blue-yellow, black-white)", "Hearing", "Smell"], 1,
             "Modern view: trichromatic at receptor level, opponent-process at ganglion-cell/LGN level. Both theories are correct at different stages."),
            ("Sound waves are transduced by hair cells in the:",
             ["Cochlea (in the inner ear, on the basilar membrane)", "Eardrum", "Eustachian tube", "Pinna"], 0,
             "Vibrations move ossicles → oval window → cochlear fluid → bend stereocilia on hair cells → AP in auditory nerve."),
            ("Place theory of pitch perception holds that pitch is coded by:",
             ["Firing rate alone", "WHICH place along the basilar membrane is maximally stimulated (best for high frequencies)", "Loudness", "Timbre"], 1,
             "Békésy (Nobel 1961): different frequencies peak at different basilar membrane locations (high pitch near oval window)."),
            ("Sensory adaptation refers to:",
             ["Increased sensitivity over time", "Decreased responsiveness to a constant, unchanging stimulus (e.g., not feeling clothes against skin)", "Absolute threshold", "Just-noticeable difference"], 1,
             "Receptors fatigue/adapt to constant input, freeing attention for changing stimuli (informational value)."),
            ("On the AP Psych exam, a question describing 'feeling colder when first jumping in a pool, then adjusting' expects:",
             ["Subliminal perception", "Sensory adaptation", "Weber's law", "Transduction failure"], 1,
             "Adaptation reduces firing in response to a constant stimulus (temperature receptors equilibrate)."),
            ("Which AP-style claim is correct?",
             ["Subliminal stimuli reliably control behavior", "Subliminal stimuli (below absolute threshold) can produce small, fleeting priming effects but do NOT control complex behavior, despite popular myths", "All sensation requires conscious attention", "Sensation and perception are identical"], 1,
             "Greenwald (1992) and others: subliminal priming exists but is weak and not 'mind control.'"),
        ],
    },

    "perception-attention": {
        "title": "Perception & Attention",
        "prefix": "pa",
        "qs": [
            ("Perception involves:",
             ["Receptor activity only", "Top-down organization and INTERPRETATION of sensory data, shaped by prior knowledge and expectations", "Reflex actions", "Storage in memory"], 1,
             "Perception adds meaning to raw sensation, combining bottom-up data with top-down expectations (schemas, context)."),
            ("Bottom-up processing is driven by:",
             ["Expectations", "The sensory input itself — building from features upward", "Memories", "Schemas"], 1,
             "Bottom-up = data-driven. Top-down = concept-driven (using context, prior knowledge)."),
            ("Gestalt psychologists (Wertheimer ~1912) argued:",
             ["Perception is the sum of sensations", "'The whole is OTHER than the sum of its parts' — we organize stimuli using grouping principles", "Sensation requires no organization", "Only structuralism is correct"], 1,
             "Gestalt principles (proximity, similarity, continuity, closure, figure-ground) describe automatic perceptual organization."),
            ("The figure-ground principle holds that we automatically:",
             ["See everything as one shape", "Separate a scene into a FIGURE (object) standing out against a BACKGROUND (e.g., Rubin's vase-faces)", "Cannot organize visual scenes", "Use only color cues"], 1,
             "Figure-ground (Rubin, 1915): even ambiguous figures force a perceptual choice between competing organizations."),
            ("Binocular depth cues include:",
             ["Linear perspective", "Retinal disparity and convergence — requiring two eyes", "Texture gradient", "Interposition"], 1,
             "Binocular = two eyes (disparity = different image in each eye; convergence = eye angle for near objects). Monocular cues = perspective, interposition, texture, etc."),
            ("Linear perspective (parallel lines converging in the distance) is a:",
             ["Binocular cue", "Monocular depth cue", "Vestibular cue", "Auditory cue"], 1,
             "Monocular cues (one eye sufficient): linear perspective, relative size, interposition, texture gradient, light/shadow, motion parallax."),
            ("Phi phenomenon (Wertheimer 1912) — the illusion of motion from rapidly flashing stationary lights — demonstrates:",
             ["Perceptual constancy", "That perception ADDS information not present in the raw sensation (basis of motion pictures)", "Sensation = perception", "Color blindness"], 1,
             "Phi (and stroboscopic) movement underlies film/TV. Brain constructs continuous motion from discrete frames."),
            ("Perceptual constancy means we perceive objects as:",
             ["Always changing", "Stable in size, shape, color, and brightness despite changes in retinal image (e.g., a door looks rectangular at any angle)", "Two-dimensional", "Random"], 1,
             "Without size/shape/color constancy, the world would seem chaotic as our viewpoint shifted."),
            ("Selective attention is dramatically illustrated by Simons & Chabris (1999) 'invisible gorilla' study, in which:",
             ["All viewers noticed the gorilla", "About 50% of viewers counting basketball passes failed to notice a gorilla walking through — INATTENTIONAL BLINDNESS", "No gorilla was used", "Only children noticed"], 1,
             "Inattentional blindness: focused attention on one task makes unexpected stimuli invisible despite being in plain view."),
            ("Cherry's (1953) cocktail-party effect demonstrates that:",
             ["We process all conversations equally", "We can selectively attend to ONE conversation among many but our name in the unattended channel still grabs attention", "We hear nothing in unattended channels", "Attention is unlimited"], 1,
             "Dichotic listening shows attention filters most unattended content but personally relevant signals (your name) break through."),
            ("Change blindness (Rensink, Simons) refers to:",
             ["Inability to see motion", "Failure to notice large changes between two scenes when changes occur during a brief disruption", "Color blindness", "Permanent blindness"], 1,
             "Change blindness shows our visual world is far less detailed than it feels — we hold limited information across saccades."),
            ("Top-down processing is illustrated by:",
             ["A reflex", "The McGurk effect (visual lip-reading alters what you HEAR) or context-driven word recognition", "Pure photoreceptor activity", "Pupil dilation"], 1,
             "Top-down example: hearing 'ba' but seeing lips say 'ga' produces the perception 'da' (McGurk & MacDonald, 1976)."),
            ("On the AP Psych exam, a question describing a person not noticing a change to a computer-screen image during a flicker expects:",
             ["Inattentional blindness", "Change blindness", "Sensory adaptation", "Phi phenomenon"], 1,
             "Change blindness specifically refers to missing differences between two states separated by a disruption."),
            ("Which AP-style claim is correct?",
             ["Perception is purely bottom-up", "Perception combines bottom-up sensory data with top-down expectations, organized by Gestalt principles and limited by attention", "Attention is unlimited", "Sensation and perception are identical"], 1,
             "Modern view integrates Gestalt organization, top-down schemas, and selective attention as joint contributors to perception."),
        ],
    },

    "prenatal-childhood-development": {
        "title": "Prenatal & Childhood Development",
        "prefix": "pcd",
        "qs": [
            ("The three prenatal stages, in order, are:",
             ["Fetal, embryonic, germinal", "Germinal (0-2 wk), embryonic (3-8 wk), fetal (9 wk-birth)", "Embryonic, germinal, fetal", "Fetal, germinal, embryonic"], 1,
             "Germinal: zygote to implantation. Embryonic: organ formation (most teratogen-vulnerable). Fetal: growth and refinement."),
            ("Teratogens are agents that:",
             ["Promote prenatal growth", "Cross the placenta and harm prenatal development (e.g., alcohol, certain drugs, viruses)", "Are always genetic", "Affect only adults"], 1,
             "Maternal alcohol use can cause Fetal Alcohol Syndrome (FAS): facial abnormalities, growth deficits, intellectual disability."),
            ("Newborn reflexes include:",
             ["Driving and reading", "Rooting (turning head toward cheek touch), sucking, grasping, Moro (startle) — present at birth, fade by ~6 months", "Walking and talking", "Algebra"], 1,
             "Reflexes provide adaptive value (rooting helps feeding) and assess neurological development. Persistence past expected age may signal problems."),
            ("Habituation studies show infants:",
             ["Cannot perceive at all", "Look LESS at familiar stimuli and MORE at novel ones — used to infer perceptual and cognitive abilities", "Are blind for 6 months", "Cannot distinguish faces"], 1,
             "Habituation paradigms reveal that even young infants discriminate phonemes, faces, and quantities."),
            ("Piaget's SENSORIMOTOR stage (birth - ~2 yr) is characterized by:",
             ["Abstract thinking", "Learning through senses and actions; achieving OBJECT PERMANENCE around 8 months", "Conservation", "Hypothetical reasoning"], 1,
             "Sensorimotor: infants build mental representations through action. Object permanence = knowing things exist when out of sight."),
            ("Piaget's PREOPERATIONAL stage (~2-7 yr) features:",
             ["Conservation mastery", "Egocentrism (3-Mountains Task), centration, lack of conservation; rapid language and pretend play", "Abstract reasoning", "Object permanence emerging"], 1,
             "Preoperational kids often fail conservation (taller glass = more water) and show egocentrism (assuming others see what they see)."),
            ("Vygotsky's 'Zone of Proximal Development' (ZPD) refers to:",
             ["What a child cannot do at all", "The gap between what a child can do alone and what they can do with SCAFFOLDING from a more capable partner", "Adult performance", "IQ score"], 1,
             "Vygotsky (1896-1934) emphasized social/cultural context: learning happens through guided participation in the ZPD."),
            ("Theory of Mind (typically achieved ~age 4-5) is the:",
             ["Ability to read", "Understanding that others have beliefs, desires, and perspectives DIFFERENT from one's own (false-belief / Sally-Anne tasks)", "IQ", "Memory span"], 1,
             "Wimmer & Perner (1983) Sally-Anne task. Delayed ToM is characteristic of autism (Baron-Cohen 1985)."),
            ("Harlow's monkey studies (1958) showed infant monkeys preferred:",
             ["Wire 'mothers' that fed them", "CLOTH 'mothers' even when wire mothers provided food — demonstrating contact comfort over feeding for attachment", "Neither mother", "Always real mothers"], 1,
             "Harlow's surrogate-mother experiments overturned 'cupboard love' theory; attachment is about comfort, not just feeding."),
            ("Mary Ainsworth's Strange Situation (1970) classifies infant attachment as:",
             ["Only one type", "Secure, insecure-avoidant, insecure-anxious/ambivalent (and later disorganized) — based on responses to mother's separation/return", "IQ-based", "Random"], 1,
             "About 60-70% of U.S. infants classified as securely attached; predicts later social-emotional outcomes."),
            ("Erik Erikson's first psychosocial stage (infancy) is:",
             ["Autonomy vs shame", "Trust vs Mistrust — caregiver responsiveness builds basic trust in the world", "Industry vs inferiority", "Identity vs role confusion"], 1,
             "Erikson's 8 stages span the lifespan; each stage has a developmental crisis whose resolution shapes later development."),
            ("Lawrence Kohlberg's moral development uses dilemmas (e.g., Heinz) to identify levels:",
             ["Pre-moral, moral, post-moral", "Preconventional (consequences), Conventional (rules/social order), Postconventional (universal principles)", "Only one level", "Ethics is innate"], 1,
             "Kohlberg's levels (built on Piaget) classify moral REASONING. Critiqued by Carol Gilligan (1982) for under-representing care/relational ethics."),
            ("On the AP Psych exam, a question describing a 4-year-old who insists pouring juice into a tall glass means 'more juice' tests:",
             ["Conservation failure (preoperational stage)", "Object permanence", "Abstract reasoning", "Theory of mind"], 0,
             "Conservation = understanding quantity stays the same despite shape changes. Mastered ~age 7 (concrete operational)."),
            ("Which AP-style claim is correct?",
             ["Development is purely genetic", "Development reflects continuous interaction of biological maturation with experience; modern critics see Piaget's stages as more gradual and culturally variable than originally proposed", "Vygotsky rejected social influence", "Attachment quality has no later effects"], 1,
             "Modern developmental psychology integrates Piaget, Vygotsky, attachment theory, and biopsychosocial influences."),
        ],
    },
}

if __name__ == "__main__":
    write_batch(T, EXPECTED)
