#!/usr/bin/env python3
"""
AAS entrance quizzes — Batch 3 (4 topics):
  aas-black-power-beyond, aas-movements-debates, aas-practice-freedom,
  aas-contemporary-issues
"""
from __future__ import annotations
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _aas_quiz_common import write_batch  # type: ignore

T: dict = {}

# ────────────────────────────────────────────────────────────────────────────
# 11. Black Power & Beyond
# ────────────────────────────────────────────────────────────────────────────
T["aas-black-power-beyond"] = {
    "title": "Black Power & Beyond",
    "prefix": "aasbpb",
    "qs": [
        # Part 1
        ("In AP African American Studies, the slogan \"Black Power\" was popularized by:",
         ["Martin Luther King, Jr. at the 1963 March on Washington.",
          "SNCC Chair Stokely Carmichael (later Kwame Ture) on June 16, 1966 during the Meredith March Against Fear in Greenwood, Mississippi — articulated more fully in Carmichael and Charles V. Hamilton's *Black Power: The Politics of Liberation* (1967).",
          "W. E. B. Du Bois in 1903.",
          "Marcus Garvey in 1920."],
         1,
         "Stokely Carmichael's June 16, 1966 Greenwood speech popularized \"Black Power\"; Carmichael and Hamilton's *Black Power* (1967) provided the book-length articulation."),
        ("\"Black Power\" most precisely refers to:",
         ["A purely electoral campaign with no cultural component.",
          "A multifaceted political and cultural framework — including community control, self-defense, Black pride, Pan-Africanism, and economic autonomy — that succeeded the integrationist Civil Rights phase from roughly 1966 onward.",
          "A 19th-century abolitionist program.",
          "A federal antipoverty agency."],
         1,
         "Black Power encompassed political (community control, electoral mobilization), cultural (Black pride, Black Arts), and economic (self-help, cooperatives) strands — see Peniel Joseph, *Waiting 'Til the Midnight Hour* (2006)."),
        # Part 2
        ("Which organization is most associated with the Black Power era's community programs and armed self-defense?",
         ["The NAACP Youth Council.",
          "The Black Panther Party for Self-Defense, founded in Oakland, CA, October 15, 1966 by Huey P. Newton and Bobby Seale, whose 10-Point Program demanded employment, housing, education, and an end to police brutality, and whose \"survival programs\" included Free Breakfast for Children (1969) and free health clinics.",
          "The Christian Coalition.",
          "The Knights of Labor."],
         1,
         "The BPP (founded Oct 15, 1966 by Newton + Seale) combined armed self-defense with extensive \"survival programs\" — Free Breakfast (1969), clinics, Liberation Schools — under FBI COINTELPRO surveillance."),
        ("FBI Counterintelligence Program (COINTELPRO) actions against Black Power organizations included:",
         ["Open public hearings and transparent oversight.",
          "Covert surveillance, infiltration, forged correspondence, and direct action — most notoriously the December 4, 1969 Chicago police raid (coordinated with the FBI) that killed Black Panther leaders Fred Hampton and Mark Clark in their beds.",
          "A federal grant program for the Panthers.",
          "A purely constitutional dialogue."],
         1,
         "COINTELPRO's anti-Panther operations included infiltration, forged letters fomenting splits, and the Dec 4, 1969 Chicago raid that killed Fred Hampton and Mark Clark; Senator Frank Church's 1976 hearings exposed the program."),
        # Part 3
        ("Which dated event illustrates the international dimension of Black Power?",
         ["The 1968 Mexico City Olympics, where U.S. sprinters Tommie Smith (gold) and John Carlos (bronze) raised black-gloved fists during the U.S. national anthem on October 16, 1968 — wearing Olympic Project for Human Rights badges and standing in solidarity with second-place Australian Peter Norman.",
          "The 1936 Berlin Olympics.",
          "The 1980 Moscow Olympics.",
          "The 1996 Atlanta Olympics."],
         0,
         "The Smith–Carlos salute (Oct 16, 1968) at the Mexico City Olympics — with Australian Peter Norman wearing the OPHR badge — internationalized Black Power's symbolic vocabulary."),
        ("The Black Arts Movement (c. 1965–1975) is best characterized as:",
         ["The cultural arm of the Civil Rights Movement, focused exclusively on integration.",
          "The cultural counterpart of Black Power, launched after Malcolm X's assassination on February 21, 1965 — Amiri Baraka founded the Black Arts Repertory Theatre/School in Harlem; figures included Sonia Sanchez, Nikki Giovanni, Larry Neal, and Maulana Karenga (founder of Kwanzaa, 1966); theorized in Larry Neal's \"The Black Arts Movement\" essay (*Drama Review*, 1968).",
          "A 1920s literary movement only.",
          "A purely European theater movement."],
         1,
         "The Black Arts Movement (Baraka, Sanchez, Giovanni, Neal, Karenga) was Black Power's cultural arm; Larry Neal's 1968 *Drama Review* essay is its key manifesto."),
        # Part 4
        ("How does Black Power connect to the Civil Rights Movement?",
         ["Black Power had no relation to the Civil Rights Movement.",
          "Black Power emerged out of, and in critique of, the integrationist Civil Rights phase — reflecting frustration with the slow pace of change after the Civil Rights Act (1964) and Voting Rights Act (1965), Northern de facto segregation, the Watts uprising (August 1965), and the assassinations of Malcolm X (1965) and King (1968).",
          "Black Power preceded and produced the Civil Rights Movement.",
          "The two movements had no shared participants."],
         1,
         "Black Power emerged out of and beyond the Civil Rights phase; SNCC's 1966 turn under Carmichael, the Watts uprising (Aug 11–16, 1965), and Malcolm X's 1965 assassination + King's 1968 assassination shaped this transition."),
        ("Which AP analytical skill is most directly tested by comparing King and the late-1960s Black Power leaders?",
         ["Memorization without comparison.",
          "Comparison: shared ultimate goal of Black liberation but contrasting tactics (nonviolence vs. self-defense), targets (federal legislation vs. community control), and rhetoric (American creed vs. Black pride and Pan-Africanism); King's own \"Beyond Vietnam\" (1967) and Poor People's Campaign moved partly toward Black Power's structural critique.",
          "Free recall of unrelated events.",
          "Citing only modern sources."],
         1,
         "AP comparison rewards explicit similarity *and* difference — King's late-period economic and antiwar turn (\"Beyond Vietnam\" 1967, Poor People's Campaign) narrowed the strategic distance with Black Power."),
        # Part 5
        ("Which best describes a major change in Black politics between the late 1960s and the 1970s?",
         ["Black electoral politics collapsed.",
          "After the VRA (1965) and Black Power's emphasis on community control, Black elected officeholders rose sharply — including the first wave of Black big-city mayors: Carl Stokes (Cleveland, 1967), Richard Hatcher (Gary, 1967), Coleman Young (Detroit, 1973), Maynard Jackson (Atlanta, 1973), and Tom Bradley (Los Angeles, 1973).",
          "There were no Black mayors in major U.S. cities through 1980.",
          "Black voter turnout fell to zero by 1975."],
         1,
         "1967–1973 saw a wave of Black big-city mayors (Stokes, Hatcher, Young, Jackson, Bradley) — the electoral counterpart to Black Power's community-control politics."),
        ("Which best describes a continuity from Civil Rights through Black Power?",
         ["The two movements shared no organizational or human ties.",
          "Many Black Power organizations grew directly out of Civil Rights organizations and their veterans (SNCC veterans staffed BPP and CORE leadership; Ella Baker mentored both Civil Rights and Black Power organizers), and both phases relied on Black church, college, and press networks.",
          "All Civil Rights organizations dissolved before Black Power emerged.",
          "There was no continuity in personnel between phases."],
         1,
         "Continuity = shared personnel (SNCC → BPP/CORE; Baker mentoring across phases) and shared institutional infrastructure (Black church, HBCUs, Black press)."),
        # Part 6
        ("A historian wants to study Black Power's political theory in its own words. Which source is most directly useful?",
         ["A 21st-century policy memo.",
          "Stokely Carmichael and Charles V. Hamilton's *Black Power: The Politics of Liberation* (1967), Malcolm X's *The Autobiography of Malcolm X* (with Alex Haley, 1965), the Black Panther Party's *10-Point Program* (October 1966), and Angela Davis's *Women, Race & Class* (1981).",
          "An undated, anonymous flyer.",
          "A modern textbook with no primary excerpts."],
         1,
         "Carmichael & Hamilton (1967), the *Autobiography of Malcolm X* (1965), the BPP 10-Point Program (1966), and Davis (1981) are core AP primary sources for Black Power's theory."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point on the BPP 10-Point Program (1966)?",
         ["Quoting it without comment.",
          "Noting that Newton and Seale drafted it in October 1966 in Oakland — a city with documented patterns of police violence and post-WWII Black migration to defense-industry jobs — and using that local situation to evaluate the program's emphasis on housing, employment, education, and an end to police brutality.",
          "Listing only the date with no analysis.",
          "Ignoring its Oakland origins entirely."],
         1,
         "AP sourcing requires *use* of audience/purpose/situation — Oakland's specific Black demographic and policing context shaped the BPP 10-Point Program."),
        # Part 7
        ("Which is the strongest one-sentence thesis on Black Power and beyond?",
         ["Black Power was important.",
          "Between roughly 1965 and 1975, Black Power — articulated by Stokely Carmichael (1966), embodied by the Black Panther Party (1966) and the Black Arts Movement (Baraka, Sanchez, Neal), and amplified internationally at the 1968 Mexico City Olympics — combined armed self-defense, community control, and Black cultural autonomy in critique of the limits of the Civil Rights phase, even as FBI COINTELPRO repression (the Dec 4, 1969 killings of Hampton and Clark) constrained its organizational reach.",
          "Black Power had no political consequences.",
          "The Civil Rights and Black Power phases were identical."],
         1,
         "Strong AP theses combine periodization, named figures and organizations, dated events, and a complexity move (state repression as constraint)."),
        ("On the AP exam, the strongest move when writing about Black Power is to:",
         ["Avoid all dates and named figures.",
          "Anchor claims in a named figure (Malcolm X, Carmichael, Newton, Seale, Hampton, Baraka, Davis), a dated event (Feb 21, 1965 Malcolm X assassination; Aug 1965 Watts; June 16, 1966 Greenwood; Oct 15, 1966 BPP; Oct 16, 1968 Smith–Carlos; Dec 4, 1969 Hampton–Clark), and a primary source (Carmichael & Hamilton 1967; *Autobiography of Malcolm X* 1965).",
          "Cite no sources at all.",
          "Use only modern op-eds."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# 12. Movements & Debates
# ────────────────────────────────────────────────────────────────────────────
T["aas-movements-debates"] = {
    "title": "Movements & Debates in African American Studies",
    "prefix": "aasmd",
    "qs": [
        # Part 1
        ("In AP African American Studies, the field's intellectual origins trace most directly to:",
         ["A 21st-century social-media debate.",
          "Late-19th- and early-20th-century Black scholarship including W. E. B. Du Bois's *The Philadelphia Negro* (1899) and *The Souls of Black Folk* (1903), Carter G. Woodson's *The Mis-Education of the Negro* (1933), and Woodson's founding of the Association for the Study of Negro Life and History (1915) and Negro History Week (1926).",
          "Post-1990 academic theory only.",
          "A 17th-century European academy."],
         1,
         "Du Bois (*Philadelphia Negro* 1899, *Souls* 1903) and Woodson (ASNLH 1915, Negro History Week 1926, *Mis-Education* 1933) are foundational figures of African American Studies."),
        ("Black Studies as a university discipline emerged most directly from:",
         ["A 19th-century European academic reform.",
          "Late-1960s student-led campaigns — most prominently the San Francisco State College Third World Liberation Front strike (November 1968 – March 1969) — which led to the founding of the first Black Studies department in 1968 (chaired by Nathan Hare) and prompted similar departments nationwide.",
          "A 1920s federal directive.",
          "A 1980s privatization initiative."],
         1,
         "The SF State strike (Nov 1968 – Mar 1969) and Nathan Hare's 1968 chairmanship founded the first Black Studies department, sparking departments at Cornell, Harvard, UCLA, and elsewhere."),
        # Part 2
        ("Which Black feminist organization is most associated with the 1977 statement coining the phrase \"interlocking oppressions\"?",
         ["The General Federation of Women's Clubs.",
          "The Combahee River Collective, whose April 1977 *Combahee River Collective Statement* — drafted by Barbara Smith, Beverly Smith, and Demita Frazier — argued that race, gender, class, and sexuality form interlocking systems and shaped what Kimberlé Crenshaw later (1989, 1991) named \"intersectionality.\"",
          "The 19th Amendment Suffrage Association.",
          "The Daughters of the American Revolution."],
         1,
         "The Combahee River Collective (founded 1974) issued its 1977 Statement (Smith, Smith, Frazier) on interlocking oppressions; Kimberlé Crenshaw's 1989/1991 essays formalized \"intersectionality.\""),
        ("\"Afrocentricity,\" as articulated by Molefi Kete Asante in *Afrocentricity* (1980), most precisely refers to:",
         ["A purely Eurocentric framework with no African content.",
          "A theoretical framework that places African civilizations and African agency at the center of historical and cultural analysis — debated within the field for both its emphasis on continental African heritage and critiques of its essentialist tendencies.",
          "A 19th-century abolitionist tactic.",
          "A post-2010 social-media slogan."],
         1,
         "Molefi Asante's *Afrocentricity* (1980) and *The Afrocentric Idea* (1987) frame the field; debates within Black Studies have engaged both its political utility and critiques of essentialism (e.g., Anthony Appiah)."),
        # Part 3
        ("Which dated example best illustrates internal debate within African American thought?",
         ["The Du Bois–Washington debate of the early 1900s — Booker T. Washington's 1895 \"Atlanta Compromise\" speech advocating vocational education and accommodation versus W. E. B. Du Bois's 1903 *Souls of Black Folk* essay \"Of Mr. Booker T. Washington and Others\" demanding immediate civil and political rights and the \"Talented Tenth.\"",
          "A 17th-century European theological dispute.",
          "A 1990s tax-policy debate.",
          "A 21st-century reality-TV controversy."],
         0,
         "The Washington–Du Bois debate (Atlanta 1895 vs. *Souls* 1903) is the classic AP-tested intra-Black strategic debate of the post-Reconstruction era."),
        ("Critical Race Theory (CRT), as developed in legal scholarship from the 1970s–90s, is best characterized as:",
         ["A K-12 elementary curriculum.",
          "A graduate-level legal academic framework — pioneered by Derrick Bell (*Faces at the Bottom of the Well*, 1992), Kimberlé Crenshaw, Richard Delgado, and Patricia Williams — that analyzes how race and racism are embedded in U.S. law and institutions, including post-civil-rights persistence of inequality.",
          "A 19th-century military doctrine.",
          "A purely religious doctrine."],
         1,
         "CRT (Bell, Crenshaw, Delgado, Williams) is a graduate-level legal-academic framework that emerged in the late 1970s–80s out of critical legal studies and Black liberation thought."),
        # Part 4
        ("How does Black feminism connect to the Civil Rights and Black Power phases?",
         ["Black feminism had no connection to either movement.",
          "Black feminist thought (Combahee 1977; Crenshaw 1989; Patricia Hill Collins's *Black Feminist Thought*, 1990) emerged in part from Black women's experience that the Civil Rights, Black Power, and second-wave feminist movements each centered some axes of identity (race or gender) while neglecting others — articulating intersectionality as both critique and method.",
          "Black women played no role in any prior movement.",
          "Black feminism predated all 19th-century abolitionism."],
         1,
         "Combahee 1977, Crenshaw 1989, and Collins 1990 explicitly responded to the gaps in both Civil Rights/Black Power and second-wave white feminist analysis."),
        ("Which AP analytical skill is most directly tested by debating Pan-Africanism vs. integrationism?",
         ["Memorization without comparison.",
          "Comparison: both responded to anti-Black racism but Pan-Africanism (Garvey's UNIA 1914; the Pan-African Congresses organized by Du Bois 1900–1945; Kwame Nkrumah's Ghana 1957) emphasized transnational Black solidarity and African liberation, while integrationism (NAACP, SCLC) sought full citizenship within the U.S. nation-state.",
          "Free recall of unrelated facts.",
          "Citing only modern sources."],
         1,
         "AP comparison rewards explicit similarity *and* difference — Pan-African (Garvey, Du Bois Pan-African Congresses, Nkrumah) vs. integrationist (NAACP, SCLC) strategies and audiences."),
        # Part 5
        ("Which best describes a major change in the institutional status of African American Studies?",
         ["The field had no university programs through 2000.",
          "From 1968's first Black Studies department at SF State, the field has expanded to hundreds of U.S. departments and programs, the founding of *The Journal of Black Studies* (1970) and *The Black Scholar* (1969), Harvard's W. E. B. Du Bois Institute (1975, now Hutchins Center), and the College Board's launch of AP African American Studies (pilot 2022; full launch 2024–25).",
          "The field shrank from hundreds of programs to none after 1980.",
          "AP African American Studies launched in 1980."],
         1,
         "From SF State 1968 through *The Black Scholar* (1969), *Journal of Black Studies* (1970), Harvard DBI (1975, now Hutchins Center), to the AP African American Studies pilot (2022) and full launch — a sustained institutional expansion."),
        ("Which best describes a continuity across African American intellectual history?",
         ["The field is a 21st-century invention with no earlier roots.",
          "A consistent commitment to using rigorous study of Black life — historical, sociological, literary, artistic — both to refute racist scholarship and to support liberation, traceable from Frederick Douglass (1845) and Anna Julia Cooper (*A Voice from the South*, 1892) through Du Bois (1903), Woodson (1933), Hurston (1937), Davis (1981), and Crenshaw (1989).",
          "Black scholarship had no political stakes in any era.",
          "The field has no consistent intellectual project."],
         1,
         "Continuity = a sustained commitment to rigorous scholarship of Black life as both refutation of racism and support for liberation, across Cooper 1892, Du Bois 1903, Woodson 1933, Hurston 1937, Davis 1981, Crenshaw 1989."),
        # Part 6
        ("A student wants to analyze the founding theoretical move of intersectionality. Which source is most directly useful?",
         ["A 21st-century social-media post.",
          "Kimberlé Crenshaw's *\"Demarginalizing the Intersection of Race and Sex\"* (*University of Chicago Legal Forum*, 1989) and *\"Mapping the Margins\"* (*Stanford Law Review*, 1991), paired with the *Combahee River Collective Statement* (1977) and Patricia Hill Collins's *Black Feminist Thought* (1990).",
          "An undated, anonymous flyer.",
          "A modern textbook with no primary excerpts."],
         1,
         "Crenshaw 1989 + 1991, Combahee 1977, and Collins 1990 are the foundational primary sources for AP analysis of intersectionality."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point on Crenshaw's 1989 article?",
         ["Quoting it without comment.",
          "Noting that Crenshaw published in the *University of Chicago Legal Forum* in 1989 as a response to anti-discrimination law cases (*DeGraffenreid v. General Motors*, 1976) where Black women's claims fell between race and sex categories, and using that legal context to evaluate her introduction of \"intersectionality\" as a doctrinal corrective.",
          "Citing only the year with no analysis.",
          "Ignoring the legal cases that prompted it."],
         1,
         "AP sourcing requires *use* of audience/purpose/situation — Crenshaw's 1989 piece directly addressed legal anti-discrimination doctrine (*DeGraffenreid* 1976) that erased Black women's compound claims."),
        # Part 7
        ("Which is the strongest one-sentence thesis on movements and debates in African American Studies?",
         ["Black scholars debated many topics.",
          "From Cooper (1892) and Du Bois's debates with Booker T. Washington (1895–1903) through Carter G. Woodson's institutional founding (ASNLH 1915), the post-1968 establishment of Black Studies departments, and Black feminist articulation of intersectionality (Combahee 1977; Crenshaw 1989), African American Studies has sustained an ongoing scholarly tradition that combines rigorous research with debates over strategy — integration vs. separatism, Pan-Africanism vs. nationalism, single-axis vs. intersectional analysis — to support Black liberation.",
          "African American Studies has no internal debates.",
          "All Black scholars have always agreed."],
         1,
         "Strong AP theses combine periodization, named figures and works, named debates, and a complexity move (rigor + liberation; ongoing strategic disagreement)."),
        ("On the AP exam, the strongest move when writing about movements and debates is to:",
         ["Avoid all dates and named figures.",
          "Anchor claims in a named figure (Cooper, Du Bois, Washington, Woodson, Asante, Crenshaw, Collins, Nathan Hare), a dated event (1895 Atlanta, 1903 *Souls*, 1915 ASNLH, 1968 SF State, 1977 Combahee, 1989 Crenshaw), and a primary source (Cooper 1892, Du Bois 1903, Combahee 1977, Crenshaw 1989).",
          "Cite no sources at all.",
          "Use only 21st-century pop culture."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# 13. Practice of Freedom
# ────────────────────────────────────────────────────────────────────────────
T["aas-practice-freedom"] = {
    "title": "Practice of Freedom",
    "prefix": "aaspf",
    "qs": [
        # Part 1
        ("In AP African American Studies, the \"practice of freedom\" most precisely refers to:",
         ["A purely 21st-century social-media phenomenon.",
          "The ongoing, everyday work — political, cultural, religious, educational, economic — by which Black communities have built and sustained free Black life under and beyond formal legal emancipation, from the antebellum era through the present.",
          "A 17th-century theological doctrine.",
          "A purely federal legislative process."],
         1,
         "The \"practice of freedom\" frames freedom as ongoing institution-building (church, school, press, family, electoral, cultural) rather than a single legal moment."),
        ("\"Freedom dreams,\" as theorized by historian Robin D. G. Kelley in *Freedom Dreams: The Black Radical Imagination* (2002), refers to:",
         ["A 21st-century reality-television concept.",
          "The visions of liberated Black futures — from maroon communities through Reconstruction land redistribution, Garveyism, civil rights, Black Power, and Afrofuturism — that Kelley argues sustain and direct Black political action.",
          "A 19th-century European philosophical school.",
          "A purely individual psychological process with no political content."],
         1,
         "Kelley's *Freedom Dreams* (2002) frames Black radical imagination — from maroons to Afrofuturism — as a sustained tradition that orients Black political practice."),
        # Part 2
        ("Which institution has most consistently served as a center of African American collective life from the 18th century to the present?",
         ["The U.S. Senate.",
          "The Black church — including the African Methodist Episcopal Church (AME, founded by Richard Allen, Philadelphia, 1816), the AME Zion Church (1821), the National Baptist Convention (1895), and the Church of God in Christ (COGIC, 1907) — which has hosted political organizing, mutual aid, and education across the era.",
          "The U.S. Supreme Court.",
          "European royal courts."],
         1,
         "The Black church (AME 1816, AME Zion 1821, NBC 1895, COGIC 1907) has been the most consistent site of Black collective life — political, mutual aid, educational, cultural."),
        ("Historically Black Colleges and Universities (HBCUs) emerged primarily through:",
         ["A 21st-century federal initiative.",
          "Reconstruction-era founding by Black communities, the Freedmen's Bureau, and Northern missionary societies — Howard (1867), Fisk (1866), Hampton (1868), Morehouse (1867), Spelman (1881), Tuskegee (Booker T. Washington, 1881), and others — supplemented by the Second Morrill Act (1890), which created Black land-grant institutions in segregated Southern states.",
          "A purely 1960s federal program.",
          "Soviet-style state planning."],
         1,
         "HBCUs (Howard 1867, Fisk 1866, Hampton 1868, Morehouse 1867, Spelman 1881, Tuskegee 1881) emerged out of Reconstruction-era Black, Bureau, and missionary effort + the Second Morrill Act (1890)."),
        # Part 3
        ("Which dated example best illustrates Black political institution-building in the 20th century?",
         ["The 1964 founding of the Mississippi Freedom Democratic Party (MFDP), led by Fannie Lou Hamer, which challenged the all-white Mississippi delegation at the Democratic National Convention in Atlantic City and helped force the seating reforms that produced the Voting Rights Act of 1965 and the 1968 reform of the national Democratic Party.",
          "The 1789 ratification of the U.S. Constitution.",
          "The 1832 founding of the Whig Party.",
          "The 1854 founding of the Republican Party."],
         0,
         "The MFDP's 1964 challenge — led by Hamer — drove both VRA passage (1965) and the McGovern–Fraser reforms reshaping Democratic Party delegate selection (1968–72)."),
        ("Which 1989 election best illustrates the Black mayoral wave's expansion into Northeastern cities?",
         ["The election of Frederick Douglass as mayor of Boston, 1885.",
          "The election of David Dinkins as the first Black mayor of New York City in November 1989, following the earlier wave of Black mayors in Cleveland (Stokes 1967), Gary (Hatcher 1967), Detroit (Young 1973), Atlanta (Jackson 1973), and Los Angeles (Bradley 1973).",
          "The election of W. E. B. Du Bois as mayor of Atlanta, 1903.",
          "The 1991 election of Carol Moseley Braun as mayor of Chicago."],
         1,
         "David Dinkins's November 1989 election as NYC mayor extended the post-VRA Black mayoral wave (Stokes 1967, Hatcher 1967, Young 1973, Jackson 1973, Bradley 1973) to the Northeast."),
        # Part 4
        ("How does the practice of freedom connect to the Resistance & Abolition unit?",
         ["The two units cover unrelated topics.",
          "Antebellum Black freedom-making — independent Black churches (Allen's AME, 1816), schools (the African Free School, NYC, 1787), mutual-aid societies (the Free African Society, 1787), and the Black abolitionist press (the *Colored American*, 1837; Douglass's *North Star*, 1847) — established the institutional template of free-Black community-building that continues into the present.",
          "Free-Black institutions did not exist before 1865.",
          "Black abolitionists never built independent institutions."],
         1,
         "AP synthesis links antebellum Black institution-building (Free African Society 1787, AME 1816, African Free School 1787, *Colored American* 1837, *North Star* 1847) to the longer tradition of the practice of freedom."),
        ("Which AP analytical skill is most directly tested by comparing the antebellum Free African Society (1787) with the 20th-century Brotherhood of Sleeping Car Porters (1925)?",
         ["Memorization without comparison.",
          "Comparison: both were Black-led mutual-aid and political institutions — the Free African Society (Allen, Absalom Jones, Philadelphia, 1787) provided burial, sickness, and moral mutual aid; the BSCP (A. Philip Randolph, 1925) was the first Black-led union to win an AFL charter and a model for civil rights organizing — but at very different scales and aligned with different national political opportunities.",
          "Free recall of unrelated facts.",
          "Citing only modern sources."],
         1,
         "AP comparison rewards similarity (Black-led mutual aid + political organizing) *and* difference (local antebellum vs. national 20th-century union; pre-Civil-War vs. New Deal political context)."),
        # Part 5
        ("Which best describes a major change in Black electoral power in the 20th century?",
         ["Black voter participation declined steadily from 1900 to 2000.",
          "After Voting Rights Act enforcement (1965 and the 1975 language-minority amendments), Black officeholding rose from a few hundred elected officials in 1965 to roughly 10,500 by 2000 (per the Joint Center for Political and Economic Studies), including a wave of Black big-city mayors and the November 2008 election of Barack Obama, the first Black U.S. president, sworn in January 20, 2009.",
          "There were no Black elected officials between 1965 and 2008.",
          "Voter registration laws did not affect Black officeholding."],
         1,
         "Post-VRA, Black officeholding rose from a few hundred (1965) to ~10,500 (2000) and culminated in Obama's 2008 election (sworn Jan 20, 2009) — though not the end of racial hierarchy."),
        ("Which best describes a continuity across the practice of freedom from 1787 to the present?",
         ["Black freedom is fully secured by formal legal emancipation alone.",
          "Black freedom-making has consistently combined institution-building (church, school, press, mutual aid, union, party) with cultural production (music, literature, art) and political action (litigation, electoral, protest) — sustained across slavery, Reconstruction, Jim Crow, Civil Rights, Black Power, and the present.",
          "Black freedom requires no institutions.",
          "There is no continuity in Black political practice across centuries."],
         1,
         "Continuity = the multi-form practice of freedom — institutions + culture + political action — sustained from 1787 through the present, even as legal regimes changed."),
        # Part 6
        ("A student wants to analyze contemporary articulations of the practice of freedom. Which source is most directly useful?",
         ["A 21st-century pop-culture meme with no documentary basis.",
          "Patrisse Khan-Cullors and Asha Bandele's *When They Call You a Terrorist: A Black Lives Matter Memoir* (2018), Ta-Nehisi Coates's *Between the World and Me* (2015), Robin D. G. Kelley's *Freedom Dreams* (2002), and Michelle Alexander's *The New Jim Crow* (2010).",
          "An undated, anonymous flyer.",
          "A modern textbook with no primary excerpts."],
         1,
         "Khan-Cullors & Bandele 2018, Coates 2015, Kelley 2002, and Alexander 2010 are core contemporary primary/secondary sources for AP analysis of the practice of freedom."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point on Coates's *Between the World and Me* (2015)?",
         ["Quoting it without comment.",
          "Noting that Coates wrote the book as an open letter to his teenage son in the wake of the 2014 Ferguson and Staten Island police killings — and using that audience and immediate context to evaluate his treatment of bodily vulnerability and the Black tradition of writing letters to descendants (cf. James Baldwin, *The Fire Next Time*, 1963).",
          "Citing only the publication year with no analysis.",
          "Ignoring the post-Ferguson context."],
         1,
         "AP sourcing requires *use* of audience/purpose/situation — Coates's 2015 letter to his son after Ferguson 2014 (and his explicit Baldwin 1963 lineage) is essential context."),
        # Part 7
        ("Which is the strongest one-sentence thesis on the practice of freedom?",
         ["Black freedom matters.",
          "From the Free African Society (1787) and Allen's AME Church (1816) through Reconstruction-era HBCUs (1865–1881), Garveyite institutions (1914), the Brotherhood of Sleeping Car Porters (1925), the MFDP (1964), the Black mayoral wave (1967–1989), and Obama's 2008 election, African Americans have sustained a multi-generational practice of freedom — institution-building, cultural production, and political mobilization — that complements and extends formal legal emancipation.",
          "Black freedom was secured by legal emancipation alone.",
          "Black institution-building had no role in expanding freedom."],
         1,
         "Strong AP theses combine periodization, multi-generational scope, named institutions, and a complexity move (institution-building extending formal emancipation)."),
        ("On the AP exam, the strongest move when writing about the practice of freedom is to:",
         ["Avoid all dates and named institutions.",
          "Anchor claims in a named figure (Allen, Hamer, Randolph, Stokes, Dinkins, Obama, Coates), a dated event (1787 Free African Society, 1816 AME, 1925 BSCP, 1964 MFDP, 1967 first Black mayors, 2008 Obama), and a primary source (Du Bois 1903, Hamer 1964 DNC testimony, Coates 2015).",
          "Cite no sources at all.",
          "Use only 21st-century pop culture."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# 14. Contemporary Issues
# ────────────────────────────────────────────────────────────────────────────
T["aas-contemporary-issues"] = {
    "title": "Contemporary Issues",
    "prefix": "aasci",
    "qs": [
        # Part 1
        ("In AP African American Studies, \"mass incarceration\" most precisely refers to:",
         ["A short-lived 1990s policy with no demographic consequences.",
          "The dramatic post-1970 expansion of U.S. imprisonment — from roughly 200,000 prisoners in 1972 to roughly 2.3 million by the 2008 peak — that disproportionately affected Black Americans and that Michelle Alexander analyzes in *The New Jim Crow* (2010).",
          "A purely 19th-century convict-leasing system that ended in 1900.",
          "A federal program limited to white-collar crime."],
         1,
         "U.S. incarceration grew from ~200K (1972) to ~2.3M (2008) — disproportionately Black; Alexander, *The New Jim Crow* (2010), is the AP-cited overview."),
        ("The Black Lives Matter movement most precisely originated:",
         ["In a 1960s SCLC campaign.",
          "On July 13, 2013 with the #BlackLivesMatter hashtag created by Alicia Garza, Patrisse Khan-Cullors, and Opal Tometi after George Zimmerman's acquittal in the killing of Trayvon Martin (Feb 26, 2012); the movement scaled after the Aug 9, 2014 police killing of Michael Brown in Ferguson, Missouri.",
          "In a 1980s academic conference.",
          "In a 1990s legislative campaign."],
         1,
         "BLM was launched July 13, 2013 by Alicia Garza, Patrisse Khan-Cullors, and Opal Tometi after the Zimmerman acquittal; it scaled after Ferguson (Aug 9, 2014) and again after George Floyd (May 25, 2020)."),
        # Part 2
        ("Which 2013 Supreme Court decision most directly weakened Voting Rights Act enforcement?",
         ["*Brown v. Board of Education* (1954).",
          "*Shelby County v. Holder* (2013), in which Chief Justice John Roberts wrote a 5–4 opinion striking down the VRA's Section 4(b) coverage formula — effectively suspending Section 5 preclearance — and prompting a wave of state-level voter ID and other voting-rule changes in formerly covered jurisdictions.",
          "*Citizens United v. FEC* (2010).",
          "*Roe v. Wade* (1973)."],
         1,
         "*Shelby County v. Holder* (2013) struck down the VRA's Section 4(b) coverage formula, suspending Section 5 preclearance and triggering rapid state voting-rule changes in formerly covered jurisdictions."),
        ("Which 1994 federal law most directly contributed to the late-20th-century expansion of incarceration?",
         ["The Civil Rights Act of 1964.",
          "The Violent Crime Control and Law Enforcement Act of 1994 (the \"1994 Crime Bill\"), which funded 100,000 new police officers, expanded the federal death penalty, and authorized prison construction grants — building on earlier mandatory-minimum policies including the Anti-Drug Abuse Acts of 1986 and 1988 and the Reagan-era \"War on Drugs.\"",
          "The Wagner Act (1935).",
          "The Glass-Steagall Act (1933)."],
         1,
         "The 1994 Crime Bill — combined with the Anti-Drug Abuse Acts of 1986 and 1988 and Reagan-era \"War on Drugs\" — drove federal and state incarceration growth disproportionately affecting Black Americans."),
        # Part 3
        ("Which dated event most clearly catalyzed the 2020 wave of racial-justice protest?",
         ["The 1992 Los Angeles uprising.",
          "The May 25, 2020 police killing of George Floyd in Minneapolis — captured on Darnella Frazier's bystander video — which sparked protests in an estimated 2,000+ U.S. cities and roughly 60 countries through summer 2020 and prompted municipal and corporate policy reviews on policing and racial equity.",
          "The 1965 Watts uprising.",
          "The 1968 Tet Offensive."],
         1,
         "George Floyd's May 25, 2020 killing — recorded by Darnella Frazier — sparked the largest U.S. protest wave in modern history (~2,000+ cities) and global solidarity protests."),
        ("Which best characterizes Black wealth and income inequality in the early 21st century?",
         ["Black and white household wealth reached parity by 2020.",
          "Persistent racial wealth gaps documented by the Federal Reserve's Survey of Consumer Finances: in 2019, median white household wealth ($188,200) was roughly 7.8 times median Black household wealth ($24,100), reflecting cumulative effects of redlining (HOLC maps from 1935), GI Bill discrimination, exclusion from wealth-building federal programs, and ongoing labor-market and housing disparities.",
          "Black households held more wealth than white households by 2010.",
          "There is no measurable racial wealth gap in the 21st-century United States."],
         1,
         "Per the 2019 Survey of Consumer Finances: median white household wealth ($188,200) ≈ 7.8× median Black ($24,100) — a gap rooted in redlining (1935 HOLC), GI Bill discrimination, and ongoing labor and housing disparities (Mehrsa Baradaran, *The Color of Money*, 2017)."),
        # Part 4
        ("How does the Contemporary Issues unit connect to the Reconstruction & Jim Crow unit?",
         ["The two units cover unrelated material.",
          "Contemporary debates over voting rights (post-*Shelby County* 2013), policing, mass incarceration, school resegregation, and racial wealth gaps directly extend the issues of Reconstruction's incomplete project — what Eric Foner calls Reconstruction's \"unfinished revolution.\"",
          "Contemporary issues bear no relation to historical patterns.",
          "Reconstruction-era issues were entirely resolved before 1900."],
         1,
         "AP synthesis explicitly links contemporary issues (post-*Shelby* voting, mass incarceration, wealth gaps) to Reconstruction's \"unfinished revolution\" framing (Foner 1988)."),
        ("Which AP analytical skill is most directly tested by comparing the Civil Rights Movement era and the Black Lives Matter era?",
         ["Memorization without comparison.",
          "Comparison: shared mass mobilization against state-sanctioned anti-Black violence, but contrasting structures — Civil Rights' centralized male-led church-based organizations (SCLC, SNCC, NAACP) versus BLM's decentralized, networked, multi-issue organizing led prominently by Black women and queer organizers (Garza, Khan-Cullors, Tometi) — and contrasting media environments (television vs. social media + smartphone video).",
          "Free recall of unrelated events.",
          "Citing only modern sources."],
         1,
         "AP comparison rewards explicit similarity *and* difference — both confronted state violence; their organizational forms (centralized vs. networked), leadership composition (male-led vs. women/queer-led), and media (TV vs. smartphones/social media) differ."),
        # Part 5
        ("Which best describes a major change in racial demographics and politics in the 21st-century U.S.?",
         ["The U.S. became 90 percent white between 2000 and 2020.",
          "The 2020 U.S. Census measured the country's most racially and ethnically diverse population to date; in November 2008, Barack Obama became the first Black U.S. president (sworn in January 20, 2009); in November 2020, Kamala Harris became the first Black and South Asian U.S. vice president (sworn in January 20, 2021) — even as the post-Obama era saw renewed racialized political conflict.",
          "There has been no change in U.S. racial composition since 1900.",
          "No Black candidate has won a national-ticket office."],
         1,
         "The 2020 Census documented a diversifying population; Obama (elected Nov 2008, inaugurated Jan 20, 2009) and Harris (elected Nov 2020, inaugurated Jan 20, 2021) marked national-level firsts."),
        ("Which best describes a continuity from earlier eras into the contemporary period?",
         ["Black political mobilization ended in 1968.",
          "From the Reconstruction-era 14th Amendment EP Clause (1868) and 15th Amendment (1870) through the Civil Rights and Voting Rights Acts (1964/1965) and contemporary BLM and post-*Shelby* voting-rights organizing, Black political mobilization has consistently invoked constitutional citizenship claims while building grassroots and electoral institutions.",
          "Constitutional citizenship claims play no role in contemporary Black politics.",
          "There has been no continuity in Black political strategy."],
         1,
         "Continuity = constitutional citizenship claims (14th + 15th Amendments) + grassroots and electoral institution-building, sustained from Reconstruction through CRA/VRA and into BLM and post-*Shelby* organizing."),
        # Part 6
        ("A student wants to analyze contemporary critiques of mass incarceration. Which source is most directly useful?",
         ["A 21st-century reality-TV episode.",
          "Michelle Alexander's *The New Jim Crow: Mass Incarceration in the Age of Colorblindness* (2010), Bryan Stevenson's *Just Mercy* (2014), and Equal Justice Initiative reports including *Lynching in America* (2nd ed., 2017) — paired with Ava DuVernay's documentary *13th* (2016).",
          "An undated, anonymous social-media post.",
          "A modern textbook with no primary excerpts."],
         1,
         "Alexander 2010, Stevenson 2014, EJI's *Lynching in America* (2017), and DuVernay's *13th* (2016) are core contemporary AP-cited sources on mass incarceration and its history."),
        ("Which sourcing move would earn the AP DBQ \"sourcing\" point on Alexander's *The New Jim Crow* (2010)?",
         ["Quoting it without comment.",
          "Noting that Alexander, a civil rights attorney and former ACLU racial-justice director, published in 2010 — at the trough of post-Obama post-racial discourse and amid sustained 30-year incarceration growth — and using that author and timing to evaluate her argument that mass incarceration functions as a racial caste system analogous to Jim Crow.",
          "Citing only the publication year with no analysis.",
          "Ignoring her professional background and the political moment."],
         1,
         "AP sourcing requires *use* of author/audience/purpose/situation — Alexander's civil-rights legal background, the 2010 post-Obama moment, and the 30-year incarceration arc all shape her argument."),
        # Part 7
        ("Which is the strongest one-sentence thesis on contemporary issues?",
         ["Many contemporary issues affect Black Americans.",
          "From the post-1970 expansion of mass incarceration (Alexander 2010), through *Shelby County v. Holder* (2013), the rise of Black Lives Matter (2013, 2014, 2020), the Obama–Harris national-ticket firsts (2008, 2020), and persistent racial wealth gaps (2019 SCF: ~7.8×), contemporary African American politics simultaneously claims constitutional citizenship and grapples with the unfinished work of Reconstruction's racial-justice project.",
          "Contemporary racial issues are unrelated to historical patterns.",
          "There are no contemporary issues worth analyzing."],
         1,
         "Strong AP theses combine multiple contemporary domains, named events and figures, dated landmarks, and a complexity move (continuity with Reconstruction's unfinished project)."),
        ("On the AP exam, the strongest move when writing about contemporary issues is to:",
         ["Avoid all dates and named figures.",
          "Anchor claims in a named figure (Garza, Khan-Cullors, Tometi, Alexander, Stevenson, Obama, Harris), a dated event (1994 Crime Bill, 2008 Obama election, 2013 *Shelby* + #BlackLivesMatter, 2014 Ferguson, 2020 Floyd), and a primary source (Alexander 2010, Stevenson 2014, Coates 2015, Khan-Cullors 2018).",
          "Cite no sources at all.",
          "Use only 21st-century pop culture."],
         1,
         "AP rubrics consistently reward specificity — named figures, dated events, and primary sources — tied to a defensible thesis."),
    ],
}

if __name__ == "__main__":
    EXPECTED = {
        "aas-black-power-beyond",
        "aas-movements-debates",
        "aas-practice-freedom",
        "aas-contemporary-issues",
    }
    write_batch(T, EXPECTED)
