/**
 * Exit Quiz - AP Biology
 * 40 questions across core AP Bio domains.
 */

export interface ExitQuizQuestion {
  id: string
  question: string
  options: string[]
  correctIndex: number
  explanation: string
  category: string
}

interface BioQuestionTemplate {
  id: string
  topicSlug: string
  category: string
  question: string
  options: string[]
  correctIndex: number
  explanation: string
}

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

const questionPool: BioQuestionTemplate[] = [
  { id: 'bio-q1', topicSlug: 'ap-bio-chemistry-of-life', category: 'Chemistry of Life', question: 'Water is an excellent solvent primarily because it is:', options: ['Nonpolar', 'Polar', 'Acidic', 'Ionic'], correctIndex: 1, explanation: 'Water has partial positive and negative ends, so it can surround ions and other polar molecules.' },
  { id: 'bio-q2', topicSlug: 'ap-bio-chemistry-of-life', category: 'Chemistry of Life', question: 'Which macromolecule stores genetic information?', options: ['Carbohydrate', 'Lipid', 'Protein', 'Nucleic acid'], correctIndex: 3, explanation: 'DNA and RNA are nucleic acids that carry hereditary information.' },
  { id: 'bio-q3', topicSlug: 'ap-bio-cell-structure-function', category: 'Cell Structure', question: 'Which organelle modifies and packages proteins for secretion?', options: ['Ribosome', 'Golgi apparatus', 'Lysosome', 'Nucleus'], correctIndex: 1, explanation: 'The Golgi apparatus modifies, sorts, and packages proteins into vesicles.' },
  { id: 'bio-q4', topicSlug: 'ap-bio-cell-structure-function', category: 'Cell Structure', question: 'The fluid mosaic model describes the membrane as:', options: ['Rigid lipid sheet', 'Dynamic bilayer with mobile proteins', 'Single protein layer', 'Cell wall substitute'], correctIndex: 1, explanation: 'Phospholipids and proteins move laterally, creating a dynamic membrane.' },
  { id: 'bio-q5', topicSlug: 'ap-bio-membrane-transport', category: 'Membrane Transport', question: 'Diffusion of water across a semipermeable membrane is called:', options: ['Facilitated diffusion', 'Active transport', 'Osmosis', 'Endocytosis'], correctIndex: 2, explanation: 'Osmosis is specifically the diffusion of water.' },
  { id: 'bio-q6', topicSlug: 'ap-bio-membrane-transport', category: 'Membrane Transport', question: 'Active transport requires:', options: ['No energy input', 'ATP and membrane proteins', 'Only concentration gradient', 'Only channel proteins'], correctIndex: 1, explanation: 'Active transport moves substances against gradients and requires ATP.' },
  { id: 'bio-q7', topicSlug: 'ap-bio-cell-cycle-mitosis', category: 'Cell Cycle', question: 'DNA replication occurs during which phase?', options: ['G1', 'S', 'G2', 'M'], correctIndex: 1, explanation: 'The S phase is when DNA is synthesized.' },
  { id: 'bio-q8', topicSlug: 'ap-bio-cell-cycle-mitosis', category: 'Cell Cycle', question: 'Chromosomes align at the cell equator during:', options: ['Prophase', 'Metaphase', 'Anaphase', 'Telophase'], correctIndex: 1, explanation: 'Metaphase lines chromosomes up at the metaphase plate.' },
  { id: 'bio-q9', topicSlug: 'ap-bio-cell-communication', category: 'Cell Communication', question: 'A ligand typically binds to a:', options: ['Chromosome', 'Receptor protein', 'Ribosome', 'Centromere'], correctIndex: 1, explanation: 'Signals are received when ligands bind receptor proteins.' },
  { id: 'bio-q10', topicSlug: 'ap-bio-cell-communication', category: 'Cell Communication', question: 'Amplification in signal transduction means:', options: ['Signal gets weaker', 'One receptor activates many downstream molecules', 'Signal stops at membrane', 'No second messengers are used'], correctIndex: 1, explanation: 'One event can trigger many events, increasing response magnitude.' },
  { id: 'bio-q11', topicSlug: 'ap-bio-cellular-energetics', category: 'Cellular Energetics', question: 'ATP is produced in greatest quantity during:', options: ['Glycolysis', 'Citric acid cycle', 'Oxidative phosphorylation', 'Fermentation'], correctIndex: 2, explanation: 'Most ATP in aerobic respiration is generated by oxidative phosphorylation.' },
  { id: 'bio-q12', topicSlug: 'ap-bio-cellular-energetics', category: 'Cellular Energetics', question: 'The final electron acceptor in aerobic respiration is:', options: ['CO2', 'O2', 'NAD+', 'Pyruvate'], correctIndex: 1, explanation: 'Oxygen accepts electrons at the end of the electron transport chain.' },
  { id: 'bio-q13', topicSlug: 'ap-bio-photosynthesis', category: 'Photosynthesis', question: 'The Calvin cycle takes place in the:', options: ['Thylakoid lumen', 'Stroma', 'Mitochondrial matrix', 'Cytosol'], correctIndex: 1, explanation: 'Carbon fixation reactions occur in the chloroplast stroma.' },
  { id: 'bio-q14', topicSlug: 'ap-bio-photosynthesis', category: 'Photosynthesis', question: 'The main pigment that absorbs light in photosynthesis is:', options: ['Chlorophyll a', 'Carotene', 'Xanthophyll', 'Phycobilin'], correctIndex: 0, explanation: 'Chlorophyll a is the primary photosynthetic pigment.' },
  { id: 'bio-q15', topicSlug: 'ap-bio-meiosis', category: 'Meiosis', question: 'Crossing over occurs during:', options: ['Prophase I', 'Metaphase I', 'Anaphase II', 'Telophase II'], correctIndex: 0, explanation: 'Homologous chromosomes exchange segments during prophase I.' },
  { id: 'bio-q16', topicSlug: 'ap-bio-meiosis', category: 'Meiosis', question: 'Independent assortment contributes to genetic variation by:', options: ['Copying DNA inaccurately', 'Random orientation of homologous pairs', 'Mutating every gene', 'Increasing chromosome number'], correctIndex: 1, explanation: 'Homologous pairs orient randomly at metaphase I.' },
  { id: 'bio-q17', topicSlug: 'ap-bio-mendelian-genetics', category: 'Genetics', question: 'A heterozygous genotype is represented as:', options: ['AA', 'aa', 'Aa', 'A0'], correctIndex: 2, explanation: 'Heterozygous means two different alleles.' },
  { id: 'bio-q18', topicSlug: 'ap-bio-mendelian-genetics', category: 'Genetics', question: 'In a monohybrid cross Aa x Aa, the expected genotype ratio is:', options: ['1:1', '3:1', '1:2:1', '9:3:3:1'], correctIndex: 2, explanation: 'Punnett outcomes are AA, Aa, Aa, aa.' },
  { id: 'bio-q19', topicSlug: 'ap-bio-molecular-genetics', category: 'Molecular Genetics', question: 'Transcription produces:', options: ['Protein from mRNA', 'DNA from RNA', 'RNA from DNA', 'ATP from glucose'], correctIndex: 2, explanation: 'Transcription copies DNA information into RNA.' },
  { id: 'bio-q20', topicSlug: 'ap-bio-molecular-genetics', category: 'Molecular Genetics', question: 'The codon AUG typically codes for:', options: ['Stop', 'Methionine/start', 'Leucine', 'Tryptophan'], correctIndex: 1, explanation: 'AUG serves as the common start codon and encodes methionine.' },
  { id: 'bio-q21', topicSlug: 'ap-bio-gene-regulation', category: 'Gene Regulation', question: 'In the lac operon, lactose presence generally:', options: ['Activates repressor binding', 'Inhibits repressor and allows transcription', 'Stops RNA polymerase permanently', 'Destroys promoter'], correctIndex: 1, explanation: 'Allolactose inactivates the repressor, allowing transcription.' },
  { id: 'bio-q22', topicSlug: 'ap-bio-gene-regulation', category: 'Gene Regulation', question: 'Epigenetic modifications can change:', options: ['DNA sequence directly', 'Gene expression patterns', 'Chromosome count', 'Species identity'], correctIndex: 1, explanation: 'Epigenetic marks alter gene expression without changing sequence.' },
  { id: 'bio-q23', topicSlug: 'ap-bio-natural-selection', category: 'Evolution', question: 'Natural selection acts on:', options: ['Genotypes only', 'Phenotypes in populations', 'Individual intentions', 'Mutations before they occur'], correctIndex: 1, explanation: 'Selection filters phenotypes, changing allele frequencies over generations.' },
  { id: 'bio-q24', topicSlug: 'ap-bio-natural-selection', category: 'Evolution', question: 'Genetic drift is strongest in:', options: ['Very large populations', 'Small populations', 'Only plants', 'Only bacteria'], correctIndex: 1, explanation: 'Random fluctuations have larger effects in small populations.' },
  { id: 'bio-q25', topicSlug: 'ap-bio-ecology-energy-flow', category: 'Ecology', question: 'Only about what fraction of energy is transferred between trophic levels?', options: ['1%', '10%', '50%', '90%'], correctIndex: 1, explanation: 'Roughly 10% transfers upward, with losses mostly as heat.' },
  { id: 'bio-q26', topicSlug: 'ap-bio-ecology-energy-flow', category: 'Ecology', question: 'Primary producers are typically:', options: ['Carnivores', 'Autotrophs', 'Decomposers only', 'Top predators'], correctIndex: 1, explanation: 'Autotrophs capture energy and form the base of food webs.' },
  { id: 'bio-q27', topicSlug: 'ap-bio-population-ecology', category: 'Population Ecology', question: 'Carrying capacity is the:', options: ['Minimum population size', 'Maximum sustainable population in an environment', 'Growth rate constant', 'Birth rate only'], correctIndex: 1, explanation: 'Carrying capacity reflects environmental limits on population size.' },
  { id: 'bio-q28', topicSlug: 'ap-bio-population-ecology', category: 'Population Ecology', question: 'A density-dependent limiting factor is:', options: ['Hurricane', 'Earthquake', 'Disease', 'Volcanic eruption'], correctIndex: 2, explanation: 'Disease spread typically increases with population density.' },
  { id: 'bio-q29', topicSlug: 'ap-bio-immune-system', category: 'Physiology', question: 'Antibodies are produced by:', options: ['T-helper cells', 'Plasma B cells', 'Macrophages', 'Neutrophils'], correctIndex: 1, explanation: 'Differentiated B cells (plasma cells) secrete antibodies.' },
  { id: 'bio-q30', topicSlug: 'ap-bio-immune-system', category: 'Physiology', question: 'A vaccine primarily works by:', options: ['Killing all pathogens instantly', 'Providing passive antibodies only', 'Generating memory immune responses', 'Increasing body temperature'], correctIndex: 2, explanation: 'Vaccines prime adaptive immunity and memory cell formation.' },
  { id: 'bio-q31', topicSlug: 'ap-bio-biotechnology', category: 'Biotechnology', question: 'PCR is used to:', options: ['Translate proteins', 'Amplify DNA', 'Sequence proteins', 'Measure ATP directly'], correctIndex: 1, explanation: 'Polymerase chain reaction amplifies selected DNA regions.' },
  { id: 'bio-q32', topicSlug: 'ap-bio-biotechnology', category: 'Biotechnology', question: 'Restriction enzymes are useful because they:', options: ['Add nucleotides randomly', 'Cut DNA at specific sequences', 'Repair all mutations', 'Convert RNA to protein'], correctIndex: 1, explanation: 'They cleave DNA at defined recognition sites.' },
  { id: 'bio-q33', topicSlug: 'ap-bio-experimental-design', category: 'Scientific Practices', question: 'The dependent variable is the variable that is:', options: ['Manipulated by researcher', 'Measured as a response', 'Kept constant', 'Always qualitative'], correctIndex: 1, explanation: 'Dependent variables are outcomes measured after manipulating the independent variable.' },
  { id: 'bio-q34', topicSlug: 'ap-bio-experimental-design', category: 'Scientific Practices', question: 'A valid control group helps researchers:', options: ['Increase bias', 'Establish a baseline comparison', 'Avoid replication', 'Remove all uncertainty'], correctIndex: 1, explanation: 'Controls isolate the effect of the tested variable.' },
  { id: 'bio-q35', topicSlug: 'ap-bio-cellular-energetics', category: 'Cellular Energetics', question: 'Fermentation allows glycolysis to continue by regenerating:', options: ['ATP', 'NAD+', 'FADH2', 'Pyruvate'], correctIndex: 1, explanation: 'Fermentation oxidizes NADH back to NAD+, allowing glycolysis to proceed.' },
  { id: 'bio-q36', topicSlug: 'ap-bio-molecular-genetics', category: 'Molecular Genetics', question: 'A nonsense mutation usually results in:', options: ['A longer protein', 'No change in sequence', 'Premature stop codon', 'Only intron expansion'], correctIndex: 2, explanation: 'Nonsense mutations convert an amino acid codon into a stop codon.' },
  { id: 'bio-q37', topicSlug: 'ap-bio-evolution-evidence', category: 'Evolution', question: 'Homologous structures are evidence for:', options: ['Convergent evolution only', 'Common ancestry', 'No evolutionary relationship', 'Only genetic drift'], correctIndex: 1, explanation: 'Shared structural patterns suggest descent from a common ancestor.' },
  { id: 'bio-q38', topicSlug: 'ap-bio-evolution-evidence', category: 'Evolution', question: 'Hardy-Weinberg equilibrium assumes all EXCEPT:', options: ['Random mating', 'No selection', 'Large population', 'Frequent directional selection'], correctIndex: 3, explanation: 'Directional selection violates Hardy-Weinberg assumptions.' },
  { id: 'bio-q39', topicSlug: 'ap-bio-ecology-interactions', category: 'Ecology', question: 'Mutualism is an interaction in which:', options: ['One benefits and one is harmed', 'Both species benefit', 'Neither species benefits', 'Both are harmed'], correctIndex: 1, explanation: 'Mutualistic interactions increase fitness for both species.' },
  { id: 'bio-q40', topicSlug: 'ap-bio-ecology-interactions', category: 'Ecology', question: 'An invasive species often causes ecological concern because it may:', options: ['Always increase biodiversity', 'Outcompete native species', 'Only affect abiotic factors', 'Reduce evolution rates to zero'], correctIndex: 1, explanation: 'Invasive species can displace natives and disrupt food webs.' },
]

export function generateExitQuiz(count: number = 10, topicSlug?: string): ExitQuizQuestion[] {
  const pool = topicSlug
    ? questionPool.filter((q) => q.topicSlug === topicSlug)
    : questionPool

  const source = pool.length > 0 ? pool : questionPool
  return shuffle(source)
    .slice(0, count)
    .map((q) => ({
      id: q.id,
      question: q.question,
      options: q.options,
      correctIndex: q.correctIndex,
      explanation: q.explanation,
      category: q.category,
    }))
}
